import type { Problem } from "@/types/content";

export const binarySearchEatingSpeed: Problem = {
  id: "c:binary-search-eating-speed",
  slug: "binary-search-eating-speed",
  source: "curated",
  topic: "binary-search",
  level: 3,
  title: "도토리 먹는 속도",
  summary: "속도 k로 h시간 안에 다 먹을 수 있는지 확인하며 가장 느린 k를 찾아요",
  statement: [
    "다람쥐가 도토리 더미 `piles`를 `hours`시간 안에 다 먹으려고 해요. 한 시간에 **한 더미**를 골라 최대 `k`개를 먹어요. 더미에 k개보다 적게 남았으면 그 시간엔 그것만 먹고 쉬어요.",
    "",
    "제시간에 다 먹을 수 있는 **가장 느린 속도 k**(정수)를 반환해 주세요. `hours`는 항상 더미 수 이상이에요.",
  ].join("\n"),
  inputFormat: "`piles`: 더미마다 도토리 수, `hours`: 주어진 시간이에요.",
  outputFormat: "가장 느린 속도 k",
  constraints: ["1 ≤ piles의 길이 ≤ 10,000", "1 ≤ 도토리 수 ≤ 1,000,000,000", "piles의 길이 ≤ hours ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "piles",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "더미별 도토리 수",
      },
      { name: "hours", type: { python: "int", javascript: "number", java: "int" }, description: "주어진 시간" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 느린 속도" },
  },
  starterCode: {
    python: ["def solution(piles, hours):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(piles, hours) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] piles, int hours) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[3, 6, 7, 11], 8],
      expected: 4,
      explanation: "k = 4면 1 + 2 + 2 + 3 = 8시간이에요. 3이면 10시간이라 늦어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[30, 11, 23, 4, 20], 5],
      expected: 30,
      explanation: "더미 수와 시간이 같으면 가장 큰 더미를 한 시간에 먹어야 해서 30이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[1], 1000],
      expected: 1,
      failureNote: "시간이 넉넉하면 1이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[30, 11, 23, 4, 20], 6],
      expected: 23,
      failureNote: "k = 23이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[10], 3],
      expected: 4,
      failureNote:
        "한 시간에 4개씩이면 4 + 4 + 2로 3시간이에요. 10 ÷ 3을 내림하면(3) 4시간이 걸려요. 올림으로 세야 해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 10000 }, (_, i) => ((i * 104729) % 1000000000) + 1), 1000000],
      expected: 4808985,
      failureNote: "더미 1만 개, 최대 10억 개예요. 속도를 1부터 하나씩 올리면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'제시간에 되는 **가장 느린** 속도' → 속도가 빠를수록 시간은 줄어요. 불가능 → 가능이 한 번 바뀌니 **답을 이분 탐색**해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 속도 범위는 1 ~ 가장 큰 더미예요. (그보다 빨라도 한 더미에 한 시간이에요)",
        "2. 속도 `mid`로 걸리는 시간 = 더미마다 `ceil(p / mid)`의 합이에요. 올림은 `(p + mid - 1) // mid`로 계산해요.",
        "3. hours 이하면 가능 → 답으로 적고 더 느리게(`hi = mid - 1`). 아니면 더 빠르게.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "lo, hi = 1, max(piles)",
        "while lo <= hi:",
        "    mid = (lo + hi) // 2",
        "    need = sum((p + mid - 1) // mid for p in piles)",
        "    if need <= hours: answer = mid; hi = mid - 1",
        "    else: lo = mid + 1",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["걸리는 시간을 계산하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "need = sum(______ for p in piles)",
            "if need <= hours:",
            "    answer = mid",
            "    hi = mid - 1",
            "else:",
            "    lo = mid + 1",
          ].join("\n"),
          javascript: [
            "let need = 0;",
            "for (const p of piles) need += ______;",
            "if (need <= hours) {",
            "  answer = mid;",
            "  hi = mid - 1;",
            "} else lo = mid + 1;",
          ].join("\n"),
          java: [
            "long need = 0;",
            "for (int p : piles) need += ______;",
            "if (need <= hours) {",
            "    answer = mid;",
            "    hi = mid - 1;",
            "} else lo = mid + 1;",
          ].join("\n"),
        },
        caption: "올림 나눗셈은 (p + mid - 1) / mid예요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["parametric-search"],
  signalIds: ["sig-max-min-answer", "sig-huge-range"],
  estimatedMinutes: 15,
  xp: 30,
};
