import type { Problem } from "@/types/content";

export const binarySearchLanternSpacing: Problem = {
  id: "c:binary-search-lantern-spacing",
  slug: "binary-search-lantern-spacing",
  source: "curated",
  topic: "binary-search",
  level: 4,
  title: "등불 멀리 떨어뜨려 달기",
  summary: "'간격 D 이상으로 c개를 달 수 있나?'를 확인하며 D를 이분 탐색해요",
  statement: [
    "숲길에 등불을 걸 수 있는 고리가 `hooks` 위치마다 있어요. 등불 `c`개를 서로 다른 고리에 걸 때, **가장 가까운 두 등불 사이의 거리**를 최대한 크게 하고 싶어요.",
    "",
    "그 거리의 최댓값을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`hooks`: 고리 위치(서로 다름, 순서 없음), `c`: 등불 수예요.",
  outputFormat: "가장 가까운 두 등불 사이 거리의 최댓값",
  constraints: ["2 ≤ hooks의 길이 ≤ 10,000", "0 ≤ 위치 ≤ 1,000,000,000", "2 ≤ c ≤ hooks의 길이"],
  signature: {
    name: "solution",
    params: [
      { name: "hooks", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "고리 위치" },
      { name: "c", type: { python: "int", javascript: "number", java: "int" }, description: "등불 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 간격의 최댓값" },
  },
  starterCode: {
    python: ["def solution(hooks, c):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(hooks, c) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] hooks, int c) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[1, 2, 8, 4, 9], 3],
      expected: 3,
      explanation: "1, 4, 8(또는 9)에 걸면 가장 가까운 거리가 3이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[0, 100], 2],
      expected: 100,
      explanation: "양 끝에 걸면 100이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3, 4, 5], 5],
      expected: 1,
      failureNote: "모든 고리에 걸어야 해서 1이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[9, 1, 5], 2],
      expected: 8,
      failureNote: "고리 위치가 정렬돼 있지 않아요. 먼저 정렬하세요. 1과 9에 걸어 8이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[0, 3, 4, 7, 10], 3],
      expected: 4,
      failureNote: "0, 4, 10에 걸면 가장 가까운 거리가 4예요. 5 이상으로는 3개를 못 걸어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "edge",
      args: [[0, 1000000000, 500000000], 3],
      expected: 500000000,
      failureNote: "5억 간격이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 10000 }, (_, i) => ((i * 37) % 10000) * 7919), 100],
      expected: 799819,
      failureNote: "고리 1만 개예요. 등불을 거는 방법을 모두 해 보는 건 불가능해요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'가장 가까운 거리를 **최대로**' → **최소의 최대** 문제예요. '간격 D 이상으로 c개를 걸 수 있나?'를 확인하며 D를 **이분 탐색**해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "확인은 욕심껏: 정렬한 고리에서 **첫 고리**에 걸고, 마지막으로 건 곳에서 D 이상 떨어진 첫 고리마다 걸어요. 건 개수가 c 이상이면 가능해요.",
        "",
        "1. 고리를 정렬해요.",
        "2. D의 범위는 1 ~ (마지막 − 처음)이에요.",
        "3. 가능하면 답으로 적고 더 크게, 아니면 더 작게.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "h = hooks를 정렬",
        "def count(D):",
        "    placed, last = 1, h[0]",
        "    for x in h[1:]:",
        "        if x - last >= D: placed += 1; last = x",
        "    return placed",
        "D를 1 ~ h[-1] - h[0]에서 이분 탐색: count(D) >= c 이면 가능",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["등불을 걸지 정하는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def count(d):",
            "    placed, last = 1, h[0]",
            "    for x in h[1:]:",
            "        if ______:",
            "            placed += 1",
            "            last = x",
            "    return placed",
          ].join("\n"),
          javascript: [
            "const count = (d) => {",
            "  let placed = 1, last = h[0];",
            "  for (let i = 1; i < h.length; i++) {",
            "    if (______) {",
            "      placed++;",
            "      last = h[i];",
            "    }",
            "  }",
            "  return placed;",
            "};",
          ].join("\n"),
          java: [
            "int count(int[] h, int d) {",
            "    int placed = 1, last = h[0];",
            "    for (int i = 1; i < h.length; i++) {",
            "        if (______) {",
            "            placed++;",
            "            last = h[i];",
            "        }",
            "    }",
            "    return placed;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["parametric-search"],
  signalIds: ["sig-max-min-answer"],
  estimatedMinutes: 20,
  xp: 40,
};
