import type { Problem } from "@/types/content";

export const binarySearchRisingPath: Problem = {
  id: "c:binary-search-rising-path",
  slug: "binary-search-rising-path",
  source: "curated",
  topic: "binary-search",
  level: 5,
  title: "점점 높아지는 징검다리",
  summary: "길이별 가장 작은 끝값을 기록하고, 이분 탐색으로 바꿀 자리를 찾아요 (LIS)",
  statement: [
    "개울에 징검돌이 한 줄로 놓여 있고, `stones[i]`는 i번째 돌의 높이예요. 노디는 **앞에서 뒤로만** 건너면서, 밟는 돌이 **점점 높아지게**(같은 높이는 안 돼요) 몇 개를 골라 밟으려고 해요. 돌은 건너뛰어도 돼요.",
    "",
    "밟을 수 있는 돌의 **최대 개수**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`stones`: 돌의 높이들이에요.",
  outputFormat: "밟을 수 있는 돌의 최대 개수",
  constraints: ["1 ≤ stones의 길이 ≤ 100,000", "0 ≤ 높이 ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "stones", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "돌 높이" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 개수" },
  },
  starterCode: {
    python: ["def solution(stones):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(stones) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] stones) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[10, 9, 2, 5, 3, 7, 101, 18]],
      expected: 4,
      explanation: "2, 3, 7, 18(또는 101)을 밟으면 4개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[7, 7, 7]],
      expected: 1,
      explanation: "같은 높이는 이어서 밟을 수 없어서 1개예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5]],
      expected: 1,
      failureNote: "돌 하나면 1개예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3, 4]],
      expected: 4,
      failureNote: "모두 밟을 수 있어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[4, 3, 2, 1]],
      expected: 1,
      failureNote: "점점 낮아지면 1개뿐이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [[0, 8, 4, 12, 2, 10, 6, 14, 1, 9]],
      expected: 4,
      failureNote:
        "0, 4, 6, 9(또는 0, 4, 10, 14 …)로 4개예요. 'x 이상인 첫 자리'를 바꿔야 같은 높이가 두 번 들어가지 않아요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i * 7919) % 100003)],
      expected: 306,
      failureNote: "돌 10만 개예요. 돌마다 앞의 모든 돌을 보면(O(N²)) 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "**가장 긴 증가 부분 수열**(LIS)이에요. N이 10만이라 O(N²)은 느려요. '길이별 가장 작은 끝값' 목록을 두고 **이분 탐색**하면 O(N log N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`tails[L]` = 길이 L+1인 증가 수열 중 **끝값이 가장 작은** 것의 끝값이에요. 이 목록은 항상 정렬돼 있어요.",
        "",
        "돌 x마다:",
        "",
        "1. `tails`에서 **x 이상인 첫 자리** i를 찾아요 (lower bound).",
        "2. i가 끝이면 x를 붙여요 (더 긴 수열이 생겼어요).",
        "3. 아니면 `tails[i] = x`로 바꿔요 (같은 길이인데 끝이 더 작아져 앞으로 더 유리해요).",
        "",
        "답은 `tails`의 길이예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "tails = []",
        "for x in stones:",
        "    i = lower_bound(tails, x)",
        "    if i == len(tails): tails에 x 추가",
        "    else: tails[i] = x",
        "return len(tails)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["자리를 찾아 바꾸는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "from bisect import bisect_left",
            "",
            "tails = []",
            "for x in stones:",
            "    i = ______",
            "    if i == len(tails):",
            "        tails.append(x)",
            "    else:",
            "        tails[i] = x",
          ].join("\n"),
          javascript: [
            "const tails = [];",
            "for (const x of stones) {",
            "  let lo = 0, hi = tails.length;",
            "  while (lo < hi) {",
            "    const mid = (lo + hi) >> 1;",
            "    if (______) hi = mid;",
            "    else lo = mid + 1;",
            "  }",
            "  tails[lo] = x;",
            "}",
          ].join("\n"),
          java: [
            "int[] tails = new int[stones.length];",
            "int size = 0;",
            "for (int x : stones) {",
            "    int lo = 0, hi = size;",
            "    while (lo < hi) {",
            "        int mid = (lo + hi) >>> 1;",
            "        if (______) hi = mid;",
            "        else lo = mid + 1;",
            "    }",
            "    tails[lo] = x;",
            "    if (lo == size) size++;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["boundary-search"],
  signalIds: ["sig-first-true"],
  estimatedMinutes: 30,
  xp: 50,
};
