import type { Problem } from "@/types/content";

export const binarySearchSplitBooks: Problem = {
  id: "c:binary-search-split-books",
  slug: "binary-search-split-books",
  source: "curated",
  topic: "binary-search",
  level: 4,
  title: "책 나눠 읽기",
  summary: "'한 사람이 X쪽까지 읽으면 k명 안에 나눠지나?'를 확인하며 X를 이분 탐색해요",
  statement: [
    "숲속 독서 모임에서 책 N권을 **순서대로** k명이 나눠 읽어요. 한 사람은 **연속한** 책들을 맡고, 모든 책을 누군가 맡아야 해요. 책은 쪼갤 수 없어요.",
    "",
    "가장 많이 읽는 사람의 **쪽수 합을 최소**로 할 때, 그 쪽수 합을 반환해 주세요. 아무 책도 안 맡는 사람이 있어도 괜찮아요.",
  ].join("\n"),
  inputFormat: "`pages`: 순서대로 놓인 책의 쪽수, `k`: 사람 수예요.",
  outputFormat: "가장 많이 읽는 사람의 쪽수 합의 최솟값",
  constraints: ["1 ≤ pages의 길이 ≤ 10,000", "1 ≤ 쪽수 ≤ 10,000", "1 ≤ k ≤ pages의 길이"],
  signature: {
    name: "solution",
    params: [
      { name: "pages", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "책 쪽수" },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "사람 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 쪽수 합의 최솟값" },
  },
  starterCode: {
    python: ["def solution(pages, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(pages, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] pages, int k) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[7, 2, 5, 10, 8], 2],
      expected: 18,
      explanation: "[7, 2, 5] / [10, 8]로 나누면 14와 18, 18이 가장 작아요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[1, 2, 3], 3],
      expected: 3,
      explanation: "한 권씩 맡으면 가장 두꺼운 3이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5, 5, 5], 1],
      expected: 15,
      failureNote: "혼자 다 읽으면 합 15예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 4, 4], 3],
      expected: 4,
      failureNote: "답은 가장 두꺼운 책(4)보다 작을 수 없어요. 범위의 시작은 max(pages)예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3, 4, 5], 2],
      expected: 9,
      failureNote: "[1, 2, 3] / [4, 5]로 9예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[10, 20, 30, 40], 2],
      expected: 60,
      failureNote: "[10, 20, 30] / [40]으로 60이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 10000 }, (_, i) => ((i * 37) % 10000) + 1), 37],
      expected: 1353916,
      failureNote: "책 1만 권이에요. 나누는 방법을 모두 해 보는 건 불가능해요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'가장 많은 것을 **최소로**' → **최대의 최소** 문제예요. '한 사람이 X쪽까지만 읽으면 k명으로 되나?'를 확인하며 X를 **이분 탐색**해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "X를 정하면 확인은 욕심껏(greedy) 하면 돼요: 앞에서부터 책을 담다가 X를 넘으면 다음 사람에게 넘겨요. 필요한 사람 수가 k 이하면 가능해요.",
        "",
        "1. X의 범위는 `max(pages)` ~ `sum(pages)`예요.",
        "2. 가능하면 답으로 적고 더 작게, 아니면 더 크게.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "def people(X):",
        "    count, cur = 1, 0",
        "    for p in pages:",
        "        if cur + p > X: count += 1; cur = 0",
        "        cur += p",
        "    return count",
        "lo, hi = max(pages), sum(pages)",
        "X를 이분 탐색: people(X) <= k 이면 가능",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["필요한 사람 수를 세는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def people(x):",
            "    count, cur = 1, 0",
            "    for p in pages:",
            "        if ______:",
            "            count += 1",
            "            cur = 0",
            "        cur += p",
            "    return count",
          ].join("\n"),
          javascript: [
            "const people = (x) => {",
            "  let count = 1, cur = 0;",
            "  for (const p of pages) {",
            "    if (______) {",
            "      count++;",
            "      cur = 0;",
            "    }",
            "    cur += p;",
            "  }",
            "  return count;",
            "};",
          ].join("\n"),
          java: [
            "int people(int[] pages, long x) {",
            "    int count = 1;",
            "    long cur = 0;",
            "    for (int p : pages) {",
            "        if (______) {",
            "            count++;",
            "            cur = 0;",
            "        }",
            "        cur += p;",
            "    }",
            "    return count;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["parametric-search"],
  signalIds: ["sig-max-min-answer"],
  estimatedMinutes: 20,
  xp: 40,
};
