import type { Problem } from "@/types/content";

export const binarySearchSquareGarden: Problem = {
  id: "c:binary-search-square-garden",
  slug: "binary-search-square-garden",
  source: "curated",
  topic: "binary-search",
  level: 1,
  title: "가장 큰 정사각형 꽃밭",
  summary: "x × x ≤ n인 가장 큰 x를 수의 범위에서 이분 탐색해요",
  statement: [
    "노디에게 꽃모종이 `n`개 있어요. 모종을 한 칸에 하나씩 심어 **정사각형** 꽃밭(x × x칸)을 만들려고 해요.",
    "",
    "만들 수 있는 가장 큰 정사각형의 한 변 `x`를 반환해 주세요. 즉 `x × x ≤ n`인 가장 큰 정수 x예요. 모종이 없으면 0이에요.",
    "",
    "제곱근 함수(`sqrt`, `isqrt`) 없이 풀어 보세요.",
  ].join("\n"),
  inputFormat: "`n`: 꽃모종 수예요.",
  outputFormat: "정사각형 한 변의 최대 길이",
  constraints: ["0 ≤ n ≤ 1,000,000,000,000"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "long" }, description: "꽃모종 수" }],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "한 변의 길이" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(long n) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [20],
      expected: 4,
      explanation: "4 × 4 = 16 ≤ 20, 5 × 5 = 25 > 20이라 4예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [36],
      expected: 6,
      explanation: "딱 맞으면 6이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [0],
      expected: 0,
      failureNote: "모종이 없으면 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [1],
      expected: 1,
      failureNote: "1 × 1이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [99],
      expected: 9,
      failureNote: "10 × 10 = 100은 넘어서 9예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [1000000000000],
      expected: 1000000,
      failureNote:
        "1조면 답은 100만이에요. 1부터 하나씩 늘려 보면 느리고, 반씩 줄이면 약 40번이에요. (Java는 x × x를 long으로 계산하세요)",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "tricky",
      args: [999999999999],
      expected: 999999,
      failureNote: "100만² − 1이라 999,999예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["x가 커질수록 `x × x ≤ n`이 **참 → 거짓**으로 한 번만 바뀌어요 → 수의 범위에서 **이분 탐색**해요."].join(
        "\n",
      ),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 답은 0 ~ n 사이(또는 0 ~ 1,000,000)예요. `lo = 0`, `hi = n`.",
        "2. `mid × mid ≤ n`이면 mid는 가능해요. 답으로 적고 더 크게(`lo = mid + 1`).",
        "3. 아니면 너무 커요. `hi = mid - 1`.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "lo, hi, answer = 0, n, 0",
        "while lo <= hi:",
        "    mid = (lo + hi) // 2",
        "    if mid * mid <= n: answer = mid; lo = mid + 1",
        "    else: hi = mid - 1",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["가능할 때의 처리예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while lo <= hi:",
            "    mid = (lo + hi) // 2",
            "    if mid * mid <= n:",
            "        answer = mid",
            "        ______",
            "    else:",
            "        hi = mid - 1",
          ].join("\n"),
          javascript: [
            "while (lo <= hi) {",
            "  const mid = Math.floor((lo + hi) / 2);",
            "  if (mid * mid <= n) {",
            "    answer = mid;",
            "    ______;",
            "  } else hi = mid - 1;",
            "}",
          ].join("\n"),
          java: [
            "while (lo <= hi) {",
            "    long mid = (lo + hi) / 2;",
            "    if (mid * mid <= n) {",
            "        answer = mid;",
            "        ______;",
            "    } else hi = mid - 1;",
            "}",
          ].join("\n"),
        },
        caption: "hi를 100만으로 두면 mid × mid가 long을 넘지 않아요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["parametric-search"],
  signalIds: ["sig-huge-range"],
  estimatedMinutes: 10,
  xp: 10,
};
