import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[20, 15, 10, 17], 7],
    expected: 15,
    explanation: "H = 15면 5 + 0 + 0 + 2 = 7이에요. 16이면 4 + 1 = 5라 모자라요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[10], 10],
    expected: 0,
    explanation: "나무를 통째로 가져가야 해서 0이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[10], 1],
    expected: 9,
    failureNote: "1만 가져가면 되니까 9예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [[4, 42, 40, 26, 46], 20],
    expected: 36,
    failureNote: "H = 36이면 6 + 4 + 10 = 20으로 딱 맞아요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [[5, 5, 5, 5], 8],
    expected: 3,
    failureNote: "H = 3이면 2씩 4그루로 8이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 10000 }, (_, i) => ((i * 7919) % 1000000000) + 1), 2000000000],
    expected: 73557897,
    failureNote: "나무 1만 그루, 높이 최대 10억이에요. 높이를 하나씩 내려 보면 시간 초과예요. (Java는 합을 long으로)",
  },
]);

export const binarySearchTreeSaw: Problem = {
  id: "c:binary-search-tree-saw",
  slug: "binary-search-tree-saw",
  source: "curated",
  topic: "binary-search",
  level: 3,
  title: "나무 톱 높이 정하기",
  summary: "톱 높이 H를 이분 탐색하며 얻는 나무 양이 m 이상인지 확인해요",
  statement: [
    "노디가 땔감을 모아요. 톱을 높이 `H`에 맞추면, H보다 큰 나무는 **윗부분**(높이 − H)이 잘려 노디가 가져가요. H 이하인 나무는 그대로예요.",
    "",
    "적어도 `m`만큼 가져가면서 나무를 **최대한 덜** 자르려면 H를 **가장 높게** 해야 해요. 가능한 가장 높은 H를 반환해 주세요. (m만큼 가져갈 수 있는 경우만 주어져요)",
  ].join("\n"),
  inputFormat: "`trees`: 나무 높이들, `m`: 필요한 나무 양이에요.",
  outputFormat: "톱의 최대 높이",
  constraints: [
    "1 ≤ trees의 길이 ≤ 10,000",
    "1 ≤ 나무 높이 ≤ 1,000,000,000",
    "1 ≤ m ≤ 나무 높이의 합, m ≤ 2,000,000,000",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "trees", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "나무 높이" },
      { name: "m", type: { python: "int", javascript: "number", java: "int" }, description: "필요한 양" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "톱의 최대 높이" },
  },
  starterCode: {
    python: ["def solution(trees, m):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(trees, m) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] trees, int m) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'m 이상 가져가는 **가장 높은** H' → H가 높을수록 가져가는 양이 줄어요. 가능 → 불가능이 한 번만 바뀌니 **답을 이분 탐색**해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. H의 범위는 0 ~ 가장 높은 나무예요.",
        "2. `mid`로 자르면 얻는 양 = `sum(max(0, t - mid))`예요.",
        "3. m 이상이면 가능 → 답으로 적고 더 높게. 아니면 더 낮게.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "lo, hi, answer = 0, max(trees), 0",
        "while lo <= hi:",
        "    mid = (lo + hi) // 2",
        "    got = sum(t - mid for t in trees if t > mid)",
        "    if got >= m: answer = mid; lo = mid + 1",
        "    else: hi = mid - 1",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["얻는 양을 계산하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "mid = (lo + hi) // 2",
            "got = sum(______ for t in trees if t > mid)",
            "if got >= m:",
            "    answer = mid",
            "    lo = mid + 1",
            "else:",
            "    hi = mid - 1",
          ].join("\n"),
          javascript: [
            "const mid = Math.floor((lo + hi) / 2);",
            "let got = 0;",
            "for (const t of trees) if (t > mid) got += ______;",
            "if (got >= m) {",
            "  answer = mid;",
            "  lo = mid + 1;",
            "} else hi = mid - 1;",
          ].join("\n"),
          java: [
            "long mid = (lo + hi) / 2;",
            "long got = 0;",
            "for (int t : trees) if (t > mid) got += ______;",
            "if (got >= m) {",
            "    answer = mid;",
            "    lo = mid + 1;",
            "} else hi = mid - 1;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["parametric-search"],
  signalIds: ["sig-max-min-answer", "sig-huge-range"],
  estimatedMinutes: 15,
  xp: 30,
};
