import type { Problem } from "@/types/content";

export const binarySearchUpdown: Problem = {
  id: "c:binary-search-updown",
  slug: "binary-search-updown",
  source: "curated",
  topic: "binary-search",
  level: 1,
  title: "업다운 숫자 맞히기",
  summary: "항상 가운데를 부르면 몇 번 만에 맞히는지 따라가 봐요",
  statement: [
    "노디가 1부터 `n` 사이의 비밀 숫자 `secret`을 맞히는 업다운 게임을 해요. 노디는 항상 이렇게 불러요.",
    "",
    "- 후보가 `lo` ~ `hi`일 때 `(lo + hi) // 2`(소수점 버림)를 불러요. 처음엔 `lo = 1`, `hi = n`이에요.",
    '- 비밀 숫자가 더 크면 "업" → `lo`가 부른 수 + 1이 돼요.',
    '- 더 작으면 "다운" → `hi`가 부른 수 − 1이 돼요.',
    "",
    "맞힐 때까지 **부른 횟수**(맞힌 번까지 포함)를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 숫자 범위의 끝, `secret`: 비밀 숫자예요.",
  outputFormat: "부른 횟수",
  constraints: ["1 ≤ secret ≤ n ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "범위의 끝" },
      { name: "secret", type: { python: "int", javascript: "number", java: "int" }, description: "비밀 숫자" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "부른 횟수" },
  },
  starterCode: {
    python: ["def solution(n, secret):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, secret) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int secret) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [100, 37],
      expected: 3,
      explanation: "50(다운) → 25(업) → 37로 3번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [100, 50],
      expected: 1,
      explanation: "처음 부른 50이 정답이라 1번이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1, 1],
      expected: 1,
      failureNote: "후보가 하나면 1번이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [100, 100],
      expected: 7,
      failureNote: "끝 숫자는 7번 만에 맞혀요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [100, 1],
      expected: 6,
      failureNote: "첫 숫자는 6번 만에 맞혀요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [1000000000, 1000000000],
      expected: 30,
      failureNote:
        "10억 개 중에서도 30번이면 맞혀요. 하나씩 부르면 너무 오래 걸려요. (Java는 lo + hi가 int를 넘지 않게 조심하세요)",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: [1000000000, 123456789],
      expected: 29,
      failureNote: "10억 범위의 아무 숫자예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["업다운 게임 = **이분 탐색** 그 자체예요. 규칙대로 범위를 좁히며 횟수를 세요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `lo = 1`, `hi = n`, `count = 0`으로 시작해요.",
        "2. `mid = (lo + hi) // 2`를 부르고 `count += 1`.",
        "3. 맞으면 끝. 비밀 숫자가 더 크면 `lo = mid + 1`, 작으면 `hi = mid - 1`.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "lo, hi, count = 1, n, 0",
        "while True:",
        "    mid = (lo + hi) // 2; count += 1",
        "    if mid == secret: return count",
        "    if mid < secret: lo = mid + 1",
        "    else: hi = mid - 1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["업·다운일 때 범위를 바꾸는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while True:",
            "    mid = (lo + hi) // 2",
            "    count += 1",
            "    if mid == secret:",
            "        return count",
            "    if mid < secret:",
            "        ______",
            "    else:",
            "        hi = mid - 1",
          ].join("\n"),
          javascript: [
            "while (true) {",
            "  const mid = Math.floor((lo + hi) / 2);",
            "  count++;",
            "  if (mid === secret) return count;",
            "  if (mid < secret) ______;",
            "  else hi = mid - 1;",
            "}",
          ].join("\n"),
          java: [
            "while (true) {",
            "    long mid = (lo + hi) / 2;",
            "    count++;",
            "    if (mid == secret) return count;",
            "    if (mid < secret) ______;",
            "    else hi = mid - 1;",
            "}",
          ].join("\n"),
        },
        caption: "lo + hi가 20억을 넘을 수 있어서 lo, hi를 long으로 두었어요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["exact-search"],
  signalIds: ["sig-huge-range"],
  estimatedMinutes: 8,
  xp: 10,
};
