import type { Problem } from "@/types/content";

export const mstManhattan: Problem = {
  id: "c:mst-manhattan",
  slug: "mst-manhattan",
  source: "curated",
  topic: "graph-advanced",
  level: 5,
  title: "바둑판 도시의 전선",
  summary: "점마다 모든 쌍을 간선으로 만들고, 거리를 비용으로 크루스칼을 돌려요",
  statement: [
    "바둑판처럼 길이 난 도시에 가로등 `points`가 있어요. `[x, y]`는 가로등의 위치예요.",
    "",
    "두 가로등을 전선으로 이으면 길을 따라 `|x1 − x2| + |y1 − y2|`만큼 전선이 들어요.",
    "",
    "모든 가로등이 전선으로 이어지도록 할 때 드는 **전선 길이 합의 최솟값**을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`points`: 가로등 위치 `[x, y]` 목록이에요. 위치는 겹치지 않아요.",
  outputFormat: "전선 길이 합의 최솟값",
  constraints: ["1 ≤ points의 길이 ≤ 500", "−1,000,000 ≤ x, y ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "points",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "가로등 위치",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "전선 길이 합의 최솟값" },
  },
  starterCode: {
    python: ["def solution(points):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(points) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(int[][] points) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        [
          [0, 0],
          [2, 2],
          [3, 10],
          [5, 2],
          [7, 0],
        ],
      ],
      expected: 20,
      explanation: "4 + 3 + 4 + 9 = 20이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [
        [
          [3, 12],
          [-2, 5],
          [-4, 1],
        ],
      ],
      expected: 18,
      explanation: "(−2, 5)를 가운데 두고 12 + 6 = 18이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[[0, 0]]],
      expected: 0,
      failureNote: "가로등이 하나면 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [
        [
          [0, 0],
          [1, 1],
          [1, 0],
          [-1, 1],
        ],
      ],
      expected: 4,
      failureNote: "1 + 1 + 2 = 4예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        [
          [-1000000, -1000000],
          [1000000, 1000000],
        ],
      ],
      expected: 4000000,
      failureNote: "거리가 4,000,000이에요. 음수 좌표도 절댓값으로 계산해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 500 }, (_, i) => [((i * 7919) % 20001) - 10000, ((i * 104729) % 20011) - 10000])],
      expected: 300700,
      failureNote: "가로등 500개면 쌍이 약 12만 5천 개예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "모든 점을 잇는 최소 비용 → **최소 신장 트리**. 간선이 주어지지 않았을 뿐, **모든 두 점 사이**가 후보 간선이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 모든 쌍 `(i, j)`에 대해 거리 `|x1 − x2| + |y1 − y2|`를 비용으로 간선을 만들어요. 점 N개면 N(N − 1) / 2개예요.",
        "2. 비용 순으로 정렬하고 크루스칼을 돌려요.",
        "3. 간선을 N − 1개 골랐으면 멈춰요.",
        "",
        "N ≤ 500이라 간선 약 12만 5천 개면 충분히 빨라요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "edges = [(거리(i, j), i, j) for 모든 i < j]",
        "edges.sort()",
        "for d, i, j in edges:",
        "    if union(i, j): total += d",
        "return total",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["후보 간선을 만드는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "edges = []",
            "for i in range(n):",
            "    for j in range(i + 1, n):",
            "        d = ______",
            "        edges.append((d, i, j))",
          ].join("\n"),
          javascript: [
            "const edges = [];",
            "for (let i = 0; i < n; i++) {",
            "  for (let j = i + 1; j < n; j++) {",
            "    const d = ______;",
            "    edges.push([d, i, j]);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < n; i++) {",
            "    for (int j = i + 1; j < n; j++) {",
            "        int d = ______;",
            "        edges[k++] = new int[] {d, i, j};",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "거리 합은 21억을 넘을 수 있어서 long으로 더해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["minimum-spanning-tree"],
  signalIds: ["sig-connect-all-cheap"],
  estimatedMinutes: 18,
  xp: 50,
};
