import type { Problem } from "@/types/content";

export const dequeSteadySignal: Problem = {
  id: "c:deque-steady-signal",
  slug: "deque-steady-signal",
  source: "curated",
  topic: "queue-deque",
  level: 5,
  title: "흔들림 없는 신호",
  summary: "최댓값과 최솟값 차이가 limit 이하인 가장 긴 연속 구간을 구해요",
  statement: [
    "노디의 무전기는 초마다 신호 세기를 기록해요. 기록 `signal`에서 **연속한 구간** 하나를 골랐을 때, 그 구간 안의 가장 센 신호와 가장 약한 신호의 차이가 `limit` 이하이면 **흔들림 없는 구간**이라고 불러요.",
    "",
    "흔들림 없는 구간 중 가장 긴 구간의 길이를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`signal`: 초마다의 신호 세기 리스트, `limit`: 허용하는 최대 차이예요.",
  outputFormat: "흔들림 없는 가장 긴 연속 구간의 길이 (정수)",
  constraints: ["1 ≤ signal의 길이 ≤ 100,000", "0 ≤ 각 세기 ≤ 1,000,000,000", "0 ≤ limit ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "signal",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "신호 세기",
      },
      { name: "limit", type: { python: "int", javascript: "number", java: "int" }, description: "허용 차이" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 긴 구간 길이" },
  },
  starterCode: {
    python: ["def solution(signal, limit):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(signal, limit) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] signal, int limit) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[8, 2, 4, 7], 4],
      expected: 2,
      explanation: "[2, 4]는 차이 2로 괜찮고, [2, 4, 7]은 차이 5라 안 돼요. 가장 긴 길이는 2예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [[10, 1, 2, 4, 7, 2], 5],
      expected: 4,
      explanation: "[2, 4, 7, 2]의 차이가 5라서 길이 4예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5], 0],
      expected: 1,
      failureNote: "한 칸짜리 구간은 늘 흔들림이 없어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[3, 3, 3, 3], 0],
      expected: 4,
      failureNote: "limit이 0이면 같은 값만 이어져야 해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[4, 2, 2, 2, 4, 4, 2, 2], 0],
      expected: 3,
      failureNote: "같은 값 묶음 중 가장 긴 것을 찾아요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 5, 6, 7, 8, 10, 6, 5, 6], 4],
      expected: 5,
      failureNote: "구간을 늘렸다 줄였다 해야 해요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "edge",
      args: [[1, 100, 1, 100], 1000],
      expected: 4,
      failureNote: "limit이 크면 전체가 답이에요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 1000) * 1000), 300000],
      expected: 4,
      failureNote: "10만 초의 기록이에요. 모든 구간을 확인하면 시간 초과예요.",
    },
    {
      id: "hid-7",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => i), 49999],
      expected: 50000,
      failureNote: "천천히 올라가는 10만 초의 기록이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"연속한 구간 안의 최댓값·최솟값" → **슬라이딩 윈도우 + 덱**이에요.',
        "",
        "창의 오른쪽 끝을 한 칸씩 늘리다가 조건이 깨지면 왼쪽 끝을 줄여요. 창 안의 최댓값과 최솟값을 빠르게 알기 위해 **덱 두 개**를 써요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "- `maxq`: 값이 앞에서 뒤로 **내려가는** 덱 → 맨 앞이 창의 최댓값",
        "- `minq`: 값이 앞에서 뒤로 **올라가는** 덱 → 맨 앞이 창의 최솟값",
        "",
        "1. 오른쪽 끝 r을 한 칸 늘리며 두 덱에 넣어요 (규칙에 어긋나는 뒤쪽 값은 빼고).",
        "2. `최댓값 − 최솟값 > limit`인 동안 왼쪽 끝 l을 한 칸씩 늘리고, 덱 맨 앞이 l보다 앞이면 빼요.",
        "3. 창 길이 `r − l + 1`의 최댓값이 답이에요. 전체 O(N).",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l = 0",
        "for r in 0..n-1:",
        "    maxq 뒤에서 signal[r] 이하인 값들 제거 후 r 추가",
        "    minq 뒤에서 signal[r] 이상인 값들 제거 후 r 추가",
        "    while signal[maxq 앞] - signal[minq 앞] > limit:",
        "        l += 1",
        "        maxq 앞이 l보다 작으면 제거, minq 앞도 마찬가지",
        "    best = max(best, r - l + 1)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["창을 줄이는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "while signal[maxq[0]] - signal[minq[0]] > limit:",
            "    left += 1",
            "    if maxq[0] < left:",
            "        maxq.popleft()",
            "    if ______:",
            "        minq.popleft()",
            "best = max(best, right - left + 1)",
          ].join("\n"),
          javascript: [
            "while (signal[maxq[maxHead]] - signal[minq[minHead]] > limit) {",
            "  left += 1;",
            "  if (maxq[maxHead] < left) maxHead += 1;",
            "  if (______) minHead += 1;",
            "}",
            "best = Math.max(best, right - left + 1);",
          ].join("\n"),
          java: [
            "while (signal[maxq.peekFirst()] - signal[minq.peekFirst()] > limit) {",
            "    left++;",
            "    if (maxq.peekFirst() < left) maxq.pollFirst();",
            "    if (______) minq.pollFirst();",
            "}",
            "best = Math.max(best, right - left + 1);",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sliding-window-deque"],
  signalIds: ["sig-recent-window"],
  estimatedMinutes: 30,
  xp: 50,
};
