import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[3, -5, 2, -1, -4, 6], 2],
    expected: 10,
    explanation: "0 → 2 → 3 → 5번 돌을 밟으면 3 + 2 − 1 + 6 = 10이에요. −5와 −4는 건너뛰어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[5], 1],
    expected: 5,
    explanation: "돌이 하나면 출발 돌이 곧 도착 돌이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "tricky",
    args: [[-1, -2, -3, -4], 3],
    expected: -5,
    failureNote: "모두 음수예요. 0번에서 3번으로 한 번에 뛰는 게 가장 나아요. 답이 음수일 수 있어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [[1, -1, 1, -1], 1],
    expected: 0,
    failureNote: "k가 1이면 모든 돌을 밟아야 해요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [[2, -10, -10, 5, -10, 3], 3],
    expected: 10,
    failureNote: "가장 가까운 좋은 돌이 아니라, 최근 k개 돌까지의 최고 점수를 봐야 해요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [[4, 1, -2, 7, -8, -3, 5, 2], 3],
    expected: 19,
    failureNote: "음수 돌 여러 개를 골라 건너뛰어요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => ((i * 37) % 201) - 100), 50000],
    expected: 2512309,
    failureNote: "돌 10만 개, 한 번에 최대 5만 칸이에요. 돌마다 앞의 k개를 모두 훑으면 시간 초과예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, () => -10000), 1],
    expected: -1000000000,
    failureNote: "모든 돌이 −10,000이고 한 칸씩만 뛸 수 있어요. 합은 −10억이에요.",
  },
]);

export const dequeSteppingScore: Problem = {
  id: "c:deque-stepping-score",
  slug: "deque-stepping-score",
  source: "curated",
  topic: "queue-deque",
  level: 5,
  title: "징검다리 최고 점수",
  summary: "최대 k칸씩 뛰어 건너며 밟은 돌의 점수 합을 가장 크게 만들어요",
  statement: [
    "개울에 징검다리 돌이 한 줄로 놓여 있어요. `scores[i]`는 i번 돌을 밟을 때 얻는 점수이고, 음수일 수도 있어요.",
    "",
    "노디는 0번 돌에서 출발해 마지막 돌(n−1번)에 도착해야 해요. 한 번 뛸 때 **앞으로 1칸에서 k칸**까지 갈 수 있어요. 뒤로는 갈 수 없어요.",
    "",
    "밟은 돌(출발 돌과 도착 돌 포함)의 점수 합이 **가장 클 때의 합**을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`scores`: 돌마다의 점수 리스트, `k`: 한 번에 뛸 수 있는 최대 칸 수예요.",
  outputFormat: "얻을 수 있는 가장 큰 점수 합 (정수)",
  constraints: ["1 ≤ scores의 길이 ≤ 100,000", "-10,000 ≤ scores[i] ≤ 10,000", "1 ≤ k ≤ scores의 길이"],
  signature: {
    name: "solution",
    params: [
      {
        name: "scores",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "돌마다의 점수",
      },
      {
        name: "k",
        type: { python: "int", javascript: "number", java: "int" },
        description: "한 번에 뛸 수 있는 최대 칸 수",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 큰 점수 합" },
  },
  starterCode: {
    python: ["def solution(scores, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(scores, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] scores, int k) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "i번 돌에 도착했을 때의 최고 점수는 **바로 앞 k개 돌 중 최고 점수** + scores[i]예요.",
        "",
        "'최근 k개 중 최댓값'을 계속 구해야 해요 → **덱 슬라이딩 윈도우**예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `best[i]` = i번 돌까지 왔을 때의 최고 점수. `best[0] = scores[0]`.",
        "2. `best[i] = scores[i] + max(best[i-k], …, best[i-1])`.",
        "3. max를 매번 k개 훑으면 O(N·k)라 느려요. 덱에 돌 번호를 넣되, **best가 큰 순서**로 유지해요.",
        "   - 맨 앞 번호가 i−k보다 작으면(너무 멀면) 앞에서 빼요.",
        "   - 그러면 맨 앞이 최근 k개 중 최고예요.",
        "   - best[i]를 구한 뒤, 뒤에서부터 best가 best[i] 이하인 번호는 빼요. 앞으로 i보다 나을 일이 없으니까요. 그다음 i를 넣어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "best[0] = scores[0], window = 덱[0]",
        "for i in 1..n-1:",
        "    while window 맨 앞 < i - k: 앞에서 빼기",
        "    best[i] = scores[i] + best[window 맨 앞]",
        "    while window가 비어 있지 않고 best[window 맨 뒤] ≤ best[i]: 뒤에서 빼기",
        "    window 뒤에 i 넣기",
        "return best[n-1]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["덱의 best가 큰 순서를 지키는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(1, n):",
            "    while window[0] < i - k:",
            "        window.popleft()",
            "    best[i] = scores[i] + best[window[0]]",
            "    while window and ______ <= best[i]:",
            "        window.pop()",
            "    window.append(i)",
          ].join("\n"),
          javascript: [
            "for (let i = 1; i < n; i++) {",
            "  while (window[head] < i - k) head++;",
            "  best[i] = scores[i] + best[window[head]];",
            "  while (window.length > head && ______ <= best[i]) window.pop();",
            "  window.push(i);",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 1; i < n; i++) {",
            "    while (window.peekFirst() < i - k) window.pollFirst();",
            "    best[i] = scores[i] + best[window.peekFirst()];",
            "    while (!window.isEmpty() && ______ <= best[i]) window.pollLast();",
            "    window.addLast(i);",
            "}",
          ].join("\n"),
        },
        caption: "JavaScript는 배열 뒤는 pop, 앞은 head 인덱스로 빼요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sliding-window-deque"],
  signalIds: ["sig-recent-window"],
  estimatedMinutes: 30,
  xp: 50,
};
