import type { Problem } from "@/types/content";

export const dequeWindowMax: Problem = {
  id: "c:deque-window-max",
  slug: "deque-window-max",
  source: "curated",
  topic: "queue-deque",
  level: 5,
  title: "k일 동안의 최고 기온",
  summary: "연속한 k일마다 가장 높은 기온을 구해요",
  statement: [
    "기상 관측소 노디는 날마다 최고 기온을 기록해 `temps`에 모았어요. 이번에는 **연속한 k일**을 한 묶음으로 보고, 묶음마다 가장 높은 기온을 알고 싶어요.",
    "",
    "첫째 날부터 시작하는 k일 묶음, 둘째 날부터 시작하는 k일 묶음, … 마지막 날에서 끝나는 묶음까지, 각 묶음의 최고 기온을 순서대로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`temps`: 날짜 순서대로의 기온 리스트, `k`: 묶음의 길이(일)예요.",
  outputFormat: "길이가 `len(temps) - k + 1`인 리스트. i번째 값은 i번째 날부터 k일 동안의 최고 기온이에요.",
  constraints: ["1 ≤ k ≤ temps의 길이 ≤ 100,000", "-100,000 ≤ 각 기온 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "temps",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "날짜별 기온",
      },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "묶음 길이" },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "묶음별 최고 기온",
    },
  },
  starterCode: {
    python: ["def solution(temps, k):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(temps, k) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(int[] temps, int k) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[1, 3, -1, -3, 5, 3, 6, 7], 3],
      expected: [3, 3, 5, 5, 6, 7],
      explanation: "[1,3,-1]→3, [3,-1,-3]→3, [-1,-3,5]→5, [-3,5,3]→5, [5,3,6]→6, [3,6,7]→7이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[4, 2, 12], 1],
      expected: [4, 2, 12],
      explanation: "k가 1이면 날마다 자기 기온이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[9, 8, 7], 3],
      expected: [9],
      failureNote: "k가 전체 길이면 묶음이 하나뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[5, 5, 5, 5], 2],
      expected: [5, 5, 5],
      failureNote: "같은 기온이 이어져요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[9, 1, 1, 1, 1, 1], 3],
      expected: [9, 1, 1, 1],
      failureNote: "최고 기온이 묶음 밖으로 빠져나가는 순간을 챙겨야 해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[-5, -1, -8, -2, -9], 2],
      expected: [-1, -1, -2, -2],
      failureNote: "모두 영하예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => i - 50000), 1000],
      expected: Array.from({ length: 99001 }, (_, i) => i - 50000 + 999),
      failureNote: "10만 일, 1,000일 묶음이에요. 묶음마다 max를 새로 계산하면 1억 번 비교해서 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => 50000 - i), 1000],
      expected: Array.from({ length: 99001 }, (_, i) => 50000 - i),
      failureNote: "기온이 계속 내려가는 10만 일이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"연속한 k일 묶음마다의 최댓값" → **슬라이딩 윈도우 + 덱**이에요.',
        "",
        "창이 한 칸 움직일 때 새 날은 **뒤로 들어오고** 오래된 날은 **앞에서 빠져요**. 양쪽 끝을 다뤄야 해서 덱이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "덱에는 **날짜 번호**를 넣고, 덱 안의 기온이 **앞에서 뒤로 내려가게**(단조 감소) 유지해요.",
        "",
        "1. 새 날 i를 넣기 전에, 덱 뒤쪽에서 기온이 `temps[i]` 이하인 날들을 빼요. 새 날보다 춥고 먼저 빠질 날은 앞으로 최고가 될 수 없어요.",
        "2. i를 뒤에 넣어요.",
        "3. 덱 맨 앞 날이 창 밖(`i - k` 이하)이면 앞에서 빼요.",
        "4. i ≥ k−1이면 덱 맨 앞 날의 기온이 이번 창의 최고 기온이에요.",
        "",
        "모든 날이 덱에 한 번 들어가고 한 번 나오므로 O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for i in 0..n-1:",
        "    while 덱이 비어 있지 않고 temps[덱의 뒤] <= temps[i]: 뒤에서 제거",
        "    덱 뒤에 i 추가",
        "    if 덱의 앞 <= i - k: 앞에서 제거",
        "    if i >= k - 1: answer에 temps[덱의 앞] 추가",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["덱을 단조 감소로 유지하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for i, t in enumerate(temps):",
            "    while window and ______:",
            "        window.pop()",
            "    window.append(i)",
            "    if window[0] <= i - k:",
            "        window.popleft()",
            "    if i >= k - 1:",
            "        answer.append(temps[window[0]])",
          ].join("\n"),
          javascript: [
            "temps.forEach((t, i) => {",
            "  while (tail > head && ______) tail -= 1;",
            "  dq[tail++] = i;",
            "  if (dq[head] <= i - k) head += 1;",
            "  if (i >= k - 1) answer.push(temps[dq[head]]);",
            "});",
          ].join("\n"),
          java: [
            "for (int i = 0; i < temps.length; i++) {",
            "    while (!dq.isEmpty() && ______) dq.pollLast();",
            "    dq.offerLast(i);",
            "    if (dq.peekFirst() <= i - k) dq.pollFirst();",
            "    if (i >= k - 1) answer.add(temps[dq.peekFirst()]);",
            "}",
          ].join("\n"),
        },
        caption:
          "JS는 크기 n인 배열 dq와 head·tail 번호로 덱을 만들었어요. 덱에는 온도가 아니라 날짜 번호(인덱스)를 넣어요. Deque<Integer> dq = new ArrayDeque<>().",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sliding-window-deque"],
  signalIds: ["sig-recent-window"],
  estimatedMinutes: 25,
  xp: 50,
};
