import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[3, 9, 1, 2]],
    expected: [5, 10],
    explanation: "노디 3(3>2), 모모 9(9>2), 노디 2(1<2), 모모 1 → [5, 10]이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[4]],
    expected: [4, 0],
    explanation: "카드가 한 장이면 노디가 가져가요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "tricky",
    args: [[5, 1, 5]],
    expected: [6, 5],
    failureNote: "양 끝이 같으면 왼쪽을 가져가요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [[1, 2, 3, 4, 5, 6]],
    expected: [12, 9],
    failureNote: "오른쪽이 계속 더 커요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [[10, 1, 1, 1, 1, 10]],
    expected: [12, 12],
    failureNote: "양 끝의 큰 카드를 먼저 나눠 가져요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "edge",
    args: [[2, 2]],
    expected: [2, 2],
    failureNote: "두 장 모두 같은 숫자예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 1000) + 1)],
    expected: [25050000, 25000000],
    failureNote: "카드 10만 장이에요. 맨 앞 카드를 pop(0)·shift()로 빼면 느려요.",
  },
]);

export const dequeEndCards: Problem = {
  id: "c:deque-end-cards",
  slug: "deque-end-cards",
  source: "curated",
  topic: "queue-deque",
  level: 4,
  title: "양 끝 카드 가져가기",
  summary: "두 사람이 번갈아 양 끝에서 큰 카드를 가져갈 때 점수를 구해요",
  statement: [
    "노디와 친구 모모가 한 줄로 놓인 숫자 카드로 게임을 해요. 노디부터 시작해 번갈아 가며, 자기 차례에는 줄의 **맨 왼쪽 또는 맨 오른쪽** 카드 한 장을 가져가요.",
    "",
    "두 사람 모두 욕심쟁이라서 **양 끝 중 더 큰 카드**를 가져가요. 두 카드가 같으면 왼쪽 카드를 가져가요.",
    "",
    "카드가 다 떨어질 때까지 게임을 했을 때 `[노디 점수, 모모 점수]`를 반환해 주세요. 점수는 가져간 카드 숫자의 합이에요.",
  ].join("\n"),
  inputFormat: "`cards`: 왼쪽부터의 카드 숫자 리스트예요.",
  outputFormat: "`[노디 점수, 모모 점수]`",
  constraints: ["1 ≤ cards의 길이 ≤ 100,000", "1 ≤ 각 숫자 ≤ 1,000"],
  signature: {
    name: "solution",
    params: [
      { name: "cards", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "카드 숫자" },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "int[]" },
      description: "[노디 점수, 모모 점수]",
    },
  },
  starterCode: {
    python: ["def solution(cards):", "    answer = [0, 0]", "    return answer", ""].join("\n"),
    javascript: ["function solution(cards) {", "  let answer = [0, 0];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] cards) {",
      "        int[] answer = new int[2];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ['"맨 왼쪽 또는 맨 오른쪽 카드를 가져가요" → **양쪽 끝**을 다루는 **덱**이에요.'].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 카드를 덱에 넣어요 (또는 왼쪽·오른쪽 번호 두 개 `left`, `right`로 남은 구간을 표시해요).",
        "2. 차례마다 양 끝을 비교해 큰 쪽(같으면 왼쪽)을 꺼내 지금 차례인 사람 점수에 더해요.",
        "3. 차례는 노디 → 모모 → 노디 … 로 번갈아요. `turn % 2`로 구분하면 편해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "score = [0, 0], turn = 0",
        "while 덱이 비어 있지 않음:",
        "    if 왼쪽 끝 >= 오른쪽 끝: card = 왼쪽에서 꺼내기",
        "    else: card = 오른쪽에서 꺼내기",
        "    score[turn % 2] += card",
        "    turn += 1",
        "return score",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["양 끝을 비교해 꺼내는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "while row:",
            "    if row[0] >= row[-1]:",
            "        card = row.popleft()",
            "    else:",
            "        card = ______",
            "    score[turn % 2] += card",
            "    turn += 1",
          ].join("\n"),
          javascript: [
            "let left = 0, right = cards.length - 1, turn = 0;",
            "while (left <= right) {",
            "  const card = cards[left] >= cards[right] ? cards[left++] : ______;",
            "  score[turn % 2] += card;",
            "  turn += 1;",
            "}",
          ].join("\n"),
          java: [
            "int left = 0, right = cards.length - 1, turn = 0;",
            "while (left <= right) {",
            "    int card = cards[left] >= cards[right] ? cards[left++] : ______;",
            "    score[turn % 2] += card;",
            "    turn++;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["two-ended-deque"],
  signalIds: ["sig-both-ends"],
  estimatedMinutes: 18,
  xp: 40,
};
