import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [5, [3, 1]],
    expected: 4,
    explanation:
      "3번을 꺼내려면 왼쪽으로 2칸(오른쪽이면 3칸). 꺼낸 뒤 레일은 4, 5, 1, 2이고, 1번은 어느 쪽으로든 2칸이에요. 모두 4번이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "basic",
    args: [5, [5]],
    expected: 1,
    explanation: "5번은 레일 맨 끝이라 오른쪽으로 1칸이면 돼요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [1, [1]],
    expected: 0,
    failureNote: "접시가 하나뿐이면 돌릴 필요가 없어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [10, [1, 2, 3]],
    expected: 0,
    failureNote: "꺼낼 때마다 다음 접시가 바로 노디 앞에 와요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [10, [2, 9, 5]],
    expected: 8,
    failureNote: "주문마다 더 가까운 방향을 골라요. 이미 꺼낸 접시는 레일에 없다는 걸 잊지 마세요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [6, [6, 5, 4, 3, 2, 1]],
    expected: 5,
    failureNote: "뒤에서부터 꺼내면 오른쪽으로 돌리는 게 가까워요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, Array.from({ length: 1000 }, (_, i) => (i % 2 === 0 ? i / 2 + 1 : 1000 - (i - 1) / 2))],
    expected: 499,
    failureNote: "접시 1,000개를 앞과 뒤에서 번갈아 꺼내요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, Array.from({ length: 500 }, (_, i) => ((i * 7) % 1000) + 1)],
    expected: 2352,
    failureNote: "접시 1,000개 중 500개를 띄엄띄엄 꺼내요.",
  },
]);

export const dequeSushiRail: Problem = {
  id: "c:deque-sushi-rail",
  slug: "deque-sushi-rail",
  source: "curated",
  topic: "queue-deque",
  level: 4,
  title: "회전 초밥 레일",
  summary: "원형 레일을 짧은 쪽으로 돌려 원하는 접시를 꺼내요",
  statement: [
    "노디가 일하는 초밥집에는 **원형 레일**이 있어요. 레일에는 1번부터 n번까지 접시가 번호 순서대로 한 바퀴 놓여 있고, 노디 앞에는 1번 접시가 있어요.",
    "",
    "노디는 레일을 두 방향으로 돌릴 수 있어요. 한 번 돌릴 때마다 접시가 한 칸씩 움직여요.",
    "",
    "- **왼쪽으로 한 칸**: 노디 앞의 접시가 레일 맨 끝으로 가고, 그다음 접시가 노디 앞에 와요.",
    "- **오른쪽으로 한 칸**: 레일 맨 끝 접시가 노디 앞으로 와요.",
    "",
    "손님이 주문한 접시 번호가 `picks` 순서대로 주어져요. 노디는 주문 순서대로, 주문한 접시가 **노디 앞에 올 때까지** 레일을 돌린 뒤 그 접시를 레일에서 꺼내요. 꺼낸 접시 자리는 사라지고, 바로 다음 접시가 노디 앞에 와요.",
    "",
    "모든 주문을 처리할 때 레일을 돌리는 **최소 횟수**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 처음 접시 수, `picks`: 꺼낼 접시 번호를 주문 순서대로 담은 리스트예요.",
  outputFormat: "레일을 돌리는 최소 횟수 (정수)",
  constraints: ["1 ≤ n ≤ 1,000", "1 ≤ picks의 길이 ≤ n", "picks의 번호는 1 이상 n 이하이고 서로 달라요"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "처음 접시 수" },
      {
        name: "picks",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "꺼낼 접시 번호 (주문 순서)",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "레일을 돌리는 최소 횟수" },
  },
  starterCode: {
    python: ["def solution(n, picks):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, picks) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[] picks) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "레일을 왼쪽으로 돌리면 **앞의 접시가 뒤로**, 오른쪽으로 돌리면 **뒤의 접시가 앞으로** 와요. 양쪽 끝에서 넣고 빼요 → **덱**이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 레일을 덱으로 만들어요 (1, 2, …, n).",
        "2. 주문한 접시가 덱의 몇 번째(idx, 0부터)에 있는지 찾아요.",
        "3. 왼쪽으로 돌리면 idx번, 오른쪽으로 돌리면 `길이 − idx`번이에요. **더 적은 쪽**을 골라 그만큼 돌리고 횟수에 더해요.",
        "4. 이제 노디 앞(덱의 맨 앞)이 주문한 접시예요. 꺼내요.",
        "",
        "어느 방향으로 돌려도 꺼낸 뒤 레일의 모양은 똑같아서, 주문마다 가까운 쪽을 고르면 전체도 최소예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "rail = 덱(1..n), total = 0",
        "for p in picks:",
        "    idx = rail에서 p의 위치",
        "    idx ≤ len(rail) - idx → 왼쪽으로 idx번 돌리기, total += idx",
        "    아니면               → 오른쪽으로 len(rail) - idx번 돌리기, total += len(rail) - idx",
        "    rail 앞에서 꺼내기",
        "return total",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["왼쪽으로 한 칸 돌리는 동작을 덱으로 옮겨 보세요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "idx = rail.index(p)",
            "if idx <= len(rail) - idx:",
            "    for _ in range(idx):",
            "        rail.append(______)   # 왼쪽으로 한 칸",
            "    total += idx",
            "else:",
            "    for _ in range(len(rail) - idx):",
            "        rail.appendleft(rail.pop())   # 오른쪽으로 한 칸",
            "    total += len(rail) - idx",
            "rail.popleft()",
          ].join("\n"),
          javascript: [
            "const idx = rail.indexOf(p);",
            "const moves = Math.min(idx, rail.length - idx);",
            "total += moves;",
            "// 어느 쪽으로 돌려도 결과는 같아요: p가 맨 앞에 오고 나머지는 순서 그대로",
            "rail = [...rail.slice(______), ...rail.slice(0, idx)];",
            "rail.shift();",
          ].join("\n"),
          java: [
            "if (idx <= rail.size() - idx) {",
            "    for (int i = 0; i < idx; i++) rail.addLast(______);   // 왼쪽으로 한 칸",
            "    total += idx;",
            "} else {",
            "    for (int i = 0; i < rail.size() - idx; i++) rail.addFirst(rail.pollLast());   // 오른쪽으로 한 칸",
            "    total += rail.size() - idx;",
            "}",
            "rail.pollFirst();",
          ].join("\n"),
        },
        caption:
          "JavaScript에는 덱이 없어서, 돌린 결과를 slice로 한 번에 만들어요 (n이 1,000 이하라 충분히 빨라요). ArrayDeque에는 indexOf가 없어서 for-each로 앞에서부터 세어 위치를 찾아요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["two-ended-deque"],
  signalIds: ["sig-both-ends"],
  visualization: {
    presets: [
      problemPreset(
        "sushi-rail-rotate",
        "deque-basic",
        "오른쪽으로 한 칸 돌리기",
        "1~4번 접시를 놓고, 맨 끝 접시를 앞으로 옮긴 뒤(pop_back → push_front) 꺼내요.",
        [["push_back 1", "push_back 2", "push_back 3", "push_back 4", "pop_back", "push_front 4", "pop_front"]],
      ),
    ],
  },
  estimatedMinutes: 20,
  xp: 40,
};
