import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const dequeTwoDoorTrain: Problem = {
  id: "c:deque-two-door-train",
  slug: "deque-two-door-train",
  source: "curated",
  topic: "queue-deque",
  level: 4,
  title: "양쪽 문 기차",
  summary: "앞·뒤 문으로 타고 내린 뒤 기차 안 승객 순서를 구해요",
  statement: [
    "노디 마을의 장난감 기차는 **앞문과 뒷문**이 모두 열려요. 승객 기록 `commands`는 다음과 같아요.",
    "",
    '- `"push_front x"`: 승객 x가 앞문으로 타서 맨 앞에 서요.',
    '- `"push_back x"`: 승객 x가 뒷문으로 타서 맨 뒤에 서요.',
    '- `"pop_front"`: 맨 앞 승객이 앞문으로 내려요.',
    '- `"pop_back"`: 맨 뒤 승객이 뒷문으로 내려요.',
    "",
    "기차가 비어 있을 때 내리는 명령은 무시해요. 모든 기록이 끝난 뒤 기차 안 승객 번호를 **앞에서부터** 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`commands`: 위 네 가지 명령 문자열의 리스트예요.",
  outputFormat: "앞에서부터 뒤까지의 승객 번호 리스트",
  constraints: ["1 ≤ commands의 길이 ≤ 100,000", "1 ≤ x ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [{ name: "commands", type: { python: "list[str]", javascript: "string[]" }, description: "승객 기록" }],
    returns: { type: { python: "list[int]", javascript: "number[]" }, description: "앞에서부터의 승객 번호" },
  },
  starterCode: {
    python: ["def solution(commands):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(commands) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["push_back 1", "push_back 2", "push_front 3", "pop_back"]],
      expected: [3, 1],
      explanation: "[1] → [1,2] → [3,1,2] → 뒤의 2가 내려서 [3, 1]이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [["pop_front", "push_front 5", "pop_back", "pop_back"]],
      expected: [],
      explanation: "빈 기차에서 내리는 명령은 무시돼요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [["push_front 1", "push_front 2", "push_front 3"]],
      expected: [3, 2, 1],
      failureNote: "앞문으로만 타면 역순으로 서요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [["push_back 1", "push_back 2", "pop_front", "push_back 3", "pop_front"]],
      expected: [3],
      failureNote: "뒤로 타고 앞으로 내리면 큐와 같아요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [["push_back 7", "pop_front", "push_front 8", "pop_back", "push_back 9"]],
      expected: [9],
      failureNote: "한 명일 때는 앞과 뒤가 같은 승객이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [["push_back 4", "push_front 5", "push_back 6", "pop_front", "push_front 7", "pop_back"]],
      expected: [7, 4],
      failureNote: "양쪽 문을 번갈아 써요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i < 50000 ? `push_front ${i}` : "pop_back"))],
      expected: [],
      failureNote: "앞문으로 5만 명이 타고 뒷문으로 모두 내려요. 배열 앞에 끼워 넣기(insert(0)·unshift)는 느려요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i % 2 === 0 ? `push_front ${i}` : `push_back ${i}`))],
      expected: [
        ...Array.from({ length: 50000 }, (_, i) => 99998 - 2 * i),
        ...Array.from({ length: 50000 }, (_, i) => 2 * i + 1),
      ],
      failureNote: "10만 명이 앞뒤로 번갈아 타요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 구조일까요?",
      body: [
        "앞과 뒤 **양쪽**에서 넣고 빼요 → **덱(deque)** 이에요.",
        "",
        "스택(한쪽 끝)과 큐(뒤로 넣고 앞으로 빼기)를 모두 할 수 있는 자료구조예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "- Python: `collections.deque`의 `appendleft`, `append`, `popleft`, `pop`이 모두 O(1)이에요.",
        "- JavaScript: 배열의 `unshift`는 O(N)이라 느려요. 앞쪽 전용 배열과 뒤쪽 전용 배열 두 개로 덱을 흉내 내거나, 충분히 큰 배열 가운데서 시작하는 **head·tail 번호** 두 개를 쓰면 O(1)이 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for 명령 in commands:",
        "    push_front x → 덱 앞에 x",
        "    push_back x  → 덱 뒤에 x",
        "    pop_front    → 비어 있지 않으면 앞에서 제거",
        "    pop_back     → 비어 있지 않으면 뒤에서 제거",
        "return 덱을 앞에서부터 리스트로",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["JS는 가운데서 시작하는 배열로 덱을 만들어요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "train = deque()",
            "for command in commands:",
            "    parts = command.split()",
            '    if parts[0] == "push_front":',
            "        train.appendleft(int(parts[1]))",
            '    elif parts[0] == "pop_back" and train:',
            "        ______",
          ].join("\n"),
          javascript: [
            "const size = commands.length;",
            "const slots = new Array(2 * size + 1);",
            "let head = size, tail = size; // [head, tail) 구간이 기차",
            "// push_front x",
            "slots[--head] = x;",
            "// push_back x",
            "______;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["two-ended-deque"],
  signalIds: ["sig-both-ends"],
  visualization: {
    presets: [
      problemPreset("two-door-ex1", "deque-basic", "예제 1", "앞과 뒤 양쪽 문으로 타고 내리는 모습을 봐요.", [
        ["push_back 1", "push_back 2", "push_front 3", "pop_back"],
      ]),
    ],
  },
  estimatedMinutes: 18,
  xp: 40,
};
