import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const queueCarouselLine: Problem = {
  id: "c:queue-carousel-line",
  slug: "queue-carousel-line",
  source: "curated",
  topic: "queue-deque",
  level: 1,
  title: "회전목마 탑승 줄",
  summary: "줄 선 순서대로 회전목마에 몇 명씩 태워요",
  statement: [
    "놀이공원 회전목마 앞에 줄이 있어요. 먼저 줄 선 사람이 먼저 타요.",
    "",
    '- `"arrive name"`: 이름이 name인 사람이 줄 맨 뒤에 서요.',
    '- `"ride k"`: 회전목마가 출발해요. 줄 맨 앞부터 **k명**이 타요. 줄에 k명보다 적게 있으면 있는 사람만 모두 타요.',
    "",
    '`"ride"` 때마다 탄 사람들의 이름을 탄 순서대로 리스트로 기록해요. 아무도 타지 않았다면 빈 리스트를 기록해요.',
    "",
    "기록한 리스트들을 차례로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: '`commands`: `"arrive name"`, `"ride k"` 문자열의 리스트예요.',
  outputFormat: "ride마다 탄 사람 이름 리스트를 순서대로 담은 리스트",
  constraints: [
    "1 ≤ commands의 길이 ≤ 1,000",
    "name은 영어 소문자와 숫자로 된 1~10글자이고 서로 달라요",
    "1 ≤ k ≤ 100",
  ],
  signature: {
    name: "solution",
    params: [
      {
        name: "commands",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "명령 목록",
      },
    ],
    returns: {
      type: { python: "list[list[str]]", javascript: "string[][]", java: "List<List<String>>" },
      description: "ride마다 탄 사람들",
    },
  },
  starterCode: {
    python: ["def solution(commands):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(commands) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<List<String>> solution(String[] commands) {",
      "        List<List<String>> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["arrive mina", "arrive jun", "arrive ara", "ride 2", "arrive bo", "ride 2"]],
      expected: [
        ["mina", "jun"],
        ["ara", "bo"],
      ],
      explanation: "첫 출발에 mina, jun이 타요. 다음 출발에는 남아 있던 ara와 새로 온 bo가 타요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [["ride 3", "arrive kai", "ride 3"]],
      expected: [[], ["kai"]],
      explanation: "첫 출발에는 아무도 없어서 빈 리스트예요. 두 번째에는 kai 혼자 타요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["arrive a", "arrive b", "arrive c"]],
      expected: [],
      failureNote: "ride가 한 번도 없으면 빈 리스트예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [["arrive a", "ride 1", "ride 1", "arrive b", "ride 5"]],
      expected: [["a"], [], ["b"]],
      failureNote: "빈 줄에서 출발하면 빈 리스트, 5명 자리에 1명뿐이면 1명만 타요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [["arrive x", "arrive y", "arrive z", "ride 1", "ride 1", "ride 1"]],
      expected: [["x"], ["y"], ["z"]],
      failureNote: "한 명씩 줄 선 순서대로 타요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 1000 }, (_, i) => (i < 900 ? "arrive p" + i : "ride 10"))],
      expected: Array.from({ length: 100 }, (_, r) =>
        r < 90 ? Array.from({ length: 10 }, (_, j) => "p" + (r * 10 + j)) : [],
      ),
      failureNote: "900명이 줄을 서고 10명씩 100번 출발해요. 마지막 10번은 빈 회전목마예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 구조일까요?",
      body: [
        "**먼저 줄 선 사람이 먼저** 타요 → **큐**예요.",
        "",
        "arrive는 뒤에 넣기(enqueue), ride k는 앞에서 k번 꺼내기(dequeue)예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 줄 `line`(큐)과 결과 `answer`를 준비해요. Python은 `collections.deque`가 편해요.",
        "2. arrive → 이름을 줄 뒤에 넣어요.",
        "3. ride k → 빈 리스트 `group`을 만들고, **k와 줄 길이 중 작은 수**만큼 앞에서 꺼내 group에 넣어요. 그다음 group을 answer에 추가해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for 명령 in commands:",
        "    arrive name → line 뒤에 name 넣기",
        "    ride k      → group = []",
        "                  min(k, line의 길이)번: line 앞에서 꺼내 group에 추가",
        "                  answer에 group 추가",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드: 출발",
      body: ["줄 앞에서 사람을 꺼내 태우는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "else:  # ride k",
            "    group = []",
            "    for _ in range(min(int(value), len(line))):",
            "        group.append(______)",
            "    answer.append(group)",
          ].join("\n"),
          javascript: [
            "} else {  // ride k",
            "  const group = [];",
            "  const count = Math.min(Number(value), line.length - head);",
            "  for (let i = 0; i < count; i++) group.push(______);",
            "  answer.push(group);",
            "}",
          ].join("\n"),
          java: [
            "} else {  // ride k",
            "    List<String> group = new ArrayList<>();",
            "    int count = Math.min(Integer.parseInt(parts[1]), line.size());",
            "    for (int i = 0; i < count; i++) group.add(______);",
            "    answer.add(group);",
            "}",
          ].join("\n"),
        },
        caption:
          "JavaScript는 앞 인덱스 head를 하나씩 옮기며 꺼내요. Java는 Deque<String> line = new ArrayDeque<>()를 큐로 써요 (offer로 뒤에 넣고 poll로 앞에서 꺼내요).",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["queue-simulation"],
  signalIds: ["sig-arrival-order"],
  visualization: {
    presets: [
      problemPreset(
        "carousel-line-flow",
        "queue-basic",
        "예제 1 흐름 (번호로)",
        "이름 대신 번호로 봐요. ride 2는 dequeue를 두 번 하는 거예요.",
        [["enqueue 1", "enqueue 2", "enqueue 3", "dequeue", "dequeue", "enqueue 4", "dequeue", "dequeue"]],
      ),
    ],
  },
  estimatedMinutes: 8,
  xp: 10,
};
