import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[10, 3], 4],
    expected: [3, 2, 3, 2, 3],
    explanation: "10은 5, 5로 잘려 줄 뒤로 가고, 3이 먼저 완성돼요. 5는 다시 2, 3으로 잘려요. 결과 [3, 2, 3, 2, 3].",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[1, 2, 3], 5],
    expected: [1, 2, 3],
    explanation: "모두 limit 이하라서 놓인 순서 그대로 완성돼요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[6], 6],
    expected: [6],
    failureNote: "limit과 무게가 같으면 자르지 않고 완성이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [[9], 2],
    expected: [2, 2, 2, 1, 2],
    failureNote: "잘린 조각은 줄 맨 뒤로 가서, 먼저 잘린 조각의 자식들이 먼저 완성돼요. 순서에 주의해요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [[5, 20, 1], 5],
    expected: [5, 1, 5, 5, 5, 5],
    failureNote: "5와 1은 바로 완성, 20은 두 번 잘려요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [[7, 8], 3],
    expected: [3, 2, 2, 2, 2, 2, 2],
    failureNote: "홀수 무게는 가벼운 조각이 먼저 줄에 서요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [[131072], 1],
    expected: Array.from({ length: 131072 }, () => 1),
    failureNote: "반죽 하나가 13만 조각으로 나뉘어요. 리스트 맨 앞을 지우는 pop(0)이나 shift()로는 시간 초과예요.",
  },
]);

export const queueDoughSplit: Problem = {
  id: "c:queue-dough-split",
  slug: "queue-dough-split",
  source: "curated",
  topic: "queue-deque",
  level: 2,
  title: "반죽 나누기",
  summary: "무거운 반죽을 반으로 잘라 다시 줄 세우며 완성 순서를 구해요",
  statement: [
    "노디는 빵 반죽을 알맞은 크기로 나누고 있어요. 반죽 덩어리들이 `doughs` 순서대로 작업대 앞에 한 줄로 놓여 있어요.",
    "",
    "줄이 빌 때까지 이 일을 반복해요.",
    "",
    "1. 줄 **맨 앞** 덩어리를 가져와요. 무게를 w라고 할게요.",
    "2. w가 `limit` 이하라면 완성! 완성 목록에 w를 적어요.",
    "3. w가 `limit`보다 무거우면 반으로 잘라요. 가벼운 조각 `w // 2`와 나머지 조각 `w - w // 2`를 **이 순서대로 줄 맨 뒤에** 놓아요.",
    "",
    "완성된 조각의 무게를 완성된 순서대로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`doughs`: 처음 줄에 놓인 반죽 무게 리스트, `limit`: 완성으로 치는 최대 무게예요.",
  outputFormat: "완성된 조각의 무게를 완성된 순서대로 담은 리스트",
  constraints: [
    "1 ≤ doughs의 길이 ≤ 1,000",
    "1 ≤ 각 무게 ≤ 1,000,000,000",
    "1 ≤ limit ≤ 1,000,000,000",
    "완성되는 조각은 모두 200,000개 이하예요",
  ],
  signature: {
    name: "solution",
    params: [
      {
        name: "doughs",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "처음 반죽 무게",
      },
      {
        name: "limit",
        type: { python: "int", javascript: "number", java: "int" },
        description: "완성으로 치는 최대 무게",
      },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "완성된 조각 무게 (완성 순서)",
    },
  },
  starterCode: {
    python: ["def solution(doughs, limit):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(doughs, limit) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(int[] doughs, int limit) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 구조일까요?",
      body: [
        "**맨 앞**에서 꺼내고, 잘린 조각은 **맨 뒤**에 넣어요 → **큐**예요.",
        "",
        "이 문제는 큐에 넣고 빼는 횟수가 26만 번이 넘어요. 큐를 **빠르게** 만드는 게 핵심이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "Python 리스트의 `pop(0)`과 JavaScript 배열의 `shift()`는 뒤의 모든 값을 한 칸씩 당기느라 O(N)이에요. 큐가 길면 매우 느려져요.",
        "",
        "- Python: `collections.deque`의 `popleft()`는 O(1)이에요.",
        "- JavaScript: 배열은 그대로 두고 **앞 인덱스** `head`만 한 칸씩 옮겨요. `line[head++]`가 꺼내기예요.",
        "",
        "그다음은 문제 그대로예요. 꺼낸 무게가 limit 이하면 answer에, 아니면 두 조각을 뒤에 넣어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "line = doughs로 만든 큐, answer = []",
        "while line이 비어 있지 않은 동안:",
        "    w = line 앞에서 꺼내기          # O(1)이어야 해요",
        "    w ≤ limit → answer에 w 추가",
        "    아니면   → line 뒤에 w // 2, 그다음 w - w // 2 넣기",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["줄 맨 앞에서 O(1)로 꺼내는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "line = deque(doughs)",
            "while line:",
            "    w = ______",
            "    if w <= limit:",
            "        answer.append(w)",
            "    else:",
            "        line.append(w // 2)",
            "        line.append(w - w // 2)",
          ].join("\n"),
          javascript: [
            "const line = [...doughs];",
            "let head = 0;",
            "while (head < line.length) {",
            "  const w = ______;",
            "  if (w <= limit) {",
            "    answer.push(w);",
            "  } else {",
            "    const half = Math.floor(w / 2);",
            "    line.push(half, w - half);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "while (!line.isEmpty()) {",
            "    int w = ______;",
            "    if (w <= limit) {",
            "        answer.add(w);",
            "    } else {",
            "        line.offer(w / 2);",
            "        line.offer(w - w / 2);",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "Java의 ArrayDeque는 poll(앞에서 꺼내기)이 O(1)이에요. ArrayList의 remove(0)은 O(N)이라 느려요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["queue-simulation"],
  signalIds: ["sig-arrival-order"],
  estimatedMinutes: 12,
  xp: 20,
};
