import type { Problem } from "@/types/content";

export const queueRecentVisits: Problem = {
  id: "c:queue-recent-visits",
  slug: "queue-recent-visits",
  source: "curated",
  topic: "queue-deque",
  level: 2,
  title: "최근 3초 방문자",
  summary: "방문할 때마다 최근 3초 안의 방문 수를 세요",
  statement: [
    "노디의 블로그에는 방문 기록이 밀리초(ms) 단위로 남아요. `times[i]`는 i번째 방문 시각이고, 시각은 **점점 커지는 순서**로 주어져요.",
    "",
    "방문이 일어날 때마다, 그 순간을 포함해 **최근 3,000ms 안**(시각 t라면 `t - 3000` 이상 `t` 이하)에 있었던 방문 수를 구하려고 해요.",
    "",
    "방문마다 구한 수를 순서대로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`times`: 방문 시각(ms) 리스트예요. 값은 서로 다르고 점점 커져요.",
  outputFormat: "i번째 값이 i번째 방문 순간의 최근 3초 방문 수인 리스트",
  constraints: ["1 ≤ times의 길이 ≤ 100,000", "1 ≤ times[i] ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [{ name: "times", type: { python: "list[int]", javascript: "number[]" }, description: "방문 시각(ms)" }],
    returns: { type: { python: "list[int]", javascript: "number[]" }, description: "최근 3초 방문 수" },
  },
  starterCode: {
    python: ["def solution(times):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(times) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[1, 100, 3001, 3002]],
      expected: [1, 2, 3, 3],
      explanation: "3001ms에는 1~3001 구간이라 3개, 3002ms에는 1이 빠져서 3개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[1000, 5000, 9000]],
      expected: [1, 1, 1],
      explanation: "방문 간격이 3초보다 길면 늘 자기 자신 1개예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[42]],
      expected: [1],
      failureNote: "방문이 한 번뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 3001]],
      expected: [1, 2],
      failureNote: "정확히 3,000ms 전 방문도 포함해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 3002]],
      expected: [1, 1],
      failureNote: "3,001ms 전 방문은 빠져요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[10, 20, 30, 3025, 6030, 6040]],
      expected: [1, 2, 3, 2, 1, 2],
      failureNote: "오래된 방문이 여러 개 한꺼번에 빠지기도 해요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => i + 1)],
      expected: Array.from({ length: 100000 }, (_, i) => Math.min(i + 1, 3001)),
      failureNote: "1ms마다 방문해서 3초 창에 3,001개씩 들어 있어요. 매번 창 전체를 세면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"최근 3,000ms" → 시간이 흐르면 **오래된 방문이 앞에서 빠지고**, 새 방문은 뒤로 들어와요 → **큐**예요.',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 새 방문 시각 t를 큐 뒤에 넣어요.",
        "2. 큐 맨 앞이 `t - 3000`보다 **작은 동안** 앞에서 꺼내요.",
        "3. 남은 큐의 크기가 답이에요.",
        "",
        "시각이 커지는 순서라서, 한 번 빠진 방문은 다시 들어올 일이 없어요. 모든 방문이 한 번 들어가고 한 번 나가니까 O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for t in times:",
        "    queue 뒤에 t 추가",
        "    while queue 맨 앞 < t - 3000:",
        "        queue 앞에서 제거",
        "    answer에 queue의 크기 추가",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["오래된 방문을 빼는 조건이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for t in times:",
            "    window.append(t)",
            "    while ______:",
            "        window.popleft()",
            "    answer.append(len(window))",
          ].join("\n"),
          javascript: [
            "for (const t of times) {",
            "  window.push(t);",
            "  while (______) head += 1;",
            "  answer.push(window.length - head);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["queue-simulation", "sliding-window-deque"],
  signalIds: ["sig-recent-window"],
  estimatedMinutes: 15,
  xp: 20,
};
