import type { Problem } from "@/types/content";

export const queueShuttleBus: Problem = {
  id: "c:queue-shuttle-bus",
  slug: "queue-shuttle-bus",
  source: "curated",
  topic: "queue-deque",
  level: 3,
  title: "셔틀버스 탑승",
  summary: "정해진 시각에 출발하는 셔틀버스에 기다린 순서대로 태워요",
  statement: [
    "캠핑장 셔틀버스 정류장에 사람들이 모여요. `arrivals[i]`는 i번 사람이 정류장에 도착한 시각이고, 도착한 순서대로 줄을 서요.",
    "",
    "셔틀버스는 모두 `buses`대예요. b번 버스(1부터)는 시각 `b × interval`에 출발하고, 한 번에 최대 `capacity`명을 태워요.",
    "",
    "- 버스는 출발 시각까지 도착한 사람(도착 시각 ≤ 출발 시각) 중 **줄 앞에서부터** 태워요.",
    "- 자리가 모자라 못 탄 사람은 줄에 남아 다음 버스를 기다려요.",
    "",
    "사람마다 **몇 번 버스에 탔는지** 담은 리스트를 반환해 주세요. 마지막 버스까지 못 탄 사람은 `-1`이에요.",
  ].join("\n"),
  inputFormat:
    "`arrivals`: 도착 시각 리스트(오름차순), `buses`: 버스 수, `interval`: 출발 간격, `capacity`: 버스 정원이에요.",
  outputFormat: "i번째 값이 i번 사람이 탄 버스 번호(또는 -1)인 리스트",
  constraints: [
    "1 ≤ arrivals의 길이 ≤ 100,000",
    "0 ≤ arrivals[i] ≤ 1,000,000,000, 오름차순이에요",
    "1 ≤ buses ≤ 100,000",
    "1 ≤ interval ≤ 10,000",
    "1 ≤ capacity ≤ 100",
  ],
  signature: {
    name: "solution",
    params: [
      {
        name: "arrivals",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "도착 시각 (오름차순)",
      },
      { name: "buses", type: { python: "int", javascript: "number", java: "int" }, description: "버스 수" },
      { name: "interval", type: { python: "int", javascript: "number", java: "int" }, description: "출발 간격" },
      { name: "capacity", type: { python: "int", javascript: "number", java: "int" }, description: "버스 정원" },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "int[]" },
      description: "사람마다 탄 버스 번호 (못 타면 -1)",
    },
  },
  starterCode: {
    python: [
      "def solution(arrivals, buses, interval, capacity):",
      "    answer = [-1] * len(arrivals)",
      "    return answer",
      "",
    ].join("\n"),
    javascript: [
      "function solution(arrivals, buses, interval, capacity) {",
      "  let answer = new Array(arrivals.length).fill(-1);",
      "  return answer;",
      "}",
      "",
    ].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] arrivals, int buses, int interval, int capacity) {",
      "        int[] answer = new int[arrivals.length];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[1, 2, 2, 7, 8], 3, 3, 2],
      expected: [1, 1, 2, 3, 3],
      explanation:
        "시각 3의 1번 버스에는 먼저 온 두 명이 타고, 세 번째 사람은 시각 6의 2번 버스를 타요. 7, 8에 온 두 명은 시각 9의 3번 버스를 타요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[5, 5, 5], 1, 5, 2],
      expected: [1, 1, -1],
      explanation: "버스가 한 대뿐이라 세 번째 사람은 못 타요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[10], 2, 3, 1],
      expected: [-1],
      failureNote: "마지막 버스(시각 6)가 떠난 뒤에 도착했어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[3, 4], 2, 3, 5],
      expected: [1, 2],
      failureNote: "출발 시각에 딱 맞춰 도착하면 탈 수 있어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[0, 0, 0, 0, 0], 3, 1, 2],
      expected: [1, 1, 2, 2, 3],
      failureNote: "한꺼번에 온 사람들이 정원만큼 나눠 타요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 20, 21], 10, 2, 1],
      expected: [1, 10, -1],
      failureNote: "빈 버스가 여러 대 지나가요. 21에 온 사람은 마지막 버스(시각 20)를 놓쳐요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, () => 0), 100000, 1, 1],
      expected: Array.from({ length: 100000 }, (_, i) => i + 1),
      failureNote:
        "10만 명이 한꺼번에 와서 한 명씩 버스를 타요. 줄 맨 앞을 지우는 데 O(N)이 들거나, 버스마다 모든 사람을 훑으면 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => i), 50000, 2, 2],
      expected: Array.from({ length: 100000 }, (_, i) => Math.floor(i / 2) + 1),
      failureNote: "1초마다 한 명씩 오고, 2초마다 버스가 두 명씩 태워 가요. 줄 앞의 한 명은 늘 다음 버스를 기다려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "**도착한 순서대로** 줄을 서고, 앞에서부터 태워요 → **큐**로 옮기는 시뮬레이션이에요.",
        "",
        "시간이 흐르면서 두 가지 일이 일어나요. 사람이 줄 뒤에 서고, 버스가 앞에서 태워 가요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "버스를 1번부터 차례로 보내요.",
        "",
        "1. 이번 버스 출발 시각 `time = b × interval`까지 도착한 사람을 모두 줄(큐)에 넣어요. 도착 시각이 오름차순이니 **다음에 넣을 사람 번호** `nxt`만 앞으로 옮기면 돼요.",
        "2. 줄 앞에서 `min(capacity, 줄 길이)`명을 꺼내 `answer[사람] = b`로 적어요.",
        "",
        "줄에는 사람 **번호**를 넣어야 나중에 answer의 자리를 알 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "answer = [-1] * n, waiting = 빈 큐, nxt = 0",
        "for b in 1..buses:",
        "    time = b * interval",
        "    while nxt < n and arrivals[nxt] ≤ time:",
        "        waiting 뒤에 nxt 넣기, nxt += 1",
        "    min(capacity, waiting의 길이)번:",
        "        answer[waiting 앞에서 꺼낸 번호] = b",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["버스가 출발하기 전에 줄을 세우는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for bus in range(1, buses + 1):",
            "    time = bus * interval",
            "    while nxt < len(arrivals) and ______:",
            "        waiting.append(nxt)",
            "        nxt += 1",
            "    for _ in range(min(capacity, len(waiting))):",
            "        answer[waiting.popleft()] = bus",
          ].join("\n"),
          javascript: [
            "for (let bus = 1; bus <= buses; bus++) {",
            "  const time = bus * interval;",
            "  while (nxt < arrivals.length && ______) waiting.push(nxt++);",
            "  const count = Math.min(capacity, waiting.length - head);",
            "  for (let i = 0; i < count; i++) answer[waiting[head++]] = bus;",
            "}",
          ].join("\n"),
          java: [
            "for (int bus = 1; bus <= buses; bus++) {",
            "    long time = (long) bus * interval;",
            "    while (nxt < arrivals.length && ______) waiting.offer(nxt++);",
            "    int count = Math.min(capacity, waiting.size());",
            "    for (int i = 0; i < count; i++) answer[waiting.poll()] = bus;",
            "}",
          ].join("\n"),
        },
        caption:
          "buses × interval은 10억까지 커질 수 있어서 long으로 계산해요. Java 배열은 0으로 시작하니 먼저 -1을 채워요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["queue-simulation"],
  signalIds: ["sig-arrival-order"],
  estimatedMinutes: 18,
  xp: 30,
};
