import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [4],
    expected: 4,
    explanation: "1 버림 → 2를 아래로 [3,4,2] → 3 버림 → 4를 아래로 [2,4] → 2 버림 → 4가 남아요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [1],
    expected: 1,
    explanation: "처음부터 한 장뿐이면 그대로 남아요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [2],
    expected: 2,
    failureNote: "1을 버리면 2만 남아요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [6],
    expected: 4,
    failureNote: "카드 6장이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [7],
    expected: 6,
    failureNote: "카드 7장이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [1024],
    expected: 1024,
    failureNote: "2의 거듭제곱 장이에요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [200000],
    expected: 137856,
    failureNote: "카드 20만 장이에요. 리스트 맨 앞을 꺼내는 pop(0)·shift()는 매번 전체를 당겨서 느려요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [199999],
    expected: 137854,
    failureNote: "카드 199,999장이에요.",
  },
]);

export const queueCardShuffle: Problem = {
  id: "c:queue-card-shuffle",
  slug: "queue-card-shuffle",
  source: "curated",
  topic: "queue-deque",
  level: 2,
  title: "한 장 버리고 한 장 넘기기",
  summary: "카드를 버리고 넘기기를 반복했을 때 마지막 카드를 구해요",
  statement: [
    "노디에게 1번부터 n번까지 번호가 적힌 카드 뭉치가 있어요. 1번 카드가 맨 위, n번 카드가 맨 아래예요.",
    "",
    "카드가 한 장 남을 때까지 다음 두 동작을 반복해요.",
    "",
    "1. 맨 위 카드를 **버려요**.",
    "2. 그다음 맨 위 카드를 뭉치의 **맨 아래로 옮겨요**.",
    "",
    "마지막에 남는 카드의 번호를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 카드의 수예요.",
  outputFormat: "마지막에 남는 카드 번호 (정수)",
  constraints: ["1 ≤ n ≤ 200,000"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "카드 수" }],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "마지막 카드 번호" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "맨 위(앞)에서 꺼내고 맨 아래(뒤)로 넣어요 → **큐** 시뮬레이션이에요.",
        "",
        "이 레벨의 핵심은 **빠른 큐**예요. n이 20만이라 앞에서 꺼내는 연산이 느리면 시간 초과가 나요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 1~n을 큐에 넣어요.",
        "2. 큐에 2장 이상 있는 동안: 앞에서 하나 꺼내 버리고, 또 하나 꺼내 뒤에 넣어요.",
        "3. 남은 한 장이 답이에요.",
        "",
        "- Python: `list.pop(0)`은 O(N)이에요. `collections.deque`의 `popleft()`는 O(1)이에요.",
        "- JavaScript: `shift()`도 O(N)이라, 배열과 **앞을 가리키는 번호(head)** 로 큐를 만들어요.",
        "- Java: `ArrayDeque`의 `offer` · `poll`은 O(1)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "queue = [1, 2, ..., n]",
        "while queue의 길이 > 1:",
        "    queue 앞에서 꺼내 버리기",
        "    queue 앞에서 꺼내 queue 뒤에 넣기",
        "return queue에 남은 카드",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["반복 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "cards = deque(range(1, n + 1))",
            "while len(cards) > 1:",
            "    cards.popleft()",
            "    ______",
            "return cards[0]",
          ].join("\n"),
          javascript: [
            "const cards = Array.from({ length: n }, (_, i) => i + 1);",
            "let head = 0;",
            "while (cards.length - head > 1) {",
            "  head += 1;              // 맨 위 카드 버리기",
            "  ______;                 // 다음 카드를 맨 아래로",
            "}",
            "return cards[head];",
          ].join("\n"),
          java: [
            "Queue<Integer> cards = new ArrayDeque<>();",
            "for (int i = 1; i <= n; i++) cards.offer(i);",
            "while (cards.size() > 1) {",
            "    cards.poll();          // 맨 위 카드 버리기",
            "    ______;                // 다음 카드를 맨 아래로",
            "}",
            "return cards.peek();",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["queue-simulation"],
  signalIds: ["sig-arrival-order"],
  estimatedMinutes: 12,
  xp: 20,
};
