import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: ["cbaebabacd", "abc"],
    expected: [0, 6],
    explanation: "0번(cba)과 6번(bac)이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: ["abab", "ab"],
    expected: [0, 1, 2],
    explanation: "ab, ba, ab가 모두 맞아서 [0, 1, 2]예요. 겹쳐도 셉니다.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: ["abc", "abcd"],
    expected: [],
    failureNote: "단어가 글보다 길면 빈 목록이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: ["aaa", "a"],
    expected: [0, 1, 2],
    failureNote: "[0, 1, 2]예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: ["aab", "abb"],
    expected: [],
    failureNote: "글자 종류는 같아도 개수가 달라서 없어요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => "abcab"[(i * i + i) % 5]).join(""), "abcab"],
    expected: [],
    failureNote: "10만 글자예요. 창마다 글자를 새로 세거나 정렬하면 느려요. 한 글자씩 넣고 빼며 개수를 고치세요.",
  },
]);

export const twoPointersAnagramSpots: Problem = {
  id: "c:two-pointers-anagram-spots",
  slug: "two-pointers-anagram-spots",
  source: "curated",
  topic: "two-pointers",
  level: 3,
  title: "글자 섞인 단어 찾기",
  summary: "단어 길이만 한 창을 옮기며 글자 개수가 같은지 비교해요",
  statement: [
    "긴 글 `text` 안에서 단어 `word`의 **글자를 섞은 모양**(애너그램)이 연속으로 나오는 곳을 모두 찾으려고 해요. 예를 들어 `abc`는 `bca`, `cab` …와 같은 글자로 돼 있어요.",
    "",
    "그런 곳의 **시작 위치**를 작은 순서로 담아 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`text`: 긴 글, `word`: 찾는 단어예요. 둘 다 영어 소문자예요.",
  outputFormat: "시작 위치 목록",
  constraints: ["1 ≤ word의 길이 ≤ text의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      { name: "text", type: { python: "str", javascript: "string", java: "String" }, description: "긴 글" },
      { name: "word", type: { python: "str", javascript: "string", java: "String" }, description: "찾는 단어" },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "시작 위치들",
    },
  },
  starterCode: {
    python: ["def solution(text, word):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(text, word) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(String text, String word) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 3000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["단어 길이만큼의 **연속 구간**을 모두 확인 → **고정 길이 창** + 글자 개수 세기예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 단어의 글자 개수 `need[26]`을 세요.",
        "2. 글의 창(길이 m)의 글자 개수 `have[26]`을 유지해요. 오른쪽 글자를 넣고, 창이 m보다 길어지면 왼쪽 글자를 빼요.",
        "3. 창 길이가 m일 때 `have == need`면 시작 위치를 기록해요.",
        "",
        "비교는 26칸짜리라 매번 해도 빨라요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "need = word의 글자 개수, have = [0]*26",
        "for i, c in enumerate(text):",
        "    have[c] += 1",
        "    if i >= m: have[text[i - m]] -= 1",
        "    if i >= m - 1 and have == need: 결과에 i - m + 1 추가",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["창에서 빠지는 글자를 처리하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i, c in enumerate(text):",
            "    have[ord(c) - 97] += 1",
            "    if i >= m:",
            "        have[______] -= 1",
            "    if i >= m - 1 and have == need:",
            "        result.append(i - m + 1)",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < text.length; i++) {",
            "  have[text.charCodeAt(i) - 97]++;",
            "  if (i >= m) have[______]--;",
            "  if (i >= m - 1 && have.every((v, j) => v === need[j])) result.push(i - m + 1);",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < text.length(); i++) {",
            "    have[text.charAt(i) - 'a']++;",
            "    if (i >= m) have[______]--;",
            "    if (i >= m - 1 && Arrays.equals(have, need)) answer.add(i - m + 1);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["fixed-window"],
  signalIds: ["sig-contiguous-window"],
  estimatedMinutes: 15,
  xp: 30,
};
