import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: ["adobecodebanc", "abc"],
    expected: 4,
    explanation: "banc로 4예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: ["a", "aa"],
    expected: 0,
    explanation: "a가 두 개 필요한데 하나뿐이라 0이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: ["a", "a"],
    expected: 1,
    failureNote: "한 가게로 충분해요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: ["aaflslflsldkalskaaa", "aaa"],
    expected: 3,
    failureNote: "끝의 aaa로 3이에요. 개수까지 맞춰야 해요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: ["abc", "cba"],
    expected: 3,
    failureNote: "전체 3이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [
      Array.from({ length: 100000 }, (_, i) => "abcdefghijklmnopqrstuvwxyz"[(i * 7919) % 26]).join(""),
      "thequickbrownfoxjumps",
    ],
    expected: 37,
    failureNote: "10만 가게예요. 시작점마다 끝까지 보면 시간 초과예요.",
  },
]);

export const twoPointersCoverWindow: Problem = {
  id: "c:two-pointers-cover-window",
  slug: "two-pointers-cover-window",
  source: "curated",
  topic: "two-pointers",
  level: 5,
  title: "모든 재료가 들어간 가장 짧은 구간",
  summary: "모자란 재료 수를 세며 창을 늘리고, 다 모이면 왼쪽을 줄여요",
  statement: [
    "시장 골목에 가게가 한 줄로 있고, `street`의 i번째 글자는 i번 가게가 파는 재료예요. 노디의 요리에는 재료 목록 `recipe`가 필요해요 (같은 재료가 여러 번 필요할 수 있어요).",
    "",
    "**연속한 가게들**만 들러 필요한 재료를 모두(개수까지) 살 수 있는 **가장 짧은 구간의 길이**를 반환해 주세요. 불가능하면 0이에요.",
  ].join("\n"),
  inputFormat: "`street`: 가게별 재료, `recipe`: 필요한 재료예요. 둘 다 영어 소문자예요.",
  outputFormat: "가장 짧은 구간의 길이 (불가능하면 0)",
  constraints: ["1 ≤ street의 길이 ≤ 100,000", "1 ≤ recipe의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      { name: "street", type: { python: "str", javascript: "string", java: "String" }, description: "가게별 재료" },
      { name: "recipe", type: { python: "str", javascript: "string", java: "String" }, description: "필요한 재료" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 짧은 길이" },
  },
  starterCode: {
    python: ["def solution(street, recipe):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(street, recipe) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String street, String recipe) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**연속 구간** + '모두 포함하는 **가장 짧은**' → **늘였다 줄이는 창** + 개수 세기예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `need[재료]` = 필요한 개수, `missing` = 아직 모자란 재료의 총 개수(= recipe 길이)",
        "2. 오른쪽 가게를 넣을 때 `need[c] > 0`이면 `missing -= 1`, 그리고 `need[c] -= 1` (음수면 남는 재료)",
        "3. `missing == 0`이면 다 모였어요. 답을 갱신하고 왼쪽을 빼요: `need[left] += 1`, 그 값이 양수가 되면 다시 모자라요(`missing += 1`).",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "need = recipe의 개수, missing = len(recipe), l = 0",
        "for r, c in enumerate(street):",
        "    if need[c] > 0: missing -= 1",
        "    need[c] -= 1",
        "    while missing == 0:",
        "        best = min(best, r - l + 1)",
        "        need[street[l]] += 1",
        "        if need[street[l]] > 0: missing += 1",
        "        l += 1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["왼쪽을 뺄 때 다시 모자라게 되는지 확인하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while missing == 0:",
            "    best = min(best, r - l + 1)",
            "    need[street[l]] += 1",
            "    if ______:",
            "        missing += 1",
            "    l += 1",
          ].join("\n"),
          javascript: [
            "while (missing === 0) {",
            "  best = Math.min(best, r - l + 1);",
            "  const c = street.charCodeAt(l) - 97;",
            "  need[c]++;",
            "  if (______) missing++;",
            "  l++;",
            "}",
          ].join("\n"),
          java: [
            "while (missing == 0) {",
            "    best = Math.min(best, r - l + 1);",
            "    int c = street.charAt(l) - 'a';",
            "    need[c]++;",
            "    if (______) missing++;",
            "    l++;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["variable-window"],
  signalIds: ["sig-contiguous-window"],
  estimatedMinutes: 30,
  xp: 50,
};
