import type { Problem } from "@/types/content";

export const twoPointersFruitBasket: Problem = {
  id: "c:two-pointers-fruit-basket",
  slug: "two-pointers-fruit-basket",
  source: "curated",
  topic: "two-pointers",
  level: 4,
  title: "바구니 k개로 과일 따기",
  summary: "창 안의 과일 종류가 k개를 넘으면 왼쪽을 줄여요",
  statement: [
    "과일나무가 한 줄로 서 있고, `trees`의 i번째 글자는 i번 나무의 과일 종류예요. 노디는 **바구니 k개**를 들고, 바구니 하나에는 **한 종류**의 과일만 담아요.",
    "",
    "**연속한 나무들**에서 과일을 하나씩 딸 때, 딸 수 있는 과일의 **최대 개수**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`trees`: 나무마다 과일 종류(영어 소문자), `k`: 바구니 수예요.",
  outputFormat: "딸 수 있는 최대 개수",
  constraints: ["1 ≤ trees의 길이 ≤ 100,000", "1 ≤ k ≤ 26"],
  signature: {
    name: "solution",
    params: [
      { name: "trees", type: { python: "str", javascript: "string", java: "String" }, description: "나무별 과일 종류" },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "바구니 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 개수" },
  },
  starterCode: {
    python: ["def solution(trees, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(trees, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String trees, int k) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["abaccc", 2],
      expected: 4,
      explanation: "accc(a, c 두 종류)로 4개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: ["aaaa", 1],
      expected: 4,
      explanation: "한 종류뿐이라 전부 4개예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: ["abc", 3],
      expected: 3,
      failureNote: "바구니가 넉넉해서 3개예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: ["abcabcbb", 2],
      expected: 4,
      failureNote: "bcbb로 4개예요. 종류가 넘치면 창 안의 개수가 0이 될 때까지 왼쪽을 줄여야 해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: ["z", 5],
      expected: 1,
      failureNote: "나무 한 그루예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from(
          { length: 100000 },
          (_, i) => "abcdefgh"[Math.floor(i / 7) % 8 === 7 ? (i * 3) % 8 : Math.floor(i / 7) % 8],
        ).join(""),
        3,
      ],
      expected: 21,
      failureNote: "나무 10만 그루예요. 시작점마다 끝까지 보면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**연속 구간** + '종류가 k개 **이하**인 **가장 긴**' → **늘였다 줄이는 창** + 종류별 개수 세기예요."].join(
        "\n",
      ),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 창 안의 과일 개수를 dict `count`로 세요. `len(count)`가 종류 수예요.",
        "2. 오른쪽 나무를 넣고, 종류가 k를 넘으면 왼쪽 나무를 빼며 줄여요. 개수가 0이 된 종류는 dict에서 지워요.",
        "3. 창 길이로 답을 갱신해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l = 0, count = {}, best = 0",
        "for r, c in enumerate(trees):",
        "    count[c] += 1",
        "    while len(count) > k:",
        "        count[trees[l]] -= 1 (0이면 지우기); l += 1",
        "    best = max(best, r - l + 1)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["종류가 넘칠 때 줄이는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while len(count) > k:",
            "    left = trees[l]",
            "    count[left] -= 1",
            "    if ______:",
            "        del count[left]",
            "    l += 1",
          ].join("\n"),
          javascript: [
            "while (count.size > k) {",
            "  const left = trees[l];",
            "  count.set(left, count.get(left) - 1);",
            "  if (______) count.delete(left);",
            "  l++;",
            "}",
          ].join("\n"),
          java: [
            "while (kinds > k) {",
            "    int left = trees.charAt(l) - 'a';",
            "    count[left]--;",
            "    if (______) kinds--;",
            "    l++;",
            "}",
          ].join("\n"),
        },
        caption: "Java는 26칸 배열로 개수를 세고, 종류 수를 따로 들고 다녀요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["variable-window"],
  signalIds: ["sig-contiguous-window"],
  estimatedMinutes: 18,
  xp: 40,
};
