import type { Problem } from "@/types/content";

export const twoPointersPalindromeNote: Problem = {
  id: "c:two-pointers-palindrome-note",
  slug: "two-pointers-palindrome-note",
  source: "curated",
  topic: "two-pointers",
  level: 1,
  title: "거꾸로 읽어도 같은 쪽지",
  summary: "양 끝에서 글자만 골라 비교하며 가운데로 좁혀 와요",
  statement: [
    "노디가 받은 쪽지 `note`가 **회문**인지 확인하려고 해요. 회문은 앞에서 읽어도 뒤에서 읽어도 같은 글이에요.",
    "",
    "이때 **영어 글자와 숫자만** 보고, 대문자와 소문자는 **같은 글자**로 봐요. 띄어쓰기나 문장 부호는 무시해요.",
    "",
    "회문이면 `true`, 아니면 `false`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`note`: 영어 글자, 숫자, 띄어쓰기, 문장 부호로 된 쪽지예요.",
  outputFormat: "회문인지 (참/거짓)",
  constraints: ["1 ≤ note의 길이 ≤ 200,000"],
  signature: {
    name: "solution",
    params: [{ name: "note", type: { python: "str", javascript: "string", java: "String" }, description: "쪽지" }],
    returns: { type: { python: "bool", javascript: "boolean", java: "boolean" }, description: "회문인지" },
  },
  starterCode: {
    python: ["def solution(note):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(note) {", "  let answer = false;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public boolean solution(String note) {",
      "        boolean answer = false;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["A man, a plan, a canal: Panama"],
      expected: true,
      explanation: "글자만 모으면 amanaplanacanalpanama로 회문이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: ["race a car"],
      expected: false,
      explanation: "raceacar는 뒤집으면 racaecar라 아니에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [" .,"],
      expected: true,
      failureNote: "글자가 하나도 없으면 빈 글이라 회문이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: ["0P"],
      expected: false,
      failureNote: "숫자 0과 글자 P는 달라요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["No 'x' in Nixon"],
      expected: true,
      failureNote: "대소문자를 무시하면 회문이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "edge",
      args: ["a"],
      expected: true,
      failureNote: "한 글자는 회문이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        (() => {
          const h = Array.from({ length: 50000 }, (_, i) => "Ab1, "[(i * 7) % 5]).join("");
          return h + [...h].reverse().join("");
        })(),
      ],
      expected: true,
      failureNote:
        "10만 글자예요. 글자만 걸러 새 문자열을 만들고 뒤집어도 되지만, 양 끝에서 비교하면 추가 공간이 없어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["앞과 뒤를 **짝지어 비교** → 양 끝에 손가락을 두고 가운데로 좁히는 **두 포인터**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `l = 0`, `r = 끝`에서 시작해요.",
        "2. `l`이 글자·숫자가 아니면 오른쪽으로, `r`이 글자·숫자가 아니면 왼쪽으로 건너뛰어요.",
        "3. 둘 다 글자면 소문자로 바꿔 비교해요. 다르면 false, 같으면 둘 다 한 칸씩 안으로.",
        "4. 만나면 true예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l, r = 0, n - 1",
        "while l < r:",
        "    if note[l]이 글자가 아니면: l += 1; continue",
        "    if note[r]이 글자가 아니면: r -= 1; continue",
        "    if 소문자(note[l]) != 소문자(note[r]): return false",
        "    l += 1; r -= 1",
        "return true",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["글자가 아닌 칸을 건너뛰는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while l < r:",
            "    if not note[l].isalnum():",
            "        l += 1",
            "    elif ______:",
            "        r -= 1",
            "    elif note[l].lower() != note[r].lower():",
            "        return False",
            "    else:",
            "        l, r = l + 1, r - 1",
          ].join("\n"),
          javascript: [
            "const ok = (c) => /[a-z0-9]/i.test(c);",
            "while (l < r) {",
            "  if (!ok(note[l])) l++;",
            "  else if (______) r--;",
            "  else if (note[l].toLowerCase() !== note[r].toLowerCase()) return false;",
            "  else { l++; r--; }",
            "}",
          ].join("\n"),
          java: [
            "while (l < r) {",
            "    if (!Character.isLetterOrDigit(note.charAt(l))) l++;",
            "    else if (______) r--;",
            "    else if (Character.toLowerCase(note.charAt(l)) != Character.toLowerCase(note.charAt(r))) return false;",
            "    else { l++; r--; }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["opposite-ends"],
  signalIds: ["sig-sorted-pair-ends"],
  estimatedMinutes: 8,
  xp: 10,
};
