import type { Problem } from "@/types/content";

export const twoPointersRainGarden: Problem = {
  id: "c:two-pointers-rain-garden",
  slug: "two-pointers-rain-garden",
  source: "curated",
  topic: "two-pointers",
  level: 5,
  title: "비 온 뒤 고인 물",
  summary: "양쪽에서 지금까지의 가장 높은 벽을 기억하며, 낮은 쪽부터 물을 계산해요",
  statement: [
    "정원에 폭이 1인 돌기둥이 한 줄로 서 있고, `heights[i]`는 i번 기둥의 높이예요. 비가 온 뒤 기둥 사이에 물이 고여요.",
    "",
    "고인 물의 **총량**을 반환해 주세요. 한 칸에 고이는 물은 `min(왼쪽의 가장 높은 기둥, 오른쪽의 가장 높은 기둥) − 그 칸의 높이`예요 (음수면 0).",
  ].join("\n"),
  inputFormat: "`heights`: 기둥 높이들이에요.",
  outputFormat: "고인 물의 총량",
  constraints: ["1 ≤ heights의 길이 ≤ 100,000", "0 ≤ 높이 ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "heights",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "기둥 높이",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "물의 총량" },
  },
  starterCode: {
    python: ["def solution(heights):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(heights) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] heights) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]],
      expected: 6,
      explanation: "모두 6만큼 고여요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [[4, 2, 0, 3, 2, 5]],
      expected: 9,
      explanation: "9만큼 고여요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5]],
      expected: 0,
      failureNote: "기둥 하나면 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[1, 2, 3, 4]],
      expected: 0,
      failureNote: "계속 높아지면 물이 흘러가서 0이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[5, 0, 0, 0, 1]],
      expected: 3,
      failureNote: "왼쪽이 5여도 오른쪽이 1이라 물은 1까지만 고여요. 3이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i * 7919) % 1000)],
      expected: 49936140,
      failureNote: "기둥 10만 개예요. 칸마다 양쪽 최댓값을 새로 찾으면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "칸마다 '왼쪽 최대'와 '오른쪽 최대' 중 **낮은 쪽**이 물 높이 → 양 끝에서 좁혀 오는 **두 포인터**로 한 번에 계산해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `l`, `r`을 양 끝에, `left_max`, `right_max`를 0으로 두어요.",
        "2. `left_max < right_max`면: 왼쪽 칸의 물은 `left_max`로 정해져요(오른쪽엔 더 높은 벽이 있으니까). `left_max`를 갱신하고 물을 더한 뒤 `l += 1`",
        "3. 아니면 오른쪽에서 똑같이 해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l, r = 0, n - 1; lmax = rmax = 0; water = 0",
        "while l <= r:",
        "    if lmax <= rmax:",
        "        lmax = max(lmax, h[l]); water += lmax - h[l]; l += 1",
        "    else:",
        "        rmax = max(rmax, h[r]); water += rmax - h[r]; r -= 1",
        "return water",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["왼쪽 칸의 물을 더하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["if lmax <= rmax:", "    lmax = max(lmax, heights[l])", "    water += ______", "    l += 1"].join(
            "\n",
          ),
          javascript: [
            "if (lmax <= rmax) {",
            "  lmax = Math.max(lmax, heights[l]);",
            "  water += ______;",
            "  l++;",
            "}",
          ].join("\n"),
          java: [
            "if (lmax <= rmax) {",
            "    lmax = Math.max(lmax, heights[l]);",
            "    water += ______;",
            "    l++;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["opposite-ends"],
  signalIds: ["sig-sorted-pair-ends"],
  estimatedMinutes: 30,
  xp: 50,
};
