import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const twoPointersShortestEnough: Problem = {
  id: "c:two-pointers-shortest-enough",
  slug: "two-pointers-shortest-enough",
  source: "curated",
  topic: "two-pointers",
  level: 4,
  title: "도토리 S개를 모으는 가장 짧은 길",
  summary: "오른쪽을 늘려 S를 채우고, 채워지면 왼쪽을 줄여 가장 짧게 만들어요",
  statement: [
    "숲길에 칸마다 도토리가 `acorns[i]`개 떨어져 있어요 (모두 1개 이상). 노디는 **연속한 칸**을 지나며 도토리를 모두 주워요.",
    "",
    "도토리를 **S개 이상** 모으는 가장 짧은 구간의 길이(칸 수)를 반환해 주세요. 전부 주워도 모자라면 0이에요.",
  ].join("\n"),
  inputFormat: "`acorns`: 칸마다 도토리 수, `S`: 모을 개수예요.",
  outputFormat: "가장 짧은 구간의 길이 (불가능하면 0)",
  constraints: ["1 ≤ acorns의 길이 ≤ 100,000", "1 ≤ acorns[i] ≤ 10,000", "1 ≤ S ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "acorns",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "칸마다 도토리",
      },
      { name: "S", type: { python: "int", javascript: "number", java: "int" }, description: "모을 개수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 짧은 길이" },
  },
  starterCode: {
    python: ["def solution(acorns, S):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(acorns, S) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] acorns, int S) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[2, 3, 1, 2, 4, 3], 7],
      expected: 2,
      explanation: "[4, 3]이 7이라 2칸이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[1, 1, 1], 5],
      expected: 0,
      explanation: "다 주워도 3개라 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[10], 7],
      expected: 1,
      failureNote: "한 칸으로 충분해요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 4, 4], 4],
      expected: 1,
      failureNote: "4 한 칸이면 돼요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 2, 3, 4, 5], 11],
      expected: 3,
      failureNote: "[3, 4, 5]가 12로 3칸이에요. 조건을 채운 뒤에도 왼쪽을 계속 줄여 봐야 해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 50) + 1), 1000000],
      expected: 39214,
      failureNote: "10만 칸이에요. 시작점마다 끝까지 더하면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**연속 구간** + '합이 S **이상**인 **가장 짧은**' + 모두 양수 → **늘였다 줄이는 창**이에요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 오른쪽 끝 `r`을 한 칸씩 늘리며 `total`에 더해요.",
        "2. `total ≥ S`인 동안: 길이 `r - l + 1`로 답을 갱신하고, 왼쪽 `acorns[l]`을 빼며 `l += 1`",
        "",
        "양수라서 왼쪽을 줄이면 합이 줄고, 오른쪽을 늘리면 합이 늘어요. 그래서 두 끝이 앞으로만 가도 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l = 0, total = 0, best = 무한대",
        "for r in 0..n-1:",
        "    total += acorns[r]",
        "    while total >= S:",
        "        best = min(best, r - l + 1)",
        "        total -= acorns[l]; l += 1",
        "return best (무한대면 0)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["왼쪽을 줄이는 반복 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for r, x in enumerate(acorns):",
            "    total += x",
            "    while ______:",
            "        best = min(best, r - l + 1)",
            "        total -= acorns[l]",
            "        l += 1",
          ].join("\n"),
          javascript: [
            "for (let r = 0; r < acorns.length; r++) {",
            "  total += acorns[r];",
            "  while (______) {",
            "    best = Math.min(best, r - l + 1);",
            "    total -= acorns[l++];",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int r = 0; r < acorns.length; r++) {",
            "    total += acorns[r];",
            "    while (______) {",
            "        best = Math.min(best, r - l + 1);",
            "        total -= acorns[l++];",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["variable-window"],
  signalIds: ["sig-contiguous-window"],
  visualization: {
    presets: [
      problemPreset(
        "two-pointers-shortest-enough-ex1",
        "tp-min-window",
        "7개 이상 모으는 가장 짧은 창",
        "오른쪽을 늘려 7을 채우고, 채워지면 왼쪽을 줄여요.",
        [[2, 3, 1, 2, 4, 3], 7],
      ),
    ],
  },
  estimatedMinutes: 18,
  xp: 40,
};
