import type { Problem } from "@/types/content";

export const twoPointersSortedSquares: Problem = {
  id: "c:two-pointers-sorted-squares",
  slug: "two-pointers-sorted-squares",
  source: "curated",
  topic: "two-pointers",
  level: 2,
  title: "제곱해도 정렬된 줄",
  summary: "제곱이 가장 큰 수는 양 끝에 있어요. 양 끝을 비교해 뒤에서부터 채워요",
  statement: [
    "정수 목록 `nums`가 오름차순으로 정렬돼 있어요. 음수도 있을 수 있어요.",
    "",
    "각 수를 **제곱**한 값들을 오름차순으로 정렬한 목록을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`nums`: 오름차순 정수 목록이에요.",
  outputFormat: "제곱을 오름차순으로 정렬한 목록",
  constraints: ["1 ≤ nums의 길이 ≤ 100,000", "−10,000 ≤ nums[i] ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "nums",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "오름차순 정수",
      },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "정렬된 제곱" },
  },
  starterCode: {
    python: ["def solution(nums):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(nums) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] nums) {",
      "        int[] answer = new int[nums.length];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[-4, -1, 0, 3, 10]],
      expected: [0, 1, 9, 16, 100],
      explanation: "[0, 1, 9, 16, 100]이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [[-7, -3, 2, 3, 11]],
      expected: [4, 9, 9, 49, 121],
      explanation: "−7의 제곱 49가 3의 제곱 9보다 커요: [4, 9, 9, 49, 121].",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5]],
      expected: [25],
      failureNote: "하나면 [25]예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[-5, -3, -1]],
      expected: [1, 9, 25],
      failureNote: "모두 음수면 거꾸로 돼요: [1, 9, 25].",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[0, 2, 4]],
      expected: [0, 4, 16],
      failureNote: "모두 0 이상이면 순서 그대로예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => Math.floor((i - 50000) / 5))],
      expected: Array.from({ length: 100000 }, (_, i) => Math.floor((i - 50000) / 5))
        .map((x) => x * x)
        .sort((a, b) => a - b),
      failureNote: "10만 개예요. 제곱해서 다시 정렬해도 되지만, 양 끝에서 채우면 O(N)이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "절댓값이 가장 큰 수는 **양 끝** 중 하나에 있어요 → 양 끝을 비교해 큰 제곱부터 뒤에서 채우는 **두 포인터**예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `l = 0`, `r = n - 1`, 결과를 **뒤에서부터** 채울 위치 `k = n - 1`",
        "2. `nums[l]²`과 `nums[r]²` 중 큰 쪽을 `result[k]`에 넣고, 그쪽 포인터를 안으로 옮겨요.",
        "3. `k -= 1`을 반복해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l, r, k = 0, n - 1, n - 1",
        "while l <= r:",
        "    if |nums[l]| > |nums[r]|: result[k] = nums[l]²; l += 1",
        "    else: result[k] = nums[r]²; r -= 1",
        "    k -= 1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["큰 쪽을 고르는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while l <= r:",
            "    if ______:",
            "        result[k] = nums[l] ** 2",
            "        l += 1",
            "    else:",
            "        result[k] = nums[r] ** 2",
            "        r -= 1",
            "    k -= 1",
          ].join("\n"),
          javascript: [
            "while (l <= r) {",
            "  if (______) {",
            "    result[k] = nums[l] * nums[l];",
            "    l++;",
            "  } else {",
            "    result[k] = nums[r] * nums[r];",
            "    r--;",
            "  }",
            "  k--;",
            "}",
          ].join("\n"),
          java: [
            "for (int k = n - 1; k >= 0; k--) {",
            "    if (______) {",
            "        answer[k] = nums[l] * nums[l];",
            "        l++;",
            "    } else {",
            "        answer[k] = nums[r] * nums[r];",
            "        r--;",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["opposite-ends"],
  signalIds: ["sig-sorted-pair-ends"],
  estimatedMinutes: 10,
  xp: 20,
};
