import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const twoPointersSortedPair: Problem = {
  id: "c:two-pointers-sorted-pair",
  slug: "two-pointers-sorted-pair",
  source: "curated",
  topic: "two-pointers",
  level: 1,
  title: "정렬된 가격표에서 두 개 고르기",
  summary: "합이 작으면 왼쪽을, 크면 오른쪽을 한 칸씩 옮겨요",
  statement: [
    "간식 가격표 `prices`가 **싼 것부터** 정렬돼 있어요. 서로 다른 간식 두 개의 가격 합이 정확히 `target`이 되는 쌍을 찾아, 두 간식의 위치 `[i, j]` (i < j)를 반환해 주세요.",
    "",
    "그런 쌍은 **딱 하나** 있어요.",
  ].join("\n"),
  inputFormat: "`prices`: 오름차순 가격표, `target`: 맞출 합이에요.",
  outputFormat: "두 간식의 위치 [i, j]",
  constraints: ["2 ≤ prices의 길이 ≤ 100,000", "1 ≤ 가격 ≤ 1,000,000", "답은 딱 하나예요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "prices",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "오름차순 가격표",
      },
      { name: "target", type: { python: "int", javascript: "number", java: "int" }, description: "맞출 합" },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "두 위치" },
  },
  starterCode: {
    python: ["def solution(prices, target):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(prices, target) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] prices, int target) {",
      "        int[] answer = new int[0];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[2, 7, 11, 15], 9],
      expected: [0, 1],
      explanation: "2 + 7 = 9라서 [0, 1]이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [[1, 2, 4, 6, 9, 11, 14, 17], 20],
      expected: [3, 6],
      explanation: "6 + 14 = 20이라 [3, 6]이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[3, 5], 8],
      expected: [0, 1],
      failureNote: "둘뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 3, 3, 10], 6],
      expected: [1, 2],
      failureNote: "같은 가격의 서로 다른 간식이에요. [1, 2]예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3, 100], 103],
      expected: [2, 3],
      failureNote: "양 끝을 쓰는 3 + 100이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => i * 2 + 2), 399998],
      expected: [99998, 99999],
      failureNote: "10만 개이고 짝은 맨 끝 두 개예요. 모든 쌍을 비교하면 약 50억 번이라 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**정렬된** 목록 + **두 수의 합** → 양 끝에서 좁혀 오는 **두 포인터**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `l = 0`, `r = n - 1`",
        "2. 합이 target보다 작으면 `l += 1` (더 큰 수로), 크면 `r -= 1` (더 작은 수로)",
        "3. 같으면 `[l, r]`이 답이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l, r = 0, n - 1",
        "while l < r:",
        "    s = prices[l] + prices[r]",
        "    if s == target: return [l, r]",
        "    if s < target: l += 1",
        "    else: r -= 1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["포인터를 옮기는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while l < r:",
            "    s = prices[l] + prices[r]",
            "    if s == target:",
            "        return [l, r]",
            "    if ______:",
            "        l += 1",
            "    else:",
            "        r -= 1",
          ].join("\n"),
          javascript: [
            "while (l < r) {",
            "  const s = prices[l] + prices[r];",
            "  if (s === target) return [l, r];",
            "  if (______) l++;",
            "  else r--;",
            "}",
          ].join("\n"),
          java: [
            "while (l < r) {",
            "    int s = prices[l] + prices[r];",
            "    if (s == target) return new int[] {l, r};",
            "    if (______) l++;",
            "    else r--;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["opposite-ends"],
  signalIds: ["sig-sorted-pair-ends"],
  visualization: {
    presets: [
      problemPreset(
        "two-pointers-sorted-pair-ex2",
        "tp-pair-sum",
        "합이 20인 두 간식",
        "합이 작으면 L을, 크면 R을 옮겨요.",
        [[1, 2, 4, 6, 9, 11, 14, 17], 20],
      ),
    ],
  },
  estimatedMinutes: 8,
  xp: 10,
};
