import type { Problem } from "@/types/content";

export const twoPointersWaterBox: Problem = {
  id: "c:two-pointers-water-box",
  slug: "two-pointers-water-box",
  source: "curated",
  topic: "two-pointers",
  level: 4,
  title: "두 벽 사이 물 가두기",
  summary: "양 끝에서 시작해 더 낮은 벽 쪽을 안으로 옮겨요",
  statement: [
    "나무 벽 N개가 같은 간격으로 서 있고, `walls[i]`는 i번 벽의 높이예요. 벽 **두 개**를 골라 그 사이에 물을 채우면, 물의 양은 `(두 벽 중 낮은 높이) × (두 벽 사이 거리)`예요.",
    "",
    "가둘 수 있는 물의 **최대 양**을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`walls`: 벽 높이들이에요.",
  outputFormat: "물의 최대 양",
  constraints: ["2 ≤ walls의 길이 ≤ 100,000", "0 ≤ 높이 ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      { name: "walls", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "벽 높이" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 양" },
  },
  starterCode: {
    python: ["def solution(walls):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(walls) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] walls) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[1, 8, 6, 2, 5, 4, 8, 3, 7]],
      expected: 49,
      explanation: "1번(8)과 8번(7) 사이: 7 × 7 = 49예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[1, 1]],
      expected: 1,
      explanation: "1 × 1 = 1이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [[4, 3, 2, 1, 4]],
      expected: 16,
      failureNote: "양 끝 4와 4: 4 × 4 = 16이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 2, 100, 100, 2, 1]],
      expected: 100,
      failureNote: "가운데 두 벽은 가깝지만 높아서 100 × 1 = 100이 가장 커요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [[0, 5, 0]],
      expected: 0,
      failureNote: "높이 0 벽이 끼면 물이 안 담겨요. 5와 0은 0이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 10000) + 1)],
      expected: 992540835,
      failureNote: "벽 10만 개예요. 모든 쌍은 약 50억 개라 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**두 개를 골라** 넓이 최대 → 양 끝에서 좁혀 오는 **두 포인터**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `l = 0`, `r = n - 1`에서 넓이를 계산해요.",
        "2. **더 낮은 벽** 쪽을 안으로 옮겨요.",
        "",
        "낮은 벽을 그대로 두고 높은 벽을 옮기면 거리는 줄고 높이는 여전히 낮은 벽 이하라 넓이가 커질 수 없어요. 그래서 낮은 쪽을 버려도 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "l, r, best = 0, n - 1, 0",
        "while l < r:",
        "    best = max(best, min(walls[l], walls[r]) * (r - l))",
        "    if walls[l] < walls[r]: l += 1",
        "    else: r -= 1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["넓이를 계산하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while l < r:",
            "    best = max(best, ______)",
            "    if walls[l] < walls[r]:",
            "        l += 1",
            "    else:",
            "        r -= 1",
          ].join("\n"),
          javascript: [
            "while (l < r) {",
            "  best = Math.max(best, ______);",
            "  if (walls[l] < walls[r]) l++;",
            "  else r--;",
            "}",
          ].join("\n"),
          java: [
            "while (l < r) {",
            "    best = Math.max(best, ______);",
            "    if (walls[l] < walls[r]) l++;",
            "    else r--;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["opposite-ends"],
  signalIds: ["sig-sorted-pair-ends"],
  estimatedMinutes: 18,
  xp: 40,
};
