import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      5,
      [
        [0, 1],
        [1, 2],
        [3, 4],
      ],
    ],
    expected: 2,
    explanation: "{0, 1, 2}와 {3, 4}로 동아리가 2개예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [4, [[0, 1]]],
    expected: 3,
    explanation: "{0, 1}, {2}, {3}이라 3개예요. 혼자인 학생도 동아리예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [1, []],
    expected: 1,
    failureNote: "학생 한 명이면 동아리 하나예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [3, []],
    expected: 3,
    failureNote: "모두 혼자예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [
      6,
      [
        [0, 5],
        [5, 1],
        [1, 4],
        [4, 2],
        [2, 3],
      ],
    ],
    expected: 1,
    failureNote: "모두 한 줄로 이어져 동아리 하나예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      6,
      [
        [0, 1],
        [1, 2],
        [2, 0],
        [3, 4],
        [4, 5],
        [5, 3],
      ],
    ],
    expected: 2,
    failureNote: "삼각형 두 개예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [2000, Array.from({ length: 2000 }, (_, i) => [i, i + 1]).filter(([a]) => a % 10 !== 9)],
    expected: 200,
    failureNote: "10명씩 이어진 동아리가 200개예요.",
  },
]);

export const dfsClubCount: Problem = {
  id: "c:dfs-club-count",
  slug: "dfs-club-count",
  source: "curated",
  topic: "dfs",
  level: 2,
  title: "동아리는 몇 개?",
  summary: "친구로 이어진 무리가 몇 개인지 세요",
  statement: [
    "새싹 학교 학생 `n`명(0번 ~ `n-1`번)의 친구 관계가 `pairs`로 주어져요. `[a, b]`는 a와 b가 서로 친구라는 뜻이에요.",
    "",
    "친구의 친구, 그 친구의 친구…로 **이어진 학생들은 모두 같은 동아리**예요. 친구가 한 명도 없는 학생은 혼자서 동아리 하나예요.",
    "",
    "동아리가 모두 몇 개인지 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 학생 수, `pairs`: `[a, b]` 친구 관계 목록이에요.",
  outputFormat: "동아리 수 (정수)",
  constraints: ["1 ≤ n ≤ 2,000", "0 ≤ pairs의 길이 ≤ 5,000", "a ≠ b"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "학생 수" },
      {
        name: "pairs",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "친구 관계",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "동아리 수" },
  },
  starterCode: {
    python: ["def solution(n, pairs):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, pairs) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] pairs) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ['"이어진 것끼리 한 무리" → **연결 요소**(connected component)의 개수를 세는 문제예요.'].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 인접 리스트를 만들어요.",
        "2. 학생 0번부터 차례로 보면서, **아직 방문하지 않은 학생**을 만나면",
        "   - 새 동아리를 발견한 거예요 → 개수 + 1",
        "   - 그 학생에서 DFS를 돌려 같은 동아리 학생을 모두 방문 표시해요.",
        "3. 이미 방문한 학생은 이미 센 동아리 소속이라 건너뛰어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count = 0",
        "for v in 0..n-1:",
        "    if not visited[v]:",
        "        count += 1",
        "        dfs(v)          # v의 동아리 전체를 방문 표시",
        "return count",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["DFS를 새로 시작할 때마다 동아리가 하나 늘어나요."].join("\n"),
      code: {
        code: {
          python: [
            "count = 0",
            "for v in range(n):",
            "    if ______:",
            "        count += 1",
            "        dfs(v)",
            "return count",
          ].join("\n"),
          javascript: [
            "let count = 0;",
            "for (let v = 0; v < n; v += 1) {",
            "  if (______) {",
            "    count += 1;",
            "    dfs(v);",
            "  }",
            "}",
            "return count;",
          ].join("\n"),
          java: [
            "int count = 0;",
            "for (int v = 0; v < n; v++) {",
            "    if (______) {",
            "        count++;",
            "        dfs(v);",
            "    }",
            "}",
            "return count;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["connected-components"],
  signalIds: ["sig-connected-group"],
  estimatedMinutes: 15,
  xp: 20,
};
