import type { Problem } from "@/types/content";

export const dfsFarthestVillages: Problem = {
  id: "c:dfs-farthest-villages",
  slug: "dfs-farthest-villages",
  source: "curated",
  topic: "dfs",
  level: 5,
  title: "가장 먼 두 마을",
  summary: "트리에서 가장 멀리 떨어진 두 마을 사이의 거리(지름)를 구해요",
  statement: [
    "노디 섬에는 마을이 `n`개(0번 ~ `n-1`번) 있고, 도로 목록 `roads`의 `[a, b]`는 a와 b를 잇는 양방향 도로예요. 도로는 정확히 `n-1`개이고 모든 마을이 이어져 있어서, 두 마을 사이의 길은 **딱 하나**뿐이에요.",
    "",
    "두 마을 사이의 거리는 그 길에서 지나는 **도로 수**예요. **가장 멀리 떨어진 두 마을 사이의 거리**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 마을 수, `roads`: `[a, b]` 도로 목록이에요 (n-1개).",
  outputFormat: "가장 먼 두 마을 사이의 거리 (정수)",
  constraints: ["1 ≤ n ≤ 100,000", "답은 1,000 이하예요."],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "마을 수" },
      {
        name: "roads",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "도로 목록",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 먼 거리" },
  },
  starterCode: {
    python: ["def solution(n, roads):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, roads) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] roads) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        5,
        [
          [0, 1],
          [1, 2],
          [1, 3],
          [3, 4],
        ],
      ],
      expected: 3,
      explanation: "2번과 4번 사이가 2 → 1 → 3 → 4로 도로 3개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [
        4,
        [
          [0, 1],
          [0, 2],
          [0, 3],
        ],
      ],
      expected: 2,
      explanation: "0번에서는 모든 마을이 거리 1이지만, 1번과 2번 사이는 2예요. 0번에서의 거리만 보면 안 돼요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1, []],
      expected: 0,
      failureNote: "마을이 하나면 거리는 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [2, [[1, 0]]],
      expected: 1,
      failureNote: "마을 두 개예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [
        6,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [3, 4],
          [4, 5],
        ],
      ],
      expected: 5,
      failureNote: "한 줄로 이어진 섬이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        7,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [0, 4],
          [4, 5],
          [0, 6],
        ],
      ],
      expected: 5,
      failureNote: "가장 긴 길이 0번을 지나 3번과 5번을 이어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        100000,
        Array.from({ length: 99999 }, (_, k) => {
          const i = k + 1;
          return i < 990 ? [i - 1, i] : [i % 990, i];
        }),
      ],
      expected: 991,
      failureNote: "990개 마을로 된 긴 길에 나머지 마을이 가지처럼 붙어 있어요. 마을마다 따로 거리를 재면 너무 느려요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [100000, Array.from({ length: 99999 }, (_, k) => [Math.floor(k / 3), k + 1])],
      expected: 21,
      failureNote: "마을마다 가지가 세 개씩 뻗은 섬이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"길이 딱 하나뿐" → **트리**예요. 트리에서 가장 먼 두 노드 사이 거리를 **지름**이라고 해요.',
        "",
        "모든 마을에서 한 번씩 DFS를 돌리면 N번 × N = 너무 느려요. **DFS 두 번**이면 충분해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 아무 마을(0번)에서 DFS로 거리를 재서, **가장 먼 마을 A**를 찾아요.",
        "2. A에서 다시 DFS로 거리를 재요. 그중 **가장 큰 거리**가 지름이에요.",
        "",
        "트리에서는 어느 마을에서 출발하든, 가장 먼 마을은 지름의 한쪽 끝이 된다는 성질이 있어요.",
        "",
        "트리는 순환이 없으니 `visited` 대신 **어디서 왔는지(parent)** 만 기억해도 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "farthest(s):   # (가장 먼 마을, 그 거리)",
        "    dfs(v, parent, d):",
        "        dist[v] = d",
        "        for w in graph[v]:",
        "            if w != parent: dfs(w, v, d + 1)",
        "    dfs(s, -1, 0)",
        "    return dist가 최대인 마을과 그 거리",
        "A, _ = farthest(0)",
        "_, answer = farthest(A)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["거리를 재는 DFS예요."].join("\n"),
      code: {
        code: {
          python: [
            "def dfs(v, parent, d):",
            "    dist[v] = d",
            "    for w in graph[v]:",
            "        if ______:",
            "            dfs(w, v, d + 1)",
          ].join("\n"),
          javascript: [
            "function dfs(v, parent, d) {",
            "  dist[v] = d;",
            "  for (const w of graph[v]) {",
            "    if (______) dfs(w, v, d + 1);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "void dfs(int v, int parent, int d) {",
            "    dist[v] = d;",
            "    for (int w : graph.get(v)) {",
            "        if (______) dfs(w, v, d + 1);",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["tree-traversal"],
  signalIds: ["sig-tree-structure"],
  estimatedMinutes: 30,
  xp: 50,
};
