import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const dfsForestLakes: Problem = {
  id: "c:dfs-forest-lakes",
  slug: "dfs-forest-lakes",
  source: "curated",
  topic: "dfs",
  level: 3,
  title: "숲속 호수 세기",
  summary: "지도 가장자리에 닿지 않는 물 덩어리가 몇 개인지 세요",
  statement: [
    "노디가 숲 지도를 그렸어요. 지도 `forest`는 같은 길이의 문자열 리스트이고, `#`은 땅, `.`은 물이에요.",
    "",
    "물 칸들이 **상하좌우**로 이어져 있으면 한 덩어리예요 (대각선은 이어진 게 아니에요).",
    "",
    "물 덩어리 중 **지도 가장자리(맨 위·맨 아래 줄, 맨 왼쪽·맨 오른쪽 칸)에 한 칸도 닿지 않는 것**만 호수예요. 가장자리에 닿은 물은 숲 밖의 강으로 흘러 나가요.",
    "",
    "호수가 몇 개인지 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`forest`: `#`(땅)과 `.`(물)로 된 문자열 리스트예요.",
  outputFormat: "호수의 개수 (정수)",
  constraints: ["1 ≤ 줄 수, 줄 길이 ≤ 30", "모든 줄의 길이가 같아요", "각 문자는 `#` 또는 `.`이에요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "forest",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "숲 지도",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "호수의 개수" },
  },
  starterCode: {
    python: ["def solution(forest):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(forest) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String[] forest) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["######", "#..#.#", "#..###", "######"]],
      expected: 2,
      explanation: "왼쪽의 네 칸짜리 물과 오른쪽의 한 칸짜리 물, 호수 2개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [["...", ".#.", "..."]],
      expected: 0,
      explanation: "물이 모두 가장자리에 닿아서 호수가 없어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["#"]],
      expected: 0,
      failureNote: "땅 한 칸뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [["."]],
      expected: 0,
      failureNote: "물 한 칸이지만 가장자리예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [["#####", "#...#", "###.#", "#...#", "#.###"]],
      expected: 0,
      failureNote:
        "구불구불한 물이 맨 아래 가장자리에 닿아요. 가장자리에 닿았다고 칠하기를 멈추면, 남은 칸을 호수로 잘못 세요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [["#####", "#.###", "##.##", "#####"]],
      expected: 2,
      failureNote: "대각선으로만 붙은 물은 따로따로예요. 호수 2개예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: [["#######", "#.#.#.#", "#######", "..#.#.#"]],
      expected: 3,
      failureNote: "아래 줄의 물은 가장자리예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 30 }, (_, r) => (r === 0 || r === 29 ? "#".repeat(30) : "#" + ".".repeat(28) + "#"))],
      expected: 1,
      failureNote: "가장자리를 뺀 28×28칸이 모두 물인 커다란 호수 하나예요.",
    },
    {
      id: "hid-7",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 30 }, (_, r) =>
          Array.from({ length: 30 }, (_, c) => (r % 2 === 1 && c % 2 === 1 && r < 29 && c < 29 ? "." : "#")).join(""),
        ),
      ],
      expected: 196,
      failureNote: "한 칸짜리 호수가 바둑판처럼 흩어져 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "상하좌우로 이어진 **덩어리**를 찾아요 → 격자 **DFS**(플러드 필)예요.",
        "",
        "덩어리마다 '가장자리에 닿았나?'를 함께 기록하면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 모든 칸을 차례로 보다가, **아직 안 칠한 물 칸**을 만나면 거기서 DFS로 덩어리 전체를 칠해요.",
        "2. 칠하는 동안 가장자리 칸을 하나라도 만나면 `touches = True`로 적어요.",
        "3. 덩어리를 **끝까지** 칠한 뒤, touches가 False일 때만 호수 수를 1 늘려요.",
        "",
        "가장자리를 만났다고 칠하기를 멈추면 안 돼요. 남은 칸이 나중에 새 덩어리처럼 보여서 잘못 세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function fill(r, c):          # 덩어리가 가장자리에 닿았는지 돌려준다",
        "    seen[r][c] = true",
        "    touches = (r, c가 가장자리)",
        "    for 상하좌우 (nr, nc):",
        "        지도 안이고, 물이고, 아직 안 칠했으면:",
        "            if fill(nr, nc): touches = true",
        "    return touches",
        "",
        "for 모든 칸: 안 칠한 물이면 if not fill(r, c): lakes += 1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["이웃 칸을 칠하면서 가장자리 여부를 모으는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def fill(r, c):",
            "    seen[r][c] = True",
            "    touches = r == 0 or r == rows - 1 or c == 0 or c == cols - 1",
            "    for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):",
            "        nr, nc = r + dr, c + dc",
            '        if 0 <= nr < rows and 0 <= nc < cols and forest[nr][nc] == "." and not seen[nr][nc]:',
            "            if ______:",
            "                touches = True",
            "    return touches",
          ].join("\n"),
          javascript: [
            "function fill(r, c) {",
            "  seen[r][c] = true;",
            "  let touches = r === 0 || r === rows - 1 || c === 0 || c === cols - 1;",
            "  for (const [dr, dc] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {",
            "    const nr = r + dr, nc = c + dc;",
            '    if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && forest[nr][nc] === "." && !seen[nr][nc]) {',
            "      if (______) touches = true;",
            "    }",
            "  }",
            "  return touches;",
            "}",
          ].join("\n"),
          java: [
            "boolean fill(int r, int c) {",
            "    seen[r][c] = true;",
            "    boolean touches = r == 0 || r == rows - 1 || c == 0 || c == cols - 1;",
            "    for (int[] d : DIRS) {",
            "        int nr = r + d[0], nc = c + d[1];",
            "        if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && forest[nr].charAt(nc) == '.' && !seen[nr][nc]) {",
            "            if (______) touches = true;",
            "        }",
            "    }",
            "    return touches;",
            "}",
          ].join("\n"),
        },
        caption:
          "`touches = touches or fill(...)`(Java·JavaScript는 `||`)처럼 쓰면 touches가 이미 참일 때 fill을 부르지 않아 칠하기가 멈춰요. 먼저 fill을 부르세요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["connected-components", "grid-flood-fill"],
  signalIds: ["sig-connected-group", "sig-grid-neighbors"],
  visualization: {
    presets: [
      problemPreset(
        "forest-lakes-fill",
        "grid-dfs",
        "물 덩어리 칠하기 (1을 물로 봐요)",
        "이어진 물 칸을 끝까지 칠하는 모습이에요. 가운데 덩어리는 가장자리에 닿지 않아요.",
        [["0000", "0110", "0100", "0001"]],
      ),
    ],
  },
  estimatedMinutes: 18,
  xp: 30,
};
