import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      4,
      [
        [0, 1],
        [1, 2],
        [2, 0],
        [2, 3],
      ],
    ],
    expected: true,
    explanation: "0 → 1 → 2 → 0으로 한 바퀴 돌 수 있어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "basic",
    args: [
      4,
      [
        [0, 1],
        [1, 2],
        [1, 3],
      ],
    ],
    expected: false,
    explanation: "나뭇가지 모양이라 어디서 출발해도 왔던 길로만 돌아올 수 있어요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [1, []],
    expected: false,
    failureNote: "쉼터 하나, 길이 없어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [2, [[0, 1]]],
    expected: false,
    failureNote:
      "0 → 1 → 0은 같은 길을 두 번 걷는 거라 한 바퀴가 아니에요. 방금 온 쉼터를 '이미 방문했다'고 착각하면 틀려요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      6,
      [
        [0, 1],
        [2, 3],
        [3, 4],
        [4, 2],
      ],
    ],
    expected: true,
    failureNote: "한 바퀴 코스가 0번과 떨어진 곳에 있어요. 모든 쉼터에서 탐색을 시작해야 해요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [
      6,
      [
        [0, 1],
        [2, 3],
        [3, 4],
        [4, 5],
      ],
    ],
    expected: false,
    failureNote: "떨어진 나뭇가지 두 개예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, Array.from({ length: 999 }, (_, i) => [i, i + 1])],
    expected: false,
    failureNote: "쉼터 1,000개가 한 줄로 이어져 있어요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, [...Array.from({ length: 999 }, (_, i) => [i, i + 1]), [999, 0]]],
    expected: true,
    failureNote: "한 줄 끝을 처음과 이어 커다란 한 바퀴가 됐어요.",
  },
  {
    id: "hid-7",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, Array.from({ length: 999 }, (_, i) => [((i * 38) % 999) + 1, 0])],
    expected: false,
    failureNote: "쉼터 0에 나머지가 모두 이어진 별 모양이에요.",
  },
]);

export const dfsLoopTrail: Problem = {
  id: "c:dfs-loop-trail",
  slug: "dfs-loop-trail",
  source: "curated",
  topic: "dfs",
  level: 4,
  title: "한 바퀴 산책로",
  summary: "같은 길을 되밟지 않고 출발점으로 돌아오는 산책 코스가 있는지 찾아요",
  statement: [
    "노디네 공원에는 쉼터가 `n`개 있고, 0번부터 `n-1`번까지 번호가 있어요. 산책로 `trails`의 `[a, b]`는 a와 b를 양쪽으로 잇는 길이에요.",
    "",
    "노디는 **한 바퀴 코스**를 찾고 있어요. 어떤 쉼터에서 출발해, **같은 길을 두 번 걷지 않고** 다른 쉼터들을 지나 출발한 쉼터로 돌아오는 코스예요.",
    "",
    "공원에 한 바퀴 코스가 하나라도 있으면 `true`, 없으면 `false`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 쉼터 수, `trails`: `[a, b]` 산책로 목록이에요.",
  outputFormat: "`true` 또는 `false`",
  constraints: ["1 ≤ n ≤ 1,000", "0 ≤ trails의 길이 ≤ 3,000", "a ≠ b, 같은 두 쉼터를 잇는 길은 하나뿐이에요"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "쉼터 수" },
      {
        name: "trails",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "산책로 목록",
      },
    ],
    returns: { type: { python: "bool", javascript: "boolean", java: "boolean" }, description: "한 바퀴 코스가 있는지" },
  },
  starterCode: {
    python: ["def solution(n, trails):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, trails) {", "  let answer = false;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public boolean solution(int n, int[][] trails) {",
      "        boolean answer = false;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "그래프에 **사이클**(순환)이 있는지 찾아요 → **DFS로 사이클 판별**이에요.",
        "",
        "길에 방향이 없어서, 방향 그래프와는 조금 다르게 판단해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "DFS로 내려가다가 **이미 방문한 쉼터**를 다시 만나면 한 바퀴가 있다는 뜻이에요. 단, 한 가지 예외가 있어요.",
        "",
        "- 방금 **나를 부른 쉼터**(부모)는 당연히 방문했어요. 그 길은 방금 걸어온 길이라 사이클이 아니에요. 그래서 `dfs(u, parent)`로 부모를 함께 넘기고, 부모는 건너뛰어요.",
        "",
        "공원이 여러 조각일 수 있으니, 아직 방문하지 않은 **모든 쉼터**에서 DFS를 시작해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function dfs(u, parent):",
        "    visited[u] = true",
        "    for v in graph[u]:",
        "        if v == parent: continue",
        "        if visited[v]: return true      # 다른 길로 다시 만남",
        "        if dfs(v, u): return true",
        "    return false",
        "",
        "for s in 0..n-1:",
        "    if not visited[s] and dfs(s, -1): return true",
        "return false",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["방금 걸어온 길을 사이클로 착각하지 않게 하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def dfs(u, parent):",
            "    visited[u] = True",
            "    for v in graph[u]:",
            "        if ______:",
            "            continue",
            "        if visited[v]:",
            "            return True",
            "        if dfs(v, u):",
            "            return True",
            "    return False",
          ].join("\n"),
          javascript: [
            "function dfs(u, parent) {",
            "  visited[u] = true;",
            "  for (const v of graph[u]) {",
            "    if (______) continue;",
            "    if (visited[v]) return true;",
            "    if (dfs(v, u)) return true;",
            "  }",
            "  return false;",
            "}",
          ].join("\n"),
          java: [
            "boolean dfs(int u, int parent) {",
            "    visited[u] = true;",
            "    for (int v : graph.get(u)) {",
            "        if (______) continue;",
            "        if (visited[v]) return true;",
            "        if (dfs(v, u)) return true;",
            "    }",
            "    return false;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["cycle-detection"],
  signalIds: ["sig-path-exists", "sig-relations-given"],
  estimatedMinutes: 20,
  xp: 40,
};
