import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      5,
      [
        [0, 1],
        [1, 2],
        [3, 1],
        [2, 0],
        [3, 4],
      ],
      0,
    ],
    expected: [1, 2],
    explanation: "0 → 1 → 2 → 0으로 돌 수 있어요. 3과 4로 가는 길은 없어요 (3 → 1은 반대 방향이에요).",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [
      5,
      [
        [0, 1],
        [3, 4],
      ],
      4,
    ],
    expected: [],
    explanation: "4에서 나가는 도로가 없어요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      3,
      [
        [1, 0],
        [2, 0],
      ],
      0,
    ],
    expected: [],
    failureNote: "도로가 모두 0으로 들어오기만 해요. 방향을 무시하면 틀려요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      2,
      [
        [0, 1],
        [1, 0],
      ],
      1,
    ],
    expected: [0],
    failureNote: "돌고 돌아 출발 도시로 돌아와도 start는 넣지 않아요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [
      7,
      [
        [0, 1],
        [0, 2],
        [2, 3],
        [4, 5],
        [5, 6],
        [6, 4],
      ],
      0,
    ],
    expected: [1, 2, 3],
    failureNote: "갈 수 없는 순환 도로가 따로 있어요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, Array.from({ length: 999 }, (_, i) => [i, i + 1]), 0],
    expected: Array.from({ length: 999 }, (_, i) => i + 1),
    failureNote: "도시 1,000개가 한 줄로 이어져 있어요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [
      1000,
      Array.from({ length: 5000 }, (_, e) => [
        e % 1000,
        ((e % 1000) + [1, 7, 31, 211, 499][Math.floor(e / 1000)]) % 1000,
      ]),
      500,
    ],
    expected: Array.from({ length: 1000 }, (_, i) => i).filter((i) => i !== 500),
    failureNote: "순환 도로가 가득해요. 방문 표시를 하지 않으면 영원히 돌아요.",
  },
]);

export const dfsOneWayTour: Problem = {
  id: "c:dfs-one-way-tour",
  slug: "dfs-one-way-tour",
  source: "curated",
  topic: "dfs",
  level: 2,
  title: "일방통행 도시 투어",
  summary: "일방통행 도로만 따라 출발 도시에서 갈 수 있는 도시를 모두 찾아요",
  statement: [
    "노디의 나라에는 도시가 `n`개 있고, 0번부터 `n-1`번까지 번호가 있어요. 도로 `roads`의 `[a, b]`는 **a에서 b로만** 갈 수 있는 일방통행 도로예요.",
    "",
    "노디는 `start` 도시에서 출발해 도로를 몇 번이든 따라갈 수 있어요.",
    "",
    "노디가 갈 수 있는 도시의 번호를 **오름차순**으로 담은 리스트를 반환해 주세요. 출발 도시 `start`는 넣지 않아요.",
  ].join("\n"),
  inputFormat: "`n`: 도시 수, `roads`: `[a, b]`(a → b) 도로 목록, `start`: 출발 도시예요.",
  outputFormat: "갈 수 있는 도시 번호의 오름차순 리스트 (start 제외)",
  constraints: [
    "1 ≤ n ≤ 1,000",
    "0 ≤ roads의 길이 ≤ 5,000",
    "a ≠ b, 같은 도로는 두 번 주어지지 않아요",
    "0 ≤ start < n",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "도시 수" },
      {
        name: "roads",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "일방통행 도로 [a, b]",
      },
      { name: "start", type: { python: "int", javascript: "number", java: "int" }, description: "출발 도시" },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "갈 수 있는 도시 (오름차순)",
    },
  },
  starterCode: {
    python: ["def solution(n, roads, start):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, roads, start) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(int n, int[][] roads, int start) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'출발지에서 **갈 수 있는 곳** 모두' → **DFS**(또는 BFS)로 탐색해요.",
        "",
        "도로에 **방향**이 있으니 인접 리스트에는 a → b 한 방향만 넣어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `graph[a]`에 b를 넣어 방향 인접 리스트를 만들어요.",
        "2. start부터 DFS를 해요. 도시에 도착하면 **방문 표시**를 하고, 아직 안 간 다음 도시로만 가요. 순환 도로가 있어서 방문 표시를 안 하면 끝나지 않아요.",
        "3. 방문한 도시 중 start를 뺀 번호를 오름차순으로 모아요.",
        "",
        "재귀 대신 **스택**을 써도 돼요. 스택에서 꺼낸 도시의 다음 도시 중 안 간 곳을 방문 표시하고 넣어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "visited[start] = true, stack = [start]",
        "while stack이 비어 있지 않은 동안:",
        "    u = stack에서 꺼내기",
        "    for v in graph[u]:",
        "        if not visited[v]:",
        "            visited[v] = true",
        "            stack에 v 넣기",
        "return visited가 true인 도시 중 start를 뺀 번호들",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["스택으로 DFS하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "visited[start] = True",
            "stack = [start]",
            "while stack:",
            "    u = stack.pop()",
            "    for v in graph[u]:",
            "        if ______:",
            "            visited[v] = True",
            "            stack.append(v)",
          ].join("\n"),
          javascript: [
            "visited[start] = true;",
            "const stack = [start];",
            "while (stack.length > 0) {",
            "  const u = stack.pop();",
            "  for (const v of graph[u]) {",
            "    if (______) {",
            "      visited[v] = true;",
            "      stack.push(v);",
            "    }",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "visited[start] = true;",
            "Deque<Integer> stack = new ArrayDeque<>();",
            "stack.push(start);",
            "while (!stack.isEmpty()) {",
            "    int u = stack.pop();",
            "    for (int v : graph.get(u)) {",
            "        if (______) {",
            "            visited[v] = true;",
            "            stack.push(v);",
            "        }",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["path-existence"],
  signalIds: ["sig-path-exists", "sig-relations-given"],
  estimatedMinutes: 12,
  xp: 20,
};
