import type { Problem } from "@/types/content";

export const dfsOrchardSplit: Problem = {
  id: "c:dfs-orchard-split",
  slug: "dfs-orchard-split",
  source: "curated",
  topic: "dfs",
  level: 5,
  title: "과수원 나누기",
  summary: "길 하나를 끊어 두 과수원 무리의 사과 수 차이를 가장 작게 만들어요",
  statement: [
    "노디 마을에는 과수원이 `n`개 있고, 0번부터 `n-1`번까지 번호가 있어요. `apples[i]`는 i번 과수원의 사과 수예요.",
    "",
    "과수원들은 길 `roads`로 이어져 있어요. `[a, b]`는 a와 b를 잇는 길이고, 길은 `n-1`개라서 **모든 과수원이 사이클 없이 하나로 이어진 트리** 모양이에요.",
    "",
    "두 형제가 과수원을 나눠 가지려고 **길 하나를 끊어요**. 그러면 과수원이 두 무리로 나뉘고, 한 사람이 한 무리씩 가져요.",
    "",
    "두 무리의 사과 수 **차이가 가장 작을 때의 차이**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`apples`: 과수원마다의 사과 수, `roads`: `[a, b]` 길 목록(n−1개)이에요.",
  outputFormat: "두 무리의 사과 수 차이의 최솟값 (정수)",
  constraints: [
    "2 ≤ n ≤ 100,000",
    "1 ≤ apples[i] ≤ 10,000",
    "0번 과수원에서 가장 먼 과수원까지 지나는 길은 1,000개 이하예요",
  ],
  signature: {
    name: "solution",
    params: [
      {
        name: "apples",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "과수원마다의 사과 수",
      },
      {
        name: "roads",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "길 목록",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "사과 수 차이의 최솟값" },
  },
  starterCode: {
    python: ["def solution(apples, roads):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(apples, roads) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] apples, int[][] roads) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        [3, 1, 4, 1, 5],
        [
          [0, 1],
          [0, 2],
          [2, 3],
          [2, 4],
        ],
      ],
      expected: 4,
      explanation:
        "사과는 모두 14개예요. 2–4 길을 끊으면 4번 과수원(5개)과 나머지(9개)로 나뉘어 차이가 4예요. 이게 가장 작아요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[5, 5], [[0, 1]]],
      expected: 0,
      explanation: "길이 하나뿐이에요. 5와 5로 나뉘어 차이 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[1, 10], [[1, 0]]],
      expected: 9,
      failureNote: "끊을 수 있는 길이 하나뿐이면 그게 답이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [
        [1, 2, 3, 4],
        [
          [0, 1],
          [1, 2],
          [2, 3],
        ],
      ],
      expected: 2,
      failureNote: "한 줄로 이어진 과수원이에요. 2–3을 끊으면 6과 4로 차이 2예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        [2, 7, 1, 8, 2, 8],
        [
          [3, 0],
          [5, 3],
          [1, 3],
          [4, 1],
          [2, 4],
        ],
      ],
      expected: 8,
      failureNote: "길이 번호 순서로 주어지지 않고, 0번이 가운데 있지도 않아요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        [10, 1, 1, 1, 1],
        [
          [0, 1],
          [0, 2],
          [0, 3],
          [0, 4],
        ],
      ],
      expected: 12,
      failureNote: "사과가 한 과수원에 몰려 있어요. 어디를 끊어도 차이가 커요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 100000 }, (_, i) => ((i * 37) % 10000) + 1),
        Array.from({ length: 99999 }, (_, k) => {
          const i = k + 1;
          return [i, i < 1000 ? i - 1 : i % 1000];
        }),
      ],
      expected: 200000,
      failureNote: "과수원 10만 개예요. 길마다 끊어 보고 사과를 다시 세면 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, () => 1), Array.from({ length: 99999 }, (_, k) => [0, k + 1])],
      expected: 99998,
      failureNote: "0번 과수원에 나머지가 모두 이어진 별 모양이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "과수원들이 **트리**로 이어져 있어요. 트리에서 길 하나를 끊으면 떨어져 나가는 쪽은 **어떤 과수원의 서브트리**예요.",
        "",
        "서브트리마다의 합을 구하는 건 **트리 DFS**로 한 번에 할 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 0번을 뿌리로 보고 DFS해요. `dfs(u, parent)`는 u의 **서브트리 사과 합** s를 돌려줘요. s = apples[u] + (자식마다 dfs 결과의 합).",
        "2. u와 부모 사이 길을 끊으면 두 무리는 s와 `total − s`예요. 차이는 `|total − 2s|`.",
        "3. 뿌리를 뺀 모든 과수원에서 이 차이를 구해 가장 작은 값을 남겨요.",
        "",
        "길마다 끊고 다시 세면 O(N²)이지만, 이렇게 하면 DFS 한 번, O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "total = apples의 합, best = total",
        "function dfs(u, parent):",
        "    s = apples[u]",
        "    for v in graph[u]:",
        "        if v != parent: s += dfs(v, u)",
        "    if parent != -1:",
        "        best = min(best, |total - 2 × s|)",
        "    return s",
        "dfs(0, -1)",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["서브트리 합으로 끊었을 때의 차이를 구하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def dfs(u, parent):",
            "    nonlocal best",
            "    s = apples[u]",
            "    for v in graph[u]:",
            "        if v != parent:",
            "            s += dfs(v, u)",
            "    if parent != -1:",
            "        best = min(best, abs(______))",
            "    return s",
          ].join("\n"),
          javascript: [
            "function dfs(u, parent) {",
            "  let s = apples[u];",
            "  for (const v of graph[u]) {",
            "    if (v !== parent) s += dfs(v, u);",
            "  }",
            "  if (parent !== -1) best = Math.min(best, Math.abs(______));",
            "  return s;",
            "}",
          ].join("\n"),
          java: [
            "int dfs(int u, int parent) {",
            "    int s = apples[u];",
            "    for (int v : graph.get(u)) {",
            "        if (v != parent) s += dfs(v, u);",
            "    }",
            "    if (parent != -1) best = Math.min(best, Math.abs(______));",
            "    return s;",
            "}",
          ].join("\n"),
        },
        caption: "사과는 모두 10억 개 이하라 int로 충분해요 (2 × s도 21억을 넘지 않아요).",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["tree-traversal"],
  signalIds: ["sig-tree-structure"],
  estimatedMinutes: 30,
  xp: 50,
};
