import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const dfsPowerRestore: Problem = {
  id: "c:dfs-power-restore",
  slug: "dfs-power-restore",
  source: "curated",
  topic: "dfs",
  level: 1,
  title: "전기가 들어온 집",
  summary: "발전소에서 전선을 따라 전기가 닿는 집의 수를 세요",
  statement: [
    "정전이 났던 노디 마을에 발전소가 다시 돌아가기 시작했어요. 마을의 집은 `n`채(0번 ~ `n-1`번)이고, 전선 목록 `wires`의 `[a, b]`는 a집과 b집이 전선으로 이어져 있다는 뜻이에요. 전기는 전선을 따라 **양쪽으로** 흘러요.",
    "",
    "발전소는 `plant`번 집에 붙어 있어요. 전선을 따라 전기가 닿는 집은 **발전소 집을 포함해** 모두 몇 채인지 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 집의 수, `wires`: `[a, b]` 전선 목록, `plant`: 발전소가 붙은 집 번호예요.",
  outputFormat: "전기가 들어온 집의 수 (정수)",
  constraints: ["1 ≤ n ≤ 1,000", "0 ≤ wires의 길이 ≤ 3,000", "a ≠ b"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "집의 수" },
      {
        name: "wires",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "전선 목록",
      },
      { name: "plant", type: { python: "int", javascript: "number", java: "int" }, description: "발전소 집" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "전기가 들어온 집 수" },
  },
  starterCode: {
    python: ["def solution(n, wires, plant):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, wires, plant) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] wires, int plant) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        6,
        [
          [0, 1],
          [1, 2],
          [3, 4],
        ],
        0,
      ],
      expected: 3,
      explanation: "0, 1, 2번 집에 전기가 들어와요. 3, 4, 5번은 이어져 있지 않아요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [
        4,
        [
          [0, 1],
          [1, 2],
          [2, 0],
          [2, 3],
        ],
        1,
      ],
      expected: 4,
      explanation: "전선이 고리 모양이어도 집은 한 번씩만 세요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [3, [], 2],
      expected: 1,
      failureNote: "전선이 없으면 발전소 집 한 채뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [1, [], 0],
      expected: 1,
      failureNote: "집이 한 채뿐이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [
        5,
        [
          [4, 3],
          [3, 2],
          [2, 1],
          [1, 0],
        ],
        2,
      ],
      expected: 5,
      failureNote: "가운데에서 시작해도 양쪽 끝까지 닿아요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        4,
        [
          [0, 1],
          [0, 1],
          [2, 3],
        ],
        1,
      ],
      expected: 2,
      failureNote: "같은 전선이 두 번 적혀 있어도 집은 한 번만 세요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [1000, Array.from({ length: 996 }, (_, i) => [i, i + 2]), 0],
      expected: 499,
      failureNote: "짝수 번 집끼리, 홀수 번 집끼리 이어져 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ['"전선을 따라 닿는 곳" = 출발점에서 **갈 수 있는 모든 노드**예요. DFS로 한 번 훑으면 돼요.'].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 전선 목록으로 인접 리스트를 만들어요 (양방향).",
        "2. `plant`에서 DFS를 시작해 닿는 집마다 방문 표시를 해요.",
        "3. 방문 표시가 된 집의 수가 답이에요.",
        "",
        "방문 표시 덕분에 고리 모양 전선이 있어도 같은 집을 두 번 세지 않아요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dfs(v):",
        "    visited[v] = True",
        "    for w in graph[v]:",
        "        if not visited[w]: dfs(w)",
        "dfs(plant)",
        "return visited가 True인 집의 수",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["dfs가 닿은 집 수를 돌려주게 만들 수도 있어요."].join("\n"),
      code: {
        code: {
          python: [
            "def dfs(v):",
            "    visited[v] = True",
            "    count = 1",
            "    for w in graph[v]:",
            "        if not visited[w]:",
            "            count += ______",
            "    return count",
          ].join("\n"),
          javascript: [
            "function dfs(v) {",
            "  visited[v] = true;",
            "  let count = 1;",
            "  for (const w of graph[v]) {",
            "    if (!visited[w]) count += ______;",
            "  }",
            "  return count;",
            "}",
          ].join("\n"),
          java: [
            "int dfs(int v) {",
            "    visited[v] = true;",
            "    int count = 1;",
            "    for (int w : graph.get(v)) {",
            "        if (!visited[w]) count += ______;",
            "    }",
            "    return count;",
            "}",
          ].join("\n"),
        },
        caption: "Java에서는 graph · visited처럼 dfs가 함께 쓰는 값을 Solution의 필드로 두면 편해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["path-existence", "connected-components"],
  signalIds: ["sig-connected-group", "sig-path-exists"],
  visualization: {
    presets: [
      problemPreset("power-ex1", "graph-dfs", "예제 1", "발전소에서 전선을 따라 전기가 퍼지는 모습을 봐요.", [
        6,
        [
          [0, 1],
          [1, 2],
          [3, 4],
        ],
        0,
      ]),
    ],
  },
  estimatedMinutes: 10,
  xp: 10,
};
