import type { Problem } from "@/types/content";

export const dfsTeamSize: Problem = {
  id: "c:dfs-team-size",
  slug: "dfs-team-size",
  source: "curated",
  topic: "dfs",
  level: 5,
  title: "우리 팀은 몇 명?",
  summary: "조직도에서 사람마다 자기 아래 팀원 수(서브트리 크기)를 구해요",
  statement: [
    "노디 회사의 조직도가 `boss` 배열로 주어져요. 직원 `n`명은 0번 ~ `n-1`번이고, `boss[i]`는 i번의 바로 위 상사예요. 대표는 `boss[i] = -1`이에요.",
    "",
    "i번이 이끄는 팀은 **i 자신과, i 아래로 이어진 모든 직원**(부하, 부하의 부하, …)이에요.",
    "",
    "i번째 원소가 **i번이 이끄는 팀의 인원 수**인 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`boss`: 길이 n인 상사 번호 배열이에요. 대표는 한 명이고, 모든 직원은 대표와 이어져 있어요.",
  outputFormat: "길이 n인 팀 인원 수 리스트",
  constraints: ["1 ≤ n ≤ 100,000", "대표에서 가장 아래 직원까지 단계 수는 1,000 이하예요."],
  signature: {
    name: "solution",
    params: [
      {
        name: "boss",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "바로 위 상사 (대표는 -1)",
      },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "직원별 팀 인원 수" },
  },
  starterCode: {
    python: ["def solution(boss):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(boss) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] boss) {",
      "        int[] answer = new int[boss.length];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[-1, 0, 0, 1, 1, 2]],
      expected: [6, 3, 2, 1, 1, 1],
      explanation: "0번 팀은 전체 6명, 1번 팀은 1, 3, 4번으로 3명, 2번 팀은 2, 5번으로 2명이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[-1]],
      expected: [1],
      explanation: "대표 혼자예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1, 2, -1, 2]],
      expected: [1, 2, 4, 1],
      failureNote: "대표가 0번이 아닐 수 있어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[-1, 0, 1, 2, 3]],
      expected: [5, 4, 3, 2, 1],
      failureNote: "한 줄로 이어진 조직이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[-1, 0, 0, 0, 0, 0]],
      expected: [6, 1, 1, 1, 1, 1],
      failureNote: "대표 아래 모두 한 단계예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [[4, 4, 0, 0, -1, 1, 1, 6]],
      expected: [3, 4, 1, 1, 8, 1, 2, 1],
      failureNote: "번호가 섞인 조직도예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i === 0 ? -1 : i < 1000 ? i - 1 : i % 1000))],
      expected: Array.from({ length: 100000 }, (_, i) => (i < 1000 ? 100 * (1000 - i) : 1)),
      failureNote: "10만 명, 1,000단계 조직이에요. 직원마다 위로 거슬러 올라가며 세면 수천만 번이라 느려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '조직도는 **트리**예요. "i 아래 전체"는 i를 뿌리로 하는 **서브트리**예요.',
        "",
        "서브트리 크기는 **자식들의 서브트리 크기를 더한 값 + 1**이라 DFS가 딱 맞아요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `boss` 배열로 **부하 목록**(자녀 목록)을 만들고 대표를 찾아요.",
        "2. `size(v)` = 1 + (v의 부하 w마다 `size(w)`의 합)",
        "3. 대표에서 DFS를 한 번 돌리면서 계산한 값을 `sizes[v]`에 저장해요.",
        "",
        "재귀가 돌아올 때(부하를 다 계산한 **뒤**) 값을 합치는 것이 핵심이에요. 모든 직원을 한 번씩만 방문하니 O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "children = boss 배열로 만든 부하 목록",
        "dfs(v):",
        "    total = 1",
        "    for w in children[v]:",
        "        total += dfs(w)",
        "    sizes[v] = total",
        "    return total",
        "dfs(대표)",
        "return sizes",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["부하들의 팀 크기를 합치는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "def dfs(v):",
            "    total = 1",
            "    for w in children[v]:",
            "        total += ______",
            "    sizes[v] = total",
            "    return total",
          ].join("\n"),
          javascript: [
            "function dfs(v) {",
            "  let total = 1;",
            "  for (const w of children[v]) total += ______;",
            "  sizes[v] = total;",
            "  return total;",
            "}",
          ].join("\n"),
          java: [
            "int dfs(int v) {",
            "    int total = 1;",
            "    for (int w : children.get(v)) total += ______;",
            "    sizes[v] = total;",
            "    return total;",
            "}",
          ].join("\n"),
        },
        caption: "Java에서는 graph · visited처럼 dfs가 함께 쓰는 값을 Solution의 필드로 두면 편해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["tree-traversal"],
  signalIds: ["sig-tree-structure"],
  estimatedMinutes: 30,
  xp: 50,
};
