import type { Problem } from "@/types/content";

export const recursionBulbSignal: Problem = {
  id: "c:recursion-bulb-signal",
  slug: "recursion-bulb-signal",
  source: "curated",
  topic: "recursion",
  level: 2,
  title: "전구 신호 만들기",
  summary: "숫자를 켜진 전구(1)와 꺼진 전구(0)로 된 신호로 바꿔요",
  statement: [
    "노디의 등대는 전구를 한 줄로 켜고 꺼서 숫자를 알려요. 켜진 전구는 `1`, 꺼진 전구는 `0`이고, 숫자는 **2진법**으로 나타내요.",
    "",
    "2진법 신호는 이렇게 만들 수 있어요.",
    "",
    "- n이 0 또는 1이면 신호는 그 숫자 한 글자예요.",
    "- 그렇지 않으면 **n을 2로 나눈 몫의 신호** 뒤에 **n을 2로 나눈 나머지**를 붙여요.",
    "",
    "예를 들어 13의 신호는 6의 신호 `110` 뒤에 13 % 2 = 1을 붙인 `1101`이에요.",
    "",
    "숫자 n의 신호를 문자열로 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 신호로 바꿀 숫자예요.",
  outputFormat: "`0`과 `1`로 된 문자열. 맨 앞은 n이 0일 때만 `0`이에요.",
  constraints: ["0 ≤ n ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "신호로 바꿀 숫자" },
    ],
    returns: { type: { python: "str", javascript: "string", java: "String" }, description: "2진법 신호" },
  },
  starterCode: {
    python: ["def solution(n):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String solution(int n) {",
      '        String answer = "";',
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [13],
      expected: "1101",
      explanation: "13 → 6 → 3 → 1로 줄여 가며 나머지 1, 0, 1을 뒤에 붙여요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [0],
      expected: "0",
      explanation: "0은 전구 하나가 꺼진 신호 `0`이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1],
      expected: "1",
      failureNote: "1도 한 글자 신호예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [2],
      expected: "10",
      failureNote: "2는 1의 신호 뒤에 0을 붙인 `10`이에요. 종료 조건을 n == 0 하나로만 두면 맨 앞에 0이 붙어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [255],
      expected: "11111111",
      failureNote: "전구 8개가 모두 켜져요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [1024],
      expected: "10000000000",
      failureNote: "1 뒤에 0이 10개예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [1000000000],
      expected: "111011100110101100101000000000",
      failureNote: "10억이에요. 재귀 깊이는 30 정도예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'n의 신호'가 'n // 2의 신호'로 정의돼 있어요. 더 작은 같은 문제로 줄어들어요 → **재귀**예요.",
        "",
        "재귀 함수는 **종료 조건**과 **재귀 호출** 두 부분으로 만들어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. **종료 조건**: n이 0 또는 1이면(n < 2) 그 숫자를 문자열로 바로 돌려줘요.",
        "2. **재귀 호출**: `신호(n // 2)`를 구하고, 그 뒤에 `n % 2`를 글자로 붙여서 돌려줘요.",
        "",
        "종료 조건이 n == 0 하나뿐이면 1의 신호가 `01`이 돼 버려요. 멈추는 곳을 정확히 정하는 게 핵심이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function signal(n):",
        "    if n < 2: return str(n)",
        "    return signal(n // 2) + str(n % 2)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["재귀 호출 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def signal(n):",
            "    if n < 2:",
            "        return str(n)",
            "    return signal(n // 2) + ______",
          ].join("\n"),
          javascript: [
            "function signal(n) {",
            "  if (n < 2) return String(n);",
            "  return signal(Math.floor(n / 2)) + ______;",
            "}",
          ].join("\n"),
          java: [
            "String signal(int n) {",
            "    if (n < 2) return String.valueOf(n);",
            "    return signal(n / 2) + ______;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursive-definition"],
  signalIds: ["sig-shrink-by-one"],
  estimatedMinutes: 10,
  xp: 20,
};
