import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [3, 5, 100],
    expected: 43,
    explanation: "3^5 = 243이고, 100으로 나눈 나머지는 43이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [2, 0, 7],
    expected: 1,
    explanation: "0시간 뒤에는 처음 세포 1개 그대로예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [5, 3, 1],
    expected: 0,
    failureNote: "1로 나눈 나머지는 항상 0이에요. b가 0일 때도요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [9, 0, 1],
    expected: 0,
    failureNote: "b가 0이어도 m이 1이면 0이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [2, 10, 10000],
    expected: 1024,
    failureNote: "2^10 = 1024예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [10000, 2, 9999],
    expected: 1,
    failureNote: "a가 m보다 커도 돼요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [7, 1000000000, 13],
    expected: 9,
    failureNote: "10억 시간이에요. 한 시간씩 곱하면 시간 초과예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [9999, 999999999, 10000],
    expected: 9999,
    failureNote: "가장 큰 값들이에요. 곱할 때마다 나머지를 구해야 수가 너무 커지지 않아요.",
  },
]);

export const recursionCellDivision: Problem = {
  id: "c:recursion-cell-division",
  slug: "recursion-cell-division",
  source: "curated",
  topic: "recursion",
  level: 4,
  title: "세포 분열 실험",
  summary: "a배씩 불어나는 세포 수를 절반씩 나눠 빠르게 계산해요",
  statement: [
    "노디의 실험실에서 세포 1개를 배양해요. 세포는 1시간마다 정확히 **a배**로 불어나요.",
    "",
    "실험실 표시판은 m보다 작은 숫자만 보여 줄 수 있어서, 세포 수를 **m으로 나눈 나머지**를 보여 줘요.",
    "",
    "b시간 뒤 표시판에 나오는 숫자, 즉 **a^b를 m으로 나눈 나머지**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`a`: 한 시간에 불어나는 배수, `b`: 지난 시간, `m`: 나누는 수예요.",
  outputFormat: "a^b를 m으로 나눈 나머지 (정수)",
  constraints: ["1 ≤ a ≤ 10,000", "0 ≤ b ≤ 1,000,000,000", "1 ≤ m ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      { name: "a", type: { python: "int", javascript: "number", java: "int" }, description: "한 시간에 불어나는 배수" },
      { name: "b", type: { python: "int", javascript: "number", java: "int" }, description: "지난 시간" },
      { name: "m", type: { python: "int", javascript: "number", java: "int" }, description: "나누는 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "a^b를 m으로 나눈 나머지" },
  },
  starterCode: {
    python: ["def solution(a, b, m):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(a, b, m) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int a, int b, int m) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "a^b는 **a^(b/2)를 두 번 곱한 것**이에요. 큰 문제가 절반 크기의 같은 문제로 쪼개져요 → **분할 정복**이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`power(e)` = a^e를 m으로 나눈 나머지.",
        "",
        "1. **종료 조건**: e가 0이면 `1 % m` (m이 1이면 0이니까 그냥 1이 아니에요).",
        "2. `half = power(e // 2)`를 **한 번만** 구해요.",
        "3. e가 짝수면 `half × half % m`, 홀수면 거기에 a를 한 번 더 곱하고 `% m`.",
        "",
        "e가 매번 절반이 되니 호출은 30번 정도예요. 곱할 때마다 `% m`을 해서 수를 작게 유지해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function power(e):",
        "    if e == 0: return 1 % m",
        "    half = power(e // 2)",
        "    result = half × half % m",
        "    if e가 홀수: result = result × a % m",
        "    return result",
        "return power(b)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: [
        "절반 문제를 푸는 부분이에요. power를 두 번 부르면 다시 느려지니 한 번만 불러요. 빈칸을 채워 보세요.",
      ].join("\n"),
      code: {
        code: {
          python: [
            "def power(e):",
            "    if e == 0:",
            "        return 1 % m",
            "    half = ______",
            "    result = half * half % m",
            "    if e % 2 == 1:",
            "        result = result * a % m",
            "    return result",
          ].join("\n"),
          javascript: [
            "function power(e) {",
            "  if (e === 0) return 1 % m;",
            "  const half = ______;",
            "  let result = (half * half) % m;",
            "  if (e % 2 === 1) result = (result * a) % m;",
            "  return result;",
            "}",
          ].join("\n"),
          java: [
            "int power(int a, int e, int m) {",
            "    if (e == 0) return 1 % m;",
            "    int half = ______;",
            "    int result = half * half % m;",
            "    if (e % 2 == 1) result = result * (a % m) % m;",
            "    return result;",
            "}",
          ].join("\n"),
        },
        caption: "m이 10,000 이하라 나머지끼리 곱해도 1억을 넘지 않아 int로 충분해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["divide-and-conquer"],
  signalIds: ["sig-self-similar"],
  estimatedMinutes: 20,
  xp: 40,
};
