import type { Problem } from "@/types/content";

export const recursionCookieBoxes: Problem = {
  id: "c:recursion-cookie-boxes",
  slug: "recursion-cookie-boxes",
  source: "curated",
  topic: "recursion",
  level: 2,
  title: "쿠키 똑같이 나누기",
  summary: "두 종류 쿠키를 남김없이 담을 수 있는 가장 큰 상자 크기를 구해요",
  statement: [
    "노디는 초코 쿠키 `a`개와 버터 쿠키 `b`개를 구웠어요. 쿠키를 상자에 나눠 담으려는데, 규칙이 있어요.",
    "",
    "- 모든 상자에는 **같은 개수**의 쿠키가 들어가요.",
    "- 한 상자에는 한 종류 쿠키만 넣어요.",
    "- 쿠키가 남으면 안 돼요.",
    "",
    "상자 하나에 담을 수 있는 쿠키 수의 **최댓값**을 반환해 주세요. (a와 b의 최대공약수예요.)",
    "",
    "> 두 수 a ≥ b의 최대공약수는, b와 `a % b`의 최대공약수와 같아요. 나머지가 0이 되면 그때의 b가 답이에요 (유클리드 호제법).",
  ].join("\n"),
  inputFormat: "`a`, `b`: 두 종류 쿠키의 개수예요.",
  outputFormat: "상자 하나에 담는 쿠키 수의 최댓값 (정수)",
  constraints: ["1 ≤ a, b ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "a", type: { python: "int", javascript: "number", java: "int" }, description: "초코 쿠키 수" },
      { name: "b", type: { python: "int", javascript: "number", java: "int" }, description: "버터 쿠키 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대공약수" },
  },
  starterCode: {
    python: ["def solution(a, b):", "    answer = 1", "    return answer", ""].join("\n"),
    javascript: ["function solution(a, b) {", "  let answer = 1;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int a, int b) {",
      "        int answer = 1;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [12, 18],
      expected: 6,
      explanation: "6개씩 담으면 초코 2상자, 버터 3상자로 남김없이 담겨요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [7, 13],
      expected: 1,
      explanation: "공통으로 나눠떨어지는 수가 1뿐이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [5, 5],
      expected: 5,
      failureNote: "두 수가 같아요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [4, 100],
      expected: 4,
      failureNote: "작은 수가 먼저 주어질 수도 있어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [270, 192],
      expected: 6,
      failureNote: "나머지를 여러 번 구해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "edge",
      args: [1, 1000000000],
      expected: 1,
      failureNote: "한쪽이 1이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [1000000000, 999999999],
      expected: 1,
      failureNote: "10억 근처의 큰 수예요. 1부터 하나씩 나눠 보면 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [701408733, 433494437],
      expected: 1,
      failureNote: "연속한 피보나치 수라서 나머지 계산이 가장 오래 이어져요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '문제에 적힌 성질 "gcd(a, b) = gcd(b, a % b)"가 그대로 **재귀 정의**예요.',
        "",
        "숫자가 계속 작아지다가 나머지가 0이 되는 순간 멈춰요. 멈추는 지점(**종료 조건**)을 정하는 연습이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. **종료 조건**: b가 0이면 a가 답이에요.",
        "2. **재귀 호출**: `gcd(b, a % b)`를 반환해요.",
        "",
        "a < b여도 괜찮아요. 첫 호출에서 `a % b = a`라서 두 수가 자연스럽게 자리를 바꿔요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: ["~~~text", "solution(a, b):", "    if b == 0: return a", "    return solution(b, a % b)", "~~~"].join(
        "\n",
      ),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["def solution(a, b):", "    if b == 0:", "        return a", "    return ______"].join("\n"),
          javascript: ["function solution(a, b) {", "  if (b === 0) return a;", "  return ______;", "}"].join("\n"),
          java: ["public int solution(int a, int b) {", "    if (b == 0) return a;", "    return ______;", "}"].join(
            "\n",
          ),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursive-definition"],
  signalIds: ["sig-self-similar"],
  estimatedMinutes: 10,
  xp: 20,
};
