import type { Problem } from "@/types/content";

export const recursionDigitSum: Problem = {
  id: "c:recursion-digit-sum",
  slug: "recursion-digit-sum",
  source: "curated",
  topic: "recursion",
  level: 1,
  title: "숫자 조각 더하기",
  summary: "각 자릿수의 합을 재귀로 구해요",
  statement: [
    "노디는 숫자 블록을 좋아해요. 큰 수 하나를 자릿수 조각으로 쪼개서 조각에 적힌 숫자를 모두 더하려고 해요. 예를 들어 `4096`은 4 + 0 + 9 + 6 = 19예요.",
    "",
    "0 이상의 정수 `n`의 각 자릿수 합을 반환해 주세요.",
    "",
    "> 마지막 자릿수는 `n % 10`, 마지막 자릿수를 뗀 나머지는 `n // 10`(JavaScript는 `Math.floor(n / 10)`)이에요.",
  ].join("\n"),
  inputFormat: "`n`: 0 이상의 정수예요.",
  outputFormat: "자릿수의 합 (정수)",
  constraints: ["0 ≤ n ≤ 10^15"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number" }, description: "정수" }],
    returns: { type: { python: "int", javascript: "number" }, description: "자릿수의 합" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [4096],
      expected: 19,
      explanation: "4 + 0 + 9 + 6 = 19예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [0],
      expected: 0,
      explanation: "0의 자릿수 합은 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [7],
      expected: 7,
      failureNote: "한 자리 수는 자기 자신이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [1000000],
      expected: 1,
      failureNote: "0이 많은 수예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [987654321],
      expected: 45,
      failureNote: "9부터 1까지 더해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [999999999999999],
      expected: 135,
      failureNote: "15자리 수예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "edge",
      args: [1000000000000000],
      expected: 1,
      failureNote: "10의 15제곱이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ['"마지막 자릿수를 떼어 내고, 나머지는 **같은 방법으로**" → 한 단계 작은 같은 문제 → **재귀**예요.'].join(
        "\n",
      ),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. **종료 조건**: n이 한 자리 수(10 미만)면 n 자체가 답이에요.",
        "2. **재귀 호출**: 마지막 자릿수 `n % 10` + (마지막 자리를 뗀 수의 자릿수 합).",
        "",
        "예: f(4096) = 6 + f(409) = 6 + 9 + f(40) = 6 + 9 + 0 + f(4) = 19",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "solution(n):",
        "    if n < 10: return n",
        "    return (n % 10) + solution(n // 10)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["def solution(n):", "    if n < 10:", "        return n", "    return n % 10 + ______"].join("\n"),
          javascript: ["function solution(n) {", "  if (n < 10) return n;", "  return (n % 10) + ______;", "}"].join(
            "\n",
          ),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursive-definition"],
  signalIds: ["sig-shrink-by-one"],
  estimatedMinutes: 8,
  xp: 10,
};
