import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const recursionEchoValley: Problem = {
  id: "c:recursion-echo-valley",
  slug: "recursion-echo-valley",
  source: "curated",
  topic: "recursion",
  level: 1,
  title: "메아리 계곡",
  summary: "내려가며 한 번, 돌아오며 한 번 외친 층 번호를 기록해요",
  statement: [
    "노디가 n층 깊이의 계곡 계단을 탐험해요. 규칙은 이래요.",
    "",
    "- k층에 도착하면 먼저 **k를 외쳐요**.",
    "- 그다음 한 층 아래(k−1층)를 똑같은 규칙으로 모두 탐험하고 돌아와요.",
    "- 돌아오면 k층의 메아리가 울려서 **k를 한 번 더** 듣게 돼요.",
    "- 0층은 바닥이라 아무것도 하지 않고 바로 돌아와요.",
    "",
    "n층에서 시작할 때, 외치고 들은 숫자를 순서대로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 시작하는 층이에요.",
  outputFormat: "외치고 들은 숫자를 순서대로 담은 리스트 (길이 2n)",
  constraints: ["1 ≤ n ≤ 1,000"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "시작하는 층" }],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "외치고 들은 숫자 순서",
    },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(int n) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [3],
      expected: [3, 2, 1, 1, 2, 3],
      explanation: "3, 2, 1을 외치며 내려가고, 바닥에서 돌아오며 1, 2, 3의 메아리를 들어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [1],
      expected: [1, 1],
      explanation: "1층에서 외치고, 0층(바닥)에 갔다 바로 돌아와 메아리를 들어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [2],
      expected: [2, 1, 1, 2],
      failureNote: "2, 1, 1, 2예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [5],
      expected: [5, 4, 3, 2, 1, 1, 2, 3, 4, 5],
      failureNote: "메아리는 가장 깊은 층부터 들려요. 호출 스택이 위에서부터 풀리는 순서예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [10],
      expected: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      failureNote: "10층 계곡이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [1000],
      expected: [...Array.from({ length: 1000 }, (_, i) => 1000 - i), ...Array.from({ length: 1000 }, (_, i) => i + 1)],
      failureNote: "1,000층이에요. 재귀 깊이도 1,000이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'k층 탐험'이 'k−1층 탐험'을 그대로 품고 있어요 → **재귀**예요.",
        "",
        "재귀 호출 **앞**에서 한 일은 내려가면서, **뒤**에서 한 일은 돌아오면서 일어나요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "함수 `echo(k)`를 만들어요.",
        "",
        "1. **종료 조건**: k가 0이면 아무것도 하지 않고 돌아가요.",
        "2. answer에 k를 추가해요 (외치기).",
        "3. `echo(k - 1)`을 불러요 (한 층 아래 탐험).",
        "4. answer에 k를 한 번 더 추가해요 (메아리).",
        "",
        "`echo(n)`을 부른 뒤 answer를 반환하면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function echo(k):",
        "    if k == 0: return        # 바닥",
        "    answer에 k 추가          # 내려가며",
        "    echo(k - 1)",
        "    answer에 k 추가          # 돌아오며",
        "echo(n)",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["외치기와 메아리 사이에 들어갈 한 줄이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def echo(k):",
            "    if k == 0:",
            "        return",
            "    answer.append(k)   # 내려가며",
            "    ______",
            "    answer.append(k)   # 돌아오며",
          ].join("\n"),
          javascript: [
            "function echo(k) {",
            "  if (k === 0) return;",
            "  answer.push(k); // 내려가며",
            "  ______;",
            "  answer.push(k); // 돌아오며",
            "}",
          ].join("\n"),
          java: [
            "void echo(int k, List<Integer> answer) {",
            "    if (k == 0) return;",
            "    answer.add(k);   // 내려가며",
            "    ______;",
            "    answer.add(k);   // 돌아오며",
            "}",
          ].join("\n"),
        },
        caption: "Java는 결과 리스트를 매개변수로 넘겨 재귀 함수들이 함께 채워요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursive-definition"],
  signalIds: ["sig-shrink-by-one"],
  visualization: {
    presets: [
      problemPreset(
        "echo-valley-stack",
        "recursion-factorial",
        "호출 스택이 쌓이고 풀리는 모습",
        "팩토리얼로 봐요. 호출이 쌓이며 내려갔다가, 바닥에서 위부터 차례로 돌아와요. 메아리가 들리는 순서와 같아요.",
        [4],
      ),
    ],
  },
  estimatedMinutes: 8,
  xp: 10,
};
