import type { Problem } from "@/types/content";

export const recursionHailstoneTrip: Problem = {
  id: "c:recursion-hailstone-trip",
  slug: "recursion-hailstone-trip",
  source: "curated",
  topic: "recursion",
  level: 2,
  title: "우박 수 여행",
  summary: "규칙대로 바꾸다 1에 도착하기까지 몇 단계가 걸리는지 구해요",
  statement: [
    "노디가 숫자 여행 놀이를 해요. 양의 정수 `n`에서 출발해 다음 규칙으로 한 걸음씩 옮겨 가요.",
    "",
    "- 짝수면 2로 나눠요.",
    "- 홀수면 3을 곱하고 1을 더해요.",
    "",
    "`1`에 도착하면 여행이 끝나요. 도착하기까지 몇 걸음이 걸리는지 반환해 주세요. 처음부터 `1`이면 0걸음이에요.",
  ].join("\n"),
  inputFormat: "`n`: 출발하는 수예요.",
  outputFormat: "1에 도착하기까지의 걸음 수 (정수)",
  constraints: ["1 ≤ n ≤ 1,000,000", "주어지는 n은 모두 1,000걸음 안에 도착해요."],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number" }, description: "출발하는 수" }],
    returns: { type: { python: "int", javascript: "number" }, description: "걸음 수" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [6],
      expected: 8,
      explanation: "6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1, 8걸음이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [1],
      expected: 0,
      explanation: "이미 1이면 0걸음이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [2],
      expected: 1,
      failureNote: "한 번 나누면 끝나요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [7],
      expected: 16,
      failureNote: "홀수에서 출발해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [27],
      expected: 111,
      failureNote: "작은 수지만 아주 멀리 돌아가요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [1024],
      expected: 10,
      failureNote: "2의 거듭제곱은 나누기만 해요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [837799],
      expected: 524,
      failureNote: "100만 이하에서 가장 긴 여행이에요. 재귀가 500번 넘게 깊어져요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"n에서 도착까지 걸음 수" = 1걸음 + "다음 수에서 도착까지 걸음 수"예요 → **재귀**로 정의할 수 있어요.',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. **종료 조건**: n이 1이면 0.",
        "2. **다음 수**를 규칙으로 구하고, `1 + solution(다음 수)`를 반환해요.",
        "",
        "다음 수가 n보다 커질 때도 있지만, 결국 1에 도착한다는 게 문제에서 보장돼 있어요. 그래서 재귀가 반드시 끝나요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "solution(n):",
        "    if n == 1: return 0",
        "    next = n / 2 (짝수) 또는 3n + 1 (홀수)",
        "    return 1 + solution(next)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["다음 수를 구하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "def solution(n):",
            "    if n == 1:",
            "        return 0",
            "    nxt = n // 2 if n % 2 == 0 else ______",
            "    return 1 + solution(nxt)",
          ].join("\n"),
          javascript: [
            "function solution(n) {",
            "  if (n === 1) return 0;",
            "  const next = n % 2 === 0 ? n / 2 : ______;",
            "  return 1 + solution(next);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursive-definition"],
  signalIds: ["sig-shrink-by-one"],
  estimatedMinutes: 10,
  xp: 20,
};
