import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const recursionHallwayTiles: Problem = {
  id: "c:recursion-hallway-tiles",
  slug: "recursion-hallway-tiles",
  source: "curated",
  topic: "recursion",
  level: 3,
  title: "복도 타일 깔기",
  summary: "1×2 타일과 2×2 타일로 2×n 복도를 채우는 방법의 수를 구해요",
  statement: [
    "노디가 폭 2, 길이 n인 복도에 타일을 깔려고 해요. 쓸 수 있는 타일은 두 종류예요.",
    "",
    "- 1×2 타일: 세로로도, 가로로도 놓을 수 있어요.",
    "- 2×2 타일",
    "",
    "타일이 겹치거나 빈틈이 생기면 안 돼요. 복도를 빈틈없이 채우는 **방법의 수**를 1,000,000,007로 나눈 나머지를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 복도의 길이예요.",
  outputFormat: "채우는 방법의 수를 1,000,000,007로 나눈 나머지 (정수)",
  constraints: ["1 ≤ n ≤ 1,000"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "복도 길이" }],
    returns: {
      type: { python: "int", javascript: "number", java: "int" },
      description: "방법의 수 (1,000,000,007로 나눈 나머지)",
    },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [3],
      expected: 5,
      explanation:
        "길이 2 복도는 3가지(세로 두 개, 가로 두 개, 2×2 하나)예요. 길이 3은 맨 끝을 세로 타일로 막는 3가지 + 가로 두 개나 2×2로 막는 2가지 = 5가지예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [1],
      expected: 1,
      explanation: "세로 타일 하나뿐이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [2],
      expected: 3,
      failureNote: "3가지예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [4],
      expected: 11,
      failureNote: "5 + 2 × 3 = 11가지예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [10],
      expected: 683,
      failureNote: "길이 10이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [40],
      expected: 7746720,
      failureNote: "메모 없이 두 갈래로 계속 부르면 호출이 수십억 번이라 시간 초과예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [1000],
      expected: 458948807,
      failureNote: "길이 1,000이에요. 나머지 연산을 빼먹으면 값이 너무 커져요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "복도의 **맨 오른쪽 끝**을 어떻게 막는지 나눠 보면, 남은 부분이 **더 짧은 같은 복도**예요 → **점화식**을 세워 재귀로 풀어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`ways(n)` = 길이 n 복도를 채우는 방법의 수.",
        "",
        "- 맨 끝을 **세로 1×2** 하나로 막으면 남은 건 길이 n−1 → `ways(n-1)`가지",
        "- 맨 끝 두 칸을 **가로 1×2 두 개**로 막으면 남은 건 길이 n−2 → `ways(n-2)`가지",
        "- 맨 끝 두 칸을 **2×2** 하나로 막으면 남은 건 길이 n−2 → `ways(n-2)`가지",
        "",
        "그래서 `ways(n) = ways(n-1) + 2 × ways(n-2)`, 종료 조건은 `ways(0) = ways(1) = 1`이에요.",
        "",
        "같은 n을 여러 번 부르니 **메모이제이션**(한 번 구한 값을 저장)이 꼭 필요해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "memo = {}",
        "function ways(k):",
        "    if k ≤ 1: return 1",
        "    if k in memo: return memo[k]",
        "    memo[k] = (ways(k-1) + 2 × ways(k-2)) % 1,000,000,007",
        "    return memo[k]",
        "return ways(n)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["점화식을 코드로 옮긴 줄이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def ways(k):",
            "    if k <= 1:",
            "        return 1",
            "    if k in memo:",
            "        return memo[k]",
            "    memo[k] = (______) % MOD",
            "    return memo[k]",
          ].join("\n"),
          javascript: [
            "function ways(k) {",
            "  if (k <= 1) return 1;",
            "  if (memo.has(k)) return memo.get(k);",
            "  const value = (______) % MOD;",
            "  memo.set(k, value);",
            "  return value;",
            "}",
          ].join("\n"),
          java: [
            "long ways(int k) {",
            "    if (k <= 1) return 1;",
            "    if (memo[k] != 0) return memo[k];",
            "    memo[k] = (______) % MOD;",
            "    return memo[k];",
            "}",
          ].join("\n"),
        },
        caption:
          "방법의 수는 0이 될 수 없어서 memo[k]가 0이면 아직 안 구한 거예요. 곱셈이 int를 넘을 수 있어 long으로 계산해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursive-definition", "recursion-tree"],
  signalIds: ["sig-self-similar"],
  visualization: {
    presets: [
      problemPreset(
        "hallway-tiles-repeat",
        "recursion-fibonacci",
        "같은 호출이 반복돼요",
        "피보나치로 봐요. 두 갈래로 부르면 같은 값을 여러 번 다시 구해요. 그래서 메모가 필요해요.",
        [5],
      ),
    ],
  },
  estimatedMinutes: 15,
  xp: 30,
};
