import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [3, 3],
    expected: [3, 2],
    explanation: "원판 3개의 이동은 [1,3] [1,2] [3,2] [1,3] [2,1] [2,3] [1,3]이에요. 3번째는 [3, 2]예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [1, 1],
    expected: [1, 3],
    explanation: "원판 하나는 1번에서 3번으로 바로 옮겨요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "basic",
    args: [3, 4],
    expected: [1, 3],
    failureNote: "가장 큰 원판을 옮기는 가운데 이동이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [3, 7],
    expected: [1, 3],
    failureNote: "마지막 이동이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [2, 2],
    expected: [1, 3],
    failureNote: "원판 2개의 가운데 이동이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [4, 5],
    expected: [3, 1],
    failureNote: "앞쪽 절반 안에서 한 번 더 절반을 따라 내려가요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "tricky",
    args: [10, 700],
    expected: [1, 2],
    failureNote: "뒤쪽 절반으로 넘어가면 기둥 역할이 바뀌어요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [50, 562949953421312],
    expected: [1, 3],
    failureNote: "원판 50개의 가운데 이동이에요.",
  },
  {
    id: "hid-7",
    visibility: "hidden",
    purpose: "stress",
    args: [50, 1125899906842623],
    expected: [2, 3],
    failureNote: "원판 50개의 마지막 이동이에요. 모든 이동을 만들면 1000조 번이 넘어요.",
  },
  {
    id: "hid-8",
    visibility: "hidden",
    purpose: "stress",
    args: [48, 123456789012345],
    expected: [2, 3],
    failureNote: "원판 48개의 한가운데쯤 이동이에요.",
  },
]);

export const recursionHanoiKthMove: Problem = {
  id: "c:recursion-hanoi-kth-move",
  slug: "recursion-hanoi-kth-move",
  source: "curated",
  topic: "recursion",
  level: 5,
  title: "하노이 탑 k번째 이동",
  summary: "원판 n개를 옮기는 최단 이동 중 k번째 이동을 바로 찾아요",
  statement: [
    "노디가 1번 기둥에 쌓인 원판 `n`개를 3번 기둥으로 옮기려고 해요. 원판은 아래로 갈수록 커요.",
    "",
    "- 한 번에 원판 하나만, 기둥 맨 위에서 다른 기둥 맨 위로 옮겨요.",
    "- 큰 원판을 작은 원판 위에 놓을 수 없어요.",
    "",
    "가장 적은 횟수(2^n − 1번)로 옮기는 방법은 딱 하나예요: 위의 n−1개를 1번 → 2번으로 옮기고, 가장 큰 원판을 1번 → 3번으로 옮기고, n−1개를 2번 → 3번으로 옮겨요.",
    "",
    "이 방법대로 옮길 때 **k번째 이동**이 `[출발 기둥, 도착 기둥]` 중 무엇인지 반환해 주세요. n이 크면 모든 이동을 만들어 볼 수 없어요.",
  ].join("\n"),
  inputFormat: "`n`: 원판 수, `k`: 몇 번째 이동인지예요 (1부터 셉니다).",
  outputFormat: "`[출발 기둥, 도착 기둥]` (기둥 번호는 1, 2, 3)",
  constraints: ["1 ≤ n ≤ 50", "1 ≤ k ≤ 2^n − 1"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "원판 수" },
      { name: "k", type: { python: "int", javascript: "number", java: "long" }, description: "몇 번째 이동" },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "[출발, 도착]" },
  },
  starterCode: {
    python: ["def solution(n, k):", "    answer = [1, 3]", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, k) {", "  let answer = [1, 3];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int n, long k) {",
      "        int[] answer = new int[] {1, 3};",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "n개를 옮기는 과정 = (n−1개 옮기기) + (큰 원판 1번) + (n−1개 옮기기). 과정 안에 **한 단계 작은 같은 과정**이 두 번 들어 있어요 → **재귀 트리**예요.",
        "",
        "모든 이동을 만들지 말고, k번째가 트리의 **어느 가지**에 있는지만 따라 내려가요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`kth(n, 출발, 도착, 경유, k)`를 생각해요. 앞쪽 n−1개 옮기기는 `half = 2^(n-1) − 1`번이에요.",
        "",
        "- `k ≤ half`: 앞쪽 과정(출발 → **경유**, 도착을 거쳐) 안의 k번째 → `kth(n-1, 출발, 경유, 도착, k)`",
        "- `k == half + 1`: 가장 큰 원판 이동 → `[출발, 도착]`",
        "- 그 외: 뒤쪽 과정(경유 → 도착, 출발을 거쳐) 안의 `k − half − 1`번째",
        "",
        "한 번 부를 때마다 n이 1씩 줄어서 최대 50번이면 끝나요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "kth(n, a, b, c, k):      # a에서 b로, c를 거쳐",
        "    half = 2^(n-1) - 1",
        "    if k <= half: return kth(n-1, a, c, b, k)",
        "    if k == half + 1: return [a, b]",
        "    return kth(n-1, c, b, a, k - half - 1)",
        "solution(n, k) = kth(n, 1, 3, 2, k)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["뒤쪽 절반으로 내려가는 호출을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def kth(n, a, b, c, k):",
            "    half = 2 ** (n - 1) - 1",
            "    if k <= half:",
            "        return kth(n - 1, a, c, b, k)",
            "    if k == half + 1:",
            "        return [a, b]",
            "    return ______",
          ].join("\n"),
          javascript: [
            "function kth(n, a, b, c, k) {",
            "  const half = 2 ** (n - 1) - 1;",
            "  if (k <= half) return kth(n - 1, a, c, b, k);",
            "  if (k === half + 1) return [a, b];",
            "  return ______;",
            "}",
          ].join("\n"),
          java: [
            "int[] kth(int n, int a, int b, int c, long k) {",
            "    long half = (1L << (n - 1)) - 1;",
            "    if (k <= half) return kth(n - 1, a, c, b, k);",
            "    if (k == half + 1) return new int[] {a, b};",
            "    return ______;",
            "}",
          ].join("\n"),
        },
        caption:
          "JS에서 1 << 49 같은 비트 연산은 32비트라 틀려요. 2 ** (n - 1)을 쓰세요. k는 2^50에 가까울 수 있어서 long이에요. 1 << 49는 int라서 넘치니 1L << 49처럼 L을 붙여요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursion-tree", "divide-and-conquer"],
  signalIds: ["sig-shrink-by-one"],
  estimatedMinutes: 30,
  xp: 50,
};
