import type { Problem } from "@/types/content";

export const recursionMagicScroll: Problem = {
  id: "c:recursion-magic-scroll",
  slug: "recursion-magic-scroll",
  source: "curated",
  topic: "recursion",
  level: 5,
  title: "마법 두루마리의 k번째 글자",
  summary: "단계마다 두 배로 길어지는 주문에서 k번째 글자를 만들지 않고 찾아요",
  statement: [
    "노디가 찾은 마법 두루마리에는 `a`와 `b`로 된 주문이 적혀 있어요. 주문은 단계마다 이렇게 길어져요.",
    "",
    "- 1단계 주문: `a`",
    "- n단계 주문: **(n−1단계 주문)** + `b` + **(n−1단계 주문의 a와 b를 서로 바꾼 것)**",
    "",
    "예를 들어 2단계는 `a` + `b` + `b` = `abb`, 3단계는 `abb` + `b` + `baa` = `abbbbaa`예요.",
    "",
    "n단계 주문의 **k번째 글자**(1부터 셈)를 반환해 주세요. n단계 주문의 길이는 2^n − 1이라, n이 50이면 1,000조 글자가 넘어요.",
  ].join("\n"),
  inputFormat: "`n`: 주문의 단계, `k`: 찾을 글자의 위치(1부터)예요.",
  outputFormat: '`"a"` 또는 `"b"`',
  constraints: ["1 ≤ n ≤ 50", "1 ≤ k ≤ 2^n − 1"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "주문의 단계" },
      {
        name: "k",
        type: { python: "int", javascript: "number", java: "long" },
        description: "찾을 글자의 위치 (1부터)",
      },
    ],
    returns: { type: { python: "str", javascript: "string", java: "String" }, description: "k번째 글자" },
  },
  starterCode: {
    python: ["def solution(n, k):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(n, k) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String solution(int n, long k) {",
      '        String answer = "";',
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [3, 6],
      expected: "a",
      explanation:
        "3단계 주문 abbbbaa의 6번째 글자는 a예요. 뒤쪽 절반 baa는 앞쪽 abb의 a·b를 바꾼 것이라, 앞쪽 2번째 글자 b를 바꾼 a예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [1, 1],
      expected: "a",
      explanation: "1단계 주문은 a 한 글자예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [2, 2],
      expected: "b",
      failureNote: "가운데 글자는 언제나 b예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [3, 4],
      expected: "b",
      failureNote: "3단계의 가운데(4번째)예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [4, 15],
      expected: "b",
      failureNote: "마지막 글자예요. 뒤쪽 절반으로 갈 때마다 바꾸기가 한 번씩 쌓여요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [5, 20],
      expected: "a",
      failureNote: "뒤쪽 → 앞쪽 → 뒤쪽 … 바꾸기를 몇 번 했는지 세야 해요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [50, 562949953421312],
      expected: "b",
      failureNote: "50단계의 가운데 글자예요. 주문을 실제로 만들면 메모리가 모자라요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [50, 1125899906842623],
      expected: "b",
      failureNote: "50단계의 마지막 글자예요.",
    },
    {
      id: "hid-7",
      visibility: "hidden",
      purpose: "stress",
      args: [50, 123456789012345],
      expected: "a",
      failureNote: "50단계의 한가운데쯤 어딘가예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "n단계 주문 안에 **(n−1)단계 주문이 두 번**(한 번은 그대로, 한 번은 바뀐 채로) 들어 있어요 → **재귀 트리**로 생각해요.",
        "",
        "주문을 만들지 않고, k가 **어느 부분**에 있는지만 따라 내려가면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "n단계 주문은 `[앞쪽 절반] [가운데 b] [뒤쪽 절반]`이고, 절반 길이는 `half = 2^(n−1) − 1`이에요.",
        "",
        "- k ≤ half: 앞쪽 절반, 즉 (n−1)단계 주문의 k번째 글자 그대로예요.",
        "- k = half + 1: 가운데라서 `b`예요.",
        "- k > half + 1: 뒤쪽 절반이에요. (n−1)단계 주문의 `k − half − 1`번째 글자를 **바꾼 것**이에요.",
        "",
        "종료 조건은 1단계(`a`)예요. 한 번 내려갈 때마다 n이 1씩 줄어서 호출은 최대 50번이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function letter(n, k):",
        "    if n == 1: return 'a'",
        "    half = 2^(n-1) - 1",
        "    if k ≤ half: return letter(n-1, k)",
        "    if k == half + 1: return 'b'",
        "    c = letter(n-1, k - half - 1)",
        "    return c를 바꾼 글자 (a ↔ b)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["뒤쪽 절반으로 내려가는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "half = 2 ** (n - 1) - 1",
            "if k <= half:",
            "    return letter(n - 1, k)",
            "if k == half + 1:",
            '    return "b"',
            "c = letter(n - 1, ______)",
            'return "b" if c == "a" else "a"',
          ].join("\n"),
          javascript: [
            "const half = 2 ** (n - 1) - 1;",
            "if (k <= half) return letter(n - 1, k);",
            'if (k === half + 1) return "b";',
            "const c = letter(n - 1, ______);",
            'return c === "a" ? "b" : "a";',
          ].join("\n"),
          java: [
            "long half = (1L << (n - 1)) - 1;",
            "if (k <= half) return letter(n - 1, k);",
            'if (k == half + 1) return "b";',
            "String c = letter(n - 1, ______);",
            'return c.equals("a") ? "b" : "a";',
          ].join("\n"),
        },
        caption: "k는 1,000조를 넘을 수 있어서 long이에요. 2^(n−1)은 1L << (n − 1)로 구해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursion-tree", "divide-and-conquer"],
  signalIds: ["sig-nested-structure"],
  estimatedMinutes: 30,
  xp: 50,
};
