import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [6],
    expected: 8,
    explanation: "1, 1, 2, 3, 5, 8 — 6달째는 8쌍이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [1],
    expected: 1,
    explanation: "1달째는 1쌍이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [2],
    expected: 1,
    failureNote: "2달째도 1쌍이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [10],
    expected: 55,
    failureNote: "10달째예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [25],
    expected: 75025,
    failureNote: "25달째예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [70],
    expected: 190392490709135,
    failureNote: "70달째. 같은 달을 반복해서 계산하면 호출이 수조 번이라 끝나지 않아요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [45],
    expected: 1134903170,
    failureNote: "45달째예요. 메모 없이 부르면 호출이 10억 번이 넘어요.",
  },
]);

export const recursionRabbitFamily: Problem = {
  id: "c:recursion-rabbit-family",
  slug: "recursion-rabbit-family",
  source: "curated",
  topic: "recursion",
  level: 3,
  title: "토끼 가족은 몇 쌍?",
  summary: "앞의 두 달을 더해 가는 토끼 쌍의 수를 메모이제이션으로 구해요",
  statement: [
    "노디의 농장에서 토끼 가족이 불어나요. 기록을 보니 달마다 토끼 쌍의 수는 이렇게 정해져요.",
    "",
    "- 1달째와 2달째에는 1쌍이에요.",
    "- 3달째부터는 **지난달 쌍의 수 + 지지난달 쌍의 수**예요.",
    "",
    "`n`달째 토끼 쌍의 수를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 몇 달째인지예요.",
  outputFormat: "n달째 토끼 쌍의 수 (정수)",
  constraints: ["1 ≤ n ≤ 70"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "달" }],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "토끼 쌍의 수" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(int n) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"지난달 + 지지난달" → 식 안에 **자기 자신이 다시 등장**하는 **재귀적 정의**(점화식)예요.',
        "",
        "그런데 그대로 재귀로 옮기면 같은 달을 **여러 번** 계산해요. 호출 트리를 그려 보면 금방 보여요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 종료 조건: n이 1이나 2면 1.",
        "2. `rabbits(n) = rabbits(n-1) + rabbits(n-2)`.",
        "3. **메모이제이션**: 한 번 계산한 달의 답을 딕셔너리(또는 배열)에 저장해 두고, 다시 필요하면 저장한 값을 꺼내 써요.",
        "",
        "메모가 있으면 각 달을 한 번씩만 계산해서 호출이 n번 정도로 줄어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "memo = {}",
        "rabbits(n):",
        "    if n <= 2: return 1",
        "    if n in memo: return memo[n]",
        "    memo[n] = rabbits(n-1) + rabbits(n-2)",
        "    return memo[n]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["메모를 확인하고 저장하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "def rabbits(n):",
            "    if n <= 2:",
            "        return 1",
            "    if n in memo:",
            "        return ______",
            "    memo[n] = rabbits(n - 1) + rabbits(n - 2)",
            "    return memo[n]",
          ].join("\n"),
          javascript: [
            "function rabbits(n) {",
            "  if (n <= 2) return 1;",
            "  if (memo.has(n)) return ______;",
            "  const value = rabbits(n - 1) + rabbits(n - 2);",
            "  memo.set(n, value);",
            "  return value;",
            "}",
          ].join("\n"),
          java: [
            "long rabbits(int n) {",
            "    if (n <= 2) return 1;",
            "    if (memo.containsKey(n)) return ______;",
            "    long value = rabbits(n - 1) + rabbits(n - 2);",
            "    memo.put(n, value);",
            "    return value;",
            "}",
          ].join("\n"),
        },
        caption:
          "memo는 Map<Integer, Long> memo = new HashMap<>()를 Solution의 필드로 두면 돼요. 답이 int 범위(약 21억)를 넘을 수 있어서 long을 써요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursion-tree", "recursive-definition"],
  signalIds: ["sig-self-similar"],
  visualization: {
    presets: [
      problemPreset(
        "rabbit-tree",
        "recursion-fibonacci",
        "같은 계산이 반복되는 호출 트리",
        "fib(4)를 부를 때 fib(2)가 몇 번 계산되는지 세어 보세요.",
        [4],
      ),
    ],
  },
  estimatedMinutes: 15,
  xp: 30,
};
