import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [4],
    expected: 7,
    explanation: "1+1+1+1, 1+1+2, 1+2+1, 2+1+1, 2+2, 1+3, 3+1 — 7가지예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [1],
    expected: 1,
    explanation: "1칸 한 번뿐이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [2],
    expected: 2,
    failureNote: "1+1, 2 — 2가지예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [3],
    expected: 4,
    failureNote: "3칸을 한 번에 뛰는 방법도 있어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [10],
    expected: 274,
    failureNote: "돌 10개예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [50],
    expected: 10562230626642,
    failureNote: "돌 50개. 메모 없이 부르면 호출이 너무 많아요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [35],
    expected: 1132436852,
    failureNote: "돌 35개예요.",
  },
]);

export const recursionSteppingStones: Problem = {
  id: "c:recursion-stepping-stones",
  slug: "recursion-stepping-stones",
  source: "curated",
  topic: "recursion",
  level: 3,
  title: "징검돌 건너기",
  summary: "한 번에 1·2·3칸씩 건너는 방법의 수를 구해요",
  statement: [
    "개울에 징검돌이 한 줄로 놓여 있어요. 노디는 개울가(0번 위치)에서 출발해 `n`번째 돌까지 가려고 해요.",
    "",
    "한 번에 **1칸, 2칸, 3칸** 중 하나를 골라 뛸 수 있어요. n번째 돌에 **정확히** 도착하는 서로 다른 방법의 수를 반환해 주세요. 뛰는 순서가 다르면 다른 방법이에요.",
  ].join("\n"),
  inputFormat: "`n`: 도착할 돌의 번호예요.",
  outputFormat: "방법의 수 (정수)",
  constraints: ["1 ≤ n ≤ 50"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "도착할 돌 번호" }],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "방법의 수" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(int n) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "n번째 돌에 도착하기 **직전**에는 n−1, n−2, n−3번째 돌 중 하나에 있었어요.",
        "",
        "그러니 `ways(n) = ways(n-1) + ways(n-2) + ways(n-3)` → **재귀적 정의**예요. 같은 계산이 반복되니 **메모**를 곁들여요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 종료 조건: `ways(0) = 1`(이미 도착한 상태, 방법 1가지), 음수 위치는 0.",
        "2. 그 외에는 세 경우를 더해요.",
        "3. 계산한 값은 메모에 저장해 다시 쓰세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "ways(k):",
        "    if k < 0: return 0",
        "    if k == 0: return 1",
        "    if k in memo: return memo[k]",
        "    memo[k] = ways(k-1) + ways(k-2) + ways(k-3)",
        "    return memo[k]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["세 경우를 더하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "def ways(k):",
            "    if k < 0:",
            "        return 0",
            "    if k == 0:",
            "        return 1",
            "    if k not in memo:",
            "        memo[k] = ______",
            "    return memo[k]",
          ].join("\n"),
          javascript: [
            "function ways(k) {",
            "  if (k < 0) return 0;",
            "  if (k === 0) return 1;",
            "  if (!memo.has(k)) memo.set(k, ______);",
            "  return memo.get(k);",
            "}",
          ].join("\n"),
          java: [
            "long ways(int k) {",
            "    if (k < 0) return 0;",
            "    if (k == 0) return 1;",
            "    if (!memo.containsKey(k)) memo.put(k, ______);",
            "    return memo.get(k);",
            "}",
          ].join("\n"),
        },
        caption: "답이 int 범위(약 21억)를 넘을 수 있어서 long을 써요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["recursive-definition", "recursion-tree"],
  signalIds: ["sig-self-similar"],
  estimatedMinutes: 15,
  xp: 30,
};
