import type { Problem } from "@/types/content";

export const recursionSwappedPairs: Problem = {
  id: "c:recursion-swapped-pairs",
  slug: "recursion-swapped-pairs",
  source: "curated",
  topic: "recursion",
  level: 4,
  title: "뒤바뀐 키 순서 세기",
  summary: "앞사람이 뒷사람보다 큰 쌍의 개수를 분할 정복으로 세요",
  statement: [
    "새싹 반 친구들이 한 줄로 섰어요. 키 순서대로 서야 하는데 뒤죽박죽이에요. 노디 선생님은 얼마나 뒤섞였는지 알고 싶어요.",
    "",
    "줄에서 **앞에 선 친구가 뒤에 선 친구보다 키가 큰 쌍**(i < j 이고 `heights[i] > heights[j]`)의 개수를 반환해 주세요. 키가 같으면 뒤바뀐 쌍이 아니에요.",
  ].join("\n"),
  inputFormat: "`heights`: 줄 선 순서대로의 키 리스트예요.",
  outputFormat: "뒤바뀐 쌍의 개수 (정수)",
  constraints: ["1 ≤ heights의 길이 ≤ 50,000", "1 ≤ 각 키 ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "heights", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "키 목록" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "뒤바뀐 쌍의 수" },
  },
  starterCode: {
    python: ["def solution(heights):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(heights) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(int[] heights) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[3, 1, 2]],
      expected: 2,
      explanation: "(3, 1), (3, 2) 두 쌍이 뒤바뀌었어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[1, 2, 3, 4]],
      expected: 0,
      explanation: "이미 키 순서대로면 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5]],
      expected: 0,
      failureNote: "한 명뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[4, 3, 2, 1]],
      expected: 6,
      failureNote: "완전히 거꾸로면 모든 쌍(6쌍)이 뒤바뀌었어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 2, 1, 1]],
      expected: 4,
      failureNote: "키가 같은 쌍은 세지 않아요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[8, 4, 2, 1, 7, 3, 6, 5]],
      expected: 15,
      failureNote: "여러 쌍이 섞여 있어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 50000 }, (_, i) => 50000 - i)],
      expected: 1249975000,
      failureNote: "5만 명이 완전히 거꾸로 섰어요. 모든 쌍을 비교하면 12억 번이라 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 50000 }, (_, i) => ((i * 7919) % 50021) + 1)],
      expected: 624860001,
      failureNote: "5만 명이 뒤섞여 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "모든 쌍을 비교하면 O(N²)이라 5만 명이면 너무 느려요.",
        "",
        "줄을 **절반으로 나눠** 각 절반 안의 뒤바뀐 쌍을 세고, **두 절반 사이**의 쌍만 따로 세면 돼요 → **분할 정복**(병합 정렬)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`count(구간)`이 구간을 **정렬한 결과**와 **뒤바뀐 쌍 수**를 함께 돌려준다고 해요.",
        "",
        "1. 길이가 1이면 (정렬된 그 자신, 0).",
        "2. 왼쪽 절반, 오른쪽 절반을 각각 재귀로 처리해요.",
        "3. 정렬된 두 절반을 **병합**하면서, 오른쪽 원소를 먼저 내려놓을 때마다 **왼쪽에 아직 남은 원소 수**만큼 뒤바뀐 쌍이 생겨요 (그 원소들이 모두 더 크니까요).",
        "",
        "전체 O(N log N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count(a):",
        "    if len(a) <= 1: return a, 0",
        "    left, x = count(a의 앞 절반)",
        "    right, y = count(a의 뒤 절반)",
        "    병합하며: right[j] < left[i] 이면 right[j]를 내려놓고 z += (left에 남은 개수)",
        "    return 병합 결과, x + y + z",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드: 병합",
      body: ["오른쪽 원소를 먼저 내려놓을 때 세는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "while i < len(left) and j < len(right):",
            "    if left[i] <= right[j]:",
            "        merged.append(left[i]); i += 1",
            "    else:",
            "        merged.append(right[j]); j += 1",
            "        swaps += ______",
          ].join("\n"),
          javascript: [
            "while (i < left.length && j < right.length) {",
            "  if (left[i] <= right[j]) merged.push(left[i++]);",
            "  else {",
            "    merged.push(right[j++]);",
            "    swaps += ______;",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "while (i < left.length && j < right.length) {",
            "    if (left[i] <= right[j]) merged[k++] = left[i++];",
            "    else {",
            "        merged[k++] = right[j++];",
            "        swaps += ______;",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "바꾸는 횟수는 10억을 넘을 수 있어서 long으로 세요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["divide-and-conquer"],
  signalIds: ["sig-self-similar"],
  estimatedMinutes: 30,
  xp: 40,
};
