import type { Problem } from "@/types/content";

export const cxBalancedSplit: Problem = {
  id: "c:cx-balanced-split",
  slug: "cx-balanced-split",
  source: "curated",
  topic: "complexity",
  level: 5,
  title: "공평하게 둘로 나누기",
  summary: "전체 합을 먼저 구하면, 왼쪽 합만 늘려 가며 오른쪽 합을 뺄셈으로 알 수 있어요",
  statement: [
    "정수 배열 `nums`를 한 곳에서 잘라 **왼쪽 묶음**과 **오른쪽 묶음**으로 나눠요. 두 묶음 모두 한 칸 이상이어야 해요.",
    "",
    "`|왼쪽 합 − 오른쪽 합|`의 **최솟값**을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`nums`: 정수 배열이에요.",
  outputFormat: "두 합의 차이의 최솟값",
  constraints: ["2 ≤ nums의 길이 ≤ 100,000", "−10,000 ≤ nums[i] ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      { name: "nums", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "정수 배열" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "차이의 최솟값" },
  },
  starterCode: {
    python: ["def solution(nums):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(nums) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(int[] nums) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[1, 2, 3, 4, 5]],
      expected: 3,
      explanation: "[1, 2, 3] | [4, 5]로 6과 9, 차이 3이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[10, 10]],
      expected: 0,
      explanation: "딱 반으로 나뉘어 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [[5, 1]],
      expected: 4,
      failureNote: "4예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, -1, 1, -1]],
      expected: 0,
      failureNote: "[1, −1] | [1, −1]이면 0이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[-5, 5, 5]],
      expected: 5,
      failureNote: "[−5, 5] | [5]로 0과 5, 차이 5예요. [−5] | [5, 5]는 −5와 10이라 차이가 15예요. 음수에 주의해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 20001) - 10000)],
      expected: 7,
      failureNote: "10만 칸이에요. 자를 곳마다 두 합을 새로 더하면 약 100억 번이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "자를 곳이 N − 1군데이고, 매번 두 합을 새로 구하면 `O(N²)`이에요 → 합을 **미리 계산해 두고** 한 번 훑어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 전체 합 `total`을 한 번 구해요.",
        "2. 왼쪽부터 훑으며 왼쪽 합 `left`에 한 칸씩 더해요. 그러면 오른쪽 합은 `total − left`예요.",
        "3. 자를 수 있는 곳(마지막 칸 앞까지)마다 `|left − (total − left)|`의 최솟값을 기억해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "total = sum(nums);  left = 0;  best = ∞",
        "for i in range(len(nums) - 1):",
        "    left += nums[i]",
        "    best = min(best, |left - (total - left)|)",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["차이를 계산하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["for i in range(len(nums) - 1):", "    left += nums[i]", "    best = min(best, abs(______))"].join(
            "\n",
          ),
          javascript: [
            "for (let i = 0; i < nums.length - 1; i++) {",
            "  left += nums[i];",
            "  best = Math.min(best, Math.abs(______));",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < nums.length - 1; i++) {",
            "    left += nums[i];",
            "    best = Math.min(best, Math.abs(______));",
            "}",
          ].join("\n"),
        },
        caption: "합의 차이는 21억을 넘을 수 있어서 long으로 계산해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["precompute"],
  signalIds: ["sig-all-pairs-slow"],
  estimatedMinutes: 10,
  xp: 50,
};
