import type { Problem } from "@/types/content";

export const cxCountDivisors: Problem = {
  id: "c:cx-count-divisors",
  slug: "cx-count-divisors",
  source: "curated",
  topic: "complexity",
  level: 4,
  title: "약수는 몇 개?",
  summary: "약수는 i와 n ÷ i로 짝을 이뤄서, √n까지만 보면 돼요",
  statement: ["자연수 `n`의 **약수**(n을 나누어떨어지게 하는 자연수)는 모두 몇 개인지 반환해 주세요."].join("\n"),
  inputFormat: "`n`: 자연수예요.",
  outputFormat: "약수의 개수",
  constraints: ["1 ≤ n ≤ 10¹⁰"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "long" }, description: "자연수" }],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "약수의 개수" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(long n) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [12],
      expected: 6,
      explanation: "1, 2, 3, 4, 6, 12로 6개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [1],
      expected: 1,
      explanation: "1의 약수는 1 하나예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [16],
      expected: 5,
      failureNote: "4 × 4처럼 짝이 자기 자신이면 한 번만 세요: 1, 2, 4, 8, 16으로 5개.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [13],
      expected: 2,
      failureNote: "소수라 1과 13, 2개예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [10000000000],
      expected: 121,
      failureNote: "2¹⁰ × 5¹⁰이라 11 × 11 = 121개예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [9999999999],
      expected: 48,
      failureNote: "3² × 11 × 41 × 271 × 9091이라 48개예요. 1부터 n까지 나눠 보면 100억 번이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["1부터 n까지 나눠 보면 `O(N)`이라 n = 10¹⁰에서 너무 느려요. **√N까지만** 보는 방법이 있어요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "i가 n의 약수면 `n ÷ i`도 약수예요. 둘 중 하나는 꼭 √n 이하예요.",
        "",
        "그래서 `i × i ≤ n`인 i만 보며, 나누어떨어지면 약수를 **2개**(i와 n ÷ i) 세요. 단, `i × i == n`이면 둘이 같으니 1개만 세요.",
        "",
        "n = 10¹⁰이어도 i는 10만까지예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count = 0;  i = 1",
        "while i * i <= n:",
        "    if n % i == 0: count += 1 if i * i == n else 2",
        "    i += 1",
        "return count",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["반복 조건 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "i = 1",
            "while ______:",
            "    if n % i == 0:",
            "        count += 1 if i * i == n else 2",
            "    i += 1",
          ].join("\n"),
          javascript: ["for (let i = 1; ______; i++) {", "  if (n % i === 0) count += i * i === n ? 1 : 2;", "}"].join(
            "\n",
          ),
          java: ["for (long i = 1; ______; i++) {", "    if (n % i == 0) count += i * i == n ? 1 : 2;", "}"].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sqrt-bound"],
  signalIds: ["sig-huge-n"],
  estimatedMinutes: 10,
  xp: 40,
};
