import type { Problem } from "@/types/content";

export const cxCountPrimes: Problem = {
  id: "c:cx-count-primes",
  slug: "cx-count-primes",
  source: "curated",
  topic: "complexity",
  level: 5,
  title: "소수는 몇 개? (체)",
  summary: "수마다 따로 확인하지 말고, 소수의 배수를 한꺼번에 지워 나가요 (에라토스테네스의 체)",
  statement: ["`n` 이하의 **소수**는 모두 몇 개인지 반환해 주세요."].join("\n"),
  inputFormat: "`n`: 자연수예요.",
  outputFormat: "n 이하 소수의 개수",
  constraints: ["1 ≤ n ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "자연수" }],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "소수의 개수" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [10],
      expected: 4,
      explanation: "2, 3, 5, 7로 4개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [1],
      expected: 0,
      explanation: "1은 소수가 아니라 0개예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [2],
      expected: 1,
      failureNote: "2 하나예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [30],
      expected: 10,
      failureNote: "2, 3, 5, 7, 11, 13, 17, 19, 23, 29로 10개예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [100],
      expected: 25,
      failureNote: "25개예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [1000000],
      expected: 78498,
      failureNote: "100만 이하 소수는 78,498개예요. 수마다 √n까지 나눠 보면 체보다 훨씬 느려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "수마다 소수인지 따로 확인하면 `O(N√N)`이에요. 여러 수를 한꺼번에 물을 땐 **미리 계산해 두기**가 빨라요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "**에라토스테네스의 체**:",
        "",
        "1. 2부터 n까지 모두 '소수 후보'로 표시해요.",
        "2. 작은 수부터 보며, 아직 후보인 i를 만나면 i는 소수예요. i의 배수(`i × i`부터)를 모두 후보에서 지워요.",
        "3. `i × i > n`이면 멈춰도 돼요. 남은 후보가 모두 소수예요.",
        "",
        "시간은 약 `O(N log log N)`으로 거의 `O(N)`이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "is_prime = [True] * (n + 1);  is_prime[0] = is_prime[1] = False",
        "for i = 2, 3, … while i * i <= n:",
        "    if is_prime[i]:",
        "        for j = i*i, i*i + i, … <= n: is_prime[j] = False",
        "return is_prime에서 True의 개수",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["배수를 지우는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["if is_prime[i]:", "    for j in range(______, n + 1, i):", "        is_prime[j] = False"].join(
            "\n",
          ),
          javascript: ["if (isPrime[i]) {", "  for (let j = ______; j <= n; j += i) isPrime[j] = false;", "}"].join(
            "\n",
          ),
          java: [
            "if (!composite[i]) {",
            "    for (long j = ______; j <= n; j += i) composite[(int) j] = true;",
            "}",
          ].join("\n"),
        },
        caption: "i × i가 int를 넘지 않도록 long으로 계산해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["precompute"],
  signalIds: ["sig-input-size"],
  estimatedMinutes: 15,
  xp: 50,
};
