import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [2, 10, 1000],
    expected: 24,
    explanation: "2¹⁰ = 1024라 24예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [5, 0, 7],
    expected: 1,
    explanation: "0제곱은 1이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [5, 0, 1],
    expected: 0,
    failureNote: "1로 나눈 나머지는 늘 0이에요. 0제곱이어도 1 % 1 = 0이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [3, 5, 100],
    expected: 43,
    failureNote: "3⁵ = 243이라 43이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [1000000000, 3, 999983],
    expected: 522411,
    failureNote: "a가 커도 먼저 m으로 나눈 나머지로 바꿔 두면 곱이 넘치지 않아요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [123456789, 1000000000000000, 999983],
    expected: 886392,
    failureNote: "b가 10¹⁵예요. 하나씩 곱하면 끝나지 않아요.",
  },
]);

export const cxFastPower: Problem = {
  id: "c:cx-fast-power",
  slug: "cx-fast-power",
  source: "curated",
  topic: "complexity",
  level: 3,
  title: "거듭제곱 빨리 하기",
  summary: "a², a⁴, a⁸…처럼 제곱해 가며 b를 절반씩 줄이면 log b번이에요",
  statement: [
    "`a`를 `b`번 곱한 값(a의 b제곱)을 `m`으로 나눈 **나머지**를 반환해 주세요.",
    "",
    "`b`가 아주 커서 `a`를 b번 곱하면 시간 안에 끝나지 않아요. `b = 0`이면 a의 0제곱은 1이에요.",
  ].join("\n"),
  inputFormat: "`a`: 밑, `b`: 지수, `m`: 나누는 수예요.",
  outputFormat: "a의 b제곱을 m으로 나눈 나머지",
  constraints: ["1 ≤ a ≤ 10⁹", "0 ≤ b ≤ 10¹⁵", "1 ≤ m ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "a", type: { python: "int", javascript: "number", java: "long" }, description: "밑" },
      { name: "b", type: { python: "int", javascript: "number", java: "long" }, description: "지수" },
      { name: "m", type: { python: "int", javascript: "number", java: "long" }, description: "나누는 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "나머지" },
  },
  starterCode: {
    python: ["def solution(a, b, m):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(a, b, m) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(long a, long b, long m) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["b가 10¹⁵라 b번 곱하는 `O(b)`는 안 돼요. b를 **절반씩** 줄이는 `O(log b)`가 필요해요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "- b가 짝수면 `a^b = (a²)^(b/2)`",
        "- b가 홀수면 `a^b = a × a^(b−1)`",
        "",
        "반복문으로: 결과 `result = 1`, 밑 `base = a % m`에서 시작해요. b가 홀수면 `result`에 `base`를 곱하고, `base`는 제곱하고, b는 절반으로 줄여요.",
        "",
        "곱할 때마다 `% m`을 해서 수가 커지지 않게 해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "result = 1 % m;  base = a % m",
        "while b > 0:",
        "    if b가 홀수: result = result * base % m",
        "    base = base * base % m",
        "    b = b // 2",
        "return result",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["반복문 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while b > 0:",
            "    if b % 2 == 1:",
            "        result = result * base % m",
            "    base = ______",
            "    b //= 2",
          ].join("\n"),
          javascript: [
            "while (b > 0) {",
            "  if (b % 2 === 1) result = (result * base) % m;",
            "  base = ______;",
            "  b = Math.floor(b / 2);",
            "}",
          ].join("\n"),
          java: [
            "while (b > 0) {",
            "    if (b % 2 == 1) result = result * base % m;",
            "    base = ______;",
            "    b /= 2;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["halving-log"],
  signalIds: ["sig-huge-n"],
  estimatedMinutes: 15,
  xp: 30,
};
