import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [12],
    expected: [2, 2, 3],
    explanation: "2 × 2 × 3이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [13],
    expected: [13],
    explanation: "소수는 자기 자신 하나예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [2],
    expected: [2],
    failureNote: "[2]예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [1024],
    expected: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    failureNote: "2를 10번 곱한 수예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [9999999999],
    expected: [3, 3, 11, 41, 271, 9091],
    failureNote: "[3, 3, 11, 41, 271, 9091]이에요. 같은 소수로 나눌 수 있을 만큼 계속 나눠요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [19999999934],
    expected: [2, 9999999967],
    failureNote: "2 × 9999999967이에요. √n까지 나누고 남은 큰 소수를 빠뜨리면 틀려요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [9999999967],
    expected: [9999999967],
    failureNote: "큰 소수예요. √n까지 나눠 봐도 안 나누어떨어지면 남은 n이 곧 소인수예요.",
  },
]);

export const cxPrimeFactors: Problem = {
  id: "c:cx-prime-factors",
  slug: "cx-prime-factors",
  source: "curated",
  topic: "complexity",
  level: 4,
  title: "소인수분해",
  summary: "√n까지 작은 수로 나눌 수 있을 만큼 나누고, 남은 수가 1보다 크면 그것도 소수예요",
  statement: [
    "2 이상인 자연수 `n`을 **소수들의 곱**으로 나타내요. 곱하는 소수들을 작은 것부터(같은 소수는 여러 번) 담아 반환해 주세요.",
    "",
    "예를 들어 12 = 2 × 2 × 3이라 `[2, 2, 3]`이에요.",
  ].join("\n"),
  inputFormat: "`n`: 2 이상의 자연수예요.",
  outputFormat: "소인수 목록 (오름차순, 중복 포함)",
  constraints: ["2 ≤ n ≤ 10¹⁰"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number", java: "long" }, description: "자연수" }],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "List<Long>" }, description: "소인수 목록" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Long> solution(long n) {",
      "        List<Long> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["작은 소수부터 나눠 가면 돼요. 다만 n까지 나눠 보면 느리니 **√n까지만** 나눠요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. i = 2부터 시작해요. `i × i ≤ n`인 동안, n이 i로 나누어떨어지면 i를 적고 n을 i로 나누기를 **안 나누어떨어질 때까지** 반복해요.",
        "2. 그다음 i를 1 늘려요. (합성수 i는 이미 더 작은 소수로 다 나눠서 나누어떨어지지 않아요)",
        "3. 끝나고 n이 1보다 크면, 남은 n은 √n보다 큰 **소수 하나**예요. 그것도 적어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "i = 2",
        "while i * i <= n:",
        "    while n % i == 0: factors.append(i);  n //= i",
        "    i += 1",
        "if n > 1: factors.append(n)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["마지막에 남은 수를 처리하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while i * i <= n:",
            "    while n % i == 0:",
            "        factors.append(i)",
            "        n //= i",
            "    i += 1",
            "if ______:",
            "    factors.append(n)",
          ].join("\n"),
          javascript: [
            "for (let i = 2; i * i <= n; i++) {",
            "  while (n % i === 0) {",
            "    factors.push(i);",
            "    n /= i;",
            "  }",
            "}",
            "if (______) factors.push(n);",
          ].join("\n"),
          java: [
            "for (long i = 2; i * i <= n; i++) {",
            "    while (n % i == 0) {",
            "        factors.add(i);",
            "        n /= i;",
            "    }",
            "}",
            "if (______) factors.add(n);",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sqrt-bound"],
  signalIds: ["sig-huge-n"],
  estimatedMinutes: 12,
  xp: 40,
};
