import type { Problem } from "@/types/content";

export const simTurnWalk: Problem = {
  id: "c:sim-turn-walk",
  slug: "sim-turn-walk",
  source: "curated",
  topic: "implementation",
  level: 1,
  title: "돌고 걷는 거북이",
  summary: "방향을 0~3 번호로 두고, 돌 때는 번호만, 걸을 때는 그 방향으로 한 칸 가요",
  statement: [
    "거북이가 좌표 (0, 0)에서 **북쪽**(y가 커지는 쪽)을 보고 서 있어요. `commands`의 글자를 차례로 따라 해요.",
    "",
    "- `L`: 제자리에서 왼쪽으로 90도 돌아요.",
    "- `R`: 제자리에서 오른쪽으로 90도 돌아요.",
    "- `F`: 보고 있는 쪽으로 한 칸 가요.",
    "",
    "마지막 위치 `[x, y]`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`commands`: `L`, `R`, `F`로 된 문자열이에요.",
  outputFormat: "마지막 위치 [x, y]",
  constraints: ["1 ≤ commands의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [{ name: "commands", type: { python: "str", javascript: "string", java: "String" }, description: "명령" }],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "[x, y]" },
  },
  starterCode: {
    python: ["def solution(commands):", "    answer = [0, 0]", "    return answer", ""].join("\n"),
    javascript: ["function solution(commands) {", "  let answer = [0, 0];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(String commands) {",
      "        int[] answer = new int[2];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["FRFF"],
      expected: [2, 1],
      explanation: "북쪽으로 한 칸, 오른쪽으로 돌아 동쪽으로 두 칸: [2, 1].",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: ["LLFF"],
      expected: [0, -2],
      explanation: "두 번 왼쪽으로 돌면 남쪽이라 [0, −2]예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: ["RRRRF"],
      expected: [0, 1],
      failureNote: "네 번 돌면 다시 북쪽이라 [0, 1]이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: ["F"],
      expected: [0, 1],
      failureNote: "[0, 1]이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: ["FLFLFLF"],
      expected: [0, 0],
      failureNote: "정사각형을 돌아 제자리 [0, 0]이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: ["LF"],
      expected: [-1, 0],
      failureNote: "북쪽에서 왼쪽으로 돌면 서쪽이라 [−1, 0]이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => "FFRFLF"[(i * 31 + (i >> 5)) % 6]).join("")],
      expected: [-38, -4],
      failureNote: "명령 10만 개예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["방향을 **돌며** 움직이는 시뮬레이션이에요. 방향을 번호로 두면 간단해요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "방향 0 = 북, 1 = 동, 2 = 남, 3 = 서로 두고, 한 칸 갈 때 바뀌는 값을 배열에 담아요.",
        "",
        "`dx = [0, 1, 0, -1]`, `dy = [1, 0, -1, 0]`",
        "",
        "- `R`: `d = (d + 1) % 4`",
        "- `L`: `d = (d + 3) % 4`",
        "- `F`: `x += dx[d]`, `y += dy[d]`",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "x = y = d = 0",
        "for ch in commands:",
        "    L이면 d = (d + 3) % 4, R이면 d = (d + 1) % 4",
        "    F면 x += dx[d], y += dy[d]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["왼쪽으로 도는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            'if ch == "L":',
            "    d = ______",
            'elif ch == "R":',
            "    d = (d + 1) % 4",
            "else:",
            "    x += dx[d]",
            "    y += dy[d]",
          ].join("\n"),
          javascript: [
            'if (ch === "L") d = ______;',
            'else if (ch === "R") d = (d + 1) % 4;',
            "else {",
            "  x += dx[d];",
            "  y += dy[d];",
            "}",
          ].join("\n"),
          java: [
            "if (ch == 'L') d = ______;",
            "else if (ch == 'R') d = (d + 1) % 4;",
            "else {",
            "    x += DX[d];",
            "    y += DY[d];",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["direction-move"],
  signalIds: ["sig-direction-turn"],
  estimatedMinutes: 8,
  xp: 10,
};
