import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: ["EEN"],
    expected: 15,
    explanation: "윗면이 4, 6, 5가 돼서 15예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: ["E"],
    expected: 4,
    explanation: "서쪽 면 4가 위로 와서 4예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "basic",
    args: ["NNNN"],
    expected: 14,
    failureNote: "북쪽으로 네 번이면 윗면이 5, 6, 2, 1이라 14예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: ["EW"],
    expected: 5,
    failureNote: "동쪽으로 굴렸다 서쪽으로 되돌리면 윗면이 4, 1이라 5예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: ["S"],
    expected: 2,
    failureNote: "남쪽으로 굴리면 북쪽 면 2가 위로 와요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => "NSEWENWS"[(i * 7919 + (i >> 4)) % 8]).join("")],
    expected: 346980,
    failureNote: "10만 번 굴려요.",
  },
]);

export const simDiceSum: Problem = {
  id: "c:sim-dice-sum",
  slug: "sim-dice-sum",
  source: "curated",
  topic: "implementation",
  level: 3,
  title: "주사위 굴리기",
  summary: "여섯 면을 변수로 두고, 굴릴 때마다 네 면의 자리를 돌려요",
  statement: [
    "주사위가 바닥에 놓여 있어요. 처음 **윗면 1, 아랫면 6, 북쪽 면 2, 남쪽 면 5, 동쪽 면 3, 서쪽 면 4**예요.",
    "",
    "`commands`의 글자(`N`, `S`, `E`, `W`)대로 그 방향으로 한 번씩 굴려요. 예를 들어 동쪽(`E`)으로 굴리면 **서쪽 면이 위로** 올라오고, 윗면은 동쪽으로, 동쪽 면은 바닥으로, 바닥 면은 서쪽으로 가요.",
    "",
    "굴릴 때마다 **윗면의 수**를 모두 더한 값을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`commands`: `N`, `S`, `E`, `W`로 된 문자열이에요.",
  outputFormat: "굴릴 때마다 윗면 수의 합",
  constraints: ["1 ≤ commands의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      { name: "commands", type: { python: "str", javascript: "string", java: "String" }, description: "굴리는 방향" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "윗면 수의 합" },
  },
  starterCode: {
    python: ["def solution(commands):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(commands) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String commands) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["주사위의 여섯 면이라는 **상태**를 규칙대로 바꾸는 시뮬레이션이에요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "변수 여섯 개(`top`, `bottom`, `north`, `south`, `east`, `west`)를 두고, 방향마다 네 면이 돌아가요. 굴리는 쪽과 수직인 두 면은 그대로예요.",
        "",
        "- `E`: 위 ← 서, 동 ← 위, 아래 ← 동, 서 ← 아래",
        "- `W`: 위 ← 동, 서 ← 위, 아래 ← 서, 동 ← 아래",
        "- `N`: 위 ← 남, 북 ← 위, 아래 ← 북, 남 ← 아래",
        "- `S`: 위 ← 북, 남 ← 위, 아래 ← 남, 북 ← 아래",
        "",
        "여러 변수를 한 번에 바꿔야 해요. 하나씩 바꾸면 이미 바뀐 값을 쓰게 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "top, bottom, north, south, east, west = 1, 6, 2, 5, 3, 4",
        "for ch in commands:",
        "    ch에 따라 네 면을 한꺼번에 바꾸기",
        "    total += top",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["동쪽으로 굴리는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ['if ch == "E":', "    top, east, bottom, west = ______, top, east, bottom"].join("\n"),
          javascript: ['if (ch === "E") [top, east, bottom, west] = [______, top, east, bottom];'].join("\n"),
          java: [
            "if (ch == 'E') {",
            "    int t = top;",
            "    top = ______;",
            "    west = bottom;",
            "    bottom = east;",
            "    east = t;",
            "}",
          ].join("\n"),
        },
        caption: "Java는 여러 변수를 한 번에 바꿀 수 없어서, 윗면을 먼저 t에 적어 둬요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["step-simulation"],
  signalIds: ["sig-follow-rules"],
  estimatedMinutes: 12,
  xp: 30,
};
