import type { Problem } from "@/types/content";

export const simZipBest: Problem = {
  id: "c:sim-zip-best",
  slug: "sim-zip-best",
  source: "curated",
  topic: "implementation",
  level: 4,
  title: "암호문 줄이기",
  summary: "자르는 길이를 1부터 모두 해 보고, 길이마다 이웃한 같은 조각을 개수로 묶어 봐요",
  statement: [
    "문자열 `s`를 길이 `k`의 조각으로 앞에서부터 잘라요. (마지막 조각은 짧을 수 있어요)",
    "",
    '그다음 **바로 이어서 같은 조각**이 반복되면 `개수 + 조각`으로 줄여 적어요. 한 번만 나오면 조각만 적어요. 예를 들어 `k = 2`일 때 `"ababcc"`는 `ab ab cc`라서 `"2abcc"`가 돼요.',
    "",
    "`k`를 1부터 `s`의 길이까지 자유롭게 고를 때, 줄인 문자열의 **가장 짧은 길이**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`s`: 소문자로 된 문자열이에요.",
  outputFormat: "줄인 문자열 길이의 최솟값",
  constraints: ["1 ≤ s의 길이 ≤ 1,000"],
  signature: {
    name: "solution",
    params: [{ name: "s", type: { python: "str", javascript: "string", java: "String" }, description: "문자열" }],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 짧은 길이" },
  },
  starterCode: {
    python: ["def solution(s):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(s) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String s) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["aaaabbb"],
      expected: 4,
      explanation: 'k = 1이면 "4a3b"로 4예요.',
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: ["abcabcabc"],
      expected: 4,
      explanation: 'k = 3이면 "3abc"로 4예요.',
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["a"],
      expected: 1,
      failureNote: "줄일 게 없어 1이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: ["xxxxxxxxxx"],
      expected: 3,
      failureNote: '"10x"라 3이에요. 개수가 두 자리면 두 글자를 차지해요.',
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["abcabcdede"],
      expected: 8,
      failureNote: 'k = 2는 "abcabc2de"(9), k = 3은 "2abcdede"(8)라 8이에요. 앞에서부터만 잘라요.',
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: ["abcd"],
      expected: 4,
      failureNote: "반복이 없어 4예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: ["abc".repeat(200) + "xy".repeat(150) + "q".repeat(100)],
      expected: 29,
      failureNote: "길이 1,000이에요. k마다 한 번 훑어도 100만 번 정도예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["규칙대로 문자열을 자르고 묶는 **구현**이에요. 모든 k를 다 해 봐도 충분히 빨라요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "k마다:",
        "",
        "1. `s`를 k글자씩 잘라 조각 목록을 만들어요.",
        "2. 앞에서부터 같은 조각이 몇 번 이어지는지 세요. 이어지다 끊기면 (개수가 1보다 크면 개수 글자 수) + 조각 길이를 더해요.",
        "3. k별 길이 중 최솟값이 답이에요.",
        "",
        "개수 10은 두 글자예요. `len(str(개수))`로 세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "best = len(s)",
        "for k in 1 .. len(s):",
        "    조각 = s를 k글자씩",
        "    length = 0;  prev = 조각[0];  cnt = 1",
        "    다음 조각마다: 같으면 cnt += 1, 다르면 length += 묶음 길이(prev, cnt);  prev, cnt = 조각, 1",
        "    length += 묶음 길이(prev, cnt);  best = min(best, length)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["묶음 하나의 길이를 세는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["def piece_len(chunk, cnt):", "    return len(chunk) + (______ if cnt > 1 else 0)"].join("\n"),
          javascript: ["const pieceLen = (chunk, cnt) => chunk.length + (cnt > 1 ? ______ : 0);"].join("\n"),
          java: [
            "int pieceLen(String chunk, int cnt) {",
            "    return chunk.length() + (cnt > 1 ? ______ : 0);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["string-parse"],
  signalIds: ["sig-follow-rules"],
  estimatedMinutes: 18,
  xp: 40,
};
