import type { Problem } from "@/types/content";

export const simCleaningRobot: Problem = {
  id: "c:sim-cleaning-robot",
  slug: "sim-cleaning-robot",
  source: "curated",
  topic: "implementation",
  level: 5,
  title: "먼지 먹는 로봇",
  summary: "규칙 세 줄을 순서대로, 빠짐없이 옮기는 게 전부예요",
  statement: [
    "방 지도 `room`에서 `'.'`은 빈칸, `'#'`은 벽이에요. 가장자리 칸은 모두 벽이에요. 로봇은 `(r, c)` 칸에서 방향 `d`(0 = 북, 1 = 동, 2 = 남, 3 = 서)를 보고 있어요. 처음엔 모든 빈칸이 더러워요.",
    "",
    "로봇은 멈출 때까지 이 규칙을 반복해요.",
    "",
    "1. 지금 칸이 더러우면 청소해요.",
    "2. 둘레 4칸 중 **더러운 빈칸이 없으면**: 방향은 그대로 두고 **한 칸 뒤로** 물러나요. 뒤가 벽이면 멈춰요.",
    "3. 둘레 4칸 중 **더러운 빈칸이 있으면**: 왼쪽으로 90도 돌아요. 앞 칸이 더러운 빈칸이면 한 칸 가요.",
    "",
    "로봇이 멈출 때까지 청소한 칸의 수를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`room`: 방 지도, `r`, `c`: 처음 위치, `d`: 처음 방향이에요.",
  outputFormat: "청소한 칸의 수",
  constraints: ["3 ≤ 줄 수, 칸 수 ≤ 50", "가장자리는 모두 벽이고, 처음 칸은 빈칸이에요", "0 ≤ d ≤ 3"],
  signature: {
    name: "solution",
    params: [
      { name: "room", type: { python: "list[str]", javascript: "string[]", java: "String[]" }, description: "방 지도" },
      { name: "r", type: { python: "int", javascript: "number", java: "int" }, description: "처음 줄" },
      { name: "c", type: { python: "int", javascript: "number", java: "int" }, description: "처음 칸" },
      { name: "d", type: { python: "int", javascript: "number", java: "int" }, description: "처음 방향" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "청소한 칸 수" },
  },
  starterCode: {
    python: ["def solution(room, r, c, d):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(room, r, c, d) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String[] room, int r, int c, int d) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "edge",
      args: [["###", "#.#", "###"], 1, 1, 0],
      expected: 1,
      explanation: "빈칸 하나를 청소하고, 뒤가 벽이라 멈춰요: 1.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [["#####", "#...#", "#...#", "#####"], 1, 1, 0],
      expected: 6,
      explanation: "빈칸 6칸을 모두 청소해요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [["#####", "#...#", "#.#.#", "#...#", "#####"], 2, 1, 0],
      expected: 8,
      failureNote: "가운데 벽을 둘러싼 8칸을 모두 청소해요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [["######", "#....#", "#.##.#", "#....#", "######"], 1, 4, 2],
      expected: 10,
      failureNote: "가운데 벽을 둘러싼 10칸을 모두 청소해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [["#######", "#.....#", "#.....#", "#.....#", "#######"], 2, 3, 1],
      expected: 13,
      failureNote: "15칸 중 13칸만 청소해요. 뒤로 물러나다 벽을 만나면, 더러운 칸이 남아 있어도 멈춰요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 50 }, (_, r) =>
          Array.from({ length: 50 }, (_, c) =>
            r === 0 || c === 0 || r === 49 || c === 49 || (r * 7 + c * 11) % 17 === 0 ? "#" : ".",
          ).join(""),
        ),
        1,
        1,
        1,
      ],
      expected: 299,
      failureNote: "50 × 50 방이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["규칙이 정확히 적힌 **시뮬레이션**이에요. 알고리즘보다 규칙을 빠짐없이 옮기는 게 중요해요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "- 방향: `dr = [-1, 0, 1, 0]`, `dc = [0, 1, 0, -1]` (북 동 남 서)",
        "- 왼쪽으로 돌기: `d = (d + 3) % 4`, 뒤 칸: `(r − dr[d], c − dc[d])`",
        "- 청소한 칸은 `cleaned` 배열로 표시해요.",
        "",
        "규칙 2에서 방향을 바꾸지 않고 뒤로 가는 것, 규칙 3에서 앞이 더러울 때만 가는 것을 놓치기 쉬워요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "loop:",
        "    if not cleaned[r][c]: cleaned[r][c] = True;  count += 1",
        "    if 둘레에 더러운 빈칸이 없으면:",
        "        br, bc = r - dr[d], c - dc[d]",
        "        벽이면 멈춤, 아니면 r, c = br, bc",
        "    else:",
        "        d = (d + 3) % 4",
        "        앞이 더러운 빈칸이면 한 칸 앞으로",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["뒤로 물러나는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["br, bc = r - dr[d], c - dc[d]", 'if room[br][bc] == "#":', "    break", "r, c = ______"].join("\n"),
          javascript: [
            "const br = r - dr[d], bc = c - dc[d];",
            'if (room[br][bc] === "#") break;',
            "[r, c] = [______];",
          ].join("\n"),
          java: [
            "int br = r - DR[d], bc = c - DC[d];",
            "if (room[br].charAt(bc) == '#') break;",
            "r = ______;",
            "c = bc;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["step-simulation"],
  signalIds: ["sig-follow-rules"],
  estimatedMinutes: 22,
  xp: 50,
};
