import type { Problem } from "@/types/content";

export const simDateAdd: Problem = {
  id: "c:sim-date-add",
  slug: "sim-date-add",
  source: "curated",
  topic: "implementation",
  level: 4,
  title: "며칠 뒤는 몇 월 며칠?",
  summary: "달마다 날 수와 윤년 규칙을 지키며, 해 단위·달 단위로 크게 건너뛰어요",
  statement: [
    '날짜 `date`가 `"YYYY-MM-DD"` 꼴로 주어져요. `days`일 뒤의 날짜를 같은 꼴로 반환해 주세요.',
    "",
    "2월은 보통 28일, **윤년**이면 29일이에요. 윤년은 4로 나누어떨어지는 해예요. 단, 100으로 나누어떨어지면 윤년이 아니고, 400으로 나누어떨어지면 다시 윤년이에요.",
  ].join("\n"),
  inputFormat: "`date`: 시작 날짜, `days`: 지날 날 수예요.",
  outputFormat: '"YYYY-MM-DD" 꼴의 날짜',
  constraints: ["date는 1900-01-01 ~ 2100-12-31", "0 ≤ days ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "date", type: { python: "str", javascript: "string", java: "String" }, description: "시작 날짜" },
      { name: "days", type: { python: "int", javascript: "number", java: "int" }, description: "지날 날 수" },
    ],
    returns: { type: { python: "str", javascript: "string", java: "String" }, description: "날짜" },
  },
  starterCode: {
    python: ["def solution(date, days):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(date, days) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String solution(String date, int days) {",
      '        String answer = "";',
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["2024-02-28", 1],
      expected: "2024-02-29",
      explanation: '2024년은 윤년이라 "2024-02-29"예요.',
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: ["2023-02-28", 1],
      expected: "2023-03-01",
      explanation: '윤년이 아니라 "2023-03-01"이에요.',
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["1999-12-31", 1],
      expected: "2000-01-01",
      failureNote: '해가 바뀌어 "2000-01-01"이에요.',
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: ["2100-02-28", 1],
      expected: "2100-03-01",
      failureNote: '2100년은 100의 배수라 윤년이 아니에요: "2100-03-01".',
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["2000-02-28", 1],
      expected: "2000-02-29",
      failureNote: '2000년은 400의 배수라 윤년이에요: "2000-02-29".',
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "edge",
      args: ["2024-05-05", 0],
      expected: "2024-05-05",
      failureNote: "0일 뒤는 그대로예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: ["2024-01-31", 30],
      expected: "2024-03-01",
      failureNote: '"2024-03-01"이에요. 달마다 날 수가 달라요.',
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: ["1900-01-01", 1000000],
      expected: "4637-11-28",
      failureNote: "100만 일(약 2,738년) 뒤예요. 하루씩 넘기면 느려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**날짜 형식**을 읽고 규칙(달마다 날 수, 윤년)대로 계산하는 구현이에요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "하루씩 넘기면 100만 번이에요. 크게 건너뛰어요.",
        "",
        "1. 먼저 '그해 1월 1일부터 며칠째'로 바꿔요. `days`를 더하면 '올해 1월 1일부터 D일째'가 돼요.",
        "2. D가 그해의 날 수(365 또는 366) 이상이면 빼고 다음 해로 넘어가기를 반복해요. (최대 약 2,700번)",
        "3. 남은 D로 달을 하나씩 빼며 월과 일을 구해요.",
        "",
        "표준 라이브러리(Python `datetime`, Java `LocalDate`)를 써도 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "D = (그해 1월 1일부터 date까지 날 수) + days",
        "while D >= 해의 날 수(y): D -= 해의 날 수(y);  y += 1",
        "m = 1",
        "while D >= 달의 날 수(y, m): D -= 달의 날 수(y, m);  m += 1",
        "return y-m-(D + 1)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["윤년을 판단하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["def is_leap(y):", "    return (y % 4 == 0 and y % 100 != 0) or ______"].join("\n"),
          javascript: ["const isLeap = (y) => (y % 4 === 0 && y % 100 !== 0) || ______;"].join("\n"),
          java: ["boolean isLeap(int y) {", "    return (y % 4 == 0 && y % 100 != 0) || ______;", "}"].join("\n"),
        },
        caption: "java.time.LocalDate.parse(date).plusDays(days).toString()로도 풀 수 있어요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["time-calc"],
  signalIds: ["sig-time-format"],
  estimatedMinutes: 18,
  xp: 40,
};
