import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: ["UURDL"],
    expected: [0, 1],
    explanation: "위로 두 번, 오른쪽, 아래, 왼쪽이라 [0, 1]이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "basic",
    args: ["RRRR"],
    expected: [4, 0],
    explanation: "[4, 0]이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: ["UDUD"],
    expected: [0, 0],
    failureNote: "제자리로 돌아와 [0, 0]이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: ["L"],
    expected: [-1, 0],
    failureNote: "음수 좌표도 돼요: [−1, 0].",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: ["DDDLL"],
    expected: [-2, -3],
    failureNote: "[−2, −3]이에요. 순서는 [x, y]예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => "UDLR"[(i * 7919 + (i >> 3)) % 4]).join("")],
    expected: [0, 0],
    failureNote: "명령 10만 개예요.",
  },
]);

export const simRobotFinal: Problem = {
  id: "c:sim-robot-final",
  slug: "sim-robot-final",
  source: "curated",
  topic: "implementation",
  level: 1,
  title: "명령대로 걷는 다람쥐",
  summary: "명령 글자마다 x, y를 하나씩 바꿔요",
  statement: [
    "다람쥐가 좌표 (0, 0)에서 출발해 `commands`의 글자를 차례로 따라 한 칸씩 움직여요.",
    "",
    "- `U`: 위로 (y + 1)",
    "- `D`: 아래로 (y − 1)",
    "- `L`: 왼쪽으로 (x − 1)",
    "- `R`: 오른쪽으로 (x + 1)",
    "",
    "마지막 위치 `[x, y]`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`commands`: `U`, `D`, `L`, `R`로 된 문자열이에요.",
  outputFormat: "마지막 위치 [x, y]",
  constraints: ["1 ≤ commands의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      { name: "commands", type: { python: "str", javascript: "string", java: "String" }, description: "움직임 명령" },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "[x, y]" },
  },
  starterCode: {
    python: ["def solution(commands):", "    answer = [0, 0]", "    return answer", ""].join("\n"),
    javascript: ["function solution(commands) {", "  let answer = [0, 0];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(String commands) {",
      "        int[] answer = new int[2];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["명령을 **그대로 따라 하면** 되는 시뮬레이션이에요. 상태는 (x, y) 두 값뿐이에요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: ["x = y = 0에서 시작해 글자마다 규칙대로 x나 y를 1씩 바꿔요."].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "x = y = 0",
        "for ch in commands:",
        "    U면 y += 1, D면 y -= 1, L이면 x -= 1, R이면 x += 1",
        "return [x, y]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["글자마다 바꾸는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for ch in commands:",
            '    if ch == "U": y += 1',
            '    elif ch == "D": y -= 1',
            '    elif ch == "L": ______',
            "    else: x += 1",
          ].join("\n"),
          javascript: [
            "for (const ch of commands) {",
            '  if (ch === "U") y++;',
            '  else if (ch === "D") y--;',
            '  else if (ch === "L") ______;',
            "  else x++;",
            "}",
          ].join("\n"),
          java: [
            "for (char ch : commands.toCharArray()) {",
            "    if (ch == 'U') y++;",
            "    else if (ch == 'D') y--;",
            "    else if (ch == 'L') ______;",
            "    else x++;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["direction-move"],
  signalIds: ["sig-follow-rules"],
  estimatedMinutes: 5,
  xp: 10,
};
