import type { Problem } from "@/types/content";

export const sortingBiggestNumber: Problem = {
  id: "c:sorting-biggest-number",
  slug: "sorting-biggest-number",
  source: "curated",
  topic: "sorting",
  level: 5,
  title: "숫자 카드로 가장 큰 수",
  summary: "a+b와 b+a를 비교하는 규칙으로 카드를 정렬해 이어 붙여요",
  statement: [
    "숫자 카드를 모두 한 줄로 이어 붙여 하나의 수를 만들려고 해요. 예를 들어 [3, 30, 34]로는 `34330`, `33430`, `30334` … 를 만들 수 있어요.",
    "",
    '만들 수 있는 **가장 큰 수**를 문자열로 반환해 주세요. 수가 0이면 `"0"`이에요 (`"000"`이 아니에요).',
  ].join("\n"),
  inputFormat: "`cards`: 카드에 적힌 수들이에요.",
  outputFormat: "가장 큰 수 (문자열)",
  constraints: ["1 ≤ cards의 길이 ≤ 10,000", "0 ≤ 카드의 수 ≤ 1,000"],
  signature: {
    name: "solution",
    params: [
      { name: "cards", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "숫자 카드" },
    ],
    returns: { type: { python: "str", javascript: "string", java: "String" }, description: "가장 큰 수" },
  },
  starterCode: {
    python: ["def solution(cards):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(cards) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String solution(int[] cards) {",
      '        String answer = "";',
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[3, 30, 34, 5, 9]],
      expected: "9534330",
      explanation: "9, 5, 34, 3, 30 순서로 이어 붙인 9534330이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[0, 0, 0]],
      expected: "0",
      explanation: '모두 0이면 "0"이에요.',
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [[10, 2]],
      expected: "210",
      failureNote: "숫자 크기 순이면 10이 앞이지만, 210 > 102라서 2가 앞이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[3, 30]],
      expected: "330",
      failureNote: "글자 순(사전 순)으로 뒤집으면 30이 앞(303)이지만, 330이 더 커요. a+b와 b+a를 비교해야 해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [[1000]],
      expected: "1000",
      failureNote: "카드 하나면 그대로예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[121, 12]],
      expected: "12121",
      failureNote: "12121 > 12112라서 12가 앞이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "tricky",
      args: [[0, 1]],
      expected: "10",
      failureNote: "10이에요. 0이 앞에 오면 안 돼요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 10000 }, (_, i) => (i * 37) % 1001)],
      expected: (() => {
        const s = Array.from({ length: 10000 }, (_, i) => (i * 37) % 1001).map(String);
        s.sort((a, b) => (a + b > b + a ? -1 : a + b < b + a ? 1 : 0));
        const r = s.join("");
        return r[0] === "0" ? "0" : r;
      })(),
      failureNote: "카드 1만 장이에요. 모든 순서를 만들어 보는 건 불가능해요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "카드를 어떤 **순서**로 놓을지 정하는 문제 → 두 카드 중 누가 앞에 와야 하는지 **비교 규칙**을 만들어 정렬해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "두 카드 a, b만 보면 답이 보여요. `a+b`와 `b+a`(문자열로 이어 붙인 것) 중 **큰 쪽**이 되도록 놓으면 돼요.",
        "",
        "1. 카드를 문자열로 바꿔요.",
        "2. `a+b > b+a`면 a가 앞이 되도록 정렬해요.",
        '3. 이어 붙이고, 맨 앞이 0이면 전부 0이니 `"0"`을 반환해요.',
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "s = cards를 문자열로",
        "s를 정렬: a+b > b+a 이면 a가 앞",
        "r = s를 이어 붙인 것",
        'return r[0] == "0" 이면 "0", 아니면 r',
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["비교 규칙이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "from functools import cmp_to_key",
            "",
            "def compare(a, b):",
            "    if ______:",
            "        return -1   # a가 앞",
            "    if a + b < b + a:",
            "        return 1",
            "    return 0",
            "",
            "s = sorted(map(str, cards), key=cmp_to_key(compare))",
          ].join("\n"),
          javascript: [
            "const s = cards.map(String);",
            "s.sort((a, b) => {",
            "  if (______) return -1;   // a가 앞",
            "  if (a + b < b + a) return 1;",
            "  return 0;",
            "});",
          ].join("\n"),
          java: [
            "String[] s = new String[cards.length];",
            "for (int i = 0; i < cards.length; i++) s[i] = String.valueOf(cards[i]);",
            "Arrays.sort(s, (a, b) -> ______);",
          ].join("\n"),
        },
        caption: "(b + a).compareTo(a + b)가 음수면 a가 앞이에요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["custom-order"],
  signalIds: ["sig-order-rule"],
  estimatedMinutes: 25,
  xp: 50,
};
