import type { Problem } from "@/types/content";

export const sortingInversions: Problem = {
  id: "c:sorting-inversions",
  slug: "sorting-inversions",
  source: "curated",
  topic: "sorting",
  level: 5,
  title: "뒤바뀐 쌍 세기",
  summary: "병합 정렬로 합칠 때 오른쪽이 먼저 나가면 왼쪽에 남은 수만큼 세요",
  statement: [
    "숫자 카드가 한 줄로 놓여 있어요. 앞에 있는 카드가 뒤에 있는 카드보다 **큰** 쌍, 즉 i < j이면서 `cards[i] > cards[j]`인 쌍을 **뒤바뀐 쌍**이라고 해요.",
    "",
    "뒤바뀐 쌍의 수를 반환해 주세요. 답이 21억을 넘을 수 있어요. (Java는 `long`으로 반환해요)",
  ].join("\n"),
  inputFormat: "`cards`: 카드에 적힌 수들이에요.",
  outputFormat: "뒤바뀐 쌍의 수",
  constraints: ["1 ≤ cards의 길이 ≤ 100,000", "0 ≤ 카드의 수 ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "cards", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "카드들" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "뒤바뀐 쌍의 수" },
  },
  starterCode: {
    python: ["def solution(cards):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(cards) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(int[] cards) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[3, 1, 2]],
      expected: 2,
      explanation: "(3, 1), (3, 2) 두 쌍이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[1, 2, 3, 4]],
      expected: 0,
      explanation: "이미 정렬돼 있으면 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [[5, 4, 3, 2, 1]],
      expected: 10,
      failureNote: "완전히 거꾸로면 모든 쌍, 10이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 2, 1, 1]],
      expected: 4,
      failureNote: "같은 수끼리는 뒤바뀐 게 아니에요. 2와 1 사이 4쌍뿐이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [[7]],
      expected: 0,
      failureNote: "카드 하나면 0이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[2, 4, 1, 3, 5]],
      expected: 3,
      failureNote: "(2, 1), (4, 1), (4, 3) 세 쌍이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => 100000 - i)],
      expected: 4999950000,
      failureNote: "10만 장이 거꾸로면 약 50억 쌍이에요. 모든 쌍을 비교하면 시간 초과이고, Java는 int로 세면 넘쳐요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i * 7919) % 100003)],
      expected: 2500038684,
      failureNote: "10만 장이 뒤섞여 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 3000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'**순서가 뒤바뀐 쌍의 수**' + N이 10만 → 모든 쌍(50억)은 못 봐요. **병합 정렬**의 합치기 단계에서 세요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "병합 정렬로 왼쪽 절반, 오른쪽 절반을 각각 정렬한 뒤 합칠 때:",
        "",
        "- 왼쪽 맨 앞 ≤ 오른쪽 맨 앞이면 왼쪽을 내보내요. 뒤바뀐 쌍은 없어요.",
        "- 오른쪽 맨 앞이 더 작으면, **왼쪽에 남은 모든 수**가 그보다 커요. 남은 개수만큼 쌍을 더해요.",
        "",
        "절반 안의 쌍은 재귀가 세 주고, 두 절반 사이의 쌍은 합칠 때 세요. 전체 O(N log N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "sort_count(a):",
        "    if len(a) <= 1: return a, 0",
        "    left, x = sort_count(a[:mid]); right, y = sort_count(a[mid:])",
        "    merged, count = [], x + y",
        "    합치면서 right[j] < left[i]이면 count += len(left) - i",
        "    return merged, count",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["오른쪽이 먼저 나갈 때 더하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while i < len(left) and j < len(right):",
            "    if left[i] <= right[j]:",
            "        merged.append(left[i]); i += 1",
            "    else:",
            "        merged.append(right[j]); j += 1",
            "        count += ______",
          ].join("\n"),
          javascript: [
            "while (i < left.length && j < right.length) {",
            "  if (left[i] <= right[j]) merged.push(left[i++]);",
            "  else {",
            "    merged.push(right[j++]);",
            "    count += ______;",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "while (i <= mid && j <= hi) {",
            "    if (a[i] <= a[j]) tmp[k++] = a[i++];",
            "    else {",
            "        tmp[k++] = a[j++];",
            "        count += ______;",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "Java는 배열 하나와 임시 배열로 제자리에서 합쳐요. 개수는 long으로 세요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["merge-step"],
  signalIds: ["sig-inversions"],
  estimatedMinutes: 30,
  xp: 50,
};
