import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const sortingKthHeaviest: Problem = {
  id: "c:sorting-kth-heaviest",
  slug: "sorting-kth-heaviest",
  source: "curated",
  topic: "sorting",
  level: 1,
  title: "K번째로 무거운 도토리",
  summary: "무거운 순으로 정렬하면 K번째 자리에 답이 있어요",
  statement: [
    "노디가 도토리를 모아 무게를 쟀어요. 무게 `weights`와 `k`가 주어질 때, **k번째로 무거운** 도토리의 무게를 반환해 주세요.",
    "",
    "무게가 같은 도토리도 각각 따로 세요. 예를 들어 [5, 5, 3]에서 2번째로 무거운 도토리는 5예요.",
  ].join("\n"),
  inputFormat: "`weights`: 도토리 무게, `k`: 몇 번째로 무거운지예요.",
  outputFormat: "k번째로 무거운 도토리의 무게",
  constraints: ["1 ≤ weights의 길이 ≤ 100,000", "1 ≤ k ≤ weights의 길이", "1 ≤ 무게 ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "weights",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "도토리 무게",
      },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "몇 번째" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "k번째로 무거운 무게" },
  },
  starterCode: {
    python: ["def solution(weights, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(weights, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] weights, int k) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[12, 35, 7, 21, 30], 2],
      expected: 30,
      explanation: "무거운 순으로 35, 30, 21, 12, 7이라 2번째는 30이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [[5, 5, 3], 2],
      expected: 5,
      explanation: "무게가 같아도 따로 세요. 2번째도 5예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[9], 1],
      expected: 9,
      failureNote: "하나뿐이면 그 무게예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[4, 8, 6], 3],
      expected: 4,
      failureNote: "k가 개수와 같으면 가장 가벼운 도토리예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[20, 3, 100, 9], 1],
      expected: 100,
      failureNote: "숫자를 글자로 정렬하면 '9'가 '100'보다 뒤에 와요. JavaScript는 비교 함수를 꼭 주세요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[7, 7, 7, 7], 3],
      expected: 7,
      failureNote: "모두 같으면 답도 같아요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i * 7919) % 1000003), 50000],
      expected: 499969,
      failureNote: "도토리 10만 개예요. 가장 무거운 것을 k번 찾아 지우면(O(N·k)) 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["'**K번째로** 무거운' → 정렬하면 K번째 자리에 답이 있어요. **정렬하고 보기**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 무게를 **무거운 순**(내림차순)으로 정렬해요.",
        "2. k번째는 인덱스 `k - 1`이에요.",
        "",
        "가벼운 순으로 정렬했다면 뒤에서 k번째, 즉 인덱스 `n - k`예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: ["~~~text", "sorted_w = weights를 무거운 순으로 정렬", "return sorted_w[k - 1]", "~~~"].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["정렬한 뒤 꺼내는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["sorted_w = sorted(weights, reverse=True)", "return ______"].join("\n"),
          javascript: ["const sorted = [...weights].sort((a, b) => b - a);", "return ______;"].join("\n"),
          java: ["int[] sorted = weights.clone();", "Arrays.sort(sorted);   // 가벼운 순", "return ______;"].join("\n"),
        },
        caption: "Arrays.sort는 가벼운 순이라 k번째로 무거운 건 뒤에서 k번째예요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sort-then-scan"],
  signalIds: ["sig-neighbor-after-sort"],
  visualization: {
    presets: [
      problemPreset(
        "sorting-kth-heaviest-ex1",
        "sort-merge",
        "병합 정렬로 줄 세우기",
        "무게를 정렬하면 자리만 보고 K번째를 알 수 있어요. (그림은 가벼운 순이라 뒤에서 k번째를 봐요)",
        [[12, 35, 7, 21, 30]],
      ),
    ],
  },
  estimatedMinutes: 8,
  xp: 10,
};
