import type { Problem } from "@/types/content";

export const sortingMeetingRooms: Problem = {
  id: "c:sorting-meeting-rooms",
  slug: "sorting-meeting-rooms",
  source: "curated",
  topic: "sorting",
  level: 4,
  title: "필요한 회의실 수",
  summary: "시작·끝 시각을 한 줄로 정렬하고 훑으며 동시에 열린 회의를 세요",
  statement: [
    "숲속 마을 회관에서 오늘 회의가 여러 개 열려요. 회의는 `[시작, 끝]` 모양이고, 끝 시각에 회의실이 비어요.",
    "",
    "모든 회의를 열기 위해 필요한 **회의실의 최소 개수**를 반환해 주세요. 한 회의가 끝나는 시각에 다른 회의가 시작하면 **같은 회의실**을 써도 돼요.",
  ].join("\n"),
  inputFormat: "`meetings`: `[시작, 끝]` 회의 리스트예요.",
  outputFormat: "필요한 회의실 수",
  constraints: ["1 ≤ meetings의 길이 ≤ 100,000", "0 ≤ 시작 < 끝 ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "meetings",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "회의들",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "회의실 수" },
  },
  starterCode: {
    python: ["def solution(meetings):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(meetings) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[][] meetings) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        [
          [0, 30],
          [5, 10],
          [15, 20],
        ],
      ],
      expected: 2,
      explanation: "[0, 30] 동안 [5, 10]과 [15, 20]이 차례로 열려요. 동시에 최대 2개라 2개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [
        [
          [1, 5],
          [5, 9],
        ],
      ],
      expected: 1,
      explanation: "5시에 끝나고 5시에 시작하면 같은 방을 써요. 1개예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[[2, 3]]],
      expected: 1,
      failureNote: "회의 하나면 1개예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [
        [
          [1, 10],
          [2, 9],
          [3, 8],
        ],
      ],
      expected: 3,
      failureNote: "셋이 모두 겹쳐요. 3개예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        [
          [4, 6],
          [1, 4],
          [6, 8],
          [2, 5],
        ],
      ],
      expected: 2,
      failureNote: "같은 시각에 끝과 시작이 겹치면 끝을 먼저 처리해야 해요. 2개예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => [(i * 7919) % 100000, ((i * 7919) % 100000) + 1000])],
      expected: 1000,
      failureNote: "회의 10만 개예요. 시각마다 열린 회의를 모두 세면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 3000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["'**동시에 겹치는 구간**이 가장 많을 때' → 시각 순으로 정렬해 훑는 **구간 정렬**이에요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "회의 시작은 +1, 끝은 −1인 **사건**으로 바꿔요.",
        "",
        "1. 사건들을 시각 순으로 정렬해요. 같은 시각이면 **끝(−1)을 먼저** 처리해요. 그래야 같은 방을 이어 써요.",
        "2. 앞에서부터 더해 가며 '지금 열린 회의 수'의 최댓값을 구해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "events = []",
        "for s, e in meetings: events에 (s, +1), (e, -1) 추가",
        "events를 (시각, 변화량) 순으로 정렬   # 같은 시각이면 -1이 먼저",
        "now = best = 0",
        "for t, d in events: now += d; best = max(best, now)",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["사건을 정렬하는 기준이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "events = []",
            "for s, e in meetings:",
            "    events.append((s, 1))",
            "    events.append((e, -1))",
            "events.sort()   # 같은 시각이면 -1이 1보다 먼저",
            "for t, d in events:",
            "    now += ______",
            "    best = max(best, now)",
          ].join("\n"),
          javascript: [
            "const events = [];",
            "for (const [s, e] of meetings) events.push([s, 1], [e, -1]);",
            "events.sort((a, b) => a[0] - b[0] || ______);",
            "for (const [, d] of events) {",
            "  now += d;",
            "  best = Math.max(best, now);",
            "}",
          ].join("\n"),
          java: [
            "int[][] events = new int[meetings.length * 2][];",
            "for (int i = 0; i < meetings.length; i++) {",
            "    events[2 * i] = new int[] {meetings[i][0], 1};",
            "    events[2 * i + 1] = new int[] {meetings[i][1], -1};",
            "}",
            "Arrays.sort(events, (x, y) -> x[0] != y[0] ? Integer.compare(x[0], y[0]) : ______);",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["interval-sweep"],
  signalIds: ["sig-intervals"],
  estimatedMinutes: 18,
  xp: 40,
};
