import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [["leaf10", "leaf9", "moss1", "leaf2"]],
    expected: ["leaf2", "leaf9", "leaf10", "moss1"],
    explanation: "leaf 묶음이 먼저(2, 9, 10 순), 그다음 moss예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [["Leaf3", "leaf03", "LEAF1"]],
    expected: ["LEAF1", "Leaf3", "leaf03"],
    explanation: "대소문자는 무시해서 모두 leaf예요. LEAF1이 먼저, Leaf3과 leaf03은 둘 다 3이라 원래 순서를 지켜요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [["solo42"]],
    expected: ["solo42"],
    failureNote: "하나면 그대로예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [["b1", "a100", "a20", "B0"]],
    expected: ["a20", "a100", "B0", "b1"],
    failureNote: "a20 < a100 (수의 크기), 그다음 b 묶음: B0, b1이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [["ab1", "a2", "abc0"]],
    expected: ["a2", "ab1", "abc0"],
    failureNote: "글자 부분 a < ab < abc 순이에요. 숫자보다 글자 부분을 먼저 비교해요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [["x00010", "x9", "x010", "x10"]],
    expected: ["x9", "x00010", "x010", "x10"],
    failureNote: "앞의 0은 무시해서 x9 다음 10이 세 개예요. 셋은 원래 순서 그대로예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "basic",
    args: [["Zoo5", "apple5", "Mango5"]],
    expected: ["apple5", "Mango5", "Zoo5"],
    failureNote: "숫자가 같으면 글자 순: apple, Mango, Zoo예요 (대소문자 무시).",
  },
]);

export const sortingPhotoNames: Problem = {
  id: "c:sorting-photo-names",
  slug: "sorting-photo-names",
  source: "curated",
  topic: "sorting",
  level: 3,
  title: "사진 이름 똑똑하게 정렬하기",
  summary: "글자 부분은 대소문자 구분 없이, 숫자 부분은 수의 크기로 비교해요",
  statement: [
    "노디의 사진 파일 이름은 **영어 글자** 뒤에 **숫자**가 붙은 모양이에요. 예: `leaf10`, `Moss2`, `leaf007`.",
    "",
    "글자로만 정렬하면 `leaf10`이 `leaf9`보다 앞에 와서 불편해요. 그래서 이렇게 정렬하려고 해요.",
    "",
    "1. 글자 부분을 **대소문자 구분 없이** 사전 순으로 비교해요.",
    "2. 글자 부분이 같으면 숫자 부분을 **수의 크기**로 비교해요. (`007`은 7이에요)",
    "3. 둘 다 같으면 **원래 순서**를 지켜요.",
    "",
    "정렬된 파일 이름 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`files`: 파일 이름 리스트예요.",
  outputFormat: "규칙대로 정렬한 파일 이름 리스트",
  constraints: ["1 ≤ files의 길이 ≤ 1,000", "파일 이름은 영어 대소문자 1~10글자 뒤에 숫자 1~5자리가 붙은 모양이에요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "files",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "파일 이름",
      },
    ],
    returns: {
      type: { python: "list[str]", javascript: "string[]", java: "String[]" },
      description: "정렬된 파일 이름",
    },
  },
  starterCode: {
    python: ["def solution(files):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(files) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String[] solution(String[] files) {",
      "        String[] answer = new String[files.length];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["비교 규칙이 여러 단계인 **정렬 기준 정하기**예요. 기준을 계산하는 함수만 잘 만들면 돼요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 파일 이름을 **글자 부분**과 **숫자 부분**으로 나눠요. 처음 나오는 숫자 위치에서 자르면 돼요.",
        "2. 정렬 키는 `(글자.소문자, int(숫자))`예요.",
        "3. 내장 정렬은 **안정 정렬**이라, 키가 같으면 원래 순서가 저절로 유지돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "def key(name):",
        "    k = 첫 숫자의 위치",
        "    return (name[:k]의 소문자, int(name[k:]))",
        "return files를 key로 정렬 (안정 정렬)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["정렬 키를 만드는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def key(name):",
            "    k = 0",
            "    while not name[k].isdigit():",
            "        k += 1",
            "    return ______",
            "return sorted(files, key=key)",
          ].join("\n"),
          javascript: [
            "const split = (name) => {",
            "  const k = name.search(/[0-9]/);",
            "  return [name.slice(0, k).toLowerCase(), Number(name.slice(k))];",
            "};",
            "return [...files].sort((a, b) => {",
            "  const [ha, na] = split(a), [hb, nb] = split(b);",
            "  if (ha !== hb) return ha < hb ? -1 : 1;",
            "  return ______;",
            "});",
          ].join("\n"),
          java: [
            "Arrays.sort(answer, (a, b) -> {",
            "    int ka = firstDigit(a), kb = firstDigit(b);",
            "    int c = a.substring(0, ka).toLowerCase().compareTo(b.substring(0, kb).toLowerCase());",
            "    if (c != 0) return c;",
            "    return ______;",
            "});",
          ].join("\n"),
        },
        caption: "Java의 Arrays.sort는 객체 배열에서 안정 정렬이라 같으면 원래 순서를 지켜요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["custom-order"],
  signalIds: ["sig-order-rule"],
  estimatedMinutes: 18,
  xp: 30,
};
