import type { Problem } from "@/types/content";

export const sortingRaftPairs: Problem = {
  id: "c:sorting-raft-pairs",
  slug: "sorting-raft-pairs",
  source: "curated",
  topic: "sorting",
  level: 4,
  title: "뗏목 태우기",
  summary: "정렬한 뒤 가장 무거운 친구와 가장 가벼운 친구를 짝지어요",
  statement: [
    "친구들이 강을 건너려고 해요. 뗏목에는 **최대 두 명**까지, 무게 합이 `limit` 이하일 때만 탈 수 있어요.",
    "",
    "모두 건너는 데 필요한 **뗏목의 최소 개수**를 반환해 주세요. 모든 친구의 무게는 `limit` 이하예요.",
  ].join("\n"),
  inputFormat: "`weights`: 친구들의 무게, `limit`: 뗏목 한 척이 버티는 무게예요.",
  outputFormat: "필요한 뗏목 수",
  constraints: ["1 ≤ weights의 길이 ≤ 100,000", "1 ≤ 무게 ≤ limit ≤ 30,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "weights",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "친구들의 무게",
      },
      { name: "limit", type: { python: "int", javascript: "number", java: "int" }, description: "뗏목 한도" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "뗏목 수" },
  },
  starterCode: {
    python: ["def solution(weights, limit):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(weights, limit) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] weights, int limit) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[70, 50, 80, 50], 100],
      expected: 3,
      explanation: "50+50이 한 척, 70과 80은 각자 한 척씩이라 3척이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [[30, 70, 50, 50], 100],
      expected: 2,
      explanation: "30+70, 50+50으로 2척이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[40], 50],
      expected: 1,
      failureNote: "혼자면 1척이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[100, 100, 100], 100],
      expected: 3,
      failureNote: "모두 혼자 타야 해서 3척이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[10, 20, 30, 40], 50],
      expected: 2,
      failureNote:
        "가장 가벼운 10과 가장 무거운 40, 20과 30을 짝지으면 2척이에요. 10+20처럼 가벼운 친구끼리 먼저 태우면 손해예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [[60, 20, 90, 40], 100],
      expected: 3,
      failureNote:
        "90은 가장 가벼운 20과도 못 타서 혼자 한 척이에요. 남은 20, 40, 60은 두 척이 필요해서 모두 3척이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => 40 + ((i * 7) % 61)), 100],
      expected: 82786,
      failureNote: "친구 10만 명이에요. 친구마다 짝을 처음부터 찾으면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "정렬해 두면 '가장 무거운 친구의 짝은 가장 가벼운 친구'로 정할 수 있어요 → **정렬 후 두 포인터**예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 무게를 정렬하고, 가장 가벼운 쪽 `i`와 가장 무거운 쪽 `j`를 가리켜요.",
        "2. 가장 무거운 `j`는 어차피 한 척을 타요. 가장 가벼운 `i`와 합이 limit 이하면 **같이 태워요** (`i += 1`).",
        "3. `j -= 1`, 뗏목 수 += 1. `i > j`가 될 때까지 반복해요.",
        "",
        "가장 무거운 친구가 가장 가벼운 친구와도 못 타면, 누구와도 못 타요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "w = weights를 정렬",
        "i = 0, j = n - 1, rafts = 0",
        "while i <= j:",
        "    if w[i] + w[j] <= limit: i += 1",
        "    j -= 1; rafts += 1",
        "return rafts",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["같이 태울지 정하는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["while i <= j:", "    if ______:", "        i += 1", "    j -= 1", "    rafts += 1"].join("\n"),
          javascript: ["while (i <= j) {", "  if (______) i++;", "  j--;", "  rafts++;", "}"].join("\n"),
          java: ["while (i <= j) {", "    if (______) i++;", "    j--;", "    rafts++;", "}"].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sort-then-scan"],
  signalIds: ["sig-neighbor-after-sort"],
  estimatedMinutes: 18,
  xp: 40,
};
