import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[1, 0, 1, 1, 0, 0, 1]],
    expected: 6,
    explanation: "처음 6일(맑음 3, 비 3)이나 마지막 6일이 가장 길어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[1, 1, 1]],
    expected: 0,
    explanation: "비 온 날이 없어서 0이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[0, 1]],
    expected: 2,
    failureNote: "이틀이 딱 맞아요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [[0]],
    expected: 0,
    failureNote: "하루로는 같을 수 없어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [[0, 0, 1, 0, 1, 1, 1, 0]],
    expected: 8,
    failureNote:
      "전체 8일이 답이에요. 첫날부터 시작하는 기간을 세려면 '누적 합 0은 −1번 위치에서 처음 나왔다'고 적어 두고 시작해야 해요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [[1, 0, 0, 1, 1, 1, 1, 0, 0]],
    expected: 8,
    failureNote: "같은 누적 합이 다시 나오면 처음 나온 위치를 그대로 둬야 가장 긴 기간이 돼요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [[...Array.from({ length: 50000 }, () => 1), ...Array.from({ length: 50000 }, () => 0)]],
    expected: 100000,
    failureNote:
      "맑은 날 5만 일 뒤에 비 온 날 5만 일이에요. 전체 10만 일이 답이에요. 기간을 하나씩 확인하면 시간 초과예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => ((i * i * 7 + 3 * i) % 5 < 2 ? 1 : 0))],
    expected: 12,
    failureNote: "10만 일, 맑음과 비가 섞여 있어요.",
  },
]);

export const hashBalancedDays: Problem = {
  id: "c:hash-balanced-days",
  slug: "hash-balanced-days",
  source: "curated",
  topic: "hash",
  level: 5,
  title: "맑은 날과 비 온 날이 같은 기간",
  summary: "맑음 +1, 비 −1로 누적 합을 만들고 같은 값이 처음 나온 위치를 기억해요",
  statement: [
    "노디의 날씨 일기에는 날마다 맑았으면 `1`, 비가 왔으면 `0`이 적혀 있어요.",
    "",
    "**연속한 며칠** 중 맑은 날 수와 비 온 날 수가 **같은** 가장 긴 기간의 길이(일 수)를 반환해 주세요. 그런 기간이 없으면 0이에요.",
  ].join("\n"),
  inputFormat: "`days`: 날마다의 날씨 (1 = 맑음, 0 = 비)예요.",
  outputFormat: "가장 긴 기간의 일 수",
  constraints: ["1 ≤ days의 길이 ≤ 100,000", "days[i]는 0 또는 1이에요"],
  signature: {
    name: "solution",
    params: [
      { name: "days", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "날씨 기록" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 긴 기간의 길이" },
  },
  starterCode: {
    python: ["def solution(days):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(days) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] days) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "맑음을 **+1**, 비를 **−1**로 바꾸면 '맑은 날 = 비 온 날'은 '구간 합 = 0'이에요 → **누적 합 + 해시**예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "구간 합이 0이려면 **양 끝의 누적 합이 같아야** 해요.",
        "",
        "1. dict `first`에 **누적 합 → 처음 나온 위치**를 적어요. 시작 전 누적 합 0은 위치 −1이에요.",
        "2. 하루씩 누적 합 `total`을 만들어요.",
        "3. `total`이 전에 나왔으면 `i − first[total]`이 후보 길이예요.",
        "4. 처음 나온 값이면 `first[total] = i`로 적어요. 이미 있으면 **바꾸지 않아요** (가장 먼저 나온 위치여야 가장 길어요).",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "first = {0: -1}",
        "total = 0, best = 0",
        "for i, d in enumerate(days):",
        "    total += (1 if d == 1 else -1)",
        "    if total in first: best = max(best, i - first[total])",
        "    else: first[total] = i",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["기간의 길이를 구하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "first = {0: -1}",
            "for i, d in enumerate(days):",
            "    total += 1 if d == 1 else -1",
            "    if total in first:",
            "        best = max(best, ______)",
            "    else:",
            "        first[total] = i",
          ].join("\n"),
          javascript: [
            "const first = new Map([[0, -1]]);",
            "for (let i = 0; i < days.length; i++) {",
            "  total += days[i] === 1 ? 1 : -1;",
            "  if (first.has(total)) best = Math.max(best, ______);",
            "  else first.set(total, i);",
            "}",
          ].join("\n"),
          java: [
            "Map<Integer, Integer> first = new HashMap<>();",
            "first.put(0, -1);",
            "for (int i = 0; i < days.length; i++) {",
            "    total += days[i] == 1 ? 1 : -1;",
            "    if (first.containsKey(total)) best = Math.max(best, ______);",
            "    else first.put(total, i);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["prefix-sum-hash"],
  signalIds: ["sig-subarray-sum"],
  estimatedMinutes: 25,
  xp: 50,
};
