import type { Problem } from "@/types/content";

export const hashCampingGear: Problem = {
  id: "c:hash-camping-gear",
  slug: "hash-camping-gear",
  source: "curated",
  topic: "hash",
  level: 4,
  title: "캠핑 장비 고르기",
  summary: "종류별 개수를 세고 (개수 + 1)을 모두 곱해요",
  statement: [
    "노디가 캠핑 가방을 싸요. 장비마다 **종류**(모자, 텐트, 랜턴 …)가 있고, 한 종류에서는 **최대 한 개**만 챙길 수 있어요. 챙기지 않는 종류가 있어도 괜찮지만, **적어도 하나**는 챙겨야 해요.",
    "",
    "장비들의 종류 `kinds`가 주어질 때 (같은 종류라도 서로 다른 장비예요), 가방을 싸는 서로 다른 방법의 수를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`kinds`: 장비마다 종류를 적은 리스트예요.",
  outputFormat: "가방을 싸는 방법의 수",
  constraints: ["1 ≤ kinds의 길이 ≤ 30", "종류 이름은 영어 소문자로 된 1~10글자예요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "kinds",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "장비들의 종류",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "방법의 수" },
  },
  starterCode: {
    python: ["def solution(kinds):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(kinds) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String[] kinds) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["hat", "hat", "tent", "lamp", "lamp", "lamp"]],
      expected: 23,
      explanation:
        "모자는 안 챙김 포함 3가지, 텐트 2가지, 랜턴 4가지. 3 × 2 × 4 = 24에서 아무것도 안 챙기는 1가지를 빼면 23이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [["hat"]],
      expected: 1,
      explanation: "모자 하나를 챙기는 1가지뿐이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [["a", "b", "c"]],
      expected: 7,
      failureNote: "종류마다 챙김/안 챙김 2가지씩: 2 × 2 × 2 − 1 = 7이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [["a", "a", "a"]],
      expected: 3,
      failureNote: "한 종류에서 한 개만 챙길 수 있어서 3가지예요. 여러 개를 같이 고르는 경우를 세면 틀려요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "stress",
      args: [
        [
          "k0",
          "k1",
          "k2",
          "k3",
          "k4",
          "k5",
          "k6",
          "k7",
          "k8",
          "k9",
          "ka",
          "kb",
          "kc",
          "kd",
          "ke",
          "kf",
          "kg",
          "kh",
          "ki",
          "kj",
          "kk",
          "kl",
          "km",
          "kn",
          "ko",
          "kp",
          "kq",
          "kr",
          "ks",
          "kt",
        ],
      ],
      expected: 1073741823,
      failureNote:
        "30종류가 하나씩이면 2^30 − 1 = 1,073,741,823가지예요. 모든 경우를 하나씩 만들어 보면 시간 초과예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [["cup", "map", "cup", "rope", "map", "cup"]],
      expected: 23,
      failureNote: "cup 3개, map 2개, rope 1개: 4 × 3 × 2 − 1 = 23이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "edge",
      // prettier-ignore
      args: [["same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same","same"]],
      expected: 30,
      failureNote: "모두 같은 종류면 30가지예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "종류마다 **몇 개**인지만 알면 돼요 → **개수 세기** 뒤에 곱셈으로 경우의 수를 구해요.",
        "",
        "모든 조합을 백트래킹으로 만들면 2^30가지라 너무 많아요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. dict로 종류별 개수를 세요.",
        "2. 종류 하나에서 고르는 방법은 '그 종류의 장비 중 하나' + '안 챙김' = **개수 + 1**가지예요.",
        "3. 종류끼리는 따로 고르니까 모두 **곱해요**.",
        "4. 아무것도 안 챙기는 1가지를 **빼요**.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count = kinds의 종류별 개수",
        "ways = 1",
        "for c in count의 값들:",
        "    ways *= (c + 1)",
        "return ways - 1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["경우의 수를 곱하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["ways = 1", "for c in count.values():", "    ways *= ______", "return ways - 1"].join("\n"),
          javascript: [
            "let ways = 1;",
            "for (const c of count.values()) {",
            "  ways *= ______;",
            "}",
            "return ways - 1;",
          ].join("\n"),
          java: [
            "int ways = 1;",
            "for (int c : count.values()) {",
            "    ways *= ______;",
            "}",
            "return ways - 1;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["frequency-count", "group-by-key"],
  signalIds: ["sig-count-each"],
  estimatedMinutes: 15,
  xp: 40,
};
