import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[1, 5, 3, 4, 2], 2],
    expected: 3,
    explanation: "(1, 3), (5, 3), (4, 2) 세 쌍이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [[3, 3, 3], 0],
    expected: 3,
    explanation:
      "k = 0이면 키가 같은 쌍이에요. 세 명 중 두 명을 고르는 3쌍이에요. x - k와 x + k가 같은 값이라 두 번 세지 않게 조심해요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "basic",
    args: [[1, 2, 3], 5],
    expected: 0,
    failureNote: "차이가 5인 쌍이 없어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [[7], 0],
    expected: 0,
    failureNote: "한 명뿐이면 쌍이 없어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [[1, 1, 2, 2], 1],
    expected: 4,
    failureNote: "1과 2가 두 명씩이라 2 × 2 = 4쌍이에요. 같은 값이 여러 번 나오면 개수를 세야 해요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "edge",
    args: [[0, 1000000], 1000000],
    expected: 1,
    failureNote: "가장 큰 차이예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => i % 1000), 1],
    expected: 9990000,
    failureNote: "10만 명이에요. 모든 쌍을 비교하면 약 50억 번이라 시간 초과예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, () => 7), 0],
    expected: 4999950000,
    failureNote: "10만 명의 키가 모두 같아요. 답이 약 50억이라 Java는 int로 세면 넘쳐요 (long을 쓰세요).",
  },
]);

export const hashDiffPairs: Problem = {
  id: "c:hash-diff-pairs",
  slug: "hash-diff-pairs",
  source: "curated",
  topic: "hash",
  level: 3,
  title: "키 차이가 K인 짝꿍",
  summary: "지나온 값의 개수를 세어 두고 x - k, x + k가 몇 번 나왔는지 더해요",
  statement: [
    "숲속 학교에서 키 차이가 정확히 `k`인 두 친구를 짝꿍으로 정하려고 해요.",
    "",
    "친구들의 키 `heights`가 주어질 때, 서로 다른 두 친구 (i < j) 중 **키 차이가 정확히 k**인 쌍의 수를 반환해 주세요. 키가 같은 친구가 여럿일 수 있고, 같은 키라도 다른 친구면 다른 쌍이에요.",
    "",
    "답이 21억을 넘을 수 있어요. (Java는 `long`으로 반환해요)",
  ].join("\n"),
  inputFormat: "`heights`: 친구들의 키, `k`: 원하는 키 차이예요.",
  outputFormat: "키 차이가 k인 쌍의 수",
  constraints: ["1 ≤ heights의 길이 ≤ 100,000", "0 ≤ 키 ≤ 1,000,000", "0 ≤ k ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "heights",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "친구들의 키",
      },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "키 차이" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "쌍의 수" },
  },
  starterCode: {
    python: ["def solution(heights, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(heights, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public long solution(int[] heights, int k) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'차이가 **정확히 k**인 쌍' → 지금 키가 `x`면 짝은 `x - k` 또는 `x + k`로 정해져 있어요. **짝 찾기** 해시예요.",
        "",
        "같은 키가 여럿일 수 있으니 set이 아니라 **개수를 세는 dict**가 필요해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. dict `count`에 지금까지 지나온 키의 개수를 세어 둬요.",
        "2. 친구 `x`를 볼 때, 앞에 있던 `x - k`인 친구 수와 `x + k`인 친구 수를 답에 더해요.",
        "3. `k == 0`이면 두 값이 같으니 `count[x]`를 **한 번만** 더해요.",
        "4. 그다음 `count[x] += 1` 해요.",
        "",
        "앞에 있던 친구하고만 짝을 지으니까 같은 쌍을 두 번 세지 않아요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count = {}, answer = 0",
        "for x in heights:",
        "    if k == 0: answer += count[x]",
        "    else: answer += count[x - k] + count[x + k]",
        "    count[x] += 1",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["k가 0이 아닐 때 짝의 수를 더하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for x in heights:",
            "    if k == 0:",
            "        answer += count.get(x, 0)",
            "    else:",
            "        answer += ______",
            "    count[x] = count.get(x, 0) + 1",
          ].join("\n"),
          javascript: [
            "for (const x of heights) {",
            "  if (k === 0) answer += count.get(x) ?? 0;",
            "  else answer += ______;",
            "  count.set(x, (count.get(x) ?? 0) + 1);",
            "}",
          ].join("\n"),
          java: [
            "for (int x : heights) {",
            "    if (k == 0) answer += count.getOrDefault(x, 0);",
            "    else answer += ______;",
            "    count.put(x, count.getOrDefault(x, 0) + 1);",
            "}",
          ].join("\n"),
        },
        caption: "답은 long으로 세요. int로 세면 21억을 넘을 때 음수가 돼요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["complement-lookup", "frequency-count"],
  signalIds: ["sig-pair-target"],
  estimatedMinutes: 15,
  xp: 30,
};
