import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [["mimi", "nodi", "toto", "nodi", "mimi"]],
    expected: "nodi",
    explanation: "4번째에 nodi가 다시 나와요. mimi도 다시 나오지만 그보다 늦어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [["mimi", "nodi"]],
    expected: "",
    explanation: "다시 나온 이름이 없어서 빈 문자열이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [["solo"]],
    expected: "",
    failureNote: "한 명뿐이면 다시 나올 수 없어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [["a", "b", "b", "a"]],
    expected: "b",
    failureNote: "먼저 적힌 a가 아니라, 다시 나온 순간이 더 빠른 b가 답이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [["zz", "z", "zzz", "z"]],
    expected: "z",
    failureNote: "z와 zz는 다른 이름이에요. 4번째의 z가 처음 재방문이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [[...Array.from({ length: 99999 }, (_, i) => "n" + i.toString(36)), "n" + (777).toString(36)]],
    expected: "nll",
    failureNote: "10만 명 중 맨 마지막에서야 다시 나온 이름이 있어요. 이름마다 앞부분을 다시 훑으면 시간 초과예요.",
  },
]);

export const hashFirstRepeat: Problem = {
  id: "c:hash-first-repeat",
  slug: "hash-first-repeat",
  source: "curated",
  topic: "hash",
  level: 1,
  title: "방명록의 첫 번째 재방문",
  summary: "앞에서부터 읽다가 처음으로 다시 나온 이름을 찾아요",
  statement: [
    "숲 도서관 방명록에는 방문한 사람의 이름이 온 순서대로 적혀 있어요.",
    "",
    '앞에서부터 읽어 가다가 **이미 한 번 나온 이름이 처음으로 다시 나오는** 순간, 그 이름을 반환해 주세요. 끝까지 읽어도 다시 나온 이름이 없으면 빈 문자열 `""`을 반환해요.',
  ].join("\n"),
  inputFormat: "`names`: 방명록에 적힌 순서대로의 이름 리스트예요.",
  outputFormat: "처음으로 다시 나온 이름, 없으면 빈 문자열",
  constraints: ["1 ≤ names의 길이 ≤ 100,000", "이름은 영어 소문자와 숫자로 된 1~10글자예요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "names",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "방명록 이름들",
      },
    ],
    returns: { type: { python: "str", javascript: "string", java: "String" }, description: "처음으로 다시 나온 이름" },
  },
  starterCode: {
    python: ["def solution(names):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(names) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String solution(String[] names) {",
      '        String answer = "";',
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["'**이미 나온 적 있나?**'를 이름마다 물어봐요 → 본 이름을 **set**에 적어 두는 해시 문제예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 빈 set `seen`을 만들어요.",
        "2. 이름을 앞에서부터 보면서, `seen`에 **이미 있으면** 그 이름이 답이에요. 바로 반환해요.",
        "3. 없으면 `seen`에 넣고 다음 이름으로 가요.",
        "4. 끝까지 못 찾으면 빈 문자열이에요.",
        "",
        "확인을 **먼저**, 넣기를 **나중에** 해야 자기 자신과 비교하지 않아요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "seen = 빈 set",
        "for name in names:",
        "    if name이 seen에 있으면: return name",
        "    seen에 name 추가",
        'return ""',
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["확인하고 넣는 순서가 중요해요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "seen = set()",
            "for name in names:",
            "    if ______:",
            "        return name",
            "    seen.add(name)",
            'return ""',
          ].join("\n"),
          javascript: [
            "const seen = new Set();",
            "for (const name of names) {",
            "  if (______) return name;",
            "  seen.add(name);",
            "}",
            'return "";',
          ].join("\n"),
          java: [
            "Set<String> seen = new HashSet<>();",
            "for (String name : names) {",
            "    if (______) return name;",
            "    seen.add(name);",
            "}",
            'return "";',
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["existence-check"],
  signalIds: ["sig-seen-before"],
  estimatedMinutes: 8,
  xp: 10,
};
