import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[100, 4, 200, 1, 3, 2]],
    expected: 4,
    explanation: "1, 2, 3, 4가 이어져서 4예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[5, 5, 5]],
    expected: 1,
    explanation: "같은 번호는 한 번만 셉니다. 길이 1이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "tricky",
    args: [[0, -1, 1, 2, -2, 10]],
    expected: 5,
    failureNote: "음수도 이어져요: −2부터 2까지 5개.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [[7]],
    expected: 1,
    failureNote: "하나뿐이면 1이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [[1, 3, 5, 7]],
    expected: 1,
    failureNote: "이어지는 번호가 없어서 1이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [[3, 2, 1, 2, 3, 4, 0]],
    expected: 5,
    failureNote: "중복을 빼면 0~4, 5개예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [
      [...Array.from({ length: 50000 }, (_, i) => i * 2), ...Array.from({ length: 50000 }, (_, i) => 1049999 - i)],
    ],
    expected: 50000,
    failureNote:
      "5만 개짜리 연속 번호가 거꾸로 들어 있어요. 번호마다 이어지는 번호를 세면(시작점 확인 없이) 약 12억 번이라 시간 초과예요.",
  },
]);

export const hashLongestRun: Problem = {
  id: "c:hash-longest-run",
  slug: "hash-longest-run",
  source: "curated",
  topic: "hash",
  level: 4,
  title: "가장 긴 연속 번호표",
  summary: "set에 넣어 두고, 연속의 시작점에서만 이어지는 번호를 세요",
  statement: [
    "노디가 숲에서 번호표를 주웠어요. 번호표는 순서 없이 섞여 있고, 같은 번호를 여러 장 주웠을 수도 있어요.",
    "",
    "주운 번호로 만들 수 있는 **1씩 커지는 연속 번호**(예: 3, 4, 5, 6) 중 가장 긴 것의 길이를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`nums`: 주운 번호표의 번호들이에요.",
  outputFormat: "가장 긴 연속 번호의 길이",
  constraints: ["1 ≤ nums의 길이 ≤ 100,000", "−1,000,000,000 ≤ 번호 ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      { name: "nums", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "번호들" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 긴 연속 길이" },
  },
  starterCode: {
    python: ["def solution(nums):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(nums) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] nums) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'`x + 1`이 **있나?**'를 계속 물어봐요 → 번호를 **set**에 넣어 두는 해시 문제예요.",
        "",
        "정렬해도 풀 수 있지만, set을 쓰면 O(N)에 끝나요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 번호를 set에 넣어요. (중복은 저절로 사라져요)",
        "2. `x - 1`이 set에 **없는** 번호만 연속의 **시작점**이에요.",
        "3. 시작점에서만 `x + 1, x + 2, …`가 있는 동안 길이를 세요.",
        "",
        "시작점이 아닌 번호에서도 세기 시작하면 같은 구간을 여러 번 세서 느려져요. 시작점에서만 세면 번호마다 한 번씩만 보게 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "s = nums의 set",
        "best = 0",
        "for x in s:",
        "    if x - 1이 s에 없으면:        # 시작점",
        "        length = 1",
        "        while x + length가 s에 있으면: length += 1",
        "        best = max(best, length)",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["시작점을 고르는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for x in s:",
            "    if ______:",
            "        length = 1",
            "        while x + length in s:",
            "            length += 1",
            "        best = max(best, length)",
          ].join("\n"),
          javascript: [
            "for (const x of s) {",
            "  if (______) {",
            "    let length = 1;",
            "    while (s.has(x + length)) length++;",
            "    best = Math.max(best, length);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int x : s) {",
            "    if (______) {",
            "        int length = 1;",
            "        while (s.contains(x + length)) length++;",
            "        best = Math.max(best, length);",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["existence-check"],
  signalIds: ["sig-seen-before"],
  estimatedMinutes: 18,
  xp: 40,
};
