import type { Problem } from "@/types/content";

export const hashMagazineLetter: Problem = {
  id: "c:hash-magazine-letter",
  slug: "hash-magazine-letter",
  source: "curated",
  topic: "hash",
  level: 2,
  title: "잡지 글자로 편지 쓰기",
  summary: "필요한 글자 수와 가진 글자 수를 비교해요",
  statement: [
    "노디는 잡지에서 글자를 한 글자씩 오려 붙여 편지를 만들려고 해요. 잡지의 글자 하나는 **한 번만** 쓸 수 있어요.",
    "",
    "잡지에 있는 글자 `letters`로 편지 `message`를 만들 수 있으면 `true`, 없으면 `false`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`letters`: 잡지에 있는 글자들, `message`: 만들고 싶은 편지예요. 둘 다 영어 소문자로만 되어 있어요.",
  outputFormat: "편지를 만들 수 있는지 (참/거짓)",
  constraints: ["1 ≤ letters의 길이 ≤ 100,000", "1 ≤ message의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      { name: "letters", type: { python: "str", javascript: "string", java: "String" }, description: "잡지 글자" },
      { name: "message", type: { python: "str", javascript: "string", java: "String" }, description: "만들 편지" },
    ],
    returns: { type: { python: "bool", javascript: "boolean", java: "boolean" }, description: "만들 수 있는지" },
  },
  starterCode: {
    python: ["def solution(letters, message):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(letters, message) {", "  let answer = false;", "  return answer;", "}", ""].join(
      "\n",
    ),
    java: [
      "class Solution {",
      "    public boolean solution(String letters, String message) {",
      "        boolean answer = false;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["hellowood", "hello"],
      expected: true,
      explanation: "h, e, l 두 개, o가 모두 있어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: ["helo", "hello"],
      expected: false,
      explanation: "l이 두 번 필요한데 잡지에는 하나뿐이에요. 글자가 있는지가 아니라 개수를 비교해야 해요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["a", "a"],
      expected: true,
      failureNote: "딱 맞게 한 글자예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: ["abc", "d"],
      expected: false,
      failureNote: "잡지에 없는 글자예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["aab", "aaab"],
      expected: false,
      failureNote: "a가 세 번 필요하지만 두 개뿐이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: ["zyxwvutsrqponmlkjihgfedcba", "nodi"],
      expected: true,
      failureNote: "순서는 상관없어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: ["abcdefghijklmnopqrstuvwxyz".repeat(3846), "z".repeat(3846) + "a"],
      expected: true,
      failureNote: "잡지 약 10만 글자예요. 편지 글자마다 잡지에서 찾아 지우면(list.remove) 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: ["abcdefghijklmnopqrstuvwxyz".repeat(3846), "q".repeat(3847)],
      expected: false,
      failureNote: "q가 딱 하나 모자라요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["글자마다 '**몇 개 있고, 몇 개 필요한가**'를 비교해요 → **개수 세기**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 잡지 글자를 세서 `have[글자]`를 만들어요.",
        "2. 편지 글자를 하나씩 쓰면서 `have[글자]`를 1씩 줄여요.",
        "3. 줄이려는데 이미 0이면(없거나 다 썼으면) 만들 수 없어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "have = letters의 글자별 개수",
        "for ch in message:",
        "    if have[ch]가 0(또는 없음): return false",
        "    have[ch] -= 1",
        "return true",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["글자가 모자란지 확인하는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for ch in message:",
            "    if ______:",
            "        return False",
            "    have[ch] -= 1",
            "return True",
          ].join("\n"),
          javascript: [
            "for (const ch of message) {",
            "  if (______) return false;",
            "  have.set(ch, have.get(ch) - 1);",
            "}",
            "return true;",
          ].join("\n"),
          java: [
            "for (char ch : message.toCharArray()) {",
            "    if (______) return false;",
            "    have.put(ch, have.get(ch) - 1);",
            "}",
            "return true;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["frequency-count"],
  signalIds: ["sig-count-each"],
  estimatedMinutes: 12,
  xp: 20,
};
