import type { Problem } from "@/types/content";

export const hashSecretPattern: Problem = {
  id: "c:hash-secret-pattern",
  slug: "hash-secret-pattern",
  source: "curated",
  topic: "hash",
  level: 3,
  title: "암호 패턴 맞추기",
  summary: "글자와 단어가 서로 한 쌍씩만 짝지어지는지 두 dict로 확인해요",
  statement: [
    "비밀 편지는 패턴 `pattern`의 글자 하나가 단어 하나를 뜻해요. 편지의 단어 목록 `words`가 패턴을 따르는지 확인하려고 해요.",
    "",
    "패턴을 따른다는 것은 다음을 모두 지키는 거예요.",
    "",
    "- 글자 수와 단어 수가 같아요.",
    "- 같은 글자는 항상 **같은 단어**를 뜻해요.",
    "- 다른 글자는 항상 **다른 단어**를 뜻해요.",
    "",
    "따르면 `true`, 아니면 `false`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`pattern`: 영어 소문자로 된 패턴, `words`: 단어 리스트예요.",
  outputFormat: "패턴을 따르는지 (참/거짓)",
  constraints: ["1 ≤ pattern의 길이 ≤ 1,000", "1 ≤ words의 길이 ≤ 1,000", "단어는 영어 소문자로 된 1~10글자예요"],
  signature: {
    name: "solution",
    params: [
      { name: "pattern", type: { python: "str", javascript: "string", java: "String" }, description: "패턴" },
      {
        name: "words",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "편지의 단어들",
      },
    ],
    returns: { type: { python: "bool", javascript: "boolean", java: "boolean" }, description: "패턴을 따르는지" },
  },
  starterCode: {
    python: ["def solution(pattern, words):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(pattern, words) {", "  let answer = false;", "  return answer;", "}", ""].join(
      "\n",
    ),
    java: [
      "class Solution {",
      "    public boolean solution(String pattern, String[] words) {",
      "        boolean answer = false;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["abba", ["nodi", "mimi", "mimi", "nodi"]],
      expected: true,
      explanation: "a ↔ nodi, b ↔ mimi로 딱 맞아요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: ["abba", ["nodi", "mimi", "mimi", "mimi"]],
      expected: false,
      explanation: "a가 처음엔 nodi였는데 마지막엔 mimi예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: ["ab", ["moss", "moss"]],
      expected: false,
      failureNote:
        "다른 글자 a와 b가 같은 단어 moss를 뜻해요. 글자 → 단어만 확인하면 놓쳐요. 단어 → 글자도 확인하세요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: ["abc", ["x", "y"]],
      expected: false,
      failureNote: "글자 수와 단어 수가 달라요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: ["aaaa", ["leaf", "leaf", "leaf", "leaf"]],
      expected: true,
      failureNote: "모두 같은 글자, 같은 단어예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "edge",
      args: ["a", ["hello"]],
      expected: true,
      failureNote: "한 글자, 한 단어예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: ["abab", ["sun", "moon", "sun", "moon"]],
      expected: true,
      failureNote: "번갈아 나와도 짝이 맞아요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "tricky",
      args: ["abcb", ["x", "y", "z", "x"]],
      expected: false,
      failureNote: "b는 y였는데 마지막 b가 x예요. 게다가 x는 이미 a의 단어예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "글자와 단어를 **짝지어 기억**해 두고, 다시 나올 때 같은 짝인지 확인해요 → dict에 '**이미 정한 짝**'을 적어 두는 해시 문제예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 길이가 다르면 바로 false예요.",
        "2. dict 두 개를 써요: `글자 → 단어`, `단어 → 글자`.",
        "3. i번째 글자 c와 단어 w를 볼 때, 한쪽이라도 **이미 다른 짝**이 정해져 있으면 false예요.",
        "4. 끝까지 문제가 없으면 true예요.",
        "",
        "dict 하나만 쓰면 'ab' ↔ 'moss moss'처럼 서로 다른 글자가 같은 단어를 쓰는 경우를 놓쳐요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "if len(pattern) != len(words): return false",
        "toWord = {}, toChar = {}",
        "for c, w in zip(pattern, words):",
        "    if c in toWord and toWord[c] != w: return false",
        "    if w in toChar and toChar[w] != c: return false",
        "    toWord[c] = w; toChar[w] = c",
        "return true",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["단어 쪽에서 짝을 확인하는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for c, w in zip(pattern, words):",
            "    if c in to_word and to_word[c] != w:",
            "        return False",
            "    if ______:",
            "        return False",
            "    to_word[c] = w",
            "    to_char[w] = c",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < words.length; i++) {",
            "  const c = pattern[i], w = words[i];",
            "  if (toWord.has(c) && toWord.get(c) !== w) return false;",
            "  if (______) return false;",
            "  toWord.set(c, w);",
            "  toChar.set(w, c);",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < words.length; i++) {",
            "    char c = pattern.charAt(i);",
            "    String w = words[i];",
            "    if (toWord.containsKey(c) && !toWord.get(c).equals(w)) return false;",
            "    if (______) return false;",
            "    toWord.put(c, w);",
            "    toChar.put(w, c);",
            "}",
          ].join("\n"),
        },
        caption: "Java에서 문자열은 == 대신 equals로 비교해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["existence-check"],
  signalIds: ["sig-seen-before"],
  estimatedMinutes: 15,
  xp: 30,
};
