import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const hashSnackPair: Problem = {
  id: "c:hash-snack-pair",
  slug: "hash-snack-pair",
  source: "curated",
  topic: "hash",
  level: 3,
  title: "예산에 딱 맞는 간식 두 개",
  summary: "지나온 간식 가격을 기억해 두고 짝이 되는 가격을 바로 찾아요",
  statement: [
    "노디가 간식 가게에 줄지어 놓인 간식 중 **서로 다른 두 개**를 골라, 가격의 합이 예산 `budget`과 **정확히 같게** 사려고 해요.",
    "",
    "두 간식의 위치 `[i, j]` (i < j)를 반환해 주세요. 그런 쌍이 여러 개면 **j가 가장 작은** 쌍을, 그중에서도 **i가 가장 작은** 쌍을 골라요. 없으면 빈 리스트를 반환해요.",
  ].join("\n"),
  inputFormat: "`prices`: 앞에서부터 놓인 간식 가격, `budget`: 예산이에요.",
  outputFormat: "두 간식의 위치 [i, j], 없으면 []",
  constraints: ["1 ≤ prices의 길이 ≤ 100,000", "1 ≤ 가격 ≤ 1,000,000", "2 ≤ budget ≤ 2,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "prices",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "간식 가격들",
      },
      { name: "budget", type: { python: "int", javascript: "number", java: "int" }, description: "예산" },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "두 간식의 위치" },
  },
  starterCode: {
    python: ["def solution(prices, budget):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(prices, budget) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] prices, int budget) {",
      "        int[] answer = new int[0];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[3, 8, 5, 2, 6], 8],
      expected: [0, 2],
      explanation: "3 + 5 = 8이에요. 2 + 6도 8이지만 j가 더 커요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [[4, 4], 8],
      expected: [0, 1],
      explanation: "같은 가격의 서로 다른 간식 두 개예요. 짝을 확인한 뒤에 기록해야 자기 자신과 짝이 되지 않아요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[4], 8],
      expected: [],
      failureNote: "간식이 하나뿐이면 쌍이 없어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[4, 2], 8],
      expected: [],
      failureNote: "4 하나로는 8을 만들 수 없어요. 자기 자신과 짝이 되면 안 돼요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 2, 3, 3], 5],
      expected: [0, 2],
      failureNote: "j = 2에서 짝 2가 0번과 1번에 있어요. 먼저 나온 0번을 골라요: [0, 2].",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3], 100],
      expected: [],
      failureNote: "어떤 두 개를 골라도 100이 안 돼요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 7, 2, 6], 8],
      expected: [0, 1],
      failureNote: "1 + 7이 가장 먼저 완성돼요: [0, 1].",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [[...Array.from({ length: 99998 }, (_, i) => 2 * i + 2), 1, 1000000], 1000001],
      expected: [99998, 99999],
      failureNote: "간식 10만 개, 짝은 맨 끝에 있어요. 모든 쌍을 비교하면 약 50억 번이라 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'합이 **정확히 budget**인 두 개' → **짝 찾기** 해시 패턴이에요.",
        "",
        "지금 가격이 `x`면 필요한 짝은 `budget - x`로 딱 정해져 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. dict `seen`에 **가격 → 처음 나온 위치**를 적어 둬요.",
        "2. 앞에서부터 j를 옮기며, `budget - prices[j]`가 seen에 있으면 `[seen[짝], j]`가 답이에요. 처음 찾은 j가 가장 작은 j예요.",
        "3. 없으면 지금 가격을 seen에 적어요. 이미 있으면 **먼저 나온 위치를 그대로** 둬야 i가 가장 작아져요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "seen = {}",
        "for j, x in enumerate(prices):",
        "    need = budget - x",
        "    if need in seen: return [seen[need], j]",
        "    if x not in seen: seen[x] = j",
        "return []",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["짝을 확인하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for j, x in enumerate(prices):",
            "    need = ______",
            "    if need in seen:",
            "        return [seen[need], j]",
            "    if x not in seen:",
            "        seen[x] = j",
          ].join("\n"),
          javascript: [
            "for (let j = 0; j < prices.length; j++) {",
            "  const need = ______;",
            "  if (seen.has(need)) return [seen.get(need), j];",
            "  if (!seen.has(prices[j])) seen.set(prices[j], j);",
            "}",
          ].join("\n"),
          java: [
            "for (int j = 0; j < prices.length; j++) {",
            "    int need = ______;",
            "    if (seen.containsKey(need)) return new int[] {seen.get(need), j};",
            "    seen.putIfAbsent(prices[j], j);",
            "}",
          ].join("\n"),
        },
        caption: "Java의 putIfAbsent는 키가 없을 때만 넣어서 먼저 나온 위치를 지켜 줘요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["complement-lookup"],
  signalIds: ["sig-pair-target"],
  visualization: {
    presets: [
      problemPreset(
        "hash-snack-pair-ex1",
        "hash-two-sum",
        "짝 가격 물어보기",
        "가격마다 짝(budget - x)이 이미 지나온 간식 중에 있는지 seen에 물어봐요.",
        [[3, 8, 5, 2, 6], 8],
      ),
    ],
  },
  estimatedMinutes: 15,
  xp: 30,
};
