import type { Problem } from "@/types/content";

export const hashSnackLine: Problem = {
  id: "c:hash-snack-line",
  slug: "hash-snack-line",
  source: "curated",
  topic: "hash",
  level: 5,
  title: "겹치지 않는 간식 줄",
  summary: "간식마다 마지막으로 본 위치를 기억하며 구간의 왼쪽 끝을 옮겨요",
  statement: [
    "간식 가게 진열대에 간식이 한 줄로 놓여 있어요. 간식 종류는 영어 소문자 한 글자로 나타내요.",
    "",
    "노디는 **연속으로 놓인** 간식을 한꺼번에 사고 싶은데, 같은 종류가 두 번 들어가면 안 돼요. 살 수 있는 가장 긴 구간의 길이를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`shelf`: 진열대의 간식 종류를 차례로 적은 문자열이에요.",
  outputFormat: "같은 종류가 없는 가장 긴 연속 구간의 길이",
  constraints: ["1 ≤ shelf의 길이 ≤ 100,000", "영어 소문자로만 되어 있어요"],
  signature: {
    name: "solution",
    params: [{ name: "shelf", type: { python: "str", javascript: "string", java: "String" }, description: "진열대" }],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 긴 구간의 길이" },
  },
  starterCode: {
    python: ["def solution(shelf):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(shelf) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String shelf) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["abcabcbb"],
      expected: 3,
      explanation: "abc처럼 세 개가 가장 길어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: ["aaaa"],
      expected: 1,
      explanation: "모두 같은 간식이면 1개씩만 살 수 있어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: ["abba"],
      expected: 2,
      failureNote:
        "마지막 a를 볼 때 a의 예전 위치(0)는 이미 구간 밖이에요. 왼쪽 끝을 뒤로 되돌리면 안 돼요. 답은 2예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: ["z"],
      expected: 1,
      failureNote: "한 개뿐이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["dvdf"],
      expected: 3,
      failureNote: "두 번째 d를 만나면 첫 d 바로 뒤(v)부터 다시 시작해요. vdf로 3이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: ["abcdefghijklmnopqrstuvwxyz"],
      expected: 26,
      failureNote: "모두 다른 26종류라 전부 살 수 있어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: ["abcdefghijklmnopqrstuvwxyz".repeat(3846)],
      expected: 26,
      failureNote: "약 10만 개예요. 시작점마다 끝까지 다시 훑으면 느려요. 한 번 훑으며 왼쪽 끝을 옮기세요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => String.fromCharCode(97 + ((i * i + i) % 26))).join("")],
      expected: 7,
      failureNote: "10만 개, 같은 간식이 불규칙하게 다시 나와요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'구간 안에 같은 것이 **이미 있나?**'를 계속 확인해요 → 간식마다 **마지막으로 본 위치**를 dict에 적어 두는 해시 문제예요.",
        "",
        "구간의 왼쪽 끝과 오른쪽 끝을 한 방향으로만 옮기는 **슬라이딩 윈도우**와 함께 써요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `left`는 지금 구간의 왼쪽 끝, `last[간식]`은 그 간식을 마지막으로 본 위치예요.",
        "2. 오른쪽 끝 `right`를 한 칸씩 옮기며 간식 `c`를 봐요.",
        "3. `c`를 구간 안(`last[c] ≥ left`)에서 본 적 있으면, `left`를 `last[c] + 1`로 옮겨요.",
        "4. `last[c] = right`로 적고, 길이 `right − left + 1`로 답을 갱신해요.",
        "",
        "구간 밖에서 본 적 있는 건 무시해야 해요. 그래서 `left`는 **앞으로만** 움직여요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "last = {}, left = 0, best = 0",
        "for right, c in enumerate(shelf):",
        "    if c in last and last[c] >= left:",
        "        left = last[c] + 1",
        "    last[c] = right",
        "    best = max(best, right - left + 1)",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["왼쪽 끝을 옮길지 정하는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for right, c in enumerate(shelf):",
            "    if ______:",
            "        left = last[c] + 1",
            "    last[c] = right",
            "    best = max(best, right - left + 1)",
          ].join("\n"),
          javascript: [
            "for (let right = 0; right < shelf.length; right++) {",
            "  const c = shelf[right];",
            "  if (______) left = last.get(c) + 1;",
            "  last.set(c, right);",
            "  best = Math.max(best, right - left + 1);",
            "}",
          ].join("\n"),
          java: [
            "for (int right = 0; right < shelf.length(); right++) {",
            "    char c = shelf.charAt(right);",
            "    if (______) left = last.get(c) + 1;",
            "    last.put(c, right);",
            "    best = Math.max(best, right - left + 1);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["existence-check"],
  signalIds: ["sig-seen-before"],
  estimatedMinutes: 25,
  xp: 50,
};
