import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[1, 2, 3, -2, 2], 3],
    expected: 4,
    explanation: "[1, 2], [3], [2, 3, −2], [3, −2, 2] 네 구간이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [[0, 0, 0], 0],
    expected: 6,
    explanation: "0으로 된 구간은 길이 1이 3개, 길이 2가 2개, 길이 3이 1개라 6이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[5], 5],
    expected: 1,
    failureNote: "하루짜리 구간 하나예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [[5], 3],
    expected: 0,
    failureNote: "구간이 없어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [[1, -1, 1, -1], 0],
    expected: 4,
    failureNote: "음수가 있어서 구간을 늘릴수록 합이 커지지 않아요. 두 포인터로는 못 풀어요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [[3, 4, 7, 2, -3, 1, 4, 2], 7],
    expected: 4,
    failureNote: "누적 합이 같은 값으로 여러 번 돌아와요. 개수를 세어 둬야 모두 셀 수 있어요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 50000 }, () => 0), 0],
    expected: 1250025000,
    failureNote: "5만 일이 모두 0이면 구간이 약 12억 개예요. 구간을 하나씩 세면 시간 초과예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 50000 }, (_, i) => ((i * 37) % 21) - 10), 5],
    expected: 22681406,
    failureNote: "5만 일, 음수와 양수가 섞여 있어요.",
  },
]);

export const hashSubarraySum: Problem = {
  id: "c:hash-subarray-sum",
  slug: "hash-subarray-sum",
  source: "curated",
  topic: "hash",
  level: 5,
  title: "합이 K인 연속 구간",
  summary: "지금까지의 누적 합이 몇 번 나왔는지 세어 구간 개수를 구해요",
  statement: [
    "노디는 날마다 도토리를 모으거나(양수) 먹었어요(음수). 날마다의 변화량이 `nums`로 주어져요.",
    "",
    "**연속한 며칠** 동안의 변화량 합이 정확히 `k`인 구간의 수를 반환해 주세요. 시작일이나 끝나는 날이 다르면 다른 구간이에요.",
  ].join("\n"),
  inputFormat: "`nums`: 날마다의 도토리 변화량, `k`: 원하는 합이에요.",
  outputFormat: "합이 k인 연속 구간의 수",
  constraints: ["1 ≤ nums의 길이 ≤ 50,000", "−1,000 ≤ nums[i] ≤ 1,000", "−10,000,000 ≤ k ≤ 10,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "nums",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "날마다의 변화량",
      },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "원하는 합" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "구간의 수" },
  },
  starterCode: {
    python: ["def solution(nums, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(nums, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] nums, int k) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'연속 구간의 합이 **정확히 k**'이고 음수가 있어요 → **누적 합 + 해시**예요.",
        "",
        "구간 `(i, j]`의 합 = `prefix[j] − prefix[i]`예요. 이게 k가 되려면 앞쪽 누적 합이 `prefix[j] − k`여야 해요. 짝 찾기와 같은 모양이에요!",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. dict `seen`에 **누적 합 → 나온 횟수**를 세요. 아무것도 더하지 않은 누적 합 0이 **한 번** 나온 상태로 시작해요.",
        "2. 하루씩 더해 누적 합 `total`을 만들고, `seen[total − k]`를 답에 더해요.",
        "3. 그다음 `seen[total] += 1` 해요.",
        "",
        "0을 한 번 넣고 시작해야 첫날부터 시작하는 구간도 세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "seen = {0: 1}",
        "total = 0, answer = 0",
        "for x in nums:",
        "    total += x",
        "    answer += seen[total - k]   # 없으면 0",
        "    seen[total] += 1",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["구간 개수를 더하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "seen = {0: 1}",
            "for x in nums:",
            "    total += x",
            "    answer += ______",
            "    seen[total] = seen.get(total, 0) + 1",
          ].join("\n"),
          javascript: [
            "const seen = new Map([[0, 1]]);",
            "for (const x of nums) {",
            "  total += x;",
            "  answer += ______;",
            "  seen.set(total, (seen.get(total) ?? 0) + 1);",
            "}",
          ].join("\n"),
          java: [
            "Map<Integer, Integer> seen = new HashMap<>();",
            "seen.put(0, 1);",
            "for (int x : nums) {",
            "    total += x;",
            "    answer += ______;",
            "    seen.put(total, seen.getOrDefault(total, 0) + 1);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["prefix-sum-hash"],
  signalIds: ["sig-subarray-sum"],
  estimatedMinutes: 25,
  xp: 50,
};
