import type { editor } from "monaco-editor";

/** 디자인 토큰과 같은 색 (Monaco는 CSS 변수를 읽지 못해 hex로 정의). 모든 토큰 색은 배경 대비 4.5:1 이상 */
export const ALGO_LIGHT_THEME: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "3A3145" },
    { token: "comment", foreground: "7A6F86", fontStyle: "italic" },
    { token: "keyword", foreground: "7B3FC4", fontStyle: "bold" },
    { token: "string", foreground: "1F7A55" },
    { token: "number", foreground: "B04A1C" },
    { token: "type", foreground: "8A6200" },
    { token: "identifier.function", foreground: "1F5F99" },
    { token: "delimiter", foreground: "6A4FD1" },
    { token: "operator", foreground: "6A4FD1" },
  ],
  colors: {
    "editor.background": "#FFFFFF",
    "editor.foreground": "#3A3145",
    "editor.lineHighlightBackground": "#FBF4EA",
    "editor.lineHighlightBorder": "#FBF4EA",
    "editor.selectionBackground": "#E3D4FF",
    "editor.inactiveSelectionBackground": "#F1ECFF",
    "editorCursor.foreground": "#6A4FD1",
    "editorLineNumber.foreground": "#7A6F86",
    "editorLineNumber.activeForeground": "#6A4FD1",
    "editorIndentGuide.background1": "#EFE4D6",
    "editorIndentGuide.activeBackground1": "#C9B8FF",
    "editorBracketMatch.background": "#F1ECFF",
    "editorBracketMatch.border": "#A792F0",
    "editorWidget.background": "#FFFFFF",
    "editorWidget.border": "#EFE4D6",
    "editorSuggestWidget.selectedBackground": "#F1ECFF",
    "editorError.foreground": "#C03A3A",
    "scrollbarSlider.background": "#EFE4D699",
    "scrollbarSlider.hoverBackground": "#E3D4FF",
  },
};

export const ALGO_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "EEEAF7" },
    { token: "comment", foreground: "A39BB8", fontStyle: "italic" },
    { token: "keyword", foreground: "CBBBFF", fontStyle: "bold" },
    { token: "string", foreground: "8EE0B8" },
    { token: "number", foreground: "FFB89A" },
    { token: "type", foreground: "FFE5A3" },
    { token: "identifier.function", foreground: "9ED3FF" },
    { token: "delimiter", foreground: "D9CCFF" },
    { token: "operator", foreground: "D9CCFF" },
  ],
  colors: {
    "editor.background": "#26223A",
    "editor.foreground": "#EEEAF7",
    "editor.lineHighlightBackground": "#2F2A47",
    "editor.lineHighlightBorder": "#2F2A47",
    "editor.selectionBackground": "#4A3F7A",
    "editor.inactiveSelectionBackground": "#352C5C",
    "editorCursor.foreground": "#CBBBFF",
    "editorLineNumber.foreground": "#8F87A6",
    "editorLineNumber.activeForeground": "#CBBBFF",
    "editorIndentGuide.background1": "#3A3452",
    "editorIndentGuide.activeBackground1": "#8F78E6",
    "editorBracketMatch.background": "#352C5C",
    "editorBracketMatch.border": "#8F78E6",
    "editorWidget.background": "#2B2742",
    "editorWidget.border": "#3A3452",
    "editorSuggestWidget.selectedBackground": "#352C5C",
    "editorError.foreground": "#FF9E9E",
    "scrollbarSlider.background": "#3A345299",
    "scrollbarSlider.hoverBackground": "#4A3F7A",
  },
};
