import type { Problem } from "@/types/content";

export const stackBackspaceKeyboard: Problem = {
  id: "c:stack-backspace-keyboard",
  slug: "stack-backspace-keyboard",
  source: "curated",
  topic: "stack",
  level: 2,
  title: "지우개 키보드",
  summary: "'<'가 앞 글자를 지우는 키보드로 친 결과를 구해요",
  statement: [
    "노디의 오래된 키보드는 지우개 키가 `<` 모양으로 찍혀요. 키보드로 친 기록 `keys`에서 `<`는 글자가 아니라 **바로 앞에 남아 있는 글자 하나를 지우는** 동작이에요. 지울 글자가 없으면 아무 일도 없어요.",
    "",
    "모든 키를 순서대로 누른 뒤 화면에 남은 글자를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`keys`: 영어 소문자와 `<`로만 이루어진 문자열이에요.",
  outputFormat: '화면에 남은 문자열. 아무것도 없으면 빈 문자열 `""`이에요.',
  constraints: ["1 ≤ keys의 길이 ≤ 100,000", "keys는 영어 소문자와 '<'로만 이루어져 있어요."],
  signature: {
    name: "solution",
    params: [{ name: "keys", type: { python: "str", javascript: "string" }, description: "누른 키 기록" }],
    returns: { type: { python: "str", javascript: "string" }, description: "남은 글자" },
  },
  starterCode: {
    python: ["def solution(keys):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(keys) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["abc<d"],
      expected: "abd",
      explanation: 'c를 지우고 d를 쳐서 "abd"예요.',
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: ["<<a<b"],
      expected: "b",
      explanation: '지울 글자가 없을 때의 <는 무시돼요. 남는 건 "b"예요.',
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["ab<<<"],
      expected: "",
      failureNote: "모두 지우면 빈 문자열이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: ["hello<<<<<world"],
      expected: "world",
      failureNote: "hello를 모두 지우고 world만 남아요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["ab<c<<d"],
      expected: "d",
      failureNote: "b, c, a 순서로 지워져요. 지우는 건 항상 가장 최근 글자예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: ["nodi"],
      expected: "nodi",
      failureNote: "지우개를 한 번도 안 눌렀어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: ["x".repeat(50000) + "<".repeat(49999)],
      expected: "x",
      failureNote: "10만 번 눌러요. 문자열을 매번 잘라 새로 만들면 느려요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: ["ab<".repeat(33333)],
      expected: "a".repeat(33333),
      failureNote: "쓰고 지우기를 3만 번 넘게 반복해요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "지우개는 항상 **가장 최근에 남은 글자**를 지워요 → **스택**이에요.",
        "",
        '근거: "바로 앞에 남아 있는 글자 하나를 지워요" = 마지막에 넣은 것을 꺼내기(pop).',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 글자를 담을 리스트(스택)를 만들어요.",
        "2. 글자면 push, `<`면 비어 있지 않을 때 pop.",
        "3. 마지막에 리스트를 이어 붙여(join) 문자열로 만들어요.",
        "",
        "> 문자열 끝을 `s = s[:-1]`처럼 잘라 내면 매번 문자열 전체를 새로 만들어서 10만 글자에서는 느려요. 리스트에 모았다가 한 번에 합치세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "stack = []",
        "for 키 in keys:",
        "    if 키 == '<':  if stack: stack.pop()",
        "    else:  stack.push(키)",
        "return stack을 이어 붙인 문자열",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["지우개 처리와 마지막 합치기예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for key in keys:",
            '    if key == "<":',
            "        if stack:",
            "            ______",
            "    else:",
            "        stack.append(key)",
            'return "".join(stack)',
          ].join("\n"),
          javascript: [
            "for (const key of keys) {",
            '  if (key === "<") {',
            "    if (stack.length > 0) ______;",
            "  } else {",
            "    stack.push(key);",
            "  }",
            "}",
            'return stack.join("");',
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["undo-history", "stack-simulation"],
  signalIds: ["sig-latest-first"],
  estimatedMinutes: 10,
  xp: 20,
};
