import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const stackBracketPartner: Problem = {
  id: "c:stack-bracket-partner",
  slug: "stack-bracket-partner",
  source: "curated",
  topic: "stack",
  level: 3,
  title: "짝꿍 괄호 번호",
  summary: "괄호마다 짝이 되는 괄호가 몇 번째 글자인지 찾아요",
  statement: [
    "노디가 쓴 수식 `s`에는 괄호 `(`, `)`와 다른 글자가 섞여 있어요. 괄호는 **항상 올바르게 짝지어져** 있어요.",
    "",
    "수식을 고칠 때 괄호 하나를 지우면 짝꿍 괄호도 함께 지워야 해서, 괄호마다 짝꿍이 어디 있는지 미리 알아 두려고 해요.",
    "",
    "각 위치 i(0부터)마다 `s[i]`가 괄호라면 **짝꿍 괄호의 위치**를, 괄호가 아니라면 `-1`을 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`s`: 괄호가 올바르게 짝지어진 수식 문자열이에요.",
  outputFormat: "길이가 s와 같은 리스트. i번째 값은 s[i]의 짝꿍 위치 또는 -1",
  constraints: [
    "1 ≤ s의 길이 ≤ 100,000",
    "s는 `(`, `)`, 영어 소문자, 숫자, `+`, `-`, `*`로만 되어 있어요",
    "괄호는 항상 올바르게 짝지어져 있어요",
  ],
  signature: {
    name: "solution",
    params: [{ name: "s", type: { python: "str", javascript: "string", java: "String" }, description: "수식" }],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "int[]" },
      description: "위치마다 짝꿍 괄호의 위치 (괄호가 아니면 -1)",
    },
  },
  starterCode: {
    python: ["def solution(s):", "    answer = [-1] * len(s)", "    return answer", ""].join("\n"),
    javascript: [
      "function solution(s) {",
      "  let answer = new Array(s.length).fill(-1);",
      "  return answer;",
      "}",
      "",
    ].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(String s) {",
      "        int[] answer = new int[s.length()];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["(a+(b))"],
      expected: [6, -1, -1, 5, -1, 3, 0],
      explanation: "0번 (는 6번 )와, 3번 (는 5번 )와 짝이에요. 괄호가 아닌 a, +, b는 -1이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: ["()()"],
      expected: [1, 0, 3, 2],
      explanation: "나란히 있는 두 쌍이에요. 0↔1, 2↔3.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["x"],
      expected: [-1],
      failureNote: "괄호가 하나도 없어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: ["((()))"],
      expected: [5, 4, 3, 2, 1, 0],
      failureNote: "겹겹이 감싼 괄호예요. 바깥끼리, 안쪽끼리 짝이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["(()())"],
      expected: [5, 2, 1, 4, 3, 0],
      failureNote:
        "닫는 괄호는 가장 최근에 열린(아직 짝이 없는) 괄호와 짝이에요. 처음 나온 )가 첫 ( 와 짝인 게 아니에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: ["a(b)c(d(e)f)g"],
      expected: [-1, 3, -1, 1, -1, 11, -1, 9, -1, 7, -1, 5, -1],
      failureNote: "글자와 괄호가 섞여 있어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: ["(".repeat(50000) + ")".repeat(50000)],
      expected: Array.from({ length: 100000 }, (_, i) => 99999 - i),
      failureNote: "괄호 5만 쌍이 겹겹이 있어요. 괄호마다 짝을 앞뒤로 훑어 찾으면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "여는 괄호와 닫는 괄호의 **짝**을 찾아요 → **스택**이에요.",
        "",
        "닫는 괄호의 짝은 **가장 최근에 열렸고 아직 닫히지 않은** 여는 괄호예요. 스택 맨 위가 바로 그 괄호예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 이번에는 괄호 글자가 아니라 **위치**(인덱스)를 스택에 넣어요. 답이 위치니까요.",
        "2. `(`를 만나면 그 위치를 push해요.",
        "3. `)`를 만나면 pop한 위치 j가 짝꿍이에요. `answer[i] = j`, `answer[j] = i`로 양쪽 모두 적어요.",
        "4. 괄호가 아닌 글자는 처음 값 -1 그대로 둬요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "answer = [-1] * n, stack = []   # 여는 괄호의 위치",
        "for i in 0..n-1:",
        "    s[i]가 '(' → stack에 i push",
        "    s[i]가 ')' → j = stack.pop()",
        "                 answer[i] = j, answer[j] = i",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["닫는 괄호를 만났을 때 짝꿍을 찾는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i, ch in enumerate(s):",
            '    if ch == "(":',
            "        stack.append(i)",
            '    elif ch == ")":',
            "        j = ______",
            "        answer[i] = j",
            "        answer[j] = i",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < s.length; i++) {",
            '  if (s[i] === "(") {',
            "    stack.push(i);",
            '  } else if (s[i] === ")") {',
            "    const j = ______;",
            "    answer[i] = j;",
            "    answer[j] = i;",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < s.length(); i++) {",
            "    char ch = s.charAt(i);",
            "    if (ch == '(') {",
            "        stack.push(i);",
            "    } else if (ch == ')') {",
            "        int j = ______;",
            "        answer[i] = j;",
            "        answer[j] = i;",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "Java 배열은 0으로 시작하니 Arrays.fill(answer, -1)로 먼저 -1을 채워요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["bracket-matching"],
  signalIds: ["sig-bracket-pair"],
  visualization: {
    presets: [
      problemPreset(
        "bracket-partner-tricky",
        "stack-bracket",
        "겹친 괄호",
        "닫는 괄호는 스택 맨 위의 여는 괄호와 짝이 돼요.",
        ["(()())"],
      ),
    ],
  },
  estimatedMinutes: 15,
  xp: 30,
};
