import type { Problem } from "@/types/content";

export const stackFolderPath: Problem = {
  id: "c:stack-folder-path",
  slug: "stack-folder-path",
  source: "curated",
  topic: "stack",
  level: 2,
  title: "폴더 길 정리",
  summary: "'.'과 '..'이 섞인 폴더 길을 가장 짧게 정리해요",
  statement: [
    "노디의 컴퓨터에서는 폴더의 위치를 `/`로 구분한 **길**로 적어요. 예를 들어 `/home/nodi`는 맨 위 폴더에서 `home`, 그 안의 `nodi` 폴더예요.",
    "",
    "길을 이리저리 옮겨 적다 보니 불필요한 부분이 생겼어요. 길을 `/`로 나눈 조각마다 이렇게 움직여요.",
    "",
    "- `.`: 지금 폴더에 그대로 있어요.",
    "- `..`: 한 단계 위 폴더로 올라가요. 이미 맨 위라면 그대로 있어요.",
    "- 빈 조각(`//`처럼 `/`가 이어진 곳): 무시해요.",
    "- 그 밖의 이름: 그 이름의 폴더로 들어가요.",
    "",
    "도착한 폴더의 **정리된 길**을 반환해 주세요. 정리된 길은 `/`로 시작하고, 폴더 이름을 `/` 하나로 이어 쓰며, 끝에는 `/`를 붙이지 않아요. 맨 위 폴더라면 `/`예요.",
  ].join("\n"),
  inputFormat: "`path`: `/`로 시작하는 폴더 길이에요.",
  outputFormat: "정리된 길 문자열",
  constraints: ["1 ≤ path의 길이 ≤ 100,000", "path는 `/`로 시작해요", "폴더 이름은 영어 소문자와 숫자로만 되어 있어요"],
  signature: {
    name: "solution",
    params: [
      { name: "path", type: { python: "str", javascript: "string", java: "String" }, description: "정리할 폴더 길" },
    ],
    returns: { type: { python: "str", javascript: "string", java: "String" }, description: "정리된 길" },
  },
  starterCode: {
    python: ["def solution(path):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(path) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String solution(String path) {",
      '        String answer = "";',
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["/home/nodi/../docs/./photos/"],
      expected: "/home/docs/photos",
      explanation: "nodi로 들어갔다가 ..로 나와요. .은 그대로, 끝의 /는 빈 조각이라 무시해요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: ["/../.."],
      expected: "/",
      explanation: "맨 위에서 ..을 해도 맨 위 그대로예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["/"],
      expected: "/",
      failureNote: "맨 위 폴더 그대로예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: ["/a//b///c"],
      expected: "/a/b/c",
      failureNote: "/가 여러 개 이어져도 하나로 정리해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["/a/b/c/../../../../x"],
      expected: "/x",
      failureNote: "맨 위보다 더 올라가려는 ..은 무시하고, 그다음 x로 들어가요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: ["/game/./save/../save2/."],
      expected: "/game/save2",
      failureNote: "save에 들어갔다 나와서 save2로 들어가요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: ["/" + "a/".repeat(20000) + "../".repeat(19999)],
      expected: "/a",
      failureNote: "a 폴더로 2만 번 들어갔다가 19,999번 올라와요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "`..`은 **가장 최근에 들어간 폴더**에서 나오는 거예요 → **스택**이에요.",
        "",
        "폴더에 들어가면 push, `..`이면 pop. 스택에 남은 폴더들이 곧 정리된 길이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `path`를 `/`로 나눠 조각 목록을 만들어요.",
        "2. 빈 조각과 `.`은 건너뛰어요.",
        "3. `..`이면 스택이 **비어 있지 않을 때만** pop해요. 맨 위에서는 더 올라갈 곳이 없으니까요.",
        "4. 나머지 이름은 push해요.",
        "5. 끝나면 `/` + 스택의 폴더들을 `/`로 이은 문자열이 답이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "stack = []",
        "for 조각 in path를 '/'로 나눈 것:",
        "    조각이 '' 또는 '.' → 건너뛰기",
        "    조각이 '..'        → stack이 비어 있지 않으면 pop",
        "    그 밖              → stack에 push",
        "return '/' + (stack을 '/'로 이은 것)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["`..`을 만났을 때가 이 문제의 함정이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            'for part in path.split("/"):',
            '    if part == "" or part == ".":',
            "        continue",
            '    if part == "..":',
            "        if ______:",
            "            stack.pop()",
            "    else:",
            "        stack.append(part)",
          ].join("\n"),
          javascript: [
            'for (const part of path.split("/")) {',
            '  if (part === "" || part === ".") continue;',
            '  if (part === "..") {',
            "    if (______) stack.pop();",
            "  } else {",
            "    stack.push(part);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            'for (String part : path.split("/")) {',
            '    if (part.isEmpty() || part.equals(".")) continue;',
            '    if (part.equals("..")) {',
            "        if (______) stack.remove(stack.size() - 1);",
            "    } else {",
            "        stack.add(part);",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "마지막에 아래 폴더부터 이어 붙여야 해서 ArrayList의 끝을 스택의 맨 위로 써요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["undo-history", "stack-simulation"],
  signalIds: ["sig-latest-first"],
  estimatedMinutes: 12,
  xp: 20,
};
