import type { Problem } from "@/types/content";

export const stackLightestBox: Problem = {
  id: "c:stack-lightest-box",
  slug: "stack-lightest-box",
  source: "curated",
  topic: "stack",
  level: 4,
  title: "가장 가벼운 상자",
  summary: "상자를 쌓고 치우는 동안 가장 가벼운 무게를 바로바로 답해요",
  statement: [
    "노디가 창고에서 상자를 한 줄로 쌓고 있어요. 상자는 맨 위에만 올리고 맨 위에서만 치울 수 있어요.",
    "",
    '- `"push w"`: 무게가 w인 상자를 맨 위에 올려요.',
    '- `"pop"`: 맨 위 상자를 치워요. 상자가 없으면 아무 일도 없어요.',
    '- `"min"`: 지금 쌓여 있는 상자 중 **가장 가벼운 상자의 무게**를 기록해요. 상자가 없으면 `-1`을 기록해요.',
    "",
    '명령을 순서대로 실행하면서 `"min"` 때마다 기록한 값을 차례로 담은 리스트를 반환해 주세요.',
  ].join("\n"),
  inputFormat: '`commands`: `"push w"`, `"pop"`, `"min"` 문자열의 리스트예요.',
  outputFormat: "min 결과를 순서대로 담은 리스트",
  constraints: ["1 ≤ commands의 길이 ≤ 100,000", "1 ≤ w ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "commands",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "명령 목록",
      },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" }, description: "min 기록" },
  },
  starterCode: {
    python: ["def solution(commands):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(commands) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(String[] commands) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["push 5", "push 3", "min", "push 7", "min", "pop", "pop", "min"]],
      expected: [3, 3, 5],
      explanation: "7과 3을 치우고 나면 가장 가벼운 상자는 다시 5예요. 기록은 [3, 3, 5].",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [["min", "push 2", "pop", "min", "pop"]],
      expected: [-1, -1],
      explanation: "상자가 없을 때 min은 -1, pop은 아무 일도 없어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [["push 9", "push 1", "pop", "min"]],
      expected: [9],
      failureNote:
        "1을 치우면 가장 가벼운 무게가 9로 되돌아가야 해요. '지금까지의 최솟값' 변수 하나로는 되돌릴 수 없어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [["push 4", "push 4", "pop", "min"]],
      expected: [4],
      failureNote: "같은 무게 상자가 두 개일 때 하나를 치워도 4가 남아 있어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [["push 1", "push 2", "push 3", "min", "pop", "min", "pop", "min"]],
      expected: [1, 1, 1],
      failureNote: "가장 가벼운 1이 맨 아래에 있으면 위를 치워도 계속 1이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [["push 6", "min", "push 2", "min", "push 8", "min", "pop", "min", "pop", "min"]],
      expected: [6, 2, 2, 2, 6],
      failureNote: "올리고 치울 때마다 가장 가벼운 무게가 바뀌어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 100000 }, (_, i) => (i < 50000 ? "push " + (100000 - i) : i % 2 === 0 ? "min" : "pop")),
      ],
      expected: Array.from({ length: 25000 }, (_, k) => 50001 + k),
      failureNote: "상자 5만 개를 쌓고 min과 pop을 번갈아 해요. min마다 상자를 모두 훑으면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "맨 위에만 올리고 치우니 **스택**이에요. 여기에 `min`이 더해졌어요.",
        "",
        "상자를 치우면 가장 가벼운 무게가 **그 상자를 올리기 직전의 값**으로 되돌아가요. '되돌리기'가 보이면 되돌아갈 값도 스택에 쌓아 두는 방법을 떠올려 보세요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`min`마다 모든 상자를 훑으면 상자가 5만 개일 때 너무 느려요.",
        "",
        "1. 상자 스택 옆에 **최솟값 스택** `mins`를 하나 더 둬요. `mins`의 k번째 값은 '아래에서 k번째 상자까지 중 가장 가벼운 무게'예요.",
        "2. push w → `mins`에는 `min(w, mins의 맨 위)`를 push해요 (비어 있으면 w).",
        "3. pop → 두 스택에서 함께 pop해요. 그러면 최솟값이 저절로 직전 값으로 돌아가요.",
        "4. min → `mins`의 맨 위가 답이에요 (비어 있으면 -1). 모든 명령이 O(1)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "stack = [], mins = [], answer = []",
        "for 명령 in commands:",
        "    push w → stack에 w push",
        "             mins에 (mins가 비었으면 w, 아니면 min(w, mins의 맨 위)) push",
        "    pop    → stack이 비어 있지 않으면 stack과 mins에서 함께 pop",
        "    min    → answer에 (mins가 비었으면 -1, 아니면 mins의 맨 위) 추가",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["상자를 올릴 때 최솟값 스택에 무엇을 쌓을지가 핵심이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            'if parts[0] == "push":',
            "    w = int(parts[1])",
            "    stack.append(w)",
            "    mins.append(w if not mins else ______)",
          ].join("\n"),
          javascript: [
            'if (name === "push") {',
            "  const w = Number(value);",
            "  stack.push(w);",
            "  mins.push(mins.length === 0 ? w : ______);",
            "}",
          ].join("\n"),
          java: [
            'if (parts[0].equals("push")) {',
            "    int w = Integer.parseInt(parts[1]);",
            "    stack.push(w);",
            "    mins.push(mins.isEmpty() ? w : ______);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["undo-history", "stack-simulation"],
  signalIds: ["sig-latest-first"],
  estimatedMinutes: 20,
  xp: 40,
};
