import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [["<red>", "<blue>", "</blue>", "</red>"]],
    expected: true,
    explanation: "blue를 먼저 매듭짓고 red를 매듭지어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [["<red>", "<blue>", "</red>", "</blue>"]],
    expected: false,
    explanation: "blue가 감긴 채로 red를 매듭지을 수 없어요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [["</gold>"]],
    expected: false,
    failureNote: "감지도 않은 리본은 매듭지을 수 없어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [["<gold>"]],
    expected: false,
    failureNote: "매듭짓지 않은 리본이 남았어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [["<a>", "<a>", "</a>", "</a>"]],
    expected: true,
    failureNote: "같은 이름 리본을 겹쳐 감아도 괜찮아요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [["<a>", "</a>", "<b>", "<c>", "</c>", "</b>"]],
    expected: true,
    failureNote: "나란히, 그리고 겹쳐서 감았어요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "tricky",
    args: [["<ab>", "</a>"]],
    expected: false,
    failureNote: "이름이 정확히 같아야 해요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [
      [
        ...Array.from({ length: 20000 }, (_, i) => `<t${i % 7}>`),
        ...Array.from({ length: 20000 }, (_, i) => `</t${(19999 - i) % 7}>`),
      ],
    ],
    expected: true,
    failureNote: "리본을 2만 겹으로 감았어요.",
  },
]);

export const stackRibbonTags: Problem = {
  id: "c:stack-ribbon-tags",
  slug: "stack-ribbon-tags",
  source: "curated",
  topic: "stack",
  level: 3,
  title: "리본 태그 검사기",
  summary: "여는 태그와 닫는 태그가 올바르게 짝지어졌는지 확인해요",
  statement: [
    '노디의 선물 가게는 상자를 리본으로 감쌀 때 태그를 붙여요. `"<이름>"`은 이름 리본을 **감기 시작**, `"</이름>"`은 그 리본을 **매듭짓기**예요.',
    "",
    "태그 기록 `tags`가 올바르려면 나중에 감기 시작한 리본을 먼저 매듭지어야 하고, 매듭은 같은 이름의 리본에만 지을 수 있으며, 마지막에 매듭짓지 않은 리본이 없어야 해요.",
    "",
    "태그 기록이 올바르면 `True`, 아니면 `False`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: '`tags`: `"<이름>"` 또는 `"</이름>"` 형태의 문자열 리스트예요. 이름은 영어 소문자예요.',
  outputFormat: "올바른 기록인지 여부 (bool)",
  constraints: ["1 ≤ tags의 길이 ≤ 50,000", "1 ≤ 이름의 길이 ≤ 10"],
  signature: {
    name: "solution",
    params: [
      {
        name: "tags",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "태그 기록",
      },
    ],
    returns: { type: { python: "bool", javascript: "boolean", java: "boolean" }, description: "올바른지 여부" },
  },
  starterCode: {
    python: ["def solution(tags):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(tags) {", "  let answer = false;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public boolean solution(String[] tags) {",
      "        boolean answer = false;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "괄호 짝 맞추기의 변형이에요 → **스택**.",
        "",
        '"나중에 감기 시작한 리본을 먼저 매듭지어요" = 가장 최근 것을 먼저 닫기(LIFO).',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 여는 태그면 **이름만** 떼어 스택에 넣어요.",
        "2. 닫는 태그면 스택이 비었거나 맨 위 이름이 다르면 실패, 같으면 pop.",
        "3. 끝에 스택이 비어 있으면 성공.",
        "",
        "여는 태그인지는 두 번째 글자가 `/`인지로 구분할 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for tag in tags:",
        "    이름 = 괄호와 / 를 뺀 부분",
        "    if 닫는 태그:",
        "        if stack이 비었거나 stack.pop() != 이름: return False",
        "    else: stack.push(이름)",
        "return stack이 비어 있는가",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["태그에서 이름을 떼어 내는 부분과 닫는 태그 검사예요."].join("\n"),
      code: {
        code: {
          python: [
            "for tag in tags:",
            '    closing = tag[1] == "/"',
            "    name = tag[2:-1] if closing else tag[1:-1]",
            "    if closing:",
            "        if ______:",
            "            return False",
            "    else:",
            "        stack.append(name)",
          ].join("\n"),
          javascript: [
            "for (const tag of tags) {",
            '  const closing = tag[1] === "/";',
            "  const name = closing ? tag.slice(2, -1) : tag.slice(1, -1);",
            "  if (closing) {",
            "    if (______) return false;",
            "  } else {",
            "    stack.push(name);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (String tag : tags) {",
            "    boolean closing = tag.charAt(1) == '/';",
            "    String name = closing ? tag.substring(2, tag.length() - 1) : tag.substring(1, tag.length() - 1);",
            "    if (closing) {",
            "        if (______) return false;",
            "    } else {",
            "        stack.push(name);",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "문자열 비교는 ==가 아니라 equals로 해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["bracket-matching"],
  signalIds: ["sig-bracket-pair"],
  estimatedMinutes: 15,
  xp: 30,
};
