import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[2, 2, 4]],
    expected: [8],
    explanation: "2와 2가 합쳐져 4, 그 뒤에 온 4와 또 합쳐져 [8]이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [[1, 2, 1, 1]],
    expected: [1, 4],
    explanation: "마지막 1이 1과 합쳐져 2가 되고, 그 2가 앞의 2와 또 합쳐져 [1, 4]예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[7]],
    expected: [7],
    failureNote: "눈덩이가 하나뿐이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [[3, 5, 3, 5]],
    expected: [3, 5, 3, 5],
    failureNote: "같은 크기가 떨어져 있으면 합쳐지지 않아요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [[4, 2, 1, 1]],
    expected: [8],
    failureNote: "1+1=2 → 2+2=4 → 4+4=8, 연쇄가 끝까지 이어져요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [[1, 1, 1]],
    expected: [2, 1],
    failureNote: "앞의 두 개가 합쳐진 2와 새 1은 크기가 달라요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "basic",
    args: [[5, 5, 5, 5, 10]],
    expected: [20, 10],
    failureNote: "5+5=10, 5+5=10, 10+10=20, 20과 10은 달라요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [Array(65536).fill(1)],
    expected: [65536],
    failureNote: "크기 1인 눈덩이 65,536개가 모두 하나로 합쳐져요.",
  },
  {
    id: "hid-7",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => (i % 2) + 1)],
    expected: Array.from({ length: 100000 }, (_, i) => (i % 2) + 1),
    failureNote: "합쳐지는 일 없이 10만 개가 쌓여요.",
  },
]);

export const stackSnowballMerge: Problem = {
  id: "c:stack-snowball-merge",
  slug: "stack-snowball-merge",
  source: "curated",
  topic: "stack",
  level: 4,
  title: "눈덩이 합치기",
  summary: "같은 크기 눈덩이가 만나면 합쳐지는 과정을 끝까지 따라가요",
  statement: [
    "노디가 언덕 위에서 눈덩이를 하나씩 굴려 보내면, 눈덩이는 언덕 아래 벽 쪽으로 굴러가 한 줄로 쌓여요. 새 눈덩이는 줄의 **맨 끝**(가장 최근에 멈춘 눈덩이 바로 뒤)에 멈춰요.",
    "",
    "새 눈덩이가 멈췄을 때 바로 앞 눈덩이와 **크기가 같으면** 둘이 합쳐져 크기가 두 배인 눈덩이 하나가 돼요. 합쳐진 눈덩이도 그 앞 눈덩이와 크기가 같으면 또 합쳐져요.",
    "",
    "굴려 보낸 눈덩이 크기 `sizes`가 순서대로 주어질 때, 모두 멈춘 뒤 벽 쪽부터 눈덩이 크기를 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`sizes`: 굴린 순서대로의 눈덩이 크기 리스트예요.",
  outputFormat: "벽 쪽부터 순서대로의 최종 눈덩이 크기 리스트",
  constraints: ["1 ≤ sizes의 길이 ≤ 100,000", "1 ≤ 각 크기 ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "sizes",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "굴린 눈덩이 크기",
      },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "최종 눈덩이 크기",
    },
  },
  starterCode: {
    python: ["def solution(sizes):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(sizes) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(int[] sizes) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "새 눈덩이는 **가장 최근에 멈춘 눈덩이**와만 비교돼요 → **스택 시뮬레이션**이에요.",
        "",
        "합쳐진 뒤 '그 앞'과 다시 비교하는 연쇄는, 맨 위를 꺼내면 그 아래가 새 맨 위가 되는 스택의 성질과 딱 맞아요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "새 눈덩이 크기를 `ball`이라고 할 때,",
        "1. 스택 맨 위가 ball과 같은 **동안** 계속: 맨 위를 pop하고 ball을 두 배로.",
        "2. 더 이상 같지 않으면 ball을 push.",
        "",
        "if가 아니라 **while**이어야 연쇄 합치기가 처리돼요. 각 눈덩이는 한 번 들어가고 최대 한 번 나오므로 전체 O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for ball in sizes:",
        "    while stack이 비어 있지 않고 stack의 맨 위 == ball:",
        "        stack.pop()",
        "        ball = ball * 2",
        "    stack.push(ball)",
        "return stack",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["연쇄 합치기 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for ball in sizes:",
            "    while stack and stack[-1] == ball:",
            "        stack.pop()",
            "        ball = ______",
            "    stack.append(ball)",
          ].join("\n"),
          javascript: [
            "for (let ball of sizes) {",
            "  while (stack.length > 0 && stack[stack.length - 1] === ball) {",
            "    stack.pop();",
            "    ball = ______;",
            "  }",
            "  stack.push(ball);",
            "}",
          ].join("\n"),
          java: [
            "for (int size : sizes) {",
            "    int ball = size;",
            "    while (!stack.isEmpty() && stack.peek() == ball) {",
            "        stack.pop();",
            "        ball = ______;",
            "    }",
            "    stack.push(ball);",
            "}",
          ].join("\n"),
        },
        caption:
          "Deque<Integer>에서 꺼낸 값은 Integer예요. int와 ==로 비교하면 자동으로 풀려서 괜찮지만, Integer끼리는 equals를 써요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["stack-simulation"],
  signalIds: ["sig-latest-first"],
  estimatedMinutes: 20,
  xp: 40,
};
