import type { Problem } from "@/types/content";

export const stackTallerNeighbor: Problem = {
  id: "c:stack-taller-neighbor",
  slug: "stack-taller-neighbor",
  source: "curated",
  topic: "stack",
  level: 5,
  title: "왼쪽의 더 큰 해바라기",
  summary: "각 해바라기 왼쪽에서 가장 가까운, 자기보다 키가 큰 해바라기를 찾아요",
  statement: [
    "노디의 정원에 해바라기 N송이가 왼쪽부터 한 줄로 서 있어요. 해바라기는 왼쪽부터 1번, 2번, … 번호가 붙어 있고, `heights[i]`는 (i+1)번 해바라기의 키예요.",
    "",
    "각 해바라기가 왼쪽을 바라볼 때, **자기보다 키가 큰 해바라기 중 가장 가까운 것**의 번호를 알고 싶어요. 그런 해바라기가 없으면 0이에요. 키가 같은 해바라기는 '큰' 것이 아니에요.",
    "",
    "해바라기마다 찾은 번호를 순서대로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`heights`: 왼쪽부터 순서대로의 해바라기 키 리스트예요.",
  outputFormat: "i번째 값이 (i+1)번 해바라기의 답(1부터 시작하는 번호, 없으면 0)인 리스트",
  constraints: ["1 ≤ heights의 길이 ≤ 100,000", "1 ≤ 각 키 ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [{ name: "heights", type: { python: "list[int]", javascript: "number[]" }, description: "해바라기 키" }],
    returns: { type: { python: "list[int]", javascript: "number[]" }, description: "왼쪽의 더 큰 해바라기 번호" },
  },
  starterCode: {
    python: ["def solution(heights):", "    answer = [0] * len(heights)", "    return answer", ""].join("\n"),
    javascript: [
      "function solution(heights) {",
      "  let answer = new Array(heights.length).fill(0);",
      "  return answer;",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[6, 9, 5, 7, 4]],
      expected: [0, 0, 2, 2, 4],
      explanation: "3번(5)의 왼쪽 가장 가까운 큰 것은 2번(9), 4번(7)도 2번(9), 5번(4)은 4번(7)이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[3, 3, 3]],
      expected: [0, 0, 0],
      explanation: "키가 같은 해바라기는 크지 않아요. 모두 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[10]],
      expected: [0],
      failureNote: "한 송이뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[5, 4, 3, 2, 1]],
      expected: [0, 1, 2, 3, 4],
      failureNote: "점점 작아지면 바로 왼쪽이 답이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[8, 2, 3, 4, 1, 9, 5]],
      expected: [0, 1, 1, 1, 4, 0, 6],
      failureNote: "4번(4)은 2·3번을 건너뛰어 1번(8)을 찾아요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 5, 5, 3, 5]],
      expected: [0, 0, 0, 3, 0],
      failureNote: "5번(5)은 같은 키 5들을 건너뛰어야 하는데, 더 큰 것이 없어서 0이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => i + 1)],
      expected: Array(100000).fill(0),
      failureNote: "점점 커지는 10만 송이. 해바라기마다 왼쪽을 끝까지 훑으면 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i % 2 === 0 ? 1000000000 - i : 1))],
      expected: Array.from({ length: 100000 }, (_, i) => (i === 0 ? 0 : i % 2 === 1 ? i : i - 1)),
      failureNote: "큰 해바라기와 작은 해바라기가 번갈아 서 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"가장 가까운, 나보다 큰 값" → **모노토닉 스택**이에요.',
        "",
        "왼쪽부터 보면서, 앞으로도 '큰 해바라기' 후보가 될 수 있는 것들만 스택에 남겨요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "지금 해바라기보다 **작거나 같은** 해바라기는, 지금 해바라기에 가려서 이후 누구의 답도 될 수 없어요. 그러니 스택에서 빼 버려요.",
        "",
        "1. 스택 맨 위의 키가 지금 키 이하인 동안 pop.",
        "2. 스택이 비어 있으면 답 0, 아니면 맨 위의 번호가 답.",
        "3. 지금 해바라기를 push.",
        "",
        "스택에는 번호를 넣고, 키는 heights에서 찾아봐요. 전체 O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for i in 0..n-1:",
        "    while stack이 비어 있지 않고 heights[stack의 맨 위] <= heights[i]:",
        "        stack.pop()",
        "    answer[i] = (stack이 비었으면 0, 아니면 stack의 맨 위 + 1)",
        "    stack.push(i)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["가려지는 해바라기를 빼는 조건과 답을 정하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for i, h in enumerate(heights):",
            "    while stack and ______:",
            "        stack.pop()",
            "    answer[i] = stack[-1] + 1 if stack else 0",
            "    stack.append(i)",
          ].join("\n"),
          javascript: [
            "heights.forEach((h, i) => {",
            "  while (stack.length > 0 && ______) stack.pop();",
            "  answer[i] = stack.length > 0 ? stack[stack.length - 1] + 1 : 0;",
            "  stack.push(i);",
            "});",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["monotonic-stack"],
  signalIds: ["sig-next-greater"],
  estimatedMinutes: 25,
  xp: 50,
};
