import type { Problem } from "@/types/content";

export const stackTwinBalloons: Problem = {
  id: "c:stack-twin-balloons",
  slug: "stack-twin-balloons",
  source: "curated",
  topic: "stack",
  level: 2,
  title: "쌍둥이 풍선 터뜨리기",
  summary: "나란히 붙은 같은 글자를 계속 없애고 남는 글자를 구해요",
  statement: [
    "풍선 가게에 글자가 적힌 풍선들이 한 줄로 매달려 있어요. **같은 글자 풍선 두 개가 바로 옆에 붙으면** 둘 다 펑 하고 터져요. 풍선이 터지면 양옆 풍선이 서로 붙게 되고, 그 둘도 같은 글자라면 또 터져요.",
    "",
    "더 이상 터질 풍선이 없을 때까지 반복한 뒤, 남은 풍선의 글자를 순서대로 이어 붙인 문자열을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`balloons`: 영어 소문자로 이루어진 문자열이에요.",
  outputFormat: "남은 풍선 글자를 이은 문자열. 모두 터지면 빈 문자열이에요.",
  constraints: ["1 ≤ balloons의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      { name: "balloons", type: { python: "str", javascript: "string", java: "String" }, description: "풍선 글자" },
    ],
    returns: { type: { python: "str", javascript: "string", java: "String" }, description: "남은 풍선" },
  },
  starterCode: {
    python: ["def solution(balloons):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(balloons) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String solution(String balloons) {",
      '        String answer = "";',
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["abbaca"],
      expected: "ca",
      explanation: 'bb가 터지면 aa가 붙어서 또 터지고, "ca"가 남아요.',
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: ["aabbcc"],
      expected: "",
      explanation: "모두 터지면 빈 문자열이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["z"],
      expected: "z",
      failureNote: "풍선이 하나뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: ["abcddcbe"],
      expected: "ae",
      failureNote: '가운데부터 연쇄로 터져서 "ae"가 남아요.',
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: ["abab"],
      expected: "abab",
      failureNote: "붙어 있는 같은 글자가 없어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: ["aaa"],
      expected: "a",
      failureNote: "앞의 두 개만 터지고 하나가 남아요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: ["ab".repeat(25000) + "ba".repeat(25000)],
      expected: "",
      failureNote: "가운데서부터 5만 쌍이 연쇄로 터져요. 반복해서 문자열을 다시 훑으면 느려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "새 풍선은 **바로 앞에 남아 있는 풍선**과만 비교하면 돼요 → **스택**이에요.",
        "",
        "터진 뒤 양옆이 붙는 연쇄도, 스택에서는 '맨 위를 꺼내고 나면 그 아래가 새 맨 위'가 되는 것으로 자연스럽게 처리돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "왼쪽부터 풍선을 하나씩 스택에 올린다고 생각해요.",
        "- 스택 맨 위 글자가 지금 풍선과 같으면 → 둘 다 터지므로 맨 위를 pop하고, 지금 풍선도 올리지 않아요.",
        "- 다르면 → push.",
        "",
        "한 번 훑으면 끝나서 O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "stack = []",
        "for c in balloons:",
        "    if stack이 비어 있지 않고 stack의 맨 위 == c:",
        "        stack.pop()",
        "    else:",
        "        stack.push(c)",
        "return stack을 이은 문자열",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["비교 조건을 완성해 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for c in balloons:",
            "    if stack and ______:",
            "        stack.pop()",
            "    else:",
            "        stack.append(c)",
          ].join("\n"),
          javascript: [
            "for (const c of balloons) {",
            "  if (stack.length > 0 && ______) stack.pop();",
            "  else stack.push(c);",
            "}",
          ].join("\n"),
          java: [
            "for (char c : balloons.toCharArray()) {",
            "    if (stack.length() > 0 && ______) stack.deleteCharAt(stack.length() - 1);",
            "    else stack.append(c);",
            "}",
          ].join("\n"),
        },
        caption: "StringBuilder의 끝을 스택의 꼭대기로 써요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["stack-simulation"],
  signalIds: ["sig-latest-first"],
  estimatedMinutes: 12,
  xp: 20,
};
