import type { Problem } from "@/types/content";

export const stackUndoMemo: Problem = {
  id: "c:stack-undo-memo",
  slug: "stack-undo-memo",
  source: "curated",
  topic: "stack",
  level: 4,
  title: "되돌리기 메모장",
  summary: "쓰기·지우기·되돌리기 명령을 실행한 뒤 남은 글을 구해요",
  statement: [
    "노디가 만든 메모장에는 세 가지 명령이 있어요.",
    "",
    '- `"type s"`: 글 끝에 문자열 s를 이어 써요.',
    '- `"delete k"`: 글 끝에서 k글자를 지워요. 글이 k글자보다 짧으면 전부 지워요.',
    '- `"undo"`: 아직 되돌리지 않은 `type`·`delete` 중 **가장 최근 것**을 되돌려 그 명령 전 상태로 만들어요. 되돌릴 명령이 없으면 아무 일도 없어요. undo 자체는 되돌릴 수 없어요.',
    "",
    "처음 메모장은 비어 있어요. 명령 `commands`를 모두 실행한 뒤 남은 글을 반환해 주세요.",
  ].join("\n"),
  inputFormat: '`commands`: `"type s"`, `"delete k"`, `"undo"` 문자열의 리스트예요. s는 영어 소문자예요.',
  outputFormat: "마지막에 남은 글 (문자열)",
  constraints: ["1 ≤ commands의 길이 ≤ 2,000", "1 ≤ s의 길이 ≤ 10", "1 ≤ k ≤ 100"],
  signature: {
    name: "solution",
    params: [{ name: "commands", type: { python: "list[str]", javascript: "string[]" }, description: "명령 목록" }],
    returns: { type: { python: "str", javascript: "string" }, description: "남은 글" },
  },
  starterCode: {
    python: ["def solution(commands):", '    answer = ""', "    return answer", ""].join("\n"),
    javascript: ["function solution(commands) {", '  let answer = "";', "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["type abc", "type de", "undo", "type x"]],
      expected: "abcx",
      explanation: '"abcde"에서 마지막 type을 되돌려 "abc", 그 뒤에 x를 써요.',
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [["type hello", "delete 2", "undo", "undo", "undo"]],
      expected: "",
      explanation: 'delete를 되돌리면 "hello", type을 되돌리면 "". 세 번째 undo는 되돌릴 게 없어요.',
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["type ab", "delete 9"]],
      expected: "",
      failureNote: "글보다 많이 지우면 전부 지워져요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [["type ab", "delete 9", "undo"]],
      expected: "ab",
      failureNote: "전부 지운 것도 원래대로 되돌릴 수 있어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [["undo", "undo", "type a"]],
      expected: "a",
      failureNote: "처음부터 undo를 눌러도 아무 일도 없어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [["type nod", "type i", "delete 1", "type y", "undo", "undo"]],
      expected: "nodi",
      failureNote: "되돌리기가 연달아 일어나요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "tricky",
      args: [["type ab", "undo", "type cd", "undo", "undo"]],
      expected: "",
      failureNote: "이미 되돌린 명령은 다시 되돌리지 않아요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 2000 }, (_, i) => ["type ab", "type cde", "delete 2", "undo"][i % 4])],
      // prettier-ignore
      expected: "abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde",
      failureNote: "명령이 2,000개예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"가장 최근 것을 되돌려요" → **되돌리기 기록 = 스택**이에요.',
        "",
        "실행 취소(Ctrl+Z)는 스택의 대표적인 쓰임이에요. 명령을 실행할 때마다 **실행 전 상태**를 스택에 쌓고, undo 때 맨 위를 꺼내면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 현재 글 `text`와 기록 스택 `history`를 둬요.",
        "2. type·delete를 실행하기 **전에** 지금 text를 history에 push해요.",
        "3. undo면 history가 비어 있지 않을 때 pop한 값으로 text를 바꿔요.",
        "",
        "undo는 기록하지 않아요. 그래야 'undo 자체는 되돌릴 수 없다'는 규칙을 지켜요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        'text = "", history = []',
        "for 명령 in commands:",
        "    type s   → history.push(text); text = text + s",
        "    delete k → history.push(text); text = text의 끝 k글자를 뺀 것",
        "    undo     → if history: text = history.pop()",
        "return text",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["delete와 undo 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            'elif name == "delete":',
            "    history.append(text)",
            "    text = text[: max(0, len(text) - int(arg))]",
            'elif name == "undo" and history:',
            "    text = ______",
          ].join("\n"),
          javascript: [
            '} else if (name === "delete") {',
            "  history.push(text);",
            "  text = text.slice(0, Math.max(0, text.length - Number(arg)));",
            '} else if (name === "undo" && history.length > 0) {',
            "  text = ______;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["undo-history"],
  signalIds: ["sig-latest-first"],
  estimatedMinutes: 20,
  xp: 40,
};
