import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const stackVaultBrackets: Problem = {
  id: "c:stack-vault-brackets",
  slug: "stack-vault-brackets",
  source: "curated",
  topic: "stack",
  level: 3,
  title: "금고 괄호 암호",
  summary: "세 종류 괄호로 된 암호가 올바르게 짝지어졌는지 판별해요",
  statement: [
    "노디네 마을 금고는 괄호로 된 암호로 열려요. 암호는 `()`, `[]`, `{}` 세 종류 괄호로만 이루어져 있고, 다음 조건을 모두 지켜야 **올바른 암호**예요.",
    "",
    "- 여는 괄호는 같은 종류의 닫는 괄호로 닫혀야 해요.",
    "- 나중에 연 괄호가 먼저 닫혀야 해요. 예를 들어 `([)]`는 올바르지 않아요.",
    "- 모든 괄호가 짝을 가져야 해요.",
    "",
    "암호 `code`가 올바르면 `True`(JavaScript는 `true`), 아니면 `False`(`false`)를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`code`: `( ) [ ] { }`로만 이루어진 문자열이에요.",
  outputFormat: "올바른 암호인지 여부 (bool)",
  constraints: ["1 ≤ code의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [{ name: "code", type: { python: "str", javascript: "string" }, description: "괄호 암호" }],
    returns: { type: { python: "bool", javascript: "boolean" }, description: "올바른지 여부" },
  },
  starterCode: {
    python: ["def solution(code):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(code) {", "  let answer = false;", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["([]){}"],
      expected: true,
      explanation: "모든 괄호가 순서대로 짝을 이뤄요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: ["([)]"],
      expected: false,
      explanation: "개수는 맞지만 ] 앞에서 가장 최근에 연 괄호가 ( 라서 틀려요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["("],
      expected: false,
      failureNote: "닫히지 않은 괄호가 남으면 틀려요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [")("],
      expected: false,
      failureNote: "닫는 괄호가 먼저 나오면 짝이 없어요. 빈 스택을 꺼내지 않게 조심해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: ["{[()()]}"],
      expected: true,
      failureNote: "여러 겹으로 잘 감싸져 있어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: ["((]]"],
      expected: false,
      failureNote: "종류가 다른 괄호로 닫았어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "edge",
      args: ["]"],
      expected: false,
      failureNote: "닫는 괄호 하나뿐이에요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: ["([{".repeat(20000) + "}])".repeat(20000)],
      expected: true,
      failureNote: "6만 겹으로 감싼 긴 암호예요.",
    },
    {
      id: "hid-7",
      visibility: "hidden",
      purpose: "stress",
      args: ["([{".repeat(20000) + "}])".repeat(19999) + "})]"],
      expected: false,
      failureNote: "긴 암호의 맨 끝만 순서가 엇갈렸어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "**괄호 짝 맞추기** → **스택**이에요.",
        "",
        "닫는 괄호는 항상 **가장 최근에 연(아직 안 닫힌)** 괄호와 짝이어야 해요. 가장 최근 것을 먼저 꺼내는 구조가 스택이죠.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 여는 괄호를 만나면 스택에 쌓아요.",
        "2. 닫는 괄호를 만나면 스택 맨 위를 꺼내 **같은 종류인지** 확인해요. 스택이 비어 있으면 곧바로 실패예요.",
        "3. 끝까지 봤을 때 스택이 **비어 있어야** 성공이에요.",
        "",
        "닫는 괄호 → 여는 괄호 짝을 딕셔너리(객체)로 만들어 두면 비교가 쉬워요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "pair = { ')': '(', ']': '[', '}': '{' }",
        "for c in code:",
        "    if c가 여는 괄호: stack.push(c)",
        "    else:",
        "        if stack이 비었거나 stack.pop() != pair[c]: return False",
        "return stack이 비어 있는가",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["닫는 괄호를 만났을 때의 검사예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            'pair = {")": "(", "]": "[", "}": "{"}',
            "for c in code:",
            '    if c in "([{":',
            "        stack.append(c)",
            "    elif not stack or ______:",
            "        return False",
          ].join("\n"),
          javascript: [
            'const pair = { ")": "(", "]": "[", "}": "{" };',
            "for (const c of code) {",
            '  if ("([{".includes(c)) stack.push(c);',
            "  else if (stack.length === 0 || ______) return false;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["bracket-matching"],
  signalIds: ["sig-bracket-pair"],
  visualization: {
    presets: [
      problemPreset("vault-ok", "stack-bracket", "예제 1: 올바른 암호", "여는 괄호가 쌓였다가 짝을 만나면 빠져요.", [
        "([]){}",
      ]),
      problemPreset("vault-bad", "stack-bracket", "예제 2: 엇갈린 암호", "] 를 만났을 때 맨 위가 ( 라서 실패해요.", [
        "([)]",
      ]),
    ],
  },
  estimatedMinutes: 15,
  xp: 30,
};
