import type { Problem } from "@/types/content";

export const stackWarmerWait: Problem = {
  id: "c:stack-warmer-wait",
  slug: "stack-warmer-wait",
  source: "curated",
  topic: "stack",
  level: 5,
  title: "온실이 따뜻해질 때까지",
  summary: "날마다 더 따뜻한 날이 오기까지 며칠 기다려야 하는지 구해요",
  statement: [
    "노디의 온실에는 매일 정오에 온도를 재는 센서가 있어요. 센서 기록 `temps`에서 `temps[i]`는 i번째 날의 온도예요.",
    "",
    "각 날마다, **그날보다 온도가 높은 날이 처음으로 오기까지 며칠을 기다려야 하는지** 구하려고 해요. 이후에 더 따뜻한 날이 없으면 0이에요.",
    "",
    "날마다 기다리는 날 수를 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`temps`: 날짜 순서대로의 온도(정수) 리스트예요.",
  outputFormat: "i번째 값이 i번째 날의 기다리는 날 수인 리스트",
  constraints: ["1 ≤ temps의 길이 ≤ 100,000", "0 ≤ 각 온도 ≤ 1,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "temps",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "날짜별 온도",
      },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "int[]" },
      description: "날마다 기다리는 날 수",
    },
  },
  starterCode: {
    python: ["def solution(temps):", "    answer = [0] * len(temps)", "    return answer", ""].join("\n"),
    javascript: [
      "function solution(temps) {",
      "  let answer = new Array(temps.length).fill(0);",
      "  return answer;",
      "}",
      "",
    ].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] temps) {",
      "        int[] answer = new int[temps.length];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[23, 24, 21, 19, 22, 26, 25]],
      expected: [1, 4, 2, 1, 1, 0, 0],
      explanation:
        "첫날(23)은 다음 날 24가 더 따뜻해서 1. 둘째 날(24)은 나흘 뒤 26이 올 때까지 기다려서 4예요. 26 이후로는 더 따뜻한 날이 없어서 0이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[30, 30, 29]],
      expected: [0, 0, 0],
      explanation: "같은 온도는 '더 따뜻한' 날이 아니에요. 모두 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[15]],
      expected: [0],
      failureNote: "하루뿐이면 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3, 4, 5]],
      expected: [1, 1, 1, 1, 0],
      failureNote: "매일 따뜻해져요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[5, 1, 1, 1, 6]],
      expected: [4, 3, 2, 1, 0],
      failureNote: "첫날은 나흘을 기다려요. 가운데 1들은 모두 마지막 날을 기다려요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [[3, 5, 3, 5, 3, 6]],
      expected: [1, 4, 1, 2, 1, 0],
      failureNote: "같은 온도가 번갈아 나와요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i === 99999 ? 1000000 : 100000 - i))],
      expected: Array.from({ length: 100000 }, (_, i) => 99999 - i),
      failureNote: "점점 추워지다 마지막 날에만 따뜻해져요. 날마다 뒤를 끝까지 훑으면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"처음으로 나보다 큰 값이 나오는 곳" → **모노토닉 스택**이에요.',
        "",
        "아직 답(더 따뜻한 날)을 못 찾은 날들을 스택에 쌓아 두고 기다려요. 따뜻한 날이 오면 그날보다 추웠던 날들의 답이 한꺼번에 정해져요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 스택에는 **날짜 번호**(인덱스)를 넣어요. 답(기다린 날 수)을 계산하려면 날짜가 필요하니까요.",
        "2. 오늘 온도가 스택 맨 위 날의 온도보다 **높은 동안**: 맨 위 날을 pop하고 그 날의 답 = 오늘 − 그 날.",
        "3. 그다음 오늘을 push해요.",
        "",
        "스택에 남아 있는 날들은 온도가 **내려가는 순서**로 쌓여 있어요(그래서 모노토닉). 각 날은 한 번 들어가고 한 번 나와서 O(N)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "answer = [0] * n, stack = []   # 날짜 번호",
        "for today in 0..n-1:",
        "    while stack이 비어 있지 않고 temps[stack의 맨 위] < temps[today]:",
        "        day = stack.pop()",
        "        answer[day] = today - day",
        "    stack.push(today)",
        "return answer",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["답이 정해지는 순간이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for today, temp in enumerate(temps):",
            "    while stack and ______ < temp:",
            "        day = stack.pop()",
            "        answer[day] = today - day",
            "    stack.append(today)",
          ].join("\n"),
          javascript: [
            "temps.forEach((temp, today) => {",
            "  while (stack.length > 0 && ______ < temp) {",
            "    const day = stack.pop();",
            "    answer[day] = today - day;",
            "  }",
            "  stack.push(today);",
            "});",
          ].join("\n"),
          java: [
            "for (int today = 0; today < temps.length; today++) {",
            "    while (!stack.isEmpty() && ______ < temps[today]) {",
            "        int day = stack.pop();",
            "        answer[day] = today - day;",
            "    }",
            "    stack.push(today);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["monotonic-stack"],
  signalIds: ["sig-next-greater"],
  estimatedMinutes: 25,
  xp: 50,
};
