import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[2, 4, 4, 3, 1, 5]],
    expected: 9,
    explanation: "가운데 세 건물(4, 4, 3)에 높이 3으로 걸면 3 × 3 = 9예요. 높이 4로 두 칸(8)보다 넓어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[3, 3, 3]],
    expected: 9,
    explanation: "모두 높이가 같으면 전체에 걸 수 있어요. 3 × 3 = 9.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[0]],
    expected: 0,
    failureNote: "높이 0인 건물에는 현수막을 붙일 수 없어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [[1, 2, 3, 4, 5]],
    expected: 9,
    failureNote: "점점 높아져요. 높이 3으로 세 칸(9)이 가장 넓어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [[5, 4, 3, 2, 1]],
    expected: 9,
    failureNote: "점점 낮아져요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [[2, 0, 2]],
    expected: 2,
    failureNote: "높이 0인 건물이 가운데를 끊어요. 양쪽을 이어 걸 수 없어요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "tricky",
    args: [[4, 2, 0, 3, 2, 5]],
    expected: 6,
    failureNote: "0으로 나뉜 오른쪽에서 높이 2로 세 칸이 가장 넓어요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, () => 10000)],
    expected: 1000000000,
    failureNote: "모두 높이 10,000인 건물 10만 개예요. 넓이는 10억이에요.",
  },
  {
    id: "hid-7",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => Math.floor(i / 10) + 1)],
    expected: 250050000,
    failureNote: "계단처럼 조금씩 높아지는 건물 10만 개예요. 시작 건물마다 오른쪽으로 넓혀 보면 시간 초과예요.",
  },
]);

export const stackWidestBanner: Problem = {
  id: "c:stack-widest-banner",
  slug: "stack-widest-banner",
  source: "curated",
  topic: "stack",
  level: 5,
  title: "가장 넓은 현수막",
  summary: "높이가 다른 건물 벽에 붙일 수 있는 가장 넓은 직사각형 현수막을 구해요",
  statement: [
    "축제 거리에 폭이 1인 건물들이 빈틈없이 한 줄로 서 있어요. `heights[i]`는 i번째 건물의 높이예요.",
    "",
    "노디는 건물 벽에 **직사각형 현수막** 하나를 붙이려고 해요.",
    "",
    "- 현수막은 이웃한 여러 건물에 걸쳐 붙일 수 있어요.",
    "- 현수막의 아랫변은 땅에 닿아야 해요.",
    "- 현수막이 건물 위로 튀어나오면 안 돼요. 그래서 현수막 높이는 걸친 건물 중 **가장 낮은 건물의 높이 이하**예요.",
    "",
    "붙일 수 있는 현수막의 **가장 큰 넓이**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`heights`: 왼쪽부터 건물 높이를 담은 정수 리스트예요.",
  outputFormat: "가장 넓은 현수막의 넓이 (정수)",
  constraints: ["1 ≤ heights의 길이 ≤ 100,000", "0 ≤ 각 높이 ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "heights",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "건물 높이",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 넓은 현수막의 넓이" },
  },
  starterCode: {
    python: ["def solution(heights):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(heights) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] heights) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "건물마다 '이 건물 높이로 현수막을 걸면 **왼쪽·오른쪽으로 어디까지** 넓힐 수 있을까?'를 알면 돼요.",
        "",
        "오른쪽 끝은 **처음으로 나보다 낮은 건물**이 나오는 곳이에요. '처음으로 나보다 작은 값' → **모노토닉 스택**이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 스택에는 건물 **위치**를 넣고, 높이가 **낮은 것부터 높은 순서**로 쌓이게 유지해요.",
        "2. 새 건물 i가 스택 맨 위 건물보다 낮거나 같으면, 맨 위 건물 top은 **i에서 막혀요**. pop해서 top의 높이로 현수막을 계산해요.",
        "3. top을 뺀 뒤의 스택 맨 위가 top의 **왼쪽 끝 바로 앞**이에요 (그 건물은 top보다 낮으니까요). 스택이 비었다면 맨 왼쪽까지 넓힐 수 있어요.",
        "4. 넓이 = top의 높이 × (i − 왼쪽 끝). 끝에 높이 0인 건물을 하나 붙이면 남은 건물들도 모두 계산돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "h = heights + [0]   # 끝에 높이 0을 붙여 남은 건물을 모두 꺼낸다",
        "stack = [], best = 0",
        "for i in 0..len(h)-1:",
        "    while stack이 비어 있지 않고 h[stack의 맨 위] >= h[i]:",
        "        top = stack.pop()",
        "        left = (stack이 비었으면 0, 아니면 stack의 맨 위 + 1)",
        "        best = max(best, h[top] × (i - left))",
        "    stack.push(i)",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["막힌 건물을 꺼내 넓이를 계산하는 부분이에요. 왼쪽 끝을 구하는 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(len(h)):",
            "    while stack and h[stack[-1]] >= h[i]:",
            "        top = stack.pop()",
            "        left = ______",
            "        best = max(best, h[top] * (i - left))",
            "    stack.append(i)",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < h.length; i++) {",
            "  while (stack.length > 0 && h[stack[stack.length - 1]] >= h[i]) {",
            "    const top = stack.pop();",
            "    const left = ______;",
            "    best = Math.max(best, h[top] * (i - left));",
            "  }",
            "  stack.push(i);",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i <= n; i++) {",
            "    int h = i == n ? 0 : heights[i];   // 끝에 높이 0",
            "    while (!stack.isEmpty() && heights[stack.peek()] >= h) {",
            "        int top = stack.pop();",
            "        int left = ______;",
            "        best = Math.max(best, heights[top] * (i - left));",
            "    }",
            "    stack.push(i);",
            "}",
          ].join("\n"),
        },
        caption: "Java는 배열 끝에 값을 붙이기 번거로워서, i == n일 때 높이를 0으로 봐요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["monotonic-stack"],
  signalIds: ["sig-next-greater"],
  estimatedMinutes: 30,
  xp: 50,
};
