import type { Problem } from "@/types/content";

export const greedyFewestJumps: Problem = {
  id: "c:greedy-fewest-jumps",
  slug: "greedy-fewest-jumps",
  source: "curated",
  topic: "greedy",
  level: 4,
  title: "가장 적게 뛰어 건너기",
  summary: "지금 한 번에 닿는 범위 안에서 다음 범위를 가장 멀리 늘려요",
  statement: [
    "징검돌 i번에서는 앞으로 **최대** `jumps[i]`칸까지 뛸 수 있어요. 0번 돌에서 출발해 **마지막 돌**까지 가는 **최소 점프 횟수**를 반환해 주세요.",
    "",
    "마지막 돌까지는 항상 갈 수 있어요.",
  ].join("\n"),
  inputFormat: "`jumps`: 돌마다 뛸 수 있는 최대 칸 수예요.",
  outputFormat: "최소 점프 횟수",
  constraints: ["1 ≤ jumps의 길이 ≤ 100,000", "1 ≤ jumps[i] ≤ 1,000 (마지막 돌 제외)"],
  signature: {
    name: "solution",
    params: [
      {
        name: "jumps",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "최대 뛸 수 있는 칸",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 점프 횟수" },
  },
  starterCode: {
    python: ["def solution(jumps):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(jumps) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] jumps) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[2, 3, 1, 1, 4]],
      expected: 2,
      explanation: "0 → 1 → 4로 2번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[7]],
      expected: 0,
      explanation: "이미 마지막 돌이라 0번이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 1, 1, 1]],
      expected: 3,
      failureNote: "한 칸씩 3번이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 1, 5, 1, 1, 1, 1]],
      expected: 2,
      failureNote:
        "처음에 멀리(2번 돌) 뛰는 게 좋아요. 0 → 2 → 6으로 2번이에요. 매번 가장 멀리 뛰는 게 아니라, 다음에 가장 멀리 갈 수 있는 돌을 골라야 해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[5, 1, 1, 1, 1, 1]],
      expected: 1,
      failureNote: "한 번에 5칸 뛰어 1번이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => 1 + ((i * 7919) % 5))],
      expected: 20001,
      failureNote: "돌 10만 개예요. 돌마다 모든 이전 돌을 확인하는 DP는 느려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**최소 횟수**지만 BFS까지 갈 필요 없이, 'k번 점프로 닿는 범위'를 한 번에 넓혀 가는 **그리디**예요."].join(
        "\n",
      ),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `end` = 지금 점프 횟수로 닿는 가장 먼 돌, `far` = 한 번 더 뛰면 닿는 가장 먼 돌",
        "2. i를 훑으며 `far = max(far, i + jumps[i])`",
        "3. i가 `end`에 도착하면 이번 범위를 다 봤으니 한 번 더 뛰어요: `jumps += 1`, `end = far`",
        "",
        "마지막 돌에 닿으면 멈춰요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count = 0, end = 0, far = 0",
        "for i in 0..n-2:",
        "    far = max(far, i + jumps[i])",
        "    if i == end: count += 1; end = far",
        "return count",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["범위 끝에 닿았을 때의 처리예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(len(jumps) - 1):",
            "    far = max(far, i + jumps[i])",
            "    if i == end:",
            "        count += 1",
            "        end = ______",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < jumps.length - 1; i++) {",
            "  far = Math.max(far, i + jumps[i]);",
            "  if (i === end) {",
            "    count++;",
            "    end = ______;",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < jumps.length - 1; i++) {",
            "    far = Math.max(far, i + jumps[i]);",
            "    if (i == end) {",
            "        count++;",
            "        end = ______;",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["greedy-accumulate"],
  signalIds: ["sig-running-reach"],
  estimatedMinutes: 20,
  xp: 40,
};
