import type { Problem } from "@/types/content";

export const greedyFuelLoop: Problem = {
  id: "c:greedy-fuel-loop",
  slug: "greedy-fuel-loop",
  source: "curated",
  topic: "greedy",
  level: 4,
  title: "주유소 한 바퀴",
  summary: "연료가 모자라는 순간 그다음 주유소부터 다시 시작해요",
  statement: [
    "원형 도로에 주유소 N개가 있어요. i번 주유소에서는 연료 `gas[i]`를 넣을 수 있고, i번에서 다음 주유소(마지막 다음은 0번)까지 가는 데 연료 `cost[i]`가 들어요.",
    "",
    "빈 연료통으로 어느 주유소에서 출발해 **한 바퀴를 돌아** 출발점으로 돌아올 수 있으면 그 **출발 주유소 번호**를, 없으면 `-1`을 반환해 주세요. 가능한 출발점은 있다면 딱 하나예요.",
  ].join("\n"),
  inputFormat: "`gas`: 주유소별 넣을 수 있는 연료, `cost`: 다음 주유소까지 드는 연료예요.",
  outputFormat: "출발 주유소 번호 (없으면 -1)",
  constraints: ["1 ≤ N ≤ 100,000", "0 ≤ gas[i], cost[i] ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "gas",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "넣을 수 있는 연료",
      },
      {
        name: "cost",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "다음까지 드는 연료",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "출발 번호" },
  },
  starterCode: {
    python: ["def solution(gas, cost):", "    answer = -1", "    return answer", ""].join("\n"),
    javascript: ["function solution(gas, cost) {", "  let answer = -1;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] gas, int[] cost) {",
      "        int answer = -1;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        [1, 2, 3, 4, 5],
        [3, 4, 5, 1, 2],
      ],
      expected: 3,
      explanation: "3번에서 출발하면 연료가 한 번도 모자라지 않아요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [
        [2, 3, 4],
        [3, 4, 3],
      ],
      expected: -1,
      explanation: "연료 합(9)이 필요한 연료 합(10)보다 적어서 -1이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5], [4]],
      expected: 0,
      failureNote: "주유소 하나면 0번이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        [3, 1, 1],
        [1, 2, 2],
      ],
      expected: 0,
      failureNote: "0번에서 출발하면 3 → 2 → 1 → 0으로 딱 돌아와요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        [0, 0, 5],
        [1, 1, 3],
      ],
      expected: 2,
      failureNote: "2번에서 출발해야 해요. 모자라는 곳 다음부터 다시 시작하면 한 번 훑어서 찾아요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 100) + 1 + (i === 77777 ? 1 : 0)),
        Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 100) + 1 + (i === 77776 ? 1 : 0)),
      ],
      expected: 77777,
      failureNote: "주유소 10만 개예요. 출발점마다 한 바퀴씩 돌아 보면 100억 번이라 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["'**모자라면 다시 시작**' → 한 번 훑으며 연료 합을 들고 가는 **그리디**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 전체 `gas` 합이 전체 `cost` 합보다 작으면 어디서 출발해도 못 돌아요 → -1",
        "2. 아니면 0번부터 훑으며 `tank += gas[i] - cost[i]`",
        "3. `tank`가 음수가 되면, 지금까지의 어느 곳에서 출발해도 여기서 막혀요. **다음 주유소**를 새 출발점으로 하고 `tank = 0`",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "if sum(gas) < sum(cost): return -1",
        "start, tank = 0, 0",
        "for i in 0..n-1:",
        "    tank += gas[i] - cost[i]",
        "    if tank < 0: start = i + 1; tank = 0",
        "return start",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["모자랄 때 다시 시작하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(len(gas)):",
            "    tank += gas[i] - cost[i]",
            "    if tank < 0:",
            "        start = ______",
            "        tank = 0",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < gas.length; i++) {",
            "  tank += gas[i] - cost[i];",
            "  if (tank < 0) {",
            "    start = ______;",
            "    tank = 0;",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < gas.length; i++) {",
            "    tank += gas[i] - cost[i];",
            "    if (tank < 0) {",
            "        start = ______;",
            "        tank = 0;",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["greedy-accumulate"],
  signalIds: ["sig-running-reach"],
  estimatedMinutes: 20,
  xp: 40,
};
