import type { Problem } from "@/types/content";

export const greedySnackBudget: Problem = {
  id: "c:greedy-snack-budget",
  slug: "greedy-snack-budget",
  source: "curated",
  topic: "greedy",
  level: 1,
  title: "용돈으로 간식 최대한 많이",
  summary: "싼 간식부터 담으면 가장 많이 살 수 있어요",
  statement: [
    "노디가 용돈 `budget`으로 간식 가게에서 간식을 사요. 간식마다 가격 `prices[i]`가 붙어 있고, 같은 간식은 하나씩만 살 수 있어요.",
    "",
    "살 수 있는 간식의 **최대 개수**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`prices`: 간식 가격, `budget`: 용돈이에요.",
  outputFormat: "살 수 있는 간식의 최대 개수",
  constraints: ["1 ≤ prices의 길이 ≤ 100,000", "1 ≤ 가격 ≤ 10,000", "0 ≤ budget ≤ 1,000,000,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "prices",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "간식 가격",
      },
      { name: "budget", type: { python: "int", javascript: "number", java: "int" }, description: "용돈" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 개수" },
  },
  starterCode: {
    python: ["def solution(prices, budget):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(prices, budget) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] prices, int budget) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[5, 1, 3, 7, 2], 10],
      expected: 3,
      explanation: "1 + 2 + 3 = 6, 여기에 5를 더하면 11이라 3개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[4, 5], 3],
      expected: 0,
      explanation: "가장 싼 간식도 못 사서 0개예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[2, 2, 2], 6],
      expected: 3,
      failureNote: "딱 맞게 모두 살 수 있어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[9], 0],
      expected: 0,
      failureNote: "용돈이 0이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[8, 1, 1, 1, 1], 9],
      expected: 4,
      failureNote: "비싼 8을 먼저 사면 1개 더 사서 2개지만, 싼 것부터면 1 × 4 = 4개예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 10000) + 1), 123456789],
      expected: 49685,
      failureNote: "간식 10만 개예요. 매번 가장 싼 간식을 처음부터 찾으면(O(N²)) 시간 초과예요. 한 번 정렬하세요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["개수를 **최대**로 → 가격은 상관없이 한 개는 한 개예요. **싼 것부터** 사는 그리디예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 가격을 오름차순으로 정렬해요.",
        "2. 앞에서부터 용돈이 허락하는 동안 사요.",
        "",
        "비싼 간식 하나 대신 싼 간식을 사면 남는 돈이 더 많아서 절대 손해가 아니에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count = 0",
        "for p in prices를 싼 순서로:",
        "    if p > budget: break",
        "    budget -= p; count += 1",
        "return count",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["멈출 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for p in sorted(prices):",
            "    if ______:",
            "        break",
            "    budget -= p",
            "    count += 1",
          ].join("\n"),
          javascript: [
            "for (const p of [...prices].sort((a, b) => a - b)) {",
            "  if (______) break;",
            "  budget -= p;",
            "  count++;",
            "}",
          ].join("\n"),
          java: [
            "int[] sorted = prices.clone();",
            "Arrays.sort(sorted);",
            "for (int p : sorted) {",
            "    if (______) break;",
            "    budget -= p;",
            "    count++;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["greedy-by-sort"],
  signalIds: ["sig-greedy-local-best"],
  estimatedMinutes: 8,
  xp: 10,
};
