import type { PatternTag, TopicSlug } from "@/types";

/** 화면에 보여 줄 패턴 이름 */
export const PATTERN_LABELS: Record<PatternTag, string> = {
  "bracket-matching": "괄호 짝 맞추기",
  "stack-simulation": "스택 시뮬레이션",
  "monotonic-stack": "단조 스택",
  "undo-history": "되돌리기 기록",
  "queue-simulation": "큐 시뮬레이션",
  "round-robin": "차례로 돌아가기",
  "sliding-window-deque": "덱 슬라이딩 윈도우",
  "two-ended-deque": "양쪽 끝 덱",
  "recursive-definition": "재귀적 정의",
  "divide-and-conquer": "분할 정복",
  "recursion-tree": "재귀 트리",
  "adjacency-list": "인접 리스트",
  "adjacency-matrix": "인접 행렬",
  "edge-list-conversion": "간선 목록 변환",
  "degree-count": "차수 세기",
  "connected-components": "연결 요소",
  "grid-flood-fill": "격자 칠하기",
  "path-existence": "경로 존재",
  "cycle-detection": "사이클 찾기",
  "tree-traversal": "트리 순회",
  "shortest-path-unweighted": "최단 거리",
  "grid-shortest-path": "격자 최단 거리",
  "multi-source-bfs": "여러 시작점 BFS",
  "state-space-bfs": "상태 공간 BFS",
  "level-order": "층별 탐색",
  permutation: "순열",
  combination: "조합",
  subset: "부분집합",
  "constraint-pruning": "가지치기",
  "existence-check": "있는지 바로 확인",
  "frequency-count": "개수 세기",
  "complement-lookup": "짝 찾기",
  "group-by-key": "같은 것끼리 묶기",
  "prefix-sum-hash": "누적 합 + 해시",
  "sort-then-scan": "정렬 후 훑기",
  "custom-order": "정렬 기준 정하기",
  "merge-step": "정렬된 것 합치기",
  "counting-sort": "계수 정렬",
  "interval-sweep": "구간 정렬",
  "exact-search": "정확히 찾기",
  "boundary-search": "경계 찾기",
  "range-count": "범위 안 개수",
  "parametric-search": "답을 이분 탐색",
  "linear-dp": "1차원 DP",
  "grid-dp": "격자 DP",
  knapsack: "배낭 · 동전",
  "sequence-dp": "문자열 · 수열 DP",
  "state-dp": "상태를 나눈 DP",
  "greedy-by-sort": "정렬하고 욕심껏",
  "interval-scheduling": "구간 고르기",
  "greedy-accumulate": "누적하며 욕심껏",
  "digit-greedy": "앞자리부터 크게",
  "opposite-ends": "양 끝에서 좁히기",
  "same-direction": "같은 방향 두 포인터",
  "fixed-window": "고정 길이 창",
  "variable-window": "늘였다 줄이는 창",
  "top-k": "상위 K개",
  "repeated-min": "가장 작은 것 계속 꺼내기",
  "k-way-merge": "여러 줄 합치기",
  "two-heaps": "힙 두 개",
  "heap-scheduling": "힙으로 순서 정하기",
  "weighted-shortest-path": "비용이 다른 최단 경로",
  "path-restore": "경로 되짚기",
  "reverse-or-multi-source": "거꾸로 · 여러 곳에서 출발",
  "state-dijkstra": "상태를 더한 다익스트라",
  "minimax-path": "가장 험한 구간 최소화",
};

/** 토픽별 대표 패턴 (AI 문제 생성의 집중 패턴 후보) */
export const TOPIC_PATTERNS: Record<TopicSlug, PatternTag[]> = {
  stack: ["bracket-matching", "stack-simulation", "monotonic-stack", "undo-history"],
  "queue-deque": ["queue-simulation", "round-robin", "sliding-window-deque", "two-ended-deque"],
  recursion: ["recursive-definition", "divide-and-conquer", "recursion-tree"],
  "graph-representation": ["adjacency-list", "adjacency-matrix", "edge-list-conversion", "degree-count"],
  dfs: ["connected-components", "grid-flood-fill", "path-existence", "cycle-detection", "tree-traversal"],
  bfs: ["shortest-path-unweighted", "grid-shortest-path", "multi-source-bfs", "state-space-bfs", "level-order"],
  backtracking: ["permutation", "combination", "subset", "constraint-pruning"],
  hash: ["existence-check", "frequency-count", "complement-lookup", "group-by-key", "prefix-sum-hash"],
  sorting: ["sort-then-scan", "custom-order", "merge-step", "counting-sort", "interval-sweep"],
  "binary-search": ["exact-search", "boundary-search", "range-count", "parametric-search"],
  dp: ["linear-dp", "grid-dp", "knapsack", "sequence-dp", "state-dp"],
  greedy: ["greedy-by-sort", "interval-scheduling", "greedy-accumulate", "digit-greedy"],
  "two-pointers": ["opposite-ends", "same-direction", "fixed-window", "variable-window"],
  heap: ["top-k", "repeated-min", "k-way-merge", "two-heaps", "heap-scheduling"],
  dijkstra: ["weighted-shortest-path", "path-restore", "reverse-or-multi-source", "state-dijkstra", "minimax-path"],
};

/** 패턴이 속한 토픽 */
export function topicOfPattern(pattern: PatternTag): TopicSlug {
  const entry = Object.entries(TOPIC_PATTERNS).find(([, patterns]) => patterns.includes(pattern));
  if (!entry) throw new Error(`토픽이 없는 패턴이에요: ${pattern}`);
  return entry[0] as TopicSlug;
}
