import type { PatternSignal } from "@/types";

/** "문제에 이런 표현이 나오면 이 알고리즘을 의심하라" 신호 목록 */
export const SIGNALS: PatternSignal[] = [
  {
    id: "sig-huge-n",
    phrase: "N이 10억·10¹⁵처럼 아주 커요",
    examples: ["1 ≤ N ≤ 10¹⁵일 때 1부터 N까지 7의 배수는 몇 개?", "a의 b제곱을 구하세요 (b ≤ 10¹⁸)"],
    suspects: ["complexity", "binary-search"],
    patterns: ["formula-o1", "halving-log", "sqrt-bound"],
    reason:
      "1초에 약 1억 번 계산해요. N이 10억을 넘으면 반복문 한 바퀴(O(N))도 못 돌아서, 공식(O(1))이나 절반씩 줄이기(O(log N))가 필요해요.",
    caution: "범위가 크고 '조건을 만족하는 가장 작은 값'을 찾는다면 이분 탐색이에요.",
    strength: "strong",
  },
  {
    id: "sig-all-pairs-slow",
    phrase: "모든 쌍을 보면 풀리는데, N이 10만이에요",
    examples: ["한 번 사고 한 번 팔 때 가장 큰 이익 (가격 10만 개)", "구간 합을 10만 번 물어봐요"],
    suspects: ["complexity", "two-pointers", "hash"],
    patterns: ["single-pass", "precompute"],
    reason:
      "모든 쌍은 N²이라 N = 10만이면 100억 번이에요. 한 번 훑으며 필요한 값(지금까지의 최솟값·누적 합)을 기억하면 N번이면 돼요.",
    caution: "기억해 둘 값이 '짝이 되는 수'라면 해시, 정렬된 배열의 양 끝이라면 두 포인터를 떠올려요.",
    strength: "medium",
  },
  {
    id: "sig-input-size",
    phrase: "N ≤ 20 / N ≤ 1,000 / N ≤ 100,000 같은 입력 제한",
    examples: ["1 ≤ N ≤ 100,000", "1 ≤ N ≤ 20"],
    suspects: ["complexity"],
    patterns: ["single-pass", "sqrt-bound"],
    reason:
      "제한을 보면 필요한 속도가 나와요. N ≤ 20이면 2ᴺ, N ≤ 1,000이면 N², N ≤ 10만이면 N log N, N ≤ 1,000만이면 N까지 괜찮아요.",
    caution: "제한은 거의 모든 문제에 있어요. 이것만으로 유형이 정해지진 않고, 방법의 속도를 가늠하는 데 써요.",
    strength: "weak",
  },
  {
    id: "sig-bracket-pair",
    phrase: "괄호·태그처럼 짝이 맞아야 하는 구조",
    examples: ["올바른 괄호 문자열인지 판단하세요", "여는 태그와 닫는 태그의 짝이 맞는지 확인하세요"],
    suspects: ["stack"],
    patterns: ["bracket-matching"],
    reason: "닫는 괄호는 항상 '가장 최근에 열린' 괄호와 짝이 돼요. 가장 최근 것을 먼저 꺼내는 구조가 바로 스택이에요.",
    caution: "괄호 종류가 한 가지뿐이면 스택 없이 개수 세기로도 풀 수 있어요.",
    strength: "strong",
  },
  {
    id: "sig-latest-first",
    phrase: "가장 최근 것 / 되돌리기 / 직전 값",
    examples: ["실행 취소(Undo)를 구현하세요", "바로 앞의 값과 비교해 지워 나가세요"],
    suspects: ["stack"],
    patterns: ["undo-history", "stack-simulation"],
    reason: "나중에 들어온 것을 먼저 처리해야 하면(LIFO) 스택이 가장 자연스러워요.",
    strength: "medium",
  },
  {
    id: "sig-next-greater",
    phrase: "처음으로 나보다 큰 값 / 몇 칸 뒤에 더 커지는지",
    examples: ["며칠을 기다려야 더 따뜻해지나요?", "왼쪽에서 가장 가까운, 나보다 키가 큰 사람은 누구인가요?"],
    suspects: ["stack"],
    patterns: ["monotonic-stack"],
    reason:
      "아직 답을 찾지 못한 값들을 스택에 쌓아 두고, 더 큰 값이 나타나면 그 값에 막힌 것들을 한꺼번에 꺼내 답을 정해요. 모든 값이 한 번씩만 들어가고 나와서 O(N)이에요.",
    caution: "두 겹 반복문으로 하나하나 찾아도 답은 나오지만, N이 10만이면 시간 초과가 나요.",
    strength: "medium",
  },
  {
    id: "sig-arrival-order",
    phrase: "먼저 온 순서대로 처리 / 차례대로 돌아가며",
    examples: ["도착한 순서대로 처리하세요", "맨 앞 사람을 맨 뒤로 보내는 과정을 반복해요"],
    suspects: ["queue-deque"],
    patterns: ["queue-simulation", "round-robin"],
    reason: "먼저 들어온 것이 먼저 나가는(FIFO) 흐름은 큐로 그대로 옮길 수 있어요.",
    caution: "파이썬 list.pop(0)은 느려요. collections.deque를 쓰세요.",
    strength: "strong",
  },
  {
    id: "sig-both-ends",
    phrase: "앞과 뒤 양쪽에서 넣고 빼기",
    examples: ["앞이나 뒤에서 카드를 한 장씩 뽑을 수 있어요", "양 끝을 비교하며 줄여 나가요"],
    suspects: ["queue-deque"],
    patterns: ["two-ended-deque", "sliding-window-deque"],
    reason: "양쪽 끝을 모두 O(1)로 다룰 수 있는 자료구조가 덱이에요.",
    strength: "medium",
  },
  {
    id: "sig-recent-window",
    phrase: "최근 k개 / 연속한 k칸 구간마다의 최댓값·최솟값",
    examples: ["최근 3초 동안 들어온 요청 수를 구하세요", "연속한 k일 동안의 최고 기온을 날마다 구하세요"],
    suspects: ["queue-deque"],
    patterns: ["sliding-window-deque", "queue-simulation"],
    reason:
      "창(window)이 오른쪽으로 한 칸씩 움직이면, 새 값은 뒤로 들어오고 오래된 값은 앞에서 빠져요. 양 끝을 다루는 큐·덱이 딱 맞아요.",
    caution: "구간마다 max()를 새로 계산하면 O(N·k)라 느려요. 덱에 '후보'만 남겨 두세요.",
    strength: "medium",
  },
  {
    id: "sig-self-similar",
    phrase: "큰 문제가 같은 모양의 작은 문제로 쪼개짐",
    examples: ["n번째 값은 n-1번째와 n-2번째 값으로 정해져요", "절반으로 나눠서 각각 해결한 뒤 합쳐요"],
    suspects: ["recursion"],
    patterns: ["recursive-definition", "divide-and-conquer"],
    reason: "문제 정의 안에 자기 자신이 다시 등장하면 재귀 함수로 그대로 옮길 수 있어요.",
    caution: "같은 계산이 반복되면 메모이제이션(DP)을 함께 떠올리세요.",
    strength: "medium",
  },
  {
    id: "sig-nested-structure",
    phrase: "안에 같은 모양이 또 들어 있는 구조",
    examples: [
      "큰 정사각형을 4등분하고, 각 조각도 똑같이 다시 나눠요",
      "상자 안에 상자가, 그 안에 또 상자가 들어 있어요",
    ],
    suspects: ["recursion", "dfs"],
    patterns: ["divide-and-conquer", "recursion-tree"],
    reason: "바깥 문제와 안쪽 문제가 모양이 같으니, 안쪽 문제는 같은 함수를 다시 불러 해결하면 돼요.",
    caution: "가장 작은 조각(더 나눌 수 없는 경우)에서 멈추는 종료 조건을 먼저 정하세요.",
    strength: "medium",
  },
  {
    id: "sig-shrink-by-one",
    phrase: "한 단계 작은 같은 문제로 줄일 수 있음",
    examples: [
      "n층 탑은 n−1층 탑을 옮긴 뒤 맨 아래 판을 옮기면 돼요",
      "마지막 자릿수를 떼어 내고 나머지를 같은 방법으로 계산해요",
    ],
    suspects: ["recursion"],
    patterns: ["recursive-definition", "recursion-tree"],
    reason: "f(n)을 f(n−1)로 설명할 수 있으면 '종료 조건 + 한 단계 줄여 부르기' 두 줄로 재귀 함수가 완성돼요.",
    strength: "weak",
  },
  {
    id: "sig-relations-given",
    phrase: "A와 B가 연결되어 있다는 관계 목록",
    examples: ["각 줄에 연결된 두 도시의 번호가 주어져요", "친구 관계 쌍이 주어져요"],
    suspects: ["graph-representation", "dfs", "bfs"],
    patterns: ["adjacency-list", "edge-list-conversion"],
    reason: "관계(간선) 목록이 주어지면 먼저 인접 리스트로 바꿔 두는 것이 거의 모든 그래프 문제의 첫 단계예요.",
    strength: "strong",
  },
  {
    id: "sig-degree",
    phrase: "몇 곳과 연결되어 있는지 / 가장 많이 연결된 곳",
    examples: [
      "환승역(3개 이상의 노선이 만나는 역)을 모두 찾으세요",
      "모두에게 추천받았지만 아무도 추천하지 않은 가게를 찾으세요",
    ],
    suspects: ["graph-representation"],
    patterns: ["degree-count"],
    reason:
      "탐색 없이 각 노드에 붙은 간선 수(차수)만 세면 풀려요. 방향 그래프라면 들어오는 수와 나가는 수를 따로 세요.",
    strength: "medium",
  },
  {
    id: "sig-matrix-given",
    phrase: "N×N 표로 연결 여부가 주어짐",
    examples: [
      "i번 컴퓨터와 j번 컴퓨터가 연결되어 있으면 grid[i][j] = 1이에요",
      "도시 사이 직항이 있으면 1, 없으면 0인 표가 주어져요",
    ],
    suspects: ["graph-representation", "dfs", "bfs"],
    patterns: ["adjacency-matrix"],
    reason:
      "표 자체가 인접 행렬이에요. 두 노드의 연결 여부는 O(1)에 알 수 있고, 이웃을 모두 보려면 한 줄(행)을 훑어요.",
    caution: "노드가 많고 간선이 적다면 인접 리스트로 바꾸는 편이 빨라요.",
    strength: "medium",
  },
  {
    id: "sig-tree-structure",
    phrase: "부모와 자식 / 사이클 없이 모두 연결된 N−1개의 길",
    examples: ["각 직원의 직속 상사가 주어져요", "마을 N개가 N−1개의 길로 모두 이어져 있어요"],
    suspects: ["dfs", "graph-representation"],
    patterns: ["tree-traversal", "edge-list-conversion"],
    reason: "트리에서는 한 노드의 답을 자식들의 답으로 계산할 수 있어요. DFS로 내려갔다가 돌아오면서 모으면 돼요.",
    caution: "간선 목록으로 주어지면 방향이 없으니, 부모로 되돌아가지 않도록 방문 표시를 하세요.",
    strength: "medium",
  },
  {
    id: "sig-connected-group",
    phrase: "이어진 덩어리 / 구역 / 그룹의 개수·크기",
    examples: [
      "상하좌우로 맞닿은 칸들은 하나의 구역이에요",
      "서로 연결된 컴퓨터는 같은 네트워크에 속해요",
      "친구의 친구도 같은 모임이에요",
    ],
    suspects: ["dfs", "bfs"],
    patterns: ["connected-components", "grid-flood-fill"],
    reason:
      "한 지점에서 출발해 닿을 수 있는 곳을 전부 칠하면 덩어리 하나가 끝나요. 목적이 '전부 방문'이라 DFS와 BFS 모두 가능하고, 보통 코드가 짧은 DFS를 먼저 떠올려요.",
    caution: "'가장 가까운', '최소 몇 번'이 함께 나오면 거리를 재야 하므로 BFS를 의심하세요.",
    strength: "strong",
  },
  {
    id: "sig-grid-neighbors",
    phrase: "격자(지도) + 상하좌우 이동",
    examples: ["N×M 크기의 지도가 주어져요", "상하좌우로 인접한 칸으로만 이동할 수 있어요"],
    suspects: ["dfs", "bfs"],
    patterns: ["grid-flood-fill", "grid-shortest-path"],
    reason:
      "격자는 '칸 = 노드, 붙어 있는 칸 = 간선'인 그래프예요. 인접 리스트를 따로 만들지 않고 방향 배열 (-1,0), (1,0), (0,-1), (0,1)로 이웃을 구해요.",
    caution: "대각선 포함 여부(4방향 / 8방향)를 문제에서 반드시 확인하세요.",
    strength: "medium",
  },
  {
    id: "sig-path-exists",
    phrase: "갈 수 있는지 / 경로가 있는지 / 순환이 있는지",
    examples: ["출발점에서 도착점까지 갈 수 있나요?", "선수 과목 관계에 순환이 있는지 확인하세요"],
    suspects: ["dfs"],
    patterns: ["path-existence", "cycle-detection"],
    reason:
      "'있다/없다'만 알면 되니 한 길로 끝까지 가 보는 DFS가 간단해요. 재귀 호출 중인 노드를 다시 만나면 순환이에요.",
    strength: "medium",
  },
  {
    id: "sig-shortest-steps",
    phrase: "최단 거리 / 최소 횟수 / 가장 빨리",
    examples: ["도착점까지 최소 몇 칸을 지나야 하나요?", "최소 몇 번 만에 목표 상태가 되나요?"],
    suspects: ["bfs"],
    patterns: ["shortest-path-unweighted", "grid-shortest-path", "state-space-bfs"],
    reason: "BFS는 가까운 곳부터 한 겹씩 넓혀 가므로, 처음 도착한 순간의 거리가 곧 최단 거리예요.",
    caution: "간선마다 비용(가중치)이 다르면 BFS가 아니라 다익스트라예요.",
    strength: "strong",
  },
  {
    id: "sig-spread-simultaneous",
    phrase: "여러 곳에서 동시에 퍼짐 / 며칠 뒤에",
    examples: ["익은 토마토가 하루마다 옆 칸으로 퍼져요", "불이 1분마다 상하좌우로 번져요"],
    suspects: ["bfs"],
    patterns: ["multi-source-bfs", "level-order"],
    reason: "시작점을 전부 큐에 넣고 BFS를 한 번 돌리면, 퍼지는 시간이 곧 BFS의 층(거리)이에요.",
    strength: "strong",
  },
  {
    id: "sig-all-cases",
    phrase: "모든 경우의 수 / 가능한 조합을 전부",
    examples: ["가능한 모든 순서를 출력하세요", "합이 K가 되는 부분집합을 모두 찾으세요"],
    suspects: ["backtracking"],
    patterns: ["permutation", "combination", "subset"],
    reason: "하나씩 고르고, 끝까지 가면 기록하고, 되돌아와 다음 선택지를 고르는 흐름이 백트래킹이에요.",
    caution: "경우의 수가 너무 많다면 가지치기나 DP가 필요해요.",
    strength: "strong",
  },
  {
    id: "sig-placement-constraint",
    phrase: "서로 부딪히지 않게 배치하는 모든 방법",
    examples: [
      "서로 공격할 수 없게 말을 놓는 방법의 수를 구하세요",
      "이웃한 지역은 다른 색이 되도록 칠하는 방법의 수를 구하세요",
    ],
    suspects: ["backtracking"],
    patterns: ["constraint-pruning"],
    reason: "하나씩 놓아 보다가 규칙을 어기는 순간 그 가지를 버리고 되돌아가요. 끝까지 도착한 배치만 셉니다.",
    caution: "놓을 때마다 전체 판을 다시 검사하지 말고, 사용 중인 열·대각선 같은 정보를 따로 기록해 O(1)에 확인하세요.",
    strength: "strong",
  },
  {
    id: "sig-small-n",
    phrase: "입력 크기가 아주 작음 (N ≤ 10 정도)",
    examples: ["1 ≤ N ≤ 8", "재료는 최대 10개예요"],
    suspects: ["backtracking"],
    patterns: ["constraint-pruning", "permutation"],
    reason: "N이 작으면 모든 경우를 다 만들어 봐도 시간 안에 끝나요. 완전 탐색을 허락한다는 힌트예요.",
    strength: "weak",
  },
  {
    id: "sig-seen-before",
    phrase: "이미 나온 적 있는지 / 중복인지 확인",
    examples: ["같은 이름이 두 번 이상 나오는지 확인하세요", "처음 보는 단어일 때만 기록하세요"],
    suspects: ["hash"],
    patterns: ["existence-check"],
    reason:
      "리스트에서 있는지 찾으면 매번 처음부터 훑어야 해서 O(N)이에요. 본 것을 해시(set·dict)에 넣어 두면 있는지 확인이 평균 O(1)이에요.",
    caution: "N이 수십 개뿐이면 리스트로 찾아도 충분해요. N이 수만 이상이면 꼭 해시를 쓰세요.",
    strength: "strong",
  },
  {
    id: "sig-count-each",
    phrase: "각각 몇 번 나왔는지 / 가장 많이 나온 것",
    examples: ["투표에서 가장 많은 표를 받은 후보는 누구인가요?", "각 과일이 몇 개씩 있는지 세어 주세요"],
    suspects: ["hash"],
    patterns: ["frequency-count"],
    reason: "이름(키)마다 개수(값)를 붙여 두는 dict가 딱 맞아요. 한 번 훑으면서 count[x] += 1만 하면 돼요.",
    caution: "키가 0~100 같은 작은 정수라면 길이 101짜리 배열로 세도 돼요.",
    strength: "strong",
  },
  {
    id: "sig-pair-target",
    phrase: "합(차)이 K가 되는 두 수 / 짝이 되는 것 찾기",
    examples: ["더해서 target이 되는 두 수의 위치를 구하세요", "차이가 정확히 K인 쌍은 몇 개인가요?"],
    suspects: ["hash"],
    patterns: ["complement-lookup"],
    reason:
      "모든 쌍을 보면 O(N²)이에요. 지금 수 x에게 필요한 짝은 K - x로 정해져 있으니, 지금까지 본 수를 해시에 넣어 두고 짝이 있는지 O(1)에 물어봐요.",
    caution: "배열이 이미 정렬돼 있으면 양쪽 끝에서 좁혀 오는 두 포인터로도 풀 수 있어요.",
    strength: "strong",
  },
  {
    id: "sig-group-same",
    phrase: "같은 종류끼리 묶기 / 글자 구성이 같은 단어",
    examples: ["애너그램끼리 묶어 주세요", "같은 반 학생끼리 이름을 모아 주세요"],
    suspects: ["hash"],
    patterns: ["group-by-key"],
    reason: "묶는 기준을 키로 만들고(예: 글자를 정렬한 문자열), dict[키]에 리스트로 모으면 한 번에 묶여요.",
    strength: "medium",
  },
  {
    id: "sig-subarray-sum",
    phrase: "연속 구간의 합이 정확히 K인 개수",
    examples: ["합이 K인 연속 구간은 몇 개인가요?", "연속한 날들의 합이 0이 되는 구간을 세세요"],
    suspects: ["hash"],
    patterns: ["prefix-sum-hash"],
    reason:
      "구간 합 = 지금까지의 누적 합 − 앞의 어떤 누적 합이에요. 지금까지 나온 누적 합의 개수를 dict에 세어 두면 필요한 앞쪽 누적 합이 몇 번 있었는지 바로 알 수 있어요.",
    caution: "음수가 없고 '합이 K 이상' 같은 조건이면 두 포인터(슬라이딩 윈도우)가 더 간단할 수 있어요.",
    strength: "medium",
  },
  {
    id: "sig-order-rule",
    phrase: "~순으로, 같으면 ~순으로 나열",
    examples: [
      "점수가 높은 순으로, 점수가 같으면 이름 순으로 출력하세요",
      "길이가 짧은 단어부터, 길이가 같으면 사전 순으로",
    ],
    suspects: ["sorting"],
    patterns: ["custom-order"],
    reason:
      "기준을 차례로 비교하는 정렬 키를 만들면 한 번의 정렬로 끝나요. 직접 정렬을 짤 필요 없이 기준만 정확히 적으면 돼요.",
    caution: "내림차순 기준은 숫자에 −를 붙이거나 비교 함수의 순서를 바꿔요.",
    strength: "strong",
  },
  {
    id: "sig-neighbor-after-sort",
    phrase: "가장 가까운 두 값 / K번째로 큰 값 / 중앙값",
    examples: ["차이가 가장 작은 두 수를 구하세요", "세 번째로 무거운 도토리는 몇 g인가요?"],
    suspects: ["sorting"],
    patterns: ["sort-then-scan"],
    reason: "정렬하면 크기가 비슷한 값이 옆에 붙고, K번째 값은 K번째 자리에 와요. 모든 쌍을 볼 필요가 없어져요.",
    caution: "정렬은 O(N log N)이에요. 딱 한 번만 필요한 최댓값·최솟값은 한 번 훑는 O(N)으로 충분해요.",
    strength: "medium",
  },
  {
    id: "sig-intervals",
    phrase: "시작과 끝이 있는 구간이 겹치는지",
    examples: ["겹치는 예약을 하나로 합쳐 주세요", "동시에 진행 중인 회의가 가장 많을 때는 몇 개인가요?"],
    suspects: ["sorting"],
    patterns: ["interval-sweep"],
    reason: "구간을 시작 시각 순으로 정렬하면, 겹치는 구간은 반드시 이웃해요. 한 번 훑으면서 합치거나 셀 수 있어요.",
    strength: "strong",
  },
  {
    id: "sig-small-value-range",
    phrase: "값의 범위가 작음 (0~100 점수, 알파벳 등)",
    examples: ["점수는 0점부터 100점 사이예요", "나이는 1살부터 120살까지예요"],
    suspects: ["sorting"],
    patterns: ["counting-sort"],
    reason: "값의 종류가 적으면 값마다 개수를 세어 두는 계수 정렬로 O(N + 값의 범위)에 정렬할 수 있어요.",
    strength: "weak",
  },
  {
    id: "sig-inversions",
    phrase: "순서가 뒤바뀐 쌍의 수 / 옆끼리 바꾸는 횟수",
    examples: [
      "i < j인데 a[i] > a[j]인 쌍은 몇 개인가요?",
      "옆 사람끼리 자리를 바꿔 키 순서로 서려면 몇 번 바꿔야 하나요?",
    ],
    suspects: ["sorting"],
    patterns: ["merge-step"],
    reason:
      "병합 정렬로 두 절반을 합칠 때, 오른쪽 값이 먼저 나가면 왼쪽에 남은 값의 수만큼 뒤바뀐 쌍이 생겨요. O(N log N)에 셀 수 있어요.",
    caution: "N이 수천 이하면 이중 반복문으로 세도 괜찮아요.",
    strength: "medium",
  },
  {
    id: "sig-sorted-many-queries",
    phrase: "정렬된 목록 + 질문이 아주 많음",
    examples: [
      "정렬된 번호 10만 개에서 질문 10만 개마다 위치를 찾으세요",
      "점수가 q점 이상인 학생 수를 질문마다 답하세요",
    ],
    suspects: ["binary-search"],
    patterns: ["exact-search", "range-count"],
    reason: "질문마다 처음부터 훑으면 O(N·Q)예요. 정렬돼 있으면 반씩 버리며 O(log N)에 찾아서 전체 O(Q log N)이에요.",
    caution: "위치가 필요 없고 '있는지'만 물으면 해시(set)가 더 간단해요.",
    strength: "strong",
  },
  {
    id: "sig-first-true",
    phrase: "처음으로 ~ 이상이 되는 위치 / 경계",
    examples: ["x 이상인 첫 번째 위치를 구하세요", "처음으로 비가 온 날은 며칠째인가요?"],
    suspects: ["binary-search"],
    patterns: ["boundary-search"],
    reason: "앞쪽은 전부 '아니오', 뒤쪽은 전부 '예'로 나뉘면 그 경계는 이분 탐색으로 찾을 수 있어요.",
    strength: "medium",
  },
  {
    id: "sig-max-min-answer",
    phrase: "~할 수 있는 최대 / 최소 값 (최대의 최소, 최소의 최대)",
    examples: ["적어도 K개를 만들 수 있는 최대 길이는?", "가장 큰 묶음의 합을 최소로 하려면?"],
    suspects: ["binary-search"],
    patterns: ["parametric-search"],
    reason:
      "답을 직접 구하긴 어렵지만 '답이 X일 때 가능한가?'는 쉽게 확인할 수 있고, 가능/불가능이 한 번만 바뀌면 X를 이분 탐색해요.",
    caution: "X가 커질수록 가능 → 불가능(또는 반대)으로 한 번만 바뀌는지 먼저 확인하세요.",
    strength: "strong",
  },
  {
    id: "sig-huge-range",
    phrase: "답의 범위가 엄청 큼 (10억, 10¹⁸)",
    examples: ["1 ≤ 시간 ≤ 1,000,000,000,000", "길이는 최대 2³¹ − 1이에요"],
    suspects: ["binary-search"],
    patterns: ["parametric-search"],
    reason: "답 후보를 하나씩 다 확인할 수 없을 만큼 크면, 반씩 줄여 약 30~60번만 확인하는 이분 탐색을 떠올려요.",
    strength: "weak",
  },
  {
    id: "sig-count-ways-mod",
    phrase: "방법의 수를 1,000,000,007로 나눈 나머지",
    examples: [
      "계단을 오르는 방법의 수를 1,000,000,007로 나눈 나머지를 구하세요",
      "경로의 수가 매우 클 수 있으니 나머지를 출력하세요",
    ],
    suspects: ["dp"],
    patterns: ["linear-dp", "grid-dp"],
    reason:
      "나머지를 구하라는 건 경우의 수가 너무 많아 하나씩 셀 수 없다는 뜻이에요. 작은 문제의 답을 표에 적어 두고 더해 가는 DP가 딱 맞아요.",
    caution: "모든 경우를 직접 나열해야 한다면 백트래킹이에요. '개수'만 필요하면 DP예요.",
    strength: "strong",
  },
  {
    id: "sig-overlapping-subproblems",
    phrase: "같은 계산이 여러 번 반복됨 (작은 문제의 답을 합쳐 큰 답)",
    examples: ["n번째 칸까지 오는 방법 = n-1번째 + n-2번째", "이 칸의 최소 비용은 위 칸과 왼쪽 칸 중 작은 쪽 + 이 칸"],
    suspects: ["dp"],
    patterns: ["linear-dp", "grid-dp"],
    reason:
      "재귀로 그대로 풀면 같은 작은 문제를 수없이 다시 계산해요. 한 번 구한 답을 표(메모)에 적어 두면 각 문제를 한 번씩만 풀어요.",
    strength: "strong",
  },
  {
    id: "sig-best-choice-sequence",
    phrase: "선택마다 결과가 달라지는 최대 · 최소 (고르면 다음 선택이 제한)",
    examples: ["이웃한 집은 함께 고를 수 없을 때 최대 금액은?", "무게 한도 안에서 가치의 합을 최대로 하세요"],
    suspects: ["dp"],
    patterns: ["knapsack", "state-dp"],
    reason:
      "그 순간 가장 좋아 보이는 선택(탐욕)이 전체 최선이 아닐 수 있어요. '여기까지 봤을 때의 최선'을 상태별로 표에 기록하면 모든 선택을 빠르게 비교할 수 있어요.",
    caution: "N이 아주 작으면(≤ 20) 백트래킹으로도 돼요. N이나 한도가 크면 DP예요.",
    strength: "strong",
  },
  {
    id: "sig-two-strings",
    phrase: "두 문자열의 공통 부분 / 바꾸는 최소 횟수",
    examples: ["두 단어의 가장 긴 공통 부분 수열의 길이는?", "한 단어를 다른 단어로 바꾸는 최소 편집 횟수는?"],
    suspects: ["dp"],
    patterns: ["sequence-dp"],
    reason:
      "앞에서 i글자, j글자까지 봤을 때의 답을 dp[i][j]에 적으면, 마지막 글자가 같은지만 보고 이웃 칸에서 답을 가져올 수 있어요.",
    strength: "strong",
  },
  {
    id: "sig-greedy-local-best",
    phrase: "매번 가장 ~한 것부터 고르면 될 것 같음",
    examples: ["가장 가벼운 짐부터 담으면 가장 많이 담을 수 있나요?", "큰 동전부터 쓰면 동전 수가 가장 적을까요?"],
    suspects: ["greedy"],
    patterns: ["greedy-by-sort", "greedy-accumulate"],
    reason:
      "지금 가장 좋아 보이는 선택이 나중에도 손해가 안 된다고 보일 수 있으면 그리디예요. 정렬 한 번 + 한 번 훑기로 끝나서 빨라요.",
    caution:
      "반례 하나로 무너져요. 작은 예를 손으로 만들어 '욕심껏 고른 답'과 '진짜 최선'이 다른 경우가 없는지 꼭 확인하세요. 있으면 DP예요.",
    strength: "medium",
  },
  {
    id: "sig-interval-max-count",
    phrase: "겹치지 않게 최대 몇 개 / 모두 덮는 최소 몇 개",
    examples: [
      "회의실 하나로 열 수 있는 회의는 최대 몇 개인가요?",
      "모든 풍선을 터뜨리려면 화살이 최소 몇 개 필요한가요?",
    ],
    suspects: ["greedy"],
    patterns: ["interval-scheduling"],
    reason: "끝나는 시각이 빠른 것부터 고르면 남은 시간이 가장 넉넉해요. 끝 시각으로 정렬하고 한 번 훑으면 돼요.",
    caution: "시작 시각이나 길이로 정렬하면 반례가 있어요. 끝 시각 기준이 핵심이에요.",
    strength: "strong",
  },
  {
    id: "sig-running-reach",
    phrase: "지금까지 갈 수 있는 가장 먼 곳 / 모자라면 다시 시작",
    examples: ["징검다리 끝까지 갈 수 있나요?", "주유소를 한 바퀴 돌 수 있는 출발점은 어디인가요?"],
    suspects: ["greedy"],
    patterns: ["greedy-accumulate"],
    reason:
      "한 번 훑으면서 '지금까지의 최선'(가장 먼 거리, 남은 연료)만 들고 가면 돼요. 되돌아가 다시 볼 필요가 없어요.",
    strength: "medium",
  },
  {
    id: "sig-sorted-pair-ends",
    phrase: "정렬된 배열에서 합(차)이 K인 두 수 / 양 끝에서 비교",
    examples: ["정렬된 수열에서 합이 X가 되는 두 수를 찾으세요", "양쪽 벽 사이에 담을 수 있는 물의 최대 양은?"],
    suspects: ["two-pointers"],
    patterns: ["opposite-ends"],
    reason:
      "정렬돼 있으면 합이 작을 때 왼쪽을, 클 때 오른쪽을 한 칸씩 옮기면 돼요. 두 손가락이 만날 때까지 O(N)이에요.",
    caution: "정렬이 안 돼 있고 위치를 그대로 돌려줘야 하면 해시로 짝을 찾는 편이 쉬워요.",
    strength: "strong",
  },
  {
    id: "sig-contiguous-window",
    phrase: "연속 구간 + 조건 (합이 S 이상인 가장 짧은 / 종류가 K개 이하인 가장 긴)",
    examples: ["합이 S 이상인 연속 부분 수열의 최소 길이는?", "서로 다른 과일이 2종류 이하인 가장 긴 구간은?"],
    suspects: ["two-pointers"],
    patterns: ["variable-window", "fixed-window"],
    reason:
      "오른쪽 끝을 늘려 조건을 만족시키고, 왼쪽 끝을 줄여 최소로 만드는 창(슬라이딩 윈도우)을 쓰면 각 칸을 두 번씩만 봐요.",
    caution: "음수가 섞여 있으면 창을 늘린다고 합이 커지지 않아요. 그땐 누적 합 + 해시를 떠올리세요.",
    strength: "strong",
  },
  {
    id: "sig-in-place",
    phrase: "순서를 지키며 제자리에서 걸러 내기 / 부분 수열인지",
    examples: ["정렬된 배열에서 중복을 없애세요", "s가 t의 부분 수열인지 확인하세요"],
    suspects: ["two-pointers"],
    patterns: ["same-direction"],
    reason:
      "읽는 손가락(빠름)과 쓰는 손가락(느림) 두 개를 같은 방향으로 움직이면, 한 번 훑으며 순서를 지켜 걸러 낼 수 있어요.",
    strength: "medium",
  },
  {
    id: "sig-repeated-min",
    phrase: "가장 작은(큰) 것을 계속 꺼내고, 새로 넣기를 반복",
    examples: [
      "가장 작은 두 더미를 합치는 일을 하나가 남을 때까지 반복해요",
      "가장 급한 환자부터 치료하고, 새 환자가 계속 와요",
    ],
    suspects: ["heap"],
    patterns: ["repeated-min", "heap-scheduling"],
    reason: "매번 정렬하면 O(N log N)씩 들어요. 힙은 가장 작은 것을 O(1)에 보고, 넣고 꺼내기를 O(log N)에 해요.",
    caution: "한 번만 가장 작은 것이 필요하면 그냥 min으로 충분해요. '꺼내고 또 넣기'가 반복될 때 힙이에요.",
    strength: "strong",
  },
  {
    id: "sig-top-k",
    phrase: "상위 K개 / K번째로 큰 것 (계속 들어오는 값에서)",
    examples: ["점수가 들어올 때마다 지금까지 3번째로 높은 점수를 알려 주세요", "가장 많이 나온 단어 K개를 구하세요"],
    suspects: ["heap"],
    patterns: ["top-k"],
    reason: "크기가 K인 최소 힙을 두면, 맨 위가 곧 K번째로 큰 값이에요. 전체를 정렬하지 않아도 돼요.",
    caution: "값이 한꺼번에 주어지고 한 번만 물으면 정렬도 괜찮아요.",
    strength: "medium",
  },
  {
    id: "sig-running-median",
    phrase: "지금까지의 중앙값 / 계속 바뀌는 가운데 값",
    examples: ["수를 하나 읽을 때마다 지금까지의 중앙값을 말하세요"],
    suspects: ["heap"],
    patterns: ["two-heaps"],
    reason: "작은 절반은 최대 힙, 큰 절반은 최소 힙에 나눠 담으면 두 힙의 맨 위가 가운데 값이에요.",
    strength: "strong",
  },
  {
    id: "sig-weighted-route",
    phrase: "길마다 걸리는 시간·비용이 다른데, 가장 적게 드는 길",
    examples: ["마을을 잇는 길마다 걸리는 시간이 달라요. 0번 마을에서 각 마을까지 가장 빨리 가는 시간은?"],
    suspects: ["dijkstra"],
    patterns: ["weighted-shortest-path", "path-restore"],
    reason:
      "간선 비용이 다르면 적게 지난 길이 짧은 길이 아니에요. 지금까지 가장 가까운 곳부터 확정하는 다익스트라가 맞아요.",
    caution: "모든 비용이 같으면 BFS로 충분해요. 비용이 음수면 다익스트라를 쓸 수 없어요.",
    strength: "strong",
  },
  {
    id: "sig-route-with-state",
    phrase: "최소 비용인데 쿠폰·환승 횟수 같은 조건이 붙어요",
    examples: ["한 번만 요금을 반으로 줄이는 쿠폰이 있어요", "많아야 K번 갈아탈 때 가장 싼 요금은?"],
    suspects: ["dijkstra"],
    patterns: ["state-dijkstra"],
    reason: "(노드, 쿠폰을 썼는지)처럼 상태를 노드에 더하면 새 그래프가 생기고, 거기서 다익스트라를 돌리면 돼요.",
    caution: "상태 수 × 노드 수가 너무 크지 않은지 먼저 확인해요.",
    strength: "medium",
  },
  {
    id: "sig-worst-edge",
    phrase: "경로에서 가장 험한(큰) 구간을 가장 작게",
    examples: ["지나는 길 중 가장 가파른 경사를 가장 작게 하려면?"],
    suspects: ["dijkstra"],
    patterns: ["minimax-path"],
    reason: "경로의 값이 '합'이 아니라 '가장 큰 값'이어도, 가장 작은 후보부터 확정하는 다익스트라가 그대로 통해요.",
    caution: "답의 범위로 이분 탐색하고 BFS로 갈 수 있는지 확인하는 방법도 있어요.",
    strength: "medium",
  },
  {
    id: "sig-merge-groups",
    phrase: "관계가 하나씩 더해지면서 '같은 그룹인가?'를 계속 물어요",
    examples: [
      "두 사람이 친구가 될 때마다, 두 사람이 같은 모임인지 알려 주세요",
      "길을 하나씩 놓다가 처음으로 고리가 생기는 순간은?",
    ],
    suspects: ["graph-advanced"],
    patterns: ["union-find", "reverse-union"],
    reason:
      "그룹을 합치고(union) 대표를 찾는(find) 일이 거의 O(1)이에요. 관계가 늘 때마다 DFS를 다시 하지 않아도 돼요.",
    caution:
      "관계가 다 주어진 뒤 그룹 수를 한 번만 세면 DFS·BFS로도 충분해요. 관계가 끊기는 문제는 거꾸로 합치기를 떠올려요.",
    strength: "strong",
  },
  {
    id: "sig-connect-all-cheap",
    phrase: "모든 곳을 잇는 데 드는 비용의 최솟값",
    examples: ["모든 집에 인터넷이 닿게 케이블을 깔 때 드는 최소 비용은?"],
    suspects: ["graph-advanced"],
    patterns: ["minimum-spanning-tree"],
    reason: "싼 간선부터 보며, 아직 다른 그룹인 두 곳만 이으면(크루스칼) 모두를 잇는 가장 싼 방법이 돼요.",
    caution: "두 곳 사이의 가장 싼 길은 최단 경로(다익스트라)예요. '모두를 잇는' 비용인지 확인해요.",
    strength: "strong",
  },
  {
    id: "sig-prerequisites",
    phrase: "먼저 끝내야 하는 일 / 선수 과목 / 순서 조건",
    examples: ["A 과목을 들어야 B 과목을 들을 수 있어요", "작업마다 먼저 끝나야 하는 작업이 있어요"],
    suspects: ["graph-advanced"],
    patterns: ["topological-sort", "dag-dp"],
    reason: "먼저 할 일이 모두 끝난(들어오는 화살표가 없는) 일부터 하나씩 꺼내면 모든 조건을 지키는 순서가 나와요.",
    caution: "끝까지 꺼내지 못한 일이 남으면 조건이 고리를 이루고 있다는 뜻이에요.",
    strength: "strong",
  },
  {
    id: "sig-follow-rules",
    phrase: "규칙이 길게 적혀 있고, 그대로 따라 하면 답이 나와요",
    examples: [
      "1초마다 머리를 한 칸 옮기고, 사과를 먹으면 꼬리는 그대로예요…",
      "청소한 칸이 없으면 뒤로 한 칸 물러나요…",
    ],
    suspects: ["implementation"],
    patterns: ["step-simulation"],
    reason:
      "특별한 알고리즘 없이 규칙을 정확히 옮기는 게 핵심이에요. 상태(위치·방향·시간)를 변수로 정하고, 한 단계씩 규칙을 적용해요.",
    caution:
      "입력이 커서 한 단계씩 하면 느리다면, 반복되는 부분을 줄이거나(나머지 연산) 다른 알고리즘이 필요한지 봐요.",
    strength: "strong",
  },
  {
    id: "sig-direction-turn",
    phrase: "동서남북·왼쪽/오른쪽으로 돌며 움직여요",
    examples: ["L이면 왼쪽으로 90도 돌고, F면 앞으로 한 칸 가요", "판을 시계 방향으로 90도 돌려요"],
    suspects: ["implementation"],
    patterns: ["direction-move", "matrix-transform"],
    reason: "방향을 0~3 번호로 두고 dr, dc 배열을 쓰면, 오른쪽으로 돌기는 (d + 1) % 4, 왼쪽은 (d + 3) % 4 한 줄이에요.",
    caution: "가장 가까운 칸·최소 이동 횟수를 물으면 BFS예요.",
    strength: "medium",
  },
  {
    id: "sig-time-format",
    phrase: '"HH:MM"·"YYYY-MM-DD" 같은 형식을 읽고 계산해요',
    examples: ['"23:50"에서 20분 뒤는?', "입차·출차 기록으로 요금을 계산하세요"],
    suspects: ["implementation"],
    patterns: ["string-parse", "time-calc"],
    reason: "시각은 모두 '분'으로, 날짜는 '며칠째'로 바꿔 계산한 뒤 다시 형식에 맞춰 적으면 실수가 줄어요.",
    caution: "두 자리로 채우기(09:05), 자정 넘기기, 윤년 같은 경계를 꼭 확인해요.",
    strength: "medium",
  },
];

const SIGNALS_BY_ID = new Map(SIGNALS.map((signal) => [signal.id, signal]));

export function getSignal(id: string): PatternSignal | undefined {
  return SIGNALS_BY_ID.get(id);
}
