import type { PatternSignal } from "@/types";

/** "문제에 이런 표현이 나오면 이 알고리즘을 의심하라" 신호 목록 */
export const SIGNALS: PatternSignal[] = [
  {
    id: "sig-bracket-pair",
    phrase: "괄호·태그처럼 짝이 맞아야 하는 구조",
    examples: ["올바른 괄호 문자열인지 판단하세요", "여는 태그와 닫는 태그의 짝이 맞는지 확인하세요"],
    suspects: ["stack"],
    patterns: ["bracket-matching"],
    reason: "닫는 괄호는 항상 '가장 최근에 열린' 괄호와 짝이 돼요. 가장 최근 것을 먼저 꺼내는 구조가 바로 스택이에요.",
    caution: "괄호 종류가 한 가지뿐이면 스택 없이 개수 세기로도 풀 수 있어요.",
    strength: "strong",
  },
  {
    id: "sig-latest-first",
    phrase: "가장 최근 것 / 되돌리기 / 직전 값",
    examples: ["실행 취소(Undo)를 구현하세요", "바로 앞의 값과 비교해 지워 나가세요"],
    suspects: ["stack"],
    patterns: ["undo-history", "stack-simulation"],
    reason: "나중에 들어온 것을 먼저 처리해야 하면(LIFO) 스택이 가장 자연스러워요.",
    strength: "medium",
  },
  {
    id: "sig-next-greater",
    phrase: "처음으로 나보다 큰 값 / 몇 칸 뒤에 더 커지는지",
    examples: ["며칠을 기다려야 더 따뜻해지나요?", "왼쪽에서 가장 가까운, 나보다 키가 큰 사람은 누구인가요?"],
    suspects: ["stack"],
    patterns: ["monotonic-stack"],
    reason:
      "아직 답을 찾지 못한 값들을 스택에 쌓아 두고, 더 큰 값이 나타나면 그 값에 막힌 것들을 한꺼번에 꺼내 답을 정해요. 모든 값이 한 번씩만 들어가고 나와서 O(N)이에요.",
    caution: "두 겹 반복문으로 하나하나 찾아도 답은 나오지만, N이 10만이면 시간 초과가 나요.",
    strength: "medium",
  },
  {
    id: "sig-arrival-order",
    phrase: "먼저 온 순서대로 처리 / 차례대로 돌아가며",
    examples: ["도착한 순서대로 처리하세요", "맨 앞 사람을 맨 뒤로 보내는 과정을 반복해요"],
    suspects: ["queue-deque"],
    patterns: ["queue-simulation", "round-robin"],
    reason: "먼저 들어온 것이 먼저 나가는(FIFO) 흐름은 큐로 그대로 옮길 수 있어요.",
    caution: "파이썬 list.pop(0)은 느려요. collections.deque를 쓰세요.",
    strength: "strong",
  },
  {
    id: "sig-both-ends",
    phrase: "앞과 뒤 양쪽에서 넣고 빼기",
    examples: ["앞이나 뒤에서 카드를 한 장씩 뽑을 수 있어요", "양 끝을 비교하며 줄여 나가요"],
    suspects: ["queue-deque"],
    patterns: ["two-ended-deque", "sliding-window-deque"],
    reason: "양쪽 끝을 모두 O(1)로 다룰 수 있는 자료구조가 덱이에요.",
    strength: "medium",
  },
  {
    id: "sig-recent-window",
    phrase: "최근 k개 / 연속한 k칸 구간마다의 최댓값·최솟값",
    examples: ["최근 3초 동안 들어온 요청 수를 구하세요", "연속한 k일 동안의 최고 기온을 날마다 구하세요"],
    suspects: ["queue-deque"],
    patterns: ["sliding-window-deque", "queue-simulation"],
    reason:
      "창(window)이 오른쪽으로 한 칸씩 움직이면, 새 값은 뒤로 들어오고 오래된 값은 앞에서 빠져요. 양 끝을 다루는 큐·덱이 딱 맞아요.",
    caution: "구간마다 max()를 새로 계산하면 O(N·k)라 느려요. 덱에 '후보'만 남겨 두세요.",
    strength: "medium",
  },
  {
    id: "sig-self-similar",
    phrase: "큰 문제가 같은 모양의 작은 문제로 쪼개짐",
    examples: ["n번째 값은 n-1번째와 n-2번째 값으로 정해져요", "절반으로 나눠서 각각 해결한 뒤 합쳐요"],
    suspects: ["recursion"],
    patterns: ["recursive-definition", "divide-and-conquer"],
    reason: "문제 정의 안에 자기 자신이 다시 등장하면 재귀 함수로 그대로 옮길 수 있어요.",
    caution: "같은 계산이 반복되면 메모이제이션(DP)을 함께 떠올리세요.",
    strength: "medium",
  },
  {
    id: "sig-nested-structure",
    phrase: "안에 같은 모양이 또 들어 있는 구조",
    examples: [
      "큰 정사각형을 4등분하고, 각 조각도 똑같이 다시 나눠요",
      "상자 안에 상자가, 그 안에 또 상자가 들어 있어요",
    ],
    suspects: ["recursion", "dfs"],
    patterns: ["divide-and-conquer", "recursion-tree"],
    reason: "바깥 문제와 안쪽 문제가 모양이 같으니, 안쪽 문제는 같은 함수를 다시 불러 해결하면 돼요.",
    caution: "가장 작은 조각(더 나눌 수 없는 경우)에서 멈추는 종료 조건을 먼저 정하세요.",
    strength: "medium",
  },
  {
    id: "sig-shrink-by-one",
    phrase: "한 단계 작은 같은 문제로 줄일 수 있음",
    examples: [
      "n층 탑은 n−1층 탑을 옮긴 뒤 맨 아래 판을 옮기면 돼요",
      "마지막 자릿수를 떼어 내고 나머지를 같은 방법으로 계산해요",
    ],
    suspects: ["recursion"],
    patterns: ["recursive-definition", "recursion-tree"],
    reason: "f(n)을 f(n−1)로 설명할 수 있으면 '종료 조건 + 한 단계 줄여 부르기' 두 줄로 재귀 함수가 완성돼요.",
    strength: "weak",
  },
  {
    id: "sig-relations-given",
    phrase: "A와 B가 연결되어 있다는 관계 목록",
    examples: ["각 줄에 연결된 두 도시의 번호가 주어져요", "친구 관계 쌍이 주어져요"],
    suspects: ["graph-representation", "dfs", "bfs"],
    patterns: ["adjacency-list", "edge-list-conversion"],
    reason: "관계(간선) 목록이 주어지면 먼저 인접 리스트로 바꿔 두는 것이 거의 모든 그래프 문제의 첫 단계예요.",
    strength: "strong",
  },
  {
    id: "sig-degree",
    phrase: "몇 곳과 연결되어 있는지 / 가장 많이 연결된 곳",
    examples: [
      "환승역(3개 이상의 노선이 만나는 역)을 모두 찾으세요",
      "모두에게 추천받았지만 아무도 추천하지 않은 가게를 찾으세요",
    ],
    suspects: ["graph-representation"],
    patterns: ["degree-count"],
    reason:
      "탐색 없이 각 노드에 붙은 간선 수(차수)만 세면 풀려요. 방향 그래프라면 들어오는 수와 나가는 수를 따로 세요.",
    strength: "medium",
  },
  {
    id: "sig-matrix-given",
    phrase: "N×N 표로 연결 여부가 주어짐",
    examples: [
      "i번 컴퓨터와 j번 컴퓨터가 연결되어 있으면 grid[i][j] = 1이에요",
      "도시 사이 직항이 있으면 1, 없으면 0인 표가 주어져요",
    ],
    suspects: ["graph-representation", "dfs", "bfs"],
    patterns: ["adjacency-matrix"],
    reason:
      "표 자체가 인접 행렬이에요. 두 노드의 연결 여부는 O(1)에 알 수 있고, 이웃을 모두 보려면 한 줄(행)을 훑어요.",
    caution: "노드가 많고 간선이 적다면 인접 리스트로 바꾸는 편이 빨라요.",
    strength: "medium",
  },
  {
    id: "sig-tree-structure",
    phrase: "부모와 자식 / 사이클 없이 모두 연결된 N−1개의 길",
    examples: ["각 직원의 직속 상사가 주어져요", "마을 N개가 N−1개의 길로 모두 이어져 있어요"],
    suspects: ["dfs", "graph-representation"],
    patterns: ["tree-traversal", "edge-list-conversion"],
    reason: "트리에서는 한 노드의 답을 자식들의 답으로 계산할 수 있어요. DFS로 내려갔다가 돌아오면서 모으면 돼요.",
    caution: "간선 목록으로 주어지면 방향이 없으니, 부모로 되돌아가지 않도록 방문 표시를 하세요.",
    strength: "medium",
  },
  {
    id: "sig-connected-group",
    phrase: "이어진 덩어리 / 구역 / 그룹의 개수·크기",
    examples: [
      "상하좌우로 맞닿은 칸들은 하나의 구역이에요",
      "서로 연결된 컴퓨터는 같은 네트워크에 속해요",
      "친구의 친구도 같은 모임이에요",
    ],
    suspects: ["dfs", "bfs"],
    patterns: ["connected-components", "grid-flood-fill"],
    reason:
      "한 지점에서 출발해 닿을 수 있는 곳을 전부 칠하면 덩어리 하나가 끝나요. 목적이 '전부 방문'이라 DFS와 BFS 모두 가능하고, 보통 코드가 짧은 DFS를 먼저 떠올려요.",
    caution: "'가장 가까운', '최소 몇 번'이 함께 나오면 거리를 재야 하므로 BFS를 의심하세요.",
    strength: "strong",
  },
  {
    id: "sig-grid-neighbors",
    phrase: "격자(지도) + 상하좌우 이동",
    examples: ["N×M 크기의 지도가 주어져요", "상하좌우로 인접한 칸으로만 이동할 수 있어요"],
    suspects: ["dfs", "bfs"],
    patterns: ["grid-flood-fill", "grid-shortest-path"],
    reason:
      "격자는 '칸 = 노드, 붙어 있는 칸 = 간선'인 그래프예요. 인접 리스트를 따로 만들지 않고 방향 배열 (-1,0), (1,0), (0,-1), (0,1)로 이웃을 구해요.",
    caution: "대각선 포함 여부(4방향 / 8방향)를 문제에서 반드시 확인하세요.",
    strength: "medium",
  },
  {
    id: "sig-path-exists",
    phrase: "갈 수 있는지 / 경로가 있는지 / 순환이 있는지",
    examples: ["출발점에서 도착점까지 갈 수 있나요?", "선수 과목 관계에 순환이 있는지 확인하세요"],
    suspects: ["dfs"],
    patterns: ["path-existence", "cycle-detection"],
    reason:
      "'있다/없다'만 알면 되니 한 길로 끝까지 가 보는 DFS가 간단해요. 재귀 호출 중인 노드를 다시 만나면 순환이에요.",
    strength: "medium",
  },
  {
    id: "sig-shortest-steps",
    phrase: "최단 거리 / 최소 횟수 / 가장 빨리",
    examples: ["도착점까지 최소 몇 칸을 지나야 하나요?", "최소 몇 번 만에 목표 상태가 되나요?"],
    suspects: ["bfs"],
    patterns: ["shortest-path-unweighted", "grid-shortest-path", "state-space-bfs"],
    reason: "BFS는 가까운 곳부터 한 겹씩 넓혀 가므로, 처음 도착한 순간의 거리가 곧 최단 거리예요.",
    caution: "간선마다 비용(가중치)이 다르면 BFS가 아니라 다익스트라예요.",
    strength: "strong",
  },
  {
    id: "sig-spread-simultaneous",
    phrase: "여러 곳에서 동시에 퍼짐 / 며칠 뒤에",
    examples: ["익은 토마토가 하루마다 옆 칸으로 퍼져요", "불이 1분마다 상하좌우로 번져요"],
    suspects: ["bfs"],
    patterns: ["multi-source-bfs", "level-order"],
    reason: "시작점을 전부 큐에 넣고 BFS를 한 번 돌리면, 퍼지는 시간이 곧 BFS의 층(거리)이에요.",
    strength: "strong",
  },
  {
    id: "sig-all-cases",
    phrase: "모든 경우의 수 / 가능한 조합을 전부",
    examples: ["가능한 모든 순서를 출력하세요", "합이 K가 되는 부분집합을 모두 찾으세요"],
    suspects: ["backtracking"],
    patterns: ["permutation", "combination", "subset"],
    reason: "하나씩 고르고, 끝까지 가면 기록하고, 되돌아와 다음 선택지를 고르는 흐름이 백트래킹이에요.",
    caution: "경우의 수가 너무 많다면 가지치기나 DP가 필요해요.",
    strength: "strong",
  },
  {
    id: "sig-placement-constraint",
    phrase: "서로 부딪히지 않게 배치하는 모든 방법",
    examples: [
      "서로 공격할 수 없게 말을 놓는 방법의 수를 구하세요",
      "이웃한 지역은 다른 색이 되도록 칠하는 방법의 수를 구하세요",
    ],
    suspects: ["backtracking"],
    patterns: ["constraint-pruning"],
    reason: "하나씩 놓아 보다가 규칙을 어기는 순간 그 가지를 버리고 되돌아가요. 끝까지 도착한 배치만 셉니다.",
    caution: "놓을 때마다 전체 판을 다시 검사하지 말고, 사용 중인 열·대각선 같은 정보를 따로 기록해 O(1)에 확인하세요.",
    strength: "strong",
  },
  {
    id: "sig-small-n",
    phrase: "입력 크기가 아주 작음 (N ≤ 10 정도)",
    examples: ["1 ≤ N ≤ 8", "재료는 최대 10개예요"],
    suspects: ["backtracking"],
    patterns: ["constraint-pruning", "permutation"],
    reason: "N이 작으면 모든 경우를 다 만들어 봐도 시간 안에 끝나요. 완전 탐색을 허락한다는 힌트예요.",
    strength: "weak",
  },
  {
    id: "sig-seen-before",
    phrase: "이미 나온 적 있는지 / 중복인지 확인",
    examples: ["같은 이름이 두 번 이상 나오는지 확인하세요", "처음 보는 단어일 때만 기록하세요"],
    suspects: ["hash"],
    patterns: ["existence-check"],
    reason:
      "리스트에서 있는지 찾으면 매번 처음부터 훑어야 해서 O(N)이에요. 본 것을 해시(set·dict)에 넣어 두면 있는지 확인이 평균 O(1)이에요.",
    caution: "N이 수십 개뿐이면 리스트로 찾아도 충분해요. N이 수만 이상이면 꼭 해시를 쓰세요.",
    strength: "strong",
  },
  {
    id: "sig-count-each",
    phrase: "각각 몇 번 나왔는지 / 가장 많이 나온 것",
    examples: ["투표에서 가장 많은 표를 받은 후보는 누구인가요?", "각 과일이 몇 개씩 있는지 세어 주세요"],
    suspects: ["hash"],
    patterns: ["frequency-count"],
    reason: "이름(키)마다 개수(값)를 붙여 두는 dict가 딱 맞아요. 한 번 훑으면서 count[x] += 1만 하면 돼요.",
    caution: "키가 0~100 같은 작은 정수라면 길이 101짜리 배열로 세도 돼요.",
    strength: "strong",
  },
  {
    id: "sig-pair-target",
    phrase: "합(차)이 K가 되는 두 수 / 짝이 되는 것 찾기",
    examples: ["더해서 target이 되는 두 수의 위치를 구하세요", "차이가 정확히 K인 쌍은 몇 개인가요?"],
    suspects: ["hash"],
    patterns: ["complement-lookup"],
    reason:
      "모든 쌍을 보면 O(N²)이에요. 지금 수 x에게 필요한 짝은 K - x로 정해져 있으니, 지금까지 본 수를 해시에 넣어 두고 짝이 있는지 O(1)에 물어봐요.",
    caution: "배열이 이미 정렬돼 있으면 양쪽 끝에서 좁혀 오는 두 포인터로도 풀 수 있어요.",
    strength: "strong",
  },
  {
    id: "sig-group-same",
    phrase: "같은 종류끼리 묶기 / 글자 구성이 같은 단어",
    examples: ["애너그램끼리 묶어 주세요", "같은 반 학생끼리 이름을 모아 주세요"],
    suspects: ["hash"],
    patterns: ["group-by-key"],
    reason: "묶는 기준을 키로 만들고(예: 글자를 정렬한 문자열), dict[키]에 리스트로 모으면 한 번에 묶여요.",
    strength: "medium",
  },
  {
    id: "sig-subarray-sum",
    phrase: "연속 구간의 합이 정확히 K인 개수",
    examples: ["합이 K인 연속 구간은 몇 개인가요?", "연속한 날들의 합이 0이 되는 구간을 세세요"],
    suspects: ["hash"],
    patterns: ["prefix-sum-hash"],
    reason:
      "구간 합 = 지금까지의 누적 합 − 앞의 어떤 누적 합이에요. 지금까지 나온 누적 합의 개수를 dict에 세어 두면 필요한 앞쪽 누적 합이 몇 번 있었는지 바로 알 수 있어요.",
    caution: "음수가 없고 '합이 K 이상' 같은 조건이면 두 포인터(슬라이딩 윈도우)가 더 간단할 수 있어요.",
    strength: "medium",
  },
  {
    id: "sig-order-rule",
    phrase: "~순으로, 같으면 ~순으로 나열",
    examples: [
      "점수가 높은 순으로, 점수가 같으면 이름 순으로 출력하세요",
      "길이가 짧은 단어부터, 길이가 같으면 사전 순으로",
    ],
    suspects: ["sorting"],
    patterns: ["custom-order"],
    reason:
      "기준을 차례로 비교하는 정렬 키를 만들면 한 번의 정렬로 끝나요. 직접 정렬을 짤 필요 없이 기준만 정확히 적으면 돼요.",
    caution: "내림차순 기준은 숫자에 −를 붙이거나 비교 함수의 순서를 바꿔요.",
    strength: "strong",
  },
  {
    id: "sig-neighbor-after-sort",
    phrase: "가장 가까운 두 값 / K번째로 큰 값 / 중앙값",
    examples: ["차이가 가장 작은 두 수를 구하세요", "세 번째로 무거운 도토리는 몇 g인가요?"],
    suspects: ["sorting"],
    patterns: ["sort-then-scan"],
    reason: "정렬하면 크기가 비슷한 값이 옆에 붙고, K번째 값은 K번째 자리에 와요. 모든 쌍을 볼 필요가 없어져요.",
    caution: "정렬은 O(N log N)이에요. 딱 한 번만 필요한 최댓값·최솟값은 한 번 훑는 O(N)으로 충분해요.",
    strength: "medium",
  },
  {
    id: "sig-intervals",
    phrase: "시작과 끝이 있는 구간이 겹치는지",
    examples: ["겹치는 예약을 하나로 합쳐 주세요", "동시에 진행 중인 회의가 가장 많을 때는 몇 개인가요?"],
    suspects: ["sorting"],
    patterns: ["interval-sweep"],
    reason: "구간을 시작 시각 순으로 정렬하면, 겹치는 구간은 반드시 이웃해요. 한 번 훑으면서 합치거나 셀 수 있어요.",
    strength: "strong",
  },
  {
    id: "sig-small-value-range",
    phrase: "값의 범위가 작음 (0~100 점수, 알파벳 등)",
    examples: ["점수는 0점부터 100점 사이예요", "나이는 1살부터 120살까지예요"],
    suspects: ["sorting"],
    patterns: ["counting-sort"],
    reason: "값의 종류가 적으면 값마다 개수를 세어 두는 계수 정렬로 O(N + 값의 범위)에 정렬할 수 있어요.",
    strength: "weak",
  },
  {
    id: "sig-inversions",
    phrase: "순서가 뒤바뀐 쌍의 수 / 옆끼리 바꾸는 횟수",
    examples: [
      "i < j인데 a[i] > a[j]인 쌍은 몇 개인가요?",
      "옆 사람끼리 자리를 바꿔 키 순서로 서려면 몇 번 바꿔야 하나요?",
    ],
    suspects: ["sorting"],
    patterns: ["merge-step"],
    reason:
      "병합 정렬로 두 절반을 합칠 때, 오른쪽 값이 먼저 나가면 왼쪽에 남은 값의 수만큼 뒤바뀐 쌍이 생겨요. O(N log N)에 셀 수 있어요.",
    caution: "N이 수천 이하면 이중 반복문으로 세도 괜찮아요.",
    strength: "medium",
  },
  {
    id: "sig-sorted-many-queries",
    phrase: "정렬된 목록 + 질문이 아주 많음",
    examples: [
      "정렬된 번호 10만 개에서 질문 10만 개마다 위치를 찾으세요",
      "점수가 q점 이상인 학생 수를 질문마다 답하세요",
    ],
    suspects: ["binary-search"],
    patterns: ["exact-search", "range-count"],
    reason: "질문마다 처음부터 훑으면 O(N·Q)예요. 정렬돼 있으면 반씩 버리며 O(log N)에 찾아서 전체 O(Q log N)이에요.",
    caution: "위치가 필요 없고 '있는지'만 물으면 해시(set)가 더 간단해요.",
    strength: "strong",
  },
  {
    id: "sig-first-true",
    phrase: "처음으로 ~ 이상이 되는 위치 / 경계",
    examples: ["x 이상인 첫 번째 위치를 구하세요", "처음으로 비가 온 날은 며칠째인가요?"],
    suspects: ["binary-search"],
    patterns: ["boundary-search"],
    reason: "앞쪽은 전부 '아니오', 뒤쪽은 전부 '예'로 나뉘면 그 경계는 이분 탐색으로 찾을 수 있어요.",
    strength: "medium",
  },
  {
    id: "sig-max-min-answer",
    phrase: "~할 수 있는 최대 / 최소 값 (최대의 최소, 최소의 최대)",
    examples: ["적어도 K개를 만들 수 있는 최대 길이는?", "가장 큰 묶음의 합을 최소로 하려면?"],
    suspects: ["binary-search"],
    patterns: ["parametric-search"],
    reason:
      "답을 직접 구하긴 어렵지만 '답이 X일 때 가능한가?'는 쉽게 확인할 수 있고, 가능/불가능이 한 번만 바뀌면 X를 이분 탐색해요.",
    caution: "X가 커질수록 가능 → 불가능(또는 반대)으로 한 번만 바뀌는지 먼저 확인하세요.",
    strength: "strong",
  },
  {
    id: "sig-huge-range",
    phrase: "답의 범위가 엄청 큼 (10억, 10¹⁸)",
    examples: ["1 ≤ 시간 ≤ 1,000,000,000,000", "길이는 최대 2³¹ − 1이에요"],
    suspects: ["binary-search"],
    patterns: ["parametric-search"],
    reason: "답 후보를 하나씩 다 확인할 수 없을 만큼 크면, 반씩 줄여 약 30~60번만 확인하는 이분 탐색을 떠올려요.",
    strength: "weak",
  },
];

const SIGNALS_BY_ID = new Map(SIGNALS.map((signal) => [signal.id, signal]));

export function getSignal(id: string): PatternSignal | undefined {
  return SIGNALS_BY_ID.get(id);
}
