import type { Problem } from "@/types/content";

export const heapBestProjects: Problem = {
  id: "c:heap-best-projects",
  slug: "heap-best-projects",
  source: "curated",
  topic: "heap",
  level: 4,
  title: "도토리 가게 키우기",
  summary: "지금 할 수 있는 일을 힙에 모으고, 그중 이익이 가장 큰 일부터 해요",
  statement: [
    "노디의 도토리 가게는 처음에 도토리가 `w`개 있어요. 할 수 있는 일 N개가 있고, i번 일은 도토리를 `need[i]`개 **이상** 가지고 있어야 시작할 수 있고, 끝내면 이익 `profit[i]`개를 얻어요 (가진 도토리는 줄지 않아요).",
    "",
    "일은 **최대 k개**까지, 한 번에 하나씩 해요. 마지막에 가질 수 있는 도토리의 **최대 개수**를 반환해 주세요. 답이 21억을 넘을 수 있어요 (Java는 `long`).",
  ].join("\n"),
  inputFormat: "`k`: 할 수 있는 일 수, `w`: 처음 도토리, `profit`, `need`: 일별 이익과 필요한 도토리예요.",
  outputFormat: "마지막 도토리의 최대 개수",
  constraints: [
    "1 ≤ N ≤ 100,000, 1 ≤ k ≤ 100,000",
    "0 ≤ w ≤ 1,000,000,000",
    "0 ≤ profit[i] ≤ 10,000, 0 ≤ need[i] ≤ 1,000,000,000",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "할 수 있는 일 수" },
      { name: "w", type: { python: "int", javascript: "number", java: "int" }, description: "처음 도토리" },
      {
        name: "profit",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "일별 이익",
      },
      {
        name: "need",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "일별 필요한 도토리",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "long" }, description: "최대 도토리" },
  },
  starterCode: {
    python: ["def solution(k, w, profit, need):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(k, w, profit, need) {", "  let answer = 0;", "  return answer;", "}", ""].join(
      "\n",
    ),
    java: [
      "class Solution {",
      "    public long solution(int k, int w, int[] profit, int[] need) {",
      "        long answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [2, 0, [1, 2, 3], [0, 1, 1]],
      expected: 4,
      explanation: "0번(+1)으로 1개가 되고, 2번(+3)으로 4개예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [3, 0, [1, 2, 3], [0, 1, 2]],
      expected: 6,
      explanation: "0번 → 1, 1번 → 3, 2번 → 6이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1, 0, [5], [1]],
      expected: 0,
      failureNote: "시작도 못 해서 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [1, 5, [1, 10, 3], [0, 5, 6]],
      expected: 15,
      failureNote: "지금 할 수 있는 일(0번, 1번) 중 이익이 큰 1번을 해요. 15예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [5, 1, [2, 3], [1, 1]],
      expected: 6,
      failureNote: "일이 2개뿐이라 6에서 멈춰요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [
        100000,
        0,
        Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 10000) + 1),
        Array.from({ length: 100000 }, (_, i) => (i * 104729) % 200000),
      ],
      expected: 1,
      failureNote: "일 10만 개예요. 매번 할 수 있는 일을 처음부터 찾으면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "'지금 **할 수 있는** 일 중 **이익이 가장 큰** 것'을 반복 → 조건이 풀리는 일을 넣는 **최대 힙** + 그리디예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 일을 필요한 도토리 순으로 정렬해요.",
        "2. k번 반복: 지금 도토리로 시작할 수 있게 된 일들의 이익을 **최대 힙**에 넣어요.",
        "3. 힙이 비었으면 더 할 일이 없어요. 아니면 가장 큰 이익을 꺼내 더해요.",
        "",
        "도토리는 늘기만 해서, 한 번 할 수 있게 된 일은 계속 할 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "jobs = (need, profit)을 need 순으로 정렬; i = 0",
        "repeat k번:",
        "    while i < n and jobs[i].need <= w: 최대 힙에 profit 넣기; i += 1",
        "    if 힙이 비었으면: break",
        "    w += pop()",
        "return w",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["이익이 가장 큰 일을 하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for _ in range(k):",
            "    while i < n and jobs[i][0] <= w:",
            "        heapq.heappush(h, -jobs[i][1])",
            "        i += 1",
            "    if not h:",
            "        break",
            "    w += ______",
          ].join("\n"),
          javascript: [
            "for (let t = 0; t < k; t++) {",
            "  while (i < n && jobs[i][0] <= w) h.push(jobs[i++][1]);",
            "  if (!h.size) break;",
            "  w += ______;",
            "}",
          ].join("\n"),
          java: [
            "for (int t = 0; t < k; t++) {",
            "    while (i < n && jobs[i][0] <= money) h.offer(jobs[i++][1]);",
            "    if (h.isEmpty()) break;",
            "    money += ______;",
            "}",
          ].join("\n"),
        },
        caption: "도토리는 21억을 넘을 수 있어서 long으로 들고 다녀요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["heap-scheduling"],
  signalIds: ["sig-repeated-min", "sig-greedy-local-best"],
  estimatedMinutes: 20,
  xp: 40,
};
