import type { Problem } from "@/types/content";

export const heapFewestRefuels: Problem = {
  id: "c:heap-fewest-refuels",
  slug: "heap-fewest-refuels",
  source: "curated",
  topic: "heap",
  level: 5,
  title: "가장 적게 들르는 샘물",
  summary: "지나온 샘물을 힙에 모아 두고, 물이 모자랄 때 가장 큰 샘물에 들른 셈 쳐요",
  statement: [
    "노디가 물통에 물 `start`만큼을 담고 출발해 거리 `goal`까지 걸어가요. 거리 1을 걸을 때마다 물이 1씩 줄어요.",
    "",
    "길 위에 샘물이 `springs[i] = [위치, 물의 양]`으로 있어요 (위치 순서로 주어져요). 샘물에 들르면 그 양만큼 물을 채울 수 있어요 (물통은 아무리 많이 담아도 넘치지 않아요).",
    "",
    "`goal`까지 가려면 **최소 몇 번** 샘물에 들러야 하는지 반환해 주세요. 갈 수 없으면 `-1`이에요. 물이 딱 0일 때 도착하거나 샘물에 닿아도 괜찮아요.",
  ].join("\n"),
  inputFormat: "`goal`: 목적지 거리, `start`: 처음 물, `springs`: 위치 순서의 `[위치, 물의 양]` 목록이에요.",
  outputFormat: "최소 들르는 횟수 (불가능하면 -1)",
  constraints: [
    "1 ≤ goal, start ≤ 1,000,000,000",
    "0 ≤ springs의 길이 ≤ 100,000",
    "0 < 위치 < goal, 위치는 오름차순, 1 ≤ 물의 양 ≤ 1,000,000,000",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "goal", type: { python: "int", javascript: "number", java: "int" }, description: "목적지 거리" },
      { name: "start", type: { python: "int", javascript: "number", java: "int" }, description: "처음 물" },
      {
        name: "springs",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "샘물",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 들르는 횟수" },
  },
  starterCode: {
    python: ["def solution(goal, start, springs):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(goal, start, springs) {", "  let answer = 0;", "  return answer;", "}", ""].join(
      "\n",
    ),
    java: [
      "class Solution {",
      "    public int solution(int goal, int start, int[][] springs) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [1, 1, []],
      expected: 0,
      explanation: "처음 물로 바로 도착해요. 0번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [
        100,
        10,
        [
          [10, 60],
          [20, 30],
          [30, 30],
          [60, 40],
        ],
      ],
      expected: 2,
      explanation: "10에서 60을 채우고(물 60), 60에서 40을 채워 100까지 가요. 2번이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [100, 1, [[10, 100]]],
      expected: -1,
      failureNote: "첫 샘물까지도 못 가요. −1이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        100,
        50,
        [
          [25, 25],
          [50, 50],
        ],
      ],
      expected: 1,
      failureNote: "딱 0이 될 때 50에 닿아 50을 채우면 도착해요. 1번이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        100,
        25,
        [
          [25, 25],
          [50, 25],
          [75, 25],
        ],
      ],
      expected: 3,
      failureNote: "셋 다 들러야 딱 도착해요. 3번이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [1000000000, 10000, Array.from({ length: 100000 }, (_, i) => [(i + 1) * 10000, ((i * 7919) % 20000) + 1])],
      expected: -1,
      failureNote: "샘물 10만 개예요. 들를 곳을 모두 고르는 건 불가능해요. (Java는 물의 합을 long으로)",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "들를 곳을 **나중에 정해도** 돼요: 지나온 샘물을 모아 두고, 물이 모자랄 때 그중 **가장 큰** 샘물에 들렀던 셈 쳐요 → **최대 힙** + 그리디예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 샘물을 위치 순으로 보며, 거기까지 가는 데 물이 모자라면: 지나온 샘물 중 가장 큰 것을 힙에서 꺼내 채우고 횟수 +1. 힙이 비면 −1",
        "2. 도착한 샘물은 힙에 넣어요 (아직 들르지 않은 후보).",
        "3. 마지막으로 goal까지도 같은 방법으로 채워요.",
        "",
        "많이 채워 주는 샘물을 고를수록 들르는 횟수가 줄어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "fuel = start, stops = 0, h = 빈 최대 힙",
        "for pos, water in springs + [(goal, 0)]:",
        "    while fuel < pos:",
        "        if 힙이 비었으면: return -1",
        "        fuel += pop(); stops += 1",
        "    push(water)",
        "return stops",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["물이 모자랄 때의 처리예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while fuel < pos:",
            "    if not h:",
            "        return -1",
            "    fuel += ______",
            "    stops += 1",
          ].join("\n"),
          javascript: [
            "while (fuel < pos) {",
            "  if (!h.size) return -1;",
            "  fuel += ______;",
            "  stops++;",
            "}",
          ].join("\n"),
          java: [
            "while (fuel < pos) {",
            "    if (h.isEmpty()) return -1;",
            "    fuel += ______;",
            "    stops++;",
            "}",
          ].join("\n"),
        },
        caption: "물의 합은 21억을 넘을 수 있어서 fuel은 long이에요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["heap-scheduling"],
  signalIds: ["sig-repeated-min", "sig-greedy-local-best"],
  estimatedMinutes: 30,
  xp: 50,
};
