import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[2, 7, 4, 1, 8, 1]],
    expected: 1,
    explanation: "8·7 → 1, 4·2 → 2, 2·1 → 1, 1·1 → 없음, 남은 1이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[3]],
    expected: 3,
    explanation: "하나면 그대로 3이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[5, 5]],
    expected: 0,
    failureNote: "같은 무게라 둘 다 부서져 0이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [[10, 4]],
    expected: 6,
    failureNote: "6이 남아요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [[9, 3, 3]],
    expected: 3,
    failureNote: "9·3 → 6이 다시 들어가서 6·3 → 3이에요. 남은 조각을 다시 넣고 가장 무거운 둘을 다시 골라야 해요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 1000) + 1)],
    expected: 0,
    failureNote: "돌 10만 개예요. 매번 정렬하면 O(N² log N)이라 시간 초과예요.",
  },
]);

export const heapLastStone: Problem = {
  id: "c:heap-last-stone",
  slug: "heap-last-stone",
  source: "curated",
  topic: "heap",
  level: 1,
  title: "돌멩이 부딪히기",
  summary: "가장 무거운 두 돌을 최대 힙에서 꺼내 부딪히고, 남은 조각을 다시 넣어요",
  statement: [
    "돌멩이 무게 `stones`가 있어요. 매번 **가장 무거운 두 돌**을 골라 부딪혀요.",
    "",
    "- 두 무게가 같으면 둘 다 부서져 없어져요.",
    "- 다르면 가벼운 돌은 부서지고, 무거운 돌은 `무거운 − 가벼운` 무게로 남아요.",
    "",
    "돌이 하나 이하가 될 때까지 반복해요. 마지막 돌의 무게를 반환해 주세요. 남은 돌이 없으면 0이에요.",
  ].join("\n"),
  inputFormat: "`stones`: 돌멩이 무게예요.",
  outputFormat: "마지막 돌의 무게 (없으면 0)",
  constraints: ["1 ≤ stones의 길이 ≤ 100,000", "1 ≤ 무게 ≤ 1,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "stones",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "돌멩이 무게",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "마지막 무게" },
  },
  starterCode: {
    python: ["def solution(stones):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(stones) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] stones) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["'가장 **큰** 두 개를 꺼내고, 결과를 다시 넣기'를 반복 → **최대 힙**이에요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 모든 돌을 최대 힙에 넣어요. (Python은 `-무게`로 넣으면 최소 힙이 최대 힙처럼 동작해요)",
        "2. 두 개 이상 남은 동안: 가장 무거운 두 개를 꺼내고, 다르면 차이를 다시 넣어요.",
        "3. 남은 게 있으면 그 무게, 없으면 0",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "h = 최대 힙(stones)",
        "while 크기 >= 2:",
        "    a = pop(); b = pop()     # a >= b",
        "    if a != b: push(a - b)",
        "return 남은 값 또는 0",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["부딪힌 뒤 남은 조각을 넣는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "h = [-s for s in stones]",
            "heapq.heapify(h)",
            "while len(h) >= 2:",
            "    a = -heapq.heappop(h)",
            "    b = -heapq.heappop(h)",
            "    if a != b:",
            "        heapq.heappush(h, ______)",
          ].join("\n"),
          javascript: [
            "const h = new Heap((a, b) => a > b);   // 최대 힙",
            "for (const s of stones) h.push(s);",
            "while (h.size >= 2) {",
            "  const a = h.pop(), b = h.pop();",
            "  if (a !== b) h.push(______);",
            "}",
          ].join("\n"),
          java: [
            "PriorityQueue<Integer> h = new PriorityQueue<>(Collections.reverseOrder());",
            "for (int s : stones) h.offer(s);",
            "while (h.size() >= 2) {",
            "    int a = h.poll(), b = h.poll();",
            "    if (a != b) h.offer(______);",
            "}",
          ].join("\n"),
        },
        caption: "Collections.reverseOrder()를 주면 가장 큰 값부터 나오는 최대 힙이에요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["repeated-min"],
  signalIds: ["sig-repeated-min"],
  estimatedMinutes: 10,
  xp: 10,
};
