import type { Problem } from "@/types/content";

export const heapNearlySorted: Problem = {
  id: "c:heap-nearly-sorted",
  slug: "heap-nearly-sorted",
  source: "curated",
  topic: "heap",
  level: 2,
  title: "조금 흐트러진 줄 정리",
  summary: "제자리에서 k칸 이내로만 벗어났으니, 크기 k+1인 힙이면 충분해요",
  statement: [
    "번호표 줄 `nums`가 조금 흐트러졌어요. 각 번호표는 정렬했을 때의 자리에서 **최대 k칸**까지만 벗어나 있어요.",
    "",
    "줄을 오름차순으로 정리해 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`nums`: 흐트러진 번호표, `k`: 벗어난 최대 칸 수예요.",
  outputFormat: "정렬한 목록",
  constraints: ["1 ≤ nums의 길이 ≤ 100,000", "0 ≤ k < nums의 길이", "각 값은 정렬된 자리에서 k칸 이내에 있어요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "nums",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "흐트러진 번호표",
      },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "벗어난 최대 칸 수" },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "정렬한 목록" },
  },
  starterCode: {
    python: ["def solution(nums, k):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(nums, k) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] nums, int k) {",
      "        int[] answer = new int[nums.length];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[2, 1, 4, 3, 6, 5], 1],
      expected: [1, 2, 3, 4, 5, 6],
      explanation: "이웃끼리만 바뀌었어요: [1, 2, 3, 4, 5, 6].",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[1, 2, 3], 0],
      expected: [1, 2, 3],
      explanation: "k = 0이면 이미 정렬돼 있어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [[3, 1, 2], 2],
      expected: [1, 2, 3],
      failureNote: "[1, 2, 3]이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[9], 0],
      expected: [9],
      failureNote: "하나뿐이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 2, 1, 1], 2],
      expected: [1, 1, 2, 2],
      failureNote: "같은 번호도 있어요: [1, 1, 2, 2].",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => i + ((i * 7) % 5) * 2 - ((i * 3) % 4)), 12],
      expected: Array.from({ length: 100000 }, (_, i) => i + ((i * 7) % 5) * 2 - ((i * 3) % 4)).sort((a, b) => a - b),
      failureNote: "10만 개, k = 12예요. 크기 13인 힙으로 O(N log k)예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "i번 자리에 올 값은 앞쪽 **k+1개 안**에 반드시 있어요 → 크기 k+1인 **최소 힙**에서 가장 작은 것을 꺼내면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 값을 하나씩 힙에 넣어요.",
        "2. 힙 크기가 k+1이 되면 가장 작은 값을 꺼내 결과에 붙여요.",
        "3. 다 넣은 뒤 남은 값을 모두 꺼내 붙여요.",
        "",
        "힙이 작아서(k+1) 한 번에 log k만 들어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "h = [], result = []",
        "for x in nums:",
        "    push(x)",
        "    if 크기 > k: result에 pop() 추가",
        "while h: result에 pop() 추가",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["꺼낼 때를 정하는 조건이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for x in nums:",
            "    heapq.heappush(h, x)",
            "    if ______:",
            "        result.append(heapq.heappop(h))",
          ].join("\n"),
          javascript: ["for (const x of nums) {", "  h.push(x);", "  if (______) result.push(h.pop());", "}"].join(
            "\n",
          ),
          java: [
            "for (int x : nums) {",
            "    h.offer(x);",
            "    if (______) answer[w++] = h.poll();",
            "}",
            "while (!h.isEmpty()) answer[w++] = h.poll();",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["repeated-min"],
  signalIds: ["sig-repeated-min"],
  estimatedMinutes: 12,
  xp: 20,
};
