import type { Problem } from "@/types/content";

export const heapTopWords: Problem = {
  id: "c:heap-top-words",
  slug: "heap-top-words",
  source: "curated",
  topic: "heap",
  level: 3,
  title: "가장 많이 들은 단어 K개",
  summary: "단어별로 세고, (많은 순, 사전 순) 기준으로 K개를 꺼내요",
  statement: [
    "노디가 숲에서 들은 단어 목록 `words`가 있어요. **가장 많이 들은 단어 k개**를 많이 들은 순서로 반환해 주세요.",
    "",
    "들은 횟수가 같으면 **사전 순으로 앞선** 단어가 먼저예요.",
  ].join("\n"),
  inputFormat: "`words`: 들은 단어들, `k`: 고를 개수예요.",
  outputFormat: "단어 k개 (많이 들은 순)",
  constraints: ["1 ≤ words의 길이 ≤ 100,000", "1 ≤ k ≤ 서로 다른 단어 수", "단어는 영어 소문자·숫자 1~10글자예요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "words",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "들은 단어",
      },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "고를 개수" },
    ],
    returns: { type: { python: "list[str]", javascript: "string[]", java: "List<String>" }, description: "단어 k개" },
  },
  starterCode: {
    python: ["def solution(words, k):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(words, k) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<String> solution(String[] words, int k) {",
      "        List<String> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["leaf", "sun", "leaf", "moss", "sun", "leaf"], 2],
      expected: ["leaf", "sun"],
      explanation: "leaf 3번, sun 2번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [["b", "a", "c", "b", "a"], 2],
      expected: ["a", "b"],
      explanation: "a와 b가 2번씩 같아서 사전 순으로 a, b예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["solo"], 1],
      expected: ["solo"],
      failureNote: "하나뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [["z", "y", "x"], 3],
      expected: ["x", "y", "z"],
      failureNote: "모두 1번이면 사전 순: x, y, z예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [["a", "b", "b", "c", "c", "c"], 1],
      expected: ["c"],
      failureNote: "c 하나예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => "w" + ((i * i) % 97).toString(36)), 10],
      expected: ["w17", "w18", "w1b", "w1c", "w1e", "w1h", "w1i", "w1p", "w1q", "w1s"],
      failureNote: "단어 10만 개예요. 단어마다 count()로 세면 느려요. dict로 세고 힙으로 골라요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["'**가장 많은 K개**' → 개수 세기(해시) + **상위 K개**(힙)예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. dict로 단어별 횟수를 세요.",
        "2. `(-횟수, 단어)`를 최소 힙에 넣어요. 횟수가 많을수록, 같으면 사전 순으로 앞설수록 먼저 나와요.",
        "3. k번 꺼내요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "count = 단어별 횟수",
        "h = [(-c, w) for w, c in count]를 힙으로",
        "return [pop()의 w for k번]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["힙에 넣을 값이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "h = [______ for w, c in count.items()]",
            "heapq.heapify(h)",
            "return [heapq.heappop(h)[1] for _ in range(k)]",
          ].join("\n"),
          javascript: [
            "const h = new Heap((a, b) => a[0] !== b[0] ? a[0] > b[0] : a[1] < b[1]);",
            "for (const [w, c] of count) h.push(______);",
          ].join("\n"),
          java: [
            "PriorityQueue<String> h = new PriorityQueue<>((a, b) -> {",
            "    int ca = count.get(a), cb = count.get(b);",
            "    return ca != cb ? cb - ca : ______;",
            "});",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["top-k"],
  signalIds: ["sig-top-k", "sig-count-each"],
  estimatedMinutes: 15,
  xp: 30,
};
