import type { Problem } from "@/types/content";

export const dijkstraCountRoutes: Problem = {
  id: "c:dijkstra-count-routes",
  slug: "dijkstra-count-routes",
  source: "curated",
  topic: "dijkstra",
  level: 4,
  title: "가장 빠른 길은 몇 가지?",
  summary: "거리가 같아지면 길의 수를 더하고, 줄어들면 새로 적어요",
  statement: [
    "마을 `n`개와 양방향 길 `roads`(`[a, b, t]`: `t`분)가 있어요.",
    "",
    "0번 마을에서 `n - 1`번 마을까지 **가장 빨리 가는 길이 몇 가지**인지 반환해 주세요. 지나는 길이 하나라도 다르면 다른 길이에요. 수가 클 수 있으니 `1,000,000,007`로 나눈 나머지를 반환해요.",
    "",
    "갈 수 없으면 `0`이에요.",
  ].join("\n"),
  inputFormat: "`n`: 마을 수, `roads`: `[a, b, t]` 길 목록이에요.",
  outputFormat: "가장 빠른 길의 수를 1,000,000,007로 나눈 나머지",
  constraints: [
    "2 ≤ n ≤ 10,000",
    "0 ≤ roads의 길이 ≤ 30,000",
    "0 ≤ a, b < n, a ≠ b",
    "1 ≤ t ≤ 1,000",
    "같은 두 마을을 잇는 길이 여러 개일 수 있어요",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "마을 수" },
      {
        name: "roads",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "[a, b, 비용] 양방향 길",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "가장 빠른 길의 수" },
  },
  starterCode: {
    python: ["def solution(n, roads):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, roads) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] roads) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        4,
        [
          [0, 1, 1],
          [0, 2, 1],
          [1, 3, 1],
          [2, 3, 1],
        ],
      ],
      expected: 2,
      explanation: "0 → 1 → 3과 0 → 2 → 3, 둘 다 2분이라 2가지예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [2, [[0, 1, 5]]],
      expected: 1,
      explanation: "길이 하나뿐이라 1가지예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        4,
        [
          [0, 3, 3],
          [0, 1, 1],
          [1, 2, 1],
          [2, 3, 1],
        ],
      ],
      expected: 2,
      failureNote: "길 하나로 3분, 길 셋으로도 3분이에요. 지나는 길 수가 달라도 시간이 같으면 모두 세서 2가지예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [3, [[0, 1, 1]]],
      expected: 0,
      failureNote: "2번 마을에 갈 수 없어서 0이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        2,
        [
          [0, 1, 2],
          [0, 1, 2],
        ],
      ],
      expected: 2,
      failureNote: "같은 두 마을을 잇는 2분 길이 두 개라 2가지예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        82,
        [
          [0, 1, 1],
          [0, 2, 1],
          ...Array.from({ length: 39 }, (_, j) => [
            [1 + 2 * j, 3 + 2 * j, 1],
            [1 + 2 * j, 4 + 2 * j, 1],
            [2 + 2 * j, 3 + 2 * j, 1],
            [2 + 2 * j, 4 + 2 * j, 1],
          ]).flat(),
          [79, 81, 1],
          [80, 81, 1],
        ],
      ],
      expected: 511620083,
      failureNote: "갈림길이 40번 이어져서 2⁴⁰가지예요. 나머지를 구하지 않으면 수가 너무 커져요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        10000,
        [
          ...Array.from({ length: 9900 }, (_, i) => [i, i + 100, 1]),
          ...Array.from({ length: 10000 }, (_, i) => i)
            .filter((i) => i % 100 !== 99)
            .map((i) => [i, i + 1, 1]),
        ],
      ],
      expected: 690285631,
      failureNote: "100 × 100 격자 모양 길이에요. 오른쪽·아래로만 가는 모든 길이 가장 빨라서 경우의 수가 아주 커요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["비용이 다른 길의 최단 시간 → 다익스트라. 거기에 최단 경로의 **개수**를 함께 세요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`ways[v]` = 0번에서 v번까지 가장 빠른 길의 수예요. `ways[0] = 1`로 시작해요.",
        "",
        "v번에서 w번으로 가는 길을 볼 때:",
        "- `d + t < dist[w]`: 더 빠른 길을 찾았어요 → `ways[w] = ways[v]` (예전 수는 버려요)",
        "- `d + t == dist[w]`: 똑같이 빠른 길이 또 있어요 → `ways[w] += ways[v]`",
        "",
        "v번을 힙에서 꺼낼 때는 v보다 가까운 마을이 모두 끝나 있어서 `ways[v]`가 이미 완성돼 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "ways[0] = 1",
        "d, v = pop(heap);  if d > dist[v]: continue",
        "for (w, t) in graph[v]:",
        "    if d + t < dist[w]: dist[w] = d + t;  ways[w] = ways[v];  push",
        "    elif d + t == dist[w]: ways[w] = (ways[w] + ways[v]) % MOD",
        "return ways[n - 1]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["거리가 같을 때 길의 수를 더하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "if d + t < dist[w]:",
            "    dist[w] = d + t",
            "    ways[w] = ways[v]",
            "    heapq.heappush(heap, (dist[w], w))",
            "elif d + t == dist[w]:",
            "    ways[w] = ______",
          ].join("\n"),
          javascript: [
            "if (d + t < dist[w]) {",
            "  dist[w] = d + t;",
            "  ways[w] = ways[v];",
            "  heap.push([dist[w], w]);",
            "} else if (d + t === dist[w]) {",
            "  ways[w] = ______;",
            "}",
          ].join("\n"),
          java: [
            "if (d + x[1] < dist[w]) {",
            "    dist[w] = d + x[1];",
            "    ways[w] = ways[v];",
            "    heap.offer(new long[] {dist[w], w});",
            "} else if (d + x[1] == dist[w]) {",
            "    ways[w] = ______;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["weighted-shortest-path"],
  signalIds: ["sig-weighted-route"],
  estimatedMinutes: 22,
  xp: 40,
};
