import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const dijkstraDeliveryTime: Problem = {
  id: "c:dijkstra-delivery-time",
  slug: "dijkstra-delivery-time",
  source: "curated",
  topic: "dijkstra",
  level: 1,
  title: "택배가 도착하는 시간",
  summary: "0번 창고에서 모든 마을까지 가장 빨리 가는 시간을 구해요",
  statement: [
    "숲속 마을 `n`개가 `0`번부터 `n - 1`번까지 있어요. 택배 창고는 **0번 마을**에 있어요.",
    "",
    "`roads`의 `[a, b, t]`는 a번과 b번 마을을 잇는 길이고, 어느 쪽으로 가든 `t`분 걸려요.",
    "",
    "각 마을까지 택배가 **가장 빨리** 도착하는 시간을 번호 순서대로 담아 반환해 주세요. 갈 수 없는 마을은 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`n`: 마을 수, `roads`: `[a, b, t]` 길 목록이에요.",
  outputFormat: "마을마다 가장 빠른 도착 시간 (갈 수 없으면 -1)",
  constraints: [
    "1 ≤ n ≤ 10,000",
    "0 ≤ roads의 길이 ≤ 30,000",
    "0 ≤ a, b < n, a ≠ b",
    "1 ≤ t ≤ 1,000",
    "같은 두 마을을 잇는 길이 여러 개일 수 있어요",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "마을 수" },
      {
        name: "roads",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "[a, b, 시간] 양방향 길",
      },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "int[]" },
      description: "마을별 가장 빠른 도착 시간",
    },
  },
  starterCode: {
    python: ["def solution(n, roads):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, roads) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int n, int[][] roads) {",
      "        int[] answer = new int[n];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        4,
        [
          [0, 1, 10],
          [0, 2, 2],
          [2, 1, 3],
          [1, 3, 1],
        ],
      ],
      expected: [0, 5, 2, 6],
      explanation: "1번은 곧장 10분보다 2번을 거쳐 2 + 3 = 5분이 빨라요. 3번은 5 + 1 = 6분이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [3, [[0, 1, 4]]],
      expected: [0, 4, -1],
      explanation: "2번 마을로 가는 길이 없어서 -1이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1, []],
      expected: [0],
      failureNote: "창고 마을 하나뿐이면 [0]이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        3,
        [
          [0, 1, 9],
          [0, 1, 3],
          [1, 2, 3],
        ],
      ],
      expected: [0, 3, 6],
      failureNote: "0번과 1번 사이 길이 두 개예요. 더 짧은 3분 길을 써서 [0, 3, 6]이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        5,
        [
          [0, 4, 100],
          [0, 1, 1],
          [1, 2, 1],
          [2, 3, 1],
          [3, 4, 1],
        ],
      ],
      expected: [0, 1, 2, 3, 4],
      failureNote: "4번은 길 하나(100분)보다 길 네 개(4분)가 빨라요. 지나는 길 수를 세는 BFS로는 틀려요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [
        10000,
        [
          ...Array.from({ length: 9999 }, (_, i) => [i, i + 1, 2]),
          ...Array.from({ length: 9998 }, (_, i) => [i, i + 2, 5]),
          ...Array.from({ length: 9997 }, (_, i) => [i, i + 3, 7]),
        ],
      ],
      expected: Array.from({ length: 10000 }, (_, i) => 2 * i),
      failureNote: "마을 1만 개, 길 3만 개예요. 가장 가까운 마을을 매번 전부 훑어 찾으면 느려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["길마다 걸리는 시간이 **달라요**. 한 곳에서 모든 곳까지 가장 빠른 시간 → **다익스트라**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 길을 양쪽 방향으로 인접 리스트에 담아요.",
        "2. `dist[0] = 0`, 나머지는 ∞로 두고 힙에 `(0, 0)`을 넣어요.",
        "3. 힙에서 가장 가까운 마을을 꺼내 이웃의 시간을 줄여요. 꺼낸 시간이 `dist`보다 크면 오래된 기록이라 버려요.",
        "4. 끝까지 ∞인 마을은 -1로 바꿔요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = [∞] * n;  dist[0] = 0",
        "heap = [(0, 0)]",
        "while heap:",
        "    d, v = pop(heap)",
        "    if d > dist[v]: continue",
        "    for (w, t) in graph[v]:",
        "        if d + t < dist[w]: dist[w] = d + t; push(heap, (dist[w], w))",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["이웃의 시간을 줄이는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for w, t in graph[v]:",
            "    if ______:",
            "        dist[w] = d + t",
            "        heapq.heappush(heap, (dist[w], w))",
          ].join("\n"),
          javascript: [
            "for (const [w, t] of graph[v]) {",
            "  if (______) {",
            "    dist[w] = d + t;",
            "    heap.push([dist[w], w]);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int[] e : graph.get(v)) {",
            "    if (______) {",
            "        dist[e[0]] = d + e[1];",
            "        heap.offer(new long[] {dist[e[0]], e[0]});",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "힙에는 {거리, 마을}을 long[]로 넣고, 거리로 비교해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["weighted-shortest-path"],
  signalIds: ["sig-weighted-route"],
  visualization: {
    presets: [
      problemPreset(
        "dijkstra-delivery-time-ex1",
        "dijkstra-basic",
        "돌아가는 길이 더 빠를 때",
        "1번은 처음에 10분으로 적히지만, 2번을 확정한 뒤 5분으로 줄어들어요.",
        [
          4,
          [
            [0, 1, 10],
            [0, 2, 2],
            [2, 1, 3],
            [1, 3, 1],
          ],
          0,
        ],
      ),
    ],
  },
  estimatedMinutes: 15,
  xp: 10,
};
