import type { Problem } from "@/types/content";

export const dijkstraWallBreak: Problem = {
  id: "c:dijkstra-wall-break",
  slug: "dijkstra-wall-break",
  source: "curated",
  topic: "dijkstra",
  level: 5,
  title: "바위를 가장 적게 치우기",
  summary: "빈칸은 0, 바위는 1인 비용으로 보고 치운 바위 수의 최솟값을 구해요",
  statement: [
    "`grid`는 동굴 지도예요. `'0'`은 빈칸, `'1'`은 바위가 막고 있는 칸이에요.",
    "",
    "왼쪽 위 칸에서 오른쪽 아래 칸까지 **상하좌우**로 한 칸씩 움직여요. 바위 칸에 들어가려면 그 바위를 치워야 해요.",
    "",
    "치워야 하는 바위 수의 **최솟값**을 반환해 주세요. 출발 칸과 도착 칸은 빈칸이에요.",
  ].join("\n"),
  inputFormat: "`grid`: 한 줄을 문자열 하나로 쓴 지도예요.",
  outputFormat: "치우는 바위 수의 최솟값",
  constraints: ["1 ≤ 줄 수, 칸 수 ≤ 200", "칸은 '0' 또는 '1'", "출발 칸과 도착 칸은 '0'"],
  signature: {
    name: "solution",
    params: [
      {
        name: "grid",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "동굴 지도",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "치우는 바위 수의 최솟값" },
  },
  starterCode: {
    python: ["def solution(grid):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(grid) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String[] grid) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["011", "111", "110"]],
      expected: 3,
      explanation: "어느 길로 가든 바위를 3개는 치워야 해요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [["0"]],
      expected: 0,
      explanation: "출발 칸이 곧 도착 칸이라 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["00", "00"]],
      expected: 0,
      failureNote: "바위가 없어서 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [["010", "111", "010"]],
      expected: 2,
      failureNote: "어느 쪽으로 돌아도 바위 2개를 치워요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [["0000000", "1111110", "0000000", "0111111", "0000000"]],
      expected: 0,
      failureNote: "빙 돌아가면 바위를 하나도 안 치워도 돼서 0이에요. 칸 수가 가장 적은 길이 답이 아니에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 200 }, (_, r) =>
          Array.from({ length: 200 }, (_, c) =>
            (r === 0 && c === 0) || (r === 199 && c === 199) ? "0" : (r * 7 + c * 13 + r * c) % 5 < 2 ? "1" : "0",
          ).join(""),
        ),
      ],
      expected: 0,
      failureNote: "200 × 200 = 40,000칸이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "칸마다 비용(빈칸 0, 바위 1)이 있고 합의 최솟값을 구해요 → 격자 위의 **다익스트라**예요.",
        "",
        "비용이 0과 1뿐이면 덱으로 하는 **0-1 BFS**도 쓸 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `broken[r][c]` = 그 칸까지 치운 바위 수의 최솟값이에요.",
        "2. 이웃 칸으로 가는 비용은 그 칸이 바위면 1, 빈칸이면 0이에요.",
        "3. 힙에서 가장 적게 치운 칸부터 꺼내요. 도착 칸을 꺼내면 끝이에요.",
        "",
        "비용 0인 간선이 있어도 음수가 아니라서 다익스트라가 그대로 통해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "broken[0][0] = 0;  heap = [(0, 0, 0)]",
        "while heap:",
        "    b, r, c = pop(heap)",
        "    if (r, c)가 도착 칸: return b",
        "    for 이웃 (nr, nc):",
        "        nb = b + (grid[nr][nc] == '1')",
        "        if nb < broken[nr][nc]: 줄이고 push",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["이웃 칸까지 치운 바위 수를 계산하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "nb = b + (1 if ______ else 0)",
            "if nb < broken[nr][nc]:",
            "    broken[nr][nc] = nb",
            "    heapq.heappush(heap, (nb, nr, nc))",
          ].join("\n"),
          javascript: [
            "const nb = b + (______ ? 1 : 0);",
            "if (nb < broken[nr][nc]) {",
            "  broken[nr][nc] = nb;",
            "  heap.push([nb, nr, nc]);",
            "}",
          ].join("\n"),
          java: [
            "int nb = b + (______ ? 1 : 0);",
            "if (nb < broken[nr][nc]) {",
            "    broken[nr][nc] = nb;",
            "    heap.offer(new int[] {nb, nr, nc});",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["weighted-shortest-path"],
  signalIds: ["sig-weighted-route"],
  estimatedMinutes: 20,
  xp: 50,
};
