import type { Problem } from "@/types/content";

export const backtrackingCoinFlips: Problem = {
  id: "c:backtracking-coin-flips",
  slug: "backtracking-coin-flips",
  source: "curated",
  topic: "backtracking",
  level: 1,
  title: "동전 던지기 기록장",
  summary: "동전을 n번 던질 때 나올 수 있는 모든 기록을 만들어요",
  statement: [
    "노디는 동전을 `n`번 던지고 결과를 기록장에 적어요. 앞면은 `'H'`, 뒷면은 `'T'`예요. 예를 들어 3번 던져 앞, 앞, 뒤가 나오면 `\"HHT\"`라고 적어요.",
    "",
    "나올 수 있는 **모든 기록**을 사전 순서(`'H'`가 `'T'`보다 앞)로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 던지는 횟수예요.",
  outputFormat: "길이 n인 'H'/'T' 문자열들의 리스트 (사전 순)",
  constraints: ["1 ≤ n ≤ 10"],
  signature: {
    name: "solution",
    params: [{ name: "n", type: { python: "int", javascript: "number" }, description: "던지는 횟수" }],
    returns: { type: { python: "list[str]", javascript: "string[]" }, description: "모든 기록 (사전 순)" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [2],
      expected: ["HH", "HT", "TH", "TT"],
      explanation: "HH, HT, TH, TT 네 가지예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [3],
      expected: ["HHH", "HHT", "HTH", "HTT", "THH", "THT", "TTH", "TTT"],
      explanation: "매번 H 또는 T를 고르니 2 × 2 × 2 = 8가지예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1],
      expected: ["H", "T"],
      failureNote: "한 번 던지면 H, T 두 가지예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [4],
      expected: [
        "HHHH",
        "HHHT",
        "HHTH",
        "HHTT",
        "HTHH",
        "HTHT",
        "HTTH",
        "HTTT",
        "THHH",
        "THHT",
        "THTH",
        "THTT",
        "TTHH",
        "TTHT",
        "TTTH",
        "TTTT",
      ],
      failureNote: "16가지예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [5],
      // prettier-ignore
      expected: ["HHHHH","HHHHT","HHHTH","HHHTT","HHTHH","HHTHT","HHTTH","HHTTT","HTHHH","HTHHT","HTHTH","HTHTT","HTTHH","HTTHT","HTTTH","HTTTT","THHHH","THHHT","THHTH","THHTT","THTHH","THTHT","THTTH","THTTT","TTHHH","TTHHT","TTHTH","TTHTT","TTTHH","TTTHT","TTTTH","TTTTT"],
      failureNote: "32가지예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [10],
      expected: Array.from({ length: 1024 }, (_, i) =>
        i.toString(2).padStart(10, "0").replace(/0/g, "H").replace(/1/g, "T"),
      ),
      failureNote: "10번 던지면 1,024가지예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"나올 수 있는 **모든** 경우"를 만들어요 → **백트래킹**이에요.',
        "",
        "한 번 던질 때마다 H와 T라는 **갈림길**이 있어요. 갈림길마다 하나를 골라 끝까지 가 보고, 돌아와서 다른 쪽을 골라요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "지금까지 적은 기록을 `path`에 담아요.",
        "",
        "1. `path`의 길이가 n이면 기록 하나 완성 → 결과에 추가하고 돌아가요.",
        "2. 아니면 H를 **골라서**(`path`에 추가) 더 깊이 들어갔다가, 돌아오면 **되돌리고**(`path`에서 빼기) T를 골라 같은 일을 해요.",
        "",
        "H를 먼저 고르니 결과가 저절로 사전 순이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "pick():",
        "    if len(path) == n:",
        "        result에 path를 문자열로 추가",
        "        return",
        "    for face in ['H', 'T']:",
        "        path에 face 추가     # 고르기",
        "        pick()               # 더 깊이",
        "        path에서 마지막 빼기  # 되돌리기",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["고르기 → 더 깊이 → 되돌리기예요."].join("\n"),
      code: {
        code: {
          python: ['for face in "HT":', "    path.append(face)", "    pick()", "    ______"].join("\n"),
          javascript: ['for (const face of ["H", "T"]) {', "  path.push(face);", "  pick();", "  ______;", "}"].join(
            "\n",
          ),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["subset"],
  signalIds: ["sig-all-cases", "sig-small-n"],
  estimatedMinutes: 10,
  xp: 10,
};
