import type { Problem } from "@/types/content";

export const backtrackingFlowerSudoku: Problem = {
  id: "c:backtracking-flower-sudoku",
  slug: "backtracking-flower-sudoku",
  source: "curated",
  topic: "backtracking",
  level: 5,
  title: "6×6 꽃밭 스도쿠",
  summary: "가로·세로·2×3 화단마다 꽃 1~6이 한 번씩 오도록 빈칸을 채워요",
  statement: [
    "노디의 꽃밭은 6×6칸이고, 칸마다 1번부터 6번까지 꽃 중 하나를 심어요. 꽃밭은 **2줄 × 3칸짜리 화단 6개**로 나뉘어 있어요 (위에서부터 두 줄씩, 왼쪽 세 칸과 오른쪽 세 칸).",
    "",
    "규칙은 이래요.",
    "",
    "- 가로 한 줄에 1~6번 꽃이 한 번씩",
    "- 세로 한 줄에 1~6번 꽃이 한 번씩",
    "- 2×3 화단 하나에 1~6번 꽃이 한 번씩",
    "",
    "몇 칸은 이미 심어져 있고, 빈칸은 `.`이에요. 규칙을 지키며 빈칸을 채운 꽃밭을 반환해 주세요. 채우는 방법은 **딱 한 가지**만 있어요.",
  ].join("\n"),
  inputFormat: "`garden`: 길이 6인 문자열 6개. 각 문자는 `1`~`6` 또는 `.`이에요.",
  outputFormat: "빈칸을 채운 꽃밭 (길이 6인 문자열 6개)",
  constraints: ["garden은 6줄, 각 줄은 6글자예요", "채우는 방법은 항상 딱 한 가지예요"],
  signature: {
    name: "solution",
    params: [
      {
        name: "garden",
        type: { python: "list[str]", javascript: "string[]", java: "String[]" },
        description: "꽃밭 (빈칸은 .)",
      },
    ],
    returns: { type: { python: "list[str]", javascript: "string[]", java: "String[]" }, description: "채운 꽃밭" },
  },
  starterCode: {
    python: ["def solution(garden):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(garden) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public String[] solution(String[] garden) {",
      "        String[] answer = new String[6];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["16...2", "54..61", ".35214", "421.3.", "2.6.4.", "31452."]],
      expected: ["163452", "542361", "635214", "421635", "256143", "314526"],
      explanation:
        "빈칸 12개예요. 예를 들어 첫 줄 셋째 칸은 가로줄에 1, 6, 2가 있고 화단에 5, 4도 있어서 3만 들어가요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [["514623", "263415", "325146", "641532", "152364", "436.51"]],
      expected: ["514623", "263415", "325146", "641532", "152364", "436251"],
      explanation: "빈칸이 하나뿐이에요. 마지막 줄에 없는 2를 넣어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["163452", "542361", "635214", "421635", "256143", "314526"]],
      expected: ["163452", "542361", "635214", "421635", "256143", "314526"],
      failureNote: "이미 다 채워져 있으면 그대로 돌려줘요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [["5.....", ".2.541", ".3..2.", "6.23.5", ".5.43.", ".6...2"]],
      expected: ["514263", "326541", "135624", "642315", "251436", "463152"],
      failureNote: "빈칸 20개예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[".4.26.", "..3...", "3..52.", ".....4", "....51", "..53.."]],
      expected: ["541263", "623415", "314526", "256134", "432651", "165342"],
      failureNote: "빈칸 24개예요. 한 칸에 들어갈 수 있는 꽃이 여러 개라 넣어 보고 막히면 되돌려야 해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [["..2...", "35.2..", ".4..51", "...32.", "..4...", ".....5"]],
      expected: ["462513", "351246", "243651", "615324", "534162", "126435"],
      failureNote: "빈칸 25개예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [["..2...", "....16", "....43", "6.....", ".3..5.", "5....."]],
      expected: ["162435", "354216", "215643", "643521", "436152", "521364"],
      failureNote: "빈칸 27개, 처음 심어진 꽃이 9개뿐이에요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "빈칸마다 꽃을 **넣어 보고**, 규칙에 어긋나면 **되돌려** 다른 꽃을 넣어요 → 제약 조건을 지키는 **백트래킹**이에요.",
        "",
        "규칙을 어기는 순간 그 가지를 버리니 가지치기가 저절로 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 꽃밭을 고칠 수 있는 2차원 리스트로 바꾸고, 빈칸 좌표 목록을 만들어요.",
        "2. `fill(k)`: k번째 빈칸에 1~6을 차례로 넣어 봐요. 가로줄·세로줄·화단에 **같은 꽃이 없을 때만** 넣고 `fill(k + 1)`로 넘어가요.",
        "3. `fill(k + 1)`이 성공하면 그대로 성공. 실패하면 그 칸을 다시 빈칸으로 **되돌리고** 다음 꽃을 넣어 봐요.",
        "4. k가 빈칸 수와 같아지면 모두 채운 거예요.",
        "",
        "(r, c)가 속한 화단의 왼쪽 위 칸은 `(r // 2 × 2, c // 3 × 3)`이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function fill(k):",
        "    if k == 빈칸 수: return true",
        "    (r, c) = k번째 빈칸",
        "    for 꽃 in 1..6:",
        "        if 꽃을 (r, c)에 놓아도 규칙에 맞으면:",
        "            grid[r][c] = 꽃",
        "            if fill(k + 1): return true",
        "            grid[r][c] = '.'           # 되돌리기",
        "    return false",
        "fill(0)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["화단 안에 같은 꽃이 있는지 보는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "def fits(r, c, flower):",
            "    for i in range(6):",
            "        if grid[r][i] == flower or grid[i][c] == flower:",
            "            return False",
            "    top, left = ______",
            "    for i in range(top, top + 2):",
            "        for j in range(left, left + 3):",
            "            if grid[i][j] == flower:",
            "                return False",
            "    return True",
          ].join("\n"),
          javascript: [
            "function fits(r, c, flower) {",
            "  for (let i = 0; i < 6; i++) {",
            "    if (grid[r][i] === flower || grid[i][c] === flower) return false;",
            "  }",
            "  const [top, left] = ______;",
            "  for (let i = top; i < top + 2; i++) {",
            "    for (let j = left; j < left + 3; j++) if (grid[i][j] === flower) return false;",
            "  }",
            "  return true;",
            "}",
          ].join("\n"),
          java: [
            "boolean fits(int r, int c, char flower) {",
            "    for (int i = 0; i < 6; i++) {",
            "        if (grid[r][i] == flower || grid[i][c] == flower) return false;",
            "    }",
            "    int top = ______, left = c / 3 * 3;",
            "    for (int i = top; i < top + 2; i++) {",
            "        for (int j = left; j < left + 3; j++) if (grid[i][j] == flower) return false;",
            "    }",
            "    return true;",
            "}",
          ].join("\n"),
        },
        caption: "Java는 문자열을 바꿀 수 없어서 char[][]로 바꿔 채운 뒤 다시 문자열로 만들어요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["constraint-pruning"],
  signalIds: ["sig-placement-constraint", "sig-small-n"],
  estimatedMinutes: 30,
  xp: 50,
};
