import type { Problem } from "@/types/content";

export const backtrackingGiftWeights: Problem = {
  id: "c:backtracking-gift-weights",
  slug: "backtracking-gift-weights",
  source: "curated",
  topic: "backtracking",
  level: 4,
  title: "선물 상자 무게 맞추기",
  summary: "넘치는 순간 멈추는 가지치기로 무게 합이 딱 맞는 조합을 세요",
  statement: [
    "택배 기사 노디는 선물 상자들을 한 번에 실어 **정확히 `limit`kg**을 맞추려고 해요. 상자 `n`개의 무게 `weights`는 **모두 달라요**. 상자마다 싣거나 안 싣거나를 정해요.",
    "",
    "실은 상자의 무게 합이 정확히 `limit`이 되는 방법의 수를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`weights`: 서로 다른 양의 정수 리스트, `limit`: 맞출 무게예요.",
  outputFormat: "방법의 수 (정수)",
  constraints: ["1 ≤ n ≤ 30", "1 ≤ weights[i] ≤ 1,000", "1 ≤ limit ≤ 1,000", "답은 100,000 이하예요."],
  signature: {
    name: "solution",
    params: [
      { name: "weights", type: { python: "list[int]", javascript: "number[]" }, description: "상자 무게" },
      { name: "limit", type: { python: "int", javascript: "number" }, description: "맞출 무게" },
    ],
    returns: { type: { python: "int", javascript: "number" }, description: "방법의 수" },
  },
  starterCode: {
    python: ["def solution(weights, limit):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(weights, limit) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[2, 3, 5, 7], 10],
      expected: 2,
      explanation: "{3, 7}, {2, 3, 5} 두 가지예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "basic",
      args: [[9, 4, 6, 1], 10],
      expected: 2,
      explanation: "{9, 1}, {4, 6} 두 가지예요. 무게가 섞여 있어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5], 5],
      expected: 1,
      failureNote: "상자 하나로 딱 맞아요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[20, 30], 10],
      expected: 0,
      failureNote: "모든 상자가 너무 무거워요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3, 4, 5, 6], 6],
      expected: 4,
      failureNote: "{6}, {1, 5}, {2, 4}, {1, 2, 3}으로 4가지예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 30 }, (_, i) => 30 - i), 30],
      expected: 296,
      failureNote: "상자 30개예요. 싣기/안 싣기를 모두 따지면 2^30 ≈ 10억 가지라, 넘치는 가지를 잘라야 해요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 30 }, (_, i) => 2 * i + 3), 100],
      expected: 1221,
      failureNote: "3, 5, 7, … 61kg 상자 30개로 100kg을 맞춰요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 30 }, (_, i) => 1000 - i * 7), 999],
      expected: 0,
      failureNote: "무거운 상자 30개예요. 두 개만 실어도 넘쳐요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "싣는다 / 안 싣는다 → **부분집합** 백트래킹이에요. 그런데 n ≤ 30이라 2^30 ≈ 10억 가지를 다 보면 시간 초과예요.",
        "",
        "답이 될 수 없는 가지를 **일찍 자르는 가지치기**가 필요해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 무게를 **오름차순 정렬**해요.",
        "2. `go(start, total)`: start번 상자부터 하나를 골라 싣는 조합 방식으로 탐색해요.",
        "3. i번 상자를 실으면 `total + weights[i]`가 limit을 **넘는 순간 `break`** 해요. 정렬했으니 뒤의 상자는 더 무거워서 모두 넘쳐요.",
        "4. 합이 정확히 limit이 되면 1가지를 세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "weights 오름차순 정렬",
        "go(start, total):",
        "    count = 0",
        "    for i in start..n-1:",
        "        w = total + weights[i]",
        "        if w > limit: break      # 가지치기",
        "        if w == limit: count += 1",
        "        else: count += go(i + 1, w)",
        "    return count",
        "return go(0, 0)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["가지를 자르는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(start, n):",
            "    w = total + weights[i]",
            "    if w > limit:",
            "        ______",
            "    if w == limit:",
            "        count += 1",
            "    else:",
            "        count += go(i + 1, w)",
          ].join("\n"),
          javascript: [
            "for (let i = start; i < n; i += 1) {",
            "  const w = total + weights[i];",
            "  if (w > limit) ______;",
            "  if (w === limit) count += 1;",
            "  else count += go(i + 1, w);",
            "}",
          ].join("\n"),
        },
        caption: "정렬해 두었기 때문에 continue가 아니라 반복 자체를 끝내도 돼요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["constraint-pruning", "subset"],
  signalIds: ["sig-all-cases"],
  estimatedMinutes: 25,
  xp: 40,
};
