import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [4],
    expected: 2,
    explanation: "4×4에는 2가지 방법이 있어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [3],
    expected: 0,
    explanation: "3×3에서는 어떻게 놓아도 겹쳐서 0가지예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [1],
    expected: 1,
    failureNote: "한 칸에 한 대, 1가지예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [2],
    expected: 0,
    failureNote: "0가지예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [5],
    expected: 10,
    failureNote: "10가지예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [6],
    expected: 4,
    failureNote: "4가지예요. n이 커진다고 늘기만 하는 건 아니에요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [9],
    expected: 352,
    failureNote: "9×9 전시장이에요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [10],
    expected: 724,
    failureNote: "10×10 전시장이에요. 100칸 중 10칸을 고르는 모든 경우(약 17조)를 보면 끝나지 않아요.",
  },
]);

export const backtrackingGuardRobots: Problem = {
  id: "c:backtracking-guard-robots",
  slug: "backtracking-guard-robots",
  source: "curated",
  topic: "backtracking",
  level: 5,
  title: "경비 로봇 배치",
  summary: "서로의 감시선이 겹치지 않게 n×n 전시장에 로봇 n대를 놓는 방법을 세요",
  statement: [
    "노디 박물관의 전시장은 `n × n` 칸이에요. 경비 로봇 `n`대를 칸마다 하나씩만 놓을 수 있어요.",
    "",
    "로봇은 **가로, 세로, 두 대각선** 방향으로 끝까지 감시선을 쏴요. 한 로봇이 다른 로봇의 감시선 위에 있으면 서로 신호가 꼬여요.",
    "",
    "어떤 두 로봇도 같은 가로줄, 세로줄, 대각선에 있지 않도록 `n`대를 모두 놓는 **방법의 수**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 전시장 크기이자 로봇 수예요.",
  outputFormat: "방법의 수 (정수)",
  constraints: ["1 ≤ n ≤ 10"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "전시장 크기 = 로봇 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "방법의 수" },
  },
  starterCode: {
    python: ["def solution(n):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"서로 겹치지 않게 **배치**하는 방법의 수" → **제약 조건이 있는 백트래킹**이에요.',
        "",
        "가로줄마다 로봇이 정확히 한 대씩 있어야 하니, **한 줄씩** 로봇의 열을 정해 나가요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`place(row)`: row번째 줄에 로봇을 놓을 차례예요.",
        "",
        "- 열 c가 이미 쓰였는지: `cols`",
        "- 같은 ↘ 대각선은 `row - c`가 같아요: `diag1`",
        "- 같은 ↙ 대각선은 `row + c`가 같아요: `diag2`",
        "",
        "세 집합 중 하나라도 걸리면 **그 칸은 건너뛰어요** (가지치기). 괜찮으면 기록하고 `place(row + 1)`, 돌아오면 기록을 지워요. row == n이면 방법 하나 완성이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "place(row):",
        "    if row == n: return 1",
        "    count = 0",
        "    for c in 0..n-1:",
        "        if c in cols or row-c in diag1 or row+c in diag2: continue",
        "        세 집합에 추가",
        "        count += place(row + 1)",
        "        세 집합에서 제거",
        "    return count",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["감시선이 겹치는지 검사하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for c in range(n):",
            "    if c in cols or (row - c) in diag1 or ______:",
            "        continue",
            "    cols.add(c); diag1.add(row - c); diag2.add(row + c)",
            "    count += place(row + 1)",
            "    cols.remove(c); diag1.remove(row - c); diag2.remove(row + c)",
          ].join("\n"),
          javascript: [
            "for (let c = 0; c < n; c += 1) {",
            "  if (cols.has(c) || diag1.has(row - c) || ______) continue;",
            "  cols.add(c); diag1.add(row - c); diag2.add(row + c);",
            "  count += place(row + 1);",
            "  cols.delete(c); diag1.delete(row - c); diag2.delete(row + c);",
            "}",
          ].join("\n"),
          java: [
            "for (int c = 0; c < n; c++) {",
            "    if (cols[c] || diag1[row - c + n] || ______) continue;",
            "    cols[c] = diag1[row - c + n] = diag2[row + c] = true;",
            "    count += place(row + 1);",
            "    cols[c] = diag1[row - c + n] = diag2[row + c] = false;",
            "}",
          ].join("\n"),
        },
        caption:
          "Java에서는 집합 대신 boolean 배열을 써도 돼요. row - c는 음수가 될 수 있어서 n을 더해 칸 번호로 써요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["constraint-pruning"],
  signalIds: ["sig-placement-constraint", "sig-small-n"],
  estimatedMinutes: 30,
  xp: 50,
};
