import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [["NODI", "XOAB", "YZCD"], "NODI"],
    expected: true,
    explanation: "첫 줄을 그대로 걸으면 돼요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [["AB", "CD"], "ABA"],
    expected: false,
    explanation: "A로 돌아가려면 이미 밟은 칸을 다시 밟아야 해서 안 돼요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "basic",
    args: [["BE", "DN"], "BEND"],
    expected: true,
    failureNote: "ㄷ자로 꺾어 걸어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [["Q"], "Q"],
    expected: true,
    failureNote: "한 칸짜리 글자판이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "edge",
    args: [["AB", "CD"], "ABDCAB"],
    expected: false,
    failureNote: "이름이 글자판 칸 수보다 길어요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [["CAT", "AXT", "TAC"], "CATTC"],
    expected: true,
    failureNote: "C에서 아래쪽 A로 먼저 가 보면 T 다음이 막혀요. 되돌아가 오른쪽 A로 가야 C-A-T-T-C를 찾아요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "basic",
    args: [["SEE", "SES", "EES"], "SEES"],
    expected: true,
    failureNote: "같은 글자가 많아도 칸마다 한 번씩만 밟아요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [["AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA"], "AAAAAAAAAB"],
    expected: false,
    failureNote: "글자판에 B가 없어요. 글자 수를 먼저 세어 보면 바로 알 수 있어요.",
  },
  {
    id: "hid-7",
    visibility: "hidden",
    purpose: "stress",
    args: [["AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAB"], "AAAAAAAAAB"],
    expected: true,
    failureNote: "A가 가득한 글자판 구석에 B가 하나 있어요. 여러 갈래를 되돌아가며 찾아야 해요.",
  },
]);

export const backtrackingLetterBoard: Problem = {
  id: "c:backtracking-letter-board",
  slug: "backtracking-letter-board",
  source: "curated",
  topic: "backtracking",
  level: 4,
  title: "글자판에서 이름 찾기",
  summary: "이웃한 칸을 이어 가며 글자판에서 이름을 만들 수 있는지 찾아요",
  statement: [
    "놀이터 바닥에 대문자 글자판 `board`가 그려져 있어요. 노디는 글자판 위를 걸으며 친구 이름 `word`를 만들고 싶어요.",
    "",
    "- 아무 칸에서나 시작할 수 있어요.",
    "- 한 걸음에 **상하좌우로 이웃한 칸**으로만 갈 수 있어요.",
    "- **같은 칸은 두 번 밟을 수 없어요**.",
    "",
    "밟은 칸의 글자를 순서대로 이어 `word`를 만들 수 있으면 `true`, 없으면 `false`를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`board`: 대문자로 된 문자열 리스트, `word`: 만들고 싶은 이름이에요.",
  outputFormat: "`true` 또는 `false`",
  constraints: [
    "1 ≤ 줄 수, 줄 길이 ≤ 5",
    "모든 줄의 길이가 같아요",
    "1 ≤ word의 길이 ≤ 10",
    "모든 글자는 영어 대문자예요",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "board", type: { python: "list[str]", javascript: "string[]", java: "String[]" }, description: "글자판" },
      { name: "word", type: { python: "str", javascript: "string", java: "String" }, description: "만들고 싶은 이름" },
    ],
    returns: { type: { python: "bool", javascript: "boolean", java: "boolean" }, description: "이름을 만들 수 있는지" },
  },
  starterCode: {
    python: ["def solution(board, word):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(board, word) {", "  let answer = false;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public boolean solution(String[] board, String word) {",
      "        boolean answer = false;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "칸을 하나씩 **골라 밟아 보고**, 글자가 안 맞으면 **되돌아와** 다른 칸을 밟아요 → **백트래킹**이에요.",
        "",
        "글자가 맞지 않는 순간 그 길을 버리는 게 **가지치기**예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `search(r, c, k)`: (r, c) 칸이 word의 k번째 글자와 같은지 보고, 이어서 k+1번째 글자를 이웃에서 찾아요.",
        "2. 글자가 다르면 바로 `false`(가지치기). k가 마지막 글자면 `true`.",
        "3. 이웃으로 가기 전에 지금 칸을 **밟음**으로 표시하고, 이웃을 모두 해 본 뒤에는 **안 밟음으로 되돌려요**. 다른 시작점에서는 이 칸을 다시 밟을 수 있어야 하니까요.",
        "4. 모든 칸을 시작점으로 해 봐요.",
        "",
        "추가 가지치기: word의 글자 수가 글자판에 있는 글자 수보다 많으면 탐색할 필요도 없이 `false`예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "function search(r, c, k):",
        "    if board[r][c] != word[k]: return false",
        "    if k == len(word) - 1: return true",
        "    used[r][c] = true",
        "    for 상하좌우 (nr, nc):",
        "        안이고 안 밟았고 search(nr, nc, k + 1)이면:",
        "            used[r][c] = false, return true",
        "    used[r][c] = false            # 되돌리기",
        "    return false",
        "",
        "return 어떤 칸 (r, c)에서든 search(r, c, 0)이 true인지",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["탐색을 마치고 칸을 되돌리는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "used[r][c] = True",
            "for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):",
            "    nr, nc = r + dr, c + dc",
            "    if 0 <= nr < rows and 0 <= nc < cols and not used[nr][nc] and search(nr, nc, k + 1):",
            "        used[r][c] = False",
            "        return True",
            "______   # 되돌리기",
            "return False",
          ].join("\n"),
          javascript: [
            "used[r][c] = true;",
            "for (const [dr, dc] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {",
            "  const nr = r + dr, nc = c + dc;",
            "  if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && !used[nr][nc] && search(nr, nc, k + 1)) {",
            "    used[r][c] = false;",
            "    return true;",
            "  }",
            "}",
            "______; // 되돌리기",
            "return false;",
          ].join("\n"),
          java: [
            "used[r][c] = true;",
            "for (int[] d : DIRS) {",
            "    int nr = r + d[0], nc = c + d[1];",
            "    if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && !used[nr][nc] && search(nr, nc, k + 1)) {",
            "        used[r][c] = false;",
            "        return true;",
            "    }",
            "}",
            "______;   // 되돌리기",
            "return false;",
          ].join("\n"),
        },
        caption: "Java는 int[26]에 글자판 글자 수를 세고, 이름의 글자마다 하나씩 빼서 모자라면 바로 false예요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["constraint-pruning"],
  signalIds: ["sig-all-cases", "sig-small-n"],
  estimatedMinutes: 20,
  xp: 40,
};
