import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      3,
      [
        [0, 1],
        [1, 2],
      ],
      3,
    ],
    expected: 12,
    explanation: "0번 3가지, 1번은 0번과 달라야 해서 2가지, 2번도 1번과 달라야 해서 2가지. 3 × 2 × 2 = 12예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [
      3,
      [
        [0, 1],
        [1, 2],
        [2, 0],
      ],
      2,
    ],
    expected: 0,
    explanation: "세 구역이 서로 맞닿아 있으면 2가지 색으로는 칠할 수 없어요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [1, [], 1],
    expected: 1,
    failureNote: "구역 하나, 색 하나예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [3, [], 2],
    expected: 8,
    failureNote: "맞닿은 곳이 없으면 2 × 2 × 2 = 8가지예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [
      4,
      [
        [0, 1],
        [1, 2],
        [2, 3],
        [3, 0],
      ],
      3,
    ],
    expected: 18,
    failureNote: "네 구역이 고리 모양이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [
      4,
      [
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 2],
        [2, 3],
        [3, 1],
      ],
      4,
    ],
    expected: 24,
    failureNote: "모든 구역이 서로 맞닿아 있어요. 4 × 3 × 2 × 1 = 24예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [
      14,
      [...Array.from({ length: 12 }, (_, i) => [i, i + 2]), ...Array.from({ length: 7 }, (_, i) => [2 * i, 2 * i + 1])],
      3,
    ],
    expected: 4374,
    failureNote: "구역 14개가 사다리 모양으로 이어져 있어요. 3^14 ≈ 478만 가지를 다 칠해 보고 검사하면 느려요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [
      14,
      [...Array.from({ length: 13 }, (_, i) => [i, i + 1]), ...Array.from({ length: 12 }, (_, i) => [i, i + 2])],
      4,
    ],
    expected: 49152,
    failureNote: "구역 14개가 삼각형 띠 모양이에요. 4^14 ≈ 2.7억 가지예요.",
  },
]);

export const backtrackingMapColoring: Problem = {
  id: "c:backtracking-map-coloring",
  slug: "backtracking-map-coloring",
  source: "curated",
  topic: "backtracking",
  level: 5,
  title: "구역 지도 색칠하기",
  summary: "맞닿은 구역끼리 다른 색이 되도록 칠하는 방법의 수를 세요",
  statement: [
    "노디는 공원 안내 지도를 색칠해요. 구역은 `n`개(0번 ~ `n-1`번)이고, `borders`의 `[a, b]`는 a구역과 b구역이 **맞닿아 있다**는 뜻이에요. 물감은 `k`가지 색이 있어요.",
    "",
    "모든 구역을 한 가지 색으로 칠하되, **맞닿은 두 구역은 색이 달라야** 해요. 쓰지 않는 색이 있어도 괜찮아요.",
    "",
    "칠하는 방법의 수를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 구역 수, `borders`: `[a, b]` 맞닿음 목록, `k`: 색의 수예요.",
  outputFormat: "방법의 수 (정수)",
  constraints: ["1 ≤ n ≤ 14", "1 ≤ k ≤ 4", "a ≠ b", "답은 100,000 이하예요."],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "구역 수" },
      {
        name: "borders",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "맞닿은 구역 쌍",
      },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "색의 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "방법의 수" },
  },
  starterCode: {
    python: ["def solution(n, borders, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, borders, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] borders, int k) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"맞닿으면 다른 색"이라는 **제약**을 지키며 모든 칠하기를 세요 → **제약 만족 백트래킹**이에요.',
        "",
        "다 칠한 뒤 검사하면 k^n가지를 모두 봐야 해요. 한 구역씩 칠하면서 **이미 칠한 이웃과 색이 같으면 바로 포기**해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 맞닿음 목록으로 인접 리스트를 만들고, `color`를 모두 -1(아직 안 칠함)로 둬요.",
        "2. `paint(v)`: v번 구역에 색 0 ~ k-1을 차례로 시도해요.",
        "   - v의 이웃 중 **같은 색으로 이미 칠해진** 구역이 있으면 그 색은 건너뛰어요.",
        "   - 괜찮으면 칠하고 `paint(v + 1)`, 돌아오면 -1로 지워요.",
        "3. v == n이면 모두 칠했으니 1가지예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "paint(v):",
        "    if v == n: return 1",
        "    count = 0",
        "    for c in 0..k-1:",
        "        if v의 이웃 중 color == c인 구역이 있으면: continue",
        "        color[v] = c",
        "        count += paint(v + 1)",
        "        color[v] = -1",
        "    return count",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["색이 겹치는지 검사하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for c in range(k):",
            "    if any(______ for w in graph[v]):",
            "        continue",
            "    color[v] = c",
            "    count += paint(v + 1)",
            "    color[v] = -1",
          ].join("\n"),
          javascript: [
            "for (let c = 0; c < k; c += 1) {",
            "  if (graph[v].some((w) => ______)) continue;",
            "  color[v] = c;",
            "  count += paint(v + 1);",
            "  color[v] = -1;",
            "}",
          ].join("\n"),
          java: [
            "for (int c = 0; c < k; c++) {",
            "    boolean clash = false;",
            "    for (int w : graph.get(v)) if (______) clash = true;",
            "    if (clash) continue;",
            "    color[v] = c;",
            "    count += paint(v + 1);",
            "    color[v] = -1;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["constraint-pruning"],
  signalIds: ["sig-placement-constraint", "sig-small-n"],
  estimatedMinutes: 30,
  xp: 50,
};
