import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[1, 2, 3], 2],
    expected: 6,
    explanation: "12, 13, 21, 23, 31, 32로 6개예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [[1, 1, 2], 2],
    expected: 3,
    explanation: "11, 12, 21 세 개예요. 1 카드 두 장을 바꿔 놓아도 같은 수라 한 번만 세요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "tricky",
    args: [[0, 1, 2], 3],
    expected: 4,
    failureNote: "0으로 시작하는 012, 021은 빼요. 102, 120, 201, 210으로 4개예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [[0], 1],
    expected: 0,
    failureNote: "0 한 장뿐이라 만들 수 있는 수가 없어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "edge",
    args: [[7, 7, 7, 7], 4],
    expected: 1,
    failureNote: "모두 같은 카드면 7777 하나예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [[5, 0, 5, 0], 2],
    expected: 2,
    failureNote: "50, 55 두 개예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [[1, 2, 3, 4, 5, 6, 7, 8], 8],
    expected: 40320,
    failureNote: "8장을 모두 늘어놓는 40,320가지예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [[0, 0, 1, 1, 2, 2, 3, 3], 6],
    expected: 1080,
    failureNote: "같은 카드가 많고 0도 섞여 있어요.",
  },
]);

export const backtrackingNumberCards: Problem = {
  id: "c:backtracking-number-cards",
  slug: "backtracking-number-cards",
  source: "curated",
  topic: "backtracking",
  level: 2,
  title: "숫자 카드로 만든 수",
  summary: "카드를 골라 늘어놓아 만들 수 있는 서로 다른 수의 개수를 세요",
  statement: [
    "노디에게 숫자 카드 `cards`가 있어요. 같은 숫자 카드가 여러 장일 수도 있어요.",
    "",
    "카드 `k`장을 골라 한 줄로 늘어놓으면 k자리 수가 돼요. 단, **맨 앞 카드가 0이면 안 돼요**.",
    "",
    "만들 수 있는 **서로 다른 수**는 몇 개인지 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`cards`: 0 ~ 9 숫자 리스트, `k`: 고를 카드 수예요.",
  outputFormat: "서로 다른 수의 개수 (정수)",
  constraints: ["1 ≤ k ≤ cards의 길이 ≤ 8"],
  signature: {
    name: "solution",
    params: [
      { name: "cards", type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "숫자 카드" },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "고를 카드 수" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "서로 다른 수의 개수" },
  },
  starterCode: {
    python: ["def solution(cards, k):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(cards, k) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] cards, int k) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "카드를 **순서 있게** 늘어놓아요 → **순열** 백트래킹이에요.",
        "",
        "같은 숫자 카드가 있어서 다른 카드로 **같은 수**가 만들어질 수 있어요. 만든 수를 **집합(set)** 에 모으면 중복이 저절로 사라져요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `used`로 쓴 카드(인덱스)를 기록하며 순열을 만들어요.",
        "2. k장을 골랐으면, 맨 앞이 0이 아닐 때만 문자열로 이어 집합에 넣어요.",
        "3. 집합의 크기가 답이에요.",
        "",
        "더 빠르게 하려면 **첫 자리에 0을 고르는 순간** 그 가지를 건너뛰어도 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "arrange():",
        "    if len(path) == k:",
        "        if path[0] != 0: made에 path를 수로 추가",
        "        return",
        "    for i in 0..n-1:",
        "        if not used[i]:",
        "            고르기 → arrange() → 되돌리기",
        "return len(made)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["완성된 수를 집합에 넣는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "if len(path) == k:",
            "    if ______:",
            '        made.add("".join(map(str, path)))',
            "    return",
          ].join("\n"),
          javascript: ["if (path.length === k) {", '  if (______) made.add(path.join(""));', "  return;", "}"].join(
            "\n",
          ),
          java: ["if (path.length() == k) {", "    if (______) made.add(path.toString());", "    return;", "}"].join(
            "\n",
          ),
        },
        caption: "Java는 path를 StringBuilder로, 만든 수는 Set<String> made = new HashSet<>()에 모아요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["permutation"],
  signalIds: ["sig-all-cases", "sig-small-n"],
  estimatedMinutes: 15,
  xp: 20,
};
