import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      [
        ["셔츠", "후드"],
        ["청바지", "치마"],
      ],
    ],
    expected: [
      ["셔츠", "청바지"],
      ["셔츠", "치마"],
      ["후드", "청바지"],
      ["후드", "치마"],
    ],
    explanation: "윗옷 2 × 아래옷 2 = 4가지예요. 셔츠를 고정하고 아래옷을 바꾼 뒤, 후드로 넘어가요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "basic",
    args: [[["모자"], ["셔츠", "후드"], ["운동화"]]],
    expected: [
      ["모자", "셔츠", "운동화"],
      ["모자", "후드", "운동화"],
    ],
    explanation: "하나뿐인 종류는 늘 그 옷이에요. 2가지예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [[["원피스"]]],
    expected: [["원피스"]],
    failureNote: "종류도 옷도 하나뿐이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [[["빨강", "파랑", "노랑"]]],
    expected: [["빨강"], ["파랑"], ["노랑"]],
    failureNote: "종류가 하나면 옷 수만큼이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [
      [
        ["a1", "a2"],
        ["b1", "b2"],
        ["c1", "c2"],
      ],
    ],
    expected: [
      ["a1", "b1", "c1"],
      ["a1", "b1", "c2"],
      ["a1", "b2", "c1"],
      ["a1", "b2", "c2"],
      ["a2", "b1", "c1"],
      ["a2", "b1", "c2"],
      ["a2", "b2", "c1"],
      ["a2", "b2", "c2"],
    ],
    failureNote: "2 × 2 × 2 = 8가지예요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [[["상의"], ["하의1", "하의2", "하의3"]]],
    expected: [
      ["상의", "하의1"],
      ["상의", "하의2"],
      ["상의", "하의3"],
    ],
    failureNote: "3가지예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 5 }, (_, g) => ["a", "b", "c", "d"].map((x) => x + g))],
    expected: Array.from({ length: 1024 }, (_, i) =>
      Array.from({ length: 5 }, (_, g) => ["a", "b", "c", "d"][Math.floor(i / 4 ** (4 - g)) % 4] + g),
    ),
    failureNote: "5종류 × 4벌이라 1,024가지예요.",
  },
]);

export const backtrackingOutfitPicker: Problem = {
  id: "c:backtracking-outfit-picker",
  slug: "backtracking-outfit-picker",
  source: "curated",
  topic: "backtracking",
  level: 1,
  title: "오늘의 옷 고르기",
  summary: "종류마다 하나씩 골라 만들 수 있는 모든 옷차림을 나열해요",
  statement: [
    "노디는 옷을 **종류마다 하나씩** 골라 입어요. `closet[i]`는 i번째 종류(예: 윗옷, 아래옷, 모자)의 옷 이름 목록이에요.",
    "",
    "만들 수 있는 **모든 옷차림**을 반환해 주세요. 옷차림 하나는 `[0번 종류에서 고른 옷, 1번 종류에서 고른 옷, …]` 리스트예요.",
    "",
    "순서는 앞 종류를 먼저 고정하고 뒤 종류를 바꿔 가며 나열해요. 각 종류 안에서는 `closet`에 적힌 순서대로 골라요.",
  ].join("\n"),
  inputFormat: "`closet`: 옷 종류별 이름 목록의 리스트예요.",
  outputFormat: "옷차림(이름 리스트)들의 리스트",
  constraints: ["1 ≤ 종류 수 ≤ 5", "1 ≤ 종류별 옷 수 ≤ 4", "옷 이름은 모두 달라요."],
  signature: {
    name: "solution",
    params: [
      {
        name: "closet",
        type: { python: "list[list[str]]", javascript: "string[][]", java: "String[][]" },
        description: "종류별 옷 목록",
      },
    ],
    returns: {
      type: { python: "list[list[str]]", javascript: "string[][]", java: "List<List<String>>" },
      description: "모든 옷차림",
    },
  },
  starterCode: {
    python: ["def solution(closet):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(closet) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<List<String>> solution(String[][] closet) {",
      "        List<List<String>> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ['"만들 수 있는 **모든** 옷차림" → 종류마다 한 벌씩 **고르고** 다음 종류로 가는 **백트래킹**이에요.'].join(
        "\n",
      ),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`choose(i)`: i번째 종류에서 옷을 고르는 함수예요.",
        "",
        "1. i가 종류 수와 같으면 모두 골랐어요 → `path`의 **복사본**을 결과에 추가해요.",
        "2. 아니면 i번째 종류의 옷마다: `path`에 넣고 → `choose(i + 1)` → `path`에서 빼요.",
        "",
        "`path`를 그대로 넣으면 나중에 빼는 동작이 결과까지 바꿔요. 꼭 **복사본**을 넣으세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "choose(i):",
        "    if i == len(closet):",
        "        result에 path 복사본 추가; return",
        "    for item in closet[i]:",
        "        path에 item 추가",
        "        choose(i + 1)",
        "        path에서 마지막 빼기",
        "choose(0)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["완성된 옷차림을 저장하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "def choose(i):",
            "    if i == len(closet):",
            "        result.append(______)",
            "        return",
            "    for item in closet[i]:",
            "        path.append(item)",
            "        choose(i + 1)",
            "        path.pop()",
          ].join("\n"),
          javascript: [
            "function choose(i) {",
            "  if (i === closet.length) {",
            "    result.push(______);",
            "    return;",
            "  }",
            "  for (const item of closet[i]) {",
            "    path.push(item);",
            "    choose(i + 1);",
            "    path.pop();",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "void choose(int i) {",
            "    if (i == closet.length) {",
            "        result.add(______);",
            "        return;",
            "    }",
            "    for (String item : closet[i]) {",
            "        path.add(item);",
            "        choose(i + 1);",
            "        path.remove(path.size() - 1);",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "Python은 path[:], JavaScript는 [...path]로 복사해요. Java는 new ArrayList<>(path)로 복사해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["combination"],
  signalIds: ["sig-all-cases", "sig-small-n"],
  estimatedMinutes: 10,
  xp: 10,
};
