import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const backtrackingSnackTotal: Problem = {
  id: "c:backtracking-snack-total",
  slug: "backtracking-snack-total",
  source: "curated",
  topic: "backtracking",
  level: 3,
  title: "용돈 딱 맞게 간식 사기",
  summary: "간식 가격 합이 정확히 용돈이 되는 고르기 방법의 수를 세요",
  statement: [
    "노디는 매점에서 간식을 사려고 해요. 간식 `n`개의 가격이 `prices`로 주어지고, 간식마다 **살지 말지**를 정해요 (같은 간식을 두 번 살 수는 없어요).",
    "",
    "산 간식의 가격 합이 **정확히 `money`원**이 되는 고르기 방법은 몇 가지인지 반환해 주세요. 가격이 같아도 다른 간식이면 다른 방법이에요.",
  ].join("\n"),
  inputFormat: "`prices`: 간식 가격 리스트, `money`: 용돈이에요.",
  outputFormat: "방법의 수 (정수)",
  constraints: ["1 ≤ n ≤ 16", "1 ≤ prices[i] ≤ 1,000", "1 ≤ money ≤ 16,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "prices",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "간식 가격",
      },
      { name: "money", type: { python: "int", javascript: "number", java: "int" }, description: "용돈" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "방법의 수" },
  },
  starterCode: {
    python: ["def solution(prices, money):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(prices, money) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] prices, int money) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[100, 200, 300, 400], 500],
      expected: 2,
      explanation: "{100, 400}, {200, 300} 두 가지예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [[500, 500, 500], 1000],
      expected: 3,
      explanation: "가격이 같아도 다른 간식이에요. 세 개 중 두 개를 고르는 3가지예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[300], 300],
      expected: 1,
      failureNote: "간식 하나로 딱 맞아요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[300, 400], 500],
      expected: 0,
      failureNote: "딱 맞출 수 없어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [[100, 100, 200, 300], 400],
      expected: 3,
      failureNote: "{100, 300} 두 가지, {100, 100, 200} 한 가지로 3가지예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3, 4, 5], 15],
      expected: 1,
      failureNote: "모두 사야 15예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100], 800],
      expected: 12870,
      failureNote: "16개 중 8개를 고르는 12,870가지예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [[120, 350, 80, 410, 200, 90, 330, 150, 60, 270, 500, 30, 180, 240, 70, 310], 1000],
      expected: 208,
      failureNote: "16개 간식의 모든 고르기(65,536가지)를 살펴봐요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "간식마다 **산다 / 안 산다** 두 갈래 → 모든 **부분집합**을 살펴보는 백트래킹이에요.",
        "",
        "n ≤ 16이라 2^16 = 65,536가지를 모두 봐도 충분히 빨라요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "`go(i, total)`: i번째 간식을 정할 차례이고 지금까지 합이 total인 상태예요.",
        "",
        "1. i == n이면 모든 간식을 정했어요 → total == money면 1, 아니면 0을 돌려줘요.",
        "2. 아니면 **산다** `go(i + 1, total + prices[i])` + **안 산다** `go(i + 1, total)`를 더해요.",
        "",
        "합을 인자로 넘기면 되돌리기를 따로 하지 않아도 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "go(i, total):",
        "    if i == n: return 1 if total == money else 0",
        "    return go(i + 1, total + prices[i]) + go(i + 1, total)",
        "return go(0, 0)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["두 갈래를 더하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "def go(i, total):",
            "    if i == n:",
            "        return 1 if total == money else 0",
            "    return go(i + 1, total + prices[i]) + ______",
          ].join("\n"),
          javascript: [
            "function go(i, total) {",
            "  if (i === n) return total === money ? 1 : 0;",
            "  return go(i + 1, total + prices[i]) + ______;",
            "}",
          ].join("\n"),
          java: [
            "int go(int i, int total) {",
            "    if (i == prices.length) return total == money ? 1 : 0;",
            "    return go(i + 1, total + prices[i]) + ______;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["subset"],
  signalIds: ["sig-all-cases", "sig-small-n"],
  visualization: {
    presets: [
      problemPreset(
        "snack-subset-tree",
        "backtracking-subset",
        "산다 / 안 산다 트리",
        "간식마다 두 갈래로 나뉘며 모든 고르기가 만들어져요.",
        [[1, 2, 3]],
      ),
    ],
  },
  estimatedMinutes: 18,
  xp: 30,
};
