import type { Problem } from "@/types/content";

export const bfsFireStations: Problem = {
  id: "c:bfs-fire-stations",
  slug: "bfs-fire-stations",
  source: "curated",
  topic: "bfs",
  level: 4,
  title: "가장 먼 집까지 소방차",
  summary: "여러 소방서에서 동시에 출발할 때 가장 늦게 닿는 집까지의 거리를 구해요",
  statement: [
    "노디 마을에는 집이 `n`채 있고 0번부터 `n-1`번까지 번호가 있어요. 길 `roads`의 `[a, b]`는 두 집을 양쪽으로 잇는 길이에요.",
    "",
    "소방서가 있는 집들이 `stations`로 주어져요. 불이 나면 **가장 가까운 소방서**에서 소방차가 출발해요.",
    "",
    "집마다 가장 가까운 소방서까지 지나는 길의 수를 구했을 때, 그중 **가장 큰 값**을 반환해 주세요. 어느 소방서에서도 갈 수 없는 집이 하나라도 있으면 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`n`: 집 수, `roads`: `[a, b]` 길 목록, `stations`: 소방서가 있는 집 목록이에요.",
  outputFormat: "가장 먼 집까지의 거리 (닿지 않는 집이 있으면 -1)",
  constraints: [
    "1 ≤ n ≤ 100,000",
    "0 ≤ roads의 길이 ≤ 200,000",
    "a ≠ b, 같은 길은 두 번 주어지지 않아요",
    "1 ≤ stations의 길이 ≤ n, 번호는 서로 달라요",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "집 수" },
      {
        name: "roads",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "길 목록",
      },
      {
        name: "stations",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "소방서가 있는 집",
      },
    ],
    returns: {
      type: { python: "int", javascript: "number", java: "int" },
      description: "가장 먼 집까지의 거리 (없으면 -1)",
    },
  },
  starterCode: {
    python: ["def solution(n, roads, stations):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, roads, stations) {", "  let answer = 0;", "  return answer;", "}", ""].join(
      "\n",
    ),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] roads, int[] stations) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        7,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [3, 4],
          [4, 5],
          [5, 6],
        ],
        [0, 6],
      ],
      expected: 3,
      explanation: "양 끝 소방서에서 가운데 3번 집까지가 3으로 가장 멀어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [3, [[0, 1]], [0]],
      expected: -1,
      explanation: "2번 집은 어느 소방서에서도 갈 수 없어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1, [], [0]],
      expected: 0,
      failureNote: "소방서가 있는 집 하나뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [
        3,
        [
          [0, 1],
          [1, 2],
        ],
        [0, 1, 2],
      ],
      expected: 0,
      failureNote: "모든 집에 소방서가 있어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        6,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [3, 4],
          [4, 5],
          [0, 5],
        ],
        [0, 3],
      ],
      expected: 1,
      failureNote: "고리 모양 마을이에요. 가까운 소방서는 집마다 달라요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [
        8,
        [
          [0, 1],
          [0, 2],
          [0, 3],
          [3, 4],
          [4, 5],
          [5, 6],
          [6, 7],
        ],
        [2],
      ],
      expected: 6,
      failureNote: "소방서가 한 곳뿐이면 그곳에서 가장 먼 집까지의 거리예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        100000,
        Array.from({ length: 99999 }, (_, i) => [i, i + 1]),
        Array.from({ length: 50000 }, (_, i) => i * 2),
      ],
      expected: 1,
      failureNote: "소방서가 5만 곳이에요. 소방서마다 따로 BFS를 하면 시간 초과예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [100000, Array.from({ length: 99999 }, (_, i) => [i, i + 1]), [0]],
      expected: 99999,
      failureNote: "한 줄로 이어진 10만 채 끝에 소방서가 하나 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "여러 소방서에서 **동시에** 소방차가 퍼져 나가요 → **여러 시작점 BFS**(멀티 소스 BFS)예요.",
        "",
        "집마다 가장 가까운 소방서를 따로 찾을 필요 없이, 모든 소방서를 **처음부터 한꺼번에** 큐에 넣으면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `dist`를 -1로 채우고, 소방서마다 `dist = 0`으로 적고 **모두** 큐에 넣어요.",
        "2. 평소처럼 BFS를 해요. 어떤 집에 처음 닿는 순간이 가장 가까운 소방서에서 온 거예요.",
        "3. BFS가 끝났을 때 dist에 -1이 남아 있으면 닿지 않는 집이 있으니 -1, 아니면 dist의 가장 큰 값이 답이에요.",
        "",
        "소방서마다 따로 BFS를 하면 O(소방서 수 × N)이지만, 한꺼번에 하면 O(N + 길 수)예요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = [-1] * n, queue = 빈 큐",
        "for s in stations: dist[s] = 0, queue 뒤에 s 넣기",
        "while queue가 비어 있지 않은 동안:",
        "    u = queue 앞에서 꺼내기",
        "    for v in graph[u]:",
        "        if dist[v] == -1: dist[v] = dist[u] + 1, queue 뒤에 v 넣기",
        "return -1 in dist ? -1 : max(dist)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["BFS를 시작하기 전에 큐를 채우는 부분이 핵심이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "dist = [-1] * n",
            "queue = deque()",
            "for s in stations:",
            "    dist[s] = ______",
            "    queue.append(s)",
          ].join("\n"),
          javascript: [
            "const dist = new Array(n).fill(-1);",
            "const queue = [];",
            "for (const s of stations) {",
            "  dist[s] = ______;",
            "  queue.push(s);",
            "}",
          ].join("\n"),
          java: [
            "int[] dist = new int[n];",
            "Arrays.fill(dist, -1);",
            "Deque<Integer> queue = new ArrayDeque<>();",
            "for (int s : stations) {",
            "    dist[s] = ______;",
            "    queue.offer(s);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["multi-source-bfs"],
  signalIds: ["sig-spread-simultaneous", "sig-shortest-steps"],
  estimatedMinutes: 20,
  xp: 40,
};
