import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      5,
      [
        [0, 1],
        [0, 2],
        [2, 3],
      ],
      0,
    ],
    expected: [0, 1, 1, 2, -1],
    explanation: "1, 2는 1다리, 3은 2다리, 4는 이어지지 않아 -1이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "tricky",
    args: [
      4,
      [
        [0, 1],
        [1, 2],
        [2, 3],
        [0, 3],
      ],
      0,
    ],
    expected: [0, 1, 2, 1],
    explanation: "3번은 0 → 1 → 2 → 3으로도 가지만, 바로 친구라서 1다리예요. 가장 적은 수를 구해요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [1, [], 0],
    expected: [0],
    failureNote: "나 혼자예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [3, [], 1],
    expected: [-1, 0, -1],
    failureNote: "친구가 없어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [
      6,
      [
        [5, 4],
        [4, 3],
        [3, 2],
        [2, 1],
        [1, 0],
      ],
      3,
    ],
    expected: [3, 2, 1, 0, 1, 2],
    failureNote: "가운데 학생에서 양쪽으로 재요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      5,
      [
        [0, 1],
        [1, 2],
        [0, 2],
        [2, 3],
        [3, 4],
        [1, 4],
      ],
      0,
    ],
    expected: [0, 1, 1, 2, 2],
    failureNote: "여러 길 중 가장 짧은 것만 세요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [100000, Array.from({ length: 99999 }, (_, i) => [i, i + 1]), 0],
    expected: Array.from({ length: 100000 }, (_, i) => i),
    failureNote: "10만 명이 한 줄로 친구예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [100000, Array.from({ length: 99999 }, (_, i) => [0, i + 1]), 0],
    expected: Array.from({ length: 100000 }, (_, i) => (i === 0 ? 0 : 1)),
    failureNote: "0번이 모두와 친구예요. 큐에 10만 명이 한꺼번에 들어가서 list.pop(0)으로 꺼내면 느려요.",
  },
]);

export const bfsFriendDistance: Problem = {
  id: "c:bfs-friend-distance",
  slug: "bfs-friend-distance",
  source: "curated",
  topic: "bfs",
  level: 1,
  title: "몇 다리 건너 친구?",
  summary: "나에서 모든 사람까지 몇 다리를 건너야 하는지 구해요",
  statement: [
    "노디 학교 학생 `n`명(0번 ~ `n-1`번)의 친구 관계가 `pairs`로 주어져요. `[a, b]`는 a와 b가 서로 친구라는 뜻이에요.",
    "",
    "`me`번 학생에게 친구는 **1다리**, 친구의 친구(친구가 아닌)는 **2다리**…예요. 자기 자신은 0다리예요.",
    "",
    "i번째 원소가 **me에서 i번 학생까지 가장 적게 건너는 다리 수**인 리스트를 반환해 주세요. 이어져 있지 않은 학생은 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`n`: 학생 수, `pairs`: 친구 관계 목록, `me`: 기준 학생이에요.",
  outputFormat: "길이 n인 다리 수 리스트 (닿지 않으면 -1)",
  constraints: ["1 ≤ n ≤ 100,000", "0 ≤ pairs의 길이 ≤ 200,000", "a ≠ b"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "학생 수" },
      {
        name: "pairs",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "친구 관계",
      },
      { name: "me", type: { python: "int", javascript: "number", java: "int" }, description: "기준 학생" },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "학생별 다리 수" },
  },
  starterCode: {
    python: ["def solution(n, pairs, me):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, pairs, me) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int n, int[][] pairs, int me) {",
      "        int[] answer = new int[n];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"가장 적게 건너는 다리 수" = 간선에 무게가 없는 그래프의 **최단 거리** → **BFS**예요.',
        "",
        "BFS는 거리 0인 곳, 1인 곳, 2인 곳… 순서로 방문해서, **처음 방문할 때의 거리가 곧 최단 거리**예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `dist`를 모두 -1로 채우고 `dist[me] = 0`, 큐에 me를 넣어요.",
        "2. 큐에서 v를 꺼내 이웃 w 중 `dist[w] == -1`(처음 보는 학생)이면 `dist[w] = dist[v] + 1`로 적고 큐에 넣어요.",
        "3. `dist` 자체가 방문 표시 역할도 해요.",
        "",
        "> Python은 `collections.deque`의 `popleft()`, JavaScript는 배열 + **head 번호**, Java는 `ArrayDeque`의 `poll()`로 앞에서 꺼내요. `list.pop(0)`·`shift()`는 매번 전체를 당겨서 느려요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = [-1] * n; dist[me] = 0",
        "queue = [me]",
        "while queue:",
        "    v = queue 앞에서 꺼내기",
        "    for w in graph[v]:",
        "        if dist[w] == -1:",
        "            dist[w] = dist[v] + 1",
        "            queue 뒤에 w 넣기",
        "return dist",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["거리를 적는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "while queue:",
            "    v = queue.popleft()",
            "    for w in graph[v]:",
            "        if dist[w] == -1:",
            "            dist[w] = ______",
            "            queue.append(w)",
          ].join("\n"),
          javascript: [
            "while (head < queue.length) {",
            "  const v = queue[head++];",
            "  for (const w of graph[v]) {",
            "    if (dist[w] === -1) {",
            "      dist[w] = ______;",
            "      queue.push(w);",
            "    }",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "while (!queue.isEmpty()) {",
            "    int v = queue.poll();",
            "    for (int w : graph.get(v)) {",
            "        if (dist[w] == -1) {",
            "            dist[w] = ______;",
            "            queue.offer(w);",
            "        }",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "dist는 int[] dist = new int[n]; Arrays.fill(dist, -1);로 만들어요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["shortest-path-unweighted", "level-order"],
  signalIds: ["sig-shortest-steps"],
  visualization: {
    presets: [
      problemPreset("friend-dist-ex2", "graph-bfs", "예제 2", "3번에 먼저 닿는 길이 가장 짧은 길이에요.", [
        4,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [0, 3],
        ],
        0,
      ]),
    ],
  },
  estimatedMinutes: 12,
  xp: 10,
};
