import type { Problem } from "@/types/content";

export const bfsFrogLeaps: Problem = {
  id: "c:bfs-frog-leaps",
  slug: "bfs-frog-leaps",
  source: "curated",
  topic: "bfs",
  level: 3,
  title: "개구리의 연잎 점프",
  summary: "앞뒤로 정해진 만큼만 뛰는 개구리가 마지막 연잎까지 가는 최소 점프 수를 구해요",
  statement: [
    "연못에 연잎 `n`장이 한 줄로 떠 있어요 (0번 ~ `n-1`번). 연잎마다 숫자 `leap[i]`가 적혀 있어요.",
    "",
    "개구리는 i번 연잎에서 **정확히 `leap[i]`칸 앞(i + leap[i])** 이나 **뒤(i − leap[i])** 로만 뛸 수 있어요. 연못 밖(0보다 작거나 n-1보다 큰 곳)으로는 뛸 수 없어요.",
    "",
    "0번 연잎에서 출발해 `n-1`번 연잎에 닿는 **최소 점프 수**를 반환해 주세요. 닿을 수 없으면 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`leap`: 길이 n인 양의 정수 리스트예요.",
  outputFormat: "최소 점프 수 (정수, 불가능하면 -1)",
  constraints: ["1 ≤ n ≤ 100,000", "1 ≤ leap[i] ≤ n"],
  signature: {
    name: "solution",
    params: [
      { name: "leap", type: { python: "list[int]", javascript: "number[]" }, description: "연잎마다 뛰는 칸 수" },
    ],
    returns: { type: { python: "int", javascript: "number" }, description: "최소 점프 수" },
  },
  starterCode: {
    python: ["def solution(leap):", "    answer = -1", "    return answer", ""].join("\n"),
    javascript: ["function solution(leap) {", "  let answer = -1;", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[2, 3, 1, 1, 2]],
      expected: 3,
      explanation: "0 → 2 → 3 → 4로 3번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [[3, 3, 9, 2, 9]],
      expected: 3,
      explanation: "0 → 3 → 1(뒤로!) → 4로 3번이에요. 앞으로만 뛰면 닿을 수 없어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5]],
      expected: 0,
      failureNote: "연잎이 하나면 이미 도착이라 0번이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[2, 1, 2]],
      expected: 1,
      failureNote: "0 → 2로 한 번에 가요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 9, 2, 9]],
      expected: -1,
      failureNote: "0 ↔ 2만 오가고 3에 닿을 수 없어요. 방문 표시가 없으면 끝없이 오가요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 4, 1, 1, 1, 1, 1]],
      expected: 3,
      failureNote: "0 → 1 → 5 → 6으로 3번이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [new Array(100000).fill(1)],
      expected: 99999,
      failureNote: "연잎 10만 장, 모두 1칸씩이에요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 997) + 1)],
      expected: 179,
      failureNote: "연잎 10만 장의 뒤섞인 점프예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "격자도 지도도 아니지만, **연잎 = 노드**, **한 번의 점프 = 간선**으로 보면 그래프예요.",
        "",
        '"최소 점프 수" → **BFS**예요. 이웃은 `i + leap[i]`, `i - leap[i]` 두 개뿐이에요.',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `dist[0] = 0`, 큐에 0을 넣어요.",
        "2. i를 꺼내 두 이웃 `i + leap[i]`, `i - leap[i]` 중 **연못 안이고 처음 보는** 연잎에 거리 + 1을 적고 큐에 넣어요.",
        "3. `dist[n-1]`을 반환해요 (못 닿았으면 -1 그대로).",
        "",
        "인접 리스트를 만들 필요 없이, 이웃을 **그때그때 계산**하면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = [-1] * n; dist[0] = 0; queue = [0]",
        "while queue:",
        "    i = 앞에서 꺼내기",
        "    for j in (i + leap[i], i - leap[i]):",
        "        if 0 <= j < n and dist[j] == -1:",
        "            dist[j] = dist[i] + 1; queue 뒤에 j",
        "return dist[n - 1]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["두 이웃을 계산하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "i = queue.popleft()",
            "for j in (i + leap[i], ______):",
            "    if 0 <= j < n and dist[j] == -1:",
            "        dist[j] = dist[i] + 1",
            "        queue.append(j)",
          ].join("\n"),
          javascript: [
            "const i = queue[head++];",
            "for (const j of [i + leap[i], ______]) {",
            "  if (j >= 0 && j < n && dist[j] === -1) {",
            "    dist[j] = dist[i] + 1;",
            "    queue.push(j);",
            "  }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["shortest-path-unweighted", "state-space-bfs"],
  signalIds: ["sig-shortest-steps"],
  estimatedMinutes: 18,
  xp: 30,
};
