import type { Problem } from "@/types/content";

export const bfsNearestShelter: Problem = {
  id: "c:bfs-nearest-shelter",
  slug: "bfs-nearest-shelter",
  source: "curated",
  topic: "bfs",
  level: 4,
  title: "가장 가까운 대피소",
  summary: "모든 칸에서 가장 가까운 대피소까지의 거리를 한 번에 구해요",
  statement: [
    "노디 시는 비상 훈련을 위해 지도를 만들어요. 지도 `city`에서 `'H'`는 대피소, `'.'`은 길, `'#'`은 건물이에요. 사람은 길과 대피소 칸만 **상하좌우**로 움직일 수 있어요.",
    "",
    "지도와 같은 크기의 표를 만들어 주세요. 각 칸에는",
    "",
    "- 대피소 칸: `0`",
    "- 길 칸: **가장 가까운 대피소까지 움직이는 최소 횟수** (갈 수 있는 대피소가 없으면 `-1`)",
    "- 건물 칸: `-1`",
    "",
    "을 적어요.",
  ].join("\n"),
  inputFormat: "`city`: 길이가 같은 문자열들의 리스트예요.",
  outputFormat: "칸별 거리를 담은 정수 표 (리스트의 리스트)",
  constraints: ["1 ≤ 행 수, 열 수 ≤ 100", "각 문자는 'H', '.', '#' 중 하나예요."],
  signature: {
    name: "solution",
    params: [{ name: "city", type: { python: "list[str]", javascript: "string[]" }, description: "도시 지도" }],
    returns: {
      type: { python: "list[list[int]]", javascript: "number[][]" },
      description: "칸별 가장 가까운 대피소 거리",
    },
  },
  starterCode: {
    python: ["def solution(city):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(city) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["H..", ".#.", "..H"]],
      expected: [
        [0, 1, 2],
        [1, -1, 1],
        [2, 1, 0],
      ],
      explanation: "왼쪽 위와 오른쪽 아래에 대피소가 있어요. 각 칸은 더 가까운 쪽까지의 거리예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [["H#.", ".#.", "..."]],
      expected: [
        [0, -1, 6],
        [1, -1, 5],
        [2, 3, 4],
      ],
      explanation: "오른쪽 위 칸은 건물을 돌아가야 해서 6이에요. 직선거리가 아니라 걷는 거리예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["H"]],
      expected: [[0]],
      failureNote: "대피소 한 칸이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [["..#H"]],
      expected: [[-1, -1, -1, 0]],
      failureNote: "건물에 막혀 왼쪽 두 칸은 갈 곳이 없어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [["....H....", "#########", "H........"]],
      expected: [
        [4, 3, 2, 1, 0, 1, 2, 3, 4],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
      ],
      failureNote: "위아래 줄은 건물로 나뉘어 각자 자기 줄의 대피소를 써요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [["...", "...", "..."]],
      expected: [
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
      ],
      failureNote: "대피소가 없으면 모든 길 칸이 -1이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 100 }, (_, r) =>
          Array.from({ length: 100 }, (_, c) => ((r === 0 && c === 0) || (r === 99 && c === 99) ? "H" : ".")).join(""),
        ),
      ],
      expected: Array.from({ length: 100 }, (_, r) =>
        Array.from({ length: 100 }, (_, c) => Math.min(r + c, 198 - r - c)),
      ),
      failureNote: "100×100 도시의 양 구석에 대피소가 있어요. 칸마다 BFS를 따로 돌리면 1억 번이 넘어요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 100 }, () =>
          Array.from({ length: 100 }, (_, c) => (c === 50 ? "H" : c === 49 ? "#" : ".")).join(""),
        ),
      ],
      expected: Array.from({ length: 100 }, () =>
        Array.from({ length: 100 }, (_, c) => (c === 49 ? -1 : c > 49 ? c - 50 : -1)),
      ),
      failureNote: "가운데 세로줄이 모두 대피소인데, 바로 왼쪽이 건물 벽이라 왼쪽 동네는 대피소에 갈 수 없어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '모든 칸에서 "**가장 가까운** 대피소"까지의 거리 → 출발점이 여러 개인 **멀티 소스 BFS**예요.',
        "",
        "칸마다 BFS를 돌리는 대신, 거꾸로 **모든 대피소에서 동시에** 퍼져 나가면 각 칸에 처음 닿은 거리가 가장 가까운 대피소까지의 거리예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 결과 표를 모두 -1로 채워요.",
        "2. 모든 'H' 칸을 0으로 적고 큐에 넣어요.",
        "3. BFS로 퍼지면서 **건물이 아니고 아직 -1인** 칸에 거리 + 1을 적어요.",
        "4. 끝나면 결과 표가 그대로 답이에요. 건물과 못 닿은 칸은 -1로 남아 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = 모두 -1",
        "모든 H 칸: dist = 0, 큐에 넣기",
        "while queue:",
        "    (r, c) = 앞에서 꺼내기",
        "    for 네 방향 (nr, nc):",
        "        if 격자 안 and city[nr][nc] != '#' and dist[nr][nc] == -1:",
        "            dist[nr][nc] = dist[r][c] + 1; 큐 뒤에 추가",
        "return dist",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["퍼져 나갈 칸의 조건이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):",
            "    nr, nc = r + dr, c + dc",
            "    if 0 <= nr < rows and 0 <= nc < cols and ______:",
            "        dist[nr][nc] = dist[r][c] + 1",
            "        queue.append((nr, nc))",
          ].join("\n"),
          javascript: [
            "for (const [dr, dc] of [[-1, 0], [1, 0], [0, -1], [0, 1]]) {",
            "  const nr = r + dr, nc = c + dc;",
            "  if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && ______) {",
            "    dist[nr][nc] = dist[r][c] + 1;",
            "    queue.push([nr, nc]);",
            "  }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["multi-source-bfs", "grid-shortest-path"],
  signalIds: ["sig-spread-simultaneous", "sig-grid-neighbors", "sig-shortest-steps"],
  estimatedMinutes: 25,
  xp: 40,
};
