import type { Problem } from "@/types/content";

export const bfsNearestStore: Problem = {
  id: "c:bfs-nearest-store",
  slug: "bfs-nearest-store",
  source: "curated",
  topic: "bfs",
  level: 2,
  title: "가장 가까운 편의점",
  summary: "지금 있는 곳에서 가장 적은 길을 지나 닿는 편의점까지의 거리를 구해요",
  statement: [
    "노디 동네에는 장소가 `n`개 있고 0번부터 `n-1`번까지 번호가 있어요. 길 `roads`의 `[a, b]`는 두 장소를 양쪽으로 잇는 길이에요.",
    "",
    "편의점이 있는 장소들이 `stores`로 주어져요. 노디는 `start`에서 출발해 **아무 편의점에나** 가려고 해요.",
    "",
    "가장 적은 길을 지나 닿을 수 있는 편의점까지 **지나는 길의 수**를 반환해 주세요. start가 편의점이면 0이에요. 어느 편의점에도 갈 수 없으면 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`n`: 장소 수, `roads`: `[a, b]` 길 목록, `start`: 출발 장소, `stores`: 편의점이 있는 장소 목록이에요.",
  outputFormat: "가장 가까운 편의점까지 지나는 길의 수 (없으면 -1)",
  constraints: [
    "1 ≤ n ≤ 100,000",
    "0 ≤ roads의 길이 ≤ 200,000",
    "a ≠ b, 같은 길은 두 번 주어지지 않아요",
    "1 ≤ stores의 길이 ≤ n, 번호는 서로 달라요",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "장소 수" },
      {
        name: "roads",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "길 목록",
      },
      { name: "start", type: { python: "int", javascript: "number", java: "int" }, description: "출발 장소" },
      {
        name: "stores",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "편의점이 있는 장소",
      },
    ],
    returns: {
      type: { python: "int", javascript: "number", java: "int" },
      description: "가장 가까운 편의점까지의 길 수 (없으면 -1)",
    },
  },
  starterCode: {
    python: ["def solution(n, roads, start, stores):", "    answer = -1", "    return answer", ""].join("\n"),
    javascript: [
      "function solution(n, roads, start, stores) {",
      "  let answer = -1;",
      "  return answer;",
      "}",
      "",
    ].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] roads, int start, int[] stores) {",
      "        int answer = -1;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        6,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [0, 4],
          [4, 5],
        ],
        0,
        [3, 5],
      ],
      expected: 2,
      explanation: "3번 편의점은 길 3개, 5번 편의점은 길 2개예요. 더 가까운 5번이라 2예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [
        3,
        [
          [0, 1],
          [1, 2],
        ],
        1,
        [1, 2],
      ],
      expected: 0,
      explanation: "출발한 곳이 편의점이면 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [
        4,
        [
          [0, 1],
          [2, 3],
        ],
        0,
        [3],
      ],
      expected: -1,
      failureNote: "편의점이 다른 동네에 있어서 갈 수 없어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        5,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [3, 4],
          [0, 4],
        ],
        0,
        [3],
      ],
      expected: 2,
      failureNote:
        "먼저 이어진 길(0 → 1 → 2 → 3)은 3개지만, 반대쪽(0 → 4 → 3)은 2개예요. 처음 찾은 길이 가장 짧은 건 BFS일 때만이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [
        7,
        [
          [0, 1],
          [0, 2],
          [1, 3],
          [2, 4],
          [3, 5],
          [4, 6],
        ],
        0,
        [5, 6],
      ],
      expected: 3,
      failureNote: "두 편의점이 같은 거리에 있어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [100000, Array.from({ length: 99999 }, (_, i) => [i, i + 1]), 0, [99999]],
      expected: 99999,
      failureNote: "한 줄로 이어진 10만 곳 끝에 편의점이 하나 있어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        100000,
        [
          ...Array.from({ length: 99999 }, (_, i) => [i, i + 1]),
          ...Array.from({ length: 100000 }, (_, i) => [i, (i + 5000) % 100000]).filter(
            ([a, b]) => Math.abs(a - b) !== 1,
          ),
        ],
        12345,
        [67890, 99999],
      ],
      expected: 554,
      failureNote: "장소 10만 곳, 길 약 20만 개예요. 편의점마다 따로 BFS를 돌 필요 없이, 출발지에서 한 번이면 돼요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "길 하나를 지날 때마다 거리가 똑같이 1씩 늘어요. **가장 적은 길 수** → **BFS**예요.",
        "",
        "BFS는 가까운 곳부터 큐에서 꺼내요. 그래서 **처음 꺼낸 편의점**이 가장 가까운 편의점이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 편의점 번호를 **집합**이나 참/거짓 배열로 만들어 '여기 편의점이야?'를 O(1)에 확인해요.",
        "2. start부터 BFS를 해요. `dist[start] = 0`.",
        "3. 큐에서 u를 꺼낼 때 u가 편의점이면 **바로** `dist[u]`를 반환해요.",
        "4. 큐가 빌 때까지 못 찾으면 -1이에요.",
        "",
        "방문 표시는 **큐에 넣을 때** 해요. 꺼낼 때 하면 같은 장소가 큐에 여러 번 들어가 느려져요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "isStore = stores로 만든 집합",
        "dist = [-1] * n, dist[start] = 0, queue = [start]",
        "while queue가 비어 있지 않은 동안:",
        "    u = queue 앞에서 꺼내기",
        "    if u가 편의점: return dist[u]",
        "    for v in graph[u]:",
        "        if dist[v] == -1:",
        "            dist[v] = dist[u] + 1, queue 뒤에 v 넣기",
        "return -1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["BFS에서 가장 가까운 편의점을 알아보는 순간이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while queue:",
            "    u = queue.popleft()",
            "    if ______:",
            "        return dist[u]",
            "    for v in graph[u]:",
            "        if dist[v] == -1:",
            "            dist[v] = dist[u] + 1",
            "            queue.append(v)",
            "return -1",
          ].join("\n"),
          javascript: [
            "for (let head = 0; head < queue.length; head++) {",
            "  const u = queue[head];",
            "  if (______) return dist[u];",
            "  for (const v of graph[u]) {",
            "    if (dist[v] === -1) {",
            "      dist[v] = dist[u] + 1;",
            "      queue.push(v);",
            "    }",
            "  }",
            "}",
            "return -1;",
          ].join("\n"),
          java: [
            "while (!queue.isEmpty()) {",
            "    int u = queue.poll();",
            "    if (______) return dist[u];",
            "    for (int v : graph.get(u)) {",
            "        if (dist[v] == -1) {",
            "            dist[v] = dist[u] + 1;",
            "            queue.offer(v);",
            "        }",
            "    }",
            "}",
            "return -1;",
          ].join("\n"),
        },
        caption: "Java는 boolean[] isStore에 편의점 자리를 표시해 두면 빠르게 확인할 수 있어요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["shortest-path-unweighted"],
  signalIds: ["sig-shortest-steps", "sig-relations-given"],
  estimatedMinutes: 12,
  xp: 20,
};
