import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const bfsNewsOrder: Problem = {
  id: "c:bfs-news-order",
  slug: "bfs-news-order",
  source: "curated",
  topic: "bfs",
  level: 1,
  title: "소식이 전해지는 순서",
  summary: "가까운 사람부터 한 겹씩 소식이 퍼지는 순서를 기록해요",
  statement: [
    "노디 마을 주민 `n`명(0번 ~ `n-1`번)은 이웃끼리 소식을 전해요. 이웃 관계 `pairs`의 `[a, b]`는 a와 b가 서로 이웃이라는 뜻이에요.",
    "",
    "`start`번 주민이 처음 소식을 들었어요. 소식은 이렇게 퍼져요.",
    "",
    "1. **먼저 소식을 들은 주민이 먼저** 전해요.",
    "2. 전할 차례가 된 주민은 아직 소식을 못 들은 이웃 모두에게 **번호가 작은 순서대로** 전해요.",
    "",
    "주민들이 **소식을 들은 순서대로** 번호를 담은 리스트를 반환해 주세요. 소식이 닿지 않는 주민은 빠져요.",
  ].join("\n"),
  inputFormat: "`n`: 주민 수, `pairs`: `[a, b]` 이웃 관계, `start`: 처음 소식을 들은 주민이에요.",
  outputFormat: "소식을 들은 순서대로의 주민 번호 리스트",
  constraints: ["1 ≤ n ≤ 1,000", "0 ≤ pairs의 길이 ≤ 3,000", "a ≠ b", "같은 관계는 두 번 주어지지 않아요."],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "주민 수" },
      {
        name: "pairs",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "이웃 관계",
      },
      { name: "start", type: { python: "int", javascript: "number", java: "int" }, description: "처음 들은 주민" },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "소식을 들은 순서",
    },
  },
  starterCode: {
    python: ["def solution(n, pairs, start):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, pairs, start) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(int n, int[][] pairs, int start) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        6,
        [
          [0, 1],
          [0, 2],
          [1, 3],
          [1, 4],
          [2, 5],
        ],
        0,
      ],
      expected: [0, 1, 2, 3, 4, 5],
      explanation:
        "0이 1, 2에게, 1이 3, 4에게, 2가 5에게 전해요. 한 겹씩 퍼져서 [0, 1, 2, 3, 4, 5]예요. (DFS라면 0, 1, 3, 4, 2, 5)",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [
        5,
        [
          [0, 1],
          [0, 2],
          [1, 3],
          [2, 3],
          [3, 4],
        ],
        0,
      ],
      expected: [0, 1, 2, 3, 4],
      explanation: "3은 1에게서 먼저 들었어요. 2가 전할 차례엔 이미 들은 사람이라 다시 전하지 않아요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1, [], 0],
      expected: [0],
      failureNote: "주민이 한 명뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        6,
        [
          [0, 1],
          [2, 3],
          [3, 4],
        ],
        3,
      ],
      expected: [3, 2, 4],
      failureNote: "3에서 시작하면 2, 4에게만 닿아요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        5,
        [
          [4, 0],
          [3, 0],
          [2, 4],
          [1, 3],
        ],
        0,
      ],
      expected: [0, 3, 4, 1, 2],
      failureNote: "관계가 뒤섞여 있어도 번호가 작은 이웃부터 전해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [
        7,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [0, 4],
          [4, 5],
          [5, 6],
        ],
        0,
      ],
      expected: [0, 1, 4, 2, 5, 3, 6],
      failureNote: "양쪽 갈래로 한 걸음씩 번갈아 퍼져요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [1000, Array.from({ length: 999 }, (_, i) => [999 - i, 998 - i]), 500],
      expected: [500].concat(...Array.from({ length: 499 }, (_, i) => [499 - i, 501 + i]), [0]),
      failureNote: "1,000명이 한 줄로 이웃이에요. 가운데에서 양쪽으로 번갈아 퍼져요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"먼저 들은 사람이 먼저 전한다" → 줄 서기(**큐**)예요. 큐로 가까운 곳부터 한 겹씩 방문하는 것이 **BFS**(너비 우선 탐색)예요.',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 인접 리스트를 만들고, 이웃을 **오름차순 정렬**해요.",
        "2. `start`를 방문 표시하고 큐에 넣어요.",
        "3. 큐 앞에서 한 명을 꺼내 순서에 기록하고, 아직 못 들은 이웃을 **방문 표시하면서** 큐 뒤에 넣어요.",
        "4. 큐가 빌 때까지 반복해요.",
        "",
        "> Python은 `collections.deque`의 `popleft()`, JavaScript는 배열 + **head 번호**, Java는 `ArrayDeque`의 `poll()`로 앞에서 꺼내요. `list.pop(0)`·`shift()`는 매번 전체를 당겨서 느려요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "visited[start] = True; queue = [start]",
        "while queue:",
        "    v = queue 앞에서 꺼내기",
        "    order에 v 추가",
        "    for w in graph[v]:   # 오름차순",
        "        if not visited[w]:",
        "            visited[w] = True",
        "            queue 뒤에 w 넣기",
        "return order",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "from collections import deque",
            "queue = deque([start])",
            "visited[start] = True",
            "while queue:",
            "    v = ______",
            "    order.append(v)",
            "    for w in graph[v]:",
            "        if not visited[w]:",
            "            visited[w] = True",
            "            queue.append(w)",
          ].join("\n"),
          javascript: [
            "const queue = [start];",
            "let head = 0;",
            "visited[start] = true;",
            "while (head < queue.length) {",
            "  const v = ______;",
            "  order.push(v);",
            "  for (const w of graph[v]) {",
            "    if (!visited[w]) {",
            "      visited[w] = true;",
            "      queue.push(w);",
            "    }",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "Queue<Integer> queue = new ArrayDeque<>();",
            "queue.offer(start);",
            "visited[start] = true;",
            "while (!queue.isEmpty()) {",
            "    int v = ______;",
            "    order.add(v);",
            "    for (int w : graph.get(v)) {",
            "        if (!visited[w]) {",
            "            visited[w] = true;",
            "            queue.offer(w);",
            "        }",
            "    }",
            "}",
          ].join("\n"),
        },
        caption: "Java는 Queue<Integer> queue = new ArrayDeque<>()로 큐를 만들어요 (offer로 넣고 poll로 꺼내요).",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["level-order"],
  signalIds: ["sig-spread-simultaneous"],
  visualization: {
    presets: [
      problemPreset("news-ex1", "graph-bfs", "예제 1", "가까운 사람부터 한 겹씩 소식이 퍼지는 모습을 봐요.", [
        6,
        [
          [0, 1],
          [0, 2],
          [1, 3],
          [1, 4],
          [2, 5],
        ],
        0,
      ]),
      problemPreset(
        "news-ex2",
        "graph-bfs",
        "예제 2: 두 길로 닿는 사람",
        "이미 소식을 들은 사람에게는 다시 전하지 않아요.",
        [
          5,
          [
            [0, 1],
            [0, 2],
            [1, 3],
            [2, 3],
            [3, 4],
          ],
          0,
        ],
      ),
    ],
  },
  estimatedMinutes: 10,
  xp: 10,
};
