import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      5,
      [
        [0, 1],
        [1, 2],
        [2, 4],
        [0, 3],
        [3, 4],
      ],
      0,
      4,
    ],
    expected: 2,
    explanation: "0 → 3 → 4로 2번이면 돼요. 0 → 1 → 2 → 4는 3번이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [
      4,
      [
        [0, 1],
        [2, 3],
      ],
      0,
      3,
    ],
    expected: -1,
    explanation: "항로로 이어지지 않아 -1이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [3, [[0, 1]], 2, 2],
    expected: 0,
    failureNote: "출발 탑이 곧 도착 탑이면 0번이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: [2, [[1, 0]], 0, 1],
    expected: 1,
    failureNote: "바로 이어져 있어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      6,
      [
        [0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [0, 5],
      ],
      1,
      4,
    ],
    expected: 3,
    failureNote: "고리 모양 항로예요. 1 → 0 → 5 → 4가 1 → 2 → 3 → 4와 똑같이 3번이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [
      7,
      [
        [0, 1],
        [0, 2],
        [1, 3],
        [2, 3],
        [3, 4],
        [4, 5],
        [2, 6],
        [6, 5],
      ],
      0,
      5,
    ],
    expected: 3,
    failureNote: "0 → 2 → 6 → 5로 3번이에요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [
      100000,
      [
        ...Array.from({ length: 99999 }, (_, i) => [i, i + 1]),
        ...Array.from({ length: 999 }, (_, i) => [i * 100, i * 100 + 100]),
      ],
      0,
      99999,
    ],
    expected: 1098,
    failureNote: "10만 개 탑에 100칸씩 건너뛰는 지름길이 있어요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [100000, Array.from({ length: 99998 }, (_, i) => [i, i + 1]), 0, 99999],
    expected: -1,
    failureNote: "마지막 탑만 떨어져 있어요. 모든 탑을 다 살펴야 -1인 걸 알 수 있어요.",
  },
]);

export const bfsPigeonPost: Problem = {
  id: "c:bfs-pigeon-post",
  slug: "bfs-pigeon-post",
  source: "curated",
  topic: "bfs",
  level: 2,
  title: "비둘기 편지",
  summary: "편지가 목적지 탑까지 가는 최소 비행 횟수를 구해요",
  statement: [
    "노디 왕국에는 비둘기 탑이 `n`개(0번 ~ `n-1`번) 있어요. 항로 목록 `routes`의 `[a, b]`는 a탑과 b탑 사이를 비둘기가 한 번에 날 수 있다는 뜻이에요 (양방향).",
    "",
    "편지는 탑에서 탑으로 한 번씩 날아 전달돼요. `s`탑에서 `t`탑까지 편지를 보낼 때 **최소 몇 번 날아야** 하는지 반환해 주세요. 보낼 수 없으면 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`n`: 탑 수, `routes`: `[a, b]` 항로 목록, `s`: 출발 탑, `t`: 도착 탑이에요.",
  outputFormat: "최소 비행 횟수 (정수, 불가능하면 -1)",
  constraints: ["1 ≤ n ≤ 100,000", "0 ≤ routes의 길이 ≤ 200,000", "a ≠ b"],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "탑 수" },
      {
        name: "routes",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "항로 목록",
      },
      { name: "s", type: { python: "int", javascript: "number", java: "int" }, description: "출발 탑" },
      { name: "t", type: { python: "int", javascript: "number", java: "int" }, description: "도착 탑" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 비행 횟수" },
  },
  starterCode: {
    python: ["def solution(n, routes, s, t):", "    answer = -1", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, routes, s, t) {", "  let answer = -1;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] routes, int s, int t) {",
      "        int answer = -1;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ['"**최소** 몇 번" + 한 번 나는 비용이 모두 같아요 → **BFS 최단 거리**예요.'].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. s에서 BFS를 시작해요. `dist[s] = 0`.",
        "2. 탑을 꺼낼 때 그 탑이 t라면 바로 `dist[t]`를 반환해도 돼요. BFS는 가까운 탑부터 꺼내니까 처음 만난 거리가 최소예요.",
        "3. 큐가 빌 때까지 t를 못 만나면 -1이에요.",
        "",
        "방문 표시(거리 기록)는 **큐에 넣을 때** 해야 같은 탑이 큐에 여러 번 들어가지 않아요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = [-1] * n; dist[s] = 0; queue = [s]",
        "while queue:",
        "    v = 앞에서 꺼내기",
        "    if v == t: return dist[v]",
        "    for w in graph[v]:",
        "        if dist[w] == -1:",
        "            dist[w] = dist[v] + 1; queue 뒤에 w",
        "return -1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["도착했는지 확인하는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "while queue:",
            "    v = queue.popleft()",
            "    if ______:",
            "        return dist[v]",
            "    for w in graph[v]:",
            "        if dist[w] == -1:",
            "            dist[w] = dist[v] + 1",
            "            queue.append(w)",
            "return -1",
          ].join("\n"),
          javascript: [
            "while (head < queue.length) {",
            "  const v = queue[head++];",
            "  if (______) return dist[v];",
            "  for (const w of graph[v]) {",
            "    if (dist[w] === -1) {",
            "      dist[w] = dist[v] + 1;",
            "      queue.push(w);",
            "    }",
            "  }",
            "}",
            "return -1;",
          ].join("\n"),
          java: [
            "while (!queue.isEmpty()) {",
            "    int v = queue.poll();",
            "    if (______) return dist[v];",
            "    for (int w : graph.get(v)) {",
            "        if (dist[w] == -1) {",
            "            dist[w] = dist[v] + 1;",
            "            queue.offer(w);",
            "        }",
            "    }",
            "}",
            "return -1;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["shortest-path-unweighted"],
  signalIds: ["sig-shortest-steps", "sig-relations-given"],
  estimatedMinutes: 15,
  xp: 20,
};
