import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [
      6,
      [
        [0, 1],
        [0, 2],
        [1, 3],
        [2, 3],
        [3, 4],
      ],
      0,
    ],
    expected: [[0], [1, 2], [3], [4]],
    explanation: "1초에 1, 2번, 2초에 3번, 3초에 4번에 닿아요. 5번은 이어진 물길이 없어요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [1, [], 0],
    expected: [[0]],
    explanation: "연잎 하나뿐이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "basic",
    args: [
      5,
      [
        [0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 0],
      ],
      2,
    ],
    expected: [[2], [1, 3], [0, 4]],
    failureNote: "고리 모양 연못이에요. 물결이 양쪽으로 퍼져요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      4,
      [
        [0, 1],
        [1, 2],
        [0, 2],
        [2, 3],
      ],
      0,
    ],
    expected: [[0], [1, 2], [3]],
    failureNote:
      "2번은 1번을 거쳐서도 닿지만, 0번에서 바로 이어져 있어서 1초에 닿아요. 깊이 우선으로 돌면 2초로 잘못 적어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: [
      6,
      [
        [5, 3],
        [3, 1],
        [5, 4],
        [4, 0],
        [2, 5],
      ],
      5,
    ],
    expected: [[5], [2, 3, 4], [0, 1]],
    failureNote: "물길이 번호 순서로 주어지지 않아요. 묶음마다 오름차순으로 정렬해야 해요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, Array.from({ length: 999 }, (_, i) => [i, i + 1]), 0],
    expected: Array.from({ length: 1000 }, (_, i) => [i]),
    failureNote: "연잎 1,000개가 한 줄로 이어져 있어요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [1000, Array.from({ length: 999 }, (_, i) => [999 - i, 0]), 0],
    expected: [[0], Array.from({ length: 999 }, (_, i) => i + 1)],
    failureNote: "0번에 나머지가 모두 바로 이어져 있어요.",
  },
]);

export const bfsRippleRings: Problem = {
  id: "c:bfs-ripple-rings",
  slug: "bfs-ripple-rings",
  source: "curated",
  topic: "bfs",
  level: 1,
  title: "물결이 닿는 순서",
  summary: "돌을 던진 곳에서 물결이 한 겹씩 닿는 곳들을 묶어요",
  statement: [
    "연못에 연잎이 `n`개 떠 있고 0번부터 `n-1`번까지 번호가 있어요. 물길 `links`의 `[a, b]`는 두 연잎이 물길로 바로 이어져 있다는 뜻이에요.",
    "",
    "노디가 `start` 연잎에 돌을 던지면 물결이 퍼져요. 물결은 1초마다 **이어진 연잎으로 한 칸씩** 퍼지고, 같은 연잎에 두 번 닿지는 않아요.",
    "",
    "0초에 닿는 연잎(start), 1초에 닿는 연잎들, 2초에 닿는 연잎들, … 을 차례로 묶어서 반환해 주세요. 한 묶음 안의 번호는 **오름차순**이고, 물결이 닿지 않는 연잎은 넣지 않아요.",
  ].join("\n"),
  inputFormat: "`n`: 연잎 수, `links`: `[a, b]` 물길 목록, `start`: 돌을 던진 연잎이에요.",
  outputFormat: "i번째 원소가 i초에 물결이 닿는 연잎 번호(오름차순) 리스트인 리스트",
  constraints: [
    "1 ≤ n ≤ 1,000",
    "0 ≤ links의 길이 ≤ 3,000",
    "a ≠ b, 같은 물길은 두 번 주어지지 않아요",
    "0 ≤ start < n",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "연잎 수" },
      {
        name: "links",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "물길 목록",
      },
      { name: "start", type: { python: "int", javascript: "number", java: "int" }, description: "돌을 던진 연잎" },
    ],
    returns: {
      type: { python: "list[list[int]]", javascript: "number[][]", java: "List<List<Integer>>" },
      description: "초마다 물결이 닿는 연잎들",
    },
  },
  starterCode: {
    python: ["def solution(n, links, start):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, links, start) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<List<Integer>> solution(int n, int[][] links, int start) {",
      "        List<List<Integer>> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "시작점에서 **가까운 곳부터 한 겹씩** 퍼져요 → **BFS**예요.",
        "",
        "BFS는 거리 0인 곳, 거리 1인 곳들, 거리 2인 곳들 … 순서로 방문해요. 물결의 '초'가 곧 BFS의 **거리**예요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 연잎마다 이어진 연잎 목록(인접 리스트)을 만들어요.",
        "2. `dist` 배열을 -1로 채우고 `dist[start] = 0`, 큐에 start를 넣어요.",
        "3. 큐에서 u를 꺼내, 이어진 v 중 `dist[v]`가 -1인 곳은 `dist[v] = dist[u] + 1`로 적고 큐에 넣어요.",
        "4. 끝나면 dist 값이 같은 연잎끼리 묶어요. 번호 순으로 훑으며 묶으면 저절로 오름차순이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = [-1] * n, dist[start] = 0, queue = [start]",
        "while queue가 비어 있지 않은 동안:",
        "    u = queue 앞에서 꺼내기",
        "    for v in graph[u]:",
        "        if dist[v] == -1:",
        "            dist[v] = dist[u] + 1",
        "            queue 뒤에 v 넣기",
        "rings = 빈 묶음 (max(dist) + 1)개",
        "for i in 0..n-1: dist[i] ≥ 0이면 rings[dist[i]]에 i 추가",
        "return rings",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["BFS로 거리를 적는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "while queue:",
            "    u = queue.popleft()",
            "    for v in graph[u]:",
            "        if dist[v] == -1:",
            "            dist[v] = ______",
            "            queue.append(v)",
          ].join("\n"),
          javascript: [
            "for (let head = 0; head < queue.length; head++) {",
            "  const u = queue[head];",
            "  for (const v of graph[u]) {",
            "    if (dist[v] === -1) {",
            "      dist[v] = ______;",
            "      queue.push(v);",
            "    }",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "while (!queue.isEmpty()) {",
            "    int u = queue.poll();",
            "    for (int v : graph.get(u)) {",
            "        if (dist[v] == -1) {",
            "            dist[v] = ______;",
            "            queue.offer(v);",
            "        }",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["level-order"],
  signalIds: ["sig-spread-simultaneous"],
  visualization: {
    presets: [
      problemPreset(
        "ripple-rings-ex1",
        "graph-bfs",
        "예제 1 물결",
        "큐에서 가까운 연잎부터 꺼내요. 한 겹이 모두 끝나야 다음 겹으로 넘어가요.",
        [
          6,
          [
            [0, 1],
            [0, 2],
            [1, 3],
            [2, 3],
            [3, 4],
          ],
          0,
        ],
      ),
    ],
  },
  estimatedMinutes: 10,
  xp: 10,
};
