import type { Problem } from "@/types/content";

export const bfsRumorDays: Problem = {
  id: "c:bfs-rumor-days",
  slug: "bfs-rumor-days",
  source: "curated",
  topic: "bfs",
  level: 4,
  title: "소문이 다 퍼지는 날",
  summary: "여러 곳에서 동시에 퍼지는 소문이 모두에게 닿는 날을 구해요",
  statement: [
    "노디 마을은 격자 모양이에요. 지도 `town`에서 `'R'`은 **이미 소문을 아는** 주민, `'P'`는 아직 모르는 주민, `'.'`은 빈 땅이에요.",
    "",
    "하루가 지날 때마다, 소문을 아는 주민은 **상하좌우**로 붙은 모르는 주민 모두에게 소문을 전해요. 빈 땅은 소문을 건네줄 수 없어요.",
    "",
    "모든 주민이 소문을 알게 되는 데 **며칠**이 걸리는지 반환해 주세요. 처음부터 모두 알고 있으면 `0`, 끝까지 모르는 주민이 남으면 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`town`: 길이가 같은 문자열들의 리스트예요.",
  outputFormat: "걸리는 날 수 (정수, 불가능하면 -1)",
  constraints: ["1 ≤ 행 수, 열 수 ≤ 100", "각 문자는 'R', 'P', '.' 중 하나예요."],
  signature: {
    name: "solution",
    params: [{ name: "town", type: { python: "list[str]", javascript: "string[]" }, description: "마을 지도" }],
    returns: { type: { python: "int", javascript: "number" }, description: "모두 알게 되는 날" },
  },
  starterCode: {
    python: ["def solution(town):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(town) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [["RPP", "PP.", ".PP"]],
      expected: 4,
      explanation: "1일째 (0,1)(1,0), 2일째 (0,2)(1,1), 3일째 (2,1), 4일째 (2,2)가 알게 돼요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [["RPPPR"]],
      expected: 2,
      explanation: "양 끝에서 동시에 퍼져서 2일이면 가운데까지 닿아요. 한쪽씩 따로 계산하면 안 돼요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [["R.R"]],
      expected: 0,
      failureNote: "모르는 주민이 없으면 0일이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [["RP.P"]],
      expected: -1,
      failureNote: "빈 땅 너머의 주민은 끝까지 몰라요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [["PPP"]],
      expected: -1,
      failureNote: "소문을 아는 사람이 아무도 없어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [["R..", ".P.", "..R"]],
      expected: -1,
      failureNote: "가운데 주민은 누구와도 붙어 있지 않아요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: [["PPPP", "PRPP", "PPPP", "PPPR"]],
      expected: 3,
      failureNote: "두 곳에서 동시에 퍼져요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 100 }, (_, r) =>
          Array.from({ length: 100 }, (_, c) => (r === 0 && c === 0 ? "R" : "P")).join(""),
        ),
      ],
      expected: 198,
      failureNote: "100×100 마을의 한 구석에서 퍼져요.",
    },
    {
      id: "hid-7",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 100 }, (_, r) =>
          Array.from({ length: 100 }, (_, c) => ((r * 100 + c) % 3 === 0 ? "R" : "P")).join(""),
        ),
      ],
      expected: 1,
      failureNote: "소문을 아는 주민이 3,000명 넘게 흩어져 있어요. 한 명씩 따로 BFS를 돌리면 너무 느려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "여러 곳에서 **동시에** 한 겹씩 퍼져요 → **멀티 소스 BFS**예요.",
        "",
        "출발점마다 BFS를 따로 돌리면 출발점 수 × 칸 수만큼 걸려요. 모든 출발점을 **처음부터 한 큐에** 넣으면 BFS 한 번으로 끝나요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 모든 'R' 칸을 거리 0으로 적고 큐에 넣어요. 'P' 칸은 거리 -1이에요.",
        "2. 보통 BFS처럼 퍼지되, **'P'이고 거리 -1인 칸**으로만 가요.",
        "3. 끝난 뒤 거리 -1인 'P'가 남아 있으면 -1, 아니면 거리의 최댓값이 답이에요.",
        "",
        '한 큐에 넣으면 "1일째 퍼진 칸들 → 2일째 퍼진 칸들 → …" 순서로 자연스럽게 처리돼요.',
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "queue = 모든 R 칸 (거리 0)",
        "while queue:",
        "    (r, c) = 앞에서 꺼내기",
        "    for 네 방향 (nr, nc):",
        "        if 격자 안 and town[nr][nc] == 'P' and dist[nr][nc] == -1:",
        "            dist[nr][nc] = dist[r][c] + 1; queue 뒤에 추가",
        "if 거리 -1인 P가 있으면: return -1",
        "return 거리 최댓값 (없으면 0)",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["시작할 때 모든 출발점을 큐에 넣는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "queue = deque()",
            "for r in range(rows):",
            "    for c in range(cols):",
            "        if ______:",
            "            dist[r][c] = 0",
            "            queue.append((r, c))",
          ].join("\n"),
          javascript: [
            "const queue = [];",
            "for (let r = 0; r < rows; r += 1) {",
            "  for (let c = 0; c < cols; c += 1) {",
            "    if (______) {",
            "      dist[r][c] = 0;",
            "      queue.push([r, c]);",
            "    }",
            "  }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["multi-source-bfs", "grid-shortest-path"],
  signalIds: ["sig-spread-simultaneous", "sig-grid-neighbors"],
  estimatedMinutes: 25,
  xp: 40,
};
