import type { Problem } from "@/types/content";

export const bfsSafeDial: Problem = {
  id: "c:bfs-safe-dial",
  slug: "bfs-safe-dial",
  source: "curated",
  topic: "bfs",
  level: 5,
  title: "금고 다이얼",
  summary: "다이얼 상태를 노드로 보고 비밀번호까지 최소 회전 수를 구해요",
  statement: [
    '노디의 금고에는 숫자 바퀴가 **4개** 달린 다이얼이 있어요. 처음에는 `"0000"`이에요.',
    "",
    "한 번 돌리면 바퀴 **하나**를 한 칸 올리거나 내릴 수 있어요. 바퀴는 둥글어서 9 다음은 0, 0 이전은 9예요.",
    "",
    "그런데 금고가 낡아서, `jammed`에 적힌 숫자 조합이 **화면에 한 번이라도 나오면** 다이얼이 걸려서 더는 못 돌려요.",
    "",
    "비밀번호 `target`을 맞추는 **최소 회전 횟수**를 반환해 주세요. 맞출 수 없으면 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`target`: 네 자리 숫자 문자열, `jammed`: 네 자리 숫자 문자열 리스트예요.",
  outputFormat: "최소 회전 횟수 (정수, 불가능하면 -1)",
  constraints: ["target은 jammed에 없어요.", "0 ≤ jammed의 길이 ≤ 5,000"],
  signature: {
    name: "solution",
    params: [
      { name: "target", type: { python: "str", javascript: "string" }, description: "비밀번호" },
      { name: "jammed", type: { python: "list[str]", javascript: "string[]" }, description: "걸리는 조합 목록" },
    ],
    returns: { type: { python: "int", javascript: "number" }, description: "최소 회전 횟수" },
  },
  starterCode: {
    python: ["def solution(target, jammed):", "    answer = -1", "    return answer", ""].join("\n"),
    javascript: ["function solution(target, jammed) {", "  let answer = -1;", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["0202", ["0100", "0001", "0201"]],
      expected: 6,
      explanation:
        "바퀴 두 개를 두 칸씩 올리면 4번이지만, 첫 회전으로 갈 수 있는 0100과 0001이 걸려 있어요. 다른 바퀴를 한 번 돌렸다가 되돌려야 해서 6번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: ["0009", []],
      expected: 1,
      explanation: "0에서 내리면 바로 9라서 1번이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["0000", []],
      expected: 0,
      failureNote: "이미 맞춰져 있으면 0번이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: ["1234", ["0000"]],
      expected: -1,
      failureNote: "처음 조합부터 걸려 있어서 돌릴 수 없어요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["8888", ["8887", "8889", "8878", "8898", "8788", "8988", "7888", "9888"]],
      expected: -1,
      failureNote: "비밀번호 바로 옆 조합이 모두 걸려서 맞출 수 없어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: ["5555", []],
      expected: 20,
      failureNote: "바퀴마다 5칸씩, 20번이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: ["1919", ["1000"]],
      expected: 4,
      failureNote: "바퀴를 돌리는 방향을 잘 골라야 해요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [
        "5555",
        Array.from({ length: 5000 }, (_, i) => String((i * 7 + 3) % 10000).padStart(4, "0")).filter(
          (s) => s !== "5555" && s !== "0000",
        ),
      ],
      expected: 20,
      failureNote: "걸리는 조합이 5,000개 가까이 돼요.",
    },
    {
      id: "hid-7",
      visibility: "hidden",
      purpose: "stress",
      args: [
        "4637",
        Array.from({ length: 4000 }, (_, i) => String(i * 2 + 1).padStart(4, "0")).filter((s) => s !== "4637"),
      ],
      expected: 16,
      failureNote: "홀수로 끝나는 조합이 거의 다 걸려요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"최소 회전 횟수" → BFS예요. 이번엔 칸이 아니라 **다이얼에 보이는 조합 하나하나가 노드**예요 → **상태 공간 BFS**.',
        "",
        "조합은 0000 ~ 9999, 딱 10,000가지라 모두 방문해도 금방이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        '1. 걸리는 조합을 **집합**에 넣어요. "0000"이 걸려 있으면 바로 -1이에요.',
        '2. "0000"에서 BFS를 시작해요. 한 조합의 이웃은 **8개**예요 (바퀴 4개 × 올리기/내리기).',
        "3. 이웃이 걸리는 조합이거나 이미 본 조합이면 건너뛰어요.",
        "4. target을 꺼내면 그 거리가 답이에요.",
        "",
        "`jammed`를 리스트 그대로 두고 `in`으로 찾으면 매번 5,000개를 훑어서 느려요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "if '0000' in jammed: return -1",
        "dist = {'0000': 0}; queue = ['0000']",
        "while queue:",
        "    s = 앞에서 꺼내기",
        "    if s == target: return dist[s]",
        "    for i in 0..3, d in (+1, -1):",
        "        t = s의 i번째 숫자를 (숫자 + d) % 10 으로 바꾼 조합",
        "        if t not in jammed and t not in dist:",
        "            dist[t] = dist[s] + 1; queue 뒤에 t",
        "return -1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["이웃 조합 8개를 만드는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(4):",
            "    for d in (1, -1):",
            "        digit = (int(s[i]) + d) % 10",
            "        t = s[:i] + str(digit) + s[i + 1:]",
            "        if t not in jammed and ______:",
            "            dist[t] = dist[s] + 1",
            "            queue.append(t)",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < 4; i += 1) {",
            "  for (const d of [1, 9]) {   // -1 대신 +9 하면 음수가 안 나와요",
            "    const digit = (Number(s[i]) + d) % 10;",
            "    const t = s.slice(0, i) + digit + s.slice(i + 1);",
            "    if (!jammed.has(t) && ______) {",
            "      dist.set(t, dist.get(s) + 1);",
            "      queue.push(t);",
            "    }",
            "  }",
            "}",
          ].join("\n"),
        },
        caption: "Python의 %는 음수에도 0 ~ 9를 주지만, JavaScript의 %는 -1을 줄 수 있어요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["state-space-bfs"],
  signalIds: ["sig-shortest-steps"],
  estimatedMinutes: 30,
  xp: 50,
};
