import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [3, 5, 4],
    expected: 6,
    explanation:
      "B 채우기(0,5) → B를 A에 붓기(3,2) → A 비우기(0,2) → B를 A에 붓기(2,0) → B 채우기(2,5) → B를 A에 붓기(3,4). 6번이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [2, 4, 3],
    expected: -1,
    explanation: "2리터와 4리터로는 짝수 양만 만들 수 있어요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: [5, 7, 0],
    expected: 0,
    failureNote: "처음부터 0리터가 담겨 있어요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "edge",
    args: [4, 9, 9],
    expected: 1,
    failureNote: "B를 채우기만 하면 돼요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "edge",
    args: [4, 9, 10],
    expected: -1,
    failureNote: "어느 물통에도 10리터는 담을 수 없어요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "basic",
    args: [7, 11, 2],
    expected: 14,
    failureNote: "여러 번 붓고 비워야 해요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "tricky",
    args: [6, 4, 2],
    expected: 2,
    failureNote: "A가 B보다 클 수도 있어요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [299, 300, 150],
    expected: 596,
    failureNote: "큰 물통 두 개로 596번이나 붓고 비워야 해요.",
  },
  {
    id: "hid-7",
    visibility: "hidden",
    purpose: "stress",
    args: [300, 150, 100],
    expected: -1,
    failureNote: "만들 수 없는 양이라 갈 수 있는 상태를 모두 살펴본 뒤에야 -1인 걸 알아요.",
  },
]);

export const bfsTwoBuckets: Problem = {
  id: "c:bfs-two-buckets",
  slug: "bfs-two-buckets",
  source: "curated",
  topic: "bfs",
  level: 5,
  title: "두 물통으로 물 재기",
  summary: "두 물통의 물 양을 상태로 보고 원하는 양을 만드는 최소 동작 수를 구해요",
  statement: [
    "노디에게는 눈금 없는 물통 두 개가 있어요. A는 `a`리터, B는 `b`리터까지 담을 수 있고, 처음엔 둘 다 비어 있어요.",
    "",
    "한 번의 동작으로 다음 중 하나를 할 수 있어요.",
    "",
    "1. A 또는 B를 수돗물로 **가득 채우기**",
    "2. A 또는 B를 **모두 비우기**",
    "3. A의 물을 B에 **붓기** (A가 비거나 B가 가득 찰 때까지), 또는 B의 물을 A에 붓기",
    "",
    "두 물통 중 **하나에** 정확히 `k`리터가 담기게 하는 **최소 동작 수**를 반환해 주세요. 만들 수 없으면 `-1`이에요.",
  ].join("\n"),
  inputFormat: "`a`, `b`: 두 물통의 크기, `k`: 만들고 싶은 양이에요.",
  outputFormat: "최소 동작 수 (정수, 불가능하면 -1)",
  constraints: ["1 ≤ a, b ≤ 300", "0 ≤ k ≤ 300"],
  signature: {
    name: "solution",
    params: [
      { name: "a", type: { python: "int", javascript: "number", java: "int" }, description: "A 물통 크기" },
      { name: "b", type: { python: "int", javascript: "number", java: "int" }, description: "B 물통 크기" },
      { name: "k", type: { python: "int", javascript: "number", java: "int" }, description: "만들 양" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 동작 수" },
  },
  starterCode: {
    python: ["def solution(a, b, k):", "    answer = -1", "    return answer", ""].join("\n"),
    javascript: ["function solution(a, b, k) {", "  let answer = -1;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int a, int b, int k) {",
      "        int answer = -1;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"최소 동작 수" → BFS예요. 노드는 **(A에 든 양, B에 든 양)** 이라는 **상태**예요.',
        "",
        "상태는 최대 301 × 301가지라 모두 방문할 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. (0, 0)에서 BFS를 시작해요.",
        "2. 한 상태 (x, y)에서 갈 수 있는 상태는 **6가지**예요.",
        "   - 채우기: (a, y), (x, b)",
        "   - 비우기: (0, y), (x, 0)",
        "   - A → B 붓기: 옮기는 양 `m = min(x, b - y)` → (x − m, y + m)",
        "   - B → A 붓기: `m = min(y, a - x)` → (x + m, y − m)",
        "3. 상태를 꺼냈을 때 x == k 또는 y == k면 그 거리가 답이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dist = {(0, 0): 0}; queue = [(0, 0)]",
        "while queue:",
        "    (x, y) = 앞에서 꺼내기",
        "    if x == k or y == k: return dist[(x, y)]",
        "    for (nx, ny) in 6가지 다음 상태:",
        "        if (nx, ny) not in dist:",
        "            dist[(nx, ny)] = dist[(x, y)] + 1; queue 뒤에 추가",
        "return -1",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["붓기 두 가지를 만드는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "m = min(x, b - y)          # A → B",
            "pour_ab = (x - m, y + m)",
            "m = ______                 # B → A",
            "pour_ba = (x + m, y - m)",
          ].join("\n"),
          javascript: [
            "let m = Math.min(x, b - y);   // A → B",
            "const pourAB = [x - m, y + m];",
            "m = ______;                   // B → A",
            "const pourBA = [x + m, y - m];",
          ].join("\n"),
          java: [
            "int m = Math.min(x, b - y);        // A → B",
            "int[] pourAB = {x - m, y + m};",
            "m = ______;                        // B → A",
            "int[] pourBA = {x + m, y - m};",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["state-space-bfs"],
  signalIds: ["sig-shortest-steps"],
  estimatedMinutes: 30,
  xp: 50,
};
