import type { Problem } from "@/types/content";

export const dpBestStreak: Problem = {
  id: "c:dp-best-streak",
  slug: "dp-best-streak",
  source: "curated",
  topic: "dp",
  level: 4,
  title: "가장 좋은 연속 기간",
  summary: "i일에 끝나는 최대 합 = max(i일만, 전날까지 + i일)",
  statement: [
    "노디의 도토리 가게 장부에 날마다 이익(음수면 손해)이 `profits`로 적혀 있어요.",
    "",
    "**연속한 하루 이상**의 기간 중 이익 합이 **가장 큰** 값을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`profits`: 날마다의 이익이에요.",
  outputFormat: "연속 기간 이익 합의 최댓값",
  constraints: ["1 ≤ profits의 길이 ≤ 100,000", "−10,000 ≤ 이익 ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "profits",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "날마다 이익",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 합" },
  },
  starterCode: {
    python: ["def solution(profits):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(profits) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[] profits) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]],
      expected: 6,
      explanation: "4, −1, 2, 1 기간이 6이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[-3, -1, -2]],
      expected: -1,
      explanation: "모두 손해여도 하루는 골라야 해요. −1이에요 (0이 아니에요).",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[5]],
      expected: 5,
      failureNote: "하루뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[1, 2, 3]],
      expected: 6,
      failureNote: "전부 더해 6이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[5, -9, 6]],
      expected: 6,
      failureNote: "앞의 5를 이어 가면 오히려 손해예요. 전날까지의 합이 음수면 버리고 새로 시작해요. 6이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => ((i * 7919) % 20001) - 10000)],
      expected: 77468,
      failureNote: "10만 일이에요. 모든 기간을 더해 보면(O(N²)) 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["연속 구간의 **최대 합** → 'i일에 **끝나는** 가장 좋은 기간'을 적어 가는 **1차원 DP**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 표의 뜻: `end[i]` = i일에 끝나는 기간 중 최대 합",
        "2. i일에 끝나는 기간은 'i일 하루'이거나 'i-1일에 끝나는 기간 + i일'이에요 → `end[i] = max(p[i], end[i-1] + p[i])`",
        "3. 답은 모든 `end[i]` 중 최댓값이에요.",
        "",
        "변수 하나로도 충분해요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "cur = best = profits[0]",
        "for x in profits[1:]:",
        "    cur = max(x, cur + x)",
        "    best = max(best, cur)",
        "return best",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["이어 갈지 새로 시작할지 정하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["for x in profits[1:]:", "    cur = ______", "    best = max(best, cur)"].join("\n"),
          javascript: [
            "for (let i = 1; i < profits.length; i++) {",
            "  cur = ______;",
            "  best = Math.max(best, cur);",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 1; i < profits.length; i++) {",
            "    cur = ______;",
            "    best = Math.max(best, cur);",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["linear-dp", "sequence-dp"],
  signalIds: ["sig-overlapping-subproblems"],
  estimatedMinutes: 15,
  xp: 40,
};
