import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const dpCommonSong: Problem = {
  id: "c:dp-common-song",
  slug: "dp-common-song",
  source: "curated",
  topic: "dp",
  level: 4,
  title: "두 새의 공통 노래",
  summary: "마지막 글자가 같으면 대각선 + 1, 다르면 위·왼쪽 중 큰 값 (LCS)",
  statement: [
    "숲속 두 새가 부르는 노래가 음표 문자열 `a`, `b`로 적혀 있어요. 두 노래에서 **순서를 지키며** 몇 개의 음표를 골라(연속이 아니어도 돼요) 똑같은 노래를 만들려고 해요.",
    "",
    "만들 수 있는 공통 노래의 **최대 길이**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`a`, `b`: 두 노래예요. 영어 소문자로만 되어 있어요.",
  outputFormat: "가장 긴 공통 부분 수열의 길이",
  constraints: ["1 ≤ a, b의 길이 ≤ 700"],
  signature: {
    name: "solution",
    params: [
      { name: "a", type: { python: "str", javascript: "string", java: "String" }, description: "첫째 노래" },
      { name: "b", type: { python: "str", javascript: "string", java: "String" }, description: "둘째 노래" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 길이" },
  },
  starterCode: {
    python: ["def solution(a, b):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(a, b) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String a, String b) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["acbde", "abcfe"],
      expected: 3,
      explanation: "abe(또는 ace)로 3이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: ["abc", "xyz"],
      expected: 0,
      explanation: "공통 음표가 없어 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["a", "a"],
      expected: 1,
      failureNote: "한 음표가 같아요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: ["abcd", "abcd"],
      expected: 4,
      failureNote: "완전히 같으면 전체 길이 4예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: ["aab", "aaab"],
      expected: 3,
      failureNote: "같은 글자가 여러 번 있어도 순서를 지켜 한 번씩만 써요. aab로 3이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: ["ab", "ba"],
      expected: 1,
      failureNote: "순서를 지켜야 해서 a나 b 하나, 1이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 700 }, (_, i) => "abcde"[(i * i + 3 * i) % 5]).join(""),
        Array.from({ length: 700 }, (_, i) => "abcde"[(i * 7 + (i >> 3)) % 5]).join(""),
      ],
      expected: 384,
      failureNote: "두 노래 모두 700음이에요. 부분 수열을 모두 만들어 보면 끝나지 않아요.",
    },
  ],
  judge: {
    timeLimitMs: 3000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**두 문자열**의 공통 부분(연속 아님) → **LCS**, 2차원 표를 채우는 DP예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 표의 뜻: `dp[i][j]` = a의 앞 i글자와 b의 앞 j글자의 공통 노래 최대 길이. 0행·0열은 0",
        "2. `a[i-1] == b[j-1]`이면 그 음표를 함께 써요 → `dp[i-1][j-1] + 1`",
        "3. 다르면 둘 중 하나를 버려요 → `max(dp[i-1][j], dp[i][j-1])`",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dp = (n+1) × (m+1) 표, 0으로",
        "for i in 1..n:",
        "    for j in 1..m:",
        "        if a[i-1] == b[j-1]: dp[i][j] = dp[i-1][j-1] + 1",
        "        else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])",
        "return dp[n][m]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["같은 음표일 때의 처리예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(1, n + 1):",
            "    for j in range(1, m + 1):",
            "        if a[i - 1] == b[j - 1]:",
            "            dp[i][j] = ______",
            "        else:",
            "            dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])",
          ].join("\n"),
          javascript: [
            "for (let i = 1; i <= n; i++) {",
            "  for (let j = 1; j <= m; j++) {",
            "    dp[i][j] = a[i - 1] === b[j - 1] ? ______ : Math.max(dp[i - 1][j], dp[i][j - 1]);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 1; i <= n; i++) {",
            "    for (int j = 1; j <= m; j++) {",
            "        if (a.charAt(i - 1) == b.charAt(j - 1)) dp[i][j] = ______;",
            "        else dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sequence-dp"],
  signalIds: ["sig-two-strings"],
  visualization: {
    presets: [
      problemPreset(
        "dp-common-song-ex1",
        "dp-lcs",
        "공통 노래 표 채우기",
        "같은 음표면 대각선 + 1, 다르면 위·왼쪽 중 큰 값이에요.",
        ["acbde", "abcfe"],
      ),
    ],
  },
  estimatedMinutes: 20,
  xp: 40,
};
