import type { Problem } from "@/types/content";

export const dpFruitPyramid: Problem = {
  id: "c:dp-fruit-pyramid",
  slug: "dp-fruit-pyramid",
  source: "curated",
  topic: "dp",
  level: 2,
  title: "과일 피라미드",
  summary: "아래 두 칸 중 큰 쪽을 더해 가며 꼭대기로 올라와요",
  statement: [
    "과일이 삼각형으로 쌓여 있어요. 맨 위 줄에는 1개, 그다음 줄에는 2개 … 이렇게 한 줄에 하나씩 늘어요. `pyramid[r][c]`는 r번째 줄 c번째 과일의 달콤함이에요.",
    "",
    "맨 위에서 출발해 한 줄씩 내려가며 과일을 하나씩 먹어요. `(r, c)`에서는 바로 아래 줄의 `(r+1, c)`나 `(r+1, c+1)`로만 내려갈 수 있어요.",
    "",
    "맨 아래 줄까지 먹은 달콤함 합의 **최댓값**을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`pyramid`: 줄마다 과일의 달콤함이 적힌 삼각형이에요.",
  outputFormat: "달콤함 합의 최댓값",
  constraints: ["1 ≤ 줄 수 ≤ 500", "r번째 줄에는 r + 1개가 있어요", "0 ≤ 달콤함 ≤ 100"],
  signature: {
    name: "solution",
    params: [
      {
        name: "pyramid",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "과일 피라미드",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 달콤함 합" },
  },
  starterCode: {
    python: ["def solution(pyramid):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(pyramid) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[][] pyramid) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[[7], [3, 8], [8, 1, 0], [2, 7, 4, 4], [4, 5, 2, 6, 5]]],
      expected: 30,
      explanation: "7 → 3 → 8 → 7 → 5로 30이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[[9]]],
      expected: 9,
      explanation: "한 줄이면 그 과일 하나예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "basic",
      args: [[[1], [2, 3]]],
      expected: 4,
      failureNote: "아래 줄에서 큰 3을 골라 4예요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[[1], [9, 1], [1, 1, 100]]],
      expected: 102,
      failureNote: "처음에 큰 9로 내려가면 100에 닿을 수 없어요. 1 → 1 → 100이 102예요. 매번 큰 쪽만 고르면 틀려요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [[[0], [0, 0], [0, 0, 0]]],
      expected: 0,
      failureNote: "모두 0이면 0이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 500 }, (_, r) => Array.from({ length: r + 1 }, (_, c) => (r * 37 + c * 11) % 100))],
      expected: 31981,
      failureNote: "500줄이에요. 내려가는 길은 2^499가지라 모두 볼 수 없어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "한 칸에서 갈 수 있는 곳이 두 군데뿐인 격자에서 **최대 합** → **격자 DP**예요. 매번 큰 쪽만 고르는 욕심은 틀릴 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "**아래에서 위로** 올라오면 간단해요.",
        "",
        "1. 표의 뜻: `best[r][c]` = (r, c)에서 출발해 맨 아래까지 먹는 최대 합",
        "2. 맨 아래 줄은 과일 그대로예요.",
        "3. `best[r][c] = pyramid[r][c] + max(best[r+1][c], best[r+1][c+1])`",
        "4. 답은 `best[0][0]`이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "best = 맨 아래 줄 복사",
        "for r in 줄수-2 .. 0:",
        "    for c in 0 .. r:",
        "        best[c] = pyramid[r][c] + max(best[c], best[c + 1])",
        "return best[0]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["아래 두 칸 중 큰 쪽을 더하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "best = pyramid[-1][:]",
            "for r in range(len(pyramid) - 2, -1, -1):",
            "    for c in range(r + 1):",
            "        best[c] = pyramid[r][c] + ______",
            "return best[0]",
          ].join("\n"),
          javascript: [
            "const best = [...pyramid[pyramid.length - 1]];",
            "for (let r = pyramid.length - 2; r >= 0; r--) {",
            "  for (let c = 0; c <= r; c++) best[c] = pyramid[r][c] + ______;",
            "}",
            "return best[0];",
          ].join("\n"),
          java: [
            "int[] best = pyramid[pyramid.length - 1].clone();",
            "for (int r = pyramid.length - 2; r >= 0; r--) {",
            "    for (int c = 0; c <= r; c++) best[c] = pyramid[r][c] + ______;",
            "}",
            "return best[0];",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["grid-dp"],
  signalIds: ["sig-overlapping-subproblems", "sig-best-choice-sequence"],
  estimatedMinutes: 12,
  xp: 20,
};
