import type { Problem } from "@/types/content";

export const dpMinTrail: Problem = {
  id: "c:dp-min-trail",
  slug: "dp-min-trail",
  source: "curated",
  topic: "dp",
  level: 2,
  title: "가장 편한 산책로",
  summary: "한 칸까지의 최소 피로 = min(위, 왼쪽) + 이 칸",
  statement: [
    "숲 지도의 칸마다 지나갈 때 드는 피로도 `fatigue[r][c]`가 적혀 있어요. 노디는 왼쪽 위에서 오른쪽 아래까지 **오른쪽이나 아래로만** 움직여요.",
    "",
    "지나가는 모든 칸(출발·도착 칸 포함)의 피로도 합의 **최솟값**을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`fatigue`: 칸마다 피로도가 적힌 2차원 리스트예요.",
  outputFormat: "피로도 합의 최솟값",
  constraints: ["1 ≤ 행 수, 열 수 ≤ 300", "0 ≤ 피로도 ≤ 100"],
  signature: {
    name: "solution",
    params: [
      {
        name: "fatigue",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "칸마다 피로도",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 피로도 합" },
  },
  starterCode: {
    python: ["def solution(fatigue):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(fatigue) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int[][] fatigue) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        [
          [1, 3, 1],
          [1, 5, 1],
          [4, 2, 1],
        ],
      ],
      expected: 7,
      explanation: "1 → 3 → 1 → 1 → 1 순서로 7이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[[5]]],
      expected: 5,
      explanation: "칸이 하나면 그 칸의 피로도예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[[1, 2, 3]]],
      expected: 6,
      failureNote: "한 줄이면 모든 칸을 지나서 6이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [[[1], [2], [3]]],
      expected: 6,
      failureNote: "한 열이어도 6이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        [
          [1, 1, 9],
          [9, 1, 9],
          [9, 1, 1],
        ],
      ],
      expected: 5,
      failureNote: "처음에 싼 쪽만 따라가면 막힐 수 있어요. 표를 채워서 비교하면 5예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 300 }, (_, r) => Array.from({ length: 300 }, (_, c) => (r * 31 + c * 17) % 100))],
      expected: 21783,
      failureNote: "300 × 300 지도예요. 모든 길을 비교하면 끝나지 않아요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["격자에서 오른쪽·아래로만 가며 **최소 합** → **격자 DP**예요. 경로의 수 대신 최솟값을 적어요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 표의 뜻: `best[r][c]` = (r, c)까지 오는 최소 피로도 합",
        "2. `best[r][c] = min(위, 왼쪽) + fatigue[r][c]`",
        "3. 첫 줄은 왼쪽에서만, 첫 열은 위에서만 와요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for r in 0..R-1:",
        "    for c in 0..C-1:",
        "        if r == 0 and c == 0: best = fatigue[0][0]",
        "        elif r == 0: best[r][c] = best[r][c-1] + fatigue[r][c]",
        "        elif c == 0: best[r][c] = best[r-1][c] + fatigue[r][c]",
        "        else: best[r][c] = min(best[r-1][c], best[r][c-1]) + fatigue[r][c]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["위·왼쪽 중 작은 쪽을 고르는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for r in range(rows):",
            "    for c in range(cols):",
            "        if r == 0 and c == 0:",
            "            continue",
            "        up = best[r - 1][c] if r > 0 else INF",
            "        left = best[r][c - 1] if c > 0 else INF",
            "        best[r][c] += ______",
          ].join("\n"),
          javascript: [
            "for (let r = 0; r < rows; r++) {",
            "  for (let c = 0; c < cols; c++) {",
            "    if (r === 0 && c === 0) continue;",
            "    const up = r > 0 ? best[r - 1][c] : Infinity;",
            "    const left = c > 0 ? best[r][c - 1] : Infinity;",
            "    best[r][c] += ______;",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int r = 0; r < rows; r++) {",
            "    for (int c = 0; c < cols; c++) {",
            "        if (r == 0 && c == 0) continue;",
            "        int up = r > 0 ? best[r - 1][c] : Integer.MAX_VALUE;",
            "        int left = c > 0 ? best[r][c - 1] : Integer.MAX_VALUE;",
            "        best[r][c] += ______;",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["grid-dp"],
  signalIds: ["sig-overlapping-subproblems", "sig-best-choice-sequence"],
  estimatedMinutes: 12,
  xp: 20,
};
