import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: ["aab"],
    expected: 1,
    explanation: "aa | b로 한 번 잘라요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: ["racecar"],
    expected: 0,
    explanation: "이미 회문이라 0이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "edge",
    args: ["a"],
    expected: 0,
    failureNote: "한 글자는 회문이라 0이에요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "basic",
    args: ["abc"],
    expected: 2,
    failureNote: "모두 한 글자씩 잘라 2번이에요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: ["abacdc"],
    expected: 1,
    failureNote: "aba | cdc로 한 번이에요. 앞에서부터 가장 짧은 회문(a)만 떼면 더 많이 잘라요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: ["aabbaa"],
    expected: 0,
    failureNote: "전체가 회문이라 0이에요. aa | bb | aa로 자르면 안 돼요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 500 }, (_, i) => "aab"[(i * i) % 3]).join("")],
    expected: 0,
    failureNote: "500글자예요. 자르는 방법을 모두 해 보면 2^499가지예요.",
  },
]);

export const dpPalindromeCuts: Problem = {
  id: "c:dp-palindrome-cuts",
  slug: "dp-palindrome-cuts",
  source: "curated",
  topic: "dp",
  level: 5,
  title: "회문 조각으로 자르기",
  summary: "회문 여부 표를 먼저 만들고, i글자까지의 최소 자르기 수를 채워요",
  statement: [
    "노디가 리본에 적힌 글자 `ribbon`을 잘라 여러 조각으로 나누려고 해요. 모든 조각이 **회문**(앞뒤로 읽어도 같은 문자열, 예: `aba`, `aa`, `c`)이어야 해요.",
    "",
    "필요한 **최소 자르기 횟수**를 반환해 주세요. 이미 전체가 회문이면 0이에요.",
  ].join("\n"),
  inputFormat: "`ribbon`: 영어 소문자 문자열이에요.",
  outputFormat: "최소 자르기 횟수",
  constraints: ["1 ≤ ribbon의 길이 ≤ 500"],
  signature: {
    name: "solution",
    params: [
      { name: "ribbon", type: { python: "str", javascript: "string", java: "String" }, description: "리본 글자" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 자르기 횟수" },
  },
  starterCode: {
    python: ["def solution(ribbon):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(ribbon) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String ribbon) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 3000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "자르는 위치마다 선택이 있고 **최소** 횟수를 물어요 → '앞 i글자까지의 최소'를 적어 가는 **DP**예요. 회문인지도 표로 미리 구해요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 회문 표: `pal[i][j]` = i~j가 회문인가? 양 끝 글자가 같고 안쪽(`pal[i+1][j-1]`)이 회문이면 참이에요.",
        "2. `cuts[j]` = 앞 j+1글자(0~j)를 회문 조각으로 나누는 최소 자르기 횟수",
        "3. 마지막 조각이 i~j라면: i가 0이면 0번, 아니면 `cuts[i-1] + 1`. 이 중 최솟값이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "for j in 0..n-1:",
        "    cuts[j] = j                   # 최악: 한 글자씩",
        "    for i in 0..j:",
        "        if s[i] == s[j] and (j - i < 2 or pal[i+1][j-1]):",
        "            pal[i][j] = true",
        "            cuts[j] = 0 if i == 0 else min(cuts[j], cuts[i-1] + 1)",
        "return cuts[n-1]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["마지막 조각이 회문일 때의 처리예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for j in range(n):",
            "    cuts[j] = j",
            "    for i in range(j + 1):",
            "        if s[i] == s[j] and (j - i < 2 or pal[i + 1][j - 1]):",
            "            pal[i][j] = True",
            "            cuts[j] = 0 if i == 0 else min(cuts[j], ______)",
          ].join("\n"),
          javascript: [
            "for (let j = 0; j < n; j++) {",
            "  cuts[j] = j;",
            "  for (let i = 0; i <= j; i++) {",
            "    if (s[i] === s[j] && (j - i < 2 || pal[i + 1][j - 1])) {",
            "      pal[i][j] = true;",
            "      cuts[j] = i === 0 ? 0 : Math.min(cuts[j], ______);",
            "    }",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int j = 0; j < n; j++) {",
            "    cuts[j] = j;",
            "    for (int i = 0; i <= j; i++) {",
            "        if (s.charAt(i) == s.charAt(j) && (j - i < 2 || pal[i + 1][j - 1])) {",
            "            pal[i][j] = true;",
            "            cuts[j] = i == 0 ? 0 : Math.min(cuts[j], ______);",
            "        }",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sequence-dp"],
  signalIds: ["sig-overlapping-subproblems", "sig-best-choice-sequence"],
  estimatedMinutes: 30,
  xp: 50,
};
