import type { Problem } from "@/types/content";

export const dpPicnicBag: Problem = {
  id: "c:dp-picnic-bag",
  slug: "dp-picnic-bag",
  source: "curated",
  topic: "dp",
  level: 3,
  title: "소풍 가방 싸기",
  summary: "무게 한도별 최대 가치 표를 물건마다 큰 무게부터 고쳐요 (0/1 배낭)",
  statement: [
    "노디가 소풍 가방에 간식을 담아요. i번 간식은 무게 `weights[i]`, 행복 점수 `values[i]`이고, 간식마다 **하나씩만** 있어요.",
    "",
    "가방에는 무게 합이 `limit` 이하까지만 들어가요. 담을 수 있는 **행복 점수 합의 최댓값**을 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`weights`, `values`: 간식별 무게와 행복 점수, `limit`: 가방 한도예요.",
  outputFormat: "행복 점수 합의 최댓값",
  constraints: ["1 ≤ 간식 수 ≤ 50", "1 ≤ 무게 ≤ 10,000", "0 ≤ 행복 점수 ≤ 1,000", "0 ≤ limit ≤ 10,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "weights",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "간식 무게",
      },
      {
        name: "values",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "행복 점수",
      },
      { name: "limit", type: { python: "int", javascript: "number", java: "int" }, description: "가방 한도" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최대 행복 점수" },
  },
  starterCode: {
    python: ["def solution(weights, values, limit):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(weights, values, limit) {", "  let answer = 0;", "  return answer;", "}", ""].join(
      "\n",
    ),
    java: [
      "class Solution {",
      "    public int solution(int[] weights, int[] values, int limit) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[6, 4, 3, 5], [13, 8, 6, 12], 7],
      expected: 14,
      explanation: "무게 4 + 3을 담으면 8 + 6 = 14가 가장 커요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[5], [10], 4],
      expected: 0,
      explanation: "하나도 못 담아서 0이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [[1, 2], [5, 6], 0],
      expected: 0,
      failureNote: "한도가 0이면 0이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [[1], [10], 5],
      expected: 10,
      failureNote:
        "같은 간식은 한 번만 담아요. 무게를 작은 쪽부터 돌면 같은 간식을 여러 번 담아 50이 나와요. 큰 쪽부터 돌아야 10이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[5, 4, 3], [10, 7, 7], 7],
      expected: 14,
      failureNote: "점수 대비 무게가 좋아 보이는 순서대로 고르면 손해일 수 있어요. 4 + 3으로 14예요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[2, 3, 4], [3, 4, 5], 9],
      expected: 12,
      failureNote: "모두 담으면 무게 9, 점수 12예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 50 }, (_, i) => ((i * 37) % 97) + 20),
        Array.from({ length: 50 }, (_, i) => ((i * 53) % 89) + 10),
        10000,
      ],
      expected: 2680,
      failureNote: "간식 50개예요. 담을지 말지 모든 경우는 2^50가지라 불가능해요.",
    },
  ],
  judge: {
    timeLimitMs: 3000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["물건마다 **넣는다 / 안 넣는다**, 무게 **한도** 안에서 **최대** → **0/1 배낭 DP**예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 표의 뜻: `best[w]` = 무게 합이 w 이하일 때 얻는 최대 점수",
        "2. 간식 (무게 wt, 점수 v)을 하나씩 보며, w를 **큰 쪽부터** `best[w] = max(best[w], best[w - wt] + v)`",
        "",
        "큰 쪽부터 돌아야 `best[w - wt]`가 **이번 간식을 넣기 전** 값이라, 같은 간식을 두 번 넣지 않아요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "best = [0] * (limit + 1)",
        "for wt, v in 간식들:",
        "    for w in limit .. wt (거꾸로):",
        "        best[w] = max(best[w], best[w - wt] + v)",
        "return best[limit]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["넣을지 말지 비교하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for wt, v in zip(weights, values):",
            "    for w in range(limit, wt - 1, -1):",
            "        best[w] = max(best[w], ______)",
          ].join("\n"),
          javascript: [
            "for (let i = 0; i < weights.length; i++) {",
            "  for (let w = limit; w >= weights[i]; w--) {",
            "    best[w] = Math.max(best[w], ______);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 0; i < weights.length; i++) {",
            "    for (int w = limit; w >= weights[i]; w--) {",
            "        best[w] = Math.max(best[w], ______);",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["knapsack"],
  signalIds: ["sig-best-choice-sequence"],
  estimatedMinutes: 18,
  xp: 30,
};
