import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: ["226"],
    expected: 3,
    explanation: "BZ(2, 26), VF(22, 6), BBF(2, 2, 6) 세 가지예요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: ["06"],
    expected: 0,
    explanation: "0으로 시작해서 읽을 수 없어요. 0이에요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "basic",
    args: ["12"],
    expected: 2,
    failureNote: "AB, L 두 가지예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: ["10"],
    expected: 1,
    failureNote: "0은 혼자 글자가 될 수 없어서 J(10) 한 가지예요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "tricky",
    args: ["100"],
    expected: 0,
    failureNote: "10 다음 0이 혼자 남아 읽을 수 없어요. 0이에요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "tricky",
    args: ["27"],
    expected: 1,
    failureNote: "27은 Z(26)보다 커서 BG 한 가지예요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "edge",
    args: ["1"],
    expected: 1,
    failureNote: "A 한 가지예요.",
  },
  {
    id: "hid-6",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => "1226103"[(i * 7) % 7]).join("")],
    expected: 967618232,
    failureNote: "10만 자리예요. 읽는 방법을 하나씩 만들면 끝나지 않아요.",
  },
]);

export const dpSecretMessage: Problem = {
  id: "c:dp-secret-message",
  slug: "dp-secret-message",
  source: "curated",
  topic: "dp",
  level: 5,
  title: "숫자 암호 풀기",
  summary: "마지막 한 자리 / 두 자리가 올바른 글자인지 보고 앞의 경우 수를 더해요",
  statement: [
    '숲속 친구들은 알파벳을 숫자로 바꿔 암호를 보내요: A = 1, B = 2, …, Z = 26. 그런데 숫자를 띄어 쓰지 않아서, `"12"`는 AB(1, 2)도 되고 L(12)도 돼요.',
    "",
    '숫자 문자열 `code`를 알파벳으로 읽는 방법의 수를 **1,000,000,007로 나눈 나머지**로 반환해 주세요. `0`으로 시작하는 조각(`"0"`, `"06"`)은 글자가 될 수 없어요. 읽을 수 없으면 0이에요.',
  ].join("\n"),
  inputFormat: "`code`: 숫자로만 된 문자열이에요.",
  outputFormat: "읽는 방법의 수를 1,000,000,007로 나눈 나머지",
  constraints: ["1 ≤ code의 길이 ≤ 100,000"],
  signature: {
    name: "solution",
    params: [{ name: "code", type: { python: "str", javascript: "string", java: "String" }, description: "숫자 암호" }],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "읽는 방법의 수 (나머지)" },
  },
  starterCode: {
    python: ["def solution(code):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(code) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String code) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "글자를 한 자리 또는 두 자리로 끊는 **방법의 수** + 나머지 → 계단 오르기와 같은 모양의 **1차원 DP**예요. 0 처리만 조심하면 돼요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 표의 뜻: `ways[i]` = 앞 i자리를 읽는 방법 수. `ways[0] = 1`",
        "2. 마지막 **한 자리**가 1~9면 `ways[i] += ways[i-1]`",
        "3. 마지막 **두 자리**가 10~26이면 `ways[i] += ways[i-2]`",
        "",
        "0은 한 자리로는 못 쓰고, 10·20의 일부로만 쓸 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "ways[0] = 1",
        "for i in 1..n:",
        "    if code[i-1] != '0': ways[i] += ways[i-1]",
        "    if i >= 2 and 10 <= int(code[i-2:i]) <= 26: ways[i] += ways[i-2]",
        "    ways[i] %= MOD",
        "return ways[n]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["두 자리로 읽을 수 있는지 확인하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for i in range(1, n + 1):",
            "    if code[i - 1] != '0':",
            "        ways[i] += ways[i - 1]",
            "    if i >= 2 and ______:",
            "        ways[i] += ways[i - 2]",
            "    ways[i] %= MOD",
          ].join("\n"),
          javascript: [
            "for (let i = 1; i <= n; i++) {",
            "  if (code[i - 1] !== '0') ways[i] += ways[i - 1];",
            "  if (i >= 2) {",
            "    const two = Number(code.slice(i - 2, i));",
            "    if (______) ways[i] += ways[i - 2];",
            "  }",
            "  ways[i] %= MOD;",
            "}",
          ].join("\n"),
          java: [
            "for (int i = 1; i <= n; i++) {",
            "    if (code.charAt(i - 1) != '0') ways[i] += ways[i - 1];",
            "    if (i >= 2) {",
            "        int two = Integer.parseInt(code.substring(i - 2, i));",
            "        if (______) ways[i] += ways[i - 2];",
            "    }",
            "    ways[i] %= MOD;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["linear-dp"],
  signalIds: ["sig-count-ways-mod", "sig-overlapping-subproblems"],
  estimatedMinutes: 25,
  xp: 50,
};
