import type { Problem } from "@/types/content";

export const dpWordEdit: Problem = {
  id: "c:dp-word-edit",
  slug: "dp-word-edit",
  source: "curated",
  topic: "dp",
  level: 4,
  title: "단어 고쳐 쓰기",
  summary: "넣기·빼기·바꾸기 세 가지를 비교해 dp[i][j]를 채워요 (편집 거리)",
  statement: [
    "노디가 쓴 단어 `source`를 선생님이 적은 단어 `target`으로 고치려고 해요. 한 번에 할 수 있는 일은 세 가지예요.",
    "",
    "- 글자 하나 **넣기**",
    "- 글자 하나 **빼기**",
    "- 글자 하나를 다른 글자로 **바꾸기**",
    "",
    "`source`를 `target`으로 만드는 **최소 횟수**를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`source`, `target`: 영어 소문자 단어예요 (빈 문자열일 수도 있어요).",
  outputFormat: "최소 편집 횟수",
  constraints: ["0 ≤ source, target의 길이 ≤ 500"],
  signature: {
    name: "solution",
    params: [
      { name: "source", type: { python: "str", javascript: "string", java: "String" }, description: "고칠 단어" },
      { name: "target", type: { python: "str", javascript: "string", java: "String" }, description: "목표 단어" },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "최소 횟수" },
  },
  starterCode: {
    python: ["def solution(source, target):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(source, target) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(String source, String target) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: ["horse", "ros"],
      expected: 3,
      explanation: "h→r 바꾸기, r 빼기, e 빼기로 3번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: ["", "abc"],
      expected: 3,
      explanation: "빈 단어에서 세 글자를 넣어 3번이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: ["same", "same"],
      expected: 0,
      failureNote: "이미 같으면 0번이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: ["abc", ""],
      expected: 3,
      failureNote: "모두 빼면 3번이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: ["intention", "execution"],
      expected: 5,
      failureNote: "5번이에요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: ["ab", "ba"],
      expected: 2,
      failureNote: "바꾸기 두 번이면 2번이에요. 순서 바꾸기는 한 번에 할 수 없어요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        Array.from({ length: 500 }, (_, i) => "nodimos"[(i * 13) % 7]).join(""),
        Array.from({ length: 500 }, (_, i) => "nodimos"[(i * 11 + (i >> 2)) % 7]).join(""),
      ],
      expected: 339,
      failureNote: "두 단어 모두 500글자예요. 고치는 방법을 하나씩 해 보면 끝나지 않아요.",
    },
  ],
  judge: {
    timeLimitMs: 3000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["**두 문자열**을 같게 만드는 **최소 편집** → **편집 거리**, 2차원 표 DP예요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 표의 뜻: `dp[i][j]` = source의 앞 i글자를 target의 앞 j글자로 만드는 최소 횟수",
        "2. 시작 값: `dp[i][0] = i`(모두 빼기), `dp[0][j] = j`(모두 넣기)",
        "3. 마지막 글자가 같으면 `dp[i-1][j-1]` 그대로",
        "4. 다르면 `1 + min(dp[i-1][j] (빼기), dp[i][j-1] (넣기), dp[i-1][j-1] (바꾸기))`",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "dp[i][0] = i, dp[0][j] = j",
        "for i in 1..n:",
        "    for j in 1..m:",
        "        if source[i-1] == target[j-1]: dp[i][j] = dp[i-1][j-1]",
        "        else: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])",
        "return dp[n][m]",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["글자가 다를 때 세 가지를 비교하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "if source[i - 1] == target[j - 1]:",
            "    dp[i][j] = dp[i - 1][j - 1]",
            "else:",
            "    dp[i][j] = 1 + min(______)",
          ].join("\n"),
          javascript: [
            "if (source[i - 1] === target[j - 1]) dp[i][j] = dp[i - 1][j - 1];",
            "else dp[i][j] = 1 + Math.min(______);",
          ].join("\n"),
          java: [
            "if (source.charAt(i - 1) == target.charAt(j - 1)) dp[i][j] = dp[i - 1][j - 1];",
            "else dp[i][j] = 1 + Math.min(______);",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["sequence-dp"],
  signalIds: ["sig-two-strings"],
  estimatedMinutes: 20,
  xp: 40,
};
