import type { Problem } from "@/types/content";

export const graphFollowers: Problem = {
  id: "c:graph-followers",
  slug: "graph-followers",
  source: "curated",
  topic: "graph-representation",
  level: 2,
  title: "나를 팔로우하는 친구",
  summary: "팔로우 목록을 사람마다 '나를 팔로우하는 사람' 목록으로 바꿔요",
  statement: [
    "노디네 사진 앱에는 `n`명의 사용자가 있고, 0번부터 `n-1`번까지 번호가 있어요.",
    "",
    "팔로우 기록 `follows`의 `[a, b]`는 **a가 b를 팔로우한다**는 뜻이에요. 팔로우는 한쪽 방향이라, a가 b를 팔로우해도 b가 a를 팔로우하는 건 아니에요.",
    "",
    "i번째 원소가 **i번 사용자를 팔로우하는 사람들의 번호를 오름차순으로 담은 리스트**인 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 사용자 수, `follows`: `[a, b]`(a가 b를 팔로우) 목록이에요.",
  outputFormat: "길이 n인 리스트의 리스트 (각 목록은 오름차순, 팔로워가 없으면 빈 리스트)",
  constraints: [
    "1 ≤ n ≤ 100,000",
    "0 ≤ follows의 길이 ≤ 100,000",
    "0 ≤ a, b < n, a ≠ b",
    "같은 팔로우 기록은 두 번 주어지지 않아요",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "사용자 수" },
      {
        name: "follows",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "팔로우 기록 [a, b]",
      },
    ],
    returns: {
      type: { python: "list[list[int]]", javascript: "number[][]", java: "List<List<Integer>>" },
      description: "사용자별 팔로워 목록",
    },
  },
  starterCode: {
    python: ["def solution(n, follows):", "    answer = [[] for _ in range(n)]", "    return answer", ""].join("\n"),
    javascript: [
      "function solution(n, follows) {",
      "  let answer = Array.from({ length: n }, () => []);",
      "  return answer;",
      "}",
      "",
    ].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<List<Integer>> solution(int n, int[][] follows) {",
      "        List<List<Integer>> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        4,
        [
          [0, 1],
          [2, 1],
          [1, 3],
          [3, 0],
        ],
      ],
      expected: [[3], [0, 2], [], [1]],
      explanation: "1번은 0번과 2번이 팔로우해요. 2번을 팔로우하는 사람은 없어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [3, []],
      expected: [[], [], []],
      explanation: "팔로우 기록이 없으면 모두 빈 목록이에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        3,
        [
          [0, 1],
          [0, 2],
        ],
      ],
      expected: [[], [0], [0]],
      failureNote: "0번이 1번과 2번을 팔로우해요. 0번의 팔로워 목록은 비어 있어요. 방향을 거꾸로 적지 않게 조심해요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [
        2,
        [
          [0, 1],
          [1, 0],
        ],
      ],
      expected: [[1], [0]],
      failureNote: "서로 팔로우하는 사이예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        5,
        [
          [4, 0],
          [2, 0],
          [3, 0],
          [1, 0],
        ],
      ],
      expected: [[1, 2, 3, 4], [], [], [], []],
      failureNote: "기록 순서와 상관없이 오름차순으로 정렬해야 해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "stress",
      args: [100000, Array.from({ length: 99999 }, (_, i) => [i + 1, 0])],
      expected: [Array.from({ length: 99999 }, (_, i) => i + 1), ...Array.from({ length: 99999 }, () => [])],
      failureNote: "모두가 0번을 팔로우해요. 사용자마다 기록 전체를 훑으면 시간 초과예요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [100000, Array.from({ length: 99999 }, (_, i) => [i, i + 1])],
      expected: [[], ...Array.from({ length: 99999 }, (_, i) => [i])],
      failureNote: "한 줄로 이어진 팔로우예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "사람은 노드, 팔로우는 **방향이 있는 간선** a → b예요. 관계 목록을 사람마다의 목록으로 바꾸니 **인접 리스트 만들기**예요.",
        "",
        "다만 이번에는 '내가 팔로우하는 사람'이 아니라 **'나를 팔로우하는 사람'**, 즉 간선을 **거꾸로** 모아요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 빈 목록 n개를 만들어요.",
        "2. 기록 `[a, b]`마다 **b의 목록에 a**를 넣어요 (a가 b의 팔로워니까요).",
        "3. 목록마다 오름차순으로 정렬해요.",
        "",
        "기록을 한 번만 훑으면 되니 O(N + M log M)이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "followers = 빈 목록 n개",
        "for [a, b] in follows:",
        "    followers[b]에 a 추가",
        "for 목록 in followers: 정렬",
        "return followers",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["누구의 목록에 누구를 넣을지가 이 문제의 전부예요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for a, b in follows:",
            "    followers[______].append(a)",
            "for f in followers:",
            "    f.sort()",
          ].join("\n"),
          javascript: [
            "for (const [a, b] of follows) followers[______].push(a);",
            "for (const f of followers) f.sort((x, y) => x - y);",
          ].join("\n"),
          java: [
            "for (int[] f : follows) followers.get(______).add(f[0]);",
            "for (List<Integer> list : followers) Collections.sort(list);",
          ].join("\n"),
        },
        caption: "f[0]이 팔로우하는 사람 a, f[1]이 팔로우받는 사람 b예요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["adjacency-list", "edge-list-conversion"],
  signalIds: ["sig-relations-given"],
  estimatedMinutes: 12,
  xp: 20,
};
