import type { Problem } from "@/types/content";
import { problemPreset } from "@/content/visualizations";

export const graphStationNeighbors: Problem = {
  id: "c:graph-station-neighbors",
  slug: "graph-station-neighbors",
  source: "curated",
  topic: "graph-representation",
  level: 1,
  title: "이웃 역 찾기",
  summary: "한 역과 선로로 바로 이어진 역들을 찾아요",
  statement: [
    "노디 마을의 장난감 기차에는 역이 `n`개 있고 0번부터 `n-1`번까지 번호가 붙어 있어요. 선로 목록 `edges`의 각 원소 `[a, b]`는 a역과 b역이 **양방향 선로**로 바로 이어져 있다는 뜻이에요.",
    "",
    "`x`역과 **선로 하나로 바로** 이어진 역 번호를 오름차순으로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 역의 수, `edges`: `[a, b]` 선로 목록, `x`: 알고 싶은 역 번호예요.",
  outputFormat: "x역의 이웃 역 번호를 오름차순으로 담은 리스트 (없으면 빈 리스트)",
  constraints: [
    "1 ≤ n ≤ 1,000",
    "0 ≤ edges의 길이 ≤ 5,000",
    "0 ≤ a, b, x < n, a ≠ b",
    "같은 선로는 두 번 주어지지 않아요.",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number" }, description: "역의 수" },
      { name: "edges", type: { python: "list[list[int]]", javascript: "number[][]" }, description: "선로 목록" },
      { name: "x", type: { python: "int", javascript: "number" }, description: "알고 싶은 역" },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]" }, description: "이웃 역 (오름차순)" },
  },
  starterCode: {
    python: ["def solution(n, edges, x):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, edges, x) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        5,
        [
          [0, 1],
          [1, 2],
          [1, 3],
          [3, 4],
        ],
        1,
      ],
      expected: [0, 2, 3],
      explanation: "1번 역은 0, 2, 3번 역과 바로 이어져 있어요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [
        4,
        [
          [2, 0],
          [3, 1],
        ],
        0,
      ],
      expected: [2],
      explanation: "[2, 0]처럼 x가 뒤에 적혀 있어도 이어진 거예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [3, [[0, 1]], 2],
      expected: [],
      failureNote: "선로가 없는 역은 이웃이 없어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "edge",
      args: [1, [], 0],
      expected: [],
      failureNote: "역이 하나뿐이에요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [
        6,
        [
          [5, 0],
          [0, 3],
          [2, 0],
          [0, 1],
          [4, 0],
        ],
        0,
      ],
      expected: [1, 2, 3, 4, 5],
      failureNote: "0번이 모든 역과 이어져 있어요. 오름차순으로 정렬해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        4,
        [
          [0, 1],
          [1, 2],
          [2, 3],
        ],
        3,
      ],
      expected: [2],
      failureNote: "건너 건너 이어진 역은 이웃이 아니에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [1000, Array.from({ length: 999 }, (_, i) => [i + 1, (i * 7) % (i + 1)]), 0],
      expected: [1, 7],
      failureNote: "역 1,000개, 선로 999개예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "역 = **노드**, 선로 = **간선**인 **그래프**예요.",
        "",
        '"양방향"이라 [a, b]는 a에서 b로도, b에서 a로도 갈 수 있어요 (무방향 그래프).',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "선로 목록을 하나씩 보면서,",
        "- a가 x면 b가 이웃,",
        "- b가 x면 a가 이웃이에요.",
        "",
        "모은 이웃을 오름차순으로 정렬해서 반환해요. 다음 레벨에서는 모든 역의 이웃을 한꺼번에 정리하는 **인접 리스트**를 만들어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "result = []",
        "for a, b in edges:",
        "    if a == x: result에 b 추가",
        "    if b == x: result에 a 추가",
        "return 정렬된 result",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "for a, b in edges:",
            "    if a == x:",
            "        result.append(b)",
            "    elif ______:",
            "        result.append(a)",
            "return sorted(result)",
          ].join("\n"),
          javascript: [
            "for (const [a, b] of edges) {",
            "  if (a === x) result.push(b);",
            "  else if (______) result.push(a);",
            "}",
            "return result.sort((p, q) => p - q);",
          ].join("\n"),
        },
        caption: "JS의 sort()는 숫자도 글자처럼 정렬해요. (p, q) => p - q 를 꼭 넣으세요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["adjacency-list"],
  signalIds: ["sig-relations-given"],
  visualization: {
    presets: [
      problemPreset(
        "station-ex1",
        "graph-adjacency",
        "예제 1의 노선도",
        "선로 목록을 읽으며 역마다 이웃이 채워지는 모습을 봐요.",
        [
          5,
          [
            [0, 1],
            [1, 2],
            [1, 3],
            [3, 4],
          ],
        ],
      ),
    ],
  },
  estimatedMinutes: 8,
  xp: 10,
};
