import type { Problem } from "@/types/content";

export const graphFamilyTree: Problem = {
  id: "c:graph-family-tree",
  slug: "graph-family-tree",
  source: "curated",
  topic: "graph-representation",
  level: 4,
  title: "가계도 읽기",
  summary: "부모 배열을 사람마다의 자녀 목록으로 바꿔요",
  statement: [
    "노디 가문의 가계도가 `parent` 배열로 적혀 있어요. 가족 `n`명은 0번부터 `n-1`번까지이고, `parent[i]`는 i번의 부모 번호예요. 가장 윗대 조상은 `parent[i] = -1`이에요.",
    "",
    "i번째 원소가 **i번의 자녀 번호를 오름차순으로** 담은 리스트인 리스트를 반환해 주세요. 자녀가 없으면 빈 리스트예요.",
  ].join("\n"),
  inputFormat: "`parent`: 길이 n인 부모 번호 배열이에요. 조상은 하나뿐이고, 모든 가족은 조상과 이어져 있어요.",
  outputFormat: "길이 n인 자녀 목록 리스트",
  constraints: ["1 ≤ n ≤ 100,000"],
  signature: {
    name: "solution",
    params: [
      {
        name: "parent",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "부모 번호 (조상은 -1)",
      },
    ],
    returns: {
      type: { python: "list[list[int]]", javascript: "number[][]", java: "List<List<Integer>>" },
      description: "사람별 자녀 목록",
    },
  },
  starterCode: {
    python: ["def solution(parent):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(parent) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<List<Integer>> solution(int[] parent) {",
      "        List<List<Integer>> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [[-1, 0, 0, 1, 1, 2]],
      expected: [[1, 2], [3, 4], [5], [], [], []],
      explanation: "0번의 자녀는 1, 2번, 1번의 자녀는 3, 4번, 2번의 자녀는 5번이에요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [[-1]],
      expected: [[]],
      explanation: "조상 혼자예요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [[2, 2, -1]],
      expected: [[], [], [0, 1]],
      failureNote: "조상이 0번이 아닐 수도 있어요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [[-1, 0, 1, 2, 3]],
      expected: [[1], [2], [3], [4], []],
      failureNote: "한 줄로 이어진 가계도예요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [[3, 3, 3, -1, 2]],
      expected: [[], [], [4], [0, 1, 2], []],
      failureNote: "자녀 번호는 오름차순으로 정리해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [[-1, 0, 0, 0, 0]],
      expected: [[1, 2, 3, 4], [], [], [], []],
      failureNote: "조상에게 자녀가 넷이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [Array.from({ length: 100000 }, (_, i) => (i === 0 ? -1 : Math.floor((i - 1) / 2)))],
      expected: Array.from({ length: 100000 }, (_, i) => [2 * i + 1, 2 * i + 2].filter((c) => c < 100000)),
      failureNote: "10만 명의 가계도예요. 사람마다 배열 전체를 훑어 자녀를 찾으면 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        '"각자의 부모"가 주어진 **트리**예요. 부모 배열은 "자식 → 부모" 방향의 간선 목록과 같아요.',
        "",
        '트리를 위에서 아래로 다루려면 "부모 → 자녀들" **인접 리스트**로 바꿔야 해요.',
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. 빈 리스트 n개를 만들어요.",
        "2. i = 0, 1, … 순서로 보면서 `parent[i]`가 -1이 아니면 `children[parent[i]]`에 i를 추가해요.",
        "3. i를 작은 번호부터 넣었으니 목록은 저절로 오름차순이에요.",
        "",
        "사람마다 배열 전체를 훑어 자녀를 찾으면 O(N²)이에요. 배열을 **한 번만** 훑으세요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "children = [빈 리스트 n개]",
        "for i in 0..n-1:",
        "    if parent[i] != -1:",
        "        children[parent[i]]에 i 추가",
        "return children",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "children = [[] for _ in range(len(parent))]",
            "for i, p in enumerate(parent):",
            "    if p != -1:",
            "        ______",
          ].join("\n"),
          javascript: [
            "const children = parent.map(() => []);",
            "parent.forEach((p, i) => {",
            "  if (p !== -1) ______;",
            "});",
          ].join("\n"),
          java: [
            "List<List<Integer>> children = new ArrayList<>();",
            "for (int i = 0; i < parent.length; i++) children.add(new ArrayList<>());",
            "for (int i = 0; i < parent.length; i++) {",
            "    if (parent[i] != -1) ______;",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["edge-list-conversion", "adjacency-list"],
  signalIds: ["sig-tree-structure"],
  estimatedMinutes: 15,
  xp: 40,
};
