import { lazy } from "@/content/problems/lazy";
import type { Problem, TestCase } from "@/types/content";

const testCases = lazy((): TestCase[] => [
  {
    id: "ex-1",
    visibility: "example",
    purpose: "basic",
    args: [[-1, 0, 0, 1]],
    expected: [0, 1, 1, 2],
    explanation: "0번이 대표예요. 1, 2번은 0번의 부하라서 1층, 3번은 1번의 부하라서 2층이에요.",
  },
  {
    id: "ex-2",
    visibility: "example",
    purpose: "edge",
    args: [[-1]],
    expected: [0],
    explanation: "대표 혼자인 회사예요.",
  },
  {
    id: "hid-1",
    visibility: "hidden",
    purpose: "tricky",
    args: [[2, 2, -1, 0]],
    expected: [1, 1, 0, 2],
    failureNote: "대표가 0번이 아니에요. 2번이 대표예요.",
  },
  {
    id: "hid-2",
    visibility: "hidden",
    purpose: "tricky",
    args: [[1, 2, 3, -1]],
    expected: [3, 2, 1, 0],
    failureNote:
      "상사 번호가 부하 번호보다 커요. 앞에서부터 한 번 훑으며 `상사의 층 + 1`을 적으면 상사의 층이 아직 정해지지 않았어요.",
  },
  {
    id: "hid-3",
    visibility: "hidden",
    purpose: "basic",
    args: [[-1, 0, 1, 1, 0, 4, 5]],
    expected: [0, 1, 2, 2, 1, 2, 3],
    failureNote: "층이 여러 갈래로 뻗어 있어요.",
  },
  {
    id: "hid-4",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => (i === 99999 ? -1 : i + 1))],
    expected: Array.from({ length: 100000 }, (_, i) => 99999 - i),
    failureNote:
      "10만 명이 한 줄로 이어진 조직이에요. 직원마다 대표까지 따라 올라가면 시간 초과이고, 재귀로 올라가면 너무 깊어요.",
  },
  {
    id: "hid-5",
    visibility: "hidden",
    purpose: "stress",
    args: [Array.from({ length: 100000 }, (_, i) => (i === 0 ? -1 : 0))],
    expected: Array.from({ length: 100000 }, (_, i) => (i === 0 ? 0 : 1)),
    failureNote: "대표 한 명에 부하가 99,999명이에요.",
  },
]);

export const graphOrgLevels: Problem = {
  id: "c:graph-org-levels",
  slug: "graph-org-levels",
  source: "curated",
  topic: "graph-representation",
  level: 4,
  title: "조직도 층수",
  summary: "직속 상사 목록으로 사람마다 대표에서 몇 단계 아래인지 구해요",
  statement: [
    "노디 회사의 직원은 `n`명이고, 0번부터 `n-1`번까지 번호가 있어요. `boss[i]`는 i번 직원의 **직속 상사** 번호예요. 대표는 상사가 없어서 `boss` 값이 `-1`이고, 대표는 딱 한 명이에요.",
    "",
    "모든 직원은 상사를 따라 올라가면 결국 대표에 닿아요. 대표의 층은 0, 대표의 직속 부하는 1, 그 부하의 부하는 2, …예요.",
    "",
    "i번째 값이 **i번 직원의 층**인 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`boss`: i번째 값이 i번 직원의 직속 상사 번호(대표는 -1)인 리스트예요.",
  outputFormat: "i번째 값이 i번 직원의 층인 리스트",
  constraints: [
    "1 ≤ n ≤ 100,000",
    "boss 값이 -1인 직원은 딱 한 명이에요",
    "상사 관계에 사이클은 없어요 (모두 대표에게 닿아요)",
    "상사 번호가 부하 번호보다 클 수도 있어요",
  ],
  signature: {
    name: "solution",
    params: [
      {
        name: "boss",
        type: { python: "list[int]", javascript: "number[]", java: "int[]" },
        description: "직속 상사 번호 (대표는 -1)",
      },
    ],
    returns: { type: { python: "list[int]", javascript: "number[]", java: "int[]" }, description: "직원별 층" },
  },
  starterCode: {
    python: ["def solution(boss):", "    answer = [0] * len(boss)", "    return answer", ""].join("\n"),
    javascript: [
      "function solution(boss) {",
      "  let answer = new Array(boss.length).fill(0);",
      "  return answer;",
      "}",
      "",
    ].join("\n"),
    java: [
      "class Solution {",
      "    public int[] solution(int[] boss) {",
      "        int[] answer = new int[boss.length];",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  get testCases() {
    return testCases();
  },
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "직원마다 상사 **한 명**이 있고 대표만 상사가 없어요 → **트리**를 **부모 배열**로 준 거예요.",
        "",
        "부모 배열은 '위로' 가기는 쉽지만, 대표부터 '아래로' 층을 매기려면 **자식 목록**(인접 리스트)으로 바꾸는 게 좋아요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. `children` 목록 n개를 만들고, `boss[i]`가 -1이 아니면 `children[boss[i]]`에 i를 넣어요. -1인 직원이 대표(root)예요.",
        "2. 대표를 큐에 넣고 층 0으로 시작해요.",
        "3. 큐에서 한 명씩 꺼내, 그 사람의 부하들 층을 **내 층 + 1**로 적고 큐에 넣어요.",
        "",
        "상사가 부하보다 **먼저** 처리되니, 부하의 층을 적을 때 상사의 층은 이미 정해져 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "children = 빈 목록 n개",
        "for i in 0..n-1:",
        "    boss[i] == -1 → root = i",
        "    아니면       → children[boss[i]]에 i 추가",
        "level = [0] * n, queue = [root]",
        "while queue가 비어 있지 않은 동안:",
        "    u = queue 앞에서 꺼내기",
        "    for c in children[u]:",
        "        level[c] = level[u] + 1",
        "        queue 뒤에 c 넣기",
        "return level",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["부하의 층을 정하는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: [
            "queue = deque([root])",
            "while queue:",
            "    u = queue.popleft()",
            "    for c in children[u]:",
            "        level[c] = ______",
            "        queue.append(c)",
          ].join("\n"),
          javascript: [
            "const queue = [root];",
            "for (let head = 0; head < queue.length; head++) {",
            "  const u = queue[head];",
            "  for (const c of children[u]) {",
            "    level[c] = ______;",
            "    queue.push(c);",
            "  }",
            "}",
          ].join("\n"),
          java: [
            "Deque<Integer> queue = new ArrayDeque<>();",
            "queue.offer(root);",
            "while (!queue.isEmpty()) {",
            "    int u = queue.poll();",
            "    for (int c : children.get(u)) {",
            "        level[c] = ______;",
            "        queue.offer(c);",
            "    }",
            "}",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["adjacency-list", "edge-list-conversion"],
  signalIds: ["sig-tree-structure"],
  estimatedMinutes: 20,
  xp: 40,
};
