import type { Problem } from "@/types/content";

export const graphOneStrokeWalk: Problem = {
  id: "c:graph-one-stroke-walk",
  slug: "graph-one-stroke-walk",
  source: "curated",
  topic: "graph-representation",
  level: 5,
  title: "산책로 한 번에 걷기",
  summary: "모든 산책로를 정확히 한 번씩 걸을 수 있는지 차수로 판별해요",
  statement: [
    "노디 공원에는 쉼터 `n`개(0번 ~ `n-1`번)와 쉼터를 잇는 **양방향 산책로** `trails`가 있어요. 모든 산책로는 서로 이어져 있어서, 어느 쉼터에서든 산책로를 따라 다른 모든 산책로에 갈 수 있어요.",
    "",
    "노디는 **모든 산책로를 정확히 한 번씩** 걷고 싶어요. 쉼터는 여러 번 지나가도 되고, 출발 쉼터와 도착 쉼터는 달라도 돼요.",
    "",
    "그렇게 걸을 수 있으면 `True`, 없으면 `False`를 반환해 주세요.",
    "",
    '> 쉼터에 붙은 산책로 수를 세어 보세요. 중간에 지나가는 쉼터는 "들어온 만큼 나가야" 해요.',
  ].join("\n"),
  inputFormat: "`n`: 쉼터 수, `trails`: `[a, b]` 산책로 목록이에요. 같은 두 쉼터 사이에 산책로가 여러 개일 수 있어요.",
  outputFormat: "모든 산책로를 한 번씩 걸을 수 있는지 (bool)",
  constraints: [
    "1 ≤ n ≤ 100,000",
    "1 ≤ trails의 길이 ≤ 200,000",
    "a ≠ b",
    "산책로가 하나 이상 붙은 쉼터들은 모두 이어져 있어요.",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "쉼터 수" },
      {
        name: "trails",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "산책로 목록",
      },
    ],
    returns: {
      type: { python: "bool", javascript: "boolean", java: "boolean" },
      description: "한 번에 걸을 수 있는지",
    },
  },
  starterCode: {
    python: ["def solution(n, trails):", "    answer = False", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, trails) {", "  let answer = false;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public boolean solution(int n, int[][] trails) {",
      "        boolean answer = false;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        4,
        [
          [0, 1],
          [1, 2],
          [2, 0],
          [2, 3],
        ],
      ],
      expected: true,
      explanation: "산책로 수가 홀수인 쉼터가 2번(3개)과 3번(1개) 두 곳뿐이에요. 2번에서 출발해 3번에서 끝나면 돼요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "tricky",
      args: [
        4,
        [
          [0, 1],
          [0, 2],
          [0, 3],
        ],
      ],
      expected: false,
      explanation: "홀수 쉼터가 0, 1, 2, 3번 네 곳이라 불가능해요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [2, [[0, 1]]],
      expected: true,
      failureNote: "산책로 하나는 그냥 걸으면 돼요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [
        3,
        [
          [0, 1],
          [1, 2],
          [2, 0],
        ],
      ],
      expected: true,
      failureNote: "삼각형 한 바퀴는 제자리로 돌아와요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        2,
        [
          [0, 1],
          [0, 1],
          [0, 1],
        ],
      ],
      expected: true,
      failureNote: "같은 두 쉼터 사이 산책로가 셋이에요. 두 쉼터 모두 홀수(3)라 가능해요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        5,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [3, 4],
          [4, 0],
          [0, 2],
          [1, 3],
        ],
      ],
      expected: false,
      failureNote: "홀수 쉼터가 넷이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "basic",
      args: [
        6,
        [
          [0, 1],
          [1, 2],
          [2, 3],
          [3, 4],
          [4, 5],
        ],
      ],
      expected: true,
      failureNote: "한 줄로 이어진 산책로예요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [100000, Array.from({ length: 100000 }, (_, i) => [i, (i + 1) % 100000])],
      expected: true,
      failureNote: "쉼터 10만 개가 큰 원을 이뤄요. 경로를 직접 찾으려 하면 너무 오래 걸려요.",
    },
    {
      id: "hid-7",
      visibility: "hidden",
      purpose: "stress",
      args: [100000, [...Array.from({ length: 99999 }, (_, i) => [i, i + 1]), [0, 50000]]],
      expected: true,
      failureNote: "긴 길 가운데에 지름길이 하나 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "모든 간선을 한 번씩 지나는 **한붓그리기**예요. 경로를 직접 찾지 않고 **차수**(쉼터에 붙은 산책로 수)만 세면 판별할 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "중간에 지나가는 쉼터는 들어갈 때 한 번, 나올 때 한 번씩 산책로를 써요. 그래서 **차수가 짝수**여야 해요.",
        "",
        "차수가 홀수일 수 있는 건 **출발 쉼터와 도착 쉼터** 둘뿐이에요.",
        "- 홀수 차수 쉼터가 **0개**: 출발한 곳으로 돌아오며 가능",
        "- **2개**: 한쪽에서 출발해 다른 쪽에서 끝나며 가능",
        "- 그 외: 불가능",
        "",
        "(모든 산책로가 이어져 있다는 조건이 있어서 연결 여부는 따로 확인하지 않아도 돼요.)",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "degree = [0] * n",
        "for a, b in trails:",
        "    degree[a] += 1; degree[b] += 1",
        "odd = degree가 홀수인 쉼터 수",
        "return odd == 0 or odd == 2",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["홀수 차수를 세는 부분이에요."].join("\n"),
      code: {
        code: {
          python: ["odd = sum(1 for d in degree if ______)", "return odd == 0 or odd == 2"].join("\n"),
          javascript: ["const odd = degree.filter((d) => ______).length;", "return odd === 0 || odd === 2;"].join("\n"),
          java: ["int odd = 0;", "for (int d : degree) if (______) odd++;", "return odd == 0 || odd == 2;"].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["degree-count"],
  signalIds: ["sig-degree"],
  estimatedMinutes: 20,
  xp: 50,
};
