import type { Problem } from "@/types/content";

export const graphTripleFriends: Problem = {
  id: "c:graph-triple-friends",
  slug: "graph-triple-friends",
  source: "curated",
  topic: "graph-representation",
  level: 5,
  title: "삼총사 찾기",
  summary: "세 명이 모두 서로 친구인 삼총사가 몇 팀인지 세요",
  statement: [
    "노디네 학교에는 학생이 `n`명 있고, 0번부터 `n-1`번까지 번호가 있어요. 친구 관계 `pairs`의 `[a, b]`는 a와 b가 서로 친구라는 뜻이에요.",
    "",
    "세 학생이 **모두 서로 친구**이면 삼총사라고 불러요. 같은 세 명은 순서를 바꿔도 한 팀이에요.",
    "",
    "삼총사가 **모두 몇 팀**인지 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 학생 수, `pairs`: `[a, b]` 친구 관계 목록이에요.",
  outputFormat: "삼총사 팀의 수 (정수)",
  constraints: [
    "1 ≤ n ≤ 2,000",
    "0 ≤ pairs의 길이 ≤ 20,000",
    "0 ≤ a, b < n, a ≠ b",
    "같은 관계는 두 번 주어지지 않아요",
  ],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "학생 수" },
      {
        name: "pairs",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "친구 관계",
      },
    ],
    returns: { type: { python: "int", javascript: "number", java: "int" }, description: "삼총사 팀의 수" },
  },
  starterCode: {
    python: ["def solution(n, pairs):", "    answer = 0", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, pairs) {", "  let answer = 0;", "  return answer;", "}", ""].join("\n"),
    java: [
      "class Solution {",
      "    public int solution(int n, int[][] pairs) {",
      "        int answer = 0;",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        4,
        [
          [0, 1],
          [1, 2],
          [0, 2],
          [2, 3],
        ],
      ],
      expected: 1,
      explanation: "0, 1, 2번이 모두 서로 친구라서 한 팀이에요. 3번은 2번하고만 친구예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [
        3,
        [
          [0, 1],
          [1, 2],
        ],
      ],
      expected: 0,
      explanation: "0과 2가 친구가 아니라서 삼총사가 아니에요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "edge",
      args: [1, []],
      expected: 0,
      failureNote: "학생이 한 명뿐이에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        4,
        [
          [0, 1],
          [0, 2],
          [0, 3],
          [1, 2],
          [1, 3],
          [2, 3],
        ],
      ],
      expected: 4,
      failureNote:
        "넷이 모두 친구면 세 명을 고르는 방법 4가지가 모두 삼총사예요. 같은 팀을 여러 번 세지 않게 조심해요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "basic",
      args: [
        5,
        [
          [0, 1],
          [1, 2],
          [0, 2],
          [1, 3],
          [2, 3],
        ],
      ],
      expected: 2,
      failureNote: "1–2 친구 관계를 두 팀이 함께 써요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [
        6,
        [
          [0, 1],
          [1, 2],
          [2, 0],
          [3, 4],
          [4, 5],
          [5, 3],
        ],
      ],
      expected: 2,
      failureNote: "서로 떨어진 삼총사 두 팀이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        200,
        Array.from({ length: 200 }, (_, a) => Array.from({ length: 200 - a - 1 }, (_, t) => [a, a + t + 1])).flat(),
      ],
      expected: 1313400,
      failureNote:
        "200명이 모두 서로 친구예요 (관계 19,900개). 세 명을 모두 골라 보거나, 관계마다 학생 전체를 훑으면 느려요.",
    },
    {
      id: "hid-6",
      visibility: "hidden",
      purpose: "stress",
      args: [
        2000,
        [
          ...Array.from({ length: 1999 }, (_, i) => [0, i + 1]),
          ...Array.from({ length: 1999 }, (_, i) => [i + 1, ((i + 1) % 1999) + 1]),
        ],
      ],
      expected: 1999,
      failureNote: "학생 2,000명이 바퀴 모양으로 이어져 있어요. 세 명을 모두 골라 보면 13억 가지라 시간 초과예요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: [
        "학생은 노드, 친구 관계는 무방향 간선이에요. 삼총사는 세 노드가 모두 이어진 **삼각형**이에요.",
        "",
        "'a와 c가 친구인가?'를 아주 많이 물어봐야 해요. 그래프를 **어떤 모양으로 저장할지**가 핵심이에요.",
      ].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "세 명을 모두 골라 보면 n = 2,000일 때 13억 가지라 너무 느려요. 관계에서 출발해요.",
        "",
        "1. 학생마다 친구를 **집합**(set)으로 저장해요. '친구인가?'를 O(1)에 확인할 수 있어요.",
        "2. 관계 `[a, b]`마다, a의 친구이면서 b의 친구인 c(**공통 친구**)의 수를 세요. `a, b, c`가 삼총사예요.",
        "3. 삼총사 하나는 세 관계(a–b, b–c, a–c)에서 한 번씩, **세 번** 세어져요. 합을 3으로 나눠요.",
        "",
        "공통 친구를 셀 때는 **친구가 적은 쪽**을 훑으면서 다른 쪽 집합에 있는지 확인하면 빨라요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "friends = 빈 집합 n개",
        "for [a, b] in pairs: friends[a]에 b, friends[b]에 a 추가",
        "count = 0",
        "for [a, b] in pairs:",
        "    count += (friends[a]와 friends[b]의 공통 원소 수)",
        "return count / 3",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["관계 하나에서 공통 친구를 세는 부분이에요. 빈칸을 채워 보세요."].join("\n"),
      code: {
        code: {
          python: ["count = 0", "for a, b in pairs:", "    count += len(______)", "return count // 3"].join("\n"),
          javascript: [
            "for (const [a, b] of pairs) {",
            "  const [small, large] = friends[a].size < friends[b].size ? [friends[a], friends[b]] : [friends[b], friends[a]];",
            "  for (const c of small) if (______) count++;",
            "}",
            "return count / 3;",
          ].join("\n"),
          java: [
            "for (int[] p : pairs) {",
            "    Set<Integer> small = friends.get(p[0]), large = friends.get(p[1]);",
            "    if (small.size() > large.size()) { Set<Integer> t = small; small = large; large = t; }",
            "    for (int c : small) if (______) count++;",
            "}",
            "return count / 3;",
          ].join("\n"),
        },
        caption:
          "Python은 집합의 교집합 `&`, JavaScript는 작은 쪽 집합을 훑으며 `has`로 확인해요. Java는 작은 쪽 집합을 훑으며 contains로 확인해요.",
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["adjacency-list"],
  signalIds: ["sig-relations-given"],
  estimatedMinutes: 30,
  xp: 50,
};
