import type { Problem } from "@/types/content";

export const graphCommonFriends: Problem = {
  id: "c:graph-common-friends",
  slug: "graph-common-friends",
  source: "curated",
  topic: "graph-representation",
  level: 2,
  title: "우리 둘의 공통 친구",
  summary: "두 사람 모두와 친구인 사람을 찾아요",
  statement: [
    "새싹 학교 학생 `n`명(0번 ~ `n-1`번)의 친구 관계가 `pairs`로 주어져요. `[a, b]`는 a와 b가 서로 친구라는 뜻이에요.",
    "",
    "학생 `u`와 `v` **둘 다와 친구인** 학생들의 번호를 오름차순으로 담은 리스트를 반환해 주세요.",
  ].join("\n"),
  inputFormat: "`n`: 학생 수, `pairs`: 친구 관계 목록, `u`, `v`: 두 학생 번호예요.",
  outputFormat: "공통 친구 번호를 오름차순으로 담은 리스트 (없으면 빈 리스트)",
  constraints: ["2 ≤ n ≤ 100,000", "0 ≤ pairs의 길이 ≤ 200,000", "u ≠ v", "같은 관계는 두 번 주어지지 않아요."],
  signature: {
    name: "solution",
    params: [
      { name: "n", type: { python: "int", javascript: "number", java: "int" }, description: "학생 수" },
      {
        name: "pairs",
        type: { python: "list[list[int]]", javascript: "number[][]", java: "int[][]" },
        description: "친구 관계",
      },
      { name: "u", type: { python: "int", javascript: "number", java: "int" }, description: "첫 번째 학생" },
      { name: "v", type: { python: "int", javascript: "number", java: "int" }, description: "두 번째 학생" },
    ],
    returns: {
      type: { python: "list[int]", javascript: "number[]", java: "List<Integer>" },
      description: "공통 친구 (오름차순)",
    },
  },
  starterCode: {
    python: ["def solution(n, pairs, u, v):", "    answer = []", "    return answer", ""].join("\n"),
    javascript: ["function solution(n, pairs, u, v) {", "  let answer = [];", "  return answer;", "}", ""].join("\n"),
    java: [
      "import java.util.*;",
      "",
      "class Solution {",
      "    public List<Integer> solution(int n, int[][] pairs, int u, int v) {",
      "        List<Integer> answer = new ArrayList<>();",
      "        return answer;",
      "    }",
      "}",
      "",
    ].join("\n"),
  },
  testCases: [
    {
      id: "ex-1",
      visibility: "example",
      purpose: "basic",
      args: [
        5,
        [
          [0, 2],
          [1, 2],
          [0, 3],
          [1, 3],
          [0, 4],
        ],
        0,
        1,
      ],
      expected: [2, 3],
      explanation: "2번과 3번은 0번, 1번 모두와 친구예요. 4번은 0번하고만 친구예요.",
    },
    {
      id: "ex-2",
      visibility: "example",
      purpose: "edge",
      args: [3, [[0, 1]], 0, 1],
      expected: [],
      explanation: "0과 1은 서로 친구지만, 공통 친구는 없어요.",
    },
    {
      id: "hid-1",
      visibility: "hidden",
      purpose: "tricky",
      args: [
        3,
        [
          [0, 1],
          [1, 2],
          [0, 2],
        ],
        0,
        1,
      ],
      expected: [2],
      failureNote: "u, v 자신은 공통 친구가 아니에요.",
    },
    {
      id: "hid-2",
      visibility: "hidden",
      purpose: "basic",
      args: [
        6,
        [
          [5, 0],
          [5, 1],
          [4, 0],
          [4, 1],
          [3, 0],
        ],
        1,
        0,
      ],
      expected: [4, 5],
      failureNote: "u와 v의 순서가 바뀌어도 같아요.",
    },
    {
      id: "hid-3",
      visibility: "hidden",
      purpose: "edge",
      args: [4, [], 2, 3],
      expected: [],
      failureNote: "관계가 하나도 없어요.",
    },
    {
      id: "hid-4",
      visibility: "hidden",
      purpose: "basic",
      args: [
        4,
        [
          [0, 2],
          [2, 1],
          [3, 0],
          [3, 1],
          [2, 3],
        ],
        0,
        1,
      ],
      expected: [2, 3],
      failureNote: "공통 친구가 둘이에요.",
    },
    {
      id: "hid-5",
      visibility: "hidden",
      purpose: "stress",
      args: [
        100000,
        [
          ...Array.from({ length: 99998 }, (_, i) => [0, i + 2]),
          ...Array.from({ length: 99998 }, (_, i) => [1, i + 2]).filter((_, i) => i % 1000 === 0),
        ],
        0,
        1,
      ],
      expected: Array.from({ length: 100 }, (_, i) => i * 1000 + 2),
      failureNote: "학생 10만 명, 관계가 10만 개 넘게 있어요.",
    },
  ],
  judge: {
    timeLimitMs: 2000,
    compare: { type: "exact" },
    recursionLimit: 3000,
    revealFirstFailure: true,
  },
  hints: [
    {
      step: 1,
      kind: "pattern",
      title: "어떤 유형일까요?",
      body: ["관계 목록에서 한 사람의 친구들을 빠르게 알아야 해요 → 먼저 **인접 리스트**를 만들어요."].join("\n"),
      xpPenaltyRate: 0.05,
    },
    {
      step: 2,
      kind: "approach",
      title: "어떻게 접근할까요?",
      body: [
        "1. u의 친구 목록과 v의 친구 목록을 구해요 (인접 리스트를 만들거나, 관계 목록에서 둘의 친구만 골라요).",
        "2. u의 친구들을 **집합(set)** 에 넣고, v의 친구 중 그 집합에 있는 사람만 골라요.",
        "3. 오름차순으로 정렬해요.",
        "",
        "리스트에서 `in`으로 찾으면 매번 전체를 훑어서 느려요. 집합은 O(1)에 찾을 수 있어요.",
      ].join("\n"),
      xpPenaltyRate: 0.15,
    },
    {
      step: 3,
      kind: "pseudocode",
      title: "의사코드",
      body: [
        "~~~text",
        "friends_u = u의 친구 집합",
        "friends_v = v의 친구 목록",
        "common = [x for x in friends_v if x in friends_u]",
        "return 정렬된 common",
        "~~~",
      ].join("\n"),
      xpPenaltyRate: 0.3,
    },
    {
      step: 4,
      kind: "key-code",
      title: "핵심 코드",
      body: ["집합으로 공통 친구를 고르는 부분이에요."].join("\n"),
      code: {
        code: {
          python: [
            "friends_u = set(graph[u])",
            "common = [x for x in graph[v] if ______]",
            "return sorted(common)",
          ].join("\n"),
          javascript: [
            "const friendsU = new Set(graph[u]);",
            "const common = graph[v].filter((x) => ______);",
            "return common.sort((p, q) => p - q);",
          ].join("\n"),
          java: [
            "Set<Integer> friendsU = new HashSet<>(graph.get(u));",
            "List<Integer> common = new ArrayList<>();",
            "for (int x : graph.get(v)) if (______) common.add(x);",
            "Collections.sort(common);",
            "return common;",
          ].join("\n"),
        },
      },
      xpPenaltyRate: 0.5,
    },
  ],
  patternTags: ["adjacency-list"],
  signalIds: ["sig-relations-given"],
  estimatedMinutes: 12,
  xp: 20,
};
