import type { ConceptCard, RecognitionQuestion } from "@/types";

export const BACKTRACKING_CARDS: ConceptCard[] = [
  {
    id: "backtracking-what",
    title: "골라 보고, 아니면 되돌아와요",
    analogy: "갈림길이 많은 숲길에서 한 길을 골라 가 보고, 막히면 갈림길로 돌아와 다른 길을 골라요.",
    body: [
      "백트래킹(backtracking)은 **모든 경우를 하나씩 만들어 보는** 방법이에요.",
      "",
      "갈림길마다 선택지 하나를 **고르고**, 더 깊이 들어가 다음 선택을 해요. 끝까지 가면(답 하나 완성) 또는 막히면, 방금 고른 것을 **되돌리고** 다른 선택지를 골라요.",
      "",
      "선택들을 나무처럼 그린 것을 **선택 트리**라고 해요. 백트래킹은 이 나무를 DFS로 도는 것과 같아요.",
    ].join("\n"),
    illustration: "backtracking-tree",
    keyPoints: ["모든 경우를 하나씩 만들어 봐요", "고르기 → 더 깊이 → 되돌리기", "선택 트리를 DFS로 도는 것"],
  },
  {
    id: "backtracking-template",
    title: "고르기 · 더 깊이 · 되돌리기",
    analogy: "블록을 하나 올려 보고, 마음에 안 들면 그 블록만 내려서 다른 블록을 올려 봐요.",
    body: [
      "백트래킹 코드는 거의 항상 이 모양이에요.",
      "",
      "1. **완성 검사**: 다 골랐으면 결과에 저장하고 돌아가요. 리스트는 꼭 **복사본**을 저장해요.",
      "2. **선택지마다** `path`에 넣고(고르기) → 재귀(더 깊이) → `path`에서 빼기(되돌리기).",
      "",
      "되돌리기를 빼먹으면 다음 선택지를 고를 때 이전 선택이 남아 있어서 결과가 틀려요.",
    ].join("\n"),
    illustration: "backtracking-tree",
    keyPoints: ["완성되면 복사본 저장", "넣고 → 재귀 → 빼기", "되돌리기를 빼먹지 않기"],
    code: {
      code: {
        python: [
          "def backtrack():",
          "    if 완성:",
          "        result.append(path[:])   # 복사본!",
          "        return",
          "    for choice in 선택지:",
          "        path.append(choice)      # 고르기",
          "        backtrack()              # 더 깊이",
          "        path.pop()               # 되돌리기",
        ].join("\n"),
        javascript: [
          "function backtrack() {",
          "  if (완성) {",
          "    result.push([...path]);      // 복사본!",
          "    return;",
          "  }",
          "  for (const choice of 선택지) {",
          "    path.push(choice);           // 고르기",
          "    backtrack();                 // 더 깊이",
          "    path.pop();                  // 되돌리기",
          "  }",
          "}",
        ].join("\n"),
        java: [
          "void backtrack() {",
          "    if (완성) {",
          "        result.add(new ArrayList<>(path));   // 복사본!",
          "        return;",
          "    }",
          "    for (int choice : 선택지) {",
          "        path.add(choice);                    // 고르기",
          "        backtrack();                         // 더 깊이",
          "        path.remove(path.size() - 1);        // 되돌리기",
          "    }",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "backtracking-perm-comb",
    title: "순열 · 조합 · 부분집합",
    analogy: "줄 세우기(순서가 중요), 대표 뽑기(순서 상관없음), 살지 말지 정하기(각각 예/아니오).",
    body: [
      "| 종류 | 무엇을 만드나 | 핵심 도구 | 개수 |",
      "| --- | --- | --- | --- |",
      "| 순열 | 순서가 있는 나열 | `used` 배열 | n! |",
      "| 조합 | 순서 없는 k개 | **시작 인덱스** 넘기기 | C(n, k) |",
      "| 부분집합 | 각각 넣는다/뺀다 | 두 갈래 재귀 | 2^n |",
      "",
      "조합에서 다음 선택을 **방금 고른 것 뒤에서만** 하면 {1, 2}와 {2, 1} 같은 중복이 생기지 않아요.",
    ].join("\n"),
    illustration: "backtracking-tree",
    keyPoints: ["순열: used 배열", "조합: 시작 인덱스를 넘겨요", "부분집합: 넣는다 / 뺀다 두 갈래"],
  },
  {
    id: "backtracking-pruning",
    title: "가지치기: 안 될 길은 일찍 자르기",
    analogy: "지도에 '막다른 길' 표시가 있으면 끝까지 가 보지 않고 바로 돌아서요.",
    body: [
      "경우의 수는 금방 폭발해요. 2^30은 약 10억, 10!은 약 363만이에요.",
      "",
      "그래서 **이 길로 가 봐야 답이 될 수 없다**는 게 보이는 순간 더 들어가지 않고 돌아와요. 이것을 **가지치기**라고 해요.",
      "",
      "- 합이 이미 목표를 넘었다 → 멈춰요 (정렬해 두면 뒤쪽도 모두 넘어요)",
      "- 닫는 괄호가 여는 괄호보다 많아졌다 → 멈춰요",
      "- 같은 줄·대각선에 이미 로봇이 있다 → 그 칸은 건너뛰어요",
    ].join("\n"),
    illustration: "backtracking-tree",
    keyPoints: [
      "답이 될 수 없으면 바로 되돌아가요",
      "정렬해 두면 더 많이 자를 수 있어요",
      "제약을 고를 때마다 검사해요",
    ],
  },
  {
    id: "backtracking-when",
    title: "언제 백트래킹을 떠올릴까?",
    analogy: "자물쇠 번호를 모를 때 가능한 조합을 하나씩 다 돌려 보는 것.",
    body: [
      "- **모든 경우 / 모든 조합 / 모든 순서**를 출력하거나 세요.",
      "- **N이 아주 작아요**: N ≤ 10 안팎이면 모두 만들어 볼 수 있다는 힌트예요.",
      "- **배치 제약**이 있어요: 서로 겹치면 안 되게 놓기, 이웃끼리 다르게 칠하기.",
      "",
      '반대로 "**최소** 몇 번"을 물으면 BFS를, N이 수만 이상이면 다른 방법을 먼저 생각해요.',
    ].join("\n"),
    illustration: "backtracking-tree",
    keyPoints: [
      "'모든 경우' + 작은 N → 백트래킹",
      "배치·색칠 제약 → 백트래킹 + 가지치기",
      "'최소 횟수'면 BFS를 먼저 의심",
    ],
  },
];

export const BACKTRACKING_QUIZ: RecognitionQuestion[] = [
  {
    id: "backtracking-q1",
    snippet: "서로 다른 알파벳 카드 N장(N ≤ 7)을 한 줄로 늘어놓는 모든 순서를 사전 순으로 출력하세요.",
    choices: ["backtracking", "bfs", "stack"],
    answer: "backtracking",
    signalIds: ["sig-all-cases", "sig-small-n"],
    highlightPhrases: ["모든 순서", "N ≤ 7"],
    explanation: "N이 작고 모든 순서를 만들어야 해요. used 배열로 순열을 만드는 백트래킹이에요.",
  },
  {
    id: "backtracking-q2",
    snippet: "9×9 스도쿠 판의 빈칸을 채우세요. 같은 가로줄, 세로줄, 3×3 칸 안에 같은 숫자가 두 번 나오면 안 돼요.",
    choices: ["dfs", "backtracking", "queue-deque"],
    answer: "backtracking",
    signalIds: ["sig-placement-constraint"],
    highlightPhrases: ["같은 숫자가 두 번 나오면 안 돼요"],
    explanation: "빈칸마다 숫자를 골라 보고, 제약을 어기면 되돌아와요. 제약 만족 백트래킹의 대표 문제예요.",
  },
  {
    id: "backtracking-q3",
    snippet: "물건 N개(N ≤ 15) 중 몇 개를 골라 무게 합이 정확히 W가 되는 방법의 수를 구하세요.",
    choices: ["stack", "backtracking", "bfs"],
    answer: "backtracking",
    signalIds: ["sig-all-cases", "sig-small-n"],
    highlightPhrases: ["몇 개를 골라", "N ≤ 15"],
    explanation: "물건마다 넣는다/뺀다를 정하는 부분집합 탐색이에요. 2^15가지라 모두 볼 수 있어요.",
  },
  {
    id: "backtracking-q4",
    snippet: "격자 지도에서 출발 칸부터 도착 칸까지 최소 몇 번 움직여야 하는지 구하세요.",
    choices: ["backtracking", "bfs", "stack"],
    answer: "bfs",
    signalIds: ["sig-shortest-steps"],
    highlightPhrases: ["최소 몇 번 움직여야"],
    explanation: "모든 길을 만들어 보면 너무 많아요. '최소 횟수'는 가까운 곳부터 퍼지는 BFS로 구해요.",
  },
  {
    id: "backtracking-q5",
    snippet: "선수 N명(N ≤ 10) 중 K명을 뽑아 팀을 만들어요. 뽑는 순서는 상관없을 때 가능한 모든 팀을 출력하세요.",
    choices: ["backtracking", "queue-deque", "graph-representation"],
    answer: "backtracking",
    signalIds: ["sig-all-cases", "sig-small-n"],
    highlightPhrases: ["순서는 상관없을 때", "모든 팀을 출력"],
    explanation: "순서 없는 뽑기라 조합이에요. 시작 인덱스를 넘겨 중복 없이 모든 팀을 만들어요.",
  },
];
