import type { ConceptCard, RecognitionQuestion } from "@/types";

export const BFS_CARDS: ConceptCard[] = [
  {
    id: "bfs-what",
    title: "가까운 곳부터 한 겹씩",
    analogy: "잔잔한 연못에 돌을 던지면 물결이 가까운 곳부터 한 겹씩 동그랗게 퍼져요.",
    body: [
      "BFS(Breadth-First Search, 너비 우선 탐색)는 출발점에서 **거리 1인 곳을 모두**, 그다음 **거리 2인 곳을 모두**… 이렇게 한 겹씩 넓혀 가며 방문해요.",
      "",
      "DFS가 한 길로 끝까지 파고든다면, BFS는 모든 방향으로 **골고루 조금씩** 나아가요.",
    ].join("\n"),
    illustration: "bfs-ripple",
    keyPoints: ["거리 0 → 1 → 2 … 순서로 방문", "DFS는 깊이 먼저, BFS는 너비 먼저", "물결처럼 퍼진다고 기억해요"],
  },
  {
    id: "bfs-queue",
    title: "큐로 만들고, 넣을 때 표시해요",
    analogy: "번호표를 받은 순서대로 부르면, 먼저 발견된 가까운 곳이 먼저 처리돼요.",
    body: [
      "먼저 발견한 곳을 먼저 처리해야 하니 **큐**(FIFO)를 써요.",
      "",
      "1. 출발점을 방문 표시하고 큐에 넣어요.",
      "2. 큐 앞에서 꺼내고, 처음 보는 이웃을 **방문 표시하면서** 큐 뒤에 넣어요.",
      "",
      "방문 표시는 **넣을 때** 해요. 꺼낼 때 하면 같은 노드가 큐에 여러 번 들어가서 느려져요.",
    ].join("\n"),
    illustration: "queue-line",
    keyPoints: [
      "큐 = 먼저 발견한 곳 먼저",
      "방문 표시는 큐에 넣을 때",
      "Python deque.popleft() · JS head 번호 · Java ArrayDeque.poll()",
    ],
    code: {
      code: {
        python: [
          "from collections import deque",
          "",
          "visited[start] = True",
          "queue = deque([start])",
          "while queue:",
          "    v = queue.popleft()",
          "    for w in graph[v]:",
          "        if not visited[w]:",
          "            visited[w] = True      # 넣을 때 표시!",
          "            queue.append(w)",
        ].join("\n"),
        javascript: [
          "visited[start] = true;",
          "const queue = [start];",
          "let head = 0;",
          "while (head < queue.length) {",
          "  const v = queue[head++];",
          "  for (const w of graph[v]) {",
          "    if (!visited[w]) {",
          "      visited[w] = true;           // 넣을 때 표시!",
          "      queue.push(w);",
          "    }",
          "  }",
          "}",
        ].join("\n"),
        java: [
          "visited[start] = true;",
          "Queue<Integer> queue = new ArrayDeque<>();",
          "queue.offer(start);",
          "while (!queue.isEmpty()) {",
          "    int v = queue.poll();",
          "    for (int w : graph.get(v)) {",
          "        if (!visited[w]) {",
          "            visited[w] = true;           // 넣을 때 표시!",
          "            queue.offer(w);",
          "        }",
          "    }",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "bfs-distance",
    title: "처음 닿은 거리가 최단 거리",
    analogy: "물결이 어떤 돌멩이에 처음 닿은 순간이, 그 돌까지 가장 빨리 닿는 시간이에요.",
    body: [
      "BFS는 가까운 곳부터 방문하니까, 어떤 노드에 **처음 닿을 때의 거리가 곧 최단 거리**예요.",
      "",
      "`dist` 배열을 -1로 채우고 `dist[w] = dist[v] + 1`로 적으면 방문 표시와 거리 기록을 한 번에 할 수 있어요.",
      "",
      "단, 모든 간선의 **비용이 같을 때**(한 칸, 한 번, 한 다리)만 성립해요.",
    ].join("\n"),
    illustration: "bfs-ripple",
    keyPoints: ["처음 방문 = 최단 거리", "dist[w] = dist[v] + 1", "간선 비용이 모두 같을 때만"],
    code: {
      code: {
        python: [
          "dist = [-1] * n",
          "dist[start] = 0",
          "queue = deque([start])",
          "while queue:",
          "    v = queue.popleft()",
          "    for w in graph[v]:",
          "        if dist[w] == -1:",
          "            dist[w] = dist[v] + 1",
          "            queue.append(w)",
        ].join("\n"),
        javascript: [
          "const dist = new Array(n).fill(-1);",
          "dist[start] = 0;",
          "const queue = [start];",
          "let head = 0;",
          "while (head < queue.length) {",
          "  const v = queue[head++];",
          "  for (const w of graph[v]) {",
          "    if (dist[w] === -1) {",
          "      dist[w] = dist[v] + 1;",
          "      queue.push(w);",
          "    }",
          "  }",
          "}",
        ].join("\n"),
        java: [
          "int[] dist = new int[n];",
          "Arrays.fill(dist, -1);",
          "dist[start] = 0;",
          "Queue<Integer> queue = new ArrayDeque<>();",
          "queue.offer(start);",
          "while (!queue.isEmpty()) {",
          "    int v = queue.poll();",
          "    for (int w : graph.get(v)) {",
          "        if (dist[w] == -1) {",
          "            dist[w] = dist[v] + 1;",
          "            queue.offer(w);",
          "        }",
          "    }",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "bfs-multi-source",
    title: "여러 곳에서 동시에 퍼지기",
    analogy: "연못 여러 곳에 동시에 돌을 던지면 물결이 한꺼번에 퍼지다 서로 만나요.",
    body: [
      "출발점이 여러 개면 BFS를 출발점마다 따로 돌리지 말고, **모든 출발점을 처음부터 한 큐에** 넣어요 (모두 거리 0).",
      "",
      "그러면 BFS 한 번으로 각 칸에 **가장 가까운 출발점까지의 거리**가 적혀요. 소문 퍼지기, 가장 가까운 대피소 같은 문제에 써요.",
    ].join("\n"),
    illustration: "bfs-ripple",
    keyPoints: [
      "모든 출발점을 거리 0으로 한 큐에",
      "BFS 한 번 = 가장 가까운 출발점까지 거리",
      "출발점마다 따로 돌리면 느려요",
    ],
  },
  {
    id: "bfs-state",
    title: "칸 대신 상태를 노드로",
    analogy: "자물쇠에 보이는 숫자 조합 하나하나를 지도의 한 칸이라고 생각해 보세요.",
    body: [
      '노드가 꼭 장소일 필요는 없어요. **다이얼 조합**, **(물통 A의 양, 물통 B의 양)** 처럼 "지금의 상황" 하나를 노드로 보고, 한 번의 동작으로 바뀌는 상황을 이웃으로 보면 돼요.',
      "",
      '"최소 몇 번의 동작"을 물으면 이 **상태 공간**에서 BFS를 돌려요. 상태의 개수가 너무 많지 않은지 먼저 세어 보세요.',
      "",
      "언제 BFS를 떠올릴까?",
      "- **최소 / 최단 / 가장 적은 횟수**",
      "- **동시에 한 겹씩 퍼진다**",
      "- 한 번의 동작 비용이 **모두 같다**",
    ].join("\n"),
    illustration: "graph-map",
    keyPoints: ["상태 = 노드, 한 번의 동작 = 간선", "'최소 횟수'는 상태 공간 BFS", "상태 수를 먼저 세어 보기"],
  },
];

export const BFS_QUIZ: RecognitionQuestion[] = [
  {
    id: "bfs-q1",
    snippet: "N×M 미로에서 출발 칸부터 도착 칸까지 최소 몇 칸을 움직여야 하는지 구하세요. 벽은 지나갈 수 없어요.",
    choices: ["dfs", "bfs", "backtracking"],
    answer: "bfs",
    signalIds: ["sig-shortest-steps", "sig-grid-neighbors"],
    highlightPhrases: ["최소 몇 칸을 움직여야"],
    explanation: "한 칸 움직이는 비용이 모두 같은 격자에서 '최소'를 물어요. BFS로 처음 닿은 거리가 답이에요.",
  },
  {
    id: "bfs-q2",
    snippet:
      "창고 곳곳에 곰팡이가 핀 빵이 있어요. 하루마다 곰팡이는 상하좌우로 붙은 빵에 옮아요. 모든 빵에 곰팡이가 피는 날을 구하세요.",
    choices: ["bfs", "stack", "recursion"],
    answer: "bfs",
    signalIds: ["sig-spread-simultaneous"],
    highlightPhrases: ["하루마다 곰팡이는 상하좌우로 붙은 빵에 옮아요"],
    explanation: "여러 곳에서 동시에 한 겹씩 퍼져요. 곰팡이 핀 빵을 모두 한 큐에 넣는 멀티 소스 BFS예요.",
  },
  {
    id: "bfs-q3",
    snippet: "숫자 x에서 시작해 한 번에 +1, ×2, −1 중 하나를 할 수 있어요. x를 y로 만드는 최소 연산 횟수를 구하세요.",
    choices: ["queue-deque", "backtracking", "bfs"],
    answer: "bfs",
    signalIds: ["sig-shortest-steps"],
    highlightPhrases: ["최소 연산 횟수"],
    explanation: "지금의 숫자를 상태(노드)로, 연산 한 번을 간선으로 보면 상태 공간 BFS예요.",
  },
  {
    id: "bfs-q4",
    snippet:
      "트럭에 택배 상자를 차례로 쌓았어요. 배달할 때는 가장 위에 있는 상자부터 내려요. 상자가 내려지는 순서를 구하세요.",
    choices: ["bfs", "stack", "dfs"],
    answer: "stack",
    signalIds: ["sig-latest-first"],
    highlightPhrases: ["가장 위에 있는 상자부터"],
    explanation: "가장 나중에 쌓은 상자가 먼저 나오는 LIFO예요. 퍼져 나가는 탐색이 아니라 스택이에요.",
  },
  {
    id: "bfs-q5",
    snippet: "1부터 N까지의 수 중 서로 다른 K개를 골라 합이 S가 되는 모든 조합을 출력하세요. (N ≤ 10)",
    choices: ["bfs", "backtracking", "queue-deque"],
    answer: "backtracking",
    signalIds: ["sig-all-cases", "sig-small-n"],
    highlightPhrases: ["모든 조합을 출력", "N ≤ 10"],
    explanation: "최소 횟수가 아니라 '모든 경우'를 만들어야 해요. N이 작으니 고르고 되돌리는 백트래킹이에요.",
  },
];
