import type { ConceptCard, RecognitionQuestion } from "@/types";

export const BINARY_SEARCH_CARDS: ConceptCard[] = [
  {
    id: "bsearch-what",
    title: "반씩 버리며 찾기",
    analogy: "업다운 게임: 1~100 중 50을 부르고 '다운'이면 51~100은 볼 필요가 없어요.",
    body: [
      "**이분 탐색**은 **정렬된** 목록에서 가운데 값을 보고, 찾는 값이 있을 수 없는 절반을 **통째로 버리는** 방법이에요.",
      "",
      "한 번 볼 때마다 후보가 반으로 줄어서, 100만 칸도 약 20번이면 끝나요. 시간은 **O(log N)** 걸려요.",
      "",
      "단, 반드시 **정렬돼 있어야** 해요. 뒤죽박죽이면 가운데 값만 보고 어느 쪽을 버릴지 알 수 없어요.",
    ].join("\n"),
    illustration: "bsearch-halving",
    keyPoints: ["가운데를 보고 절반을 버려요", "100만 칸도 약 20번", "정렬돼 있어야 해요"],
  },
  {
    id: "bsearch-template",
    title: "lo · mid · hi 세 개의 손가락",
    analogy: "책장의 왼쪽 끝과 오른쪽 끝에 손가락을 대고, 가운데 책을 꺼내 봐요.",
    body: [
      "`lo`와 `hi`는 **아직 후보인 범위**의 양 끝이에요. `mid`는 그 가운데예요.",
      "",
      "- `a[mid]`가 찾는 값이면 끝!",
      "- 찾는 값보다 **작으면** mid까지는 모두 작아요 → `lo = mid + 1`",
      "- **크면** mid부터는 모두 커요 → `hi = mid - 1`",
      "",
      "`lo > hi`가 되면 후보가 없어요. `+1`, `-1`을 빼먹으면 같은 범위를 계속 보며 **무한 반복**에 빠져요.",
    ].join("\n"),
    illustration: "bsearch-halving",
    keyPoints: ["lo~hi가 남은 후보", "작으면 lo = mid + 1, 크면 hi = mid - 1", "±1을 빼먹으면 무한 반복"],
    code: {
      code: {
        python: [
          "lo, hi = 0, len(a) - 1",
          "while lo <= hi:",
          "    mid = (lo + hi) // 2",
          "    if a[mid] == target:",
          "        return mid",
          "    if a[mid] < target:",
          "        lo = mid + 1",
          "    else:",
          "        hi = mid - 1",
          "return -1",
        ].join("\n"),
        javascript: [
          "let lo = 0, hi = a.length - 1;",
          "while (lo <= hi) {",
          "  const mid = (lo + hi) >> 1;",
          "  if (a[mid] === target) return mid;",
          "  if (a[mid] < target) lo = mid + 1;",
          "  else hi = mid - 1;",
          "}",
          "return -1;",
        ].join("\n"),
        java: [
          "int lo = 0, hi = a.length - 1;",
          "while (lo <= hi) {",
          "    int mid = (lo + hi) >>> 1;",
          "    if (a[mid] == target) return mid;",
          "    if (a[mid] < target) lo = mid + 1;",
          "    else hi = mid - 1;",
          "}",
          "return -1;",
        ].join("\n"),
      },
    },
  },
  {
    id: "bsearch-boundary",
    title: "경계 찾기: 처음으로 x 이상인 자리",
    analogy: "시험 성적표에서 '80점 이상'이 시작되는 줄에 책갈피를 꽂아요.",
    body: [
      "같은 값이 여러 개거나 찾는 값이 없을 때는 **'x 이상인 첫 위치'**(lower bound)를 찾으면 쓸모가 많아요.",
      "",
      "- `a[mid] >= x`면 mid도 답일 수 있으니 **남기고** `hi = mid`",
      "- 아니면 `lo = mid + 1`",
      "",
      "이 위치를 알면 '**x보다 작은 수의 개수**'가 바로 나와요. 범위 [l, r] 안의 개수는 `(r보다 큰 첫 위치) − (l 이상인 첫 위치)`예요.",
      "",
      "Python은 `bisect_left`, `bisect_right`가 이 일을 해 줘요.",
    ].join("\n"),
    illustration: "bsearch-halving",
    keyPoints: [
      "mid가 조건을 만족하면 남겨요 (hi = mid)",
      "x보다 작은 수의 개수 = 그 위치",
      "범위 안 개수 = 두 경계의 차",
    ],
    code: {
      code: {
        python: [
          "from bisect import bisect_left, bisect_right",
          "",
          "a = [2, 4, 4, 4, 7]",
          "print(bisect_left(a, 4))    # 1: 4 이상인 첫 위치",
          "print(bisect_right(a, 4))   # 4: 4보다 큰 첫 위치",
          "print(bisect_right(a, 4) - bisect_left(a, 4))   # 4의 개수 3",
        ].join("\n"),
        javascript: [
          "function lowerBound(a, x) {",
          "  let lo = 0, hi = a.length;",
          "  while (lo < hi) {",
          "    const mid = (lo + hi) >> 1;",
          "    if (a[mid] >= x) hi = mid;",
          "    else lo = mid + 1;",
          "  }",
          "  return lo;",
          "}",
        ].join("\n"),
        java: [
          "int lowerBound(int[] a, int x) {",
          "    int lo = 0, hi = a.length;",
          "    while (lo < hi) {",
          "        int mid = (lo + hi) >>> 1;",
          "        if (a[mid] >= x) hi = mid;",
          "        else lo = mid + 1;",
          "    }",
          "    return lo;",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "bsearch-answer",
    title: "답을 이분 탐색하기",
    analogy: "줄을 몇 cm씩 자르면 10도막이 나올까? 50cm는 안 되고 20cm는 되면, 답은 20~49 사이예요.",
    body: [
      "답을 바로 계산하긴 어렵지만 '**답이 X라면 가능한가?**'는 쉽게 확인할 수 있는 문제가 많아요.",
      "",
      "X가 커질수록 가능 → 불가능으로 **딱 한 번** 바뀐다면, 그 경계를 이분 탐색으로 찾아요. 이것을 **매개 변수 탐색**이라고 해요.",
      "",
      "1. 답의 범위 `lo ~ hi`를 정해요. (예: 1 ~ 가장 긴 줄)",
      "2. `mid`로 가능한지 확인해요. 가능하면 답을 적고 더 큰 쪽, 아니면 더 작은 쪽으로 가요.",
      "",
      "범위가 10억이어도 확인은 약 30번뿐이에요. 확인 한 번이 O(N)이면 전체 O(N log 범위)예요.",
    ].join("\n"),
    illustration: "bsearch-yes-no",
    keyPoints: ["'X로 가능한가?'를 확인하는 함수", "가능/불가능이 한 번만 바뀌어야 해요", "범위 10억도 약 30번 확인"],
  },
  {
    id: "bsearch-when",
    title: "언제 이분 탐색을 떠올릴까?",
    analogy: "사전에서 단어를 찾을 때 첫 장부터 넘기지 않고 가운데쯤 펼쳐요.",
    body: [
      "- **정렬된** 목록에서 **질문이 많아요** → 질문마다 O(log N)",
      "- '**처음으로 ~ 이상**', '**~보다 작은 개수**' → 경계 찾기",
      "- '**~할 수 있는 최대/최소**', 최대의 최소 → 답을 이분 탐색",
      "- 답의 범위가 **10억, 10¹⁸**처럼 커요 → 하나씩은 불가능, 반씩 줄여요",
      "",
      "정렬이 안 돼 있다면 먼저 정렬(O(N log N))하고 쓰면 돼요. 질문이 한 번뿐이면 그냥 훑는 O(N)이 더 나을 수도 있어요.",
    ].join("\n"),
    illustration: "bsearch-yes-no",
    keyPoints: [
      "정렬 + 질문 많음 → 이분 탐색",
      "최대/최소를 묻고 확인이 쉬우면 → 답을 이분 탐색",
      "범위가 엄청 크면 반씩",
    ],
  },
];

export const BINARY_SEARCH_QUIZ: RecognitionQuestion[] = [
  {
    id: "bsearch-q1",
    snippet:
      "정렬된 회원 번호 N개(N ≤ 100,000)가 있어요. 질문 Q개(Q ≤ 100,000)마다 그 번호가 몇 번째에 있는지 답하세요.",
    choices: ["binary-search", "stack", "bfs"],
    answer: "binary-search",
    signalIds: ["sig-sorted-many-queries"],
    highlightPhrases: ["정렬된 회원 번호", "질문 Q개"],
    explanation: "질문마다 처음부터 찾으면 100억 번이에요. 정렬돼 있으니 질문마다 이분 탐색으로 약 17번이면 돼요.",
  },
  {
    id: "bsearch-q2",
    snippet:
      "길이가 제각각인 통나무 N개를 같은 길이로 잘라 적어도 K개의 장작을 만들 때, 장작의 최대 길이를 구하세요. 통나무 길이는 최대 10억이에요.",
    choices: ["backtracking", "binary-search", "hash"],
    answer: "binary-search",
    signalIds: ["sig-max-min-answer", "sig-huge-range"],
    highlightPhrases: ["적어도 K개", "최대 길이", "최대 10억"],
    explanation: "'길이 X로 K개 이상 나오나?'는 한 번 훑으면 확인돼요. X가 길수록 불가능해지니 X를 이분 탐색해요.",
  },
  {
    id: "bsearch-q3",
    snippet: "정렬된 점수표에서 70점 이상 90점 이하인 학생 수를 구하세요.",
    choices: ["binary-search", "queue-deque", "dfs"],
    answer: "binary-search",
    signalIds: ["sig-first-true", "sig-sorted-many-queries"],
    highlightPhrases: ["정렬된 점수표", "70점 이상 90점 이하"],
    explanation: "90보다 큰 첫 위치 − 70 이상인 첫 위치가 답이에요. 경계 두 개를 이분 탐색으로 찾아요.",
  },
  {
    id: "bsearch-q4",
    snippet: "뒤섞인 단어 N개 중 같은 단어가 있는지 딱 한 번 확인하세요.",
    choices: ["binary-search", "hash", "recursion"],
    answer: "hash",
    signalIds: ["sig-seen-before"],
    highlightPhrases: ["뒤섞인", "같은 단어가 있는지"],
    explanation: "정렬돼 있지 않고 '있는지'만 물어요. set에 넣으며 확인하는 해시가 O(N)으로 가장 간단해요.",
  },
  {
    id: "bsearch-q5",
    snippet: "책 N권을 순서대로 K명에게 나눠 줄 때(각자 연속한 책), 가장 많이 받은 사람의 쪽수 합을 최소로 하세요.",
    choices: ["sorting", "binary-search", "bfs"],
    answer: "binary-search",
    signalIds: ["sig-max-min-answer"],
    highlightPhrases: ["가장 많이 받은 사람의 쪽수 합을 최소로"],
    explanation:
      "'최대의 최소' 문제예요. '한 사람이 X쪽까지만 받으면 K명 안에 나눌 수 있나?'를 확인하며 X를 이분 탐색해요.",
  },
];
