import type { ConceptCard, RecognitionQuestion } from "@/types";

export const COMPLEXITY_CARDS: ConceptCard[] = [
  {
    id: "cx-what",
    title: "왜 연산 횟수를 세나요?",
    analogy: "책장에서 책 한 권을 찾을 때, 책이 10권이면 아무렇게나 찾아도 되지만 100만 권이면 찾는 방법이 중요해져요.",
    body: [
      "컴퓨터는 1초에 대략 **1억 번** 계산해요. 채점은 보통 1~2초 안에 끝나야 해요.",
      "",
      "그래서 풀기 전에 '입력 크기 N이 커지면 몇 번 계산할까?'를 어림해요. 이걸 **시간 복잡도**라고 하고 `O(…)`로 적어요.",
      "",
      "- 1부터 N까지 한 번 도는 반복문 → `O(N)`",
      "- 반복문 안에 반복문 → `O(N²)`",
      "- 공식 한 줄 → `O(1)`",
      "",
      "`O(2N)`이나 `O(N + 5)`처럼 곱하거나 더한 상수는 떼고, 가장 빨리 커지는 부분만 봐요.",
    ].join("\n"),
    illustration: "cx-count-steps",
    keyPoints: ["1초에 약 1억 번", "N이 커질 때 몇 번 계산하는지", "상수는 떼고 가장 큰 부분만"],
  },
  {
    id: "cx-classes",
    title: "자주 만나는 복잡도",
    analogy: "걸어가기, 자전거, 자동차, 비행기처럼 방법마다 속도가 확 달라요.",
    body: [
      "빠른 순서대로예요.",
      "",
      "- `O(1)`: 공식 한 번. N이 아무리 커도 같아요.",
      "- `O(log N)`: 절반씩 줄이기. N이 10억이어도 30번이에요.",
      "- `O(√N)`: 제곱근까지만 보기. N이 10¹²이어도 100만 번이에요.",
      "- `O(N)`: 한 번 훑기.",
      "- `O(N log N)`: 정렬.",
      "- `O(N²)`: 모든 쌍 보기. N이 10만이면 100억 번이라 너무 느려요.",
      "- `O(2ᴺ)`: 모든 부분집합 보기. N이 20이면 약 100만 번이에요.",
    ].join("\n"),
    illustration: "cx-growth-curves",
    keyPoints: ["1 < log N < √N < N < N log N < N² < 2ᴺ", "N²은 N = 10만에서 너무 느려요", "log N은 10억에도 30번"],
  },
  {
    id: "cx-limits",
    title: "제한을 보고 방법 고르기",
    analogy: "도착 시간을 알면 걸어갈지 택시를 탈지 먼저 정할 수 있어요.",
    body: [
      "문제의 **입력 제한**을 보면 어느 정도로 빨라야 하는지 알 수 있어요. (1초에 1억 번 기준)",
      "",
      "- N ≤ 20 → `O(2ᴺ)`까지 괜찮아요",
      "- N ≤ 1,000 → `O(N²)`까지",
      "- N ≤ 100,000 → `O(N log N)`까지",
      "- N ≤ 10,000,000 → `O(N)`까지",
      "- 그보다 크면 → `O(√N)`, `O(log N)`, `O(1)`",
      "",
      "먼저 떠오른 방법이 느리면, 풀기 전에 더 빠른 방법을 찾아요.",
    ].join("\n"),
    illustration: "cx-growth-curves",
    keyPoints: ["제한에서 필요한 속도가 나와요", "N ≤ 10만이면 N log N까지", "N이 아주 크면 공식이나 log N"],
  },
  {
    id: "cx-reduce",
    title: "계산을 줄이는 방법들",
    analogy: "계단을 하나씩 세지 않고, 층수 × 층당 계단 수로 한 번에 구하는 것과 같아요.",
    body: [
      "- **공식으로 한 번에**: 1 + 2 + … + N = N(N + 1) / 2처럼 반복을 식 하나로 바꿔요.",
      "- **한 번 훑으며 기억하기**: 모든 쌍을 보지 않고, 지금까지의 최솟값이나 합을 들고 다녀요.",
      "- **미리 계산해 두기**: 누적 합처럼 한 번 만들어 두면 질문마다 O(1)에 답해요.",
      "- **절반씩 줄이기**: 거듭제곱을 제곱해 가며 구하면 b번이 아니라 log b번이에요.",
      "- **제곱근까지만**: 약수는 짝을 이뤄서 √N까지만 보면 돼요.",
    ].join("\n"),
    illustration: "cx-count-steps",
    keyPoints: ["반복 → 공식", "모든 쌍 → 한 번 훑기", "질문이 많으면 미리 계산"],
    code: {
      caption: "같은 답을 O(N²)과 O(N)으로 구해요: 한 번 사고 한 번 팔 때 가장 큰 이익",
      code: {
        python: [
          "# O(N²): 모든 쌍",
          "best = 0",
          "for i in range(n):",
          "    for j in range(i + 1, n):",
          "        best = max(best, prices[j] - prices[i])",
          "",
          "# O(N): 지금까지 가장 싼 가격만 기억",
          "best, low = 0, prices[0]",
          "for p in prices:",
          "    best = max(best, p - low)",
          "    low = min(low, p)",
        ].join("\n"),
        javascript: [
          "// O(N²): 모든 쌍",
          "let best = 0;",
          "for (let i = 0; i < n; i++)",
          "  for (let j = i + 1; j < n; j++)",
          "    best = Math.max(best, prices[j] - prices[i]);",
          "",
          "// O(N): 지금까지 가장 싼 가격만 기억",
          "best = 0;",
          "let low = prices[0];",
          "for (const p of prices) {",
          "  best = Math.max(best, p - low);",
          "  low = Math.min(low, p);",
          "}",
        ].join("\n"),
        java: [
          "// O(N²): 모든 쌍",
          "int best = 0;",
          "for (int i = 0; i < n; i++)",
          "    for (int j = i + 1; j < n; j++)",
          "        best = Math.max(best, prices[j] - prices[i]);",
          "",
          "// O(N): 지금까지 가장 싼 가격만 기억",
          "best = 0;",
          "int low = prices[0];",
          "for (int p : prices) {",
          "    best = Math.max(best, p - low);",
          "    low = Math.min(low, p);",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "cx-when",
    title: "모든 문제의 첫 단계",
    analogy: "요리 전에 손님이 몇 명인지부터 확인하는 것과 같아요.",
    body: [
      "시간 복잡도는 따로 떨어진 유형이라기보다 **모든 문제에서 먼저 하는** 어림이에요.",
      "",
      "1. 입력 제한을 읽어요.",
      "2. 떠오른 방법의 연산 횟수를 어림해요.",
      "3. 1억 번을 크게 넘으면 더 빠른 방법을 찾아요. 이때 뒤에서 배우는 스택·해시·정렬·이분 탐색·DP 같은 도구가 필요해져요.",
      "",
      "이 토픽의 문제는 **반복문과 배열만으로** 느린 방법을 빠르게 바꾸는 연습이에요.",
    ].join("\n"),
    illustration: "cx-count-steps",
    keyPoints: ["제한 읽기 → 횟수 어림 → 방법 고르기", "1억 번이 기준", "반복문과 배열만으로 줄이는 연습"],
  },
];

export const COMPLEXITY_QUIZ: RecognitionQuestion[] = [
  {
    id: "cx-q1",
    snippet: "1 ≤ N ≤ 10¹⁵일 때, 1부터 N까지의 수 중 7의 배수는 몇 개인가요?",
    choices: ["complexity", "binary-search", "dp"],
    answer: "complexity",
    signalIds: ["sig-huge-n"],
    highlightPhrases: ["N ≤ 10¹⁵"],
    explanation: "N이 너무 커서 하나씩 셀 수 없어요. N을 7로 나눈 몫이 답인 O(1) 공식이에요.",
  },
  {
    id: "cx-q2",
    snippet: "a의 b제곱을 1,000,007로 나눈 나머지를 구하세요. (b ≤ 10¹⁸)",
    choices: ["hash", "complexity", "sorting"],
    answer: "complexity",
    signalIds: ["sig-huge-n"],
    highlightPhrases: ["b ≤ 10¹⁸"],
    explanation: "a를 b번 곱하면 너무 느려요. a², a⁴, a⁸…처럼 제곱해 가며 b를 절반씩 줄이면 O(log b)예요.",
  },
  {
    id: "cx-q3",
    snippet: "물건 N개(N ≤ 20) 중 몇 개를 골라 무게 합이 정확히 K가 되는 방법의 수를 모두 세세요.",
    choices: ["complexity", "backtracking", "heap"],
    answer: "backtracking",
    signalIds: ["sig-small-n"],
    highlightPhrases: ["N ≤ 20", "모두 세세요"],
    explanation: "N이 20 이하라 2²⁰ ≈ 100만 가지를 모두 봐도 충분해요. 입력이 작으면 느린 방법도 괜찮아요.",
  },
  {
    id: "cx-q4",
    snippet: "N의 약수는 모두 몇 개인가요? (N ≤ 10¹²)",
    choices: ["complexity", "greedy", "two-pointers"],
    answer: "complexity",
    signalIds: ["sig-huge-n"],
    highlightPhrases: ["N ≤ 10¹²"],
    explanation: "약수는 i와 N / i로 짝을 이뤄요. √N = 100만까지만 보면 돼요.",
  },
  {
    id: "cx-q5",
    snippet: "정수 N개(N ≤ 100,000)가 있어요. 두 수의 차이 중 가장 작은 값을 구하세요.",
    choices: ["complexity", "sorting", "stack"],
    answer: "sorting",
    signalIds: ["sig-neighbor-after-sort"],
    highlightPhrases: ["두 수의 차이 중 가장 작은 값"],
    explanation:
      "모든 쌍은 N²이라 느려요. 정렬하면 가장 가까운 두 수가 이웃이 되어 O(N log N)이에요. 줄이는 도구가 정렬이라 정렬 유형이에요.",
  },
];
