import type { ConceptCard, RecognitionQuestion } from "@/types";

export const DIJKSTRA_CARDS: ConceptCard[] = [
  {
    id: "dijkstra-what",
    title: "길마다 걸리는 시간이 다를 때",
    analogy: "내비게이션은 지나는 교차로 수가 아니라 걸리는 시간이 가장 짧은 길을 알려 줘요.",
    body: [
      "BFS는 **간선을 몇 번 지났는지**로 거리를 재요. 모든 길의 비용이 같을 때만 그게 최단 거리예요.",
      "",
      "길마다 비용이 다르면 이야기가 달라져요. 곧장 가는 길이 10분이고, 한 마을을 거쳐 가는 길이 2분 + 3분이면 **돌아가는 쪽이 더 빨라요**.",
      "",
      "**다익스트라**는 간선 비용이 다른 그래프에서 **한 출발점에서 모든 노드까지의 최단 거리**를 구해요. 단, 비용이 **0 이상**이어야 해요.",
    ].join("\n"),
    illustration: "dijkstra-map",
    keyPoints: ["비용이 다르면 BFS로는 안 돼요", "한 출발점 → 모든 노드의 최단 거리", "비용은 0 이상이어야 해요"],
  },
  {
    id: "dijkstra-settle",
    title: "가장 가까운 곳부터 확정",
    analogy: "잉크 방울이 종이에 번지듯, 출발점에서 가까운 곳부터 차례로 물들어요.",
    body: [
      "다익스트라는 한 번에 한 노드씩 **거리를 확정**해요.",
      "",
      "1. 아직 확정하지 않은 노드 중 **지금까지 알려진 거리가 가장 짧은 노드**를 골라 확정해요.",
      "2. 그 노드에서 이웃으로 가는 길을 보고, 더 짧아지면 이웃의 거리를 **줄여요**.",
      "3. 모든 노드를 확정할 때까지 반복해요.",
      "",
      "가장 가까운 노드는 왜 확정해도 될까요? 다른 노드를 거쳐 오면 그 노드까지 이미 더 멀고, 비용이 음수가 아니니 **돌아와도 짧아질 수 없어요**.",
    ].join("\n"),
    illustration: "dijkstra-settle",
    keyPoints: ["가장 가까운 노드부터 확정", "이웃의 거리를 줄이기(relax)", "음수 비용이 없어야 성립해요"],
  },
  {
    id: "dijkstra-code",
    title: "힙으로 가장 가까운 노드 찾기",
    analogy: "대기표에 (지금 아는 거리, 노드)를 적어 힙에 넣으면, 가장 짧은 표가 늘 맨 위에 있어요.",
    body: [
      "'가장 가까운 노드 고르기'를 매번 전부 훑으면 느려요. **힙**에 `(거리, 노드)`를 넣으면 O(log N)에 꺼낼 수 있어요.",
      "",
      "거리를 줄일 때마다 새 표를 힙에 넣기만 하고, 예전 표는 지우지 않아요. 대신 꺼낸 표의 거리가 `dist[v]`보다 크면 **오래된 기록**이니 버려요.",
      "",
      "시간은 노드 V개, 간선 E개일 때 **O((V + E) log V)** 걸려요.",
    ].join("\n"),
    illustration: "dijkstra-settle",
    keyPoints: ["힙에 (거리, 노드)", "오래된 기록은 꺼낼 때 버려요", "O((V + E) log V)"],
    code: {
      code: {
        python: [
          "import heapq",
          "",
          "def dijkstra(n, graph, start):   # graph[v] = [(w, cost), ...]",
          "    dist = [float('inf')] * n",
          "    dist[start] = 0",
          "    heap = [(0, start)]",
          "    while heap:",
          "        d, v = heapq.heappop(heap)",
          "        if d > dist[v]:",
          "            continue               # 오래된 기록",
          "        for w, cost in graph[v]:",
          "            if d + cost < dist[w]:",
          "                dist[w] = d + cost",
          "                heapq.heappush(heap, (dist[w], w))",
          "    return dist",
        ].join("\n"),
        javascript: [
          "// Heap: 힙 토픽에서 만든 최소 힙 (비교 함수를 받는 버전)",
          "function dijkstra(n, graph, start) {   // graph[v] = [[w, cost], ...]",
          "  const dist = new Array(n).fill(Infinity);",
          "  dist[start] = 0;",
          "  const heap = new Heap((a, b) => a[0] < b[0]);",
          "  heap.push([0, start]);",
          "  while (heap.size > 0) {",
          "    const [d, v] = heap.pop();",
          "    if (d > dist[v]) continue;          // 오래된 기록",
          "    for (const [w, cost] of graph[v]) {",
          "      if (d + cost < dist[w]) {",
          "        dist[w] = d + cost;",
          "        heap.push([dist[w], w]);",
          "      }",
          "    }",
          "  }",
          "  return dist;",
          "}",
        ].join("\n"),
        java: [
          "// graph.get(v) = [[w, cost], ...]",
          "long[] dijkstra(int n, List<List<int[]>> graph, int start) {",
          "    long[] dist = new long[n];",
          "    Arrays.fill(dist, Long.MAX_VALUE);",
          "    dist[start] = 0;",
          "    PriorityQueue<long[]> heap = new PriorityQueue<>((a, b) -> Long.compare(a[0], b[0]));",
          "    heap.offer(new long[] {0, start});",
          "    while (!heap.isEmpty()) {",
          "        long[] top = heap.poll();",
          "        long d = top[0];",
          "        int v = (int) top[1];",
          "        if (d > dist[v]) continue;       // 오래된 기록",
          "        for (int[] e : graph.get(v)) {",
          "            if (d + e[1] < dist[e[0]]) {",
          "                dist[e[0]] = d + e[1];",
          "                heap.offer(new long[] {dist[e[0]], e[0]});",
          "            }",
          "        }",
          "    }",
          "    return dist;",
          "}",
        ].join("\n"),
      },
      caption: "JavaScript에는 기본 힙이 없어서 힙 토픽의 Heap 클래스를 함께 써요.",
    },
  },
  {
    id: "dijkstra-variants",
    title: "조금씩 바꿔 쓰는 다익스트라",
    analogy: "같은 내비게이션도 '톨게이트 피하기', '가장 가까운 주유소' 같은 옵션을 붙일 수 있어요.",
    body: [
      "- **경로 되짚기**: 거리를 줄일 때 `prev[w] = v`로 어디서 왔는지 적어 두고, 도착점에서 거꾸로 따라가요.",
      "- **여러 출발점**: 출발점을 모두 거리 0으로 힙에 넣고 시작하면, 각 노드에서 가장 가까운 출발점까지의 거리가 나와요.",
      "- **모두가 한 곳으로**: 간선 방향을 뒤집은 그래프에서 도착점을 출발점으로 한 번만 돌려요.",
      "- **상태 더하기**: 쿠폰을 썼는지, 몇 번 갈아탔는지를 노드에 붙여 `(노드, 상태)`를 새 노드로 봐요.",
      "- **격자**: 칸이 노드, 이웃 칸이 간선이에요.",
    ].join("\n"),
    illustration: "dijkstra-map",
    keyPoints: ["prev로 경로 되짚기", "여러 출발점은 모두 0으로 시작", "(노드, 상태)를 새 노드로"],
  },
  {
    id: "dijkstra-when",
    title: "언제 다익스트라를 떠올릴까?",
    analogy: "지도 앱을 켜야 할지, 그냥 걸어가도 될지 먼저 판단하는 것과 같아요.",
    body: [
      "- 간선마다 **비용이 다르고**, **최소 비용·최단 시간**을 물어요 → 다익스트라",
      "- 모든 비용이 **같아요** → BFS가 더 간단하고 빨라요",
      "- 오른쪽·아래로만 가는 격자처럼 **되돌아올 수 없는** 길 → DP로 충분해요",
      "- 비용이 **음수**일 수 있어요 → 다익스트라는 틀려요 (벨만-포드 같은 다른 방법)",
    ].join("\n"),
    illustration: "dijkstra-map",
    keyPoints: ["비용이 다름 + 최소 비용 → 다익스트라", "비용이 같으면 BFS", "한 방향 격자면 DP"],
  },
];

export const DIJKSTRA_QUIZ: RecognitionQuestion[] = [
  {
    id: "dijkstra-q1",
    snippet:
      "마을 N개(N ≤ 10,000)를 잇는 길마다 걸리는 시간이 달라요. 1번 마을에서 출발해 각 마을까지 가장 빨리 도착하는 시간을 구하세요.",
    choices: ["bfs", "dijkstra", "dp"],
    answer: "dijkstra",
    signalIds: ["sig-weighted-route"],
    highlightPhrases: ["길마다 걸리는 시간이 달라요", "가장 빨리 도착하는 시간"],
    explanation: "길마다 시간이 다르니 지나는 길 수로는 알 수 없어요. 가장 가까운 마을부터 확정하는 다익스트라예요.",
  },
  {
    id: "dijkstra-q2",
    snippet: "미로에서 한 번에 상하좌우로 한 칸씩 움직여요. 출구까지 최소 몇 번 움직여야 하나요?",
    choices: ["dijkstra", "bfs", "backtracking"],
    answer: "bfs",
    signalIds: ["sig-shortest-steps"],
    highlightPhrases: ["한 칸씩", "최소 몇 번"],
    explanation: "한 번 움직이는 비용이 모두 1로 같아요. 이럴 땐 BFS가 더 간단하고 빨라요.",
  },
  {
    id: "dijkstra-q3",
    snippet:
      "도시 사이 기차 요금이 주어져요. 한 구간의 요금을 반으로 줄이는 쿠폰이 한 장 있을 때, 출발 도시에서 도착 도시까지 가장 싼 요금은?",
    choices: ["greedy", "dp", "dijkstra"],
    answer: "dijkstra",
    signalIds: ["sig-route-with-state"],
    highlightPhrases: ["쿠폰이 한 장", "가장 싼 요금"],
    explanation:
      "(도시, 쿠폰을 썼는지)를 하나의 노드로 보면 노드가 두 배인 그래프가 돼요. 그 위에서 다익스트라를 돌려요.",
  },
  {
    id: "dijkstra-q4",
    snippet:
      "높이 지도에서 왼쪽 위부터 오른쪽 아래까지 가요. 경로의 '험하기'는 이웃한 두 칸 높이 차 중 가장 큰 값이에요. 가장 덜 험한 경로의 험하기는?",
    choices: ["dijkstra", "dfs", "greedy"],
    answer: "dijkstra",
    signalIds: ["sig-worst-edge"],
    highlightPhrases: ["가장 큰 값", "가장 덜 험한 경로"],
    explanation:
      "경로의 값이 합이 아니라 '가장 큰 값'이지만, 가장 작은 후보부터 확정하는 방식은 그대로 통해요. 거리 대신 max(지금까지, 높이 차)를 넣어요.",
  },
  {
    id: "dijkstra-q5",
    snippet:
      "칸마다 비용이 적힌 격자에서 오른쪽이나 아래로만 움직여요. 왼쪽 위에서 오른쪽 아래까지 비용 합의 최솟값은?",
    choices: ["dijkstra", "dp", "bfs"],
    answer: "dp",
    signalIds: ["sig-overlapping-subproblems"],
    highlightPhrases: ["오른쪽이나 아래로만"],
    explanation:
      "오른쪽·아래로만 가면 되돌아오는 길이 없어서, 위 칸과 왼쪽 칸 중 작은 쪽 + 이 칸으로 표를 채우면 돼요. 다익스트라도 맞지만 DP가 더 간단해요.",
  },
];
