import type { ConceptCard, RecognitionQuestion } from "@/types";

export const DP_CARDS: ConceptCard[] = [
  {
    id: "dp-what",
    title: "한 번 푼 답은 적어 두기",
    analogy: "구구단을 외워 두면 7 × 8을 매번 7을 여덟 번 더해서 구하지 않아도 돼요.",
    body: [
      "**DP**(동적 계획법)는 큰 문제를 **작은 문제의 답**으로 풀되, 작은 문제의 답을 **표에 적어 두고** 다시 쓰는 방법이에요.",
      "",
      "피보나치를 재귀로 그대로 풀면 f(3)을 몇 번이고 다시 계산해요. f(40)이면 호출이 3억 번을 넘어요. 한 번 구한 f(k)를 적어 두면 각각 **한 번씩만** 계산해서 41번이면 끝나요.",
      "",
      "DP가 되려면 두 가지가 필요해요.",
      "",
      "- **같은 작은 문제가 반복**돼요 (그래서 적어 둘 가치가 있어요).",
      "- 작은 문제의 답을 합치면 **큰 문제의 답**이 돼요.",
    ].join("\n"),
    illustration: "dp-memo-notebook",
    keyPoints: ["작은 문제의 답을 표에 적어 둬요", "같은 계산을 다시 하지 않아요", "작은 답을 합쳐 큰 답을 만들어요"],
  },
  {
    id: "dp-steps",
    title: "DP를 세우는 세 단계",
    analogy: "요리 레시피: 무엇을 만들지(표의 뜻), 재료를 어떻게 섞을지(점화식), 첫 재료(시작 값).",
    body: [
      "1. **표의 뜻 정하기**: `dp[i]`가 무엇인지 한 문장으로 말해요. 예: `dp[i]` = i칸까지 오는 방법의 수",
      "2. **점화식 세우기**: `dp[i]`를 더 작은 칸들로 표현해요. 예: `dp[i] = dp[i-1] + dp[i-2]`",
      "3. **시작 값과 순서**: 가장 작은 칸(`dp[0]`, `dp[1]`)을 채우고, 필요한 칸이 먼저 채워지는 순서로 돌아요.",
      "",
      "1번이 가장 중요해요. 표의 뜻이 분명하면 점화식은 '마지막에 무엇을 했나?'만 생각하면 나와요.",
    ].join("\n"),
    illustration: "dp-table-fill",
    keyPoints: ["dp[i]의 뜻을 한 문장으로", "마지막 선택으로 점화식 세우기", "시작 값 + 채우는 순서"],
    code: {
      code: {
        python: [
          "def climb(n):",
          "    ways = [0] * (n + 1)",
          "    ways[0] = ways[1] = 1",
          "    for i in range(2, n + 1):",
          "        ways[i] = ways[i - 1] + ways[i - 2]",
          "    return ways[n]",
        ].join("\n"),
        javascript: [
          "function climb(n) {",
          "  const ways = Array(n + 1).fill(0);",
          "  ways[0] = ways[1] = 1;",
          "  for (let i = 2; i <= n; i++) {",
          "    ways[i] = ways[i - 1] + ways[i - 2];",
          "  }",
          "  return ways[n];",
          "}",
        ].join("\n"),
        java: [
          "long climb(int n) {",
          "    long[] ways = new long[n + 1];",
          "    ways[0] = 1;",
          "    if (n >= 1) ways[1] = 1;",
          "    for (int i = 2; i <= n; i++) {",
          "        ways[i] = ways[i - 1] + ways[i - 2];",
          "    }",
          "    return ways[n];",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "dp-grid",
    title: "2차원 표: 격자와 두 문자열",
    analogy: "바둑판 칸마다 '여기까지 오는 길의 수'를 적어 가면, 마지막 칸에 답이 쌓여요.",
    body: [
      "상태가 두 가지로 정해지면 표도 2차원이에요.",
      "",
      "- **격자**: `dp[r][c]` = (r, c)까지 오는 방법 수(또는 최소 비용). 오른쪽·아래로만 가면 `위 + 왼쪽`에서 와요.",
      "- **두 문자열**: `dp[i][j]` = A의 앞 i글자와 B의 앞 j글자에 대한 답. 마지막 글자가 **같은지 다른지**로 나눠요.",
      "",
      "표를 **왼쪽 위부터** 채우면 필요한 칸(위·왼쪽·대각선)이 항상 먼저 채워져 있어요.",
    ].join("\n"),
    illustration: "dp-table-fill",
    keyPoints: ["상태가 두 개면 2차원 표", "격자: 위 + 왼쪽", "두 문자열: 마지막 글자가 같은지"],
  },
  {
    id: "dp-choice",
    title: "고를까 말까: 배낭과 동전",
    analogy: "여행 가방에 물건을 넣을지 말지, 무게가 남는 만큼 계속 비교해요.",
    body: [
      "물건마다 **넣는다 / 안 넣는다**를 정하는 문제는 백트래킹이면 2^N가지예요. N이 100이면 불가능해요.",
      "",
      "DP는 '**무게 w까지 썼을 때의 최대 가치**'를 표에 적어 두고, 물건을 하나씩 보며 표를 고쳐요.",
      "",
      "- 0/1 배낭(물건마다 한 번): `dp[w] = max(dp[w], dp[w - 무게] + 가치)`, w를 **큰 쪽부터** 돌아요 (같은 물건을 두 번 넣지 않게).",
      "- 동전(몇 번이든): w를 **작은 쪽부터** 돌면 같은 동전을 여러 번 쓸 수 있어요.",
      "",
      "시간은 물건 수 × 무게 한도예요.",
    ].join("\n"),
    illustration: "dp-table-fill",
    keyPoints: ["넣는다/안 넣는다를 표로 비교", "0/1 배낭은 큰 무게부터", "무제한(동전)은 작은 금액부터"],
    code: {
      code: {
        python: [
          "dp = [0] * (limit + 1)          # dp[w] = 무게 w 이하로 얻는 최대 가치",
          "for weight, value in items:",
          "    for w in range(limit, weight - 1, -1):   # 큰 쪽부터!",
          "        dp[w] = max(dp[w], dp[w - weight] + value)",
        ].join("\n"),
        javascript: [
          "const dp = Array(limit + 1).fill(0);   // dp[w] = 무게 w 이하로 얻는 최대 가치",
          "for (const [weight, value] of items) {",
          "  for (let w = limit; w >= weight; w--) {   // 큰 쪽부터!",
          "    dp[w] = Math.max(dp[w], dp[w - weight] + value);",
          "  }",
          "}",
        ].join("\n"),
        java: [
          "int[] dp = new int[limit + 1];   // dp[w] = 무게 w 이하로 얻는 최대 가치",
          "for (int[] item : items) {",
          "    for (int w = limit; w >= item[0]; w--) {   // 큰 쪽부터!",
          "        dp[w] = Math.max(dp[w], dp[w - item[0]] + item[1]);",
          "    }",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "dp-when",
    title: "언제 DP를 떠올릴까?",
    analogy: "같은 길을 몇 번이고 다시 걷고 있다면, 지도에 표시를 해 두세요.",
    body: [
      "- '**방법의 수**를 1,000,000,007로 나눈 나머지' → 개수가 너무 많아 하나씩 못 세요.",
      "- **최대 / 최소**를 묻는데, 한 번의 선택이 다음 선택에 영향을 줘요 → 욕심(탐욕)으로는 틀릴 수 있어요.",
      "- **두 문자열**의 공통 부분·편집 거리",
      "- 재귀로 풀어 보니 **같은 인자로 여러 번** 불려요 → 메모를 붙이면 DP예요.",
      "",
      "반대로 '모든 경우를 **출력**'하라면 백트래킹, '**최소 이동 횟수**'(간선 비용이 같음)면 BFS를 먼저 생각해요.",
    ].join("\n"),
    illustration: "dp-memo-notebook",
    keyPoints: ["방법의 수 + 나머지 → DP", "선택이 이어지는 최대/최소 → DP", "모든 경우 출력은 백트래킹"],
  },
];

export const DP_QUIZ: RecognitionQuestion[] = [
  {
    id: "dp-q1",
    snippet: "N칸 계단을 1칸 또는 2칸씩 오르는 방법의 수를 1,000,000,007로 나눈 나머지를 구하세요. (N ≤ 100,000)",
    choices: ["dp", "backtracking", "bfs"],
    answer: "dp",
    signalIds: ["sig-count-ways-mod", "sig-overlapping-subproblems"],
    highlightPhrases: ["방법의 수를 1,000,000,007로 나눈 나머지"],
    explanation: "방법을 하나씩 나열하면 너무 많아요. i칸까지의 방법 수 = (i-1칸) + (i-2칸)을 표에 채워요.",
  },
  {
    id: "dp-q2",
    snippet:
      "물건 N개(N ≤ 100)의 무게와 가치가 주어져요. 무게 합이 W 이하가 되게 골라 가치의 합을 최대로 하세요. (W ≤ 10,000)",
    choices: ["hash", "dp", "backtracking"],
    answer: "dp",
    signalIds: ["sig-best-choice-sequence"],
    highlightPhrases: ["무게 합이 W 이하", "가치의 합을 최대로"],
    explanation: "N이 100이라 모든 조합(2^100)은 불가능해요. 무게별 최대 가치를 표에 적는 배낭 DP예요.",
  },
  {
    id: "dp-q3",
    snippet: "두 단어가 주어질 때, 한 단어를 다른 단어로 바꾸는 최소 편집(삽입·삭제·교체) 횟수를 구하세요.",
    choices: ["dp", "stack", "sorting"],
    answer: "dp",
    signalIds: ["sig-two-strings"],
    highlightPhrases: ["최소 편집"],
    explanation: "앞 i글자와 앞 j글자에 대한 답을 dp[i][j]에 적고, 마지막 글자가 같은지 보고 이웃 칸에서 가져와요.",
  },
  {
    id: "dp-q4",
    snippet: "숫자 N개(N ≤ 8)로 만들 수 있는 모든 순서를 출력하세요.",
    choices: ["dp", "backtracking", "binary-search"],
    answer: "backtracking",
    signalIds: ["sig-all-cases", "sig-small-n"],
    highlightPhrases: ["모든 순서를 출력"],
    explanation: "개수가 아니라 경우를 하나하나 출력해야 해요. N이 작으니 고르고 되돌리는 백트래킹이에요.",
  },
  {
    id: "dp-q5",
    snippet:
      "일렬로 놓인 집들에서 이웃한 두 집은 함께 고를 수 없을 때, 고른 집의 금액 합의 최댓값을 구하세요. (집 ≤ 100,000채)",
    choices: ["dp", "queue-deque", "hash"],
    answer: "dp",
    signalIds: ["sig-best-choice-sequence"],
    highlightPhrases: ["이웃한 두 집은 함께 고를 수 없을 때"],
    explanation:
      "i번째 집까지의 최대 = max(i-1번째까지의 최대, i-2번째까지의 최대 + i번째 집). 가장 큰 집부터 욕심껏 고르면 틀릴 수 있어요.",
  },
];
