import type { ConceptCard, RecognitionQuestion } from "@/types";

export const GRAPH_ADVANCED_CARDS: ConceptCard[] = [
  {
    id: "ga-uf-what",
    title: "같은 그룹인가요? (유니온 파인드)",
    analogy: "반마다 반장이 있으면, 두 친구가 같은 반인지는 반장이 같은지만 보면 돼요.",
    body: [
      "**유니온 파인드**는 여러 그룹을 다루는 도구예요. 그룹마다 **대표** 하나를 두고, 모든 노드는 부모(`parent`)를 따라 올라가면 대표에 닿아요.",
      "",
      "- **find(x)**: x가 속한 그룹의 대표 찾기",
      "- **union(a, b)**: a의 그룹과 b의 그룹 합치기 (한 대표를 다른 대표 밑에 붙여요)",
      "",
      "관계가 하나씩 늘어나는 동안 '같은 그룹인가?'를 계속 물을 때, 매번 DFS를 다시 하지 않고 거의 O(1)에 답해요.",
    ].join("\n"),
    illustration: "uf-groups",
    keyPoints: ["그룹마다 대표 하나", "find: 대표 찾기, union: 대표끼리 잇기", "관계가 늘어나며 계속 물을 때"],
  },
  {
    id: "ga-uf-code",
    title: "find와 union을 빠르게",
    analogy: "반장까지 가는 길을 한 번 알아 두면, 다음부터는 반장에게 바로 가요.",
    body: [
      "그냥 붙이기만 하면 부모를 따라 올라가는 줄이 길어져서 find가 O(N)이 될 수 있어요. 두 가지로 줄여요.",
      "",
      "- **경로 압축**: find하며 지나온 노드가 대표를 **바로** 가리키게 바꿔요.",
      "- **크기로 합치기**: 작은 그룹을 큰 그룹 밑에 붙여서 줄이 깊어지지 않게 해요.",
      "",
      "둘을 함께 쓰면 find와 union이 사실상 O(1)이에요. find를 재귀로 짜면 줄이 길 때 재귀 깊이 제한에 걸릴 수 있어서, 반복문으로 쓰는 게 안전해요.",
    ].join("\n"),
    illustration: "uf-groups",
    keyPoints: ["경로 압축: 대표를 바로 가리키게", "작은 그룹을 큰 그룹 밑에", "find는 반복문이 안전해요"],
    code: {
      code: {
        python: [
          "parent = list(range(n))",
          "size = [1] * n",
          "",
          "def find(x):",
          "    root = x",
          "    while parent[root] != root:",
          "        root = parent[root]",
          "    while x != root:              # 경로 압축",
          "        nxt = parent[x]",
          "        parent[x] = root",
          "        x = nxt",
          "    return root",
          "",
          "def union(a, b):",
          "    ra, rb = find(a), find(b)",
          "    if ra == rb:",
          "        return False              # 이미 같은 그룹",
          "    if size[ra] < size[rb]:",
          "        ra, rb = rb, ra",
          "    parent[rb] = ra               # 작은 그룹을 큰 그룹 밑에",
          "    size[ra] += size[rb]",
          "    return True",
        ].join("\n"),
        javascript: [
          "const parent = Array.from({ length: n }, (_, i) => i);",
          "const size = new Array(n).fill(1);",
          "",
          "function find(x) {",
          "  let root = x;",
          "  while (parent[root] !== root) root = parent[root];",
          "  while (x !== root) {            // 경로 압축",
          "    const next = parent[x];",
          "    parent[x] = root;",
          "    x = next;",
          "  }",
          "  return root;",
          "}",
          "",
          "function union(a, b) {",
          "  let ra = find(a), rb = find(b);",
          "  if (ra === rb) return false;     // 이미 같은 그룹",
          "  if (size[ra] < size[rb]) [ra, rb] = [rb, ra];",
          "  parent[rb] = ra;                 // 작은 그룹을 큰 그룹 밑에",
          "  size[ra] += size[rb];",
          "  return true;",
          "}",
        ].join("\n"),
        java: [
          "int[] parent, size;",
          "",
          "int find(int x) {",
          "    int root = x;",
          "    while (parent[root] != root) root = parent[root];",
          "    while (x != root) {            // 경로 압축",
          "        int next = parent[x];",
          "        parent[x] = root;",
          "        x = next;",
          "    }",
          "    return root;",
          "}",
          "",
          "boolean union(int a, int b) {",
          "    int ra = find(a), rb = find(b);",
          "    if (ra == rb) return false;    // 이미 같은 그룹",
          "    if (size[ra] < size[rb]) { int t = ra; ra = rb; rb = t; }",
          "    parent[rb] = ra;               // 작은 그룹을 큰 그룹 밑에",
          "    size[ra] += size[rb];",
          "    return true;",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "ga-mst",
    title: "모두 잇는 가장 싼 방법 (크루스칼)",
    analogy: "마을마다 전기를 놓을 때, 싼 공사부터 하되 이미 전기가 통하는 두 마을 사이는 또 잇지 않아요.",
    body: [
      "노드 N개를 **모두 잇는** 간선 N − 1개 중 비용 합이 가장 작은 것을 **최소 신장 트리**라고 해요.",
      "",
      "**크루스칼**은 유니온 파인드로 이렇게 구해요.",
      "",
      "1. 간선을 비용이 싼 순서로 정렬해요.",
      "2. 싼 간선부터 보며, 두 끝이 **다른 그룹**이면 잇고(union), **같은 그룹**이면 고리가 생기니 건너뛰어요.",
      "3. 간선을 N − 1개 골랐으면 끝이에요.",
      "",
      "정렬이 대부분이라 시간은 **O(E log E)** 정도예요.",
    ].join("\n"),
    illustration: "uf-groups",
    keyPoints: ["싼 간선부터", "같은 그룹이면 건너뛰기 (고리)", "간선 N − 1개면 끝"],
  },
  {
    id: "ga-topo",
    title: "먼저 할 일부터 (위상 정렬)",
    analogy: "양말을 신어야 신발을 신을 수 있어요. 먼저 할 일이 없는 옷부터 하나씩 입으면 돼요.",
    body: [
      "'a를 끝내야 b를 할 수 있다'를 a → b 화살표로 그려요. 모든 화살표 방향을 지키는 줄을 **위상 정렬**이라고 해요.",
      "",
      "1. 노드마다 들어오는 화살표 수(**진입 차수**)를 세요.",
      "2. 진입 차수가 0인 노드(지금 바로 할 수 있는 일)를 큐에 넣어요.",
      "3. 큐에서 꺼낼 때마다 나가는 화살표를 지워요. 새로 0이 된 노드를 큐에 넣어요.",
      "",
      "끝까지 꺼내지 못한 노드가 있으면, 조건이 **고리**를 이뤄서 동시에 지킬 수 없다는 뜻이에요.",
    ].join("\n"),
    illustration: "topo-order",
    keyPoints: ["진입 차수 0부터 꺼내기", "꺼낼 때 나가는 화살표 지우기", "남은 노드가 있으면 고리"],
    code: {
      code: {
        python: [
          "from collections import deque",
          "",
          "graph = [[] for _ in range(n)]",
          "indeg = [0] * n",
          "for a, b in edges:           # a를 먼저",
          "    graph[a].append(b)",
          "    indeg[b] += 1",
          "",
          "queue = deque(v for v in range(n) if indeg[v] == 0)",
          "order = []",
          "while queue:",
          "    v = queue.popleft()",
          "    order.append(v)",
          "    for w in graph[v]:",
          "        indeg[w] -= 1",
          "        if indeg[w] == 0:",
          "            queue.append(w)",
          "# len(order) < n 이면 고리가 있어요",
        ].join("\n"),
        javascript: [
          "const graph = Array.from({ length: n }, () => []);",
          "const indeg = new Array(n).fill(0);",
          "for (const [a, b] of edges) {  // a를 먼저",
          "  graph[a].push(b);",
          "  indeg[b]++;",
          "}",
          "",
          "const queue = [];",
          "for (let v = 0; v < n; v++) if (indeg[v] === 0) queue.push(v);",
          "const order = [];",
          "for (let head = 0; head < queue.length; head++) {",
          "  const v = queue[head];",
          "  order.push(v);",
          "  for (const w of graph[v]) {",
          "    if (--indeg[w] === 0) queue.push(w);",
          "  }",
          "}",
          "// order.length < n 이면 고리가 있어요",
        ].join("\n"),
        java: [
          "List<List<Integer>> graph = new ArrayList<>();",
          "for (int i = 0; i < n; i++) graph.add(new ArrayList<>());",
          "int[] indeg = new int[n];",
          "for (int[] e : edges) {            // e[0]을 먼저",
          "    graph.get(e[0]).add(e[1]);",
          "    indeg[e[1]]++;",
          "}",
          "",
          "ArrayDeque<Integer> queue = new ArrayDeque<>();",
          "for (int v = 0; v < n; v++) if (indeg[v] == 0) queue.add(v);",
          "List<Integer> order = new ArrayList<>();",
          "while (!queue.isEmpty()) {",
          "    int v = queue.poll();",
          "    order.add(v);",
          "    for (int w : graph.get(v)) {",
          "        if (--indeg[w] == 0) queue.add(w);",
          "    }",
          "}",
          "// order.size() < n 이면 고리가 있어요",
        ].join("\n"),
      },
    },
  },
  {
    id: "ga-when",
    title: "언제 떠올릴까?",
    analogy: "그룹 문제인지, 순서 문제인지, 연결 비용 문제인지부터 가려내요.",
    body: [
      "- 관계가 **하나씩 더해지며** '같은 그룹인가?', '고리가 생겼나?'를 물어요 → **유니온 파인드**",
      "- 관계가 **끊어지는** 순서가 주어져요 → 끝 상태에서 **거꾸로 합치기**",
      "- **모든 곳을 잇는** 최소 비용 → **크루스칼** (두 곳 사이 최단 경로는 다익스트라)",
      "- **먼저 해야 하는 일**, 선수 과목 → **위상 정렬**. 순서를 따라가며 걸리는 시간 같은 값을 채우면 DP가 돼요.",
      "",
      "관계가 다 주어지고 그룹 수를 한 번만 세면 DFS·BFS로도 충분해요.",
    ].join("\n"),
    illustration: "topo-order",
    keyPoints: ["늘어나는 관계 → 유니온 파인드", "모두 잇는 최소 비용 → 크루스칼", "먼저 할 일 → 위상 정렬"],
  },
];

export const GRAPH_ADVANCED_QUIZ: RecognitionQuestion[] = [
  {
    id: "ga-q1",
    snippet:
      "학생 N명(N ≤ 100,000) 사이에 친구 관계가 하나씩 생겨요. 관계가 생길 때마다 '두 학생이 같은 친구 모임인가요?'라는 질문 Q개(Q ≤ 100,000)에 답하세요.",
    choices: ["dfs", "graph-advanced", "hash"],
    answer: "graph-advanced",
    signalIds: ["sig-merge-groups"],
    highlightPhrases: ["하나씩 생겨요", "같은 친구 모임인가요?"],
    explanation: "관계가 늘 때마다 DFS를 다시 하면 너무 느려요. 합치고(union) 대표를 비교(find)하는 유니온 파인드예요.",
  },
  {
    id: "ga-q2",
    snippet: "과목마다 먼저 들어야 하는 과목이 정해져 있어요. 모든 조건을 지키며 과목을 듣는 순서를 하나 구하세요.",
    choices: ["sorting", "graph-advanced", "greedy"],
    answer: "graph-advanced",
    signalIds: ["sig-prerequisites"],
    highlightPhrases: ["먼저 들어야 하는 과목"],
    explanation: "조건이 '무엇이 먼저'라는 화살표예요. 진입 차수가 0인 과목부터 꺼내는 위상 정렬이에요.",
  },
  {
    id: "ga-q3",
    snippet: "섬 N개 사이에 다리를 놓을 수 있는 후보와 비용이 있어요. 모든 섬이 이어지도록 다리를 놓는 최소 비용은?",
    choices: ["dijkstra", "graph-advanced", "dp"],
    answer: "graph-advanced",
    signalIds: ["sig-connect-all-cheap"],
    highlightPhrases: ["모든 섬이 이어지도록", "최소 비용"],
    explanation:
      "두 섬 사이의 가장 싼 길(다익스트라)이 아니라 모두를 잇는 비용이에요. 싼 다리부터 고리가 안 생기게 고르는 크루스칼이에요.",
  },
  {
    id: "ga-q4",
    snippet: "지도에 땅과 바다가 그려져 있어요. 상하좌우로 이어진 땅을 하나의 섬이라 할 때, 섬은 모두 몇 개인가요?",
    choices: ["graph-advanced", "dfs", "dp"],
    answer: "dfs",
    signalIds: ["sig-connected-group"],
    highlightPhrases: ["섬은 모두 몇 개"],
    explanation:
      "지도가 처음부터 다 주어지고 한 번만 세요. 땅을 만날 때마다 DFS로 한 섬을 칠하면 돼요. 유니온 파인드도 되지만 DFS가 더 간단해요.",
  },
  {
    id: "ga-q5",
    snippet:
      "작업마다 걸리는 시간과 먼저 끝나야 하는 작업이 있어요. 작업은 동시에 여러 개 할 수 있을 때, 모든 작업을 끝내는 가장 이른 시각은?",
    choices: ["graph-advanced", "binary-search", "heap"],
    answer: "graph-advanced",
    signalIds: ["sig-prerequisites"],
    highlightPhrases: ["먼저 끝나야 하는 작업"],
    explanation:
      "위상 정렬 순서로 작업을 보며 '이 작업이 끝나는 시각 = 선행 작업 중 가장 늦게 끝나는 시각 + 내 시간'을 채워요.",
  },
];
