import type { ConceptCard, RecognitionQuestion } from "@/types";

export const HASH_CARDS: ConceptCard[] = [
  {
    id: "hash-what",
    title: "이름표로 바로 찾는 사물함",
    analogy: "사물함 번호를 이름으로 계산할 수 있다면, 모든 사물함을 열어 보지 않고 내 칸으로 바로 가요.",
    body: [
      "리스트에서 `x in list`로 찾으면 앞에서부터 하나씩 비교해요. 10만 개면 최악 10만 번, 시간은 **O(N)** 걸려요.",
      "",
      "**해시**(hash)는 키를 **해시 함수**에 넣어 **칸 번호**를 계산하고, 그 칸만 봐요. 그래서 넣기·찾기·지우기가 평균 **O(1)** 시간에 끝나요.",
      "",
      "이 칸들의 모음을 **해시 테이블**이라고 하고, Python의 `set`·`dict`, JavaScript의 `Set`·`Map`, Java의 `HashSet`·`HashMap`이 모두 해시 테이블이에요.",
    ].join("\n"),
    illustration: "hash-lockers",
    keyPoints: ["키 → 해시 함수 → 칸 번호", "그 칸만 보니까 평균 O(1)", "set·dict가 해시 테이블이에요"],
  },
  {
    id: "hash-set-dict",
    title: "set은 '있다/없다', dict는 '키 → 값'",
    analogy: "set은 출석부(왔는지만 체크), dict는 사물함(이름표마다 물건이 들어 있어요).",
    body: [
      "- **set**: 값이 **있는지만** 기억해요. 중복은 저절로 사라져요.",
      "- **dict**(Map): 키마다 **값**을 붙여 둬요. 개수, 위치, 이름 같은 걸 저장해요.",
      "",
      'JavaScript는 일반 객체 `{}` 대신 `Map`을 쓰는 게 안전해요. 객체는 키를 모두 문자열로 바꾸기 때문에 `1`과 `"1"`이 같은 키가 돼요.',
    ].join("\n"),
    illustration: "hash-lockers",
    keyPoints: ["set: 있는지만", "dict: 키 → 값", "JS는 Set·Map을 써요"],
    code: {
      code: {
        python: [
          "seen = set()",
          'seen.add("cat")',
          'print("cat" in seen)      # True',
          "",
          "age = {}",
          'age["nodi"] = 3',
          'print(age.get("mimi", 0)) # 없으면 0',
        ].join("\n"),
        javascript: [
          "const seen = new Set();",
          'seen.add("cat");',
          'console.log(seen.has("cat"));        // true',
          "",
          "const age = new Map();",
          'age.set("nodi", 3);',
          'console.log(age.get("mimi") ?? 0);   // 없으면 0',
        ].join("\n"),
        java: [
          "Set<String> seen = new HashSet<>();",
          'seen.add("cat");',
          'System.out.println(seen.contains("cat"));         // true',
          "",
          "Map<String, Integer> age = new HashMap<>();",
          'age.put("nodi", 3);',
          'System.out.println(age.getOrDefault("mimi", 0));  // 없으면 0',
        ].join("\n"),
      },
    },
  },
  {
    id: "hash-collision",
    title: "충돌: 두 키가 같은 칸이면?",
    analogy: "사물함 번호가 겹치면 그 칸 안에 이름표를 줄 세워 넣어 두고, 찾을 때 그 줄만 훑어요.",
    body: [
      "칸 수는 정해져 있어서 서로 다른 키가 **같은 칸 번호**를 받을 수 있어요. 이것을 **충돌**이라고 해요.",
      "",
      "충돌한 키들은 한 칸에 **줄을 서서** 들어가요. 찾을 때는 그 칸의 줄만 비교하면 돼요.",
      "",
      "해시 함수가 키를 칸마다 **고르게** 나눠 주면 한 줄이 짧아서 평균 O(1)이 유지돼요. 언어가 알아서 칸 수를 늘려 주니 우리는 편하게 쓰면 돼요.",
      "",
      "단, 키는 **바뀌지 않는 값**이어야 해요. Python에서 리스트는 키가 될 수 없어서 `tuple`로 바꿔 써요.",
    ].join("\n"),
    illustration: "hash-lockers",
    keyPoints: ["다른 키가 같은 칸 = 충돌", "같은 칸 안에서만 줄을 훑어요", "키는 바뀌지 않는 값 (리스트 → 튜플)"],
  },
  {
    id: "hash-count",
    title: "개수 세기: count[x] += 1",
    analogy: "투표함을 열 때 후보 이름마다 바를 정(正) 자를 하나씩 그어 가요.",
    body: [
      "해시에서 가장 많이 쓰는 모양이에요. 한 번 훑으면서 키마다 개수를 1씩 늘려요.",
      "",
      "처음 보는 키는 값이 없으니까 **기본값 0**에서 시작하게 해요. 다 세고 나면 가장 큰 값, 1인 키, 두 dict 비교 같은 걸 바로 할 수 있어요.",
    ].join("\n"),
    illustration: "hash-tally",
    keyPoints: ["한 번 훑으면서 1씩 늘려요", "처음 보는 키는 0에서 시작", "O(N)으로 모든 개수를 구해요"],
    code: {
      code: {
        python: [
          "count = {}",
          "for x in items:",
          "    count[x] = count.get(x, 0) + 1",
          "",
          "# collections.Counter(items)도 같은 일을 해요",
        ].join("\n"),
        javascript: [
          "const count = new Map();",
          "for (const x of items) {",
          "  count.set(x, (count.get(x) ?? 0) + 1);",
          "}",
        ].join("\n"),
        java: [
          "Map<String, Integer> count = new HashMap<>();",
          "for (String x : items) {",
          "    count.put(x, count.getOrDefault(x, 0) + 1);",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "hash-when",
    title: "언제 해시를 떠올릴까?",
    analogy: "'이거 전에 본 적 있나?'를 매번 처음부터 뒤지고 있다면, 메모장을 옆에 두세요.",
    body: [
      "- **있는지 / 중복인지** 확인해요 → `set`",
      "- **각각 몇 번** 나왔는지 세요 → `dict`로 개수 세기",
      "- **합이 K인 짝**을 찾아요 → 지금 수 `x`의 짝 `K - x`가 이미 나왔는지 해시에 물어봐요",
      "- **같은 종류끼리** 묶어요 → 묶는 기준을 키로",
      "",
      "공통점: 이중 반복문(O(N²))으로 '앞에서 본 것'을 다시 뒤지는 코드를, 해시에 적어 두고 O(1)에 꺼내 보는 코드로 바꿔요.",
    ].join("\n"),
    illustration: "hash-tally",
    keyPoints: ["있는지·중복 → set", "개수·위치 → dict", "짝 찾기: K - x를 해시에 물어보기"],
  },
];

export const HASH_QUIZ: RecognitionQuestion[] = [
  {
    id: "hash-q1",
    snippet: "회원 N명(N ≤ 100,000)의 아이디 목록에서 같은 아이디가 두 번 이상 나오는지 확인하세요.",
    choices: ["hash", "stack", "backtracking"],
    answer: "hash",
    signalIds: ["sig-seen-before"],
    highlightPhrases: ["두 번 이상 나오는지", "N ≤ 100,000"],
    explanation: "본 아이디를 set에 넣어 두면 '이미 있나?'를 O(1)에 확인해요. 이중 반복문은 N이 크면 시간 초과예요.",
  },
  {
    id: "hash-q2",
    snippet: "투표 용지에 적힌 후보 이름 목록이 주어져요. 가장 많은 표를 받은 후보의 이름을 구하세요.",
    choices: ["queue-deque", "hash", "bfs"],
    answer: "hash",
    signalIds: ["sig-count-each"],
    highlightPhrases: ["가장 많은 표"],
    explanation: "이름마다 표 수를 세는 dict를 만들면 한 번 훑어서 끝나요. 개수 세기 패턴이에요.",
  },
  {
    id: "hash-q3",
    snippet: "정수 배열에서 더해서 정확히 target이 되는 두 수의 위치를 구하세요. 배열 길이는 최대 100,000이에요.",
    choices: ["hash", "backtracking", "recursion"],
    answer: "hash",
    signalIds: ["sig-pair-target"],
    highlightPhrases: ["더해서 정확히 target이 되는 두 수"],
    explanation: "모든 쌍을 보면 O(N²)이에요. 지나온 수를 dict에 적어 두고 target - x가 있는지 물어보면 O(N)이에요.",
  },
  {
    id: "hash-q4",
    snippet: "올바른 괄호 문자열인지 판단하세요. 괄호는 ( ) [ ] { } 세 종류예요.",
    choices: ["hash", "stack", "queue-deque"],
    answer: "stack",
    signalIds: ["sig-bracket-pair"],
    highlightPhrases: ["올바른 괄호"],
    explanation:
      "짝이 맞는지는 '가장 최근에 연 괄호'와 비교해야 해서 스택이에요. 괄호 종류를 짝짓는 표로 dict를 곁들일 수는 있어요.",
  },
  {
    id: "hash-q5",
    snippet: "단어 목록에서 글자 구성이 같은 단어끼리(예: listen, silent) 묶어 주세요.",
    choices: ["graph-representation", "backtracking", "hash"],
    answer: "hash",
    signalIds: ["sig-group-same"],
    highlightPhrases: ["글자 구성이 같은 단어끼리"],
    explanation: "글자를 정렬한 문자열을 키로 쓰면 같은 구성의 단어가 같은 키로 모여요. dict[키]에 리스트로 모아요.",
  },
];
