import type { ConceptCard, RecognitionQuestion } from "@/types";

export const HEAP_CARDS: ConceptCard[] = [
  {
    id: "heap-what",
    title: "가장 급한 것부터 꺼내는 줄",
    analogy: "응급실에서는 먼저 온 사람이 아니라 가장 아픈 사람이 먼저 진료실에 들어가요.",
    body: [
      "큐는 **먼저 온 순서**대로 꺼내요. **우선순위 큐**는 **가장 작은(또는 큰) 값**부터 꺼내요.",
      "",
      "우선순위 큐는 보통 **힙**으로 만들어요.",
      "",
      "- 가장 작은 값 **보기**: O(1)",
      "- **넣기**, 가장 작은 값 **꺼내기**: O(log N)",
      "",
      "새 값이 들어올 때마다 정렬을 다시 하면 O(N log N)씩 들지만, 힙은 log N만 들어요. '가장 작은 것 꺼내고, 새로 넣고'를 반복하는 문제에 딱 맞아요.",
    ].join("\n"),
    illustration: "heap-emergency",
    keyPoints: ["가장 작은 값부터 꺼내요", "넣기·꺼내기 O(log N), 보기 O(1)", "꺼내고 넣기를 반복할 때"],
  },
  {
    id: "heap-tree",
    title: "힙의 모양: 부모 ≤ 자식",
    analogy: "회사 조직도에서 윗사람이 늘 아랫사람보다 연차가 적은(더 급한) 것과 같아요.",
    body: [
      "힙은 **부모가 언제나 자식보다 작거나 같은** 트리예요. 그래서 맨 위(뿌리)가 가장 작은 값이에요.",
      "",
      "트리지만 **배열 하나**에 담아요. i번 칸의 자식은 `2i + 1`, `2i + 2`번, 부모는 `(i − 1) // 2`번이에요.",
      "",
      "- **넣기**: 맨 끝에 두고, 부모보다 작으면 자리를 바꾸며 **위로**",
      "- **꺼내기**: 맨 위를 빼고, 맨 끝 값을 맨 위로 올린 뒤, 더 작은 자식과 바꾸며 **아래로**",
      "",
      "트리의 높이가 log N이라 한 번에 log N번만 바꿔요.",
    ].join("\n"),
    illustration: "heap-tree",
    keyPoints: ["부모 ≤ 자식, 맨 위가 가장 작아요", "배열에 담아요 (자식 2i+1, 2i+2)", "위로·아래로 바꾸기는 log N번"],
  },
  {
    id: "heap-lang",
    title: "언어별로 힙 쓰기",
    analogy: "도구 상자에 이미 들어 있는 망치를 꺼내 쓰는 것처럼, 힙도 직접 만들 필요가 별로 없어요.",
    body: [
      "- **Python**: `heapq`는 **최소 힙**이에요. 최대 힙이 필요하면 값에 `-`를 붙여 넣어요.",
      "- **Java**: `PriorityQueue`가 최소 힙이고, `Collections.reverseOrder()`를 주면 최대 힙이에요.",
      "- **JavaScript**: 기본 힙이 없어요. 아래처럼 짧은 `MinHeap`을 직접 만들어 써요.",
      "",
      "튜플이나 배열을 넣으면 **첫 값으로 비교**하고, 같으면 다음 값으로 비교해요.",
    ].join("\n"),
    illustration: "heap-tree",
    keyPoints: ["Python heapq: 최소 힙, 최대는 −값", "Java PriorityQueue", "JS는 MinHeap을 직접"],
    code: {
      code: {
        python: [
          "import heapq",
          "",
          "h = []",
          "heapq.heappush(h, 5)",
          "heapq.heappush(h, 1)",
          "print(h[0])               # 1 (가장 작은 값 보기)",
          "print(heapq.heappop(h))   # 1 (꺼내기)",
          "",
          "heapq.heappush(h, -7)     # 최대 힙처럼: -를 붙여 넣고 꺼낼 때 다시 -",
        ].join("\n"),
        javascript: [
          "class MinHeap {",
          "  constructor() { this.a = []; }",
          "  get size() { return this.a.length; }",
          "  peek() { return this.a[0]; }",
          "  push(x) {",
          "    const a = this.a; a.push(x);",
          "    for (let i = a.length - 1; i > 0; ) {",
          "      const p = (i - 1) >> 1;",
          "      if (a[p] <= a[i]) break;",
          "      [a[p], a[i]] = [a[i], a[p]]; i = p;",
          "    }",
          "  }",
          "  pop() {",
          "    const a = this.a, top = a[0], last = a.pop();",
          "    if (a.length) {",
          "      a[0] = last;",
          "      for (let i = 0; ; ) {",
          "        const l = 2 * i + 1, r = l + 1; let m = i;",
          "        if (l < a.length && a[l] < a[m]) m = l;",
          "        if (r < a.length && a[r] < a[m]) m = r;",
          "        if (m === i) break;",
          "        [a[m], a[i]] = [a[i], a[m]]; i = m;",
          "      }",
          "    }",
          "    return top;",
          "  }",
          "}",
        ].join("\n"),
        java: [
          "PriorityQueue<Integer> h = new PriorityQueue<>();",
          "h.offer(5);",
          "h.offer(1);",
          "System.out.println(h.peek());   // 1 (보기)",
          "System.out.println(h.poll());   // 1 (꺼내기)",
          "",
          "PriorityQueue<Integer> max = new PriorityQueue<>(Collections.reverseOrder());",
        ].join("\n"),
      },
    },
  },
  {
    id: "heap-topk",
    title: "상위 K개와 힙 두 개",
    analogy: "반 대표 3명만 뽑는다면, 지금까지의 3명 중 가장 약한 사람만 신경 쓰면 돼요.",
    body: [
      "- **상위 K개**: 크기가 K인 **최소 힙**을 둬요. 새 값이 맨 위보다 크면 맨 위를 빼고 넣어요. 맨 위가 곧 **K번째로 큰 값**이에요.",
      "- **여러 줄 합치기**: 줄마다 맨 앞 값을 힙에 넣고, 가장 작은 것을 꺼낼 때 그 줄의 다음 값을 넣어요.",
      "- **중앙값**: 작은 절반은 **최대 힙**, 큰 절반은 **최소 힙**에 담고 크기를 맞춰요. 두 힙의 맨 위가 가운데예요.",
    ].join("\n"),
    illustration: "heap-tree",
    keyPoints: ["상위 K: 크기 K 최소 힙", "여러 줄: 줄마다 맨 앞만 힙에", "중앙값: 최대 힙 + 최소 힙"],
  },
  {
    id: "heap-when",
    title: "언제 힙을 떠올릴까?",
    analogy: "할 일 목록에서 늘 '가장 급한 일'만 보고 싶다면, 목록을 계속 다시 정렬하는 대신 급한 순 줄을 만들어요.",
    body: [
      "- **가장 작은(큰) 것을 계속 꺼내고**, 새 값이 계속 들어와요 → 힙",
      "- **상위 K개**, **K번째로 큰 값**을 물어요 → 크기 K 힙",
      "- 작업을 **도착 순서가 아니라 조건 순서**로 처리해요 (짧은 일 먼저, 이익 큰 일 먼저) → 힙",
      "- **지금까지의 중앙값** → 힙 두 개",
      "",
      "한 번만 가장 작은 값이 필요하면 `min`, 값이 다 주어진 뒤 한 번 정렬하면 되면 **정렬**이 더 간단해요.",
    ].join("\n"),
    illustration: "heap-emergency",
    keyPoints: ["꺼내고 넣기를 반복 → 힙", "상위 K → 크기 K 힙", "한 번이면 min이나 정렬"],
  },
];

export const HEAP_QUIZ: RecognitionQuestion[] = [
  {
    id: "heap-q1",
    snippet:
      "카드 묶음 N개가 있어요(N ≤ 100,000). 두 묶음을 합치면 두 묶음의 장수 합만큼 비교가 필요해요. 모두 하나로 합칠 때 비교 횟수의 최솟값을 구하세요.",
    choices: ["heap", "sorting", "dp"],
    answer: "heap",
    signalIds: ["sig-repeated-min"],
    highlightPhrases: ["모두 하나로 합칠 때"],
    explanation:
      "가장 작은 두 묶음을 합치고 그 결과를 다시 넣기를 반복해요. 매번 정렬하면 느리고, 힙이면 O(N log N)이에요.",
  },
  {
    id: "heap-q2",
    snippet: "점수가 하나씩 들어올 때마다 지금까지의 점수 중 3번째로 높은 점수를 출력하세요.",
    choices: ["heap", "stack", "binary-search"],
    answer: "heap",
    signalIds: ["sig-top-k"],
    highlightPhrases: ["들어올 때마다", "3번째로 높은 점수"],
    explanation: "크기 3인 최소 힙을 두면 맨 위가 3번째로 높은 점수예요. 새 점수가 더 크면 맨 위를 빼고 넣어요.",
  },
  {
    id: "heap-q3",
    snippet: "수를 하나 읽을 때마다 지금까지 읽은 수의 중앙값을 말하세요. (수는 최대 100,000개)",
    choices: ["sorting", "heap", "two-pointers"],
    answer: "heap",
    signalIds: ["sig-running-median"],
    highlightPhrases: ["지금까지 읽은 수의 중앙값"],
    explanation: "작은 절반은 최대 힙, 큰 절반은 최소 힙에 담아요. 매번 정렬하면 O(N² log N)이라 너무 느려요.",
  },
  {
    id: "heap-q4",
    snippet: "손님이 도착한 순서대로 한 명씩 창구에서 처리하세요.",
    choices: ["heap", "queue-deque", "hash"],
    answer: "queue-deque",
    signalIds: ["sig-arrival-order"],
    highlightPhrases: ["도착한 순서대로"],
    explanation: "도착 순서 그대로면 그냥 큐예요. 우선순위(급한 정도, 짧은 일)로 순서를 바꿀 때 힙을 써요.",
  },
  {
    id: "heap-q5",
    snippet:
      "작업마다 들어오는 시각과 걸리는 시간이 있어요. 일을 할 수 있을 때 기다리는 작업 중 가장 짧은 것부터 처리할 때 처리 순서를 구하세요.",
    choices: ["greedy", "heap", "sorting"],
    answer: "heap",
    signalIds: ["sig-repeated-min"],
    highlightPhrases: ["기다리는 작업 중 가장 짧은 것부터"],
    explanation:
      "기다리는 작업이 계속 바뀌고, 매번 가장 짧은 것을 꺼내야 해요. 들어온 작업을 힙에 넣고 가장 짧은 것부터 꺼내요.",
  },
];
