import type { ConceptCard, RecognitionQuestion } from "@/types";

export const IMPLEMENTATION_CARDS: ConceptCard[] = [
  {
    id: "sim-what",
    title: "규칙을 그대로 옮기기",
    analogy: "보드게임 설명서를 읽고 말을 한 칸씩 옮기는 것처럼, 적힌 규칙을 빠짐없이 따라 하면 돼요.",
    body: [
      "**구현·시뮬레이션** 문제는 특별한 알고리즘보다 **규칙을 정확히 코드로 옮기는 것**이 핵심이에요.",
      "",
      "1. **상태**를 정해요: 위치, 방향, 시간, 판의 모양처럼 매 순간 바뀌는 값",
      "2. **한 단계**에서 상태가 어떻게 바뀌는지 규칙을 적어요",
      "3. 끝날 때까지 한 단계씩 반복해요",
      "",
      "문제가 길고 조건이 많을수록 꼼꼼히 읽는 게 가장 중요해요.",
    ].join("\n"),
    illustration: "sim-rulebook",
    keyPoints: ["상태를 변수로", "한 단계의 규칙을 정확히", "조건을 빠짐없이 읽기"],
  },
  {
    id: "sim-direction",
    title: "방향은 번호와 배열로",
    analogy: "나침반의 방향에 0, 1, 2, 3 번호를 붙이면, 오른쪽으로 돌기는 번호에 1을 더하는 일이 돼요.",
    body: [
      "방향을 `0 = 위, 1 = 오른쪽, 2 = 아래, 3 = 왼쪽`으로 두고, 한 칸 움직일 때 바뀌는 줄·칸을 배열에 담아요.",
      "",
      "- 오른쪽으로 90도: `d = (d + 1) % 4`",
      "- 왼쪽으로 90도: `d = (d + 3) % 4`",
      "- 뒤로 돌기: `d = (d + 2) % 4`",
      "",
      "if 문을 방향마다 네 번 쓰지 않아도 돼서 실수가 줄어요. 움직이기 전에 **격자 밖·벽**인지 먼저 확인해요.",
    ].join("\n"),
    illustration: "sim-robot-grid",
    keyPoints: ["방향 = 0~3 번호", "오른쪽 (d + 1) % 4, 왼쪽 (d + 3) % 4", "움직이기 전에 밖·벽 확인"],
    code: {
      code: {
        python: [
          "dr = [-1, 0, 1, 0]   # 위 오른쪽 아래 왼쪽",
          "dc = [0, 1, 0, -1]",
          "",
          "r, c, d = 0, 0, 0",
          "for cmd in commands:",
          "    if cmd == 'L':",
          "        d = (d + 3) % 4",
          "    elif cmd == 'R':",
          "        d = (d + 1) % 4",
          "    else:",
          "        nr, nc = r + dr[d], c + dc[d]",
          "        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] != '#':",
          "            r, c = nr, nc",
        ].join("\n"),
        javascript: [
          "const dr = [-1, 0, 1, 0]; // 위 오른쪽 아래 왼쪽",
          "const dc = [0, 1, 0, -1];",
          "",
          "let r = 0, c = 0, d = 0;",
          "for (const cmd of commands) {",
          "  if (cmd === 'L') d = (d + 3) % 4;",
          "  else if (cmd === 'R') d = (d + 1) % 4;",
          "  else {",
          "    const nr = r + dr[d], nc = c + dc[d];",
          "    if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && grid[nr][nc] !== '#') {",
          "      r = nr;",
          "      c = nc;",
          "    }",
          "  }",
          "}",
        ].join("\n"),
        java: [
          "int[] dr = {-1, 0, 1, 0};   // 위 오른쪽 아래 왼쪽",
          "int[] dc = {0, 1, 0, -1};",
          "",
          "int r = 0, c = 0, d = 0;",
          "for (char cmd : commands.toCharArray()) {",
          "    if (cmd == 'L') d = (d + 3) % 4;",
          "    else if (cmd == 'R') d = (d + 1) % 4;",
          "    else {",
          "        int nr = r + dr[d], nc = c + dc[d];",
          "        if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && grid[nr].charAt(nc) != '#') {",
          "            r = nr;",
          "            c = nc;",
          "        }",
          "    }",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "sim-matrix",
    title: "판을 돌리고 옮기기",
    analogy: "종이에 그린 표를 시계 방향으로 돌리면, 맨 위 줄이 맨 오른쪽 세로줄이 돼요.",
    body: [
      "판을 바꾸는 문제는 **칸 하나가 어디로 가는지** 식으로 적으면 돼요.",
      "",
      "- 시계 방향 90도: `b[c][n − 1 − r] = a[r][c]` (n × m 판이 m × n 판이 돼요)",
      "- 네 번 돌리면 제자리라, k번 돌리기는 `k % 4`번만 하면 돼요",
      "- 달팽이 모양 채우기: 앞이 밖이거나 이미 채운 칸이면 오른쪽으로 돌아요",
      "",
      "헷갈리면 2 × 3 같은 작은 판을 손으로 그려 칸마다 확인해요.",
    ].join("\n"),
    illustration: "sim-robot-grid",
    keyPoints: ["칸이 어디로 가는지 식으로", "90도: b[c][n−1−r] = a[r][c]", "반복은 나머지로 줄이기"],
  },
  {
    id: "sim-time",
    title: "시각·날짜·문자열 다루기",
    analogy: "시계를 볼 때도 '몇 시 몇 분'을 '자정부터 몇 분'으로 바꾸면 더하고 빼기가 쉬워요.",
    body: [
      '- **시각**: `"HH:MM"`은 `시 × 60 + 분`으로 바꿔 계산하고, 다시 두 자리씩 채워 적어요. 하루를 넘기면 `% 1440`.',
      "- **날짜**: 달마다 날 수가 다르고, 윤년(4의 배수, 단 100의 배수는 빼고 400의 배수는 넣기)이면 2월이 29일이에요.",
      "- **문자열**: 공백·콜론으로 쪼개고(split), 숫자는 정수로 바꿔요.",
      "",
      "경계(자정, 연말, 빈 문자열)에서 가장 많이 틀려요.",
    ].join("\n"),
    illustration: "sim-rulebook",
    keyPoints: ["시각은 분으로 바꿔 계산", "윤년 규칙 확인", "두 자리 채우기와 경계 조심"],
  },
  {
    id: "sim-when",
    title: "언제, 어떻게 풀까?",
    analogy: "요리 레시피처럼 순서대로 따라 하되, 재료를 빠뜨리지 않게 미리 준비해요.",
    body: [
      "- 규칙이 길고 '이렇게 하면 이렇게 된다'가 이어져요 → **시뮬레이션**",
      "- 방향을 돌며 움직여요 → **방향 번호와 dr, dc 배열**",
      "- 형식이 있는 입력(시각, 날짜, 기록) → **쪼개서 숫자로 바꾸고 계산**",
      "",
      "풀기 전에 입력 크기로 단계 수를 어림해요. 단계가 너무 많으면 반복 규칙(나머지)이나 다른 알고리즘(최단 거리면 BFS)이 필요해요.",
    ].join("\n"),
    illustration: "sim-rulebook",
    keyPoints: ["긴 규칙 → 시뮬레이션", "방향 → dr, dc", "최단 거리를 물으면 BFS"],
  },
];

export const IMPLEMENTATION_QUIZ: RecognitionQuestion[] = [
  {
    id: "sim-q1",
    snippet:
      "애벌레가 N × N 판 위를 움직여요. 1초마다 머리를 한 칸 옮기고, 사과를 먹으면 몸이 한 칸 길어져요. 벽이나 자기 몸에 부딪히면 끝나요. 몇 초 만에 끝날까요?",
    choices: ["implementation", "bfs", "dp"],
    answer: "implementation",
    signalIds: ["sig-follow-rules"],
    highlightPhrases: ["1초마다 머리를 한 칸 옮기고", "부딪히면 끝나요"],
    explanation: "특별한 알고리즘 없이 규칙대로 1초씩 상태(머리·꼬리·방향)를 바꾸면 돼요. 시뮬레이션이에요.",
  },
  {
    id: "sim-q2",
    snippet:
      "로봇이 명령 L·R·F를 받아요. L은 왼쪽으로 90도, R은 오른쪽으로 90도 돌고, F는 앞으로 한 칸 가요. 마지막 위치는?",
    choices: ["dfs", "implementation", "greedy"],
    answer: "implementation",
    signalIds: ["sig-direction-turn"],
    highlightPhrases: ["왼쪽으로 90도", "오른쪽으로 90도"],
    explanation: "방향을 0~3 번호로 두고 dr, dc 배열로 움직이면 돼요.",
  },
  {
    id: "sim-q3",
    snippet: "미로의 출발점에서 도착점까지, 상하좌우로 움직여 최소 몇 칸 만에 갈 수 있나요?",
    choices: ["implementation", "bfs", "greedy"],
    answer: "bfs",
    signalIds: ["sig-shortest-steps"],
    highlightPhrases: ["최소 몇 칸"],
    explanation: "움직이는 규칙이 정해진 게 아니라 '가장 짧은 길'을 찾아야 해요. 가까운 곳부터 넓혀 가는 BFS예요.",
  },
  {
    id: "sim-q4",
    snippet: '주차장 입차·출차 기록이 "HH:MM 차량번호 IN/OUT" 꼴로 주어져요. 차마다 머문 시간으로 요금을 계산하세요.',
    choices: ["implementation", "sorting", "hash"],
    answer: "implementation",
    signalIds: ["sig-time-format"],
    highlightPhrases: ['"HH:MM 차량번호 IN/OUT"'],
    explanation:
      "기록을 쪼개고 시각을 분으로 바꿔 규칙대로 요금을 계산하는 구현 문제예요. 차별로 모으는 데 딕셔너리를 함께 써요.",
  },
  {
    id: "sim-q5",
    snippet: "N × M 판을 시계 방향으로 90도씩 K번 돌린 결과를 구하세요. (K ≤ 10⁹)",
    choices: ["implementation", "recursion", "two-pointers"],
    answer: "implementation",
    signalIds: ["sig-direction-turn"],
    highlightPhrases: ["시계 방향으로 90도씩 K번"],
    explanation: "칸 하나가 어디로 가는지 식으로 옮기면 돼요. 네 번 돌리면 제자리라 K % 4번만 돌려요.",
  },
];
