import type { ConceptCard, RecognitionQuestion } from "@/types";

export const QUEUE_DEQUE_CARDS: ConceptCard[] = [
  {
    id: "queue-what",
    title: "큐는 줄 서기예요",
    analogy: "빵집 앞에 줄을 서면, 먼저 온 사람이 먼저 빵을 받아요.",
    body: [
      "큐(queue)는 **먼저 넣은 것을 먼저 꺼내는** 자료구조예요. 이 규칙을 **FIFO**(First In, First Out)라고 불러요.",
      "",
      "넣는 곳은 **뒤(rear)**, 꺼내는 곳은 **앞(front)** 으로 서로 달라요. 한쪽 끝에서만 넣고 빼는 스택과 가장 큰 차이예요.",
    ].join("\n"),
    illustration: "queue-line",
    keyPoints: ["먼저 들어온 값이 먼저 나와요 (FIFO)", "넣기는 뒤, 꺼내기는 앞", "스택(LIFO)과 반대 순서"],
  },
  {
    id: "queue-ops",
    title: "enqueue · dequeue · front",
    analogy: "줄 맨 뒤에 서기, 맨 앞 사람 들여보내기, 맨 앞 사람 확인하기.",
    body: [
      "- **enqueue(x)**: 뒤에 x를 넣어요.",
      "- **dequeue()**: 앞에서 하나를 꺼내요.",
      "- **front()**: 앞에 있는 값을 보기만 해요.",
      "",
      "Python은 `collections.deque`를 큐로 써요. JavaScript에는 큐가 따로 없어서, 배열에 넣고 **앞 위치를 가리키는 번호(head)** 를 하나 두는 방법이 가장 간단해요.",
    ].join("\n"),
    illustration: "queue-line",
    keyPoints: ["enqueue = 뒤에 넣기", "dequeue = 앞에서 꺼내기", "front = 앞 보기 (꺼내지 않음)"],
    code: {
      code: {
        python: [
          "from collections import deque",
          "",
          "queue = deque()",
          "queue.append(3)        # enqueue",
          "queue.append(5)",
          "first = queue[0]       # front → 3",
          "x = queue.popleft()    # dequeue → 3",
        ].join("\n"),
        javascript: [
          "const queue = [];",
          "let head = 0;                // 맨 앞 위치",
          "queue.push(3);               // enqueue",
          "queue.push(5);",
          "const first = queue[head];   // front → 3",
          "const x = queue[head++];     // dequeue → 3",
        ].join("\n"),
      },
    },
  },
  {
    id: "queue-speed",
    title: "앞에서 꺼내기가 느리면 안 돼요",
    analogy: "맨 앞 사람이 나갈 때마다 줄 선 사람 모두가 한 걸음씩 앞으로 옮기면 너무 오래 걸려요.",
    body: [
      "Python 리스트의 `pop(0)`과 JavaScript 배열의 `shift()`는 맨 앞을 뺀 뒤 **나머지를 모두 한 칸씩 당겨요**. 그래서 한 번에 O(N)이고, 10만 번 반복하면 시간 초과가 나요.",
      "",
      "- Python: `deque.popleft()`는 O(1)이에요.",
      "- JavaScript: 원소를 옮기지 않고 **head 번호만 한 칸 옮기면** O(1)이에요.",
    ].join("\n"),
    illustration: "queue-line",
    keyPoints: ["list.pop(0) · shift()는 O(N)", "deque.popleft()는 O(1)", "JS는 head 번호를 옮겨서 꺼내요"],
  },
  {
    id: "deque-what",
    title: "덱은 양쪽 문이 열린 기차예요",
    analogy: "앞문으로도 뒷문으로도 타고 내릴 수 있는 기차를 떠올려 보세요.",
    body: [
      "덱(deque, double-ended queue)은 **앞과 뒤 양쪽에서** 넣고 뺄 수 있어요. 네 연산 모두 O(1)이에요.",
      "",
      "- `appendleft` / `append`: 앞 / 뒤에 넣기",
      "- `popleft` / `pop`: 앞 / 뒤에서 꺼내기",
      "",
      "뒤로만 넣고 앞으로만 빼면 큐, 한쪽으로만 넣고 빼면 스택처럼 쓸 수 있어요.",
    ].join("\n"),
    illustration: "deque-train",
    keyPoints: ["양쪽 끝 모두 넣고 빼기 O(1)", "큐처럼도, 스택처럼도 쓸 수 있어요", "Python은 collections.deque"],
    code: {
      code: {
        python: [
          "from collections import deque",
          "",
          "d = deque([2, 3])",
          "d.appendleft(1)   # [1, 2, 3]",
          "d.append(4)       # [1, 2, 3, 4]",
          "d.popleft()       # 1 → [2, 3, 4]",
          "d.pop()           # 4 → [2, 3]",
        ].join("\n"),
        javascript: [
          "// 가운데에서 시작하는 배열 + head·tail 번호로 만든 덱",
          "const slots = new Array(2 * 1000 + 1);",
          "let head = 1000, tail = 1000;   // [head, tail) 구간이 덱",
          "slots[--head] = 1;              // 앞에 넣기",
          "slots[tail++] = 4;              // 뒤에 넣기",
          "const front = slots[head++];    // 앞에서 꺼내기",
          "const back = slots[--tail];     // 뒤에서 꺼내기",
        ].join("\n"),
      },
    },
  },
  {
    id: "queue-when",
    title: "언제 큐·덱을 떠올릴까?",
    analogy: "번호표 순서대로 부르는 은행 창구, 한 바퀴씩 돌아가며 하는 놀이.",
    body: [
      "- **도착한 순서대로 처리**: 먼저 온 것이 먼저 나가요 → 큐",
      "- **돌아가며 차례대로**: 앞에서 꺼내 다시 뒤로 보내요 → 큐",
      "- **양쪽 끝에서 넣고 빼기**: 앞뒤를 모두 다뤄요 → 덱",
      "- **최근 k개 / 연속한 k칸**: 새 값은 뒤로 들어오고 오래된 값은 앞에서 빠져요 → 큐·덱",
      "",
      '뒤에서 배울 **BFS**도 "가까운 곳부터 차례대로" 방문하려고 큐를 써요.',
    ].join("\n"),
    illustration: "deque-train",
    keyPoints: ["'도착 순서' · '차례대로'는 큐", "'양쪽 끝'은 덱", "가장 최근 것부터라면 큐가 아니라 스택"],
  },
];

export const QUEUE_DEQUE_QUIZ: RecognitionQuestion[] = [
  {
    id: "queue-q1",
    snippet: "프린터에 문서가 들어온 순서대로 인쇄해요. 각 문서의 인쇄가 끝나는 시각을 구하세요.",
    choices: ["stack", "queue-deque", "recursion"],
    answer: "queue-deque",
    signalIds: ["sig-arrival-order"],
    highlightPhrases: ["들어온 순서대로"],
    explanation: "먼저 들어온 문서가 먼저 인쇄돼요(FIFO). 큐에 넣고 앞에서부터 꺼내면 돼요.",
  },
  {
    id: "queue-q2",
    snippet:
      "N명이 원 모양으로 앉아 있어요. 맨 앞 사람은 과자를 하나 먹고 줄의 맨 뒤로 가요. 과자를 다 먹은 사람은 빠져요. 빠지는 순서를 구하세요.",
    choices: ["queue-deque", "stack", "dfs"],
    answer: "queue-deque",
    signalIds: ["sig-arrival-order"],
    highlightPhrases: ["맨 앞 사람", "맨 뒤로 가요"],
    explanation: "앞에서 꺼내 뒤로 보내는 '돌아가며 차례대로' 흐름이에요. 큐로 그대로 옮길 수 있어요.",
  },
  {
    id: "queue-q3",
    snippet: "카드 뭉치의 맨 위나 맨 아래에서 한 장씩 뽑을 수 있어요. 뽑은 카드의 합이 가장 크게 되도록 하세요.",
    choices: ["stack", "backtracking", "queue-deque"],
    answer: "queue-deque",
    signalIds: ["sig-both-ends"],
    highlightPhrases: ["맨 위나 맨 아래에서"],
    explanation: "양쪽 끝에서 모두 꺼내야 해요. 앞뒤를 O(1)로 다루는 덱의 신호예요.",
  },
  {
    id: "queue-q4",
    snippet: "웹 브라우저의 뒤로 가기 버튼을 누르면 가장 최근에 방문한 페이지부터 거꾸로 돌아가요.",
    choices: ["queue-deque", "stack", "bfs"],
    answer: "stack",
    signalIds: ["sig-latest-first"],
    highlightPhrases: ["가장 최근에 방문한 페이지부터"],
    explanation: "가장 최근 것이 먼저 나오는 LIFO예요. 먼저 온 순서가 아니라서 큐가 아니라 스택이에요.",
  },
  {
    id: "queue-q5",
    snippet: "센서 기록에서 연속한 k개 값마다 가장 큰 값을 구하세요. 기록은 최대 10만 개예요.",
    choices: ["queue-deque", "recursion", "stack"],
    answer: "queue-deque",
    signalIds: ["sig-recent-window"],
    highlightPhrases: ["연속한 k개 값마다 가장 큰 값"],
    explanation:
      "창이 한 칸씩 움직이며 새 값은 뒤로 들어오고 오래된 값은 앞에서 빠져요. 덱에 최댓값 후보만 남기면 O(N)이에요.",
  },
];
