import type { ConceptCard, RecognitionQuestion } from "@/types";

export const SORTING_CARDS: ConceptCard[] = [
  {
    id: "sorting-what",
    title: "줄을 세우면 보이는 것들",
    analogy: "뒤죽박죽인 학생들을 키 순서로 세우면, 누가 세 번째로 큰지, 키가 비슷한 친구가 누구인지 한눈에 보여요.",
    body: [
      "**정렬**은 값을 정해진 순서(작은 것부터, 이름 순 …)로 늘어놓는 거예요.",
      "",
      "정렬해 두면 문제가 쉬워지는 경우가 많아요.",
      "",
      "- 크기가 비슷한 값끼리 **옆에 붙어요**. 가장 가까운 두 값은 이웃끼리만 비교하면 돼요.",
      "- **K번째로 작은 값**은 K번째 자리에 있어요.",
      "- 같은 값끼리 모여서 중복을 찾기 쉬워요.",
      "",
      "언어가 주는 정렬은 시간이 **O(N log N)** 걸려서, 10만 개도 순식간에 끝나요.",
    ].join("\n"),
    illustration: "sorting-bars",
    keyPoints: ["비슷한 값이 옆에 붙어요", "K번째 값은 K번째 자리에", "내장 정렬은 O(N log N)"],
  },
  {
    id: "sorting-builtin",
    title: "내장 정렬과 정렬 기준",
    analogy: "선생님이 '점수 높은 순, 같으면 이름 순'이라고 규칙만 말하면, 줄 세우기는 도우미가 해 줘요.",
    body: [
      "정렬은 직접 짜지 않고 **언어가 주는 정렬**을 쓰면 돼요. 우리는 **무엇을 기준으로** 할지만 정해요.",
      "",
      "- Python: `key=`에 기준을 튜플로 적어요. 내림차순은 숫자에 `-`를 붙여요.",
      "- JavaScript: 비교 함수가 **음수면 a가 먼저**예요. 비교 함수 없이 `sort()`하면 **숫자도 글자로 비교**해서 `[10, 9]`가 그대로예요!",
      "- Java: `Comparator`로 기준을 이어 붙여요.",
      "",
      "세 언어의 정렬은 모두 **안정 정렬**이라, 기준이 같은 값은 원래 순서를 지켜요.",
    ].join("\n"),
    illustration: "sorting-bars",
    keyPoints: ["기준만 정하면 돼요", "JS는 숫자 정렬에 비교 함수 필수", "같으면 원래 순서 유지 (안정 정렬)"],
    code: {
      code: {
        python: [
          'players = [("mimi", 90), ("nodi", 95), ("toto", 90)]',
          "",
          "# 점수 높은 순, 같으면 이름 순",
          "players.sort(key=lambda p: (-p[1], p[0]))",
          "",
          "nums = [10, 9, 1]",
          "nums.sort()        # [1, 9, 10]",
        ].join("\n"),
        javascript: [
          'const players = [["mimi", 90], ["nodi", 95], ["toto", 90]];',
          "",
          "// 점수 높은 순, 같으면 이름 순",
          "players.sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));",
          "",
          "const nums = [10, 9, 1];",
          "nums.sort((a, b) => a - b);   // [1, 9, 10]",
        ].join("\n"),
        java: [
          'String[] names = {"mimi", "nodi", "toto"};',
          "int[] scores = {90, 95, 90};",
          "Integer[] order = {0, 1, 2};",
          "",
          "// 점수 높은 순, 같으면 이름 순",
          "Arrays.sort(order, Comparator",
          "    .comparingInt((Integer i) -> -scores[i])",
          "    .thenComparing(i -> names[i]));",
          "",
          "int[] nums = {10, 9, 1};",
          "Arrays.sort(nums);   // [1, 9, 10]",
        ].join("\n"),
      },
    },
  },
  {
    id: "sorting-insertion",
    title: "삽입 정렬: 카드 끼워 넣기",
    analogy: "손에 든 카드 사이로 새 카드를 한 장씩 알맞은 자리에 끼워 넣어요.",
    body: [
      "앞에서부터 한 장씩 뽑아서, 왼쪽의 이미 정렬된 카드들 사이 **알맞은 자리**에 끼워 넣어요. 자기보다 큰 카드는 한 칸씩 오른쪽으로 밀어요.",
      "",
      "최악에는 카드마다 앞쪽을 전부 밀어야 해서 시간이 **O(N²)** 걸려요. N = 10만이면 약 50억 번이라 너무 느려요.",
      "",
      "그래도 **거의 정렬된** 배열에서는 밀 일이 거의 없어서 빨라요. 옆끼리 바꾸는 횟수는 **순서가 뒤바뀐 쌍**의 수와 같아요.",
    ].join("\n"),
    illustration: "sorting-bars",
    keyPoints: ["뽑아서 알맞은 자리에 끼워 넣기", "최악 O(N²) — 큰 N에는 느려요", "거의 정렬된 배열에서는 빨라요"],
  },
  {
    id: "sorting-merge",
    title: "병합 정렬: 나누고 합치기",
    analogy: "정렬된 두 줄의 맨 앞 사람끼리 키를 비교해서, 작은 사람부터 새 줄로 보내요.",
    body: [
      "1. 배열을 **반으로** 나눠요. 한 칸이 될 때까지 계속 나눠요. (한 칸은 이미 정렬돼 있어요)",
      "2. 정렬된 두 절반을 **맨 앞끼리 비교**하며 작은 것부터 붙여서 합쳐요.",
      "",
      "나누는 단계가 log N번, 단계마다 N개를 합쳐서 전체 **O(N log N)** 시간이 걸려요.",
      "",
      "'정렬된 두 줄 합치기'는 따로 떼어서도 자주 쓰여요. 합칠 때 오른쪽 값이 먼저 나가면, 왼쪽에 남은 값들은 모두 그 값보다 커요. 이걸로 **순서가 뒤바뀐 쌍**을 셀 수 있어요.",
    ].join("\n"),
    illustration: "sorting-merge",
    keyPoints: ["반으로 나누고, 맨 앞끼리 비교하며 합쳐요", "항상 O(N log N)", "합치기 단계로 뒤바뀐 쌍도 세요"],
    code: {
      code: {
        python: [
          "def merge(left, right):",
          "    out, i, j = [], 0, 0",
          "    while i < len(left) and j < len(right):",
          "        if left[i] <= right[j]:",
          "            out.append(left[i]); i += 1",
          "        else:",
          "            out.append(right[j]); j += 1",
          "    return out + left[i:] + right[j:]",
        ].join("\n"),
        javascript: [
          "function merge(left, right) {",
          "  const out = [];",
          "  let i = 0, j = 0;",
          "  while (i < left.length && j < right.length) {",
          "    if (left[i] <= right[j]) out.push(left[i++]);",
          "    else out.push(right[j++]);",
          "  }",
          "  return out.concat(left.slice(i), right.slice(j));",
          "}",
        ].join("\n"),
        java: [
          "int[] merge(int[] left, int[] right) {",
          "    int[] out = new int[left.length + right.length];",
          "    int i = 0, j = 0, k = 0;",
          "    while (i < left.length && j < right.length) {",
          "        if (left[i] <= right[j]) out[k++] = left[i++];",
          "        else out[k++] = right[j++];",
          "    }",
          "    while (i < left.length) out[k++] = left[i++];",
          "    while (j < right.length) out[k++] = right[j++];",
          "    return out;",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "sorting-when",
    title: "언제 정렬을 떠올릴까?",
    analogy: "서랍 속 물건을 찾기 어려우면, 먼저 종류별·크기별로 정리부터 해요.",
    body: [
      "- '**~순으로, 같으면 ~순으로**' 나열하래요 → 정렬 기준을 정해요.",
      "- **가장 가까운 두 값, K번째 값**을 물어요 → 정렬하고 이웃·자리를 봐요.",
      "- **시작과 끝이 있는 구간**이 겹치는지 봐요 → 시작 순으로 정렬하고 훑어요.",
      "- 값의 **범위가 작아요** (점수 0~100) → 개수를 세는 계수 정렬도 가능해요.",
      "",
      "반대로 '있는지'만 확인하면 해시가 더 빨라요. 정렬은 **순서 정보가 필요할 때** 써요.",
    ].join("\n"),
    illustration: "sorting-merge",
    keyPoints: ["기준대로 나열 → 정렬 기준", "가까운 값·K번째 → 정렬 후 훑기", "구간 겹침 → 시작 순 정렬"],
  },
];

export const SORTING_QUIZ: RecognitionQuestion[] = [
  {
    id: "sorting-q1",
    snippet: "학생들을 점수가 높은 순으로, 점수가 같으면 이름의 사전 순으로 출력하세요.",
    choices: ["sorting", "hash", "stack"],
    answer: "sorting",
    signalIds: ["sig-order-rule"],
    highlightPhrases: ["점수가 높은 순으로, 점수가 같으면 이름의 사전 순으로"],
    explanation: "기준이 두 개인 정렬이에요. (−점수, 이름)을 정렬 키로 쓰면 한 번에 끝나요.",
  },
  {
    id: "sorting-q2",
    snippet: "회의 N개(N ≤ 100,000)의 시작·끝 시각이 주어져요. 겹치는 회의를 하나로 합쳐 남은 회의 시간표를 구하세요.",
    choices: ["bfs", "sorting", "hash"],
    answer: "sorting",
    signalIds: ["sig-intervals"],
    highlightPhrases: ["겹치는 회의를 하나로 합쳐"],
    explanation: "시작 시각 순으로 정렬하면 겹치는 회의끼리 이웃해요. 한 번 훑으며 끝 시각을 늘려 가요.",
  },
  {
    id: "sorting-q3",
    snippet: "정수 N개(N ≤ 100,000)에서 차이가 가장 작은 두 수의 차이를 구하세요.",
    choices: ["sorting", "backtracking", "queue-deque"],
    answer: "sorting",
    signalIds: ["sig-neighbor-after-sort"],
    highlightPhrases: ["차이가 가장 작은 두 수"],
    explanation: "모든 쌍은 약 50억 개예요. 정렬하면 가장 가까운 두 수는 반드시 이웃해서 N − 1쌍만 보면 돼요.",
  },
  {
    id: "sorting-q4",
    snippet: "단어 N개에서 같은 단어가 두 번 이상 나오는지 확인하세요. 순서는 필요 없어요.",
    choices: ["sorting", "hash", "dfs"],
    answer: "hash",
    signalIds: ["sig-seen-before"],
    highlightPhrases: ["두 번 이상 나오는지", "순서는 필요 없어요"],
    explanation: "정렬해도 풀리지만, 순서가 필요 없으면 set에 넣으며 확인하는 해시가 O(N)으로 더 빨라요.",
  },
  {
    id: "sorting-q5",
    snippet: "줄 선 사람들이 옆 사람과 자리를 바꿔 키 순서로 서려고 해요. 최소 몇 번 바꿔야 하나요? (N ≤ 100,000)",
    choices: ["bfs", "stack", "sorting"],
    answer: "sorting",
    signalIds: ["sig-inversions"],
    highlightPhrases: ["옆 사람과 자리를 바꿔", "최소 몇 번"],
    explanation: "바꾸는 횟수는 순서가 뒤바뀐 쌍의 수와 같아요. 병합 정렬의 합치기 단계로 O(N log N)에 셀 수 있어요.",
  },
];
