import type { ConceptCard, RecognitionQuestion } from "@/types";

export const TWO_POINTERS_CARDS: ConceptCard[] = [
  {
    id: "tp-what",
    title: "손가락 두 개로 훑기",
    analogy: "책장 양 끝에 손가락을 하나씩 대고, 조건에 맞춰 한쪽씩 안으로 옮겨요.",
    body: [
      "**두 포인터**는 배열 위에 **위치 표시(포인터) 두 개**를 두고, 조건에 따라 한쪽씩 움직이며 답을 찾는 방법이에요.",
      "",
      "두 개를 모두 짝지어 보면 O(N²)이지만, 포인터는 **한 방향으로만** 움직여서 각 칸을 몇 번만 봐요. 그래서 시간이 **O(N)** 걸려요.",
      "",
      "- **양 끝에서 좁히기**: 정렬된 배열의 합 찾기, 물통 넓이",
      "- **같은 방향**: 읽는 손가락과 쓰는 손가락, 부분 수열 확인",
      "- **창(윈도우)**: 연속 구간을 늘였다 줄이며 조건 맞추기",
    ].join("\n"),
    illustration: "tp-squeeze",
    keyPoints: ["포인터 두 개를 한 방향으로만 움직여요", "모든 쌍 O(N²) → O(N)", "양 끝 · 같은 방향 · 창"],
  },
  {
    id: "tp-opposite",
    title: "양 끝에서 좁히기",
    analogy: "시소 양 끝에 앉은 두 친구: 한쪽이 무거우면 그쪽이 한 칸 안으로 들어와요.",
    body: [
      "**정렬된** 배열에서 합이 target인 두 수를 찾을 때:",
      "",
      "- 합이 **작으면** 왼쪽 포인터를 오른쪽으로 (더 큰 수로)",
      "- 합이 **크면** 오른쪽 포인터를 왼쪽으로 (더 작은 수로)",
      "",
      "왼쪽 수를 키우는 대신 오른쪽 수를 키울 방법은 없어요. 이미 가장 오른쪽이니까요. 그래서 버린 쌍들 중에 답이 있을 수 없어요.",
    ].join("\n"),
    illustration: "tp-squeeze",
    keyPoints: ["정렬이 먼저", "작으면 L++, 크면 R--", "만나면 끝"],
    code: {
      code: {
        python: [
          "l, r = 0, len(a) - 1",
          "while l < r:",
          "    s = a[l] + a[r]",
          "    if s == target:",
          "        return [l, r]",
          "    if s < target:",
          "        l += 1",
          "    else:",
          "        r -= 1",
        ].join("\n"),
        javascript: [
          "let l = 0, r = a.length - 1;",
          "while (l < r) {",
          "  const s = a[l] + a[r];",
          "  if (s === target) return [l, r];",
          "  if (s < target) l++;",
          "  else r--;",
          "}",
        ].join("\n"),
        java: [
          "int l = 0, r = a.length - 1;",
          "while (l < r) {",
          "    int s = a[l] + a[r];",
          "    if (s == target) return new int[] {l, r};",
          "    if (s < target) l++;",
          "    else r--;",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "tp-window",
    title: "창(슬라이딩 윈도우): 늘이고 줄이기",
    analogy: "기차 창문으로 풍경을 볼 때, 창틀이 한 칸씩 옆으로 미끄러져요.",
    body: [
      "**연속 구간**을 창이라고 생각해요.",
      "",
      "- **고정 길이 k**: 오른쪽에 하나 넣고 왼쪽에서 하나 빼며 창을 옮겨요. 합을 매번 새로 더하지 않아요.",
      "- **길이가 변하는 창**: 오른쪽 끝을 늘려 조건을 채우고, 채워지면 왼쪽 끝을 줄여 가장 짧게(또는 길게) 만들어요.",
      "",
      "오른쪽·왼쪽 끝 모두 **앞으로만** 가니까, 칸마다 한 번 들어오고 한 번 나가서 O(N)이에요.",
      "",
      "단, 창을 늘리면 합이 커진다는 성질(**모든 수가 양수**)이 필요해요. 음수가 있으면 누적 합 + 해시를 써요.",
    ].join("\n"),
    illustration: "tp-window",
    keyPoints: ["고정 창: 넣고 빼며 옮기기", "변하는 창: 늘여서 채우고 줄여서 다듬기", "양수일 때만 쓸 수 있어요"],
    code: {
      code: {
        python: [
          "l, total, best = 0, 0, float('inf')",
          "for r, x in enumerate(a):",
          "    total += x                  # 오른쪽 늘리기",
          "    while total >= S:",
          "        best = min(best, r - l + 1)",
          "        total -= a[l]           # 왼쪽 줄이기",
          "        l += 1",
        ].join("\n"),
        javascript: [
          "let l = 0, total = 0, best = Infinity;",
          "for (let r = 0; r < a.length; r++) {",
          "  total += a[r];                // 오른쪽 늘리기",
          "  while (total >= S) {",
          "    best = Math.min(best, r - l + 1);",
          "    total -= a[l++];            // 왼쪽 줄이기",
          "  }",
          "}",
        ].join("\n"),
        java: [
          "int l = 0, total = 0, best = Integer.MAX_VALUE;",
          "for (int r = 0; r < a.length; r++) {",
          "    total += a[r];                // 오른쪽 늘리기",
          "    while (total >= S) {",
          "        best = Math.min(best, r - l + 1);",
          "        total -= a[l++];          // 왼쪽 줄이기",
          "    }",
          "}",
        ].join("\n"),
      },
    },
  },
  {
    id: "tp-same-direction",
    title: "같은 방향: 읽는 손가락과 쓰는 손가락",
    analogy: "받아쓰기 공책 두 권: 한 권을 읽으면서 틀리지 않은 문장만 다른 권에 옮겨 적어요.",
    body: [
      "두 포인터가 **같은 방향**으로 가는 경우도 있어요.",
      "",
      "- **중복 없애기 · 0 뒤로 보내기**: 읽는 손가락은 매번 앞으로, 쓰는 손가락은 남길 값이 나올 때만 앞으로. 새 배열 없이 제자리에서 걸러요.",
      "- **부분 수열인가?**: s의 손가락은 글자가 맞을 때만, t의 손가락은 매번 앞으로.",
      "",
      "두 손가락 모두 되돌아가지 않아서 O(N + M)이에요.",
    ].join("\n"),
    illustration: "tp-window",
    keyPoints: ["읽기는 매번, 쓰기는 남길 때만", "순서를 지키며 걸러 내기", "되돌아가지 않아요"],
  },
  {
    id: "tp-when",
    title: "언제 두 포인터를 떠올릴까?",
    analogy: "모든 사람과 한 번씩 악수하는 대신, 줄을 세우고 양 끝부터 짝을 지어요.",
    body: [
      "- **정렬된** 배열에서 **두 수의 합·차**, 양 끝의 넓이 → 양 끝에서 좁히기",
      "- **연속 구간** + '합이 S 이상인 가장 짧은', '종류가 K개 이하인 가장 긴' → 창",
      "- 순서를 지키며 **제자리에서** 거르기, 부분 수열 → 같은 방향",
      "",
      "정렬이 안 돼 있고 위치를 그대로 알려 줘야 하면 **해시**가, 음수가 섞인 구간 합이면 **누적 합 + 해시**가 더 잘 맞아요.",
    ].join("\n"),
    illustration: "tp-squeeze",
    keyPoints: ["정렬 + 두 수 → 양 끝", "연속 구간 + 조건 → 창", "음수 구간 합은 해시로"],
  },
];

export const TWO_POINTERS_QUIZ: RecognitionQuestion[] = [
  {
    id: "tp-q1",
    snippet:
      "오름차순으로 정렬된 N개의 수(N ≤ 100,000)에서 합이 정확히 X가 되는 두 수의 위치를 구하세요. 추가 메모리는 거의 쓰지 마세요.",
    choices: ["two-pointers", "backtracking", "dp"],
    answer: "two-pointers",
    signalIds: ["sig-sorted-pair-ends"],
    highlightPhrases: ["오름차순으로 정렬된", "합이 정확히 X가 되는 두 수"],
    explanation: "정렬돼 있으니 양 끝에서 합을 비교하며 좁혀 오면 O(N)이에요. 해시도 되지만 메모리를 더 써요.",
  },
  {
    id: "tp-q2",
    snippet: "양의 정수 N개(N ≤ 100,000)가 있어요. 합이 S 이상인 연속 부분 수열 중 가장 짧은 것의 길이를 구하세요.",
    choices: ["binary-search", "two-pointers", "bfs"],
    answer: "two-pointers",
    signalIds: ["sig-contiguous-window"],
    highlightPhrases: ["양의 정수", "합이 S 이상인 연속 부분 수열 중 가장 짧은"],
    explanation: "양수라서 창을 늘리면 합이 커지고 줄이면 작아져요. 늘였다 줄이는 창으로 O(N)이에요.",
  },
  {
    id: "tp-q3",
    snippet: "정수 N개(음수 포함)에서 합이 정확히 K인 연속 구간의 개수를 구하세요.",
    choices: ["two-pointers", "hash", "greedy"],
    answer: "hash",
    signalIds: ["sig-subarray-sum"],
    highlightPhrases: ["음수 포함", "합이 정확히 K인 연속 구간의 개수"],
    explanation: "음수가 있으면 창을 늘려도 합이 커진다는 보장이 없어서 창이 안 돼요. 누적 합의 개수를 해시에 세요.",
  },
  {
    id: "tp-q4",
    snippet: "문자열 s가 문자열 t의 부분 수열인지(순서를 지키며 몇 글자를 골라 만들 수 있는지) 판단하세요.",
    choices: ["two-pointers", "dp", "stack"],
    answer: "two-pointers",
    signalIds: ["sig-in-place"],
    highlightPhrases: ["부분 수열인지"],
    explanation: "t를 훑으며 s의 다음 글자와 같을 때만 s의 손가락을 옮기면 돼요. 같은 방향 두 포인터, O(N + M)이에요.",
  },
  {
    id: "tp-q5",
    snippet:
      "막대 N개의 높이가 주어질 때, 두 막대를 골라 그 사이에 물을 담아요. 담을 수 있는 물의 최대 양을 구하세요. (N ≤ 100,000)",
    choices: ["greedy", "two-pointers", "sorting"],
    answer: "two-pointers",
    signalIds: ["sig-sorted-pair-ends"],
    highlightPhrases: ["두 막대를 골라", "최대 양"],
    explanation: "양 끝에서 시작해 더 낮은 막대 쪽을 안으로 옮겨요. 낮은 쪽을 그대로 두면 넓이가 커질 수 없어서예요.",
  },
];
